module
public import Linear.HomogeneousRationalPullback
public import Mathlib.FieldTheory.IntermediateField.Adjoin.Algebra
@[expose] public section
noncomputable section
set_option autoImplicit false
namespace LinearStudy
variable {K F : Type*} [Field K] [Field F] [Algebra K F] {n : ℕ}

/-- The actual field generated by projective coordinate ratios. -/
def coordinateRatioField (x : Fin (n + 1) → F) : IntermediateField K F :=
  IntermediateField.adjoin K (Set.range (fun i : Fin n => x i.succ / x 0))

def coordinateRatioPolynomialMap (x : Fin (n + 1) → F) :
    MvPolynomial (Fin n) K →ₐ[K] F :=
  MvPolynomial.aeval (fun i => x i.succ / x 0)

theorem coordinateRatioField_essFiniteType (x : Fin (n + 1) → F) :
    Algebra.EssFiniteType K (coordinateRatioField (K := K) x) :=
  IntermediateField.essFiniteType_iff.mpr
    (IntermediateField.fg_adjoin_of_finite (Set.finite_range _))

theorem coordinateRatioPolynomialMap_mem (x : Fin (n + 1) → F)
    (P : MvPolynomial (Fin n) K) :
    coordinateRatioPolynomialMap x P ∈ coordinateRatioField (K := K) x := by
  let z : Fin n → coordinateRatioField (K := K) x := fun i =>
    ⟨x i.succ / x 0, IntermediateField.subset_adjoin K _ ⟨i, rfl⟩⟩
  have he : (coordinateRatioField (K := K) x).val.comp (MvPolynomial.aeval z) =
      coordinateRatioPolynomialMap x := by
    apply MvPolynomial.algHom_ext
    intro i
    simp [coordinateRatioPolynomialMap, z]
  rw [← he]
  exact (MvPolynomial.aeval z P).property

theorem coordinateRatioPolynomialMap_homogeneous (x : Fin (n + 1) → F)
    (hx : x 0 ≠ 0) (H : MvPolynomial (Fin (n + 1)) K)
    {m : ℕ} (hH : H.IsHomogeneous m) :
    coordinateRatioPolynomialMap x (affineChartPolynomialMap H) =
      (x 0)⁻¹ ^ m * MvPolynomial.aeval x H := by
  change (MvPolynomial.aeval (fun i : Fin n => x i.succ / x 0))
    (affineChartPolynomialMap H) = _
  rw [← AlgHom.comp_apply, affineChartPolynomialMap_comp_aeval]
  have hv : Fin.cases 1 (fun i : Fin n => x i.succ / x 0) =
      (fun i : Fin (n + 1) => (x 0)⁻¹ * x i) := by
    funext i
    cases i using Fin.cases with
    | zero => simp [hx]
    | succ j => simp [div_eq_mul_inv, mul_comm]
  rw [hv, homogeneous_aeval_smul hH]

end LinearStudy
