module

public import Linear.Primitive
public import Mathlib.LinearAlgebra.Matrix.Adjugate
public import Mathlib.RingTheory.Ideal.Operations

/-!
# The multivariable determinant-annihilation step

For equations H = M x the adjugate identity puts det(M) in the annihilator
of the coordinate ideal in R/(H). This is the first, purely algebraic part
of the coefficient-determinant/socle route. It does not claim that det(M)
is nonzero or identify it with the derivative Jacobian.
-/

@[expose] public section
noncomputable section
namespace LinearStudy

variable {R : Type*} [CommRing R] {ι : Type*} [Fintype ι] [DecidableEq ι]

/-- A matrix relation over any commutative ring implies determinant
annihilation, including rings with zero divisors. -/
theorem determinant_mul_coordinate_of_relation (M : Matrix ι ι R)
    (x : ι → R) (hx : M.mulVec x = 0) (i : ι) : M.det * x i = 0 := by
  have h := congrArg (fun v => M.adjugate.mulVec v) hx
  rw [Matrix.mulVec_mulVec, Matrix.adjugate_mul, Matrix.smul_mulVec,
    Matrix.one_mulVec, Matrix.mulVec_zero] at h
  exact congrFun h i

/-- The same determinant annihilates the ideal generated by every
coordinate, rather than only the individual coordinate elements. -/
theorem determinant_annihilates_coordinate_ideal (M : Matrix ι ι R)
    (x : ι → R) (hx : M.mulVec x = 0) :
    Annihilates (Ideal.span (Set.range x)) M.det := by
  rw [annihilates_iff_mem_annihilator]
  apply Submodule.mem_annihilator.mpr
  intro a ha
  change M.det * a = 0
  induction ha using Submodule.span_induction with
  | mem a ha =>
      obtain ⟨i, rfl⟩ := ha
      exact determinant_mul_coordinate_of_relation M x hx i
  | zero => simp
  | add a b ha hb hza hzb => simp [mul_add, hza, hzb]
  | smul a b hb hzb =>
      change M.det * (a * b) = 0
      calc
        M.det * (a * b) = a * (M.det * b) := by ring
        _ = 0 := by rw [hzb, mul_zero]

/-- Pass an actual equation H_i = sum_j M_ij x_j to its quotient and
obtain the determinant-annihilation identity there. No regular-sequence
or nonvanishing assumption is hidden in this statement. -/
theorem coefficientDeterminant_annihilates_quotient
    (H x : ι → R) (M : Matrix ι ι R)
    (hH : M.mulVec x = H) :
    let J := Ideal.span (Set.range H)
    Annihilates (Ideal.span (Set.range (fun i => Ideal.Quotient.mk J (x i))))
      (Ideal.Quotient.mk J M.det) := by
  let J := Ideal.span (Set.range H)
  let f := Ideal.Quotient.mk J
  have hz : (fun i => f (H i)) = 0 := by
    funext i
    apply Ideal.Quotient.eq_zero_iff_mem.mpr
    exact Ideal.subset_span (Set.mem_range_self i)
  have hm : (M.map f).mulVec (fun i => f (x i)) = 0 := by
    funext i
    change (M.map f).mulVec (f ∘ x) i = 0
    rw [← f.map_mulVec M x i, hH]
    exact congrFun hz i
  have hd := determinant_annihilates_coordinate_ideal (M.map f) (fun i => f (x i)) hm
  have hdet : f M.det = (M.map f).det := f.map_det M
  rw [← hdet] at hd
  exact hd

end LinearStudy
