module
public import Mathlib.FieldTheory.IntermediateField.Adjoin.Basic
@[expose] public section
noncomputable section
set_option autoImplicit false
set_option backward.isDefEq.respectTransparency false
namespace LinearStudy

/-- The image of the WHOLE field generated by E and t is exactly
the field generated by the actual coefficient image and the actual image of t. -/
theorem fieldEndomorphism_simple_fieldRange
    {k F : Type*} [Field k] [Field F] [Algebra k F]
    (E : IntermediateField k F) (t : F) (φ : F →ₐ[k] F)
    (hgen : IntermediateField.adjoin E {t} = ⊤) :
    φ.fieldRange =
      (IntermediateField.adjoin (E.map φ) {φ t}).restrictScalars k := by
  have hg : IntermediateField.adjoin k ((E : Set F) ∪ {t}) = ⊤ := by
    calc
      IntermediateField.adjoin k ((E : Set F) ∪ {t}) =
          (IntermediateField.adjoin E ({t} : Set F)).restrictScalars k :=
        (IntermediateField.restrictScalars_adjoin k E ({t} : Set F)).symm
      _ = ⊤ := by rw [hgen]; rfl
  rw [IntermediateField.restrictScalars_adjoin]
  calc
    φ.fieldRange = (⊤ : IntermediateField k F).map φ :=
      AlgHom.fieldRange_eq_map φ
    _ = (IntermediateField.adjoin k ((E : Set F) ∪ {t})).map φ := by rw [hg]
    _ = IntermediateField.adjoin k (φ '' ((E : Set F) ∪ {t})) :=
      IntermediateField.adjoin_map k ((E : Set F) ∪ {t}) φ
    _ = IntermediateField.adjoin k ((E.map φ : Set F) ∪ {φ t}) := by
      rw [Set.image_union, Set.image_singleton, IntermediateField.coe_map]

end LinearStudy
