module
public import Linear.NativeDualHomogeneousFractionValues
public import Linear.NativeLocalizationScalarComparison
public import Linear.NativeGradedModuleAway
@[expose] public section
noncomputable section
set_option autoImplicit false
set_option backward.isDefEq.respectTransparency false
set_option backward.isDefEq.respectTransparency.types false
set_option maxHeartbeats 1600000
namespace LinearStudy
open CategoryTheory
universe u
variable {K R S : Type u} [Field K] [CommRing R] [CommRing S]
variable [Algebra K R] [Algebra K S] [Algebra R S] [IsScalarTower K R S]
variable (𝒜 : ℕ → Submodule K R) [GradedAlgebra 𝒜]
variable (𝓑 : ℕ → Submodule K S) [GradedAlgebra 𝓑]
variable [SetLike.GradedSMul 𝒜 𝓑] [Module.Finite R S]
attribute [local instance] coextensionGradedBaseModule
attribute [local instance] LocalizedModule.moduleOfIsLocalization
attribute [local instance] nativeHomogeneousAwayModuleScalar

/-- Restrict the actual native upper action to its normalization base. -/
@[instance_reducible] def nativeCoextensionNormalizationBaseModule :
    Module R ((ModuleCat.coextendScalars (algebraMap R S)).obj (ModuleCat.of R R)) :=
  Module.compHom _ (algebraMap R S)

attribute [local instance] nativeCoextensionNormalizationBaseModule

/-- The actual chart submodule of the original source, generated by its
degree-zero homogeneous fractions over the normalization base. -/
def nativeNormalizationSourceAwayZero (a : R) :
    Submodule (HomogeneousLocalization.Away 𝒜 a)
      (LocalizedModule (Submonoid.powers a) S) :=
  Submodule.span _ {z | ∃ n : ℕ, ∃ x : S, x ∈ 𝓑 n ∧
    z = LocalizedModule.mk x (⟨a^n, ⟨n,rfl⟩⟩ : Submonoid.powers a)}

/-- Evaluation on the actual generated degree-zero dual/source chart
modules lands in the ACTUAL homogeneous localization ring, not just in
the full localization. No canonical-module identification is assumed. -/
theorem finiteNativeDual_degreeZero_span_value
    (a : R) (ha : a ∈ 𝒜 1)
    (hinj : Function.Injective (algebraMap R (Localization.Away a))) :
    let D := (ModuleCat.restrictScalars (algebraMap R S)).obj
      ((ModuleCat.coextendScalars (algebraMap R S)).obj (ModuleCat.of R R))
    ∀ ell : LocalizedModule (Submonoid.powers a) D,
      ell ∈ nativeGradedModuleAwayZero 𝒜 (coextensionGradedPiece 𝒜 𝓑) a →
    ∀ x : LocalizedModule (Submonoid.powers a) S,
      x ∈ nativeNormalizationSourceAwayZero 𝒜 𝓑 a →
    ∃ z : HomogeneousLocalization.Away 𝒜 a,
      z.val = finiteNativeCoextensionLocalizationEquiv
        (Q := Localization.Away a) (Submonoid.powers a) hinj ell x := by
  let P := Submonoid.powers a
  let Q := Localization.Away a
  let A₀ := HomogeneousLocalization.Away 𝒜 a
  let D := (ModuleCat.restrictScalars (algebraMap R S)).obj
    ((ModuleCat.coextendScalars (algebraMap R S)).obj (ModuleCat.of R R))
  letI : Module Q (LocalizedModule P S) := LocalizedModule.moduleOfIsLocalization
  letI : Module Q (LocalizedModule P D) := LocalizedModule.moduleOfIsLocalization
  letI : IsScalarTower A₀ Q (LocalizedModule P S) :=
    IsScalarTower.of_compHom A₀ Q _
  letI : IsScalarTower A₀ Q (LocalizedModule P D) :=
    IsScalarTower.of_compHom A₀ Q _
  let E := finiteNativeCoextensionLocalizationEquiv (S := S) (Q := Q) P hinj
  let j := Algebra.linearMap A₀ Q
  let F : LocalizedModule P D →ₗ[A₀] (LocalizedModule P S →ₗ[Q] Q) := {
    toFun := E
    map_add' := E.map_add
    map_smul' := by
      intro c ell
      change E (algebraMap A₀ Q c • ell) = algebraMap A₀ Q c • E ell
      rw [← localizedModule_abstract_smul_eq_native P]
      exact E.map_smul (algebraMap A₀ Q c) ell }
  have hgen : ∀ n : ℕ, ∀ ell : D,
      ell ∈ coextensionGradedPiece 𝒜 𝓑 (n : ℤ) →
    ∀ x : LocalizedModule P S,
      x ∈ nativeNormalizationSourceAwayZero 𝒜 𝓑 a →
      E (LocalizedModule.mk ell (⟨a^n, ⟨n,rfl⟩⟩ : P)) x ∈ j.range := by
    intro n ell hell
    let f : LocalizedModule P S →ₗ[A₀] Q := {
      toFun := E (LocalizedModule.mk ell (⟨a^n, ⟨n,rfl⟩⟩ : P))
      map_add' := (E _).map_add
      map_smul' := by
        intro c x
        change (E (LocalizedModule.mk ell (⟨a^n, ⟨n,rfl⟩⟩ : P)))
          (algebraMap A₀ Q c • x) = algebraMap A₀ Q c • (E _) x
        rw [← localizedModule_abstract_smul_eq_native P]
        exact (E _).map_smul (algebraMap A₀ Q c) x }
    have hs : nativeNormalizationSourceAwayZero 𝒜 𝓑 a ≤ j.range.comap f := by
      apply Submodule.span_le.mpr
      rintro z ⟨d,x,hx,rfl⟩
      obtain ⟨w,hw⟩ := finiteNativeDual_degreeZero_fraction_value 𝒜 𝓑 a ha hinj n d ell hell x hx
      exact ⟨w,hw⟩
    exact fun x hx => hs hx
  dsimp only
  intro ell hell x hx
  suffices hv : E ell x ∈ j.range from hv
  induction hell using Submodule.span_induction with
  | mem ell hell =>
      obtain ⟨n,z,hz,rfl⟩ := hell
      exact hgen n z hz x hx
  | zero =>
      simpa only [map_zero, LinearMap.zero_apply] using j.range.zero_mem
  | add ell₁ ell₂ _ _ h₁ h₂ =>
      simpa only [map_add, LinearMap.add_apply] using j.range.add_mem h₁ h₂
  | smul c ell _ h =>
      have he : E (c • ell) = c • E ell := F.map_smul c ell
      simpa only [he, LinearMap.smul_apply] using j.range.smul_mem c h

end LinearStudy
