module
public import Linear.NativeHomogeneousAwayTwistFraction
public import Linear.GradedIntegerProjection
public import Mathlib.RingTheory.Localization.Module
@[expose] public section
noncomputable section
set_option autoImplicit false
set_option backward.isDefEq.respectTransparency false
set_option backward.isDefEq.respectTransparency.types false
set_option maxHeartbeats 1000000
namespace LinearStudy
variable {K S D : Type*} [Field K] [CommRing S] [Algebra K S]
variable [AddCommGroup D] [Module S D]
variable (𝓑 : ℕ → Submodule K S) [GradedAlgebra 𝓑]
attribute [local instance] LocalizedModule.moduleOfIsLocalization

/-- Restrict the ACTUAL full-localization action to the native degree-zero
chart ring. This is not a supplied chart-module model. -/
@[instance_reducible] def nativeHomogeneousAwayModuleScalar (a : S) :
    Module (HomogeneousLocalization.Away 𝓑 a)
      (LocalizedModule (Submonoid.powers a) D) :=
  Module.compHom _ (algebraMap (HomogeneousLocalization.Away 𝓑 a) (Localization.Away a))

attribute [local instance] nativeHomogeneousAwayModuleScalar

/-- Localize an actual module map and restrict scalars to the actual
Proj chart ring. -/
def nativeHomogeneousAwayLocalizedMap (a : S) (e : D →ₗ[S] S) :
    LocalizedModule (Submonoid.powers a) D →ₗ[HomogeneousLocalization.Away 𝓑 a]
      Localization.Away a := by
  let f := IsLocalizedModule.mapExtendScalars (Submonoid.powers a)
    (LocalizedModule.mkLinearMap (Submonoid.powers a) D)
    (Algebra.linearMap S (Localization.Away a)) (Localization.Away a) e
  exact {
    toFun := f
    map_add' := f.map_add
    map_smul' := fun z x => f.map_smul (algebraMap _ (Localization.Away a) z) x }

theorem nativeHomogeneousAwayLocalizedMap_mk (a : S) (e : D →ₗ[S] S)
    (x : D) (b : Submonoid.powers a) :
    nativeHomogeneousAwayLocalizedMap 𝓑 a e (LocalizedModule.mk x b) =
      IsLocalization.mk' (Localization.Away a) (e x) b := by
  change IsLocalizedModule.map (Submonoid.powers a)
    (LocalizedModule.mkLinearMap (Submonoid.powers a) D)
    (Algebra.linearMap S (Localization.Away a)) e (LocalizedModule.mk x b) = _
  rw [IsLocalizedModule.mk_eq_mk',IsLocalizedModule.map_mk',
    IsLocalization.mk'_eq_mk']

theorem nativeHomogeneousAwayLocalizedMap_injective (a : S) (e : D →ₗ[S] S)
    (he : Function.Injective e) :
    Function.Injective (nativeHomogeneousAwayLocalizedMap 𝓑 a e) :=
  IsLocalizedModule.map_injective (Submonoid.powers a)
    (LocalizedModule.mkLinearMap (Submonoid.powers a) D)
    (Algebra.linearMap S (Localization.Away a)) e he

variable [Module K D]
variable (𝒟 : ℤ → Submodule K D)

/-- The actual degree-zero chart module generated by the fractions
x/a^n with x in the ORIGINAL degree-n module piece. It is a submodule
of mathlib's actual localized module, not an abstract local substitute. -/
def nativeGradedModuleAwayZero (a : S) :
    Submodule (HomogeneousLocalization.Away 𝓑 a)
      (LocalizedModule (Submonoid.powers a) D) :=
  Submodule.span _ {z | ∃ n : ℕ, ∃ x : D, x ∈ 𝒟 (n : ℤ) ∧
    z = LocalizedModule.mk x (⟨a^n,⟨n,rfl⟩⟩ : Submonoid.powers a)}

/-- An actual degree-m homogeneous map takes the original degree-zero
chart module into the ACTUAL degree-m twist chart module. -/
theorem nativeGradedModuleAwayZero_map_mem_twist (a : S) (ha : a ∈ 𝓑 1)
    (m : ℕ) (e : D →ₗ[S] S)
    (hh : ∀ d : ℤ, ∀ x : D, x ∈ 𝒟 d →
      e x = gradedIntegerProjection 𝓑 (d+(m : ℤ)) (e x)) :
    nativeGradedModuleAwayZero 𝓑 𝒟 a ≤
      (nativeHomogeneousAwayTwistModule 𝓑 a m).comap
        (nativeHomogeneousAwayLocalizedMap 𝓑 a e) := by
  apply Submodule.span_le.mpr
  rintro z ⟨n,x,hx,rfl⟩
  change nativeHomogeneousAwayLocalizedMap 𝓑 a e _ ∈
    nativeHomogeneousAwayTwistModule 𝓑 a m
  rw [nativeHomogeneousAwayLocalizedMap_mk]
  have hdeg : e x ∈ 𝓑 (n+m) := by
    have h := hh (n : ℤ) x hx
    have hproj : gradedIntegerProjection 𝓑 ((n : ℤ)+(m : ℤ)) =
        gradedModuleProjection 𝓑 (n+m) := by
      rw [← Int.natCast_add]
      simp only [gradedIntegerProjection,Int.natCast_nonneg,ite_true,Int.toNat_natCast]
    rw [hproj] at h
    rw [h]
    exact (DirectSum.decompose 𝓑 (e x) (n+m)).property
  exact nativeHomogeneousAwayTwist_fraction_mem 𝓑 a ha m n (e x) hdeg

/-- The actual chart injection into the fixed positive twist, obtained
from the original homogeneous map by localization and restriction. -/
def nativeGradedModuleAwayTwistEmbedding (a : S) (ha : a ∈ 𝓑 1)
    (m : ℕ) (e : D →ₗ[S] S)
    (hh : ∀ d : ℤ, ∀ x : D, x ∈ 𝒟 d →
      e x = gradedIntegerProjection 𝓑 (d+(m : ℤ)) (e x)) :
    nativeGradedModuleAwayZero 𝓑 𝒟 a →ₗ[HomogeneousLocalization.Away 𝓑 a]
      nativeHomogeneousAwayTwistModule 𝓑 a m :=
  ((nativeHomogeneousAwayLocalizedMap 𝓑 a e).domRestrict
    (nativeGradedModuleAwayZero 𝓑 𝒟 a)).codRestrict _
      (fun x => nativeGradedModuleAwayZero_map_mem_twist 𝓑 𝒟 a ha m e hh x.property)

theorem nativeGradedModuleAwayTwistEmbedding_injective (a : S) (ha : a ∈ 𝓑 1)
    (m : ℕ) (e : D →ₗ[S] S) (he : Function.Injective e)
    (hh : ∀ d : ℤ, ∀ x : D, x ∈ 𝒟 d →
      e x = gradedIntegerProjection 𝓑 (d+(m : ℤ)) (e x)) :
    Function.Injective (nativeGradedModuleAwayTwistEmbedding 𝓑 𝒟 a ha m e hh) := by
  intro x y hxy
  apply Subtype.ext
  apply nativeHomogeneousAwayLocalizedMap_injective 𝓑 a e he
  exact congrArg Subtype.val hxy

end LinearStudy
