module

public import Linear.Thickening
public import Mathlib.RingTheory.PowerSeries.Order

/-! # The one-variable closed-fiber Jacobian theorem

Every nonzero H in K[[X]] with zero constant coefficient is a unit times a
positive power of X. Transport the actual derivative calculation through the
resulting equality of ideals. No perfect pairing or socle generator is assumed.
This does not establish the multivariable or relative-parameter theorem.
-/

@[expose] public section
noncomputable section
namespace LinearStudy

theorem oneVariable_unit_factorization {K : Type*} [Field K]
    (H : PowerSeries K) (hH : H ≠ 0) (h0 : PowerSeries.constantCoeff H = 0) :
    ∃ (s : ℕ) (u : PowerSeries K), IsUnit u ∧ H = u * PowerSeries.X ^ (s + 1) := by
  have hpos : 0 < H.order.toNat := by
    by_contra h
    have hz : H.order.toNat = 0 := Nat.eq_zero_of_not_pos h
    have hc := PowerSeries.coeff_order hH
    simp [hz, h0] at hc
  refine ⟨H.order.toNat - 1, H.divXPowOrder, ?_, ?_⟩
  · apply PowerSeries.isUnit_iff_constantCoeff.mpr
    apply isUnit_iff_ne_zero.mpr
    exact PowerSeries.constantCoeff_divXPowOrder_eq_zero_iff.not.mpr hH
  · rw [Nat.sub_add_cancel (Nat.succ_le_of_lt hpos), mul_comm]
    exact PowerSeries.X_pow_order_mul_divXPowOrder.symm

/-- An actual Artinian quotient with maximal nilradical, whose socle is
generated by the nonzero class of dH/dX. -/
theorem oneVariable_closedFiber_jacobian {K : Type*} [Field K] [CharZero K]
    (H : PowerSeries K) (hH : H ≠ 0) (h0 : PowerSeries.constantCoeff H = 0) :
    let I := Ideal.span {H}
    let A := PowerSeries K ⧸ I
    let delta := Ideal.Quotient.mk I (PowerSeries.derivative H)
    IsArtinianRing A ∧ (nilradical A).IsMaximal ∧
      (nilradical A).annihilator = Ideal.span {delta} ∧ delta ≠ 0 := by
  obtain ⟨s, u, hu, hfactor⟩ := oneVariable_unit_factorization H hH h0
  have hI : Ideal.span {H} = thickeningIdeal K s := by
    rw [hfactor, thickeningIdeal]
    exact Ideal.span_singleton_mul_left_unit hu _
  dsimp only
  rw [hI]
  change IsArtinianRing (Thickening K s) ∧
    (nilradical (Thickening K s)).IsMaximal ∧
    (nilradical (Thickening K s)).annihilator =
      Ideal.span {thickeningMk K s (PowerSeries.derivative H)} ∧
    thickeningMk K s (PowerSeries.derivative H) ≠ 0
  have hd : thickeningMk K s (PowerSeries.derivative H) =
      thickeningMk K s u * thickeningJacobian K s := by
    rw [hfactor]
    exact thickeningJacobian_unit_twist K s u
  have hu' := hu.map (thickeningMk K s)
  obtain ⟨hart, hmax, hann, hdelta⟩ := thickening_closedFiber_jacobian (K := K) s
  refine ⟨hart, hmax, ?_, ?_⟩
  · rw [hd, Ideal.span_singleton_mul_left_unit hu']
    exact hann
  · rw [hd]
    obtain ⟨v, hv⟩ := hu'
    rw [← hv]
    intro h
    apply hdelta
    have hh := congrArg (fun a => (↑v⁻¹ : Thickening K s) * a) h
    simpa [← mul_assoc] using hh

end LinearStudy
