module
public import Linear.ArtinianDiagonal
public import Linear.TensorSpecialization
public import Linear.DiagonalTrace
/-!
# Relative derivative Jacobian and algebraic trace

Over a general commutative base, assume the actual quotient coordinate
images are nilpotent. The true tensor diagonal ideal is generated by their
differences. Construct its determinant and compare multiplication with the
actual derivative Jacobian. A finite free perfect pairing makes the Jacobian
a trace multiple; over a reduced base with reduction map it annihilates the
nilradical. Nilpotent coordinates and a pairing are explicit here; later
assembly must derive them. Arbitrary coordinate shifts are not proved.
-/
@[expose] public section
noncomputable section
set_option backward.isDefEq.respectTransparency false
set_option backward.defeqAttrib.useBackward true
set_option maxHeartbeats 1500000
open scoped TensorProduct
namespace LinearStudy
variable {K : Type*} [CommRing K] {n : ℕ}
theorem relativePowerSeriesQuotient_diagonal_jacobian
    (H : Fin (n + 1) → MvPowerSeries (Fin (n + 1)) K)
    (hnil : ∀ i, IsNilpotent (Ideal.Quotient.mk (Ideal.span (Set.range H))
      (MvPowerSeries.X i))) :
    let Q := MvPowerSeries (Fin (n + 1)) K ⧸ Ideal.span (Set.range H)
    let q := Ideal.Quotient.mk (Ideal.span (Set.range H))
    ∃ M : Matrix (Fin (n + 1)) (Fin (n + 1)) (Q ⊗[K] Q),
      Annihilates (KaehlerDifferential.ideal K Q) M.det ∧
      Algebra.TensorProduct.lmul' K M.det =
        Matrix.det (fun i j => q (MvPowerSeries.pderiv j (H i))) := by
  classical
  let Q := MvPowerSeries (Fin (n + 1)) K ⧸ Ideal.span (Set.range H)
  let q := Ideal.Quotient.mkₐ K (Ideal.span (Set.range H))
  let l : Q →ₐ[K] Q ⊗[K] Q := Algebra.TensorProduct.includeLeft
  let r : Q →ₐ[K] Q ⊗[K] Q := Algebra.TensorProduct.includeRight
  let u := l.toRingHom.comp q.toRingHom
  let v := r.toRingHom.comp q.toRingHom
  let π := (Algebra.TensorProduct.lmul' K : Q ⊗[K] Q →ₐ[K] Q).toRingHom
  have hc : ∀ c, u (MvPowerSeries.C c) = v (MvPowerSeries.C c) := by
    intro c
    change l (q (MvPowerSeries.C c)) = r (q (MvPowerSeries.C c))
    have hq : q (MvPowerSeries.C c) = algebraMap K Q c := by
      simpa [MvPowerSeries.algebraMap_apply] using q.commutes c
    rw [hq, l.commutes, r.commutes]
  have hx : ∀ i, π (u (MvPowerSeries.X i)) = π (v (MvPowerSeries.X i)) := by
    intro i; simp [π, u, v, l, r]
  have hu : ∀ i, IsNilpotent (u (MvPowerSeries.X i)) := by
    intro i; exact (hnil i).map l.toRingHom
  have hv : ∀ i, IsNilpotent (v (MvPowerSeries.X i)) := by
    intro i; exact (hnil i).map r.toRingHom
  have hH : ∀ i, u (H i) = v (H i) := by
    intro i
    have hz : q (H i) = 0 := Ideal.Quotient.eq_zero_iff_mem.mpr
      (Ideal.subset_span (Set.mem_range_self i))
    change l (q (H i)) = r (q (H i))
    rw [hz, map_zero, map_zero]
  obtain ⟨M, hM, he, hd⟩ := powerSeries_diagonal_jacobian_matrix
    (R := K) (A := Q ⊗[K] Q) (B := Q) (ι := Fin (n + 1)) u v π hc hx hu hv H hH
  have hideal := powerSeries_tensor_diagonal_eq_coordinate_ideal q
    Ideal.Quotient.mk_surjective (fun i => hnil i)
  refine ⟨M, ?_, ?_⟩
  · rw [← hideal]
    exact hM
  change π M.det = Matrix.det (fun i j => q (MvPowerSeries.pderiv j (H i)))
  simpa [π, u, l] using hd

theorem relativePowerSeriesQuotient_jacobian_trace_multiple
    (H : Fin (n + 1) → MvPowerSeries (Fin (n + 1)) K)
    (hnil : ∀ i, IsNilpotent (Ideal.Quotient.mk (Ideal.span (Set.range H))
      (MvPowerSeries.X i)))
    [Module.Free K (MvPowerSeries (Fin (n + 1)) K ⧸ Ideal.span (Set.range H))]
    [Module.Finite K (MvPowerSeries (Fin (n + 1)) K ⧸ Ideal.span (Set.range H))]
    (p : PerfectMultiplicationPairing (B := K)
      (A := MvPowerSeries (Fin (n + 1)) K ⧸ Ideal.span (Set.range H))) :
    ∃ c, Ideal.Quotient.mk (Ideal.span (Set.range H))
      (Matrix.det (fun i j => MvPowerSeries.pderiv j (H i))) = c * traceElement p := by
  let Q := MvPowerSeries (Fin (n + 1)) K ⧸ Ideal.span (Set.range H)
  let q := Ideal.Quotient.mk (Ideal.span (Set.range H))
  obtain ⟨M, hM, hd⟩ := relativePowerSeriesQuotient_diagonal_jacobian H hnil
  refine ⟨pairingTensorEndEquiv p M.det 1, ?_⟩
  rw [q.map_det]
  change Matrix.det (fun i j => q (MvPowerSeries.pderiv j (H i))) = _
  rw [← hd]
  exact diagonal_annihilator_multiplication_eq_trace_multiple p M.det hM

theorem relativePowerSeriesQuotient_jacobian_annihilates_nilradical
    [IsReduced K] [StrongRankCondition K]
    (H : Fin (n + 1) → MvPowerSeries (Fin (n + 1)) K)
    (hnil : ∀ i, IsNilpotent (Ideal.Quotient.mk (Ideal.span (Set.range H))
      (MvPowerSeries.X i)))
    [Module.Free K (MvPowerSeries (Fin (n + 1)) K ⧸ Ideal.span (Set.range H))]
    [Module.Finite K (MvPowerSeries (Fin (n + 1)) K ⧸ Ideal.span (Set.range H))]
    (a : (MvPowerSeries (Fin (n + 1)) K ⧸ Ideal.span (Set.range H)) →ₐ[K] K)
    (ha : RingHom.ker a.toRingHom = nilradical
      (MvPowerSeries (Fin (n + 1)) K ⧸ Ideal.span (Set.range H)))
    (p : PerfectMultiplicationPairing (B := K)
      (A := MvPowerSeries (Fin (n + 1)) K ⧸ Ideal.span (Set.range H))) :
    Annihilates (nilradical (MvPowerSeries (Fin (n + 1)) K ⧸ Ideal.span (Set.range H)))
      (Ideal.Quotient.mk (Ideal.span (Set.range H))
        (Matrix.det (fun i j => MvPowerSeries.pderiv j (H i)))) := by
  obtain ⟨c, hc⟩ := relativePowerSeriesQuotient_jacobian_trace_multiple H hnil p
  have ht := traceElement_annihilates_kernel a ha p
  rw [ha] at ht
  rw [hc]
  intro x hx
  calc
    x * (c * traceElement p) = c * (x * traceElement p) := by ring
    _ = 0 := by rw [ht x hx, mul_zero]
end LinearStudy
