window.CourseLanguage.add({'魔方与群论 · 交互专题 ↗':'Rubik’s cube and group theory · interactive topic ↗'});
window.CourseLanguage.add({'韩士安、林磊、杜荣 编著':'Han Shi’an, Lin Lei and Du Rong','域的基本性质':'Basic properties of fields','搜索内容 / 日期':'Search topics / dates'});
window.CourseLanguage.add({'代数学':'Algebra','代数学 Ⅰ':'Algebra Ⅰ','即将到来':'Upcoming','教材小节导航':'Textbook section navigation','第一讲学习路径':'Lesson topics','2026 年秋季代数学 Ⅰ 课程安排，日期为北京时间':'Algebra Ⅰ schedule, Autumn 2026; Beijing time'});
window.CourseLanguage.add({'2026 秋季':'Autumn 2026','查看课程安排':'View the schedule','2026 年秋季抽象代数 I 课程安排，日期为北京时间':'Abstract Algebra Ⅰ schedule, Autumn 2026; Beijing time','关闭页面设置':'Close appearance settings','选择页面风格':'Choose an appearance'});
window.CourseScheduleEnglish=[
 ['Equivalence relations and partitions','Equivalence relations, partitions, equivalence classes and quotient sets.'],
 ['Groups and subgroups','Binary operations, group axioms, basic properties and integer powers; subgroup tests and generated subgroups.'],
 ['Group isomorphisms','Isomorphism invariants; constructing and ruling out isomorphisms; Cayley’s theorem.'],
 ['Cyclic groups','Classification, subgroups and generators of cyclic groups; element orders.'],
 ['Permutation and symmetric groups','Cycle decomposition, orders of permutations, parity and alternating groups.'],
 ['Cosets','Coset decompositions, index, Lagrange’s theorem and its limitations.'],
 ['Normal subgroups and quotient groups','The meaning of normality and why the quotient operation is well-defined.'],
 ['Homomorphisms and the first isomorphism theorem','Homomorphisms, kernels and images; proof of the first isomorphism theorem and examples of quotient groups.'],
 ['Direct products and an introduction to group actions','Internal and external direct products; group actions, orbits and stabilizers.'],
 ['Group actions and applications','Orbit–stabilizer theorem, conjugation, the class equation and the nontrivial center of a finite p-group.'],
 ['Sylow theorems and applications; group theory review','Statements on existence, conjugacy and counting; applications to normality and groups of small order.'],
 ['Why study ring theory?','Common structures in integers and polynomials; modular arithmetic, coding, equations and coordinate rings.'],
 ['Midterm examination: group theory','Sections 1.1–1.6 and 2.1–2.6 as covered in class. Emphasis on actions and Sylow applications; full Sylow proofs are not required.'],
 ['Rings, integral domains, fields and division rings','Distinguish structures through integers, matrices and polynomials.'],
 ['Ideals and quotient rings','How ideals differ from subrings; construct and calculate quotient rings.'],
 ['Ring homomorphisms','Kernels, the first isomorphism theorem and evaluation maps.'],
 ['Prime and maximal ideals','Characterize ideals through quotients in commutative rings with identity.'],
 ['Characteristic and prime fields; ring exercises','Characteristic and prime subfields; connect ideals, quotient rings and homomorphisms.'],
 ['Polynomial rings and fields of fractions','Formal polynomials and fractions; distinguish polynomial rings from rational function fields.'],
 ['Unique factorization domains','Units, associates, irreducibles and primes; examples where unique factorization fails.'],
 ['Principal ideal domains','Why principal ideal domains have unique factorization; greatest common divisors and Bézout identities.'],
 ['Euclidean domains','The Euclidean algorithm; relations among Euclidean, principal ideal and unique factorization domains.'],
 ['Polynomials over a unique factorization domain','Primitive polynomials, Gauss’s lemma, transfer of unique factorization and irreducibility examples.'],
 ['Basic properties of fields','Examples, inverses and zero divisors; finite integral domains are fields; characteristic and prime subfields.'],
 ['Course review','Review the semester and prepare for the final. Consultation times will be announced.'],
 ['Final examination','Date, time and room follow the university examination notice for weeks 17–18.']
];
window.CourseLanguage.add({
 '设置':'Settings','页面风格':'Appearance','为课程与讲义，选择一种阅读氛围。':'Choose an appearance for the course and lessons.','砂岩金粒':'Sand and gold','纸页青绿':'Paper and green','默认':'Default','原版':'Original','暗色砂岩 · 暖金细砂':'Dark sandstone · warm golden grains','延续开场动画的光与质感':'The light and texture of the opening animation','温润纸白 · 沉静青绿':'Warm paper · quiet green','保留熟悉的纸页阅读风格':'The original paper appearance','课程页与第一讲共用此设置。':'Shared by the course and lecture pages.','当前：砂岩金粒 · 选择自动保存':'Current: sand and gold · saved automatically','当前：纸页青绿 · 选择自动保存':'Current: paper and green · saved automatically','直接进入课程 · 跳过动画':'Enter the course · skip animation','凝聚成形':'Gathering into form','万象将启':'Ready to begin','准备动画':'Preparing animation','准备就绪':'Ready','点击或按空格 / 回车 · 开始动画':'Click, Space or Enter · start animation','复习周':'Review week','时间待定':'Time to be announced','全屏讲授 ↗':'Fullscreen ↗','退出授课 ↙':'Exit fullscreen ↙','课程安排 ↗':'Course ↗','概念与讲解':'Concepts and explanation','概念':'Concepts','互动':'Explore','当前主题':'Topic','← 上一主题':'← Previous topic','下一主题 →':'Next topic →','教材习题':'Textbook exercises','本节自测':'Section practice','可交互':'Interactive','核心语言':'Key definitions','试着发现':'Try this','教材范围与记号':'Textbook and notation','阅读范围':'Reading','记号约定':'Notation','等价关系与集合的分类':'Equivalence relations and partitions','群的概念':'The concept of a group','等价关系':'Equivalence relations','等价类':'Equivalence classes','集合的分类':'Partitions','代数运算':'Binary operations','群的公理':'Group axioms','对称与群':'Symmetries','基本性质':'Basic properties','方幂与指数':'Integer powers','群的判别':'Recognizing groups','第一讲 / § 1.1':'Lecture 1 / §1.1','第一讲 / § 1.2':'Lecture 1 / §1.2','§ 1.1 · 等价关系与集合的分类':'§1.1 · Equivalence relations and partitions','§ 1.2 · 群的概念':'§1.2 · The concept of a group'
});
window.CourseLanguage.add({
 '课程':'Courses','抽象代数':'Abstract Algebra','抽象代数 I':'Abstract Algebra Ⅰ','抽象代数':'Abstract Algebra','/ 2026 秋季':'/ Autumn 2026','2026—2027 学年第一学期':'Semester 1, 2026–2027','从群的对称性，到环的分解，再认识域的基本性质。':'From symmetries of groups to factorization in rings and the basic properties of fields.','孟晟':'Sheng Meng','2025 级数学非师范班':'Mathematics cohort 2025','教务课名：代数学 Ⅰ':'Registered course: Algebra Ⅰ','查看课程安排 ↓':'View the schedule ↓','课程概览 ↗':'Overview ↗','第一讲 · 交互讲义 ↗':'Lecture 1 · Interactive lesson ↗','观看对称开场 ↗':'Watch the opening ↗','学期周数':'Teaching weeks','周均学时':'Hours per week','总学时':'Total hours','2026—2027 · 秋季学期':'2026–2027 · Autumn semester','课程概览':'Course overview','以例子理解概念，以证明建立联系。':'Understand concepts through examples; connect them through proofs.','上课地点':'Classroom','闵四教 221':'Minhang Teaching Building 4, Room 221','华东师范大学 · 闵行校区':'East China Normal University · Minhang Campus','周一 / 第 3—4 节':'Monday / periods 3–4','第 1—3、5—16 周':'Weeks 1–3 and 5–16','第 4 周调至 10 月 10 日（周六）':'Week 4 moves to Saturday 10 October','双周周四 / 第 7—8 节':'Thursday in even weeks / periods 7–8','第 2、4、6、8、10、12、14、16 周':'Weeks 2, 4, 6, 8, 10, 12, 14, 16','课间说明':'Periods and breaks','第 3 节 09:50—10:35，第 4 节 10:40—11:25；第 7 节 13:50—14:35，第 8 节 14:50—15:35。以上时段包含课间休息，均为北京时间。':'Period 3: 09:50–10:35; period 4: 10:40–11:25; period 7: 13:50–14:35; period 8: 14:50–15:35. Class blocks include breaks. All times are Beijing time.','教材与范围':'Textbook and coverage',
 '环论开始前安排一次独立的课外导论“为什么要学环论”。覆盖前四章核心内容，包含 §4.5；用一次课（2 学时）介绍域的基本性质，结合 §3.2、§3.6 回顾与举例。第一章安排 5 次课，第二章安排 6 次课，重点讲授群作用及西罗定理的应用。西罗定理简述结论，不展开完整证明。§1.7、§2.7 自由群为拓展阅读，不列入本学期必讲范围。总学时按 18 周、周均 3 学时计，共 54 学时。':'A separate introduction, “Why study ring theory?”, precedes ring theory. The course covers core material in Chapters 1–4, including §4.5, and devotes one two-hour class to basic field properties using §§3.2 and 3.6. Chapter 1 has five classes and Chapter 2 has six, emphasizing group actions and Sylow applications. Sylow statements are covered without full proofs. Sections 1.7 and 2.7 on free groups are optional reading. The semester totals 54 hours over 18 weeks.',
 '01 / 群':'01 / Groups','02 / 群的进一步讨论':'02 / Further group theory','03—04 / 环论（含导论）':'03–04 / Ring theory, including introduction','期中考试 / 群论':'Midterm / Group theory','课程安排':'Course schedule','10.10 / 周六补课':'10 October / Saturday makeup class','第 4 周周一课程调至 10 月 10 日（周六）09:50—11:25；该周先上周四课，再上周六课。':'The Monday class in week 4 moves to Saturday 10 October, 09:50–11:25. The Thursday class comes first that week.','期中考试：':'Midterm examination:',
 '11 月 9 日（周一）09:50—11:25，闵四教 221。群论于 11 月 2 日讲授结束，留出一周复习；11 月 5 日先上环论导论。考试范围为 §1.1—§1.6、§2.1—§2.6 课堂讲授内容；重点包括群作用及西罗定理的应用，不要求西罗定理的完整证明。':'Monday 9 November, 09:50–11:25, Room 221, Minhang Teaching Building 4. Group theory ends on 2 November, leaving a week for review; ring theory begins with an introduction on 5 November. The examination covers §§1.1–1.6 and §§2.1–2.6 as taught, emphasizing group actions and Sylow applications. Full Sylow proofs are not required.',
 '全部':'All','第一章':'Chapter 1','第二章':'Chapter 2','第三章':'Chapter 3','第四章':'Chapter 4','期中考试':'Midterm','期末考试':'Final examination','搜索课程内容或日期':'Search topics or dates','按章节筛选':'Filter by chapter','课次':'Class','日期 / 教学周':'Date / week','时间 / 节次':'Time / periods','教材与教学内容':'Textbook and topics','学习重点':'Learning focus','日期':'Date','时间':'Time','教学内容':'Topics','国庆补课 · 补周一':'National Day makeup · Monday class','课外专题':'Supplementary topic','第一、二章':'Chapters 1–2','§ 3.2、3.6 回顾':'§§3.2, 3.6 revisited','具体安排另行通知':'Details to be announced','全课程':'Entire course','期末考核':'Final assessment','以学校通知为准':'Subject to the university notice','至':'to','第 17—18 周 · 校历考试周':'Weeks 17–18 · examination period','没有匹配的课程，请更换关键词或章节。':'No matching classes. Change the keywords or chapter.','教学内容按学习进度适当调整。第 1—24 次课均在闵行校区闵四教 221 上课；期末考试日期、时段及考场以学校通知为准。':'Topics may be adjusted to the class’s progress. Classes 1–24 meet in Room 221, Minhang Teaching Building 4. The final examination date, time and room follow the university notice.','孟晟 · 华东师范大学':'Sheng Meng · East China Normal University','返回个人主页 ↗':'Personal homepage ↗','选择讲解主题':'Choose a topic','课件内容':'Lesson content','页面设置':'Page settings','关闭设置':'Close settings','教材小节':'Textbook sections','概念上一页':'Previous concept page','概念下一页':'Next concept page','互动上一页':'Previous exploration page','互动下一页':'Next exploration page','观察尺度：整数到分类到商集':'View: integers, classes, quotient','选择代表元':'Choose a representative'
});
