import {chapters,ui,notation} from './notebook-content.js?v=3';
import {drawDiagram} from './diagrams.js?v=3';
import {statementMark} from '../spectral/statement-marks.js?v=153';
const R=String.raw,$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const safeStore={get(k,f){try{return localStorage.getItem(k)||f}catch{return f}},set(k,v){try{localStorage.setItem(k,v)}catch{}}};
let lang=safeStore.get('mhs-language','zh'),current=0,reached=0,line=0,entered=false;
let duration=+safeStore.get('mhs-duration','1000'),reduce=safeStore.get('mhs-reduce','false')==='true'||matchMedia('(prefers-reduced-motion: reduce)').matches;
let evolutionToken=0,graphState={},mathErrors=[],transitionSerial=0,graphAnimations=[],playTimer=0,playEpoch=0,hiddenAnimation=false;
const L=value=>Array.isArray(value)?value[lang==='zh'?0:1]:value||'',tr=k=>L(ui[k])||k;
const kind=c=>({definition:'D',theorem:'T',proposition:'P',construction:'D',example:'E',application:'E',goal:'T',foundation:'T'}[c.kind]||'P');
function math(tex,display=false){try{return katex.renderToString(tex,{displayMode:display,throwOnError:true,strict:'error',output:'htmlAndMathml',trust:false})}catch(e){mathErrors.push({tex,error:e.message});console.error('MHS mathematics:',e.message);return `<span class="math-error">${tex.replaceAll('<','&lt;')}</span>`}}
const inline=s=>L(s).replace(/\$([^$]+)\$/g,(_,tex)=>`<span class="math">${math(tex)}</span>`),display=s=>`<div class="math display">${math(s,true)}</div>`,ms=factor=>reduce?0:duration*factor;
function animateTo(el,keyframes,options={}){if(reduce)return Promise.resolve();const a=el.animate(keyframes,{duration,easing:'cubic-bezier(.22,.8,.22,1)',...options});return a.finished.catch(()=>{});}
const icons={home:'<path d="m3 10 9-7 9 7v10H15v-6H9v6H3Z"/>',settings:'<path d="M3 7h6m5 0h7M3 17h12m5 0h1"/><circle cx="11.5" cy="7" r="2.5"/><circle cx="17.5" cy="17" r="2.5"/>',fullscreen:'<path d="M4 4h16v16H4Z"/>'};
for(const b of $$('[data-icon]'))b.innerHTML=`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linejoin="round" aria-hidden="true">${icons[b.dataset.icon]}</svg>`;
const labels={settings:['设置','Settings'],theme:['面板风格','Panel style'],autoplay:['自动播放','Autoplay'],delay:['开始前等待','Start delay'],loop:['循环演示','Loop demonstration'],interval:['循环间隔','Loop interval'],parameters:['当前图示参数','Diagram parameters']};
function translateUI(){document.documentElement.lang=lang==='zh'?'zh-CN':'en';document.title=lang==='zh'?'混合 Hodge 结构 · 孟晟':'Mixed Hodge Structure · Sheng Meng';$$('[data-i18n]').forEach(el=>el.textContent=tr(el.dataset.i18n));$$('[data-label]').forEach(el=>el.textContent=L(labels[el.dataset.label]));$$('[data-action="language"]').forEach(b=>{b.textContent=lang==='zh'?'Eng':'中文';b.setAttribute('aria-label',lang==='zh'?'Switch to English':'切换为中文');});for(const b of $$('[data-action="cover"]'))b.setAttribute('aria-label',lang==='zh'?'返回封面':'Return to cover');for(const b of $$('[data-action="settings"]'))b.setAttribute('aria-label',lang==='zh'?'设置':'Settings');$('#sceneTitle').textContent=lang==='zh'?'混合 Hodge 结构':'Mixed Hodge Structure';$('#enter').textContent=lang==='zh'?'开始阅读':'Start reading';$('#more').textContent='More ↗';$('#closeProof').setAttribute('aria-label',lang==='zh'?'关闭证明':'Close proof');$('#closeSettings').setAttribute('aria-label',lang==='zh'?'关闭设置':'Close settings');$('#reduce').checked=reduce;$('#duration').value=duration;$('#durationValue').textContent=(duration/1000).toFixed(1)+' s';window.spectralThemeCursor?.sync(lang);syncFullscreen();}
function positionCard(instant=false){const pane=$('.notebook'),card=$('.card.current');if(!card||!entered)return;requestAnimationFrame(()=>{const h=pane.clientHeight,rect=card.getBoundingClientRect(),top=rect.top-pane.getBoundingClientRect().top+pane.scrollTop;const target=Math.max(18,Math.min(h*.47,h-rect.height-25));pane.scrollTo({top:Math.max(0,top-target),behavior:reduce||instant?'instant':'smooth'});});}
function renderCards(){const container=$('#cards');container.innerHTML='';let section='';chapters.forEach((c,i)=>{if(i>reached)return;const sec=c.no.split('.')[0];if(sec!==section){section=sec;const names={'0':['目标','Goal'],'1':['对象与滤过','Objects and filtrations'],'2':['收敛、退化与等变性','Convergence, degeneration and equivariance'],'3':['应用','Applications']};const h=document.createElement('h2');h.className='section-title';h.textContent=(sec==='0'?'':`§${sec} `)+L(names[sec]||['目标','Goal']);container.append(h);}const card=document.createElement('article');card.className='card'+(i===current?' current':'');card.dataset.index=i;const shown=i===current?line:c.formulas.length-1;card.innerHTML=`<button class="card-head"><span class="number">${c.no}</span>${statementMark(kind(c),lang==='en')}<span class="card-title-mini">${L(c.title)}</span></button><div class="card-body">${i===current&&c.intro?`<p>${inline(c.intro)}</p>`:''}${i===current&&c.tag?`<p class="card-tag">${L(c.tag)}</p>`:''}<div class="formula">${c.formulas.map((f,j)=>j<=shown?`<button class="formula-line ${i===current&&j===line?'current-line':''}" data-line="${j}" aria-label="${c.no} ${lang==='zh'?'条目':'item'} ${j+1}">${math(f,true)}</button>`:'').join('')}</div></div>`;card.querySelector('.card-head').onclick=()=>go(i,{line:Math.min(line,c.formulas.length-1)});card.querySelectorAll('[data-line]').forEach(b=>b.onclick=()=>go(i,{line:+b.dataset.line}));container.append(card);});renderRail();positionCard();}
function renderRail(){$('#readingRail').innerHTML=chapters.map((c,i)=>`<button class="rail-item ${i===current?'current':''} ${i===0||c.no.split('.')[0]!==chapters[i-1].no.split('.')[0]?'section-start':''}" aria-label="${c.no} ${L(c.title)}" ${i===current?'aria-current="step"':''} data-index="${i}"><span>${c.no} ${L(c.title)}</span></button>`).join('');$('#readingRail').querySelectorAll('button').forEach(b=>b.onclick=()=>go(+b.dataset.index));}
function initialGraphState(c){const base={n:3,p:1,route:'top'};if(c.graph==='complex')base.focus='both';if(c.graph==='pages')base.page=0;if(c.graph==='hodge'){base.w=2;base.ell=1}if(c.graph==='degeneration')base.r=2;if(c.graph==='equivariance')base.square='rho';return base;}
function graphTitle(){const names={comparison:['收敛 · 退化 · 等变性','CONVERGENCE · DEGENERATION · EQUIVARIANCE'],simplicial:['几何映射的交换图','GEOMETRIC COMMUTATION'],complex:['总复形的双次数','THE TOTAL COMPLEX'],filtration:['固定总次数的列滤过','COLUMN FILTRATION IN FIXED TOTAL DEGREE'],hodge:['纯分次商上的 Hodge 分解','HODGE TYPES ON A PURE GRADED QUOTIENT'],action:['拉回诱导的交换方块','THE PULLBACK SQUARE'],pages:['由滤过复形产生谱序列','FROM THE FILTERED COMPLEX TO ITS PAGES'],degeneration:['高阶微分与权重','HIGHER DIFFERENTIALS AND WEIGHTS'],convergence:['稳定页与总上同调的分次商','STABLE PAGE AND GRADED TOTAL COHOMOLOGY'],equivariance:['同一个代表元，两条路径','ONE REPRESENTATIVE, TWO PATHS'],representative:['闭总代表元的首列','LEADING COLUMN OF A CLOSED TOTAL COCHAIN'],example:['商空间中的分支交换','BRANCH EXCHANGE ON THE QUOTIENT'],descent:['真下降将比较传回 X','PROPER DESCENT BACK TO X']};return L(names[chapters[current].graph]);}
async function renderGraph(instant=false){const serial=++transitionSerial,holder=$('#diagram');const next=drawDiagram(chapters[current].graph,graphState,lang,tex=>math(notation(tex,chapters[current].id)));next.dataset.current='true';holder.setAttribute('aria-label',graphTitle());
// Preserve the currently composited image when an interaction interrupts a transition.
const old=[...holder.children].map(el=>({el,opacity:+getComputedStyle(el).opacity}));for(const a of graphAnimations)a.cancel();graphAnimations=[];
for(const {el,opacity}of old){el.style.opacity=opacity;delete el.dataset.current;}next.style.opacity=instant||reduce?'1':'0';holder.append(next);
if(instant||reduce){old.forEach(x=>x.el.remove());return;}const options={duration:ms(.72),easing:'cubic-bezier(.22,.8,.22,1)',fill:'forwards'};
for(const {el,opacity} of old)graphAnimations.push(el.animate([{opacity},{opacity:0}],options));graphAnimations.push(next.animate([{opacity:0},{opacity:1}],options));
await Promise.allSettled(graphAnimations.map(a=>a.finished));if(serial!==transitionSerial)return;
next.style.opacity='1';old.forEach(x=>x.el.remove());for(const a of graphAnimations)a.cancel();graphAnimations=[];
}
const button=(label,fn,selected=false)=>{const b=document.createElement('button');b.type='button';b.innerHTML=label;b.classList.toggle('selected',selected);b.setAttribute('aria-pressed',String(selected));b.addEventListener('click',fn);$('#controls').append(b);return b;};
function range(label,key,min,max){const wrap=document.createElement('label');wrap.innerHTML=`${inline(label)} <input type="range" aria-label="${L(label).replaceAll('$','')}" min="${min}" max="${max}" step="1" value="${graphState[key]}"><output>${graphState[key]}</output>`;wrap.querySelector('input').addEventListener('input',e=>{graphState[key]=+e.target.value;wrap.querySelector('output').textContent=e.target.value;if(key==='n'&&graphState.p>graphState.n){graphState.p=graphState.n;renderControls();}if(key==='n'){const pInput=$('#controls input[data-parameter="p"]');if(pInput)pInput.max=graphState.n;}renderGraph();});wrap.querySelector('input').dataset.parameter=key;$('#controls').append(wrap);}
function choose(key,value){if(key==='page')return formPage(value);graphState[key]=value;renderControls();renderGraph();}
async function formPage(target){const token=++evolutionToken;
 if(target<2||reduce){graphState.page=target;delete graphState.cohom;delete graphState.pending;$('#diagram').setAttribute('aria-busy','false');renderControls();renderGraph();return;}
 graphState.page=target-1;graphState.pending=target;graphState.cohom='kernel';$('#diagram').setAttribute('aria-busy','true');renderControls();await renderGraph();await new Promise(resolve=>setTimeout(resolve,ms(.25)));
 if(token!==evolutionToken)return;graphState.cohom='quotient';await renderGraph();await new Promise(resolve=>setTimeout(resolve,ms(.45)));
 if(token!==evolutionToken)return;delete graphState.cohom;delete graphState.pending;graphState.page=target;renderControls();await renderGraph();if(token===evolutionToken)$('#diagram').setAttribute('aria-busy','false');
}
function renderControls(){const g=chapters[current].graph;$('#controls').replaceChildren();const options=(key,items)=>items.forEach(([value,label])=>button(inline(label),()=>choose(key,value),graphState[key]===value));
if(g==='comparison'){button(inline(['查看证明主线','Follow the proof']),()=>go(1));}
if(g==='simplicial'){button(inline(['强调交换方块','Emphasize the square']),()=>replay());}
if(g==='complex'){options('focus',[['h',[R`横向 $\delta_1$`,R`Horizontal $\delta_1$`]],['v',[R`纵向 $\delta_2$`,R`Vertical $\delta_2$`]],['both',['双复形','Double complex']],['total',[R`总空间 $C^n$`,R`Total space $C^n$`]],['D',[R`总微分 $D$`,R`Total differential $D$`]]]);if(['total','D'].includes(graphState.focus))range([R`次数 $n$`,R`Degree $n$`],'n',1,3);}
if(['filtration','representative'].includes(g)){range([R`总次数 $n$`,R`Total degree $n$`],'n',1,4);range([R`列 $p$`,R`Column $p$`],'p',0,graphState.n);}
if(g==='convergence'){range([R`总次数 $n$`,R`Total degree $n$`],'n',1,4);range([R`列 $p$`,R`Column $p$`],'p',0,graphState.n);}
if(g==='hodge'){range([R`权重 $w$`,R`Weight $w$`],'w',0,3);range([R`Hodge 滤过 $\ell$`,R`Hodge level $\ell$`],'ell',0,4);}
if(g==='action'||g==='equivariance'){if(g==='equivariance')options('square',[['rho',[R`$\rho$ 的方块`,R`Square for $\rho$`]],['sigma',[R`$\sigma$ 的方块`,R`Square for $\sigma$`]],['alpha',[R`$\alpha$ 的方块`,R`Square for $\alpha$`]]]);button(inline(['先向右，再向下','Right, then down']),()=>traceRoute('top'),graphState.route==='top');button(inline(['先向下，再向右','Down, then right']),()=>traceRoute('bottom'),graphState.route==='bottom');}
if(g==='pages'){options('page',[[0,[R`$K$`,R`$K$`]],[1,[R`产生 $E_0$`,R`Form $E_0$`]],[2,[R`$H(d_0)\cong E_1$`,R`$H(d_0)\cong E_1$`]],[3,[R`$H(d_1)\cong E_2$`,R`$H(d_1)\cong E_2$`]]]);}
if(g==='degeneration')range([R`微分页数 $r$`,R`Differential page $r$`],'r',2,4);
if(g==='example'){button(inline(['原代表元','Original representative']),()=>choose('swap',false),!graphState.swap);button(inline([R`施加 $f_1^*$`,R`Apply $f_1^*$`]),()=>choose('swap',true),!!graphState.swap);}
if(g==='descent'){button(inline(['回看等变比较','Revisit equivariant comparison']),()=>go(9));button(inline(['打开原始 PDF','Open the source PDF']),()=>window.open('sources/MHS_DESCENT.pdf','_blank','noopener'));}}
async function replay(){const svg=$('#diagram .diagram-scene[data-current]');if(!svg)return;const edges=[...svg.querySelectorAll('[data-emphasis], [data-route]')];const chosen=edges.length?edges:[...svg.querySelectorAll('rect')];chosen.forEach(el=>{const from=+getComputedStyle(el).opacity;const rest=+(el.getAttribute('opacity')||1);for(const a of el.getAnimations())a.cancel();animateTo(el,[{opacity:from},{opacity:Math.max(.12,rest*.35),offset:.35},{opacity:rest}],{duration:ms(1.2)});});}
async function traceRoute(route){graphState.route=route;renderControls();await renderGraph();if(!entered||!['action','equivariance'].includes(chapters[current].graph))return;const svg=$('#diagram .diagram-scene[data-current]');if(!svg||reduce)return;
// A representative follows both sides of the same square. Fade the terminal point out continuously.
const drawing=svg.querySelector('svg');const dot=document.createElementNS('http://www.w3.org/2000/svg','circle');dot.setAttribute('cx','0');dot.setAttribute('cy','0');dot.setAttribute('r','5');dot.setAttribute('fill','#ffd078');dot.style.opacity='0';drawing.append(dot);
const points=route==='top'?[[205,122],[595,122],[595,332]]:[[205,122],[205,332],[595,332]];
await animateTo(dot,[{transform:`translate(${points[0][0]}px,${points[0][1]}px)`,opacity:0},{transform:`translate(${points[0][0]}px,${points[0][1]}px)`,opacity:1,offset:.08},{transform:`translate(${points[1][0]}px,${points[1][1]}px)`,opacity:1,offset:.46},{transform:`translate(${points[2][0]}px,${points[2][1]}px)`,opacity:1,offset:.83},{transform:`translate(${points[2][0]}px,${points[2][1]}px)`,opacity:0}],{duration:ms(2.2)});dot.remove();}
function renderProof(){const c=chapters[current],p=c.proof[Math.min(line,c.proof.length-1)];$('#proof').innerHTML=(p.formulas[0]?display(p.formulas[0]):'')+`<p>${inline(p.text)}</p>`;}
function openProof(){const c=chapters[current],isStatement=['goal','theorem','proposition','foundation','application'].includes(c.kind);$('#proofTitle').innerHTML=`${c.no} ${statementMark(kind(c),lang==='en')} ${L(c.title)}`;const setup=lang==='zh'?R`设 $X_\bullet$ 的各层为光滑射影复簇的有限不交并，$f_\bullet$ 为给定的单纯自映射。采用上述第一象限双复形 $(C^\bullet,D)$ 与列滤过 $F$，在单纯上同调上相应滤过记为 $L$。则有以下结论。`:R`Let each level of $X_\bullet$ be a finite disjoint union of smooth projective complex varieties, and let $f_\bullet$ be a given simplicial endomorphism. Use the preceding first-quadrant total complex $(C^\bullet,D)$ with column filtration $F$, transported to simplicial cohomology as $L$. Then the following conclusions hold.`;
const intro=c.id==='example'||c.id==='descent'?(c.intro?inline(c.intro):inline(c.tag)):isStatement?inline(setup):(c.intro?inline(c.intro):'');$('#proofDetail').innerHTML=`${intro?`<p>${intro}</p>`:''}${c.formulas.map(display).join('')}<p><strong>${lang==='zh'?(isStatement?'证明。':'说明。'):(isStatement?'Proof.':'Explanation.')}</strong></p>`+c.proof.map(p=>`<section class="proof-part"><h3>${L(p.title)}</h3>${p.formulas.map(display).join('')}<p>${inline(p.text)}</p></section>`).join('')+`<div class="source-note"><a href="sources/${c.source}.pdf#page=${c.page}" target="_blank" rel="noopener">${lang==='zh'?'参考笔记':'Reference note'} ↗</a><a href="../spectral/" target="_blank" rel="noopener">Spectral Sequence ↗</a></div>`;$('#proofDialog').showModal();$('#proofDetail').scrollTop=0;}
function stopPlayback(){clearTimeout(playTimer);playEpoch++;}
function schedulePlayback(){stopPlayback();hiddenAnimation=false;$('#diagram').style.opacity='1';$('#hideAnimation').hidden=true;if(!entered||reduce||!$('#autoplay').checked)return;const epoch=playEpoch;playTimer=setTimeout(()=>playDemo(epoch),+$('#delay').value*1000+duration*.72);}
async function playDemo(epoch){if(epoch!==playEpoch||!entered||hiddenAnimation)return;$('#hideAnimation').hidden=false;const type=chapters[current].graph;if(['action','equivariance'].includes(type))await traceRoute(graphState.route==='top'?'bottom':'top');else if(type==='pages')await formPage(((graphState.page||0)+1)%4);else if(type==='degeneration'){graphState.r=graphState.r===4?2:(graphState.r||2)+1;await renderGraph();}else await replay();if(epoch===playEpoch&&$('#loop').checked)playTimer=setTimeout(()=>playDemo(epoch),+$('#interval').value*1000+duration*1.3);}
function go(index,options={}){evolutionToken++;stopPlayback();current=Math.max(0,Math.min(chapters.length-1,index));line=options.line??0;line=Math.max(0,Math.min(chapters[current].formulas.length-1,line));reached=Math.max(reached,current);graphState=initialGraphState(chapters[current]);$('#diagram').setAttribute('aria-busy','false');renderCards();renderControls();renderProof();renderGraph(options.instant);history.replaceState(null,'',`#${chapters[current].id}`);schedulePlayback();}
function advance(delta){const last=chapters[current].formulas.length-1;if(delta>0){if(line<last)line++;else if(current<chapters.length-1)return go(current+1);else return;}else{if(line>0)line--;else if(current>0)return go(current-1,{line:chapters[current-1].formulas.length-1});else return;}renderCards();renderProof();schedulePlayback();}
async function showCover(){stopPlayback();entered=false;$('#cover').hidden=false;$('#app').inert=true;history.replaceState(null,'','#title');await animateTo($('#cover'),[{opacity:0},{opacity:1}],{duration:ms(.5)});$('#enter').focus({preventScroll:true});}
async function enter(){if(entered||$('#enter').disabled)return;entered=true;$('#app').inert=false;await animateTo($('#cover'),[{opacity:1},{opacity:0}],{duration:ms(.65)});$('#cover').hidden=true;history.replaceState(null,'',`#${chapters[current].id}`);positionCard(true);schedulePlayback();}
function syncFullscreen(){const active=!!document.fullscreenElement||document.body.classList.contains('immersive');$$('[data-action="fullscreen"]').forEach(b=>{b.setAttribute('aria-pressed',String(active));b.setAttribute('aria-label',lang==='zh'?(active?'退出全屏':'全屏'):(active?'Exit fullscreen':'Fullscreen'));});}
let fullscreenPending=false;async function fullscreen(){if(fullscreenPending)return;fullscreenPending=true;try{if(document.fullscreenElement)await document.exitFullscreen();else if(document.body.classList.contains('immersive'))document.body.classList.remove('immersive');else{try{if(!document.fullscreenEnabled)throw Error('unavailable');await document.documentElement.requestFullscreen();}catch{document.body.classList.add('immersive');}}}finally{fullscreenPending=false;syncFullscreen();}}
document.addEventListener('fullscreenchange',syncFullscreen);
$$('[data-action]').forEach(b=>b.onclick=()=>{if(b.dataset.action==='language'){lang=lang==='zh'?'en':'zh';safeStore.set('mhs-language',lang);translateUI();renderCards();renderControls();renderProof();renderGraph(true);}if(b.dataset.action==='cover')showCover();if(b.dataset.action==='settings')$('#settings').showModal();if(b.dataset.action==='fullscreen')fullscreen();});
$('#more').onclick=openProof;$('#closeProof').onclick=()=>$('#proofDialog').close();$('#closeSettings').onclick=()=>$('#settings').close();$('#enter').onclick=enter;$('#cover').onclick=e=>{if(!e.target.closest('a,button'))enter();};$('#hideAnimation').onclick=()=>{hiddenAnimation=true;stopPlayback();$('#diagram').style.opacity='0';$('#hideAnimation').hidden=true;};$('#replay').onclick=()=>{schedulePlayback();replay();};
$('#theme').value=safeStore.get('mhs-panel-style','sand');document.documentElement.dataset.panelStyle=$('#theme').value;$('#theme').onchange=e=>{document.documentElement.dataset.panelStyle=e.target.value;safeStore.set('mhs-panel-style',e.target.value);renderGraph(true);};
for(const id of ['autoplay','loop']){$('#'+id).checked=safeStore.get('mhs-'+id,'true')==='true';$('#'+id).onchange=e=>{safeStore.set('mhs-'+id,e.target.checked);schedulePlayback();};}
for(const id of ['delay','interval']){$('#'+id).value=safeStore.get('mhs-'+id,id==='delay'?'2':'5');$('#'+id+'Value').textContent=$('#'+id).value+' s';$('#'+id).oninput=e=>{safeStore.set('mhs-'+id,e.target.value);$('#'+id+'Value').textContent=e.target.value+' s';schedulePlayback();};}
$('#duration').oninput=e=>{duration=+e.target.value;$('#durationValue').textContent=(duration/1000).toFixed(1)+' s';safeStore.set('mhs-duration',duration);};$('#reduce').onchange=e=>{reduce=e.target.checked;safeStore.set('mhs-reduce',reduce);schedulePlayback();};
document.addEventListener('keydown',e=>{if(document.querySelector('dialog[open]')||e.target.closest('input,select,textarea')||e.altKey||e.ctrlKey||e.metaKey||e.repeat)return;if(!entered){if(['Enter',' '].includes(e.key)){e.preventDefault();enter();}return;}if(['Enter','ArrowRight',' '].includes(e.key)){e.preventDefault();advance(1);}if(e.key==='ArrowLeft'){e.preventDefault();advance(-1);}});
let touch=null;$('.workspace').addEventListener('pointerdown',e=>{if(e.pointerType==='touch'&&!e.target.closest('button,a,input,select'))touch={x:e.clientX,y:e.clientY};});$('.workspace').addEventListener('pointerup',e=>{if(!touch)return;const dx=e.clientX-touch.x,dy=e.clientY-touch.y;touch=null;if(Math.abs(dx)>45&&Math.abs(dx)>Math.abs(dy)*1.3)advance(dx>0?1:-1);else if(Math.hypot(dx,dy)<10)advance(1);});
function fitDiagram(){const holder=$('#diagram'),module=$('.visual-module');const width=Math.min(module.clientWidth,Math.max(0,module.clientHeight-30)*800/450);holder.style.width=width+'px';holder.style.setProperty('--diagram-scale',width/800);}
new ResizeObserver(()=>{fitDiagram();positionCard(true);}).observe($('.visual-column'));window.addEventListener('hashchange',()=>{const i=chapters.findIndex(c=>c.id===location.hash.slice(1));if(i>=0)go(i);});
await new Promise(resolve=>{if(window.katex)resolve();else window.addEventListener('load',resolve,{once:true});});
for(let i=0;i<chapters.length;i++){const c=chapters[i];c.formulas.forEach(f=>math(f,true));if(c.intro)inline(c.intro);for(const p of c.proof){p.formulas.forEach(f=>math(f,true));inline(p.text);}$('#loadProgress').style.width=((i+1)/chapters.length*85)+'%';await new Promise(requestAnimationFrame);}
const initial=chapters.findIndex(c=>c.id===location.hash.slice(1));if(initial>=0)current=initial;reached=current;translateUI();go(current,{instant:true});await document.fonts.ready;$('#loadProgress').style.width='100%';$('#enter').disabled=false;fitDiagram();
window.__mhs={get state(){return{current,reached,line,lang,entered,graphState:{...graphState},mathErrors:[...mathErrors]};},chapters};
