import {chapters,ui} from './content.js?v=1';
import {drawDiagram} from './diagrams.js?v=1';
const R=String.raw;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const safeStore={get(k,f){try{return localStorage.getItem(k)||f}catch{return f}},set(k,v){try{localStorage.setItem(k,v)}catch{}}};
let lang=safeStore.get('mhs-language','zh'),current=0,reached=0,proofStep=0,entered=false;
let duration=+safeStore.get('mhs-duration','1000'),reduce=safeStore.get('mhs-reduce','false')==='true'||matchMedia('(prefers-reduced-motion: reduce)').matches;
let evolutionToken=0;
let graphState={},mathErrors=[],transitionSerial=0,graphAnimations=[],foldAnimations=new Map();
const L=value=>Array.isArray(value)?value[lang==='zh'?0:1]:value||'';
const tr=k=>L(ui[k])||k;
function math(tex,display=false){try{return katex.renderToString(tex,{displayMode:display,throwOnError:true,strict:'error',output:'htmlAndMathml',trust:false})}catch(e){mathErrors.push({tex,error:e.message});console.error('MHS mathematics:',e.message);return `<span class="math-error">${tex.replaceAll('<','&lt;')}</span>`}}
const inline=s=>L(s).replace(/\$([^$]+)\$/g,(_,tex)=>`<span class="math">${math(tex)}</span>`);
const display=s=>`<div class="math display">${math(s,true)}</div>`;
const ms=factor=>reduce?0:duration*factor;
function animateTo(el,keyframes,options){if(reduce){return Promise.resolve()}const a=el.animate(keyframes,{duration:duration,easing:'cubic-bezier(.22,.8,.22,1)',...options});return a.finished.catch(()=>{});}
function translateUI(){$$('[data-i18n]').forEach(el=>el.textContent=tr(el.dataset.i18n));$$('[data-action="language"]').forEach(b=>b.textContent=lang==='zh'?'EN':'中文');document.documentElement.lang=lang==='zh'?'zh-CN':'en';$('#enter').textContent=tr('enter');$('#reduce').checked=reduce;$('#duration').value=duration;$('#durationValue').textContent=(duration/1000).toFixed(1)+' s';}
function addCard(index){const c=chapters[index],article=document.createElement('article');article.className='card';article.dataset.index=index;article.dataset.open='false';article.innerHTML=`<button class="card-head" aria-expanded="false" aria-controls="card-body-${index}"><span class="card-kind">${tr(c.kind)} ${c.no}</span><span class="card-title-mini">${L(c.title)}</span><span class="fold" aria-hidden="true">⌄</span></button><div class="card-body" id="card-body-${index}"><div class="card-body-inner"><h2>${L(c.title)}</h2>${c.tag?`<span class="card-tag">${L(c.tag)}</span>`:''}${c.intro?`<p>${inline(c.intro)}</p>`:''}<div class="formula">${c.formulas.map(display).join('')}</div><button class="inspect" data-inspect="${index}">${tr('preview')} ↗</button></div></div>`;
article.querySelector('.card-head').addEventListener('click',()=>setFold(article,article.dataset.open!=='true'));
article.querySelector('.inspect').addEventListener('click',()=>go(index));$('#cards').append(article);return article;}
function setFold(card,open,instant=false){const body=card.querySelector('.card-body'),inner=body.firstElementChild;const previous=foldAnimations.get(card);const from=body.getBoundingClientRect().height,fromOpacity=+getComputedStyle(body).opacity;
if(previous){previous.cancel();foldAnimations.delete(card)}body.style.height=from+'px';body.style.opacity=fromOpacity;card.dataset.open=String(open);card.querySelector('.card-head').setAttribute('aria-expanded',String(open));body.inert=!open;
const end=open?inner.getBoundingClientRect().height:0;if(instant||reduce){body.style.height=open?'auto':'0px';body.style.opacity=open?'1':'0';return;}
const animation=body.animate([{height:from+'px',opacity:fromOpacity},{height:end+'px',opacity:open?1:0}],{duration:ms(.85),easing:'cubic-bezier(.22,.8,.22,1)',fill:'forwards'});foldAnimations.set(card,animation);
animation.finished.then(()=>{if(foldAnimations.get(card)!==animation)return;body.style.height=open?'auto':'0px';body.style.opacity=open?'1':'0';animation.cancel();foldAnimations.delete(card);}).catch(()=>{});}
function renderCards(rebuild=false){if(rebuild){for(const a of foldAnimations.values())a.cancel();foldAnimations.clear();$('#cards').replaceChildren();}for(let i=0;i<=reached;i++)if(!$(`.card[data-index="${i}"]`))addCard(i);
$$('.card').forEach(card=>{const active=+card.dataset.index===current;card.classList.toggle('current',active);card.querySelector('.inspect').hidden=active;setFold(card,active,rebuild||!entered);});
$('#chapterCount').textContent=`${String(current+1).padStart(2,'0')} / ${String(chapters.length).padStart(2,'0')}`;$('#progressLabel').textContent=L(chapters[current].title);$('#progressBar').style.width=((current+1)/chapters.length*100)+'%';$('#previous').disabled=current===0;$('#next').textContent=tr(current===chapters.length-1?'finish':'next');
if(entered){const pane=$('.notebook'),card=$('.card.current');requestAnimationFrame(()=>{const top=card.getBoundingClientRect().top-pane.getBoundingClientRect().top+pane.scrollTop;pane.scrollTo({top:Math.max(0,top-37),behavior:reduce?'instant':'smooth'});});}}
function initialGraphState(c){const base={n:3,p:1,route:'top'};if(c.graph==='complex')base.focus='h';if(c.graph==='pages')base.page=0;if(c.graph==='hodge'){base.w=2;base.ell=1}if(c.graph==='degeneration')base.r=2;if(c.graph==='equivariance')base.square='rho';return base;}
function graphTitle(){const names={comparison:['收敛 · 退化 · 等变性','CONVERGENCE · DEGENERATION · EQUIVARIANCE'],simplicial:['几何映射的交换图','GEOMETRIC COMMUTATION'],complex:['总复形的双次数','THE TOTAL COMPLEX'],filtration:['固定总次数的列滤过','COLUMN FILTRATION IN FIXED TOTAL DEGREE'],hodge:['纯分次商上的 Hodge 分解','HODGE TYPES ON A PURE GRADED QUOTIENT'],action:['拉回诱导的交换方块','THE PULLBACK SQUARE'],pages:['由滤过复形产生谱序列','FROM THE FILTERED COMPLEX TO ITS PAGES'],degeneration:['高阶微分与权重','HIGHER DIFFERENTIALS AND WEIGHTS'],convergence:['稳定页与总上同调的分次商','STABLE PAGE AND GRADED TOTAL COHOMOLOGY'],equivariance:['同一个代表元，两条路径','ONE REPRESENTATIVE, TWO PATHS'],representative:['闭总代表元的首列','LEADING COLUMN OF A CLOSED TOTAL COCHAIN'],example:['商空间中的分支交换','BRANCH EXCHANGE ON THE QUOTIENT'],descent:['真下降将比较传回 X','PROPER DESCENT BACK TO X']};return L(names[chapters[current].graph]);}
async function renderGraph(instant=false){const serial=++transitionSerial,holder=$('#diagram');const next=drawDiagram(chapters[current].graph,graphState,lang,math);next.dataset.current='true';holder.setAttribute('aria-label',graphTitle());$('#diagramTitle').textContent=graphTitle();
// Preserve the currently composited image when an interaction interrupts a transition.
const old=[...holder.children].map(el=>({el,opacity:+getComputedStyle(el).opacity}));for(const a of graphAnimations)a.cancel();graphAnimations=[];
for(const {el,opacity}of old){el.style.opacity=opacity;delete el.dataset.current;}next.style.opacity=instant||reduce?'1':'0';holder.append(next);
if(instant||reduce){old.forEach(x=>x.el.remove());return;}const options={duration:ms(.72),easing:'cubic-bezier(.22,.8,.22,1)',fill:'forwards'};
for(const {el,opacity} of old)graphAnimations.push(el.animate([{opacity},{opacity:0}],options));graphAnimations.push(next.animate([{opacity:0},{opacity:1}],options));
await Promise.allSettled(graphAnimations.map(a=>a.finished));if(serial!==transitionSerial)return;
next.style.opacity='1';old.forEach(x=>x.el.remove());for(const a of graphAnimations)a.cancel();graphAnimations=[];
}
const button=(label,fn,selected=false)=>{const b=document.createElement('button');b.type='button';b.innerHTML=label;b.classList.toggle('selected',selected);b.setAttribute('aria-pressed',String(selected));b.addEventListener('click',fn);$('#controls').append(b);return b;};
function range(label,key,min,max){const wrap=document.createElement('label');wrap.innerHTML=`${inline(label)} <input type="range" aria-label="${L(label).replaceAll('$','')}" min="${min}" max="${max}" step="1" value="${graphState[key]}"><output>${graphState[key]}</output>`;wrap.querySelector('input').addEventListener('input',e=>{graphState[key]=+e.target.value;wrap.querySelector('output').textContent=e.target.value;if(key==='n'&&graphState.p>graphState.n){graphState.p=graphState.n;renderControls();}if(key==='n'){const pInput=$('#controls input[data-parameter="p"]');if(pInput)pInput.max=graphState.n;}renderGraph();});wrap.querySelector('input').dataset.parameter=key;$('#controls').append(wrap);}
function choose(key,value){if(key==='page')return formPage(value);graphState[key]=value;renderControls();renderGraph();}
async function formPage(target){const token=++evolutionToken;
 if(target<2||reduce){graphState.page=target;delete graphState.cohom;delete graphState.pending;$('#diagram').setAttribute('aria-busy','false');renderControls();renderGraph();return;}
 graphState.page=target-1;graphState.pending=target;graphState.cohom='kernel';$('#diagram').setAttribute('aria-busy','true');renderControls();await renderGraph();await new Promise(resolve=>setTimeout(resolve,ms(.25)));
 if(token!==evolutionToken)return;graphState.cohom='quotient';await renderGraph();await new Promise(resolve=>setTimeout(resolve,ms(.45)));
 if(token!==evolutionToken)return;delete graphState.cohom;delete graphState.pending;graphState.page=target;renderControls();await renderGraph();if(token===evolutionToken)$('#diagram').setAttribute('aria-busy','false');
}
function renderControls(){const g=chapters[current].graph;$('#controls').replaceChildren();const options=(key,items)=>items.forEach(([value,label])=>button(inline(label),()=>choose(key,value),graphState[key]===value));
if(g==='comparison'){button(inline(['查看证明主线','Follow the proof']),()=>go(1));}
if(g==='simplicial'){button(inline(['强调交换方块','Emphasize the square']),()=>replay());}
if(g==='complex'){options('focus',[['h',[R`横向 $h$`,R`Horizontal $h$`]],['v',[R`纵向 $v$`,R`Vertical $v$`]],['both',['双复形','Double complex']],['total',[R`总空间 $C^n$`,R`Total space $C^n$`]],['D',[R`总微分 $D$`,R`Total differential $D$`]]]);if(['total','D'].includes(graphState.focus))range([R`次数 $n$`,R`Degree $n$`],'n',1,3);}
if(['filtration','representative'].includes(g)){range([R`总次数 $n$`,R`Total degree $n$`],'n',1,4);range([R`列 $p$`,R`Column $p$`],'p',0,graphState.n);}
if(g==='convergence'){range([R`总次数 $n$`,R`Total degree $n$`],'n',1,4);range([R`列 $p$`,R`Column $p$`],'p',0,graphState.n);}
if(g==='hodge'){range([R`权重 $w$`,R`Weight $w$`],'w',0,3);range([R`Hodge 滤过 $\ell$`,R`Hodge level $\ell$`],'ell',0,4);}
if(g==='action'||g==='equivariance'){if(g==='equivariance')options('square',[['rho',[R`$\rho$ 的方块`,R`Square for $\rho$`]],['sigma',[R`$\sigma$ 的方块`,R`Square for $\sigma$`]],['alpha',[R`$\alpha$ 的方块`,R`Square for $\alpha$`]]]);button(inline(['先向右，再向下','Right, then down']),()=>traceRoute('top'),graphState.route==='top');button(inline(['先向下，再向右','Down, then right']),()=>traceRoute('bottom'),graphState.route==='bottom');}
if(g==='pages'){options('page',[[0,[R`$K$`,R`$K$`]],[1,[R`产生 $E_0$`,R`Form $E_0$`]],[2,[R`$H(d_0)\Rightarrow E_1$`,R`$H(d_0)\Rightarrow E_1$`]],[3,[R`$H(d_1)\Rightarrow E_2$`,R`$H(d_1)\Rightarrow E_2$`]]]);}
if(g==='degeneration')range([R`微分页数 $r$`,R`Differential page $r$`],'r',2,4);
if(g==='example'){button(inline(['原代表元','Original representative']),()=>choose('swap',false),!graphState.swap);button(inline([R`施加 $f_1^*$`,R`Apply $f_1^*$`]),()=>choose('swap',true),!!graphState.swap);}
if(g==='descent'){button(inline(['回看等变比较','Revisit equivariant comparison']),()=>go(9));button(inline(['打开原始 PDF','Open the source PDF']),()=>window.open('sources/MHS_DESCENT.pdf','_blank','noopener'));}}
function renderProof(instant=false){const c=chapters[current],s=c.proof[proofStep];$('#sourceLink').href=`sources/${c.source}.pdf#page=${c.page}`;$('#sourceLink').textContent=`${c.source.replace('MHS_','')} · ${c.page} ↗`;$('#proofTabs').replaceChildren();c.proof.forEach((step,i)=>{const b=document.createElement('button');b.type='button';b.textContent=`${i+1} ${L(step.title)}`;b.setAttribute('role','tab');b.setAttribute('aria-selected',String(i===proofStep));b.classList.toggle('selected',i===proofStep);b.addEventListener('click',()=>setProof(i));$('#proofTabs').append(b);});
let extras='';if(c.id==='descent'&&proofStep>=1){extras=`<div class="sources">${['MHS_EQUIV','MHS_DESCENT','MHS_PACKAGE','MHS_EXAMPLE','MHS_KEY'].map(name=>`<a href="sources/${name}.pdf" target="_blank" rel="noopener">${name}.pdf ↗</a>`).join('')}</div>`;if(proofStep===2)extras+=`<div class="sources"><a href="https://www.numdam.org/item/10.1007/BF02685881.pdf" target="_blank" rel="noopener">Deligne · Théorie de Hodge III · (8.1.20), (8.3.5) ↗</a><a href="https://math.mit.edu/~hrm/palestine/weibel/05-spectral_sequences.pdf" target="_blank" rel="noopener">Weibel · 5.4.1, 5.5.1 ↗</a><a href="../spectral/">Spectral Sequence · Sheng Meng ↗</a></div>`;}
const panel=$('#proof');panel.innerHTML=`<h3>${L(s.title)}</h3>${s.formulas.map(display).join('')}${L(s.text)?`<p>${inline(s.text)}</p>`:''}${extras}`;panel.dataset.step=proofStep;panel.dataset.chapter=c.id;$('#proofCount').textContent=`${proofStep+1} / ${c.proof.length}`;$('#proofPrev').disabled=proofStep===0;$('#proofNext').disabled=proofStep===c.proof.length-1;if(!instant)animateTo(panel,[{opacity:.15},{opacity:1}],{duration:ms(.45)});
}
function setProof(i){proofStep=Math.min(chapters[current].proof.length-1,Math.max(0,i));renderProof();}
function go(index,{instant=false}={}){evolutionToken++;$('#diagram').setAttribute('aria-busy','false');current=Math.max(0,Math.min(chapters.length-1,index));reached=Math.max(reached,current);proofStep=0;graphState=initialGraphState(chapters[current]);renderCards(instant);renderControls();renderProof(instant);renderGraph(instant);history.replaceState(null,'',`#${chapters[current].id}`);}
async function replay(){const svg=$('#diagram .diagram-scene[data-current]');if(!svg)return;const edges=[...svg.querySelectorAll('[data-emphasis], [data-route]')];const chosen=edges.length?edges:[...svg.querySelectorAll('rect')];chosen.forEach(el=>{const from=+getComputedStyle(el).opacity;const rest=+(el.getAttribute('opacity')||1);for(const a of el.getAnimations())a.cancel();animateTo(el,[{opacity:from},{opacity:Math.max(.12,rest*.35),offset:.35},{opacity:rest}],{duration:ms(1.2)});});}
async function traceRoute(route){graphState.route=route;renderControls();await renderGraph();if(!entered||!['action','equivariance'].includes(chapters[current].graph))return;const svg=$('#diagram .diagram-scene[data-current]');if(!svg||reduce)return;
// A representative follows both sides of the same square. Fade the terminal point out continuously.
const drawing=svg.querySelector('svg');const dot=document.createElementNS('http://www.w3.org/2000/svg','circle');dot.setAttribute('cx','0');dot.setAttribute('cy','0');dot.setAttribute('r','5');dot.setAttribute('fill','#ffd078');dot.style.opacity='0';drawing.append(dot);
const points=route==='top'?[[205,122],[595,122],[595,332]]:[[205,122],[205,332],[595,332]];
await animateTo(dot,[{transform:`translate(${points[0][0]}px,${points[0][1]}px)`,opacity:0},{transform:`translate(${points[0][0]}px,${points[0][1]}px)`,opacity:1,offset:.08},{transform:`translate(${points[1][0]}px,${points[1][1]}px)`,opacity:1,offset:.46},{transform:`translate(${points[2][0]}px,${points[2][1]}px)`,opacity:1,offset:.83},{transform:`translate(${points[2][0]}px,${points[2][1]}px)`,opacity:0}],{duration:ms(2.2)});dot.remove();}
async function showCover(){entered=false;const cover=$('#cover');cover.hidden=false;cover.style.opacity='1';$('#app').inert=true;history.replaceState(null,'','#title');await animateTo(cover,[{opacity:0},{opacity:1}],{duration:ms(.4)});$('#enter').focus({preventScroll:true});}
async function enter(){if(entered)return;entered=true;$('#app').inert=false;const cover=$('#cover');await animateTo(cover,[{opacity:1},{opacity:0}],{duration:ms(.7)});cover.hidden=true;history.replaceState(null,'',`#${chapters[current].id}`);replay();}
$$('[data-action]').forEach(button=>button.addEventListener('click',async()=>{const action=button.dataset.action;if(action==='language'){evolutionToken++;if(graphState.pending)graphState.page=graphState.pending;delete graphState.pending;delete graphState.cohom;$('#diagram').setAttribute('aria-busy','false');lang=lang==='zh'?'en':'zh';safeStore.set('mhs-language',lang);translateUI();renderCards(true);renderControls();renderProof(true);renderGraph(true);}if(action==='cover')showCover();if(action==='settings'){$('#settings').hidden=!$('#settings').hidden;button.setAttribute('aria-expanded',String(!$('#settings').hidden));}if(action==='fullscreen'){try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{document.body.classList.toggle('immersive');}}}));
$('#duration').addEventListener('input',e=>{duration=+e.target.value;$('#durationValue').textContent=(duration/1000).toFixed(1)+' s';safeStore.set('mhs-duration',duration);});$('#reduce').addEventListener('change',e=>{reduce=e.target.checked;safeStore.set('mhs-reduce',reduce);});$('#enter').addEventListener('click',enter);$('#previous').addEventListener('click',()=>go(current-1));$('#next').addEventListener('click',()=>go(current===chapters.length-1?9:current+1));$('#proofPrev').addEventListener('click',()=>setProof(proofStep-1));$('#proofNext').addEventListener('click',()=>setProof(proofStep+1));$('#replay').addEventListener('click',replay);
document.addEventListener('keydown',e=>{if(e.key==='Escape'){$('#settings').hidden=true;$('[data-action="settings"]').setAttribute('aria-expanded','false');}if(e.target.closest('button,input,a,select,textarea')||e.altKey||e.ctrlKey||e.metaKey||e.repeat)return;if(!entered){if(e.key==='Enter'){e.preventDefault();enter()}return;}if(['ArrowRight','Enter'].includes(e.key)){e.preventDefault();if(current<chapters.length-1)go(current+1);}if(e.key==='ArrowLeft'){e.preventDefault();go(current-1);}});
const sizeObserver=new ResizeObserver(()=>{const holder=$('#diagram');holder.style.setProperty('--diagram-scale',holder.clientWidth/800);if(entered){const pane=$('.notebook'),card=$('.card.current');if(card)pane.scrollTop=card.getBoundingClientRect().top-pane.getBoundingClientRect().top+pane.scrollTop-28;}});sizeObserver.observe($('#diagram'));
// Typeset every formula once before dismissing the cover, including content revealed later.
await new Promise(resolve=>{if(window.katex)resolve();else window.addEventListener('load',resolve,{once:true});});
for(const c of chapters){c.formulas.forEach(f=>math(f,true));if(c.intro)inline(c.intro);for(const p of c.proof){p.formulas.forEach(f=>math(f,true));inline(p.text);}}
const hash=location.hash.slice(1);const initial=chapters.findIndex(c=>c.id===hash);if(initial>=0)current=initial;reached=current;translateUI();go(current,{instant:true});const fontWarmup=document.createElement('div');fontWarmup.style.cssText='position:fixed;visibility:hidden;pointer-events:none;inset:0;overflow:hidden;';fontWarmup.setAttribute('aria-hidden','true');fontWarmup.innerHTML=math(R`\mathcal A\mathbb{QC}\operatorname{Gr}\alpha\Phi\rho\sigma\infty\bigoplus\frac{a}{b}`);document.body.append(fontWarmup);await document.fonts.ready;fontWarmup.remove();$('#enter').disabled=false;
window.__mhs={get state(){return{current,reached,proofStep,lang,entered,graphState:{...graphState},mathErrors:[...mathErrors],moving:graphAnimations.length,folding:foldAnimations.size}},chapters};
