const esc=s=>s.replace(/&/g,'&amp;').replace(/"/g,'&quot;').replace(/</g,'&lt;');
const math=(tex,display)=>`<${display?'div':'span'} class="${display?'math-block':'math-inline'}" data-tex="${esc(tex)}"${display?' data-display="true"':''}></${display?'div':'span'}>`;
const m=(s,...xs)=>math(String.raw(s,...xs),false),d=(s,...xs)=>math(String.raw(s,...xs),true);
const proof=(title,body,open=false)=>`<details class="proof"${open?' open':''}><summary>${title}</summary><div class="proof-body">${body}<p class="qed">□</p></div></details>`;
const theorem=(label,body)=>`<div class="theorem"><h3>${label}</h3>${body}</div>`;
const experiment=(title,buttons,note)=>`<section class="experiment"><h3>${title}</h3><div class="experiment-actions">${buttons.map(([label,alg,type])=>`<button ${type?'data-action="'+type+'"':'data-alg="'+alg+'"'}>${label}</button>`).join('')}</div><p>${note}</p></section>`;
export const LESSONS=[
{id:'language',short:'群的语言',en:'THE LANGUAGE OF MOVES',title:'一次转动，一个元素',subtitle:'A move is a transformation, not a written word.',lead:'拿起魔方，先转右面 R，再转上面 U。把这两步连起来，就是一个新的操作。群论从这个最朴素的动作开始：把可以复合、可以撤销的变换放在一起。',body:
theorem('定义 1 · 魔方群',`<p>固定六个中心块。令 ${m`\Omega`} 为 48 个活动贴纸的位置，六个面顺时针转 90° 的置换记为 ${m`R,U,F,D,L,B`}。定义</p>${d`G=\langle R,U,F,D,L,B\rangle\leq S_{\Omega}.`}<p>每个群元素是一个置换；不同操作词可以表示同一元素。</p>`)+
experiment('从最小的动作开始',[['四次 R','R R R R'],['操作与撤销',"R U U' R'"],['自由操作','','free']],"点选演示后按播放，或逐步前进。R′ 表示逆转，R2 表示转 180°；顺时针方向总是从该面的外侧正视判断。")+
proof('约定：从左到右执行',`<p>本页采用右作用记法。${m`x\cdot g`} 表示贴纸 ${m`x`} 经 ${m`g`} 后的位置，且</p>${d`x\cdot(gh)=(x\cdot g)\cdot h.`}<p>因此 ${m`RU`} 表示<strong>先 R，后 U</strong>。写成函数就是 ${m`(gh)(x)=h(g(x))`}；这与部分教材的函数复合记法相反，但全文一致。观察角度的改变不是群元素，也不会改变贴纸的数学状态。</p>`,true)+
proof('证明：这些操作确实组成一个群',`<p>六个面转动都是有限集 ${m`\Omega`} 的双射；一次反向转动给出其逆。取它们及其逆的所有有限复合：</p><ol><li><strong>封闭性。</strong>连接两个有限操作词仍是有限操作词。</li><li><strong>结合律。</strong>对任意贴纸 ${m`x`}，${m`x\cdot((gh)k)=((x\cdot g)\cdot h)\cdot k=x\cdot(g(hk))`}，所以两个置换相同。</li><li><strong>单位元。</strong>空操作词给出恒等置换 ${m`e`}，满足 ${m`eg=ge=g`}。</li><li><strong>逆元。</strong>若 ${m`g=a_1\cdots a_n`}，反向撤销每一步，便有 ${m`g^{-1}=a_n^{-1}\cdots a_1^{-1}`}。相邻的 ${m`a_i a_i^{-1}`} 逐次消去。</li></ol><p>以在每个贴纸上的作用是否相同来判定两个词是否相等，不依赖词的写法。由此得到 ${m`S_{48}`} 的一个子群，而不是自由生成的所有文字串。</p>`)+
proof('辨析：状态与操作为什么能一一对应',`<p>复原态给每个活动贴纸一个唯一标签。一个操作将每个标签放入某个位置，因而确定一个置换；反过来，全部标签的位置决定该置换。故群在复原态的可达状态集合上的作用是自由且传递的，群元素与可达状态一一对应。</p><p>角块的三种颜色组合、棱块的两种颜色组合彼此不同，且固定中心确定六个面。因此在普通魔方中，颜色状态已经确定每块的位置与朝向；不需要把同色贴纸视为任意可互换的小纸片。</p>`)+
`<p class="scope-note">键盘 R U F D L B：顺转；Shift + 字母：逆转。也可以拖动色块转面，用下方按钮精确选择 90°、逆转或 180°。</p>`},
{id:'permutations',short:'置换与阶',en:'PERMUTATIONS & ORDER',title:'转动会在何时回来',subtitle:'Disjoint cycles turn motion into arithmetic.',lead:'一次转动同时移动许多贴纸，却能拆成若干条互不相交的循环。让每一条循环都走完整数圈，整个魔方才会回到出发点。',body:
theorem('定理 2 · 置换的阶',`<p>若置换 ${m`g`} 的不相交轮换长度为 ${m`\ell_1,\ldots,\ell_r`}，则</p>${d`\operatorname{ord}(g)=\operatorname{lcm}(\ell_1,\ldots,\ell_r).`}<p>恒等置换的阶为 1。不动点对应的长度 1 可以省略。</p>`)+
experiment('比较短算法，观察完整贴纸轮换',[['R：阶为 4','R'],['RU：阶为 105','R U'],['(RU)³','(R U)3']],"打开“状态与不变量”，比较块的位置轮换与完整贴纸的阶。角块即使回到原位，朝向也可能尚未复原。")+
proof('证明：轨道分解与最小公倍数',`<p>取 ${m`x\in\Omega`}。有限性保证 ${m`x,xg,xg^2,\ldots`} 重复；双射性允许消去相同的前缀，所以存在最小正整数 ${m`\ell`} 使 ${m`xg^\ell=x`}。于是这 ${m`\ell`} 个位置组成一条轮换。</p><p>两条这样的轨道若相交，沿 ${m`g`} 及 ${m`g^{-1}`} 就能从一个位置到达另一个，故轨道相同。不断取尚未包含的位置，得到全体位置的不相交轮换分解。</p><p>在长度 ${m`\ell`} 的轮换上，${m`g^k`} 恒等当且仅当 ${m`\ell\mid k`}：将 ${m`k=q\ell+r`}，${m`0\le r<\ell`}，则移动 ${m`k`} 步等于移动 ${m`r`} 步，仅 ${m`r=0`} 时回到原位。因此 ${m`g^k=e`} 当且仅当每个 ${m`\ell_i`} 都整除 ${m`k`}，最小正解正是它们的最小公倍数。</p>`,true)+
proof('精确算例：为什么 RU 的阶不是 5 或 7',`<p>本页的整数坐标转动给出以下完整贴纸轮换长度（不计不动点）：</p><div class="table-scroll"><table><thead><tr><th>操作</th><th>48 贴纸的非平凡轮换长度</th><th>阶</th></tr></thead><tbody><tr><td>R</td><td>4, 4, 4, 4, 4</td><td>4</td></tr><tr><td>RU</td><td>15, 7, 3, 7</td><td>105</td></tr><tr><td>RUR′U′</td><td>6, 3, 6, 3</td><td>6</td></tr></tbody></table></div><p>例如 ${m`\operatorname{lcm}(15,7,3,7)=105`}。这些是可复核的有限计算：展开下方完整贴纸数据，或查看 <a class="proof-download" href="cube-core.mjs">精确置换实现</a>；每个贴纸位置只使用 ${m`-1,0,1`} 的整数坐标。</p><p>角块位置只记录 ${m`S_8`} 中的投影，棱块位置只记录 ${m`S_{12}`} 中的投影；它们没有记录朝向，所以仅用块位置轮换计算的阶可能偏小。</p>`)+
proof('练习与解答：R² 的阶是多少',`<p>${m`(R^2)^2=R^4=e`}，而 ${m`R^2\ne e`}，因为它将某个右面贴纸送至对面的位置。因此 ${m`\operatorname{ord}(R^2)=2`}。</p><p>一般地，若 ${m`\operatorname{ord}(g)=n`}，则 ${m`(g^k)^t=e`} 当且仅当 ${m`n\mid kt`}。写 ${m`n=dn_0,k=dk_0`} 且 ${m`\gcd(n_0,k_0)=1`}，等价于 ${m`n_0\mid t`}。故 ${m`\operatorname{ord}(g^k)=n/\gcd(n,k)`}。</p>`)},
{id:'commutators',short:'交换子',en:'NONCOMMUTATIVITY',title:'次序留下了什么',subtitle:'The commutator measures a failure to commute.',lead:'先转右面再转上面，与先转上面再转右面，会给出不同的结果。把两种次序的差异组织成一个操作，就是交换子。',body:
theorem('定义与命题 3 · 交换子',`<p>采用本页的约定，定义 ${m`[a,b]=aba^{-1}b^{-1}`}。则</p>${d`[a,b]=e\quad\Longleftrightarrow\quad ab=ba.`}<p>不同文献也使用另一种交换子约定；这里始终使用上式。</p>`)+
experiment('把两种次序分别做出来',[['先 R 后 U','R U'],['先 U 后 R','U R'],['交换子 [R,U]','[R,U]'],['重复六次','(R U R\' U\')6']],"每个演示均从复原态开始；点击播放观察结果。设置中开启“突出改变的贴纸”，可以清楚看到操作的作用范围。")+
proof('证明：魔方群不是交换群',`<p>考察角块 URF 的位置。顺转 R 将它送到 UBR，接着顺转 U 将它送回 URF；所以 ${m`URF\cdot(RU)=URF`}。</p><p>若先转 U，URF 被送至 UFL；UFL 不在右层，R 不移动它。因此 ${m`URF\cdot(UR)=UFL`}。同一角块的像不同，故 ${m`RU\ne UR`}。</p><p>这里的 URF 表示上—右—前三面交会的角块位置；用于区分两个操作时，找到一个位置的像不同就已经足够。</p>`,true)+
proof('证明：交换子等价式与局部作用',`<p>若 ${m`ab=ba`}，则 ${m`aba^{-1}b^{-1}=baa^{-1}b^{-1}=e`}。反之，将 ${m`aba^{-1}b^{-1}=e`} 依次在右侧乘 ${m`b`}、${m`a`}，得到 ${m`ab=ba`}。</p><p>若两个置换的支集不相交，它们可交换：一个置换只能在自己的支集内置换位置，对另一支集逐点固定，在两支集外二者皆恒等。所以交换子可以检测作用范围相互影响的部分。</p><p>但不能由此声称交换子“只移动两个支集的交集”。具体的作用范围必须逐点计算。本页 ${m`[R,U]`} 的角位置投影是两个对换，棱位置投影是一条 3 轮换；完整贴纸轮换长度为 6、3、6、3，故它的阶为 6。</p>`)+
proof('证明：六次相同的交换子复原',`<p>记 ${m`c=[R,U]`}。由上一章的轮换定理，${m`\operatorname{ord}(c)=\operatorname{lcm}(6,3,6,3)=6`}，故 ${m`c^6=e`}。因为存在一个长度为 6 的贴纸轮换，对 ${m`1\le k<6`} 不可能有 ${m`c^k=e`}。</p><p>这个结论依赖具体的 R、U 置换，不是“任何交换子的阶都为 6”。</p>`)},
{id:'conjugation',short:'共轭',en:'CONJUGATION',title:'同一种动作，换一个位置',subtitle:'Change the coordinates; keep the cycle structure.',lead:'先做准备动作，把目标搬到熟悉的位置；执行已有算法；最后撤销准备。共轭让一个局部算法能在不同的位置重复使用。',body:
theorem('定理 4 · 共轭保持阶',`<p>对 ${m`a,b\in G`} 及 ${m`k\in\mathbb Z`}，</p>${d`(aba^{-1})^k=ab^ka^{-1}.`}${d`\operatorname{ord}(aba^{-1})=\operatorname{ord}(b).`}<p>在置换群中，共轭还保持各轮换的长度。</p>`)+
experiment('先搬运，再操作，再搬回',[['原动作 R','R'],['共轭 FRF′','[F:R]'],['搬运交换子','[F:[R,U]]']],"[F:R] 是 F R F′ 的缩写；[F:[R,U]] 是 F [R,U] F′。慢速逐步播放，观察开头与结尾的准备动作如何抵消。")+
proof('证明：相邻准备动作相消',`<p>对正整数 ${m`k`} 展开乘积，相邻的 ${m`a^{-1}a`} 消去，得到 ${m`(aba^{-1})^k=ab^ka^{-1}`}。${m`k=0`} 时两侧均为 ${m`e`}；取逆后相同论证覆盖负整数。</p><p>于是 ${m`(aba^{-1})^k=e`} 当且仅当 ${m`b^k=e`}。两边可行的正整数 ${m`k`} 完全相同，最小值也相同。这证明共轭保持阶。</p>`,true)+
proof('证明：轮换只是重命名',`<p>若 ${m`b`} 含轮换 ${m`(x_1\ x_2\ \cdots\ x_r)`}，令 ${m`y_i=x_i\cdot a^{-1}`}。则在右作用约定下，</p>${d`y_i\cdot(aba^{-1})=(x_i\cdot b)\cdot a^{-1}=y_{i+1}.`}<p>末项的下一个位置理解为第一项。因此该轮换被重命名为 ${m`(y_1\ y_2\ \cdots\ y_r)`}，长度不变。支集相应变为 ${m`\operatorname{supp}(b)\cdot a^{-1}`}。</p><p>注意逆号来自本页“先 a 再 b”的约定。实际执行顺序始终是准备 a、操作 b、撤销 a。</p>`)+
proof('辨析：相同的阶并不意味着共轭',`<p>在 ${m`S_4`} 中，对换 ${m`(1\ 2)`} 与双对换 ${m`(1\ 2)(3\ 4)`} 的阶同为 2，但轮换长度分别为 2 与 2、2。共轭保持轮换类型，所以它们不共轭。</p><p>甚至在魔方群中，判断共轭也不能只看阶。本页只使用已证明的必要条件，不把它倒过来用。</p>`)},
{id:'orbits',short:'子群与轨道',en:'SUBGROUPS & ORBITS',title:'先读懂一个小世界',subtitle:'A four-state Cayley graph, then orbit–stabilizer.',lead:'若只允许转上面 U，魔方只有四个可达状态。四个节点、四条箭头，就是一个完整的凯莱图。整个魔方群太大时，这样的小世界帮助我们看见结构。',body:
theorem('命题 5 · 一个循环子群',`${d`\langle U\rangle=\{e,U,U^2,U^3\}\cong\mathbb Z/4\mathbb Z.`}<p>图中箭头表示右乘 U。点击节点查看对应状态；这张图只画子群 ${m`\langle U\rangle`}，不是整个魔方群。</p>`)+
`<svg class="cayley" viewBox="0 0 380 180" role="group" aria-label="U 生成的四阶循环群凯莱图"><defs><marker id="arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="5" markerHeight="5" orient="auto-start-reverse"><path d="M0 0L10 5L0 10" fill="#a59c88"/></marker></defs><path d="M80 48H288M312 72V115M290 140H83M60 117V73" marker-end="url(#arrow)"/><text x="187" y="34" text-anchor="middle" font-size="13">· U</text><text x="187" y="94" text-anchor="middle" font-size="16">C₄</text>${[[60,48,'e',''],[312,48,'U','U'],[312,140,'U²','U2'],[60,140,'U³',"U'"]].map(([x,y,label,alg])=>`<g role="button" tabindex="0" aria-label="查看 ${label} 状态" data-state-alg="${alg}"><circle cx="${x}" cy="${y}" r="23"/><text x="${x}" y="${y+5}" text-anchor="middle" font-size="16">${label}</text></g>`).join('')}</svg>`+
experiment('沿着箭头走一圈',[['走完 C₄','U U U U'],['轨道中的一步','U']],"将范围缩小后，可以枚举全部元素；对整个魔方群，下一步用轨道与稳定子的大小关系计数。")+
proof('证明：循环子群与模 4 加法',`<p>${m`U^4=e`} 且 U 的阶恰为 4，所以这四个元素两两不同，所有整数次幂都落在其中。复合满足 ${m`U^iU^j=U^{i+j}`}，逆元为 ${m`U^{-i}`}。映射 ${m`\bar i\mapsto U^i`} 从 ${m`\mathbb Z/4\mathbb Z`} 到该子群良定义、双射并保持运算，因此是群同构。</p>`,true)+
proof('定理与证明：轨道—稳定子公式',`<p>设有限群 ${m`H`} 右作用于集合，固定一个点 ${m`x`}。定义轨道 ${m`xH=\{xh:h\in H\}`}，稳定子 ${m`H_x=\{h\in H:xh=x\}`}。</p><p>${m`H_x`} 包含单位元，对乘积与逆封闭，故为子群。且 ${m`xg=xh`} 当且仅当 ${m`xgh^{-1}=x`}，即 ${m`gh^{-1}\in H_x`}，等价于右陪集 ${m`H_xg=H_xh`}。</p><p>所以轨道点与稳定子的右陪集一一对应。右陪集两两相同或不交，覆盖 H；每个右陪集由双射 ${m`k\mapsto kg`} 与 ${m`H_x`} 等大。因此</p>${d`|H|=|xH|\,|H_x|.`}<p>同样的陪集分割论证对任意子群 ${m`K\le H`} 给出拉格朗日定理 ${m`|H|=[H:K]|K|`}。</p>`)+
proof('推论：稳定子链如何给出一个下界',`<p>依次选点 ${m`b_1,\ldots,b_r`}，令 ${m`G_0=G`}，${m`G_i=\{g\in G:g\text{ 固定 }b_1,\ldots,b_i\}`}。反复应用轨道—稳定子公式：</p>${d`|G|=\prod_{i=1}^{r}|b_iG_{i-1}|\,|G_r|.`}<p>若找到若干已知操作词，它们固定前 ${m`i-1`} 个点并让第 ${m`i`} 个点到达至少 ${m`m_i`} 个位置，则 ${m`|b_iG_{i-1}|\ge m_i`}。由于 ${m`|G_r|\ge1`}，得到 ${m`|G|\ge\prod_i m_i`}。</p><p>这个下界不要求先证明所给操作词生成整个稳定子，因而特别适合做有限证书。</p>`)},
{id:'invariants',short:'三条约束',en:'THREE CONSERVED QUANTITIES',title:'有些状态永远到不了',subtitle:'One flipped edge is already impossible.',lead:'把魔方拆开后重新装配，能得到一些靠转面永远到不了的状态。障碍藏在三处：角的总扭转、棱的总翻转，以及角与棱置换的奇偶是否匹配。',body:
theorem('定理 6 · 可达的必要条件',`<p>以 ${m`\sigma\in S_8,\tau\in S_{12}`} 记录角、棱位置；以 ${m`c_i\in\mathbb Z/3`}、${m`e_j\in\mathbb Z/2`} 记录各槽位的朝向。任何可达状态都满足</p>${d`\sum_{i=1}^{8}c_i=0\pmod3,`}${d`\sum_{j=1}^{12}e_j=0\pmod2,`}${d`\operatorname{sgn}\sigma=\operatorname{sgn}\tau.`}`)+
experiment('故意制造不可达的装配状态',[['翻一条棱','','flip'],['扭一个角','','twist'],['只交换两条棱','','parity'],['回到合法状态','','free']],"这些按钮模拟拆装，不是合法转面算法。状态栏会标出违反的约束；继续转面也无法消除该障碍。")+
proof('朝向坐标的精确定义',`<p>角槽位按以下有向面序编号：</p><p><code>URF, UFL, ULB, UBR, DFR, DLF, DBL, DRB</code>。</p><p>每个角块的本来颜色也使用其复原槽位的这个顺序。${m`c_i`} 是它的 U 或 D 贴纸在目标槽位三元组中的下标 0、1 或 2；余下两张贴纸按循环次序确定。普通角块只有这三种保持手性的朝向。</p><p>棱槽位和对应复原颜色次序为：</p><p><code>UR, UF, UL, UB, DR, DF, DL, DB, FR, FL, BL, BR</code>。</p><p>目标槽位两张颜色的顺序与该棱的本来顺序相同，记 ${m`e_j=0`}；相反，记 ${m`e_j=1`}。因此位置与朝向坐标完全确定每个活动贴纸。</p><p>这些次序固定后，“总和为零”才有精确含义。更换朝向 convention 可能改变单项坐标，但不得在同一计算中混用。</p>`,true)+
proof('证明：转动保持两个朝向总和',`<p>角块从一个有向三元组移到另一个，转动对下标的作用是循环平移。因此若操作 g 将槽位 i 送至 ${m`i\sigma_g`}，其对该块施加的下标增量记为 ${m`d_i(g)`}，则新朝向为旧朝向加上该增量，模 3 计算；棱块同理，模 2 计算。</p><p>位置的置换不会改变朝向总和；总和的变化只等于该转动所有增量之和。由整数 90° 旋转逐槽计算，六个生成元作用于复原态的朝向如下（列次序同前）：</p><div id="generatorTable" class="table-scroll"></div><p>U、D 无角扭转；R、L、F、B 各出现两项 1 和两项 2，总增量为 6，模 3 为零。F、B 各翻转四条棱，其他面无棱翻转，总增量模 2 也为零。</p><p>故每个生成元保持两个总和。其逆与任意复合仍保持总和；复原态总和为零，结论成立。</p>`)+
proof('证明：角与棱必须同时为奇或同时为偶',`<p>置换符号可定义为其置换矩阵的行列式；矩阵乘法给出 ${m`\operatorname{sgn}(ab)=\operatorname{sgn}(a)\operatorname{sgn}(b)`}。一个对换交换两列，符号为 −1；一条 r 轮换是 r−1 个对换的积，符号为 ${m`(-1)^{r-1}`}。</p><p>每个面 90° 转动在角位置上是一条 4 轮换，在棱位置上也是一条 4 轮换，二者符号都为 −1。于是每做一步，两类置换符号同时改变；半转则都保持。复原态二者都是 +1，所以任意操作后仍相等。</p><p>因此单棱翻转违反第二条，单角扭转违反第一条，仅交换两条棱违反第三条。这三类状态都不可达。本章尚未声称条件充分；充分性在下一章证明。</p>`)},
{id:'reachability',short:'可达与计数',en:'THE REACHABILITY THEOREM',title:'从三个障碍，到全部状态',subtitle:'A rigorous upper bound meets a certified lower bound.',lead:'找出障碍只完成了半个证明。现在反过来问：除此之外，还有隐藏的限制吗？用一份很小的有限证书，把可构造的状态数下界推到同一个上界，就能证明没有别的障碍。',body:
theorem('定理 7 · 普通三阶魔方的可达性',`<p>固定中心、保持块的种类与手性的装配状态可达，当且仅当上一章的三条约束成立。因此</p>${d`|G|=\frac{8!\,12!}{2}\,3^7\,2^{11}`}<div class="math-block" style="font-variant-numeric:tabular-nums;font-size:clamp(15px,1.7vw,22px);letter-spacing:.02em">= 43,252,003,274,489,856,000.</div>`)+
proof('第一步 · 计数给出上界',`<p>先任意选择角置换，共 ${m`8!`} 种。选前七个角朝向，共 ${m`3^7`} 种；第八个由总和为零唯一决定。</p><p>棱置换必须与角置换同奇偶，共 ${m`12!/2`} 种：将任意棱置换与固定对换复合，在奇置换与偶置换之间给出双射。前十一条棱的朝向有 ${m`2^{11}`} 种，最后一条由翻转和唯一决定。</p><p>这些选择互不额外制约，而且每组坐标对应唯一一个保持块手性的装配状态。故满足约束的集合 ${m`A`} 的大小为上述乘积。上一章已证 ${m`G\subseteq A`}，所以 ${m`|G|\le|A|`}；这里仍没有假定每个装配状态可达。</p>`,true)+
proof('第二步 · 稳定子轨道给出相同下界',`<p>给 48 个活动贴纸编号。依次选前七个角块各自的第一张贴纸，再选前十一条棱各自的第一张贴纸，共 18 个基点；每选一个点，要求后续操作逐点固定此前的基点。</p><p>每层提供一组用六个面转动写成的操作词。逐个验证它们固定此前的点，再对当前点作有限广度优先遍历。所得轨道大小依次为：</p><div class="table-scroll"><table><thead><tr><th>层</th><th>逐层轨道大小</th></tr></thead><tbody><tr><td>7 个角贴纸</td><td>24, 21, 18, 15, 12, 9, 6</td></tr><tr><td>11 个棱贴纸</td><td>24, 22, 20, 18, 16, 14, 12, 10, 8, 6, 2</td></tr></tbody></table></div><p>这些词全是合法操作，所以每个遍历到的点都属于实际稳定子的轨道。由上一章的稳定子链下界：</p>${d`|G|\ge(24\cdot21\cdots6)(24\cdot22\cdots6\cdot2).`}<p>第一项为 ${m`3^7(8\cdot7\cdots2)=3^7 8!`}；第二项为 ${m`2^{11}(12\cdot11\cdots3\cdot1)=2^{11}12!/2`}。两项相乘恰好是 ${m`|A|`}。</p><p>这里不需要声称给出的词生成整个稳定子；轨道子集就足以给出所需下界。操作词使用复合与取逆的有向无环图压缩为 48 个节点，不隐藏任何新生成元。</p>`)+
`<section class="experiment"><h3>在此设备上复核有限证书</h3><p>检验器从六个整数置换开始，重建每个操作词，检查固定点，并重新遍历 18 个轨道。检验器不调用外部代数库，也不预存全体魔方状态。</p><div class="experiment-actions" style="margin-top:13px"><button id="verifyCertificate" class="verify-button">验证完整证书 ↗</button></div><div id="certificateLog" class="certificate-log" role="status" aria-live="polite"></div><a class="proof-download" href="certificate.json" download>下载证书</a><a class="proof-download" href="certificate.mjs">检验器源码</a><a class="proof-download" href="generate-certificate.py">重建脚本</a></section>`+
proof('第三步 · 上下界相等，充分性成立',`<p>第二步经有限证书给出 ${m`|G|\ge|A|`}，第一步给出 ${m`G\subseteq A`} 且 ${m`|G|\le|A|`}。因这两个集合有限，包含关系与相同大小迫使 ${m`G=A`}。所以每一个满足三条约束的装配状态都可由合法转面得到。</p><p>这是一个包含有限、可重复检验步骤的证明。它不是“试了很多随机打乱都成立”的经验验证；也不是只报一个软件算出的阶而省略其与充分性的联系。</p>`)+
proof('证书检验为什么足够：逐项审计',`<ol><li>初始节点只能是本页定义的六个面置换；其余节点只能引用更早节点的积或逆。因此归纳可知每个节点确实属于 G。</li><li>第 i 层的每个生成元必须固定所有先前基点；检查失败即拒绝证书。因此这些生成元属于实际的 ${m`G_{i-1}`}。</li><li>广度优先遍历从 ${m`b_i`} 出发，只沿这些置换移动。每个记录的位置都可由一个合法词到达，故记录数不超过 ${m`|b_iG_{i-1}|`}。由于置换的集合有限，正向遍历也会覆盖所生成子群的轨道，但下界本身甚至不需要这个更强的事实。</li><li>将实际遍历数相乘，并与用阶乘独立计算的 ${m`|A|`} 比较。证书修改了词、固定点或轨道大小，都会被相应检查发现。</li></ol><p>重建脚本使用 SymPy 的 Schreier–Sims 方法寻找这些词；其正确性不作为前提，因为检验器独立验证所需的每个有限事实。</p>`)},
{id:'quotient',short:'核与商群',en:'KERNELS & QUOTIENTS',title:'忘记朝向，留下骨架',subtitle:'A homomorphism separates position from orientation.',lead:'一个复杂对象可以通过“忘记一部分信息”变得简单。忘掉角与棱的朝向，只保留它们去了哪里，得到一个群同态；被忘掉的全部自由度，恰好组成它的核。',body:
theorem('定理 8 · 位置投影的核与像',`<p>令 ${m`\pi:G\to S_8\times S_{12}`} 为角、棱位置投影，且</p>${d`P=\{(\sigma,\tau):\operatorname{sgn}\sigma=\operatorname{sgn}\tau\}.`}<p>则 ${m`\pi(G)=P`}，而</p>${d`K=\ker\pi\cong(\mathbb Z/3)^7\times(\mathbb Z/2)^{11}.`}${d`G/K\cong P.`}`)+
experiment('分别观察角与棱的位置投影',[['[R,U]²','(R U R\' U\')2'],['[R,U]³','(R U R\' U\')3']],"第一个例子角位置复原，但棱位置未必；第二个例子棱位置复原，但角位置未必。分别观察两个投影，避免把其中一个投影的单位元误认为整个核。")+
proof('证明：忘记朝向是群同态',`<p>一段操作先将每块送至中间位置，另一段操作再将它送到最终位置；块的移动不依赖其颜色朝向。因此按从左到右的复合约定，位置映射满足 ${m`\pi(gh)=\pi(g)\pi(h)`}，是群同态。</p><p>核 K 是所有块都回到各自位置的操作集合，但块可以仍有扭转或翻转。它是正规子群：若 ${m`k\in K,g\in G`}，则 ${m`\pi(gkg^{-1})=\pi(g)e\pi(g)^{-1}=e`}。</p>`,true)+
proof('证明：核与像的结构',`<p>在 K 中所有位置固定，复合只逐项叠加朝向坐标。由可达性定理，任意满足总和零的角、棱朝向都实际可达。前七个角朝向、前十一条棱朝向可自由指定，末项由总和唯一决定，故</p>${d`K\cong(\mathbb Z/3)^7\times(\mathbb Z/2)^{11}.`}<p>三条约束给出 ${m`\pi(G)\subseteq P`}。反过来，任取一对同奇偶的位置置换，将全部朝向设为零，便满足全部约束；可达性定理保证存在对应元素。因此 ${m`\pi(G)=P`}。</p><p>这里用到了上一章已经完成的充分性证明。如果只有不变量的必要性，不能直接断言投影满射或核中所有朝向都可达。</p>`)+
proof('证明：商群同构，而不仅是计数相同',`<p>由 K 正规，陪集组成商群。定义 ${m`\bar\pi:G/K\to P`} 为 ${m`gK\mapsto\pi(g)`}。若 ${m`gK=hK`}，则 ${m`h^{-1}g\in K`}，故 ${m`\pi(g)=\pi(h)`}，映射良定义。</p><p>它保持乘法；由 ${m`\pi(G)=P`} 得满射。若 ${m`\bar\pi(gK)=e`}，则 ${m`g\in K`}，从而 ${m`gK=K`}，故核平凡，映射单射。因此它是群同构。</p><p>相应地 ${m`|G|=|K|\,|P|`} 再次给出前章的计数。这个等式不意味着 ${m`G=K\times P`}；仅有核与商群信息，不能把整个群贸然写成直积。</p>`)+
`<p class="scope-note">至此，指尖的转动连接了生成元、置换、交换子、共轭、子群、群作用、稳定子、同态、核与商群。每个结论都在明确的约定下证明，并与同一套精确魔方状态相连。</p>`}
];
export function lessonHTML(i){const l=LESSONS[i];return `<p class="eyebrow">${String(i+1).padStart(2,'0')} / ${l.en}</p><h2 id="lessonTitle">${l.title}<small>${l.subtitle}</small></h2><p class="lead">${l.lead}</p>${l.body}${i<LESSONS.length-1?`<button class="next-chapter" data-next="${i+1}"><span>下一章 · ${LESSONS[i+1].short}</span><span>→</span></button>`:'<a class="next-chapter" href="../2026-fall/"><span>返回抽象代数课程</span><span>↗</span></a>'}`;}
