// Ordered pages remain independent of question selection. UI sits in the
// manuscript's available whitespace; a future scan renderer uses anchored overlays.
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function renderNotebook({questions,student,grades,tools}){
 const [a,b]=questions;
 const hand=(lines,wrong=false)=>`<div class="handwriting">${lines.map((line,i)=>`<p class="${wrong&&i===lines.length-1?'wrong-line':''}">${line}</p>`).join('')}</div>`;
 const score=i=>`<div class="grade-ink" data-grade-for="${i}"><button class="score-mark" data-edit-score="${i}" aria-label="修改第 ${questions[i].number} 题评分" title="点击分数，调整分项"><span data-total="${i}">${grades[i].scores.reduce((x,y)=>x+y,0)}</span><small>/ 10</small></button><span class="score-state" data-score-state="${i}">建议</span><button class="continuation-jump" data-jump-end="${i}">核对续页 ↘</button><div class="rubric-ink" data-rubric="${i}" hidden>${questions[i].criteria.map(([label,max,description],j)=>`<label class="criterion"><span title="${esc(description)}">${label}</span><span><input type="number" min="0" max="${max}" step="0.5" data-score="${i}:${j}" value="${grades[i].scores[j]}" aria-label="第 ${questions[i].number} 题${label}得分"> / ${max}</span></label>`).join('')}<button class="muted-ink" data-close-rubric="${i}">收起分项</button></div></div>`;
 const note=i=>`<div class="teacher-writing" data-note-for="${i}"><label class="sr-only" for="note-${i}">第 ${questions[i].number} 题评语</label><textarea id="note-${i}" class="ink-comment" data-feedback="${i}" rows="2" spellcheck="false" title="点击评语直接编辑">${esc(grades[i].feedback)}</textarea><div class="inline-actions"><button data-edit-score="${i}" class="muted-ink">分项</button><button data-confirm="${i}">确认 ✓</button><button data-next="${i}" class="muted-ink">下一题 →</button><span class="confirmed-note" data-confirm-state="${i}" aria-live="polite"></span></div></div>`;
 const region=(i,content,continuation=false)=>`<section class="answer-region ${continuation?'continuation':'question-start'}" data-question-region="${i}" ${continuation?'data-question-end':'data-question-start'}="${i}" tabindex="0" aria-label="第 ${questions[i].number} 题${continuation?'续答':'作答'}">${!continuation?score(i):''}<div class="original-answer">${content}</div>${continuation?note(i):''}</section>`;
 const page=(n,content)=>`<article class="scan-page" data-page-number="${n}" aria-label="扫描第 ${n} 页">${n===1?tools:`<div class="page-running"><span>${student.name} · <span data-document-kind>作业本</span>续页</span></div>`}${content}<footer class="paper-footer"><button class="book-previous" data-turn="-1" aria-label="上一页">← 上一页</button><span>模拟扫描稿 · ${n} / 3</span><span class="live-status" ${n===1?'id="status" role="status"':''}></span><button class="book-next" data-turn="1" aria-label="下一页">下一页 →</button></footer></article>`;
 const split=Math.max(1,Math.floor(b.lines.length/2));
 const cover=`<div class="page-spread cover-spread"><div class="cover-space" aria-hidden="true"></div><article class="scan-page notebook-cover" aria-label="作业本封面"><div class="cover-print"><header class="cover-school"><p>华东师范大学</p><span>EAST CHINA NORMAL UNIVERSITY</span></header><h1 class="cover-title">作业本</h1><p class="cover-english">EXERCISE BOOK</p><dl class="cover-fields"><div><dt>课程</dt><dd>${esc(a.paper.split(' · ')[0])}</dd></div><div><dt>姓名</dt><dd>${esc(student.name)}</dd></div><div><dt>学号</dt><dd>${esc(student.id)}</dd></div></dl><p class="cover-term">二〇二六 — 二〇二七学年 · 第一学期</p></div><footer class="paper-footer cover-footer"><a href="../" aria-label="返回课程主页">← 课程</a><button data-turn="1" aria-label="打开作业本">翻开作业本 →</button></footer></article></div>`;
 return cover+`<div class="page-spread">`+page(1,`<header class="document-heading"><span class="document-kind" data-document-kind>作业本</span><h1>${a.paper}</h1><p>姓名：${student.name}　　学号：${student.id}</p></header>${region(0,`<div class="paper-question"><strong>${a.number}.</strong> ${a.prompt}（10 分）</div>${hand(a.lines.slice(0,-1))}`)}<button class="page-next" data-jump-page="2">续答见下一页 ↓</button>`)
 +page(2,`${region(0,`<div class="continued-label">第 ${a.number} 题（续）</div>${hand(a.lines.slice(-1),!student.correct)}<p class="correction">${student.correct?'✓':a.annotation}</p>`,true)}${region(1,`<div class="paper-question"><strong>${b.number}.</strong> ${b.prompt}（10 分）</div>${hand(b.lines.slice(0,split))}`)}<button class="page-next" data-jump-page="3">续答见下一页 ↓</button>`)
 +`</div><div class="page-spread">`+page(3,`${region(1,`<div class="continued-label">第 ${b.number} 题（续）</div>${hand(b.lines.slice(split))}<p class="correction">✓</p>`,true)}<div class="submission-end"><span data-completion></span><button data-next-student>下一份作业 →</button></div>`)+`<div class="scan-page book-blank" aria-hidden="true"></div></div>`;
}
