import {nodes} from './graph-data.js';
const $=s=>document.querySelector(s),byId=new Map(nodes.map(n=>[n.id,n]));
let lang=localStorage.getItem('linear-language')||'en', selected='target',tab='statement',snapshot=null,camera={x:0,y:0,z:1},drag=null;
const tr=pair=>pair[lang==='zh'?1:0],escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const labels={done:['Checked by Lean','Lean 已验证'],conditional:['Checked implication · explicit inputs','已验证蕴含 · 显式输入'],assumption:['Required input · still open','所需输入 · 待证明'],pending:['Full theorem · still open','完整定理 · 待完成']};
function state(n){if(n.goal)return snapshot?.mainTheoremVerified?'done':'pending';if(n.scope==='assumption')return 'assumption';return snapshot?.declarations?.[n.decl]?.verified?n.scope:'pending';}
function math(el){if(!window.katex)return;for(const node of el.querySelectorAll('[data-tex]'))try{katex.render(node.dataset.tex,node,{throwOnError:false,displayMode:node.classList.contains('math')});}catch{node.textContent=node.dataset.tex;}}
function formula(f,cls='math'){return `<div class="${cls}" data-tex="${escape(f)}"></div>`;}
function status(n){return `<span class="pill ${state(n)}">${tr(labels[state(n)])}</span>`;}
function lineCount(n){return snapshot?.files?.find(f=>f.path===n.file)?.lineCount;}
function renderCards(){const wrap=$('#cards');wrap.replaceChildren();for(const n of nodes){const b=document.createElement('button');b.type='button';b.className=`node ${state(n)}${n.goal?' goal':''}`;b.dataset.node=n.id;b.style.left=n.x+'px';b.style.top=n.y+'px';b.setAttribute('aria-pressed',String(n.id===selected));b.setAttribute('aria-label',tr(n.title)+' · '+tr(labels[state(n)]));const count=lineCount(n);b.innerHTML=`<b>${escape(tr(n.title))}</b><span class="badge" aria-hidden="true">${({done:'✓',conditional:'◐',assumption:'?',pending:'○'})[state(n)]}</span><span class="summary">${escape(tr(n.summary))}</span>${n.goal?`<div class="target-lines">${formula(n.formula,'formula')}${formula('\\overline\\Delta\\ne0,\\quad\\operatorname{Soc}(Q)=\\mathbb C\\overline\\Delta','formula')}</div>`:formula(n.formula,'formula')}<span class="source-lines" title="Physical module lines; includes comments and blank lines. This count does not certify a theorem.">${count==null?tr(['Source not yet audited','源码尚未审计']):'Lean · '+count+' '+tr(['lines','行'])}</span>${n.deps.length?'<span class="port in" aria-hidden="true"></span>':''}${nodes.some(m=>m.deps.includes(n.id))?'<span class="port out" aria-hidden="true"></span>':''}`;b.onclick=()=>{if(Date.now()<(window.linearDragUntil||0))return;select(n.id);};b.oncontextmenu=e=>{e.preventDefault();select(n.id);tab='source';renderDetail();};wrap.append(b);}math(wrap);renderWires();}
function renderWires(){const svg=$('#wires');svg.querySelectorAll('g').forEach(g=>g.remove());for(const n of nodes)for(const id of n.deps){const d=byId.get(id),x1=d.x+280,y1=d.y+72,x2=n.x,y2=n.y+(n.goal?145:72),bend=Math.max(70,Math.abs(x2-x1)*.45),path=`M${x1},${y1} C${x1+bend},${y1} ${x2-bend},${y2} ${x2},${y2}`,g=document.createElementNS('http://www.w3.org/2000/svg','g');for(const cls of ['wire-shadow','wire','wire-shine']){const p=document.createElementNS(svg.namespaceURI,'path');p.setAttribute('d',path);p.setAttribute('class',cls+(d.scope==='assumption'?' assumption':'')+(n.id===selected?' selected':''));g.append(p);}svg.append(g);}}
function dependencyButtons(n){return n.deps.map(id=>`<button class="dep" data-select="${id}">${escape(tr(byId.get(id).title))} ${status(byId.get(id))}</button>`).join('');}
function renderDetail(){const n=byId.get(selected);$('#detailHeading').innerHTML=`<h2>${escape(tr(n.title))}</h2>${status(n)}`;$('.tabs').querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.tab===tab)));let html='';
if(tab==='statement'){html=n.statement.map(s=>`<p>${escape(tr(s))}</p>`).join('')+n.formulas.map(f=>formula(f)).join('');if(state(n)==='conditional')html+=`<p class="notice">${tr(['The verified theorem takes the displayed algebraic data as hypotheses. These inputs have not yet been constructed from all the hypotheses of Lemma 3.1.','已验证定理以所列代数数据为假设；尚未从引理 3.1 的全部原始假设构造这些输入。'])}</p>`;if(n.deps.length)html+=`<h3>${tr(['Dependencies','依赖'])}</h3>${dependencyButtons(n)}`;}
if(tab==='proof'){html=n.proof.map(p=>`<h3>${escape(p[lang==='zh'?1:0])}</h3><p>${escape(p[lang==='zh'?3:2])}</p>`).join('')+`<p><a href="proof/lemma31-excerpt.txt" target="_blank" rel="noopener">${tr(['Read the original lemma','阅读原引理'])} ↗</a></p>`;}
if(tab==='source'){const decl=snapshot?.declarations?.[n.decl];html=`<p><a href="source/${escape(n.file)}" target="_blank">${tr(['Full source module','完整源码模块'])} ↗</a></p>`;if(decl){html+=`<p>${escape(decl.path)} · ${tr(['line','行'])} ${decl.line}</p><pre>${escape(decl.code)}</pre><h3>${tr(['Kernel axioms','内核公理'])}</h3><pre>${escape((decl.axioms||[]).join('\n')||'[]')}</pre>`;}else{html+=`<p class="notice">${tr(['There is no verified theorem declaration for this card. The source contains a target definition or the interface still to construct. Compiling a definition does not prove its proposition.','本卡尚无已验证定理声明。源码包含目标定义或待构造接口；编译定义不等于证明该命题。'])}</p>`;}}
$('#panel').innerHTML=html;math($('#panel'));$('#panel').querySelectorAll('[data-select]').forEach(b=>b.onclick=()=>select(b.dataset.select));}
function paint(){ $('#scene').style.transform=`translate(${camera.x}px,${camera.y}px) scale(${camera.z})`;$('#zoom').textContent=Math.round(camera.z*100)+'%';}
function layout(){const r=$('#canvas').getBoundingClientRect(),cols=r.width/r.height>1.8?3:2,order=['reduction','duality','pairing','matrix','jacobian','primitive','generic','parameters','doublepoint','quotient'];order.forEach((id,i)=>{const n=byId.get(id);n.x=20+(i%cols)*315;n.y=40+Math.floor(i/cols)*190;});const target=byId.get('target');target.x=35+cols*315;target.y=Math.max(80,(Math.ceil(order.length/cols)*190-290)/2+40);const w=target.x+330,h=Math.ceil(order.length/cols)*190+55;$('#scene').style.width=w+'px';$('#scene').style.height=h+'px';$('#wires').style.width=w+'px';$('#wires').style.height=h+'px';renderCards();}
function fit(){const r=$('#canvas').getBoundingClientRect(),w=Math.max(...nodes.map(n=>n.x+(n.goal?310:280)))+20,h=Math.max(...nodes.map(n=>n.y+(n.goal?290:150)))+35;camera.z=Math.max(.2,Math.min(1.1,(r.width-38)/w,(r.height-55)/h));camera.x=(r.width-w*camera.z)/2;camera.y=(r.height-h*camera.z)/2;paint();}
function select(id){selected=id;history.replaceState(null,'','#node='+id);renderCards();renderDetail();const n=byId.get(id),box=$('#canvas').getBoundingClientRect(),width=n.goal?310:280,height=n.goal?290:150;camera.x=Math.max(15,Math.min(box.width-width*camera.z-15,box.width*.62-width*camera.z/2))-n.x*camera.z;camera.y=Math.max(16,(box.height-height*camera.z)/2)-n.y*camera.z;paint();}
function zoom(f,cx=$('#canvas').clientWidth/2,cy=$('#canvas').clientHeight/2){const z=Math.max(.2,Math.min(2.2,camera.z*f));camera.x=cx-(cx-camera.x)*z/camera.z;camera.y=cy-(cy-camera.y)*z/camera.z;camera.z=z;paint();}
function renderLanguage(){document.documentElement.lang=lang;$('#language').textContent=lang==='en'?'中文':'EN';for(const el of document.querySelectorAll('[data-en]'))el.textContent=el.dataset[lang];renderCards();renderDetail();$('#progress').textContent=tr(['Full Lemma 3.1 remains open.','完整引理 3.1 尚未完成。']);if(snapshot){const count=Object.keys(snapshot.declarations).length;$('#totalLines').textContent=`Lean · ${snapshot.files.reduce((s,f)=>s+f.lineCount,0)} ${tr(['lines','行'])}`;$('#progress').textContent=tr([`${count} checked declarations · Full Lemma 3.1 open`,`${count} 项已核验声明 · 完整引理 3.1 待证`]);}}
function evidence(){selected='target';renderCards();$('#detailHeading').innerHTML=`<h2>${tr(['Verification evidence','验证记录'])}</h2>${status(byId.get('target'))}`;$('.tabs').querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed','false'));const s=snapshot;$('#panel').innerHTML=s?`<p>${tr(['Local Lean build completed. The full theorem has not been proved.','本地 Lean 编译已完成；完整定理尚未证明。'])}</p><p>Lean ${escape(s.lean)}<br>mathlib ${escape(s.mathlib)}</p><p>${tr(['Checked at','核验时间'])}: ${escape(s.checkedAt)}</p><p class="notice">${tr(['Axiom audit checks sorryAx and custom axioms. It does not discharge theorem parameters. Read the complete types of the conditional results.','公理审计检查 sorryAx 与自定义公理，不能消除定理的参数假设；请同时阅读条件式结果的完整类型。'])}</p><p><a href="verification.txt">${tr(['Build and axiom audit log','编译及公理审计日志'])} ↗</a></p><p><a href="full-audit.json">${tr(['Whole-module axiom audit','完整模块公理审计'])} ↗</a></p><p><a href="snapshot.json">${tr(['Source hashes and declaration snapshot','源码指纹与声明快照'])} ↗</a></p><p><a href="source/CheckAxioms.lean">${tr(['Audit script','审计脚本'])} ↗</a></p><p><a href="linear-lean.zip" download>${tr(['Download reproducible project','下载可复现工程'])} ↓</a></p><h3>${tr(['Still to prove','仍待证明'])}</h3><ul><li>${tr(['Complete-intersection pairing existence','完全交配对的存在性'])}</li><li>${tr(['Scheja–Storch Jacobian theorem and family descent','Scheja–Storch Jacobian 定理及族下降'])}</li><li>${tr(['Arbitrary parameter lifts and the final socle statement','任意参数提升及最终 socle 结论'])}</li></ul>`:`<p>${tr(['The current source is being audited. No verification status is inferred from page loading.','当前源码尚在审计，页面加载不代表证明验证。'])}</p>`;}
$('#language').onclick=()=>{lang=lang==='en'?'zh':'en';localStorage.setItem('linear-language',lang);renderLanguage();};$('.tabs').querySelectorAll('button').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;renderDetail();});$('#fit').onclick=fit;$('#plus').onclick=()=>zoom(1.15);$('#minus').onclick=()=>zoom(1/1.15);$('#evidence').onclick=evidence;
const canvas=$('#canvas');canvas.addEventListener('wheel',e=>{e.preventDefault();const r=canvas.getBoundingClientRect();zoom(Math.exp(-e.deltaY*.0015),e.clientX-r.left,e.clientY-r.top);},{passive:false});canvas.addEventListener('pointerdown',e=>{if(e.button!==0)return;drag={id:e.pointerId,x:e.clientX,y:e.clientY,ox:e.clientX,oy:e.clientY,moved:false};canvas.setPointerCapture(e.pointerId);});canvas.addEventListener('pointermove',e=>{if(!drag||e.pointerId!==drag.id)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(Math.hypot(e.clientX-drag.ox,e.clientY-drag.oy)>5)drag.moved=true;if(drag.moved){camera.x+=dx;camera.y+=dy;canvas.classList.add('panning');paint();}drag.x=e.clientX;drag.y=e.clientY;});const end=e=>{if(drag?.moved)window.linearDragUntil=Date.now()+200;else if(drag){const r=document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-node]');if(r)select(r.dataset.node);}drag=null;canvas.classList.remove('panning');};canvas.addEventListener('pointerup',end);canvas.addEventListener('pointercancel',()=>{drag=null;canvas.classList.remove('panning');});canvas.addEventListener('keydown',e=>{if(e.key==='Home'){e.preventDefault();fit();}if(e.key==='+'||e.key==='='){e.preventDefault();zoom(1.15);}if(e.key==='-'){e.preventDefault();zoom(1/1.15);}});new ResizeObserver(()=>{layout();paint();}).observe(canvas);
if(location.hash.startsWith('#node=')){const id=location.hash.slice(6);if(byId.has(id))selected=id;}
layout();renderLanguage();requestAnimationFrame(fit);window.addEventListener('load',()=>{math($('#cards'));math($('#panel'));});fetch('snapshot.json?v=20261005-3').then(r=>{if(!r.ok)throw Error(r.status);return r.json();}).then(s=>{snapshot=s;renderLanguage();}).catch(()=>{$('#progress').textContent=tr(['Verification snapshot unavailable · Full theorem open','核验快照未加载 · 完整定理待证']);});
