import {suits,ranks,name,rank,codes,outShuffle,inShuffle,encodeFive,targetRoute} from './models.js?v=20260927a';
const $=id=>document.getElementById(id),escape=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let language='zh';try{language=new URLSearchParams(location.search).get('lang')||localStorage.getItem('shengmeng-course-language-v1')||'zh';}catch{}if(language!=='en')language='zh';
const t=(zh,en)=>language==='en'?en:zh,txt=pair=>pair[language==='en'?1:0];
let tricks=[],current='five-card';
function card(id,back=false){if(back)return '<div class="playing-card back" role="img" aria-label="'+t('隐藏的牌','Hidden card')+'"><span class="card-suit">?</span></div>';const r=ranks[rank(id)-1],s=suits[id%4];return `<div class="playing-card ${[1,2].includes(id%4)?'red':''}" role="img" aria-label="${name(id)}"><span class="card-corner">${r}<small>${s}</small></span><span class="card-suit">${s}</span><span class="card-corner bottom" aria-hidden="true">${r}<small>${s}</small></span></div>`;}
function header(){
 $('course-link').href='../2026-fall/?view=lesson&section=1.6&lang='+language+'#card-magic';
document.documentElement.lang=language==='en'?'en':'zh-CN';document.title=t('纸牌与群论 · 孟晟','Card Magic & Group Theory · Sheng Meng');document.querySelector('h1').innerHTML=t('纸牌与群论<span>Card Magic <i>&</i> Group Theory</span>','Card Magic <i>&</i> Group Theory<span>纸牌与群论</span>');$('lead').textContent=t('看见奇迹，追踪置换，亲手拆解其中的数学。','See the effect. Track the permutation. Uncover the mathematics.');$('language').textContent=t('EN','中文');$('language').setAttribute('aria-label',t('Switch to English','切换为中文'));$('course-link').textContent=t('返回 §1.6 ↗','Back to §1.6 ↗');$('algebra-link').textContent=t('抽象代数','Abstract Algebra');$('rubik-link').textContent=t('魔方与群论 ↗','Rubik’s Cube & Groups ↗');const fsLabel=document.fullscreenElement?t('退出全屏','Exit fullscreen'):t('全屏','Fullscreen');$('fullscreen').title=fsLabel;$('fullscreen').setAttribute('aria-label',fsLabel);$('fullscreen').setAttribute('aria-pressed',String(!!document.fullscreenElement));$('fullscreen').hidden=!document.documentElement.requestFullscreen;}
function theory(trick){$('theory').innerHTML=`<div class="theory-heading"><h2>${t('揭开原理','Behind the magic')}</h2><small>${t('保留悬念 · 点击 ＋ 按需展开','Keep the surprise · Expand + when ready')}</small></div>${trick.details.map(d=>`<details class="proof"><summary>${escape(txt(d.title))}</summary><div class="proof-body">${d.blocks.map(b=>`<p>${escape(txt(b.text))}</p>${b.tex?`<div class="formula" data-tex="${escape(b.tex)}"></div>`:''}`).join('')}</div></details>`).join('')}<p class="source"><a href="${trick.source.url}" target="_blank" rel="noopener">${escape(txt(trick.source.label))} ↗</a></p>`;document.querySelectorAll('[data-tex]').forEach(node=>{try{node.innerHTML=window.katex.renderToString(node.dataset.tex,{displayMode:true,throwOnError:true});}catch{node.textContent=node.dataset.tex;}});}
function render(){header();const trick=tricks.find(x=>x.id===current)||tricks[0];current=trick.id;$('trick-tabs').innerHTML=tricks.map((x,i)=>`<button type="button" data-tab="${x.id}" aria-current="${x.id===current}" aria-controls="laboratory"><b>0${i+1}</b><span>${escape(txt(x.title))}<small>${['CYCLIC ENCODING','PERMUTATION ORDER','BINARY ROUTES'][i]}</small></span></button>`).join('');$('laboratory').innerHTML=`<div class="lab-header"><div><h2>${escape(txt(trick.title))}</h2><p>${escape(txt(trick.effect))}</p></div><span class="tag">${t('可操作 · 可验证','PLAY · TRACE · VERIFY')}</span></div><div class="lab-stage"></div>`;theory(trick);if(current==='five-card')five();else if(current==='perfect-shuffle')shuffle();else target();}
function five(){
 let hand=[46,10,4,25,51],step=0;const root=document.querySelector('.lab-stage');
 function draw(){const e=encodeFive(hand),display=step?[...e.shown,e.hidden]:hand;root.innerHTML=`<p class="stage-label">0${step+1} / 04 · ${t(...[['任选五张牌','Choose five cards'],['四张明牌，一张秘密','Four cards. One secret.'],['顺序就是信息','Order carries information'],['揭晓隐藏的牌','Reveal the hidden card']][step])}</p><div class="hand">${display.map((id,i)=>`<div>${card(id,step>0&&step<3&&i===4)}${step===0?`<select class="card-choice" data-card-slot="${i}" aria-label="${t('选择第 '+(i+1)+' 张牌','Choose card '+(i+1))}">${Array.from({length:52},(_,k)=>`<option value="${k}" ${k===id?'selected':''}>${name(k)}</option>`).join('')}</select>`:`<p class="card-under">${i===0?t('起点与花色','BASE & SUIT'):i===4?t('隐藏牌','HIDDEN'):step>=2?e.code[i-1]:t('编码牌','CODE')}</p>`}</div>`).join('')}</div><div class="controls"><button type="button" data-random>${t('重新抽五张','Draw five new cards')}</button><button type="button" data-prev ${step===0?'disabled':''}>${t('← 上一步','← Back')}</button><button type="button" class="primary" data-next>${t(...[['藏一张，摆出四张 →','Hide one, arrange four →'],['尝试解码 →','Decode the message →'],['翻开验证 →','Reveal and verify →'],['重新开始 ↻','Start again ↻']][step])}</button></div><div class="explanation" aria-live="polite">${step===0?t('可以更换任意一张。选择已出现的牌时，两张牌交换位置，保证五张牌互不相同。','Change any card. Choosing a card already in the hand swaps their positions, keeping all five distinct.'):step===1?t('第一张告诉你花色。剩下三张的排列藏着一个 1—6 的数字。猜猜看？','The first card gives the suit. The next three encode a number from 1 to 6. Can you guess it?'):step===2?t(`后三张按点数及花色排序后编码为 ${e.code}，表示前进 ${e.distance} 步。`,`Rank the three code cards: ${e.code} encodes ${e.distance} steps forward.`):t(`隐藏牌是 ${name(e.hidden)}。任意五张不同的牌都可以这样编码。`,`The hidden card is ${name(e.hidden)}. The code works for any five distinct cards.`)}</div>${step>=2?`<div class="code-table">${codes.map((code,i)=>`<span class="${code===e.code?'active':''}">${code} = ${i+1}</span>`).join('')}</div><div class="rank-ring" aria-label="${t('点数前进路线','Rank path')}">${Array.from({length:e.distance+1},(_,i)=>`<span class="in-route ${i===e.distance?'destination':''}">${ranks[(rank(e.base)-1+i)%13]}</span>${i<e.distance?' → ':''}`).join('')}</div>`:''}`;}
 root.onclick=event=>{const b=event.target.closest('button');if(!b)return;if(b.hasAttribute('data-random')){const deck=Array.from({length:52},(_,i)=>i);for(let i=51;i>0;i--){const j=Math.floor(Math.random()*(i+1));[deck[i],deck[j]]=[deck[j],deck[i]];}hand=deck.slice(0,5);step=0;}else if(b.hasAttribute('data-next'))step=(step+1)%4;else if(b.hasAttribute('data-prev'))step=Math.max(0,step-1);draw();};root.onchange=event=>{const i=Number(event.target.dataset.cardSlot),value=Number(event.target.value);if(!Number.isInteger(i))return;const j=hand.indexOf(value);if(j!==-1)hand[j]=hand[i];hand[i]=value;step=0;draw();};draw();
}
function snapshot(grid){return new Map(Array.from(grid?.querySelectorAll('[data-moving-card]')||[],node=>[node.dataset.movingCard,node.getBoundingClientRect()]));}
function animateGrid(grid,before){if(window.matchMedia?.('(prefers-reduced-motion: reduce)').matches)return;grid?.querySelectorAll('[data-moving-card]').forEach(node=>{const old=before.get(node.dataset.movingCard);if(!old)return;const now=node.getBoundingClientRect(),dx=old.left-now.left,dy=old.top-now.top;if(dx||dy)node.animate?.([{transform:`translate(${dx}px,${dy}px)`},{transform:'translate(0,0)'}],{duration:650,easing:'cubic-bezier(.25,.8,.25,1)'});});}
function shuffle(){
 const root=document.querySelector('.lab-stage');let size=8,deck=Array.from({length:8},(_,i)=>i),count=0;
 function init(){root.innerHTML=`<div class="config"><label for="deck-size">${t('牌堆大小','Deck size')}</label><select id="deck-size"><option value="8" ${size===8?'selected':''}>8 ${t('张 · 三次复原','cards · order 3')}</option><option value="52" ${size===52?'selected':''}>52 ${t('张 · 八次复原','cards · order 8')}</option></select></div><p class="stage-label">${t('牌面编号固定 · 位置随洗牌变化','CARD LABELS STAY FIXED · POSITIONS MOVE')}</p>${size===8?`<div class="shuffle-track">${deck.map(i=>`<div class="shuffle-card" data-card="${i}" style="--slot:${i}">${i+1}</div>`).join('')}</div>`:'<div class="deck-grid"></div>'}<div class="counter"></div><div class="controls"><button type="button" data-reset>${t('复位','Reset')}</button><button type="button" class="primary" data-shuffle>${t('完美外洗一次 →','One perfect out-shuffle →')}</button></div><p class="explanation" aria-live="polite"></p><p class="small-note">${t('始终从原上半副开始，两半严格逐张交替。','Always start with the top half and alternate cards strictly.')}</p>`;draw();}
 function draw(){root.querySelector('.counter').textContent=count+' / '+(size===8?3:8);if(size===8)root.querySelectorAll('[data-card]').forEach(c=>c.style.setProperty('--slot',deck.indexOf(+c.dataset.card)));else {const grid=root.querySelector('.deck-grid'),before=snapshot(grid);grid.innerHTML=deck.map(i=>`<span data-moving-card="${i}">${i+1}</span>`).join('');animateGrid(grid,before);}root.querySelector('.explanation').textContent=count===0?t('从初始顺序出发。每按一次，执行同一个置换 σ。','Start in order. Each click applies the same permutation σ.'):deck.every((x,i)=>x===i)?t(`第 ${count} 次：整副牌已恢复原序。`,`Shuffle ${count}: the entire deck is back in order.`):t(`第 ${count} 次。现在的顺序：${deck.map(i=>i+1).join(' · ')}`,`Shuffle ${count}. Current order: ${deck.map(i=>i+1).join(' · ')}`);}
 root.onclick=event=>{if(event.target.closest('[data-shuffle]')){deck=outShuffle(deck);count++;draw();}else if(event.target.closest('[data-reset]')){deck=Array.from({length:size},(_,i)=>i);count=0;draw();}};root.onchange=event=>{if(event.target.id==='deck-size'){size=Number(event.target.value);deck=Array.from({length:size},(_,i)=>i);count=0;init();}};init();
}
function target(){
 const root=document.querySelector('.lab-stage');let position=7,route=targetRoute(position),step=0,deck=Array.from({length:52},(_,i)=>i);
 function draw(){const before=snapshot(root.querySelector('.deck-grid'));const currentIndex=deck.indexOf(0);root.innerHTML=`<form class="config" id="target-form"><label for="target-position">${t('送到第几张？','Target position?')}</label><input id="target-position" name="position" type="number" inputmode="numeric" min="1" max="52" step="1" required value="${position}"><button type="submit">${t('生成路线','Build route')}</button></form><p class="small-note">${t('金色是选中的牌，虚线框是目标位置。位置从 1 开始数。','Gold marks the chosen card; the dashed frame marks the target. Positions start at 1.')}</p><div class="deck-grid">${deck.map((id,i)=>`<span data-moving-card="${id}" class="${id===0?'tracked':''} ${i===position-1?'target':''}" aria-label="${t('位置','Position')} ${i+1}: ${id===0?t('选中的牌','chosen card'):id+1}">${id===0?'★':id+1}</span>`).join('')}</div><div class="route">${route.steps.length?route.steps.map((type,i)=>`<span class="${i<step?'done':i===step?'next':''}">${type} · ${type==='I'?t('内洗','IN'):t('外洗','OUT')}</span>`).join(''):t('已在顶端，无需洗牌','Already on top; no shuffle needed')}</div><div class="controls"><button type="button" data-reset>${t('复位路线','Reset route')}</button><button type="button" class="primary" data-route-next ${step===route.steps.length?'disabled':''}>${step===route.steps.length?t('已到达目标 ✓','Target reached ✓'):t('执行下一次洗牌 →','Perform next shuffle →')}</button></div><p class="explanation" aria-live="polite">${t(`当前在第 ${currentIndex+1} 张；目标是第 ${position} 张。`,`Currently at position ${currentIndex+1}; target position ${position}.`)}</p><p class="small-note">${position-1} = (${route.bits||'0'})₂ · ${t('索引路径','Index path')}: ${route.indices.slice(0,step+1).join(' → ')}<br>${t('操作按时间从左到右执行；群乘法书写顺序相反。','Perform operations left to right in time; group products are written in reverse order.')}</p>`;animateGrid(root.querySelector('.deck-grid'),before);root.querySelector('form').onsubmit=event=>{event.preventDefault();const input=root.querySelector('input');if(!input.checkValidity())return;position=Number(input.value);route=targetRoute(position);step=0;deck=Array.from({length:52},(_,i)=>i);draw();};}
 root.onclick=event=>{if(event.target.closest('[data-route-next]')&&step<route.steps.length){deck=(route.steps[step++]==='I'?inShuffle:outShuffle)(deck);draw();}else if(event.target.closest('[data-reset]')){step=0;deck=Array.from({length:52},(_,i)=>i);draw();}};draw();
}
$('trick-tabs').onclick=event=>{const button=event.target.closest('[data-tab]');if(button)location.hash=button.dataset.tab;};
window.addEventListener('hashchange',()=>{if(tricks.length){current=location.hash.slice(1);render();}});
$('language').onclick=()=>{language=language==='zh'?'en':'zh';try{localStorage.setItem('shengmeng-course-language-v1',language);}catch{}render();};
$('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen?.();}catch{}header();};document.addEventListener('fullscreenchange',header);
const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),30000);
try{const response=await fetch('../2026-fall/lesson-groups/sections/1.6.json?v=20260927-card-magic-v1',{signal:controller.signal});if(!response.ok)throw Error(response.status);const payload=await response.json();tricks=payload.book.entries.find(e=>e.id==='card-magic').extension.tricks;current=location.hash.slice(1)||tricks[0].id;render();}catch(error){$('laboratory').innerHTML='<div id="load-note" role="status">'+t('暂时无法加载实验，请重新加载。','The experiments could not load. Please retry.')+'<br><button type="button" id="retry-load">'+t('重新加载','Reload')+'</button></div>';$('retry-load').onclick=()=>location.reload();console.error(error);}finally{clearTimeout(timeout);}
