import {completionRecord,publicRecord,rankedRecords,migrateRecord} from './campaign-record-data.mjs?v=nebula-63';
import {GALAXIES} from './galaxy-campaign.mjs?v=nebula-63';
import {groups} from './model.mjs?v=nebula-63';
import {levels} from './challenge-model.mjs?v=nebula-63';
export function mountCampaignRecords({getJourney,getAccount,t,api}){
 const link=document.createElement('link');link.rel='stylesheet';link.href=new URL('../../../visuals/group-sudoku/records.css?v=20260923-sand-links1',import.meta.url);document.head.append(link);
 document.body.insertAdjacentHTML('beforeend',"<dialog id=\"recordsDialog\" class=\"records-dialog\" aria-labelledby=\"recordsTitle\"><header><h2 id=\"recordsTitle\">通关记录</h2><button id=\"recordsClose\" type=\"button\">关闭</button></header><div class=\"records-body\"><p id=\"recordsIntro\" class=\"records-intro\">全员可查看。姓名显示拼音首字母，学号部分隐藏。</p><div class=\"records-actions\"><button id=\"recordsRefresh\" type=\"button\">刷新</button><p id=\"recordsStatus\" class=\"records-status\" role=\"status\" aria-live=\"polite\"></p><button id=\"recordsSync\" class=\"records-primary\" type=\"button\" hidden>重试同步</button></div><div class=\"records-scroll\" tabindex=\"0\" aria-labelledby=\"recordsTitle\"><div id=\"recordsList\"></div>\n\n<details><summary id=\"recordsTeacherSummary\">教师导出完整记录</summary><form id=\"recordsTeacherForm\"><label id=\"recordsPasswordLabel\" for=\"recordsPassword\">教师口令</label><input id=\"recordsPassword\" type=\"password\" autocomplete=\"current-password\" enterkeyhint=\"go\" required><button id=\"recordsTeacherLogin\" type=\"submit\">登录</button></form></details><div id=\"recordsAdminActions\" hidden><button id=\"recordsExport\" type=\"button\">导出 CSV</button><button id=\"recordsLogout\" type=\"button\">退出教师查看</button></div></div></div></dialog>");
 const $=id=>document.getElementById(id);let admin='';
 const storageKey='generators-completion-records-v1';let records={};
 try{records=JSON.parse(localStorage.getItem(storageKey))||{};records=Object.fromEntries(Object.entries(records).map(([id,r])=>[id,migrateRecord(r,GALAXIES)]));}catch{}
 function save(completed=false){const account=getAccount(),r=completionRecord(account,getJourney(),GALAXIES,records[account.id],completed?new Date().toISOString():null);if(r){records[account.id]=r;try{localStorage.setItem(storageKey,JSON.stringify(records));}catch{}}}
 function level(r){return String(r.highest+1).padStart(2,'0')+'. '+GALAXIES[r.highest].name;}
 function refresh(){save();$('recordsTitle').textContent=t('通关记录','Completion records');$('recordsIntro').textContent=t('最高通关关卡优先；同关卡按通关时间从早到晚排列。姓名显示拼音首字母。','Highest completed level first; ties are ordered by the time reached, earliest first. Student names use pinyin initials.');$('recordsStatus').textContent=t('已从本机更新 · 生成元云端记录尚未接入','Updated from this device · Generator cloud records not connected');
 for(const [id,zh,en] of [['recordsClose','关闭','Close'],['recordsRefresh','刷新','Refresh'],['recordsTeacherSummary','教师导出完整记录','Teacher: export full records'],['recordsPasswordLabel','教师口令','Teacher password'],['recordsTeacherLogin','登录','Log in'],['recordsExport','导出 CSV','Export CSV'],['recordsLogout','退出教师查看','Exit teacher view']])$(id).textContent=t(zh,en);
 const list=$('recordsList');list.replaceChildren(...rankedRecords(Object.values(records)).map((raw,index)=>{const r=publicRecord(raw,!!admin),card=document.createElement('article');card.className='completion-card';const h=document.createElement('h3');h.textContent=String(index+1)+'. '+(document.documentElement.lang==='en'?r.name.replace(/^游客 /,'Guest '):r.name);h.title=h.textContent;
 const sid=document.createElement('span');sid.className='record-id';sid.textContent=r.studentId;const state=document.createElement('span');state.className='record-level';state.textContent=level(r);
 const date=document.createElement('time');if(r.reachedAt)date.dateTime=r.reachedAt;const parts=r.reachedAt?new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}).formatToParts(new Date(r.reachedAt)):[],part=type=>parts.find(p=>p.type===type)?.value;
 const full=part('year')+'.'+part('month')+'.'+part('day')+' '+part('hour')+':'+part('minute')+':'+part('second'),f=document.createElement('span'),d=document.createElement('span');f.className='record-date-full';f.textContent=full;d.className='record-date-short';d.textContent=part('month')+'.'+part('day')+' '+part('hour')+':'+part('minute');if(!r.reachedAt){f.textContent='—';d.textContent='—';}date.append(f,d);date.title=t('达到最高关卡时间（北京时间）','Highest level reached (China Standard Time)')+' '+(r.reachedAt?full:t('旧记录未保存时间','Time not saved for this earlier record'));card.append(h,sid,state,date);return card;}));
 if(!list.children.length){const p=document.createElement('p');p.className='records-empty';p.textContent=t('暂无通关记录。','No completed levels yet.');list.append(p);}}
 $('cosmicRecords').onclick=()=>{refresh();$('recordsDialog').showModal();};$('recordsClose').onclick=()=>$('recordsDialog').close();$('recordsRefresh').onclick=refresh;
 $('recordsTeacherForm').onsubmit=async e=>{e.preventDefault();$('recordsTeacherLogin').disabled=true;try{const data=await api('/api/admin/session',{method:'POST',body:{password:$('recordsPassword').value}});admin=data.token;$('recordsPassword').value='';$('recordsAdminActions').hidden=false;refresh();$('recordsStatus').textContent=t('身份已验证；仅导出本机生成元记录','Verified; export includes local generator records only');}catch(e){$('recordsStatus').textContent=e.message;}finally{$('recordsTeacherLogin').disabled=false;}};
 $('recordsLogout').onclick=()=>{admin='';$('recordsAdminActions').hidden=true;refresh();};$('recordsDialog').addEventListener('close',()=>{admin='';$('recordsAdminActions').hidden=true;$('recordsPassword').value='';});
 $('recordsExport').onclick=()=>{if(!admin)return;const rows=[['排名','身份','学号','姓名','最高关卡','达到最高关卡时间（UTC）'],...rankedRecords(Object.values(records)).map((raw,i)=>{const r=publicRecord(raw,true);return[i+1,r.kind==='guest'?'游客':'学生',r.studentId,r.name,level(r),r.reachedAt];})],quote=x=>{const q=String.fromCharCode(34),v=String(x??'').replace(/^[=+@-]/,String.fromCharCode(39)+'$&');return q+v.replaceAll(q,q+q)+q;},csv='\ufeff'+rows.map(r=>r.map(quote).join(',')).join('\r\n'),url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='生成元-通关记录.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 return {save};
}
