import {mountEcnuConstellation} from './ecnu-constellation.mjs?v=nebula-72';
import {mountGroupExtension} from './group-extension.mjs?v=nebula-70';
import {mountCampaignRecords} from './campaign-records.mjs?v=nebula-66';
import {mountBalanceControls} from './galaxy-balance.mjs?v=nebula-70';
import {mountCosmicControls} from './cosmic-controls.mjs?v=nebula-70';
import {GALAXIES,progress,unlocked,complete} from './galaxy-campaign.mjs?v=nebula-69';
import {GalaxyScene} from './galaxy-scene.mjs?v=nebula-70';
import {mountStellarChallenge} from './stellar-challenge.mjs?v=nebula-70';
import {groups} from './model.mjs?v=nebula-66';
import {levels,normalizeJourney,completedCount} from './challenge-model.mjs?v=nebula-66';
import {createRecordsApi} from '../../../visuals/group-sudoku/records-api.mjs?v=records6-oneline';
import {RECORDS_CONFIG} from '../../../visuals/group-sudoku/records-config.mjs?v=records6-oneline';
const $=id=>document.getElementById(id),read=k=>{try{return JSON.parse(localStorage.getItem(k));}catch{return null;}},write=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v));}catch{}};
let en=false,index=0,account=read('group-sudoku-guest-session')?.account||read('group-sudoku-local-guest'),done=0,world,lookup='',lookupId='',run=0,abort,transition=false;
if(!account){account={id:'local-guest-'+crypto.randomUUID(),kind:'guest',name:'',local:true};write('group-sudoku-local-guest',account);}
const t=(zh,eng)=>en?eng:zh,api=createRecordsApi({config:RECORDS_CONFIG,t}),key=()=>`generators-galaxy-demo:${account.id}`;
let journey=normalizeJourney(read('generators-campaign-v1:'+account.id),GALAXIES,groups),challenge,records,extension;done=completedCount(journey,GALAXIES,groups);
document.body.insertAdjacentHTML('afterbegin',`<div id="cosmos"><canvas id="cosmosCanvas" aria-label="三维星系场景"></canvas><div class="cosmos-vignette"></div></div>
<section id="galaxyUI" aria-label="星系选择"><div class="cosmic-top"><a href="../" aria-label="返回代数学" class="cosmic-home">⌂</a><div class="cosmic-tools"><button id="cosmicAccount">◈ <span></span></button><button id="cosmicLang">EN</button><button id="cosmicSettings" aria-label="设置">⚙</button><button id="cosmicFull" aria-label="全屏">□</button></div></div>
<div class="cosmic-heading"><p id="cosmicEyebrow"></p><h1 id="cosmicTitle"></h1><p id="cosmicSubtitle"></p></div>
<div class="sector-info"><div class="sector-kicker" id="sectorKicker"></div><h2 id="sectorName"></h2><div id="sectorGroup"></div><p id="sectorDefinition"></p><p id="sectorState"></p></div><button id="demoComplete" class="cosmic-demo demo-corner"></button>
<button id="previousGalaxy" class="neighbor-label previous"></button><button id="nextGalaxy" class="neighbor-label next"></button><div id="galaxyWatermark" aria-hidden="true"></div><div class="cosmic-bottom"><span id="cosmicHint"></span><span id="demoLabel"></span></div><div id="flightNotice" role="status"></div></section>
<button id="returnGalaxies" class="cosmic-return">← 星图</button>
<dialog id="cosmicLogin" class="cosmic-dialog"><button class="cosmic-close" aria-label="关闭">×</button><p class="dialog-eyebrow">IDENTITY</p><h2 id="loginTitle"></h2><p id="identityText"></p><div id="identityChoices"><button id="studentIdentity" class="cosmic-primary"></button><button id="guestIdentity"></button></div><form id="cosmicStudentForm" hidden><label id="sidLabel" for="cosmicStudentId"></label><input id="cosmicStudentId" inputmode="numeric" autocomplete="off" maxlength="11" pattern="[0-9]{11}" required><p id="cosmicStudentName"></p><p id="cosmicLoginStatus" role="status"></p><button id="confirmIdentity" class="cosmic-primary" disabled></button></form><p id="identityNote"></p></dialog>
<dialog id="cosmicPreferences" class="cosmic-dialog"><button class="cosmic-close" aria-label="关闭">×</button><p class="dialog-eyebrow">SETTINGS</p><h2 id="prefsTitle"></h2><label class="cosmic-setting"><span id="motionLabel"></span><input id="cosmicMotion" type="checkbox" checked></label><button id="prefsIdentity"></button><p id="prefsStudent"></p><button id="resetDemo"></button><p id="localNote"></p></dialog>`);
const icon=path=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${path}</svg>`;
const icons={account:icon('<circle cx="12" cy="8" r="3.3"/><path d="M5 21v-3a7 7 0 0 1 14 0v3"/>'),settings:icon('<path d="M4 7h16M4 17h16"/><circle cx="9" cy="7" r="2.5" fill="#0a1324"/><circle cx="16" cy="17" r="2.5" fill="#0a1324"/>'),full:icon('<path d="M9 4H4v5m11-5h5v5M4 15v5h5m11-5v5h-5"/>'),restore:icon('<rect x="7" y="7" width="10" height="10"/>')};
$('cosmicAccount').innerHTML=icons.account+'<span></span>';$('cosmicSettings').innerHTML=icons.settings;$('cosmicFull').innerHTML=icons.full;
function tip(id,label){const b=$(id);b.dataset.tip=label;b.setAttribute('aria-label',label);}
const savedMotion=read('generators-nebula-motion');$('cosmicMotion').checked=savedMotion!==false;
function render(){
 extension?.sync();
 tip('cosmicAccount',t('身份与学生信息','Identity and student information'));tip('cosmicLang',t('切换英文','Switch to Chinese'));tip('cosmicSettings',t('航行设置','Flight settings'));tip('cosmicFull',document.fullscreenElement?t('退出全屏','Exit fullscreen'):t('全屏','Fullscreen'));
 const g=GALAXIES[index],open=unlocked(index,done),finished=index<done; $('galaxyUI').setAttribute('aria-label',t('星系选择','Galaxy selection'));$('cosmicSettings').setAttribute('aria-label',t('设置','Settings'));document.querySelectorAll('.cosmic-close').forEach(b=>b.setAttribute('aria-label',t('关闭','Close'))); $('cosmosCanvas').setAttribute('aria-label',t('三维星系：','3D galaxy: ')+g.name+' · '+g.order+t('个天体',' celestial bodies'));$('cosmosCanvas').dataset.planetCount=world?.systems[index].userData.planets.length||g.order;
 $('cosmicAccount').lastElementChild.textContent=account.kind==='student'?account.name:(account.name?t('游客 ','Guest ')+account.name:t('游客','Guest'));$('cosmicLang').textContent=en?'中文':'EN';$('cosmicTitle').textContent=t('让群星，由你生成。','A universe, generated by you.');$('cosmicEyebrow').textContent=t('以宇宙为画布，以群论绘星河','THE COSMOS AS CANVAS · GROUPS AS ART');$('cosmicSubtitle').textContent=t('一个天体，一个群元素。','One celestial body. One group element.');$('sectorKicker').textContent=`${String(index+1).padStart(2,'0')} / ${String(GALAXIES.length).padStart(2,'0')}  ·  ${t('星系','SECTOR')}`;$('sectorName').textContent=en?g.en:g.zh;$('sectorGroup').textContent=`${g.name}  /  ${g.order} ${t('个天体','bodies')}`;$('sectorState').textContent=finished?t('已探索 · 可以再次进入','Explored · Ready to revisit'):open?t('航道已开启','Navigation ready'):t('完成前一星系后解锁','Explore the previous sector to unlock');$('demoComplete').textContent=t('模拟通关 → 下一星系','Simulate completion → Next');$('demoComplete').disabled=!open||transition;$('cosmicHint').textContent=t('左右拖动切换星系 · ← →','Swipe or use ← → to explore galaxies');$('demoLabel').textContent=t('通关进度保存在本机','PROGRESS SAVED ON THIS DEVICE');$('returnGalaxies').textContent=t('← 返回星图','← Star map');
 $('galaxyWatermark').textContent=g.name;$('galaxyWatermark').classList.toggle('completed',finished);
 const definitions={F56:['𝔽₈ 上的仿射变换 x ↦ ax+b。56 阶非交换群，中心只有单位元。','Affine maps x ↦ ax+b over 𝔽₈. A non-abelian group of order 56 with trivial centre.'],A5:['五个对象的偶置换群，也是正二十面体的旋转群。60 阶，最小的不可解群。','Even permutations of five objects; rotations of an icosahedron. Order 60, the smallest non-solvable group.'],C4:['C 表示循环群。C₄ 是四阶循环群，同构于模 4 加法群 ℤ/4ℤ。','C stands for cyclic. C₄ is the cyclic group of order four, isomorphic to the additive group ℤ/4ℤ.'],S3:['三个对象的全部置换，以复合为运算。最小的非交换群。','All permutations of three objects under composition. The smallest non-abelian group.'],V4:['ℤ/2ℤ × ℤ/2ℤ。三个非单位元的平方都等于单位元。','ℤ/2ℤ × ℤ/2ℤ. Each of its three nonidentity elements squares to the identity.'],D4:['正方形的对称群：四种旋转、四种反射，以复合为运算。','The symmetries of a square: four rotations and four reflections, composed as transformations.'],Q8:['{±1, ±i, ±j, ±k}，i² = j² = k² = ijk = −1。四元数乘法不交换。','{±1, ±i, ±j, ±k}, with i² = j² = k² = ijk = −1. Quaternion multiplication is noncommutative.'],S4:['S₄ 是可解群，因此一般四次方程可用根式求解。','S₄ is solvable, so the general quartic equation is solvable by radicals.'],S5:['S₅ 不可解，因此一般五次方程不存在根式通解。特殊五次方程仍可能用根式求解。','S₅ is not solvable: there is no radical formula for the general quintic. Particular quintics may still be solvable by radicals.']};
 $('sectorDefinition').textContent=t(...definitions[g.key]);$('sectorState').textContent=open?t('点击中央星系探索','Click the central galaxy to explore'):t('完成前一星系后解锁','Complete the previous galaxy to unlock');

 for(const [id,offset] of [['previousGalaxy',-1],['nextGalaxy',1]]){const adjacent=GALAXIES[index+offset],button=$(id);button.hidden=!adjacent;if(adjacent){button.textContent='';button.setAttribute('aria-label',t(offset<0?'查看前一星系 ':'查看后一星系 ',offset<0?'Previous galaxy ':'Next galaxy ')+adjacent.name);button.onclick=()=>select(index+offset);}}

 $('loginTitle').textContent=t('选择航行身份','Choose your identity');$('identityText').textContent=account.kind==='student'?`${account.name} · ${account.id}`:t('游客探索 · 无需等待连接','Explore as a guest · No waiting');$('studentIdentity').textContent=t('学号登录','Student login');$('guestIdentity').textContent=t('游客进入','Enter as guest');$('sidLabel').textContent=t('11 位学号','11-digit student ID');$('confirmIdentity').textContent=t('确认姓名并进入','Confirm name and enter');$('identityNote').textContent=t('使用群数独同一学号与姓名核对服务。','Uses the same student identity service as Group Sudoku.');$('prefsTitle').textContent=t('航行设置','Flight settings');$('motionLabel').textContent=t('星云动态与视差','Nebula motion and parallax');$('prefsIdentity').textContent=t('学生信息 / 切换登录','Student information / Switch player');$('prefsStudent').textContent=account.kind==='student'?`${account.name} · ${account.id}`:t('当前：游客','Current: guest');$('resetDemo').textContent=t('重置模拟航程','Reset demo journey');$('localNote').textContent=t('各难度分别判定，进度保存在本机。','Each difficulty is evaluated; progress is stored on this device.');document.documentElement.lang=en?'en':'zh-CN';if(world){world.unlocked=Math.min(done,GALAXIES.length-1);world.completed=done;world.colors=GALAXIES.map(g=>journey[g.key].passed/levels(groups[g.key]).length);}window.dispatchEvent(new Event('cosmic-ui-change'));
}
function select(i){if(world?.challenge||transition||!Number.isInteger(i)||!GALAXIES[i])return;index=i;world?.select(i);render();}
function assign(next){if(account.id===next.id){account=next;render();return;}account=next;journey=normalizeJourney(read('generators-campaign-v1:'+account.id),GALAXIES,groups);done=completedCount(journey,GALAXIES,groups);challenge?.close();index=Math.min(done,GALAXIES.length-1);world?.select(index);render();}
$('cosmicAccount').onclick=()=>{$('cosmicLogin').showModal();};$('cosmicSettings').onclick=()=>{$('cosmicPreferences').showModal();};$('prefsIdentity').onclick=()=>{$('cosmicPreferences').close();$('cosmicLogin').showModal();};document.querySelectorAll('.cosmic-close').forEach(b=>b.onclick=()=>b.closest('dialog').close());
$('cosmicLang').onclick=()=>{en=!en;render();};$('cosmicFull').onclick=async()=>{const root=document.documentElement,active=document.fullscreenElement||document.webkitFullscreenElement,fn=active?(document.exitFullscreen||document.webkitExitFullscreen):(root.requestFullscreen||root.webkitRequestFullscreen);if(typeof fn!=='function'){$('flightNotice').textContent=t('当前浏览器不支持全屏，可横屏浏览','Fullscreen is unavailable in this browser. Try landscape view.');$('flightNotice').classList.add('visible');setTimeout(()=>$('flightNotice').classList.remove('visible'),2600);return;}try{await fn.call(active?document:root);}catch{} };document.addEventListener('fullscreenchange',()=>{$('cosmicFull').innerHTML=document.fullscreenElement?icons.restore:icons.full;tip('cosmicFull',document.fullscreenElement?t('退出全屏','Exit fullscreen'):t('全屏','Fullscreen'));});
$('cosmicMotion').onchange=()=>{if(world)world.motion=$('cosmicMotion').checked;write('generators-nebula-motion',$('cosmicMotion').checked);};$('resetDemo').onclick=()=>{done=0;write(key(),0);select(0);$('cosmicPreferences').close();};
$('studentIdentity').onclick=()=>{$('cosmicStudentForm').hidden=false;$('cosmicStudentId').focus();};
$('cosmicStudentId').oninput=async()=>{const id=$('cosmicStudentId');id.value=id.value.replace(/\D/g,'').slice(0,11);const own=++run;abort?.abort();abort=new AbortController();lookup='';lookupId='';$('confirmIdentity').disabled=true;$('cosmicStudentName').textContent='';$('cosmicLoginStatus').textContent='';if(id.value.length!==11)return;$('cosmicLoginStatus').textContent=t('正在核对姓名…','Checking your name…');try{const data=await api('/api/lookup',{method:'POST',body:{studentId:id.value},signal:abort.signal});if(own!==run)return;lookup=data.lookupToken;lookupId=id.value;$('cosmicStudentName').textContent=data.name;$('cosmicLoginStatus').textContent=t('请核对姓名。','Please confirm your name.');$('confirmIdentity').disabled=false;}catch(e){if(own===run)$('cosmicLoginStatus').textContent=e.message;}};
$('cosmicStudentForm').onsubmit=async e=>{e.preventDefault();if(!lookup||lookupId!==$('cosmicStudentId').value)return;$('confirmIdentity').disabled=true;const own=run;try{const data=await api('/api/login',{method:'POST',body:{mode:'student',studentId:lookupId,lookupToken:lookup},signal:abort.signal});if(own!==run)return;assign(data.account);write('group-sudoku-last-student',lookupId);$('cosmicLogin').close();}catch(e){if(own===run){$('cosmicLoginStatus').textContent=e.message;$('confirmIdentity').disabled=false;}}};
$('cosmicLogin').addEventListener('close',()=>{run++;abort?.abort();lookup='';lookupId='';$('cosmicStudentId').value='';$('cosmicStudentName').textContent='';$('cosmicStudentForm').hidden=true;});
$('guestIdentity').onclick=()=>{const guest=read('group-sudoku-guest-session')?.account||read('group-sudoku-local-guest');assign(guest);$('cosmicLogin').close();};
function enterSelected(){if(!unlocked(index,done)||transition||world.challenge)return;challenge.open(GALAXIES[index].key,groups[GALAXIES[index].key],GALAXIES[index].name,journey[GALAXIES[index].key].passed);} $('returnGalaxies').onclick=()=>challenge?.close();
$('demoComplete').onclick=()=>{if(transition||!unlocked(index,done))return;done=complete(index,done);write(key(),done);transition=true;render();$('flightNotice').textContent=index<GALAXIES.length-1?t('航道已解锁 · 正在跃迁','Route unlocked · In transit'):t('模拟航程完成','Demo journey complete');$('flightNotice').classList.add('visible');setTimeout(()=>{transition=false;if(index<GALAXIES.length-1)select(index+1);else render();setTimeout(()=>$('flightNotice').classList.remove('visible'),1500);},650);};
try{world=new GalaxyScene($('cosmosCanvas'),select,enterSelected);world.motion=$('cosmicMotion').checked;world.select(index);}catch(error){$('cosmicHint').textContent=t('3D 渲染不可用，请开启浏览器硬件加速。','3D unavailable. Enable browser hardware acceleration.');document.body.classList.add('cosmos-fallback');console.error(error);}
challenge=mountStellarChallenge({world,t,getIdentity:()=>account.id,onExit:()=>render(),onPass:(key,stage,seconds)=>{const r=journey[key];r.passed=Math.max(r.passed,stage+1);r.times[stage]=seconds;write('generators-campaign-v1:'+account.id,journey);records?.save(true);done=completedCount(journey,GALAXIES,groups);render();}});
extension=mountGroupExtension({t,getGalaxy:()=>GALAXIES[index],getJourney:()=>journey,groups});
render();window.CourseHealth?.appReady();

if(!world) $('cosmicHint').textContent=t('3D 渲染不可用，请开启浏览器硬件加速。','3D unavailable. Enable browser hardware acceleration.');

window.addEventListener('galaxy-language',e=>{en=e.detail;render();challenge?.sync();});

window.addEventListener('keydown',e=>{if(!document.body.classList.contains('galaxy-mode')||document.querySelector('dialog[open]')||e.target.closest('input,textarea,select')||!['ArrowLeft','ArrowRight'].includes(e.key))return;e.preventDefault();select(Math.max(0,Math.min(GALAXIES.length-1,index+(e.key==='ArrowRight'?1:-1))));});

mountCosmicControls({t,api,read,write,getAccount:()=>account,assign,getProgress:()=>done,clearJourney:()=>{challenge?.close();journey=normalizeJourney(null,GALAXIES,groups);done=0;write('generators-campaign-v1:'+account.id,journey);select(0);},render});

mountBalanceControls(world);

records=mountCampaignRecords({getJourney:()=>journey,getAccount:()=>account,t,api});
$('cosmicPreferences').insertAdjacentHTML('beforeend','<a class="disk-lab-link" href="galaxy-disk-lab.html">星盘图谱 · 20 种草图 ↗</a>');
$('cosmicLogin').showModal();
mountEcnuConstellation();
