import test from 'node:test';import assert from 'node:assert/strict';
import {BalancePose,createBalanceInput,pointerPose} from './galaxy-balance.mjs';
function fixture(request){const host=new EventTarget();host.document=new EventTarget();host.document.hidden=false;host.screen={orientation:new EventTarget()};host.screen.orientation.angle=0;host.isSecureContext=true;host.DeviceOrientationEvent=request?{requestPermission:request}:{};let timer;host.setTimeout=fn=>(timer=fn,1);host.clearTimeout=()=>timer=null;const poses=[],states=[];const input=createBalanceInput({host,onTilt:p=>poses.push(p),onState:s=>states.push(s)});return {host,input,poses,states,timeout:()=>timer?.(),sample:(beta,gamma)=>{const e=new Event('deviceorientation');Object.assign(e,{beta,gamma});host.dispatchEvent(e);}};}
test('calibrates from held posture, ignores absent readings and bounds tilt',()=>{const p=new BalancePose();assert.equal(p.sample(null,3),null);assert.deepEqual(p.sample(50,10),{x:0,z:0});assert.equal(p.sample(50.3,10.3).x,0);assert.ok(p.sample(70,30).x>0);const extreme=p.sample(-100,-70);assert.ok(Math.abs(extreme.x)<=Math.PI/15+1e-12);assert.ok(Math.abs(extreme.z)<=Math.PI/15+1e-12);assert.deepEqual(p.sample(10,10,90),{x:0,z:0});assert.ok(p.sample(10,30,90).x>0);});
test('wraps through beta boundary instead of flipping',()=>{const p=new BalancePose();p.sample(179,0);assert.ok(p.sample(-179,0).x>0);assert.ok(p.sample(-179,0).x<.02);});
test('permission denial never attaches active sensing',async()=>{let calls=0;const f=fixture(async()=>{calls++;return 'denied';});await f.input.enable();f.sample(10,10);assert.equal(calls,1);assert.equal(f.input.state,'denied');assert.equal(f.poses.length,0);f.input.dispose();});
test('authorized readings, recenter, disable and background suspension',async()=>{const f=fixture(async()=>'granted');await f.input.enable();assert.equal(f.input.state,'waiting');f.sample(null,null);assert.equal(f.input.state,'waiting');f.sample(45,0);f.sample(60,15);assert.equal(f.input.state,'active');assert.ok(f.poses.at(-1).x>0);f.input.recenter();f.sample(60,15);assert.deepEqual(f.poses.at(-1),{x:0,z:0});f.host.document.hidden=true;f.host.document.dispatchEvent(new Event('visibilitychange'));const n=f.poses.length;f.sample(10,2);assert.equal(f.poses.length,n);f.host.document.hidden=false;f.host.document.dispatchEvent(new Event('visibilitychange'));f.sample(30,8);assert.equal(f.input.state,'active');f.input.disable();const m=f.poses.length;f.sample(10,2);assert.equal(f.poses.length,m);f.input.dispose();});
test('unavailable sensor and insecure origin report actionable states',async()=>{const f=fixture();await f.input.enable();f.timeout();assert.equal(f.input.state,'unavailable');assert.equal(f.input.enabled,false);f.host.isSecureContext=false;await f.input.enable();assert.equal(f.input.state,'insecure');f.input.dispose();});

test('mouse movement gives bounded tilt in both axes',()=>{assert.deepEqual(pointerPose(0,0),{x:-0,z:-0});assert.ok(pointerPose(1,1).x<0);assert.ok(pointerPose(1,1).z<0);assert.deepEqual(pointerPose(20,-20),pointerPose(1,-1));});
