import * as T from 'three';
import {createAsset,assetTypes} from './design-assets.js';
import {routeBridge} from './design-routing.js';
export function createDesignTools({bar,layout,members,scene,camera,controls,anchor,materials,bridgeGroup}){
 const ui=document.createElement('section');ui.id='designTools';ui.innerHTML=`<h2>难民营设计</h2><label><input id="designEdit" type="checkbox"> 左键编辑（可选）</label><label>选择层级<select id="designLevel"><option value="building">整组建筑 / 新增元素</option><option value="detail">单件装饰 / 构件</option></select></label><small>右键选中并拖动整组建筑，默认左键观察。需要调整装饰时，开启左键编辑并选择单件装饰；拖动在水平面移动。</small><label><input id="designSnap" type="checkbox"> 吸附到 1 米网格</label><p id="designSelection">尚未选择</p><label>添加元素<select id="designType">${Object.entries(assetTypes).map(([id,n])=>`<option value="${id}">${n}</option>`).join('')}</select></label><button id="designAdd">添加到视线中心</button><button id="designDelete">删除新增元素</button><label>连桥起点<select id="bridgeFrom"></select></label><label>连桥终点<select id="bridgeTo"></select></label><button id="bridgeAdd">自动连接平台锚点</button><select id="bridgeSelect" aria-label="已有连桥"></select><button id="bridgeDelete">删除所选连桥</button><p id="designMessage" role="status"></p>`;
 bar.append(ui);const $=id=>ui.querySelector('#'+id),canvas=document.getElementById('world');let api,added=[],connections=[],edits={},selected=null,drag=null,timer;
 const baseCount=layout.length,detailMap=new Map(),ray=new T.Raycaster(),mouse=new T.Vector2(),plane=new T.Plane(new T.Vector3(0,1,0),-.4);
 // Stable construction-order keys identify individual meshes and instances across reloads.
 for(const [id,objects]of members){let n=0;for(const root of objects)root.traverse(o=>{if(!o.isMesh)return;const key=id+':'+n++;o.userData.designKey=key;o.userData.designOwner=id;detailMap.set(key,o);});}
 const highlight=new T.Box3Helper(new T.Box3(),0xffd276);highlight.material.depthTest=false;highlight.material.transparent=true;highlight.material.opacity=.9;highlight.renderOrder=10000;highlight.visible=false;scene.add(highlight);
 function objectBox(o,index){o.updateWorldMatrix(true,false);if(index===undefined)return new T.Box3().setFromObject(o);const m=new T.Matrix4();o.getMatrixAt(index,m);if(!o.geometry.boundingBox)o.geometry.computeBoundingBox();return o.geometry.boundingBox.clone().applyMatrix4(m.premultiply(o.matrixWorld));}
 function parts(sel){const obj=detailMap.get(sel.key),tag=obj?.userData.designGroups?.[sel.instance];if(!tag)return [{key:sel.key,instance:sel.instance}];const out=[];for(const [key,o]of detailMap)if(o.userData.designOwner===sel.id)o.userData.designGroups?.forEach((g,i)=>{if(g===tag)out.push({key,instance:i});});return out;}
 function paint(){if(!selected){highlight.visible=false;return;}const b=new T.Box3();if(selected.key){for(const p of parts(selected)){const o=detailMap.get(p.key);if(o)b.union(objectBox(o,p.instance));}}else {const row=layout.find(r=>r[0]===selected.id);if(row&&!row[8])b.set(new T.Vector3(anchor+row[4]-row[6]/2,-1,-row[5]-row[7]/2),new T.Vector3(anchor+row[4]+row[6]/2,row[0]==='07'?20:12,-row[5]+row[7]/2));else for(const o of members.get(selected.id)||[])if(o.visible)b.union(objectBox(o));}highlight.box.copy(b);highlight.visible=!b.isEmpty();$('designSelection').textContent=selected.key?'已选构件：'+selected.key+(selected.instance===undefined?'':' / '+selected.instance):'已选：'+selected.id;}
 function updateLists(){for(const id of ['bridgeFrom','bridgeTo']){const old=$(id).value;$(id).replaceChildren(...layout.filter(b=>!['tree','boat','bench'].includes(b[8])).map(b=>new Option(b[0]+' '+b[1],b[0])));if(layout.some(b=>b[0]===old))$(id).value=old;}if($('bridgeFrom').value===$('bridgeTo').value&&$('bridgeTo').options.length>1)$('bridgeTo').selectedIndex=1;$('bridgeSelect').replaceChildren(...connections.map((c,i)=>new Option(c.join(' ↔ '),i)));paint();}
 function rebuild(){clearTimeout(timer);for(const o of [...bridgeGroup.children]){o.geometry.dispose();bridgeGroup.remove(o);}let failed=0;for(const [a,b]of connections){const path=routeBridge(layout.find(r=>r[0]===a),layout.find(r=>r[0]===b),layout);if(!path){failed++;continue;}for(let i=1;i<path.length;i++){const p=path[i-1],q=path[i],len=Math.hypot(q[0]-p[0],q[1]-p[1]);if(len<.01)continue;const m=new T.Mesh(new T.BoxGeometry(3,.28,len),materials.timber);m.position.set(anchor+(p[0]+q[0])/2,.25,-(p[1]+q[1])/2);m.rotation.y=Math.atan2(q[0]-p[0],-(q[1]-p[1]));m.receiveShadow=true;bridgeGroup.add(m);}}$('designMessage').textContent=failed?`${failed} 条连接无可行路径，请分开重叠平台`:'连桥随平台锚点更新';paint();}
 function add(row){const asset=createAsset(row.type,materials);asset.object.position.set(anchor+row.east,row.type==='boat'?-1:.4,-row.north);asset.object.userData.layoutId=row.id;scene.add(asset.object);members.set(row.id,new Set([asset.object]));layout.push([row.id,assetTypes[row.type],0,0,row.east,row.north,asset.width,asset.depth,row.type]);added.push({id:row.id,type:row.type});}
 function setDetail(key,offset){const [k,index]=key.split('@'),o=detailMap.get(k);if(!o)return;const old=edits[key]||[0,0],delta=new T.Vector3(offset[0]-old[0],0,-offset[1]+old[1]);o.updateWorldMatrix(true,false);const inv=new T.Matrix4().copy(index===undefined?o.parent.matrixWorld:o.matrixWorld).invert(),zero=new T.Vector3().applyMatrix4(inv);delta.applyMatrix4(inv).sub(zero);if(index!==undefined){const m=new T.Matrix4();o.getMatrixAt(Number(index),m);m.elements[12]+=delta.x;m.elements[13]+=delta.y;m.elements[14]+=delta.z;o.setMatrixAt(Number(index),m);o.instanceMatrix.needsUpdate=true;o.computeBoundingBox();o.computeBoundingSphere();}else o.position.add(delta);o.updateMatrixWorld(true);edits[key]=offset;paint();}
 function serialize(){return {version:2,assets:added.map(a=>{const b=layout.find(b=>b[0]===a.id);return {...a,east:b[4],north:b[5]};}),connections:connections.map(c=>c.slice()),decorations:structuredClone(edits)};}
 function validate(doc){if(doc.version===1)return;const assets=doc.assets||[],ids=new Set(layout.slice(0,baseCount).map(b=>b[0]));if(assets.length>150)throw Error('最多150个新增元素');for(const a of assets){if(!/^new-[a-z0-9-]+$/.test(a.id)||ids.has(a.id)||!Object.hasOwn(assetTypes,a.type)||![a.east,a.north].every(n=>Number.isFinite(n)&&Math.abs(n)<=10000))throw Error('新增元素数据无效');ids.add(a.id);}if(!Array.isArray(doc.connections)||doc.connections.length>100||doc.connections.some(c=>!Array.isArray(c)||c.length!==2||c[0]===c[1]||c.some(id=>!ids.has(id)||['tree','boat','bench'].includes(assets.find(a=>a.id===id)?.type))))throw Error('连桥数据无效');for(const [key,v]of Object.entries(doc.decorations||{})){const [k,index]=key.split('@'),o=detailMap.get(k);if(!o||index!==undefined&&(!o.isInstancedMesh||!/^\d+$/.test(index)||Number(index)>=o.count)||!Array.isArray(v)||v.length!==2||!v.every(n=>Number.isFinite(n)&&Math.abs(n)<=10000))throw Error('装饰数据无效');}}
 function restore(doc){validate(doc);for(const key of Object.keys(edits))setDetail(key,[0,0]);edits={};for(const a of added){for(const o of members.get(a.id)||[]){o.traverse(m=>{if(m.isMesh){m.geometry.dispose();if(!Object.values(materials).includes(m.material))m.material.dispose();}});scene.remove(o);}members.delete(a.id);}layout.splice(baseCount);added=[];for(const a of doc.assets||[])add(a);connections=(doc.connections||[['01B','R1'],['R1','05N'],['05N','01C'],['01C','02'],['02','G'],['01B','R3'],['R3','05S'],['05S','07']]).map(c=>c.slice());for(const [key,v]of Object.entries(doc.decorations||{}))setDetail(key,v);selected=null;updateLists();}
 function changed(){api.changed();updateLists();rebuild();}
 $('designAdd').onclick=()=>{if(added.length>=150)return;api.remember();const p=controls.target;add({id:'new-'+Date.now().toString(36),type:$('designType').value,east:Math.round(p.x-anchor),north:Math.round(-p.z)});selected={id:added.at(-1).id};changed();api.select(selected.id);};
 $('designDelete').onclick=()=>{if(!selected||!added.some(a=>a.id===selected.id)){$('designMessage').textContent='请选择一个新增元素';return;}api.remember();const doc=serialize();doc.assets=doc.assets.filter(a=>a.id!==selected.id);doc.connections=doc.connections.filter(c=>!c.includes(selected.id));restore(doc);changed();};
 $('bridgeAdd').onclick=()=>{const a=$('bridgeFrom').value,b=$('bridgeTo').value;if(a===b||connections.some(c=>c.includes(a)&&c.includes(b))||connections.length>=100)return;api.remember();connections.push([a,b]);changed();};
 $('bridgeDelete').onclick=()=>{const i=Number($('bridgeSelect').value);if(!connections[i])return;api.remember();connections.splice(i,1);changed();};
 function point(e){const r=canvas.getBoundingClientRect();mouse.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(mouse,camera);return ray.ray.intersectPlane(plane,new T.Vector3());}
 function pick(e){point(e);const objects=[];for(const [id,set]of members)for(const root of set)if(root.visible)root.traverse(o=>{if(o.isMesh&&o.visible){let visible=true;for(let a=o.parent;a;a=a.parent)if(!a.visible)visible=false;if(visible)objects.push(o);}});const hit=ray.intersectObjects(objects,false)[0];if(!hit)return null;let id=hit.object.userData.designOwner;for(let o=hit.object;o&&!id;o=o.parent)id=o.userData.layoutId;if(!id)return null;if(e.button!==2&&$('designLevel').value==='detail'&&hit.object.userData.designKey)return {id,key:hit.object.userData.designKey,instance:hit.instanceId};return {id};}
 function down(e){if(e.button!==2&&(!$('designEdit').checked||e.button!==0))return;e.preventDefault();e.stopImmediatePropagation();selected=pick(e);paint();if(!selected)return;api.select(selected.id);const p=point(e);if(!p)return;api.remember();const controlsEnabled=controls.enabled;controls.enabled=false;canvas.setPointerCapture(e.pointerId);const b=layout.find(b=>b[0]===selected.id),key=selected.key+(selected.instance===undefined?'':'@'+selected.instance);drag={pointer:e.pointerId,controlsEnabled,start:p.clone(),east:b[4],north:b[5],key,offset:(edits[key]||[0,0]).slice(),parts:selected.key?parts(selected).map(p=>{const key=p.key+(p.instance===undefined?'':'@'+p.instance);return {key,offset:(edits[key]||[0,0]).slice()};}):[]};}
 function move(e){if(!drag||drag.pointer!==e.pointerId)return;e.preventDefault();e.stopImmediatePropagation();const p=point(e);if(!p)return;let x=p.x-drag.start.x,y=drag.start.z-p.z;if($('designSnap').checked){x=Math.round(x);y=Math.round(y);}if(Math.abs(drag.east+x)>10000||Math.abs(drag.north+y)>10000)return;if(selected.key){for(const p of drag.parts)setDetail(p.key,[p.offset[0]+x,p.offset[1]+y]);api.changed();}else api.move([{id:selected.id,east:drag.east+x,north:drag.north+y}]);paint();}
 function up(e){if(!drag||drag.pointer!==e.pointerId)return;e.stopImmediatePropagation();controls.enabled=drag.controlsEnabled;drag=null;if(canvas.hasPointerCapture(e.pointerId))canvas.releasePointerCapture(e.pointerId);rebuild();}
 canvas.addEventListener('contextmenu',e=>{e.preventDefault();e.stopImmediatePropagation();},true);canvas.addEventListener('auxclick',e=>{if(e.button===2){e.preventDefault();e.stopImmediatePropagation();}},true);canvas.addEventListener('click',e=>{if($('designEdit').checked){e.preventDefault();e.stopImmediatePropagation();}},true);canvas.addEventListener('pointerdown',down,true);canvas.addEventListener('pointermove',move,true);canvas.addEventListener('pointerup',up,true);canvas.addEventListener('pointercancel',up,true);$('designEdit').onchange=()=>{if(!$('designEdit').checked){drag=null;controls.enabled=true;}};
 return {serialize,validate,restore,bind(a){api=a;},update(){updateLists();if(!drag){clearTimeout(timer);timer=setTimeout(rebuild,180);}},select(id){selected=id==='all'?null:{id};paint();}};
}
