"""Publish only project sources and verified evidence, never .lake or local user data."""
from pathlib import Path
import datetime, hashlib, json, os, re, shutil, subprocess, sys, zipfile

project, destination = map(Path, sys.argv[1:3])
names = {'ImportedProjectiveCechVanishing.lean': ['imported_projective_laurent_cech_positive_twist_vanishing'],
 'ImportedProjectiveCechFiniteness.lean': ['imported_projective_laurent_cech_cohomology_finite'],
 'ActualRelativeCechCycleModule.lean': ['actual_relative_cech_cycles_rees_module'],
 'ActualRelativeCechGradedAction.lean': ['actual_relative_ideal_section_mul_mem',
                                         'actual_relative_cech_graded_action_on_classes'],
 'ActualRelativeCechMultiplication.lean': ['actual_base_ideal_local_pullback_mem',
                                           'actual_relative_cech_graded_cocycle_multiplication'],
 'ActualProperCechCover.lean': ['exists_actual_proper_affine_cech_cover'],
 'ActualCechModule.lean': ['actual_closed_cech_module_action'],
 'ActualCechScalars.lean': ['actual_cech_difference_scale',
                            'actual_cech_boundary_scale',
                            'actual_cech_pullback_scale_zero',
                            'actual_cech_pullback_scale_one',
                            'actual_closed_cech_scalar_on_cocycles'],
 'RelativeCechFormalComparison.lean': ['actual_relative_power_inclusion_comp',
                                       'actual_relative_formal_functions_bijective_of_cech_kernel_vanishing'],
 'RelativeCechSectionLifting.lean': ['actual_relative_section_lifting_of_cech_kernel_vanishing'],
 'ActualCechKernelLifting.lean': ['actual_closed_cech_lifting_of_cohomology_kernel_bound'],
 'ActualCechCohomologyExact.lean': ['actual_closed_cech_cohomology_exact'],
 'ActualCechClosedTransition.lean': ['actual_closed_cech_connecting_naturality'],
 'ActualCechClosedObstruction.lean': ['actual_closed_cech_obstruction_independent_of_lifts',
                                      'actual_closed_cech_obstruction_zero_iff',
                                      'actual_closed_cech_connecting_exact'],
 'ActualCechClosedLifting.lean': ['actual_section_restriction_naturality',
                                  'actual_cech_pullback_difference',
                                  'actual_closed_cech_local_lift_pullback',
                                  'actual_closed_cech_section_lifting_criterion'],
 'ActualCechSections.lean': ['actual_section_restriction_trans',
                             'actual_cech_boundary_difference_zero',
                             'actual_cech_global_sections_exact'],
 'RelativeFormalInjectivity.lean': ['actual_relative_formal_functions_injective'],
 'AdicComparisonInjectivity.lean': ['adic_comparison_injective_of_uniform_kernel_bound'],
 'RelativeKernelBound.lean': ['actual_relative_kernel_uniform_bound'],
 'RelativeKernelFiniteness.lean': ['actual_relative_kernel_rees_module_finite'],
 'RelativeKernelIntegral.lean': ['integral_of_all_valuation_subrings',
                                 'actual_relative_kernel_monomial_integral'],
 'ReesFractionField.lean': ['polynomial_scaled_mem_rees', 'rees_algebra_polynomial_fraction_field'],
 'RelativeKernelWeighted.lean': ['actual_relative_kernel_weighted_valuation_mem'],
 'AffineValuationBase.lean': ['actual_affine_ring_base_sections',
                              'actual_affine_ring_base_dominant',
                              'actual_affine_valuation_generic_dominant'],
 'WeightedIdealExtension.lean': ['weighted_subring_ideal_mul', 'weighted_ideal_extension_mem'],
 'RelativeKernelValuative.lean': ['actual_proper_birational_valuation_lift',
                                  'actual_relative_kernel_valuative_contraction'],
 'ProperBirationalGlobalFiniteness.lean': ['actual_proper_birational_global_functions_finite'],
 'RelativeKernelFiltration.lean': ['actual_relative_kernel_ideal_mono',
                                   'actual_relative_kernel_ideal_mul',
                                   'actual_relative_kernel_filtration'],
 'PullbackIdealProducts.lean': ['actual_affine_ideal_pullback_mul',
                                'actual_open_ideal_pullback_mul',
                                'actual_ideal_pullback_mul_over_affine_base',
                                'actual_ideal_pullback_pow_over_affine_base'],
 'AffinePullbackIdeal.lean': ['actual_affine_ideal_pushforward', 'actual_affine_ideal_pullback'],
 'RelativeFormalApproximation.lean': ['actual_relative_quotient_map_constant',
                                      'actual_relative_restriction_transition',
                                      'actual_relative_quotient_map_transition',
                                      'actual_relative_formal_functions_bijective_of_uniform_approximation'],
 'AdicApproximationComparison.lean': ['adic_comparison_bijective_of_uniform_approximation'],
 'ActualProperNegativityFull.lean': ['actual_proper_negativity_of_actual_formal_functions'],
 'GlobalClosedFiberConnectedness.lean': ['actual_closed_fibers_connected_of_affine_formal_functions'],
 'AffineNeighborhoodFiber.lean': ['actual_restricted_fiber_connected_iff'],
 'ActualProperSupportDichotomy.lean': ['actual_proper_support_dichotomy_of_connected_closed_fibers'],
 'ClosedFiberCompleteness.lean': ['actual_closed_fiber_proper_over_ground_field'],
 'ClosedFiberSupportDetection.lean': ['actual_fiber_closed_subset_dichotomy_of_closed_points'],
 'ConstructibleClosedPoint.lean': ['noetherian_constructible_contains_closed_point'],
 'RelativeFormalConnectedness.lean': ['actual_closed_fiber_connected_of_relative_formal_functions'],
 'ClosedFiberInfinitesimalIdempotent.lean': ['actual_closed_fiber_infinitesimal_nontrivial_idempotent'],
 'ClosedPointFiberThickenings.lean': ['actual_closed_point_ideal_support',
                                      'actual_closed_point_ideal_top',
                                      'actual_closed_point_ideal_top_maximal',
                                      'actual_closed_point_completion_local'],
 'RelativeInfinitesimalIdempotents.lean': ['actual_relative_power_inclusion_point',
                                           'actual_compatible_clopen_nontrivial_idempotent',
                                           'actual_relative_infinitesimal_nontrivial_idempotent'],
 'RelativeFormalFunctionsMap.lean': ['actual_relative_power_projection_square',
                                     'actual_relative_formal_functions_evaluation'],
 'ActualProperNegativityIff.lean': ['actual_proper_negativity_effectivity_iff'],
 'ActualProperNegativity.lean': ['actual_proper_negativity_part_one'],
 'ActualProperAffineNegativity.lean': ['actual_proper_affine_negativity_part_one'],
 'HartshorneCartierModification.lean': ['exists_actual_hartshorne_cartier_modification'],
 'BirationalCycleComposition.lean': ['actual_cycle_push_at_codimension_one_preimage',
                                     'actual_proper_birational_weil_pushforward_comp'],
 'CanonicalCartierPushPull.lean': ['actual_canonical_real_cartier_push_pull'],
 'ProjectiveProductCartierSections.lean': ['exists_actual_projective_product_cartier_sections'],
 'NormalHartshorneModification.lean': ['exists_actual_normal_hartshorne_modification'],
 'BirationalComposition.lean': ['birational_of_actual_generic_stalk_isIso',
                                'actual_birational_morphism_comp'],
 'HartshorneFiniteModification.lean': ['exists_actual_hartshorne_finite_modification'],
 'FiniteProperRelativeProduct.lean': ['exists_actual_finite_proper_relative_product'],
 'AffineProductCharts.lean': ['actual_affine_product_chart'],
 'HartshorneProjectionFinite.lean': ['actual_graph_projection_isImmersion',
                                     'hartshorne_graph_second_projection_finite'],
 'HartshorneAffineCover.lean': ['exists_actual_hartshorne_affine_projective_cover'],
 'StandardProjectiveProper.lean': ['projective_degree_zero_inclusion_bijective',
                                   'actual_standard_projective_space_proper'],
 'FiniteTypeProjectiveImmersion.lean': ['actual_projective_affine_chart_inclusion_over',
                                        'exists_actual_affine_finite_type_projective_immersion'],
 'ProjectiveAffineChartAlgebra.lean': ['actual_projective_chart_evaluation_constant',
                                       'actual_projective_chart_evaluation_coordinate',
                                       'exists_actual_projective_affine_chart_quotient'],
 'AffineFormalFunctions.lean': ['completion_power_quotient_eval',
                                'completion_power_quotient_transition',
                                'adic_completion_power_eval_transition',
                                'actual_affine_formal_functions_bijective'],
 'AffineThickeningSections.lean': ['actual_affine_thickening_sections_pullback',
                                   'actual_affine_thickening_sections_transition'],
 'InfinitesimalIdempotents.lean': ['actual_power_thickening_inclusion_point',
                                   'actual_infinitesimal_nontrivial_idempotent'],
 'ClopenCharacteristicSection.lean': ['actual_clopen_characteristic_exists_unique',
                                      'actual_clopen_characteristic_germ',
                                      'actual_clopen_characteristic_idempotent',
                                      'actual_clopen_characteristic_pullback'],
 'SchemeClopenIdempotent.lean': ['actual_clopen_nontrivial_global_idempotent',
                                 'actual_scheme_connected_of_global_idempotents_trivial'],
 'ProperBirationalSections.lean': ['proper_normal_birational_open_functions_isIso',
                                   'proper_normal_birational_open_functions_bijective'],
 'ProperBirationalStructureSheaf.lean': ['proper_normal_birational_structure_sheaf_isIso'],
 'ProperBirationalFunctions.lean': ['birational_functionField_pullback_bijective',
                                    'proper_normal_birational_affine_functions_bijective'],
 'ActualProjectiveNegativityIff.lean': ['actual_projective_negativity_effectivity_iff'],
 'ActualProjectiveNegativity.lean': ['actual_projective_negativity_part_one'],
 'RelativeProjectiveEmbedding.lean': ['actual_relative_projective_embedding_cartier_sections'],
 'ActualOpenNef.lean': ['actual_relative_nef_on_target_open'],
 'ActualOpenPushforward.lean': ['actual_weil_cycle_pushforward_isWeil',
                                'actual_real_cartier_pushforward_effective_on_open'],
 'CartierOpenRestriction.lean': ['actual_cartier_open_restriction_coefficient',
                                 'actual_real_cartier_open_restriction_cycle'],
 'ActualProjectiveAffineNegativity.lean': ['actual_projective_affine_negativity'],
 'ProjectiveExceptionalWitness.lean': ['exists_actual_projective_exceptional_cartier'],
 'ProjPolynomialSections.lean': ['mvPolynomial_degree_zero_adjoin_variables',
                                 'exists_actual_projective_space_cartier_sections'],
 'ProjStandardSections.lean': ['exists_actual_proj_sections_of_generators'],
 'ProjCartierSections.lean': ['exists_actual_proj_cartier_affine_section_cover'],
 'ProjCartierAtlas.lean': ['proj_coordinate_generic_of_point', 'exists_actual_proj_cartier_atlas'],
 'ProjCoordinatePullback.lean': ['pulled_proj_coordinate_ratio_local',
                                 'pulled_proj_coordinate_ratio_ne_zero',
                                 'pulled_proj_coordinate_ratio_mul'],
 'ProjCoordinateRatios.lean': ['proj_coordinate_ratio_stalk_unit_iff',
                               'proj_coordinate_ratio_stalk_mul',
                               'proj_coordinate_ratio_section_germ'],
 'ActualNegativityAffineSections.lean': ['actual_negativity_of_affine_section_cover'],
 'CartierInverse.lean': ['cartierAtlas_inverse_coefficient',
                         'complete_integral_curve_cartier_intersection_inverse'],
 'CartierAffineSections.lean': ['complete_integral_curve_positive_of_affine_section_cover'],
 'NormalizedCartierSigns.lean': ['complete_integral_curve_effective_cartier_intersection_signs'],
 'CompleteCurveAffineAvoidance.lean': ['complete_integral_curve_not_affine',
                                       'complete_integral_curve_meets_complement_affine_open'],
 'ActualNegativityConstruction.lean': ['actual_negativity_of_strictly_negative_cartier'],
 'EffectiveExceptionalWitness.lean': ['exists_effective_exceptional_covering_cartier_twist'],
 'NormalizedPrincipalInvariance.lean': ['complete_integral_curve_ambient_cartier_principal_invariance'],
 'CartierEffectiveTwist.lean': ['exists_effective_cartier_rational_twist'],
 'ActualConnectedSupport.lean': ['actual_connected_contracted_scheme_support_dichotomy'],
 'ConnectedCurveCrossing.lean': ['connected_closed_subset_crossing_component',
                                 'connected_complete_scheme_actual_crossing_curve'],
 'CompleteCurveAvoiding.lean': ['exists_complete_integral_curve_through_closed_point_avoiding'],
 'AffineCurveAvoiding.lean': ['affine_integral_curve_through_maximal_avoiding'],
 'AffineLineAvoiding.lean': ['affine_line_through_point_avoiding_polynomial'],
 'ActualNegativityWitness.lean': ['actualRealCartierCoefficients_apply',
                                  'actual_negativity_of_antiample_witness'],
 'NegativeActualCenter.lean': ['actual_cycle_coefficient_over_isomorphism_open',
                               'actual_negative_coefficient_image_in_center'],
 'ZeroPrimeCurve.lean': ['zero_weil_coefficient_outside_geometric_support',
                         'zero_exceptional_prime_actual_curve_nonnegative_intersection'],
 'ExceptionalCompleteCurve.lean': ['exceptional_closed_point_complete_contracted_curve'],
 'NonisolatedCompleteCurve.lean': ['nonisolated_point_positive_irreducible_component',
                                   'exists_complete_integral_curve_through_nonisolated_closed_point'],
 'IntegralClosedSubscheme.lean': ['vanishingIdeal_subscheme_isReduced',
                                  'closed_irreducible_actual_subscheme_properties'],
 'CompleteCurveThroughPoint.lean': ['affine_chart_not_field_at_nonGeneric_point',
                                    'dimension_one_of_curve_domain',
                                    'exists_complete_integral_curve_through_closed_point'],
 'CompleteCurveClosure.lean': ['dominant_functionField_constants_comp',
                               'quasiCompact_integral_actual_image_isIntegral',
                               'complete_integral_curve_actual_closure'],
 'FunctionFieldDimension.lean': ['finiteType_domain_dimension_of_trdeg_le_one',
                                 'affine_chart_dimension_of_functionField_trdeg_le_one',
                                 'integral_scheme_dimension_of_functionField_trdeg_le_one'],
 'AffineCurveThroughPoint.lean': ['integral_extension_krullDimLE_one',
                                  'affine_integral_curve_through_maximal'],
 'AffineLineThroughPoint.lean': ['affine_line_kernel_below_point'],
 'ActualCycleProjectionCases.lean': ['actual_point_image_curve_cycle_zero',
                                     'actual_complete_curve_cycle_projection_cases'],
 'ActualRelativeNef.lean': ['actual_relative_nef_negative_iff', 'actual_relative_nef_canonical_pullback'],
 'CanonicalRealPullbackIntersection.lean': ['actualCartierPullback_data',
                                            'complete_integral_curve_canonical_real_pullback_intersection'],
 'FixedCartierPullbackIntersection.lean': ['complete_curve_cartier_intersection_of_actual_pullback'],
 'EmbeddedCurveProjection.lean': ['residueDegree_precomp_closedImmersion',
                                  'embedded_curve_actual_cycle_push',
                                  'exists_embedded_complete_curve_real_projection_formula'],
 'ActualProjectionFormula.lean': ['exists_complete_integral_curve_actual_real_projection_formula'],
 'AmbientCurveProjection.lean': ['complete_integral_curve_ambient_real_projection'],
 'ImageCycleMultiplicity.lean': ['closedImmersion_residueFieldMap_bijective',
                                 'residueDegree_comp_closedImmersion',
                                 'actual_image_residueDegree_functionField'],
 'CurveImageCases.lean': ['closedImmersion_height_eq',
                          'integral_scheme_point_or_curve',
                          'complete_integral_curve_actual_image_dichotomy'],
 'CurveImageGeometry.lean': ['actual_image_isReduced',
                             'proper_integral_actual_image_isIntegral',
                             'complete_integral_curve_actual_image_properties'],
 'CurveCycleProjection.lean': ['dominant_generic_residueDegree_functionField',
                               'curve_generic_height_preserved',
                               'complete_integral_curve_actual_cycle_projection'],
 'RealIntegralCurveProjection.lean': ['complete_integral_curve_real_cartier_projection'],
 'IntegralCurveProjection.lean': ['complete_integral_curve_cartier_projection'],
 'CurveRestrictionComposition.lean': ['dominant_curve_generic_unit_comp',
                                      'generic_unit_transport_functionField',
                                      'complete_normal_curve_cartier_intersection_reparametrization'],
 'CurveNormalizationLift.lean': ['birational_functionFieldMap_bijective',
                                 'complete_integral_curves_normalization_lift_degree'],
 'NormalizationLift.lean': ['dominant_functionField_Spec_square',
                            'exists_finite_dominant_normalization_lift'],
 'RelativeNormalizationIdentification.lean': ['finite_dominant_generic_section_birational',
                                              'finiteType_perfectField_relative_normalization_source_isIso'],
 'RelativeFieldNormalization.lean': ['finiteType_perfectField_relative_generic_normalization_isFinite'],
 'FiniteFunctionField.lean': ['finite_dominant_functionField_finite'],
 'NormalNormalization.lean': ['finiteType_perfectField_normal_normalization_isIso'],
 'FiniteFrobenius.lean': ['frobenius_isIntegral',
                          'finiteType_perfectField_frobenius_finite',
                          'finiteType_perfectField_iterateFrobenius_finite'],
 'FrobeniusIntegralClosure.lean': ['finiteType_perfectField_integralClosure_purelyInseparable_finite'],
 'PerfectIntegralClosure.lean': ['finiteType_perfectField_normal_integralClosure_finite'],
 'FiniteNormalizationAlgebra.lean': ['finiteType_perfectField_integralClosure_finite'],
 'RelativeIntegralClosureFinite.lean': ['finiteType_perfectField_relative_integralClosure_finite'],
 'FiniteNormalizationGeometry.lean': ['generic_stalk_preimage_nonempty_open',
                                      'generic_stalk_affine_functionField_embedding',
                                      'finiteType_perfectField_normalization_isFinite'],
 'GenericNormalizationNormal.lean': ['relative_integralClosure_isIntegrallyClosed',
                                     'generic_normalization_affine_sections_normal',
                                     'generic_normalization_stalks_normal'],
 'GenericNormalizationBirational.lean': ['finiteType_perfectField_normalization_birational'],
 'CurveNormalization.lean': ['generic_normalization_dimension_le_one',
                             'finiteType_perfectField_normalization_surjective',
                             'complete_integral_curve_normalization_properties'],
 'NormalizedCurveIntersection.lean': ['complete_integral_curve_real_intersection_point_image_zero',
                                      'complete_integral_curve_real_cartier_presentation_independent'],
 'NormalizedIntersectionSigns.lean': ['complete_integral_curve_effective_real_intersection_signs'],
 'NormalizedIntersectionPullback.lean': ['exists_complete_integral_curve_real_intersection_pullback'],
 'FunctionFieldFunctoriality.lean': ['dominantFunctionFieldMap_comp'],
 'NormalizedCurveDegree.lean': ['complete_integral_curve_cartier_intersection_degree'],
 'NormalizedRealDegree.lean': ['complete_integral_curve_real_cartier_intersection_degree'],
 'AmbientCartierMoving.lean': ['movedCartierRestrictionData_rationalTwist',
                               'complete_normal_curve_ambient_cartier_principal_invariance'],
 'CartierZeroIntersection.lean': ['cartier_support_empty_of_coefficients_zero',
                                  'cartierTotalOrder_zero_of_support_empty',
                                  'complete_normal_curve_zero_cartier_intersection'],
 'CurveCartierCombinations.lean': ['moved_restriction_equation_on_chart',
                                   'integral_combination_moved_local_units',
                                   'exists_complete_curve_cartier_intersection_integralCombination'],
 'RealCurveIntersection.lean': ['complete_normal_curve_cartier_integral_relation',
                                'complete_normal_curve_cartier_rational_relation',
                                'complete_normal_curve_cartier_real_relation',
                                'complete_normal_curve_real_cartier_intersection_wellDefined'],
 'CartierReindex.lean': ['cartierAtlas_pointIndexed_coefficient',
                         'complete_normal_curve_cartier_intersection_pointIndexed'],
 'RealIntersectionPresentations.lean': ['complete_normal_curve_real_cartier_presentation_independent'],
 'EffectiveRealIntersection.lean': ['complete_normal_curve_effective_real_cartier_intersection_signs'],
 'CurveIntersectionPullback.lean': ['curve_generic_stalk_pullback_comp',
                                    'exists_complete_curve_cartier_intersection_pullback'],
 'RealIntersectionPullback.lean': ['complete_normal_curve_real_cartier_intersection_point_image_zero',
                                   'exists_complete_curve_real_cartier_intersection_pullback'],
 'CurvePointImageDegree.lean': ['cartierTotalOrder_zero_of_equations_one',
                                'constant_image_moved_cartier_restriction_degree_zero'],
 'CurveMoveDegree.lean': ['moved_cartier_restriction_ratio_equations',
                          'complete_normal_curve_moved_restriction_degree_independent'],
 'CartierCurveIntersection.lean': ['complete_normal_curve_cartier_intersection_eq_restriction',
                                   'complete_normal_curve_cartier_intersection_wellDefined'],
 'EffectiveCurveIntersection.lean': ['effective_cartier_restriction_with_data',
                                     'complete_normal_curve_effective_cartier_intersection_signs'],
 'CurveIntersectionDegree.lean': ['generic_stalk_functionField_self',
                                  'genericPoint_not_cartier_support',
                                  'dominant_moved_restriction_equations',
                                  'complete_normal_curve_cartier_intersection_degree'],
 'AffineCurveOrders.lean': ['normal_curve_affine_dedekind',
                            'curve_affine_prime_coheight',
                            'normal_curve_affine_prime_order'],
 'FiniteCurveOrders.lean': ['finite_curve_chart_generic_tower',
                            'dominant_curve_chart_torsionFree',
                            'finite_normal_curve_fiber_order_degree'],
 'CurveFiberPrimes.lean': ['curve_chart_point_mem',
                           'curve_primeOver_maps_to_fiber',
                           'curve_fiber_point_prime_liesOver',
                           'curve_fiber_primes_actual_bijective'],
 'CurveClosedResidue.lean': ['curve_chart_base_scalar_tower',
                             'curve_chart_base_finiteType',
                             'finite_normal_curve_relative_residueDegree_one'],
 'CurveFiberDegree.lean': ['finite_normal_curve_unweighted_order_degree',
                           'finite_normal_curve_actual_fiber_order_degree'],
 'FiniteCurvePoints.lean': ['curve_affine_point_heightOne',
                            'finite_dominant_curve_preimage_nonempty',
                            'finite_normal_curve_maps_coheight_one'],
 'CurveCartierFiber.lean': ['finite_normal_curve_cartier_fiber_orders'],
 'CurveCartierDegree.lean': ['finsupp_mapDomain_actual_fiber',
                             'finite_normal_curve_cartier_push_pull',
                             'finite_normal_curve_cartier_pullback_degree'],
 'ProperCurveFinite.lean': ['curve_coheight_zero_generic',
                            'curve_nonGeneric_coheight_one',
                            'curve_genericPoint_not_closed',
                            'proper_dominant_curve_fibers_finite',
                            'proper_dominant_integral_curve_isFinite'],
 'ProperCurveCartierDegree.lean': ['complete_normal_curve_finite_cartier_pullback_degree',
                                   'complete_normal_curve_cartier_pullback_degree'],
 'SeparatingParameter.lean': ['exists_finite_separable_transcendental_parameter',
                              'exists_compatible_finite_separable_ratFunc_embedding'],
 'AffineCurveFunctionField.lean': ['integral_subring_krullDimLE_one',
                                   'affine_curve_ring_trdeg_one',
                                   'affine_curve_fractionField_finiteType_trdeg_one'],
 'CurveFunctionField.lean': ['curve_affine_chart_dimension',
                             'curve_affine_chart_not_field',
                             'curve_affine_constants_compatible',
                             'curve_functionField_properties_of_closed_point',
                             'curve_exists_coheight_one',
                             'finiteType_curve_exists_separating_parameter'],
 'CurveProductFormula.lean': ['complete_normal_curve_principal_product_formula'],
 'CartierDegreeInvariance.lean': ['complete_normal_curve_cartier_degree_invariant'],
 'DedekindValuationPlaces.lean': ['valuation_fraction_mem_of_unit_denominator',
                                  'valuation_chart_center_nonzero',
                                  'dedekind_chart_valuation_unique_prime'],
 'ValuationChartCover.lean': ['valuation_constants_trivial',
                              'integral_element_mem_valuation',
                              'rational_infinity_ring_mem_of_parameter_pole',
                              'functionField_valuation_integralClosure_chart_cover'],
 'FunctionFieldValuationPlaces.lean': ['finite_place_parameter_regular',
                                       'infinity_place_parameter_pole',
                                       'twoChartValuation_injective',
                                       'twoChartValuation_ne_top',
                                       'twoChartValuation_contains_constants',
                                       'functionField_valuation_unique_twoChart_place'],
 'DvrAdicOrders.lean': ['dvr_heightOneOrder_regular',
                        'dvr_heightOneOrder_eq_rationalOrder',
                        'dedekind_prime_order_eq_valuationRing_order'],
 'CurveChartPlaces.lean': ['curve_twoChart_center_exists',
                           'curveTwoChartCenter_valuation',
                           'proper_normal_curve_twoChart_centers_bijective'],
 'CurvePrincipalDegree.lean': ['dedekind_prime_actual_curve_order',
                               'twoChartPrincipalDivisor_actual_order',
                               'curvePrincipalDivisor_coefficient',
                               'proper_normal_curve_principal_degree_zero'],
 'CartierPrincipalDegree.lean': ['curvePrincipalDivisor_allPoints_coefficient',
                                 'cartierOrderDivisor_rationalTwist',
                                 'cartierTotalOrder_rationalTwist'],
 'RationalInfinityResidue.lean': ['rational_infinity_approximate_constant',
                                  'rational_infinity_residue_constants_bijective',
                                  'rational_infinity_residue_degree_one',
                                  'rational_infinity_inertia_degree_one',
                                  'infinity_pushforward_degree',
                                  'twoChart_baseField_principal_degree_zero',
                                  'algebraicallyClosed_infinity_point_degree_one',
                                  'affineDivisorDegree_eq_order_sum'],
 'FunctionFieldDegree.lean': ['functionField_principal_degree_baseField_zero',
                              'functionField_principal_order_sum_zero'],
 'ValuationCenters.lean': ['curveFunctionFieldBaseMap_spec',
                           'local_valuation_fractionRing_bijective',
                           'valuation_generic_lift_over_base',
                           'proper_functionField_valuation_unique_lift',
                           'valuation_center_stalk_functionField_compat',
                           'valuation_center_stalk_bijective',
                           'normal_curve_stalk_isValuation',
                           'nontrivial_valuation_center_coheight_one',
                           'curve_coheight_one_isClosed',
                           'proper_normal_curve_unique_valuation_center_iso'],
 'NormalCurveValuations.lean': ['normalCurvePointValuation_ne_top',
                                'normalCurvePointValuation_contains_constants',
                                'normalCurvePointValuation_center_eq',
                                'normalCurvePointValuation_lift',
                                'normalCurvePointValuation_injective',
                                'proper_normal_curve_valuation_has_closed_point',
                                'proper_normal_curve_points_valuations_bijective'],
 'ValuationOrderTransport.lean': ['dvr_rationalOrder_commonField_ringEquiv',
                                  'normal_curve_valuation_center_order',
                                  'proper_normal_curve_valuation_order_correspondence'],
 'NormDivisor.lean': ['separable_relNorm_factorization',
                      'ideal_primePower_multiplicity',
                      'ideal_primePower_product_multiplicity',
                      'normalizedIdealPoints_asIdeal',
                      'separable_ideal_norm_order',
                      'heightOneOrder_regular_eq_multiplicity',
                      'separable_integral_norm_order',
                      'ideal_order_eq_point_count',
                      'idealFactorDivisor_apply',
                      'idealFactorDivisor_principal',
                      'affineDivisorPushforward_single',
                      'separable_ideal_norm_divisor',
                      'fractionFieldNormUnits_integral',
                      'separable_integral_principal_norm',
                      'separable_affine_principal_norm',
                      'affineDivisorPushforward_degree',
                      'separable_affine_principal_norm_degree',
                      'fractionRing_separable_of_fractionFields',
                      'separable_integral_functionField_norm',
                      'separable_functionField_principal_norm',
                      'separable_functionField_principal_norm_degree'],
 'RationalDivisor.lean': ['polynomial_point_residueDegree',
                          'polynomial_prime_principal_divisor',
                          'polynomial_prime_principal_degree',
                          'polynomial_principal_degree',
                          'rational_affine_principal_degree',
                          'rational_actual_principal_degree_zero'],
 'InfinityNorm.lean': ['normalized_discrete_valuation_eq',
                       'rational_infinity_normalized_valuation',
                       'rational_infinity_heightOneOrder',
                       'separable_infinity_principal_norm',
                       'twoChart_principal_degree_zero'],
 'FunctionFieldProductFormula.lean': ['functionField_principal_degree_zero',
                                      'FunctionFieldPlaces.principalDegree_eq_zero'],
 'CartierDegree.lean': ['cartierOrderDivisor_apply',
                        'cartierTotalOrder_eq_of_unit_transitions',
                        'effective_cartierTotalOrder_nonneg',
                        'effective_cartierTotalOrder_pos',
                        'effective_cartierTotalOrder_pos_of_support'],
 'CartierCurveRestriction.lean': ['stalkSpecialization_functionField',
                                  'generic_stalkMap_commutes',
                                  'exists_cartierAtlas_nondominant_pullback',
                                  'exists_effective_nondominant_cartier_pullback',
                                  'effective_cartier_restriction_order_signs'],
 'RealCartierCurveDegree.lean': ['effective_real_cartier_curve_order_signs',
                                 'effective_realCartier_curve_decomposition_order_signs'],
 'CartierCurveMoving.lean': ['cartierAtlas_move_off_generic_curve',
                             'cartierAtlas_rationalTwist_transition',
                             'exists_moved_cartier_curve_restriction'],
 'RealCartierPullback.lean': ['dominantFunctionFieldMap_stalk_unit',
                              'cartierAtlas_pullback_coefficient_eq',
                              'cartierAtlas_integralCombination_coefficients',
                              'exists_realCartier_effective_decomposition_equations',
                              'cartierAtlas_pullback_integralCombination_coefficients',
                              'realWeightedWeilCycle_eq_of_integral_coefficients',
                              'exists_effective_cartierAtlas_pullback_data',
                              'exists_realCartier_termwise_pullback_support',
                              'exists_realCartier_termwise_fiber_descent'],
 'NormalExtension.lean': ['normal_local_annihilator_maximal_isPrincipal',
                          'normal_local_associated_principal_maximal_isPrincipal',
                          'normal_local_associated_principal_isDVR',
                          'normal_principal_associated_prime_isDVR',
                          'normal_principal_associated_prime_height_one',
                          'normal_divisibility_of_height_one_local',
                          'normal_fraction_regular_iff_height_one',
                          'normal_fraction_regular_of_height_one_denominators'],
 'CartierEffectivity.lean': ['dvr_rationalOrder_nonneg_iff_regular',
                             'normal_affine_rational_regular',
                             'cartierAtlas_effective_iff_weil_nonneg',
                             'exists_realCartier_effective_weil_decomposition'],
 'CartierVanishing.lean': ['rationalUnitAt_exists_affine_unit_section',
                           'rationalUnitAt_isOpen',
                           'cartierAtlas_vanishingSupport_isClosed',
                           'normal_affine_rationalUnitAt_of_orders_zero',
                           'cartierAtlas_vanishingSupport_eq_closure_weilSupport',
                           'effective_cartier_real_sum_support',
                           'exists_effective_real_sum_pullback_support',
                           'exists_realCartier_decomposition_support_pullback'],
 'RationalCone.lean': ['open_set_mem_convexHull_rational',
                       'open_set_exists_rational_convex_combination',
                       'positive_rational_coefficient_decomposition',
                       'rational_parameterization_preserves_zero',
                       'rationalCoefficientMap_cast',
                       'rationalCoefficientMap_comp_zero',
                       'effective_rational_coefficient_decomposition',
                       'rational_vector_positive_integer_multiple',
                       'effective_integral_coefficient_decomposition'],
 'CartierCombinations.lean': ['dvr_rationalOrder_zpow',
                              'dvr_rationalOrder_prod',
                              'exists_cartierAtlas_integralCombination',
                              'exists_cartierAtlas_integralCombination_coefficients'],
 'RealCartierDecomposition.lean': ['exists_realCartier_nonnegative_weil_decomposition'],
 'FiniteNormalGeometry.lean': ['birationalMorphism_dominant',
                               'birationalMorphism_generic_stalk_isIso',
                               'dominantFunctionFieldMap_germ',
                               'finite_normal_birational_affine_bijective',
                               'finite_normal_birational_isIso',
                               'normalStalks_restrict',
                               'birationalMorphism_restrict',
                               'proper_normal_birational_isIso_near_finite_fiber',
                               'birational_affine_functionField_embedding',
                               'birational_relative_integralClosure_bijective',
                               'normal_birational_fromNormalization_isIso',
                               'proper_normal_birational_isIso_near_quasiFiniteAt',
                               'exceptional_point_not_quasiFiniteAt',
                               'exceptional_fiber_point_not_isOpen_singleton'],
 'CartierSupport.lean': ['rationalUnitAt_unit_transition',
                         'cartierAtlas_support_eq_on_chart',
                         'rationalUnitAt_regular_iff',
                         'rationalUnitAt_regular_pullback_iff',
                         'exists_effective_cartierAtlas_pullback_support',
                         'effective_cartierAtlas_weil_nonneg',
                         'exists_effective_cartierAtlas_fiber_descent'],
 'DivisorPullback.lean': ['affineDivisorDegree_single',
                          'affinePointDivisorPullback_degree',
                          'affineDivisorPullback_degree',
                          'affinePointDivisorPullback_apply',
                          'affineDivisorPullback_apply',
                          'affinePrincipalDivisor_pullback',
                          'closedPoint_residueDegree_one',
                          'algebraicallyClosed_point_pullback_count',
                          'affineDivisorPullback_support',
                          'affineDivisorPullback_effective_iff',
                          'algebraicallyClosed_effective_divisor_degree_pos'],
 'SeparableNorm.lean': ['separable_prime_ideal_norm'],
 'StrictTransform.lean': ['geometricStrictTransform_image',
                          'geometricStrictTransform_injective',
                          'geometric_exceptional_iff',
                          'scheme_cycle_strictTransform_coefficient',
                          'weilCycleCoefficients_pushforward'],
 'CartierPushPull.lean': ['proper_birational_weil_cycle_pushforward',
                          'exists_cartierAtlas_pullback_pushforward',
                          'cartierAtlas_real_sum_isWeilDivisor',
                          'exists_realCartier_pullback_pushforward',
                          'exists_realCartier_effectivity_descent'],
 'CartierPullback.lean': ['dominant_genericPoint_eq',
                          'dominantFunctionFieldMap_stalk',
                          'exists_cartierAtlas_pullback',
                          'dominantFunctionFieldMap_order_of_stalk_iso'],
 'CartierAtlas.lean': ['cartierAtlas_order_agrees',
                       'schemeRationalOrder_zero_of_unit_germs',
                       'finite_schemeRationalOrder_on_affine',
                       'cartierAtlas_coefficient_eq',
                       'cartierAtlas_locallyFiniteSupport',
                       'cartierAtlas_weilCycle_isWeilDivisor',
                       'cartierAtlas_weilCycle_eq_of_unit_transitions',
                       'cartierAtlas_weilCycle_finite_support'],
 'CodimensionSupport.lean': ['finite_heightOne_primes_containing', 'finite_codimensionOne_nonunit_germs'],
 'FractionFieldOrders.lean': ['dvr_rationalOrder_represents',
                              'dvr_rationalOrder_unit',
                              'dvr_rationalOrder_mul',
                              'dvr_rationalOrder_unit_transition'],
 'CodimensionOne.lean': ['generic_stalk_dominant',
                         'normal_codimensionOne_stalk_isDVR',
                         'separated_dominant_section_isIso',
                         'proper_birational_isIso_near_DVR',
                         'proper_birational_isIso_near_codimensionOne',
                         'proper_birational_isIso_on_codimensionOne_open',
                         'stalkMap_isIso_over_isomorphism_open',
                         'proper_birational_codimensionOne_unique_preimage',
                         'proper_birational_surjective'],
 'HartshorneGraph.lean': ['isIso_over_dense_open_section', 'hartshorne_graph_closure'],
 'RelativeNumerics.lean': ['relative_nef_neg_iff', 'relative_curvePositive_neg_iff'],
 'RationalProductFormula.lean': ['polynomial_factor_degree_sum',
                                 'rationalInfinityOrder_eq',
                                 'rationalFunction_principal_degree_zero'],
 'NormalSections.lean': ['normal_affine_sections'],
 'PointPullback.lean': ['point_pullback_tensor_iso',
                        'point_pullback_tensor_length',
                        'finite_flat_point_pullback_degree',
                        'finite_flat_point_pullback_degree_over_base'],
 'CurveSelection.lean': ['exists_closedPoint_outside_support',
                         'finiteType_exists_closedPoint_outside_support'],
 'LocalConnectedness.lean': ['localRing_idempotent_trivial', 'localRing_not_product_nontrivial'],
 'CurveDegree.lean': ['finite_flat_fiber_degree',
                      'finite_flat_signed_point_degree',
                      'finite_flat_fiber_functionField_degree',
                      'heightOneOrder_mul',
                      'heightOneOrder_pullback',
                      'finite_flat_order_fiber_degree'],
 'PrincipalDivisors.lean': ['heightOneOrder_finite_support',
                            'affinePrincipalDivisor_apply',
                            'affinePrincipalDivisor_mul',
                            'heightOneOrder_regular_unit',
                            'affinePrincipalDivisor_unit_transition',
                            'heightOneOrder_nonneg_iff',
                            'affinePrincipalDivisor_effective_iff',
                            'affinePrincipalDivisor_inv',
                            'affinePrincipalDivisor_eq_zero_iff'],
 'PullbackDiagram.lean': ['curve_square_pullback_iso'],
 'AffineSections.lean': ['affine_quasicoherent_exists_nonzero_section'],
 'NormalBirational.lean': ['integral_birational_algebraMap_bijective',
                           'finite_birational_algebraMap_bijective',
                           'finite_birational_spec_isIso'],
 'LocalGeometry.lean': ['normal_one_dimensional_local_isDVR',
                        'scheme_normal_one_dimensional_stalk_isDVR',
                        'proper_dvr_lift',
                        'proper_valuative_lift_unique',
                        'proper_quasiFinite_isFinite',
                        'proper_finite_fiber_neighborhood'],
 'LocalPushPull.lean': ['dvr_order_ringEquiv',
                        'dvr_fraction_order_well_defined',
                        'dvr_fraction_order_ringEquiv',
                        'scheme_pushpull_of_local_coefficients',
                        'scheme_stalk_fraction_order_of_iso',
                        'scheme_residueDegree_of_iso',
                        'scheme_residueDegree_of_stalk_iso',
                        'scheme_pushpull_of_local_isomorphisms'],
 'Projection.lean': ['scheme_cycle_map_single',
                     'scheme_curve_push_of_same_weight',
                     'scheme_curve_push_of_drop',
                     'projection_cases_from_cycle_push',
                     'nonpositive_pullback_from_cycle_push',
                     'projection_formula_on_real_span',
                     'scheme_effective_descends'],
 'GeometricCycles.lean': ['scheme_cycle_map_effective',
                          'scheme_mapCoeff_zero_of_drop',
                          'scheme_mapCoeff_of_same_weight',
                          'scheme_cycle_map_zero_of_drop'],
 'Numerical.lean': ['exists_effective_shift', 'effective_of_curve_tests'],
 'Coefficients.lean': ['effective_push', 'negative_is_exceptional', 'exists_least_effective_shift'],
 'Descent.lean': ['push_comp',
                  'push_zero_iff_exceptional_support',
                  'effective_both_signs_iff_zero',
                  'nonpositive_smul',
                  'nonpositive_pullback',
                  'effective_descends',
                  'negativity_descends',
                  'subset_iff_preimage_subset',
                  'disjoint_iff_preimage_disjoint',
                  'support_dichotomy_descends',
                  'composite_fiber',
                  'fiber_dichotomy_descends',
                  'push_embDomain',
                  'push_add_exceptional',
                  'effective_descends_coefficients'],
 'Interfaces.lean': ['effective_iff_push_effective', 'exceptional_subset_support', 'fiber_support_dichotomy'],
 'ActualAffineOpenReesBaseScalars.lean': ['actual_affine_open_image_coordinates_base',
                                          'actual_rees_closed_open_chart_base',
                                          'actual_affine_open_closed_chart_base',
                                          'actual_appTop_restriction',
                                          'actual_section_base_frame',
                                          'actual_affine_open_rees_base_frame',
                                          'actual_affine_open_rees_sections_base_scalars'],
 'ActualAffineOpenReesCoordinates.lean': ['actual_affine_open_coefficient_triangle',
                                          'actual_affine_open_rees_square',
                                          'actual_affine_open_rees_kernel',
                                          'actual_affine_open_image_coordinates_fac',
                                          'actual_rees_closed_open_chart_preimage',
                                          'actual_rees_closed_open_chart_sections_hom',
                                          'actual_affine_open_image_coordinates_source',
                                          'actual_rees_closed_open_chart_source',
                                          'actual_affine_open_rees_sections_equiv_apply',
                                          'actual_appLE_congr_morphism',
                                          'actual_section_source_frame',
                                          'actual_affine_open_closed_chart_source',
                                          'actual_affine_open_closed_chart_preimage',
                                          'actual_appLE_comp_top',
                                          'actual_affine_open_closed_chart_sections',
                                          'actual_affine_open_rees_source_frame',
                                          'actual_affine_open_rees_sections_coefficients'],
 'ActualAffineOpenReesRestriction.lean': ['actual_affine_open_coefficient_restriction',
                                          'actual_open_sections_restriction_source',
                                          'actual_ring_equiv_symm_of_apply',
                                          'actual_affine_open_rees_sections_symm_coefficients',
                                          'actual_affine_open_rees_restriction_coefficients',
                                          'actual_appLE_top_restriction',
                                          'actual_rees_sections_restrict_base',
                                          'actual_rees_coefficient_map_restriction'],
 'ActualAffineOpenReesRestrictionFinal.lean': ['actual_affine_open_rees_sections_base_scalars_appLE',
                                               'actual_affine_open_rees_sections_symm_base_scalars',
                                               'actual_affine_open_rees_restriction_base_scalars',
                                               'actual_affine_open_rees_sections_restriction',
                                               'actual_affine_open_rees_sections_restriction_coeff'],
 'ActualAffineReesBaseScalarCoordinates.lean': ['actual_affine_rees_section_coordinates_base_scalars',
                                                'actual_affine_rees_image_sections_base_scalars'],
 'ActualAffineReesImageCoordinates.lean': ['actual_affine_rees_sections_square',
                                           'actual_affine_rees_image_section_map_surjective',
                                           'actual_affine_rees_image_section_map_kernel',
                                           'actual_affine_rees_kernel_top',
                                           'actual_affine_rees_image_sections_equiv_inclusion',
                                           'actual_affine_rees_image_sections_equiv_symm_map',
                                           'actual_affine_rees_image_sections_equiv_factor',
                                           'actual_affine_rees_image_sections_on_tensors',
                                           'actual_affine_rees_section_coordinates_coefficients',
                                           'actual_affine_rees_image_sections_coefficients'],
 'ActualAffineReesMapCoordinates.lean': ['actual_affine_polynomial_coordinates_inv_fst',
                                         'actual_affine_polynomial_coordinates_inv_snd',
                                         'actual_affine_polynomial_rees_map_coordinates'],
 'ActualAffineVarietySections.lean': ['actual_affine_variety_section_algebra_finite_type'],
 'ActualCechAmbientModule.lean': ['actualCechHOneGlobalModule'],
 'ActualClosedFibersConnectedFromAffineCharacteristicLifts.lean': ['actual_closed_fibers_connected_of_affine_characteristic_lifts'],
 'ActualGradedClosedCechQuotient.lean': ['actual_relative_cech_hone_direct_sum_quotient_map_surjective',
                                         'actual_relative_cech_hone_polynomial_quotient_map_surjective',
                                         'actualGradedClosedCechCycleEquiv',
                                         'actualGradedClosedCechQuotientEquiv',
                                         'actualRelativeCechHOneDirectSumQuotientMap',
                                         'actualRelativeCechHOnePolynomialQuotientMap'],
 'ActualNativeCechKernelComparison.lean': ['actualIdealModuleAppKernelIso_coe',
                                           'actualIdealModuleAppKernelAddEquiv_coe',
                                           'actualIdealModuleAppKernelAddEquiv_naturality',
                                           'actualNativeProductOpen_eq_iInf',
                                           'actualNativeProductOpen_zero',
                                           'actualNativeProductOpen_one',
                                           'actualNativeProductOpen_two',
                                           'actualNativeCech_d_comp_projection',
                                           'actualNativeCechZeroEquiv_coe',
                                           'actualNativeCechOneEquiv_coe',
                                           'actualNativeCechZeroEquiv_coe_tuple',
                                           'actualNativeCechOneEquiv_coe_tuple',
                                           'actualNativeCechTwoEquiv_coe',
                                           'actualIdealModuleTransportRestriction',
                                           'actualNativeCech_difference',
                                           'actualNativeCech_boundary',
                                           'actualNativeCech_cycle_iff',
                                           'actualNativeCechCycleEquiv_boundary',
                                           'actualNativeCechCycleEquiv_range',
                                           'actualNativeCechOneEquiv_smul',
                                           'actualNativeCechCycleEquiv_smul',
                                           'actual_closed_cech_native_comparison'],
 'ActualNativeUnitCechCoordinates.lean': ['actualNativeUnitCechZeroEquiv_coe',
                                          'actualNativeUnitCechOneEquiv_coe',
                                          'actualNativeUnitCechTwoEquiv_coe',
                                          'actualNativeUnitCechZeroEquiv_coe_tuple',
                                          'actualNativeUnitCechOneEquiv_coe_tuple',
                                          'actualUnitModuleTransportRestriction',
                                          'actualNativeUnitCech_difference',
                                          'actualNativeUnitCech_boundary'],
 'ActualNativeUnitCechCycles.lean': ['actualNativeUnitCech_cycle_iff',
                                     'actualNativeUnitCechCycleEquiv_boundary',
                                     'actualNativeUnitCechCycleEquiv_range',
                                     'actualNativeUnitCechOneEquiv_smul',
                                     'actualNativeUnitCechHOneAddEquiv'],
 'ActualNativeUnitCechLinearComparison.lean': ['actualNativeUnitCechCycleEquiv_smul',
                                               'actualNativeUnitCechHOneLinearEquiv'],
 'ActualProperBirationalFiberConnectedFromClopenLifts.lean': ['actual_proper_birational_fiber_connected_of_clopen_characteristic_lifts'],
 'ActualProperCechKernelVanishing.lean': ['actual_proper_affine_cech_kernel_vanishing'],
 'ActualProperClosedFiberConnected.lean': ['actual_proper_birational_closed_fibers_connected'],
 'ActualProperFiberIdempotentDescent.lean': ['actual_proper_birational_closed_fiber_idempotent_descends'],
 'ActualProperFormalFunctions.lean': ['actual_proper_birational_closed_fiber_formal_functions'],
 'ActualProperNegativityComplete.lean': ['actual_proper_negativity_lemma'],
 'ActualReesCechCoordinates.lean': ['finitePiDirectSumLinearEquiv_symm_apply',
                                    'actualReesCechZeroEquiv_coeff',
                                    'actualReesCechOneEquiv_coeff',
                                    'actualReesCechZeroEquiv_symm_coeff',
                                    'actualReesCechZeroEquiv_symm_of',
                                    'actualReesCechOneEquiv_symm_coeff',
                                    'actualReesCechOneEquiv_symm_of',
                                    'actualReesCechZeroEquiv',
                                    'actualReesCechOneEquiv'],
 'ActualReesCechCover.lean': ['actual_rees_cech_cover_covers',
                              'actual_rees_cech_chart_range',
                              'exists_actual_rees_finite_affine_cech_cover'],
 'ActualReesCechCycleScalars.lean': ['actualReesCechCycleScalarModule_apply',
                                     'actual_affine_open_coefficient_scalar',
                                     'actualReesCechCycleEquivFromNaturality_symm_coeff',
                                     'actualReesCechCycleEquivFromNaturality_symm_of',
                                     'actual_rees_cech_cycle_homogeneous_scalars'],
 'ActualReesCechCycleSemilinearFromNaturality.lean': ['actual_rees_cech_cycle_target_homogeneous_scalars',
                                                      'actualReesCechCycleSemilinearFromNaturality'],
 'ActualReesCechCyclesFromNaturality.lean': ['actual_rees_cech_sum_differential_iff_from_naturality',
                                             'actualGradedClosedCechCycleEquiv_coe',
                                             'actualReesCechCycleEquivFromNaturality_coeff',
                                             'actualReesCechCycleEquivFromNaturality_boundary',
                                             'actualReesCechCycleEquivFromNaturality'],
 'ActualReesCechDifferentialsFromNaturality.lean': ['actualReesSectionCoefficient_apply',
                                                    'actualCechDifference_apply',
                                                    'actualCechBoundary_apply',
                                                    'actualCechTwo_zero_apply',
                                                    'actual_rees_cech_difference_coeff_from_naturality',
                                                    'actual_rees_cech_boundary_coeff_from_naturality',
                                                    'actual_rees_cech_cycle_iff_from_naturality'],
 'ActualReesCechNaturality.lean': ['actual_rees_coordinate_restriction_compatibility'],
 'ActualReesClosedOpenChart.lean': ['actual_rees_closed_open_chart_fac',
                                    'actual_rees_closed_open_chart_isPullback',
                                    'actual_rees_closed_open_chart_range'],
 'ActualReesFinitenessHypotheses.lean': ['actual_relative_rees_scheme_locally_of_finite_presentation',
                                         'actual_relative_rees_scheme_noetherian',
                                         'actual_relative_rees_scheme_separated'],
 'ActualReesHOneFinite.lean': ['actual_relative_cech_hone_finite_of_proper_spec'],
 'ActualReesHOneFiniteFromNative.lean': ['actualReesNativeUnitCycle_smul',
                                         'actual_rees_native_cech_quotient_semilinear_surjective',
                                         'actual_rees_native_cech_quotient_semilinear_ker',
                                         'actual_rees_native_hone_semilinear_comparison_bijective',
                                         'actual_relative_cech_hone_finite_of_native_rees'],
 'ActualReesIdealSectionCoordinates.lean': ['actualSpecPowerSectionKernelEquiv_coe',
                                            'actualLocalReesPowerSectionsEquiv_coeff',
                                            'actualLocalReesPowerSectionsEquiv_monomial',
                                            'actualAffineReesPowerSectionsEquiv_coeff',
                                            'actualSpecPowerSectionKernelEquiv',
                                            'actualAffineReesPowerSectionsEquiv'],
 'ActualReesNativeQuotientFromNaturality.lean': ['actualReesNativeCechCycleEquivFromNaturality_boundary',
                                                 'actual_rees_native_cech_quotient_from_naturality_surjective',
                                                 'actual_rees_native_cech_quotient_from_naturality_ker'],
 'ActualReesOpenChart.lean': ['actual_base_change_open_chart_range',
                              'actual_rees_open_chart_square',
                              'actual_rees_open_chart_isPullback',
                              'actual_rees_open_chart_kernel'],
 'ActualReesProperCechFinite.lean': ['actual_rees_structure_cech_homology_finite'],
 'ActualReesStructureSheafCoherence.lean': ['actual_structure_sheaf_finite_type_and_quasicoherent'],
 'ActualRelativeCechForgetKernel.lean': ['actual_relative_cech_graded_forget_kernel_preserved',
                                         'actual_relative_cech_forget_kernel_finite_of_hone_finite',
                                         'actualRelativeCechForgetKernelGradedModule'],
 'ActualRelativeCechHOneReesModule.lean': ['actual_relative_cech_hone_rees_module_homogeneous_smul',
                                           'actualRelativeCechHOneDirectSumReesModule',
                                           'actualRelativeCechHOnePolynomialReesModule'],
 'ActualRelativeCechKernelGeneratorVanishing.lean': ['actual_relative_cech_kernel_transition_zero_of_bounded_generators',
                                                     'actual_relative_cech_kernel_vanishing_of_hone_finite'],
 'ActualRelativeCechKernelScalarVanishing.lean': ['actual_relative_cech_kernel_scalar_transition_zero'],
 'ActualRelativeReesScheme.lean': ['actual_polynomial_rees_triangle',
                                   'actual_polynomial_rees_map_affine',
                                   'actual_relative_rees_scheme_proper'],
 'ActualSchemeConnectedOfCharacteristic.lean': ['actual_scheme_connected_of_characteristic_sections_trivial'],
 'ActualSpecIdealPullback.lean': ['actual_spec_ideal_sheaf_top',
                                  'actual_spec_ideal_power_pullback_coordinates'],
 'ActualSpecReesScalarCoordinates.lean': ['actualSpecReesScalarEquiv_coeff',
                                          'actualSpecReesScalarEquiv_monomial',
                                          'actual_ring_equiv_restricted_module_finite_iff',
                                          'actualSpecReesScalarEquiv',
                                          'actualReesCechScalarEquiv'],
 'AffineBaseCechVanishing.lean': ['actual_ideal_family_cech_kernel_vanishing_congr',
                                  'actual_relative_power_ideal_antitone',
                                  'actual_affine_base_cech_kernel_vanishing'],
 'AffineBaseReesCoordinates.lean': ['actual_affine_base_spec_ideal_pullback',
                                    'actual_affine_base_spec_power_pullback',
                                    'actual_affine_base_spec_coefficient',
                                    'actual_affine_base_rees_coordinates'],
 'AffineOpenPullbackIdeal.lean': ['actual_affine_open_ideal_pullback',
                                  'actual_affine_open_ideal_power_pullback'],
 'Basic.lean': ['numerical_contradiction'],
 'ClosedFiberThickeningIso.lean': ['actual_closed_fiber_ideal_map_fac',
                                   'actual_closed_fiber_ideal_scheme_iso'],
 'ConnectedSchemeGlobalIdempotents.lean': ['actual_connected_scheme_global_idempotent_trivial',
                                           'actual_connected_fiber_idempotent_lifts_from_global'],
 'DirectSumKernelReuse.lean': ['actual_direct_sum_kernel_map_bijective',
                               'actualDirectSumKernelEquiv_apply',
                               'actualDirectSumKernelEquiv'],
 'DirectSumQuotientReuse.lean': ['actual_direct_sum_map_range',
                                 'actual_direct_sum_quotient_map_surjective',
                                 'actual_direct_sum_quotient_map_ker',
                                 'actualDirectSumQuotientEquiv_mk',
                                 'actualDirectSumQuotientEquiv'],
 'FiberCharacteristicLifting.lean': ['actual_closed_fiber_to_power_transition',
                                     'actual_closed_fiber_characteristic_lifts_of_cech_kernel_vanishing'],
 'FiberCharacteristicThickening.lean': ['actual_closed_fiber_to_power_fac',
                                        'actual_closed_fiber_to_power_point',
                                        'actual_closed_fiber_characteristic_extends_to_thickening'],
 'FiberIdempotentConstancy.lean': ['actual_proper_birational_fiber_lift_is_constant',
                                   'actual_fiber_neighborhood_square',
                                   'actual_proper_birational_neighborhood_lift_is_constant',
                                   'actual_proper_birational_fiber_lifted_idempotent_trivial'],
 'FiniteGradedModuleGeneratorBound.lean': ['actual_finite_graded_module_generator_bound'],
 'FinitePiDirectSumReuse.lean': ['finitePiDirectSumLinearEquiv_apply', 'finitePiDirectSumLinearEquiv'],
 'GradedModuleComponentVanishing.lean': ['actual_graded_component_vanishing_of_bounded_generators'],
 'GradedModuleMapReuse.lean': ['actualGradedModuleMap_injective',
                               'actualGradedModuleOfInjective',
                               'actualGradedModuleMap'],
 'GradedModuleQuotientReuse.lean': ['actualGradedModuleOfSurjective'],
 'ModuleCatHomologyQuotientReuse.lean': ['actualModuleCatHomologyQuotientComparison'],
 'ModuleCatHomologySemilinearReuse.lean': ['actual_module_cat_homology_semilinear_quotient_map_bijective',
                                           'actual_module_cat_homology_finite_of_semilinear_quotient',
                                           'actualModuleCatHomologySemilinearQuotientMap'],
 'ReesBaseChange.lean': ['actual_rees_base_change_surjective'],
 'ReesDirectSumBaseChange.lean': ['actualReesCoefficientMap_monomial',
                                  'actualDirectSumReesCoefficientMap_lof',
                                  'actualDirectSumReesBaseModule_lof_smul',
                                  'actualPolynomialReesBaseModule_monomial_smul',
                                  'actualReesBaseChangeLinearEquiv_lof',
                                  'actualReesBaseChangeLinearEquiv'],
 'ReesDirectSumCoordinates.lean': ['actualDirectSumToRees_lof',
                                   'actualDirectSumToRees_coeff',
                                   'actualDirectSumToRees_bijective',
                                   'actualReesDirectSumAlgEquiv_lof',
                                   'actualReesDirectSumAlgEquiv_symm_monomial',
                                   'actualPolynomialReesModule_monomial_smul',
                                   'actualPolynomialReesModule_finite_iff',
                                   'actualReesDirectSumAlgEquiv'],
 'ReesImageCoordinates.lean': ['actual_rees_polynomial_kernel', 'actual_rees_image_coordinates_on_tensors'],
 'ReesRestrictionGenerators.lean': ['rees_hom_ext_on_coefficients_and_base',
                                    'rees_polynomial_restriction_of_generators'],
 'ReesRingEquivReuse.lean': ['actualReesRingEquiv_coeff',
                             'actualReesRingEquiv_monomial',
                             'actualReesRingEquiv'],
 'RelativeCechSourceLifting.lean': ['actual_relative_source_section_lifting_of_cech_kernel_vanishing'],
 'SchemeSectionLiftRestriction.lean': ['actual_scheme_section_lift_restriction']}

logs = []
for args in [['lake', '--rehash', 'build'], ['lake', 'env', 'lean', 'CheckAxioms.lean']]:
    try:
        result = subprocess.run(args, cwd=project, capture_output=True, text=True, encoding='utf-8', check=True)
    except subprocess.CalledProcessError as error:
        failed = '$ ' + ' '.join(args) + '\n' + (error.stdout or '') + (error.stderr or '')
        destination.mkdir(parents=True, exist_ok=True)
        (destination / 'failed-verification.txt').write_text('\n'.join(logs + [failed]), encoding='utf-8')
        sys.stderr.write(failed)
        raise
    logs.append('$ ' + ' '.join(args) + '\n' + result.stdout + result.stderr)
audit = logs[1]
axiom_records = {}
for name in sum(names.values(), []):
    match = re.search(r"'Negativity\." + name + r"' depends on axioms: \[(.*?)\]", audit, re.S)
    if match:
        actual = [a.strip() for a in match.group(1).split(',') if a.strip()]
    elif "'Negativity." + name + "' does not depend on any axioms" in audit:
        actual = []
    else:
        raise RuntimeError('Missing axiom record: ' + name)
    if not set(actual) <= {'propext', 'Classical.choice', 'Quot.sound'}:
        raise RuntimeError('Unexpected axioms: ' + name + str(actual))
    axiom_records[name] = actual
if 'sorryAx' in audit:
    raise RuntimeError('Unproved axiom detected')
source = destination / 'source'
if source.exists() and any(source.iterdir()):
    raise RuntimeError('Export into a fresh destination to prevent stale source files')
source.mkdir(parents=True, exist_ok=True)
files = ['Negativity.lean', 'CheckAxioms.lean', 'lakefile.toml', 'lake-manifest.json', 'lean-toolchain', 'THIRD_PARTY_NOTICES.txt']
files += [p.relative_to(project).as_posix() for p in sorted((project / 'Negativity').glob('*.lean'))]
files += [p.relative_to(project).as_posix() for p in sorted(
    (project / 'Negativity/External').rglob('*')) if p.is_file()]

def lean_code_without_comments_or_strings(text):
    # Nested Lean comments and string literals are source data, not proof holes.
    # The independent #print axioms audit above remains the semantic guard.
    out, i, depth = [], 0, 0
    while i < len(text):
        if depth:
            if text.startswith('/-', i): depth += 1; i += 2
            elif text.startswith('-/', i): depth -= 1; i += 2
            else: i += 1
            continue
        if text.startswith('/-', i): depth = 1; out.append(' '); i += 2
        elif text.startswith('--', i):
            j = text.find('\n', i)
            i = len(text) if j < 0 else j
            out.append(' ')
        elif text[i] == '"':
            i += 1; out.append(' ')
            while i < len(text):
                if text[i] == '\\': i += 2
                elif text[i] == '"': i += 1; break
                else: i += 1
        else: out.append(text[i]); i += 1
    if depth: raise RuntimeError('Unterminated Lean comment')
    return ''.join(out)

manifest = []
for relative in files:
    data = (project / relative).read_bytes()
    if relative.endswith('.lean') and re.search(r'\b(sorry|admit|axiom)\b', lean_code_without_comments_or_strings(data.decode('utf-8-sig'))):
        raise RuntimeError('Unexpected placeholder: ' + relative)
    target = source / relative
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_bytes(data)
    record = {'path': relative, 'sha256': hashlib.sha256(data).hexdigest()}
    if relative.endswith('.lean'):
        record['lineCount'] = len(data.decode('utf-8-sig').splitlines())
    manifest.append(record)
declarations = {}
for filename, declarations_in_file in names.items():
    code = (project / 'Negativity' / filename).read_text(encoding='utf-8-sig')
    for name in declarations_in_file:
        match = re.search(r'^(?:noncomputable )?(theorem|lemma|def|abbrev) ' + re.escape(name.rsplit('.', 1)[-1]) + r'\b', code, re.M)
        if not match:
            raise RuntimeError('Missing declaration ' + name)
        remainder = code[match.start():]
        end = re.search(r'\n(?:/--|(?:noncomputable )?(?:theorem|lemma|def|abbrev) |end Negativity|@\[|#print axioms)', remainder)
        snippet = remainder[:end.start() if end else len(remainder)].strip()
        declarations[name] = {'kind': match.group(1), 'path': 'Negativity/' + filename, 'line': code[:match.start()].count('\n') + 1, 'code': snippet, 'axioms': axiom_records[name]}
mathlib = next(p['rev'] for p in json.loads((project / 'lake-manifest.json').read_text(encoding='utf-8-sig'))['packages'] if p['name'] == 'mathlib')
date = datetime.datetime.now(datetime.timezone(datetime.timedelta(hours=8))).isoformat(timespec='seconds')
snapshot = {'schemaVersion': 1, 'checkedAt': date, 'lean': (project / 'lean-toolchain').read_text().strip(), 'mathlib': mathlib, 'files': manifest, 'declarations': declarations, 'graphEdges': 'manually curated mathematical blueprint; not a kernel dependency dump', 'verification': 'local lake build and #print axioms; not browser-side verification'}
(destination / 'snapshot.json').write_text(json.dumps(snapshot, ensure_ascii=False, indent=2), encoding='utf-8')
(destination / 'verification.txt').write_text('Verified ' + date + '\n\n' + '\n'.join(line.rstrip() for log in logs for line in log.splitlines()), encoding='utf-8')
readme = "Actual proper negativity lemma — both conclusions\n\nFinal theorem: Negativity.actual_proper_negativity_lemma\nSource: Negativity/ActualProperNegativityComplete.lean\n\nLet k be algebraically closed of arbitrary characteristic. For a proper\nbirational morphism f:X->Y of normal k-varieties and a real Cartier divisor D\nwith -D relatively nef, the final theorem proves:\n  (1) D is effective if and only if the actual Weil pushforward f_*D is effective.\n  (2) If D is effective, every fiber is disjoint from Supp D or contained in it.\n\nThe code uses actual mathlib schemes, finite Cartier presentations, actual\nWeil cycles, and intersection by local orders on curve normalizations.\nThe final theorem has no formal-functions, curve-existence, projection-formula,\nChow-modification, numerical-positivity, or cohomology-finiteness input.\n\nActual proper cohomology finite generation is reused from pinned AINTLIB\nsource and rebuilt on this project's toolchain. The actual relative Rees\nimage and its native Cech cohomology are identified with the source's summed\nideal-power H1, including genuine restrictions, scalars, and boundaries.\nFinite generation supplies a uniform kernel bound. A clopen characteristic\nfunction extends to finite thickenings and then lifts to actual global\nsections. Normal proper birational function descent makes its fiber\nrestriction constant, proving actual closed-fiber connectedness. The\nall-fiber support argument and independent effectivity proof complete the\ntwo-part theorem. A separate closed-fiber formal-functions comparison for\nproper normal birational morphisms is also proved; the final connectedness\nroute uses finite characteristic lifts.\n\nSome auxiliary results have general explicit hypotheses or abstract model\nparameters. Their statements remain visible. They are distinct from the\nfinal actual geometric theorem, whose required geometric bridges are proved.\n\nVerification: local lake build and #print axioms. Every exported own theorem\nis checked against the whitelist propext, Classical.choice, Quot.sound.\nNo sorry, admit, added axiom, or sorryAx is accepted. Browser rendering and\nthe curated mathematical graph are not independent Lean verification.\n\nReproduce with Lean's elan and Git:\n  lake update\n  lake exe cache get\n  lake build\n  lake env lean CheckAxioms.lean\n\nlean-toolchain, lakefile.toml, and lake-manifest.json pin the toolchain and\ndependencies. The archive deliberately excludes .lake and local user data.\nThe complete selected third-party source closures, Apache-2.0 licenses,\nrevision/hash provenance, and migration notes are in External/Laurent and\nExternal/Aintlib. Imported source authors and copyright notices are retained.\nThe private Hartshorne scan is not included.\n\nThe exact audited own declarations, source positions, hashes, and checking\ntime are recorded in snapshot.json and verification.txt. The dependency\natlas is a curated mathematical blueprint, not a kernel dependency dump.\n"

(source / 'README.txt').write_text(readme, encoding='utf-8')
with zipfile.ZipFile(destination / 'negativity-lean.zip', 'w', zipfile.ZIP_DEFLATED) as archive:
    for f in sorted(source.rglob('*')):
        if f.is_file():
            archive.write(f, 'negativity/' + f.relative_to(source).as_posix())
print('Verified and exported', len(files), 'files and', len(declarations), 'declarations')
