const {chromium}=require('playwright'),assert=require('node:assert/strict');
(async()=>{const b=await chromium.launch({channel:'chrome',headless:true,args:['--enable-webgl','--enable-unsafe-swiftshader']}),p=await b.newPage({viewport:{width:1280,height:900}}),errors=[];p.on('pageerror',e=>errors.push(e.message));const base=(process.env.COURSE_TEST_URL||'http://127.0.0.1:8768/courses/abstract-algebra/2026-fall/');
await p.goto(base+'?view=lesson&section=1.2#one-sided');await p.frameLocator('#lecture-frame').locator('.axiom-lab').waitFor();let f=p.frames().find(f=>f.url().includes('/lesson-1/'));
assert.match(await f.locator('.notebook-entry.is-current').innerText(),/扩展 1.2.2/);
for(const lang of ['zh','en']){await f.evaluate(lang=>CourseLanguage.set(lang),lang);for(let mask=0;mask<32;mask++){await f.locator('.axiom-all').evaluate(el=>el.open=true);await f.locator(`[data-mask="${mask}"]`).click();const expected=await f.evaluate(mask=>GroupAxiomLab.implies(Object.fromEntries(GroupAxiomLab.keys.map((k,i)=>[k,!!(mask&(1<<i))]))),mask);assert.equal(await f.locator('.axiom-verdict').evaluate(el=>el.classList.contains('is-group')),expected);}}
await f.evaluate(()=>CourseLanguage.set('zh'));await f.locator('[data-axiom="L"]').uncheck();await f.locator('[data-axiom="J"]').uncheck();assert.match(await f.locator('.axiom-result').innerText(),/最小反例/);
await p.setViewportSize({width:390,height:844});assert.equal(await f.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);console.log('32 selections × 2 languages; mobile layout');
await p.locator('#portal-course-open').click();await p.locator('[data-replay-opening]').click();await p.waitForFunction(()=>document.querySelector('#symmetry-particle-studies').dataset.stage==='ready',{},{timeout:45000});
async function readyBar(){assert.equal(await p.locator('.loader-progress').getAttribute('aria-valuenow'),'100');assert(await p.evaluate(()=>{const c=document.querySelector('#loadingSand'),d=c.getContext('2d').getImageData(500,50,100,20).data;return d.some((v,i)=>i%4===3&&v>0);}));}
await readyBar();await p.locator('[data-start-animation]').click();await p.waitForFunction(()=>document.querySelector('#symmetry-particle-studies').dataset.stage==='playing');await p.waitForTimeout(1200);assert(await p.evaluate(()=>!document.querySelector('#openingMusic').paused&&document.querySelector('#openingMusic').currentTime>0));
for(const selector of ['#openingMusicToggle','[data-opening-language]','#openingFullscreen','#openingSettingsToggle']){const state=()=>p.evaluate(()=>({lang:document.querySelector('#symmetry-particle-studies').dataset.narrationLanguage,music:document.querySelector('#openingMusicToggle').dataset.sound,full:!!document.fullscreenElement,panel:document.querySelector('#openingSettings').hidden,stage:document.querySelector('#symmetry-particle-studies').dataset.stage}));const before=await state();await p.locator(selector).press('Enter');assert.deepEqual(await state(),before);}
await p.locator('#openingFullscreen').click();assert.equal(await p.evaluate(()=>!!document.fullscreenElement),false);await p.locator('#openingFullscreen').click();assert.equal(await p.evaluate(()=>!!document.fullscreenElement),true);
const boxes=await Promise.all(['#openingMusicToggle','[data-opening-language]','#openingFullscreen','#openingSettingsToggle'].map(s=>p.locator(s).boundingBox()));for(let i=0;i<boxes.length;i++)for(let j=i+1;j<boxes.length;j++)assert(boxes[i].x+boxes[i].width<=boxes[j].x||boxes[j].x+boxes[j].width<=boxes[i].x);
await p.locator('#openingSettingsToggle').click();const spark=p.locator('[data-setting-toggle="gemSparkleEnabled"]');assert(await spark.isChecked());await spark.uncheck();assert.equal(await p.evaluate(()=>JSON.parse(document.querySelector('#symmetry-particle-studies').dataset.settings).gemSparkleEnabled),false);await spark.check();await p.locator('[data-settings-close]').click();
await p.locator('#courseOpening').focus();await p.keyboard.press('Enter');await p.waitForFunction(()=>document.querySelector('#symmetry-particle-studies').dataset.stage==='galois');await p.waitForTimeout(1200);const early=await p.evaluate(()=>document.querySelector('#symmetry-particle-studies')._openingPreview.evidence());assert(early.entrance);assert(early.galoisStory.music.scorePlaying);assert(early.galoisStory.music.mediaTime>.3);assert.equal(early.glError,0);console.log('Galois audio plays during entry; fullscreen mouse-only; gem switch persists');
await p.locator('[data-opening-next]').click();await p.waitForFunction(()=>document.querySelector('#symmetry-particle-studies').dataset.outro==='hold');await p.locator('[data-opening-next]').click();await p.locator('[data-replay-opening]').click();await p.waitForFunction(()=>document.querySelector('#symmetry-particle-studies').dataset.stage==='ready');await readyBar();await p.locator('[data-start-animation]').click();await p.waitForTimeout(1200);assert(await p.evaluate(()=>!document.querySelector('#openingMusic').paused&&document.querySelector('#openingMusic').currentTime>0));assert.equal(await p.evaluate(()=>document.querySelector('#symmetry-particle-studies')._openingPreview.evidence().glError),0);assert.deepEqual(errors,[]);console.log('Cached replay: painted 100% loading bar and audible main music');await b.close()})().catch(e=>{console.error(e);process.exit(1)});
