const {chromium}=require('playwright');const assert=require('node:assert/strict');
(async()=>{const b=await chromium.launch({channel:'chrome',headless:true,args:['--enable-webgl','--enable-unsafe-swiftshader']}),p=await b.newPage({viewport:{width:1280,height:900}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto((process.env.COURSE_TEST_URL||'http://127.0.0.1:8768/courses/abstract-algebra/2026-fall/'));await p.waitForFunction(()=>document.querySelector('#symmetry-particle-studies').dataset.stage==='ready',{},{timeout:45000});
await p.locator('[data-start-animation]').click();await p.waitForFunction(()=>document.querySelector('#symmetry-particle-studies').dataset.stage==='playing');
await p.locator('[data-opening-language]').click();assert.equal(await p.evaluate(()=>CourseLanguage.language),'zh');
await p.locator('#courseOpening').focus();await p.keyboard.press('Enter');await p.waitForFunction(()=>document.querySelector('#symmetry-particle-studies').dataset.stage==='galois');await p.keyboard.press('Enter');await p.waitForFunction(()=>document.querySelector('#symmetry-particle-studies').dataset.outro==='hold');assert.equal(await p.locator('#symmetry-particle-studies').getAttribute('data-outro-language'),'en');
await p.keyboard.press('Enter');await p.waitForFunction(()=>!document.querySelector('#courseOpening').open);assert.equal(await p.evaluate(()=>CourseLanguage.language),'en');assert.match(await p.locator('.hero h1').innerText(),/Algebra/);assert.equal(await p.locator('#portal-language').innerText(),'中文');console.log('Opening English -> English course + title docking');
await p.locator('#portal-language').click();assert.equal(await p.evaluate(()=>CourseLanguage.language),'zh');await p.locator('#portal-course-open').click();assert.equal(await p.evaluate(()=>CourseLanguage.language),'zh');console.log('Course language changes not overwritten by later navigation');
// Replay, choose Chinese, and exit directly rather than via the final title.
await p.locator('[data-replay-opening]').click();await p.waitForFunction(()=>document.querySelector('#symmetry-particle-studies').dataset.stage==='ready');await p.locator('[data-opening-language]').click();assert.equal(await p.locator('#symmetry-particle-studies').getAttribute('data-narration-language'),'zh');await p.locator('[data-skip-opening]').click();assert.equal(await p.evaluate(()=>CourseLanguage.language),'zh');assert.match(await p.locator('.hero h1').innerText(),/代数学/);
await p.reload();assert.equal(await p.evaluate(()=>CourseLanguage.language),'zh');assert.deepEqual(errors,[]);console.log('Chinese choice passed through direct skip and persisted on refresh');await b.close()})().catch(e=>{console.error(e);process.exit(1)});
