const {chromium}=require('playwright'),assert=require('node:assert/strict');
(async()=>{const b=await chromium.launch({headless:true,channel:'chrome'}),p=await b.newPage({viewport:{width:1280,height:900}}),errors=[];p.on('pageerror',e=>errors.push(e.message));
await p.goto('http://127.0.0.1:8768/courses/abstract-algebra/2026-fall/?view=course#schedule');
async function hitCheck(){return p.evaluate(()=>[...document.querySelectorAll('.portal-header button')].filter(el=>el.getBoundingClientRect().width).flatMap(el=>{const r=el.getBoundingClientRect(),errors=[];for(const dx of [3,r.width/2,r.width-3])for(const dy of [3,r.height/2,r.height-3])if(document.elementFromPoint(r.x+dx,r.y+dy)?.closest('button')!==el)errors.push(el.id+' hit miss');if(getComputedStyle(el).cursor!=='pointer')errors.push(el.id+' cursor');return errors;}));}
assert.deepEqual(await hitCheck(),[]);await p.locator('#portal-fullscreen').click();await p.waitForFunction(()=>!!document.fullscreenElement);
for(const id of ['portal-course-open','portal-language','portal-fullscreen','portal-settings']){const el=p.locator('#'+id),before=await el.boundingBox();await el.hover();await p.waitForTimeout(320);assert(await p.locator('#portal-control-tip').isVisible());assert.deepEqual(await el.boundingBox(),before);assert.deepEqual(await hitCheck(),[]);await p.waitForTimeout(2700);assert.equal(await p.locator('.portal-header').evaluate(e=>e.classList.contains('is-idle')),false);}
const lang=p.locator('#portal-language'),r=await lang.boundingBox();await lang.click();assert.deepEqual(await lang.boundingBox(),r);await p.locator('#portal-settings').hover();await p.waitForTimeout(300);assert.match(await p.locator('#portal-control-tip').innerText(),/Page settings/);await p.locator('#portal-settings').click();await p.locator('#pageStyleSettings').waitFor({state:'visible'});await p.locator('#pageStyleSettings .page-style-close').click();
await p.locator('#portal-language').click();await p.mouse.move(500,400);await p.waitForTimeout(3000);assert.equal(await p.locator('.portal-header').evaluate(e=>e.classList.contains('is-idle')),true);assert.deepEqual(await hitCheck(),[]);await p.locator('#portal-fullscreen').click();await p.waitForFunction(()=>!document.fullscreenElement);
// Newly mounted lesson frames must still wake the toolbar on pointer activity.
await p.goto('http://127.0.0.1:8768/courses/abstract-algebra/2026-fall/?view=lesson&section=2.5');await p.frameLocator('#lecture-frame').locator('.notebook-entry').first().waitFor();await p.mouse.move(500,400);await p.waitForTimeout(3000);await p.mouse.move(520,420);await p.waitForTimeout(50);assert.equal(await p.locator('.portal-header').evaluate(e=>e.classList.contains('is-idle')),false);
await p.locator('#portal-next').click();await p.frameLocator('#lecture-frame').locator('.notebook-entry').first().waitFor();await p.mouse.move(500,400);await p.waitForTimeout(3000);await p.mouse.move(520,420);await p.waitForTimeout(50);assert.equal(await p.locator('.portal-header').evaluate(e=>e.classList.contains('is-idle')),false);
await p.setViewportSize({width:390,height:844});assert.deepEqual(await hitCheck(),[]);assert.equal(await p.locator('#portal-fullscreen').isVisible(),false);assert.deepEqual(errors,[]);console.log('PASS: fullscreen hit regions, stable hover/language geometry, bilingual tooltips, settings, idle wake across frame replacements, mobile targets.');await b.close()})().catch(e=>{console.error(e);process.exit(1)});
