(()=>{
'use strict';
const L=window.GroupCourseContent;
const E=(id,zh,en,tex,text,textEn,extra={})=>({id,title:[zh,en],tex,text:[text,textEn],...extra});
const P=(...steps)=>steps,B=(zh,en)=>[zh,en],V=(kind,extra={})=>({kind,...extra});
const add=(id,title,en,entries,extra={})=>L[id]={id,title:[title,en],entries,...extra};
add('2.1','子群的陪集','Cosets of a subgroup',[
 E('cosets','把子群平移出去','Translating a subgroup',String.raw`aH=\{ah:h\in H\},\qquad Ha=\{ha:h\in H\}`, '左陪集 aH 与右陪集 Ha 是集合，一般不是子群，也未必彼此相等。映射 h↦ah 给出 H 与 aH 的双射。','Left and right cosets are sets. They need not be subgroups or equal to each other. The map h↦ah is a bijection from H to aH.',{visual:V('cosets'),example:B('在 ℤ₆ 中，H={0,3}，三个陪集是 {0,3}、{1,4}、{2,5}。只有第一个含单位元。','In ℤ₆, H={0,3} has cosets {0,3}, {1,4}, {2,5}. Only the first contains the identity.')}),
 E('criterion','两个陪集何时相等','When two cosets are equal',String.raw`aH=bH\iff b^{-1}a\in H`, '左陪集相等的判别使用 b⁻¹a；右陪集 Ha=Hb 的对应判别是 ab⁻¹∈H。次序取决于在哪一侧消去。','The left-coset criterion uses b⁻¹a. For right cosets, Ha=Hb exactly when ab⁻¹∈H. The order reflects the side on which cancellation occurs.',{proof:P(B('若 aH=bH，则 a∈bH，存在 h∈H 使 a=bh，所以 b⁻¹a=h∈H。','If aH=bH, then a=bh for some h∈H, hence b⁻¹a∈H.'),B('反向，若 a=bh 且 h∈H，则 aH=bhH=bH，因为 hH=H。','Conversely, a=bh with h∈H gives aH=bhH=bH.'),B('若 aH 与 bH 有交点 ah₁=bh₂，则 b⁻¹a=h₂h₁⁻¹∈H；故两个左陪集要么相等，要么不交。','If ah₁=bh₂, then b⁻¹a=h₂h₁⁻¹∈H. Thus two left cosets are equal or disjoint.')),visual:V('cosets')}),
 E('partition','陪集给出一种分类','Cosets partition the group',String.raw`a\sim b\iff b^{-1}a\in H,\qquad G=\coprod aH`, '子群确定等价关系，其等价类就是左陪集。陪集的个数称为指数 [G:H]；左、右陪集数相同。','A subgroup defines an equivalence relation whose classes are its left cosets. Their number is the index [G:H]. Left and right indices agree.',{proof:P(B('e∈H 保证反身；对子群取逆保证对称；b⁻¹a、c⁻¹b∈H 时，c⁻¹a=(c⁻¹b)(b⁻¹a)∈H 保证传递。','Identity, inversion and multiplication in H give reflexivity, symmetry and transitivity respectively.'),B('每个 a 在 aH 中，且不同陪集不交，因此所有左陪集构成分类。','Each a lies in aH, and distinct cosets are disjoint; hence they form a partition.'),B('取逆把 aH 送到 Ha⁻¹。这是左陪集集合与右陪集集合之间的双射。','Taking inverses sends aH to Ha⁻¹, a bijection between left and right coset sets.'))}),
 E('lagrange','拉格朗日定理','Lagrange’s theorem',String.raw`|G|=[G:H]\,|H|\qquad (|G|<\infty)`, '有限群中，每个子群的阶都整除群的阶。证明的核心是将 G 划分为大小相同的陪集。','The order of a subgroup divides the order of a finite group. The proof partitions G into cosets of equal size.',{proof:P(B('选择各个不同左陪集代表 a₁,…,aₘ，其中 m=[G:H]。','Choose representatives a₁,…,aₘ of the distinct left cosets.'),B('每个映射 H→aᵢH，h↦aᵢh，都是双射，故每个陪集有 |H| 个元素。','Left multiplication is a bijection H→aᵢH, so each coset has |H| elements.'),B('这些陪集互不相交且覆盖 G，因此 |G|=m|H|。','The disjoint cosets cover G, giving |G|=m|H|.')),visual:V('cosets'),warning:B('逆命题一般不成立：|G| 的每个因子未必都是某个子群的阶；A₄ 没有 6 阶子群。','The converse fails: not every divisor of |G| is a subgroup order. A₄ has no subgroup of order 6.')}),
 E('consequences','元素阶、素数阶与费马','Orders, prime-order groups and Fermat',String.raw`|a|\mid |G|,\qquad a^{|G|}=e`, '有限群中元素阶整除群阶；素数阶群必为循环群。应用到模素数的非零剩余类乘法群，得到费马小定理。','Element orders divide the group order; every group of prime order is cyclic. Applying this to nonzero residues modulo a prime gives Fermat’s little theorem.',{proof:P(B('⟨a⟩ 是阶为 |a| 的子群，拉格朗日定理给出 |a|∣|G|，因此 a^|G|=e。','Apply Lagrange to ⟨a⟩ to obtain |a|∣|G| and a^|G|=e.'),B('若 |G|=p 为素数，取 a≠e；|a|>1 且整除 p，只能等于 p，所以 ⟨a⟩=G。','If |G|=p is prime and a≠e, then |a|=p and G=⟨a⟩.'),B('若 p∤a，a 的剩余类在 p−1 阶群 (ℤ/pℤ)× 中，所以 a^(p−1)≡1 mod p。','For p∤a, its residue lies in the group (ℤ/pℤ)× of order p−1, giving a^(p−1)≡1 mod p.'))}),
 E('index','指数的乘法公式','Multiplication of indices',String.raw`K\le H\le G:\qquad [G:K]=[G:H][H:K]`, '当右边两个指数有限时，逐层选择代表元可以得到 G 中 K 的全部代表元。此结论不要求 G 本身有限。','When both indices on the right are finite, nested representatives give all cosets of K in G. The group itself need not be finite.',{proof:P(B('设 G 中 H 的左陪集代表为 aᵢ，H 中 K 的左陪集代表为 bⱼ。每个 g 可唯一确定 i,j，使 g∈aᵢbⱼK。','Choose representatives aᵢ for G/H and bⱼ for H/K. Every g belongs to some aᵢbⱼK.'),B('若 aᵢbⱼK=aₖbₗK，先比较 H 陪集得 i=k，再左消去 aᵢ，比较 K 陪集得 j=l。','Equality of two such cosets first forces i=k by H-cosets, then j=l by K-cosets.'),B('所以这些乘积代表恰好给出 [G:H][H:K] 个不同陪集。','Thus the products give exactly [G:H][H:K] distinct cosets.'))})
]);
add('2.2','正规子群与商群','Normal subgroups and quotient groups',[
 E('normal','左右平移得到同一块','Left and right translates agree',String.raw`N\trianglelefteq G\iff gN=Ng\ \ (\forall g\in G)`, '正规子群在所有共轭下不变：gNg⁻¹=N。交换群的每个子群都正规；非交换群则需额外检验。','A normal subgroup is invariant under every conjugation: gNg⁻¹=N. Every subgroup of an abelian group is normal; nonabelian groups require an additional check.',{visual:V('normal'),example:B('D₃ 中旋转子群 ⟨r⟩ 正规，反射子群 ⟨s⟩ 不正规。改变所选 g，观察左右陪集何时不同。','In D₃, the rotation subgroup ⟨r⟩ is normal, but the reflection subgroup ⟨s⟩ is not. Compare left and right cosets.')}),
 E('tests','等价判别与指数 2','Equivalent tests and index two',String.raw`N\trianglelefteq G\iff (\forall g,n)\ gng^{-1}\in N`, 'N≤G 时，对每个 g∈G、n∈N 检查 gng⁻¹∈N 就够了。另一个常用捷径：指数为 2 的子群一定正规。','For a subgroup N, it suffices to check gng⁻¹∈N for all g,n. A useful special case: every subgroup of index two is normal.',{proof:P(B('若所有共轭元素都留在 N，就有 gNg⁻¹⊆N。把 g 换成 g⁻¹，再共轭回去得到反向包含，所以相等。','Conjugate closure gives gNg⁻¹⊆N. Apply this with g⁻¹ and conjugate back to obtain the reverse inclusion.'),B('若 [G:H]=2，对 g∈H，两边陪集都为 H。','If the index is two and g∈H, both cosets equal H.'),B('对 g∉H，唯一另一个左陪集和唯一另一个右陪集都为 G∖H，因此 gH=Hg。','If g∉H, the unique other left and right cosets are both G∖H, so they agree.'))}),
 E('well-defined','陪集为什么能够相乘','Why coset multiplication is well-defined',String.raw`(aN)(bN):=abN\qquad(N\trianglelefteq G)`, '用代表元定义运算必须证明：换代表元后结果仍是同一个陪集。正规性正是允许把中间的 N 移过 b 的条件。','An operation defined with representatives must be independent of their choices. Normality lets the subgroup factor move past b.',{proof:P(B('写 a′=an₁、b′=bn₂，其中 n₁,n₂∈N。','Write alternative representatives a′=an₁ and b′=bn₂.'),B('a′b′=an₁bn₂=ab(b⁻¹n₁b)n₂。由正规性，括号内元素及其与 n₂ 的乘积都在 N。','Compute a′b′=ab(b⁻¹n₁b)n₂. Normality puts the parenthesized term and its product with n₂ in N.'),B('因此 a′b′N=abN，运算良定义。','Hence a′b′N=abN, proving independence of representatives.')),visual:V('quotient'),warning:B('如果 N 不正规，这条代表元乘法公式会产生矛盾；“陪集集合”始终存在，但未必能按此方式成为群。','For a nonnormal subgroup the representative formula fails. The coset set still exists, but this formula does not make it a group.')}),
 E('quotient','商群及其群公理','The quotient group',String.raw`G/N=\{gN:g\in G\},\quad e_{G/N}=N,\quad(gN)^{-1}=g^{-1}N`, '正规子群 N 的全部陪集在上述运算下构成商群。商群把 N 中的所有元素视作同一个单位元。','Cosets of a normal subgroup form a group under the well-defined product. Every element of N becomes the same identity element.',{proof:P(B('封闭性由 ab∈G 得到。结合律来自 (ab)c=a(bc)。','Closure follows from ab∈G, and associativity is inherited from G.'),B('N·aN=aN·N=aN，所以 N 是单位元；aN·a⁻¹N=N，反向亦然。','N is a two-sided identity and a⁻¹N is a two-sided inverse of aN.'),B('有限群时，商群的阶就是陪集数 |G/N|=[G:N]=|G|/|N|。','For finite G, the quotient order is the number of cosets: |G|/|N|.')),visual:V('quotient')}),
 E('examples','两个重要商群','Two important quotients',String.raw`\mathbb Z/n\mathbb Z\cong C_n,\qquad D_3/\langle r\rangle\cong C_2`, '整数模 n 是最熟悉的商群。三角形对称群模旋转子群后，只剩“保持方向”与“反转方向”两种类型。','Integers modulo n form the familiar quotient. Quotienting the triangle group by rotations leaves only orientation-preserving and orientation-reversing types.',{visual:V('quotient'),example:B('在 D₃/⟨r⟩ 中，任何两个反射所在的陪集相乘都是旋转陪集。商群的一个元素是一整个陪集，不能与某个固定代表混同。','In D₃/⟨r⟩, the product of two reflection cosets is the rotation coset. A quotient element is an entire coset, not a chosen representative.')}),
 E('necessity','为什么正规性是必要的','Why normality is necessary',String.raw`(aH)(bH)=abH\text{ well-defined}\Longrightarrow H\trianglelefteq G`, '若在左陪集集合上，代表元乘法对所有代表选择都良定义，则 H 必正规。由此，正规性既充分又必要。','If the representative product on left cosets is well-defined for every representative choice, H must be normal. Thus normality is both necessary and sufficient.',{proof:P(B('取 h∈H、g∈G。由于 hH=eH，把它们分别与 gH 相乘，良定义性给出 hgH=gH。','For h∈H, hH=eH. Multiplying by gH gives hgH=gH.'),B('用左陪集相等判别，得到 g⁻¹hg∈H。对所有 g,h 成立，故 H 正规。','The coset criterion yields g⁻¹hg∈H for all g,h; hence H is normal.'))})
]);
add('2.3','群的同态和同态基本定理','Homomorphisms and the first isomorphism theorem',[
 E('maps','保持乘法，允许信息丢失','Preserve products, allow information loss',String.raw`\varphi:G\to K,\qquad\varphi(ab)=\varphi(a)\varphi(b)`, '同态保持群运算，不要求单射或满射。它自动保持单位元、逆元与整数幂。','A homomorphism preserves multiplication but need not be injective or surjective. It automatically preserves identity, inverses and integer powers.',{visual:V('homomorphism'),example:B('ℤ→ℤ/nℤ，k↦[k]；sgn:Sₙ→{±1}；det:GLₙ(ℝ)→ℝ× 都是同态。','Examples are reduction modulo n, the sign map Sₙ→{±1}, and determinant GLₙ(ℝ)→ℝ×.')}),
 E('kernel','核与像','Kernel and image',String.raw`\ker\varphi=\{g:\varphi(g)=e\},\qquad\operatorname{im}\varphi=\{\varphi(g):g\in G\}`, '核记录被压成单位元的全部信息；像记录真正能到达的目标。核是 G 的正规子群，像是 K 的子群。','The kernel records what is collapsed to the identity; the image records which target elements are reached. The kernel is normal in G, and the image is a subgroup of K.',{proof:P(B('φ(e)=e，且 a,b∈ker φ 时 φ(ab⁻¹)=e，所以核为子群。','φ(e)=e and φ(ab⁻¹)=e for a,b in the kernel, so the kernel is a subgroup.'),B('若 n∈ker φ，则 φ(gng⁻¹)=φ(g)eφ(g)⁻¹=e，故核正规。','For n in the kernel, φ(gng⁻¹)=φ(g)eφ(g)⁻¹=e, proving normality.'),B('像含 e，且 φ(a)φ(b)⁻¹=φ(ab⁻¹) 仍在像中，所以像也是子群。','The image contains e and is closed under xy⁻¹ because φ(a)φ(b)⁻¹=φ(ab⁻¹).')),visual:V('homomorphism')}),
 E('fibers','纤维就是核的陪集','Fibers are cosets of the kernel',String.raw`\varphi(a)=\varphi(b)\iff b^{-1}a\in\ker\varphi`, '同态不能区分 a、b，当且仅当它们相差一个核中的元素。因此非空纤维正是核的陪集；同态单射当且仅当核平凡。','A homomorphism identifies a and b exactly when they differ by a kernel element. Every nonempty fiber is a kernel coset; injectivity is equivalent to a trivial kernel.',{proof:P(B('φ(a)=φ(b) ⇔ φ(b)⁻¹φ(a)=e ⇔ φ(b⁻¹a)=e。','Apply multiplication by φ(b)⁻¹ and the homomorphism law.'),B('固定 b 后，这个条件等价于 a∈b ker φ，故纤维为陪集。','For fixed b, this is precisely a∈b ker φ, identifying the fiber.'),B('若核只有 e，相同像迫使 a=b；若 φ 单射，φ(g)=φ(e) 当然只可能有 g=e。','A trivial kernel forces equal-image elements to agree; injectivity conversely forces the kernel to be trivial.')),visual:V('homomorphism')}),
 E('isomorphism-theorem','同态基本定理','The first isomorphism theorem',String.raw`G/\ker\varphi\ \cong\ \operatorname{im}\varphi,\qquad g\ker\varphi\longmapsto\varphi(g)`, '先把同态无法区分的元素合并成类，再映到像，就得到没有信息丢失的同构。目标是 im φ；只有 φ 满射时才能写成 K。','After identifying indistinguishable elements, the induced map to the image becomes an isomorphism. The target is im φ, which equals K only for a surjective map.',{proof:P(B('令 N=ker φ。核正规，所以 G/N 已是群。定义 f(gN)=φ(g)。','Put N=ker φ. It is normal, so G/N is a group. Define f(gN)=φ(g).'),B('良定义：gN=hN ⇒ h⁻¹g∈N ⇒ φ(g)=φ(h)。','Well-definedness: equal cosets imply equal images.'),B('保运算：f(gN·hN)=φ(gh)=φ(g)φ(h)。','Product preservation: f(ghN)=φ(gh)=φ(g)φ(h).'),B('单射：φ(g)=φ(h) ⇒ h⁻¹g∈N ⇒ gN=hN。满射到 im φ 则由像的定义得到。','Injectivity follows from the fiber criterion. Surjectivity onto the image holds by definition.')),visual:V('homomorphism')}),
 E('applications','识别商群的三步法','Three steps for recognizing a quotient',String.raw`\text{map}\ \longrightarrow\ \text{kernel}\ \longrightarrow\ \text{image}`, '识别 G/N 时，先找一个自然同态，再证明其核恰为 N，最后确定像。不要只比较两边的阶。','To recognize G/N, construct a natural homomorphism, identify its kernel exactly, then determine its image. Equal orders alone are insufficient.',{example:B('det:GLₙ(ℝ)→ℝ× 是满射（取 diag(t,1,…,1)），核为 SLₙ(ℝ)，故 GLₙ(ℝ)/SLₙ(ℝ)≅ℝ×。又如 n≥2 时 Sₙ/Aₙ≅C₂。','Determinant is onto ℝ× by diagonal matrices and has kernel SLₙ(ℝ). Hence GLₙ(ℝ)/SLₙ(ℝ)≅ℝ×. Likewise Sₙ/Aₙ≅C₂ for n≥2.'),visual:V('homomorphism')}),
 E('correspondence','商群中的子群来自哪里','Subgroups of a quotient',String.raw`\{H:N\le H\le G\}\longleftrightarrow\{\bar H:\bar H\le G/N\}`, '设 N◁G。H↦H/N 与 B↦π⁻¹(B) 给出包含 N 的子群与商群子群之间的对应，并且保持包含关系及正规性。','For N normal in G, H↦H/N and inverse image under π give a correspondence between subgroups containing N and subgroups of G/N. Inclusion and normality are preserved.',{proof:P(B('同态的子群像、子群原像都是子群。π⁻¹(B) 包含 N，因为单位陪集属于 B。','Images and inverse images of subgroups are subgroups. The inverse image contains N.'),B('若 H 包含 N，则 π⁻¹(π(H))=H：与 H 中元素同陪集的元素仍在 H 中；π(π⁻¹(B))=B 由 π 满射得到。','If H contains N, π⁻¹(π(H))=H. Surjectivity gives π(π⁻¹(B))=B.'),B('gHg⁻¹⊆H 的像给出商群中的正规性；反过来，商群正规性取原像也给出 H 的正规性。','Apply π or inverse image to conjugate-closure conditions to obtain preservation of normality.'))}),
 E('third','再取商与自然映射','Taking a quotient twice',String.raw`N\trianglelefteq G,\ M\trianglelefteq G,\ N\subseteq M\quad\Rightarrow\quad (G/N)/(M/N)\cong G/M`, '若 N⊆M 都在 G 中正规，先模掉 N 再模掉 M/N，与直接模掉 M 得到相同结构。','If N⊆M are both normal in G, quotienting first by N and then by M/N gives the same structure as quotienting by M directly.',{proof:P(B('定义 f:G/N→G/M，gN↦gM。因 N⊆M，它良定义。','Define f(gN)=gM. Inclusion N⊆M makes it well-defined.'),B('f 保乘法且满射，核是所有 g∈M 对应的陪集，即 M/N。','It preserves products, is surjective, and has kernel M/N.'),B('对 f 使用同态基本定理即得结论。','Apply the first isomorphism theorem to f.')),example:B('(ℤ/12ℤ)/⟨[4]⟩≅ℤ/4ℤ。这里 ⟨[4]⟩ 有 3 个元素，商群有 4 个元素。','(ℤ/12ℤ)/⟨[4]⟩≅ℤ/4ℤ. The subgroup has three elements and the quotient has four.')})
]);
add('2.4','群的直积','Direct products of groups',[
 E('product','两个独立的群并行运算','Independent operations in parallel',String.raw`(g_1,h_1)(g_2,h_2)=(g_1g_2,h_1h_2)`, '直积 G×H 的元素是有序对，运算逐坐标进行。单位元是 (e,e)，逆元是 (g⁻¹,h⁻¹)。','The direct product has ordered pairs as elements and coordinatewise multiplication. Its identity is (e,e) and its inverses are coordinatewise.',{visual:V('product'),example:B('ℤ₄×ℤ₆ 的元素 ([a],[b]) 每一步分别在两个圆周上前进。两边同时回到原点才完成一个周期。','In ℤ₄×ℤ₆, each coordinate moves around its own cycle. Both must return simultaneously.')}),
 E('order','直积中元素的阶','Orders in a direct product',String.raw`|(g,h)|=\operatorname{lcm}(|g|,|h|)`, '若 g、h 都为有限阶，则有此公式；任意一个坐标无穷阶时，(g,h) 也无穷阶。','For finite-order coordinates, the pair has order equal to their least common multiple. If either coordinate has infinite order, so does the pair.',{proof:P(B('(g,h)ᵏ=(gᵏ,hᵏ)，所以它等于单位元当且仅当两个坐标都回到单位元。','(g,h)ᵏ=(gᵏ,hᵏ), so both coordinates must be identities.'),B('有限阶时，条件是 |g|∣k 且 |h|∣k，最小正解为最小公倍数；无穷阶坐标则不存在这样的 k。','For finite orders, k must be a multiple of both orders. Infinite-order coordinates never return for positive k.')),visual:V('product')}),
 E('cyclic-product','两个循环群的直积何时循环','When a product of cyclic groups is cyclic',String.raw`C_m\times C_n\cong C_{mn}\iff\gcd(m,n)=1`, '对正整数 m,n，直积为循环群当且仅当两个阶互素。关键比较是元素可能达到的最大阶与群的总阶。','For positive m,n, the product is cyclic exactly when the orders are coprime. Compare the largest possible element order with mn.',{proof:P(B('若 gcd(m,n)=1，两个生成元组成的元素阶为 lcm(m,n)=mn，因此生成全群。','If m and n are coprime, a pair of generators has order mn and generates the whole product.'),B('若 gcd(m,n)>1，任意元素的阶都整除 lcm(m,n)<mn，所以没有生成元。','If they are not coprime, every element order divides lcm(m,n)<mn, so no element generates the product.')),visual:V('product')}),
 E('internal','内部直积分解','Internal direct products',String.raw`G=HK,\ H,K\trianglelefteq G,\ H\cap K=\{e\}\quad\Longrightarrow\quad G\cong H\times K`, '若两个正规子群交平凡且乘积覆盖 G，则每个元素都能唯一写成 hk，且两个因子互相交换。','If two normal subgroups intersect trivially and their product covers G, every element has a unique expression hk and the factors commute.',{proof:P(B('对 h∈H,k∈K，交换子 hkh⁻¹k⁻¹ 因 H、K 都正规而同时属于 H、K，故等于 e。','The commutator hkh⁻¹k⁻¹ belongs to both H and K by normality; trivial intersection forces it to be e.'),B('定义 H×K→G，(h,k)↦hk。因两个因子交换，映射保乘法；G=HK 保证满射。','The map (h,k)↦hk preserves multiplication because the factors commute, and is onto by G=HK.'),B('若 hk=e，则 h=k⁻¹∈H∩K，所以 h=k=e，核平凡，映射是同构。','If hk=e, h=k⁻¹ belongs to the intersection. Thus both are identities and the map is injective.')),warning:B('仅有 H∩K={e} 且 G=HK 不够：D₃=⟨r⟩⟨s⟩，但 D₃ 不是 C₃×C₂。','Trivial intersection and G=HK alone do not suffice: D₃=⟨r⟩⟨s⟩ is not C₃×C₂.')}),
 E('crt','从群论看中国剩余定理','The Chinese remainder map',String.raw`\mathbb Z/mn\mathbb Z\longrightarrow\mathbb Z/m\mathbb Z\times\mathbb Z/n\mathbb Z,\quad[x]\mapsto([x],[x])`, '当 m,n 互素时，这个自然映射是加法群同构。一个整数的模 mn 信息，可以由模 m 与模 n 的两份信息共同确定。','For coprime m,n, the natural residue map is an isomorphism of additive groups. The two residues together determine the residue modulo mn.',{proof:P(B('模 mn 相等蕴含模 m、模 n 分别相等，所以映射良定义且保加法。','Congruence modulo mn implies congruence modulo m and n; the map is well-defined and additive.'),B('若 x 同时被 m,n 整除，由互素性得 mn∣x，因此核平凡。','If both m and n divide x, coprimality implies mn∣x, so the kernel is trivial.'),B('源、目标都有 mn 个元素，有限集合上的单射于是为双射。','Both sets have mn elements, so this injection is a bijection.')),example:B('求 x≡2 mod 3，x≡3 mod 5：在模 15 下唯一解为 [8]。','The congruences x≡2 mod 3 and x≡3 mod 5 have the unique solution [8] modulo 15.')})
]);
add('2.5','群在集合上的作用','Group actions on sets',[
 E('action','群成为集合的运动规则','A group as rules for motion',String.raw`e\cdot x=x,\qquad(gh)\cdot x=g\cdot(h\cdot x)`, '左作用是映射 G×X→X，满足单位元与复合兼容两条公理。每个 g 都给出 X 的一个双射，逆变换由 g⁻¹ 给出。','A left action is a map G×X→X satisfying identity and composition laws. Each g acts bijectively, with inverse given by g⁻¹.',{visual:V('action'),example:B('D₄ 作用在正方形的顶点集，也可作用在边集、对角线集。改变作用对象，即使群不变，轨道与稳定子也会改变。','D₄ acts on vertices, edges or diagonals of a square. Changing the acted-on set changes orbits and stabilizers.')}),
 E('representation','作用等价于置换表示','Actions and permutation representations',String.raw`G\curvearrowright X\quad\Longleftrightarrow\quad \rho:G\to\operatorname{Sym}(X)`, '令 ρ(g)(x)=g·x。作用公理正是 ρ 保乘法的条件。核由固定每个点的元素组成；核平凡的作用叫忠实作用。','Set ρ(g)(x)=g·x. The action law says exactly that ρ is a homomorphism. Its kernel consists of elements fixing every point; a trivial kernel means a faithful action.',{proof:P(B('作用给出的每个 ρ(g) 可逆，且 ρ(gh)=ρ(g)ρ(h)，所以得到同态。','Each action map is invertible and ρ(gh)=ρ(g)ρ(h), giving a homomorphism.'),B('反向，从同态定义 g·x=ρ(g)(x)，单位元与复合公理直接成立。','Conversely define g·x=ρ(g)(x); the homomorphism laws give both action axioms.')),example:B('左正则作用 G↷G 总是忠实的；平凡作用 g·x=x 的核是整个 G。','The left regular action is always faithful, while a trivial action has kernel G.')}),
 E('orbit','轨道与稳定子','Orbits and stabilizers',String.raw`Gx=\{g\cdot x:g\in G\},\qquad G_x=\{g:g\cdot x=x\}`, '轨道回答“x 能走到哪里”；稳定子回答“哪些运动把 x 留在原位”。稳定子是子群，轨道给出 X 的分类。','An orbit records where x can move; its stabilizer records the motions leaving it fixed. Stabilizers are subgroups and orbits partition X.',{proof:P(B('e 固定 x；若 a,b 固定 x，则 b⁻¹ 也固定 x，故 ab⁻¹ 固定 x，稳定子满足子群判别。','Identity fixes x, and if a,b fix x then ab⁻¹ fixes x, proving the subgroup criterion.'),B('“y=g·x 对某个 g 成立”是等价关系：用 e、g⁻¹、复合分别验证反身、对称、传递。','Reachability is an equivalence relation: use e, inverses and composition for its three properties.')),visual:V('action')}),
 E('orbit-stabilizer','轨道—稳定子定理','The orbit–stabilizer theorem',String.raw`G/G_x\overset{\sim}{\longrightarrow}Gx,\quad gG_x\mapsto g\cdot x;\qquad |Gx|=[G:G_x]`, '这里 G/Gₓ 首先表示左陪集集合，不要求 Gₓ 正规。有限群时 |G|=|Gx|·|Gₓ|。','Here G/Gₓ means a left-coset set, not necessarily a quotient group. For finite G, |G|=|Gx|·|Gₓ|.',{proof:P(B('良定义：gGₓ=hGₓ 意味着 h⁻¹g 固定 x，所以 g·x=h·x。','Equal cosets mean h⁻¹g fixes x, so g·x=h·x.'),B('单射：反过来，g·x=h·x 意味着 h⁻¹g∈Gₓ，所以两个陪集相同。','Conversely, equal images imply h⁻¹g∈Gₓ and hence equal cosets.'),B('满射：轨道中的点按定义都形如 g·x。由此得到双射及计数公式。','Every orbit point is g·x by definition, proving surjectivity and the counting formula.')),visual:V('action')}),
 E('conjugacy','共轭作用与类方程','Conjugation and the class equation',String.raw`|G|=|Z(G)|+\sum_i[G:C_G(x_i)]`, '取作用 g·x=gxg⁻¹。轨道是共轭类，稳定子是中心化子。单元素共轭类恰是中心元素；求和遍历所有非中心共轭类的一个代表。','For g·x=gxg⁻¹, the orbits are conjugacy classes and stabilizers are centralizers. Singleton classes are central elements; the sum uses one representative of each noncentral class.',{proof:P(B('g 固定 x ⇔ gxg⁻¹=x ⇔ gx=xg，因此 Gₓ=C_G(x)。','The stabilizer equation gxg⁻¹=x is equivalent to gx=xg.'),B('轨道—稳定子定理给出共轭类大小 [G:C_G(x)]。类大小为 1 当且仅当 x∈Z(G)。','Orbit–stabilizer gives the class size. The class is a singleton exactly for central elements.'),B('把 G 按所有共轭类分块相加，得到类方程。','Sum the sizes of the disjoint conjugacy classes.')),visual:V('conjugation')}),
 E('p-center','有限 p 群的中心非平凡','The center of a finite p-group',String.raw`|G|=p^n,\ n\ge1\quad\Longrightarrow\quad |Z(G)|\equiv0\pmod p`, '非平凡有限 p 群的中心至少含 p 个元素。这是类方程把群结构转化为整除问题的典型应用。','A nontrivial finite p-group has at least p central elements. The class equation turns a structural question into divisibility.',{proof:P(B('非中心共轭类大小是大于 1 的 p 的幂：它是 |G| 除以某个子群阶。','A noncentral class has size a power of p greater than 1, by orbit–stabilizer and Lagrange.'),B('所以类方程中非中心项都被 p 整除；|G| 也被 p 整除，因而 p∣|Z(G)|。','Every noncentral term and |G| are divisible by p; so is |Z(G)|.'),B('e∈Z(G)，中心非空，因此其阶不可能为 0，至少为 p。','The center contains e and is nonempty, hence its positive order is at least p.')),example:B('进一步：p² 阶群一定交换。若中心仅 p 阶，则 G/Z(G) 为 p 阶循环群；而 G/Z(G) 循环会迫使 G 交换，矛盾。','Consequently groups of order p² are abelian. Otherwise the center would have order p and G/Z(G) would be cyclic, forcing G abelian.'),extraProof:P(B('若 G/Z(G)=⟨aZ(G)⟩，任意 x=aⁱz、y=aʲw，其中 z,w 在中心；于是 xy=aⁱ⁺ʲzw=yx。','If G/Z(G) is generated by aZ(G), write x=aⁱz and y=aʲw with central z,w; then xy=yx.'))}),
 E('burnside','用不动点数轨道','Counting orbits by fixed points',String.raw`|X/G|=\frac1{|G|}\sum_{g\in G}|\operatorname{Fix}(g)|`, '有限群作用在有限集上，轨道数等于每个群元素的不动点个数的平均值。计数前必须明确“哪种对称视为等价”。','For a finite group acting on a finite set, the orbit count is the average number of fixed points. Specify which symmetries count as equivalences before counting.',{proof:P(B('计算集合 T={(g,x):g·x=x} 的大小。先固定 g，得 |T|=∑g |Fix(g)|。','Count pairs (g,x) with g·x=x by first fixing g.'),B('再固定 x，得 |T|=∑x |Gₓ|。一个轨道中稳定子的阶相同，每个轨道贡献 |Gx|·|Gₓ|=|G|。','Counting by x gives ∑x|Gₓ|. Stabilizers along an orbit have equal size, so each orbit contributes |G|.'),B('故 ∑g |Fix(g)|=|X/G|·|G|，两边除以 |G|。','Equate the counts and divide by |G|.')),visual:V('burnside')}),
 E('colorings','正方形二色着色','Two-colorings of a square',String.raw`\frac{16+2+4+2+4+8+4+8}{8}=6`, '用两种颜色给四个顶点着色，允许整体旋转与反射。有 16 种带标号着色；按 D₄ 的对称合并后有 6 类。','Color four vertices with two colors, identifying rotations and reflections. There are 16 labeled colorings and six orbits under D₄.',{visual:V('burnside'),example:B('一个置换固定着色，当且仅当同一轮换内的顶点颜色相同。因此含 c 个轮换的置换固定 2ᶜ 种二色着色。只允许旋转 C₄ 时，此例也得到 6 类，但一般并不相同。','A coloring is fixed exactly when colors are constant on permutation cycles. A permutation with c cycles fixes 2ᶜ two-colorings. Rotations alone also give six here, but not in general.')}),
 E('coset-action','陪集作用连接群与置换','Coset actions connect groups to permutations',String.raw`G\curvearrowright G/H,\quad g\cdot(aH)=(ga)H,\qquad G\to S_{[G:H]}`, '任意子群 H 给出陪集作用；H 不必正规。指数越小，得到的置换表示维度越小，可以用来限制群结构。','Any subgroup gives an action on its left cosets, without requiring normality. Small index yields a small permutation representation and strong structural restrictions.',{proof:P(B('若 aH=bH，则 (ga)H=(gb)H，故作用良定义；作用公理来自 G 的结合律。','Equal cosets remain equal after left multiplication; associativity gives the action law.'),B('g 固定每个 aH 当且仅当 a⁻¹ga∈H 对所有 a 成立。因此作用核是 ⋂a aHa⁻¹。','An element fixes every coset exactly when a⁻¹ga∈H for all a; the kernel is the intersection of all conjugates of H.'),B('这个核是包含在 H 内的最大正规子群。取 H={e} 就恢复凯莱的正则表示。','This is the largest normal subgroup contained in H. For H={e}, it recovers Cayley’s regular representation.'))})
]);
add('2.6','西罗定理','Sylow theorems',[
 E('statements','三条定理，一套计数工具','Three theorems, one counting toolkit',String.raw`|G|=p^a m,\ p\nmid m:\quad |P|=p^a,\quad n_p\mid m,\quad n_p\equiv1\pmod p`, '设 G 为有限群，p 为素数，a≥1。存在 pᵃ 阶子群（西罗 p 子群）；每个 p 子群包含在某个西罗 p 子群中；所有西罗 p 子群彼此共轭；其个数 nₚ 满足上述整除与同余条件。本课简述定理结论，重点用于解题。','Let G be finite and p prime, with a≥1. Sylow p-subgroups of order pᵃ exist; every p-subgroup lies in one; all Sylow p-subgroups are conjugate; their number satisfies the displayed constraints. This course states the theorems and emphasizes applications.',{visual:V('sylow'),warning:B('右侧筛出的 nₚ 候选值只是必要条件，不能据此声称每个数都能在实际群中出现。','The candidate counts satisfy necessary conditions only; not every candidate is necessarily realized.')}),
 E('normalizer','把共轭性翻译成轨道','Conjugacy as an orbit',String.raw`n_p=[G:N_G(P)],\qquad N_G(P)=\{g:gPg^{-1}=P\}`, 'G 通过共轭作用在全部西罗 p 子群上。共轭定理说这个作用传递，稳定子正是正规化子。','G acts by conjugation on its Sylow p-subgroups. Sylow conjugacy says this action is transitive; the stabilizer is the normalizer.',{proof:P(B('g·P=gPg⁻¹ 仍为同阶子群，因此仍为西罗 p 子群。','A conjugate has the same order, so it is again Sylow.'),B('西罗共轭定理保证只有一个轨道。固定 P 的元素恰是 N_G(P)。','Conjugacy gives one orbit, and the stabilizer of P is N_G(P).'),B('由轨道—稳定子得 nₚ=[G:N_G(P)]。又 P≤N_G(P)，指数乘法给出 nₚ∣[G:P]=m。','Orbit–stabilizer gives the formula. Since P≤N_G(P), the index multiplication formula yields nₚ∣m.')),example:B('这一步解释“个数整除 m”的来源；nₚ≡1 mod p 则是西罗定理的另一条约束。','This explains divisibility by m; the congruence nₚ≡1 mod p is the other Sylow constraint.')}),
 E('unique','唯一性等价于正规性','Uniqueness is equivalent to normality',String.raw`P\trianglelefteq G\iff n_p=1`, '对西罗 p 子群 P，正规与唯一等价。解题时先列出同时满足“整除”和“同余”的数；若只剩 1，就立即得到正规子群。','A Sylow subgroup is normal exactly when it is unique. Intersect the divisibility and congruence conditions; if only 1 remains, normality follows.',{proof:P(B('若只有一个西罗 p 子群，任意共轭 gPg⁻¹ 必等于它，因此 P 正规。','If P is unique, every conjugate equals P, so it is normal.'),B('若 P 正规，每个共轭都是 P；所有西罗 p 子群又都与 P 共轭，因此只能有一个。','If P is normal, all its conjugates equal P, and Sylow conjugacy gives uniqueness.')),visual:V('sylow')}),
 E('order-fifteen','完整例题：15 阶群','Worked example: groups of order 15',String.raw`|G|=15\quad\Longrightarrow\quad G\cong C_{15}`, '先找两个唯一的西罗子群，再证明它们形成内部直积，最后使用互素循环群直积的结论。','Find two unique Sylow subgroups, show they give an internal direct product, then use coprime cyclic orders.',{proof:P(B('n₅∣3 且 n₅≡1 mod 5，只能 n₅=1。n₃∣5 且 n₃≡1 mod 3，也只能 n₃=1。','The Sylow constraints give n₅=1 and n₃=1.'),B('设 P,Q 分别为 3、5 阶子群。它们都正规；交集的阶同时整除 3、5，故交平凡。','Let P,Q have orders 3,5. Both are normal and their intersection is trivial by Lagrange.'),B('映射 P×Q→G，(p,q)↦pq 为单射，因此 PQ 有 15 个元素，等于 G。','The product map is injective, so PQ has 15 elements and equals G.'),B('于是 G≅P×Q≅C₃×C₅≅C₁₅。','Thus G≅C₃×C₅≅C₁₅.')),visual:V('sylow',{order:15,prime:3})}),
 E('order-twenty-one','完整例题：21 阶群','Worked example: groups of order 21',String.raw`|G|=21\quad\Longrightarrow\quad n_7=1,\quad n_3\in\{1,7\}`, '唯一的 7 阶子群保证 G 不是单群，但并不保证 G 交换。必须保留 n₃=7 的可能性。','The unique subgroup of order 7 makes G nonsimple, but does not force commutativity. The possibility n₃=7 must remain.',{proof:P(B('n₇∣3 且 n₇≡1 mod 7，故 n₇=1。','The Sylow constraints give n₇=1.'),B('n₃∣7 且 n₃≡1 mod 3，1 与 7 都符合。因此不能直接推出西罗 3 子群正规。','Both 1 and 7 satisfy the constraints for n₃; normality is not forced.'),B('例如在 ℤ₇ 上取 a(x)=x+1、b(x)=2x。变换 x↦2ʲx+i（0≤j<3，0≤i<7）组成一个 21 阶群。','On ℤ₇, the maps x↦2ʲx+i, with 0≤j<3 and 0≤i<7, form a group of order 21.'),B('bab⁻¹=a²≠a，所以此群不交换。计数条件没有排除它。','Here bab⁻¹=a²≠a, so this group is nonabelian.')),visual:V('sylow',{order:21,prime:3})}),
 E('order-thirty','计数排除：30 阶群','Counting contradiction: order 30',String.raw`|G|=30\quad\Longrightarrow\quad n_3=1\ \text{or}\ n_5=1`, '当单独一组同余条件不能强迫唯一时，把不同素数阶元素的数量放在一起计数。此例说明 30 阶群一定有非平凡真正规子群。','When individual constraints do not force uniqueness, count elements of different prime orders together. This proves that a group of order 30 has a nontrivial proper normal subgroup.',{proof:P(B('n₅∣6、n₅≡1 mod 5，所以 n₅=1 或 6；n₃∣10、n₃≡1 mod 3，所以 n₃=1 或 10。','The possibilities are n₅∈{1,6} and n₃∈{1,10}.'),B('假设两者均不为 1。不同 5 阶子群交平凡，所以共有 6×4=24 个 5 阶元素。','Assume neither is 1. Distinct order-5 subgroups intersect trivially, giving 24 elements of order 5.'),B('同理有 10×2=20 个 3 阶元素。两种阶不同的元素互不重复，再加单位元，至少 45 个元素，矛盾。','Similarly there are 20 elements of order 3. Along with the identity this gives at least 45 elements, a contradiction.'),B('故至少一个西罗子群唯一，因而正规。','At least one of these Sylow subgroups is unique and normal.')),warning:B('这类“不同子群仅在 e 相交”的计数用于素数阶子群；不能不加说明地推广到任意 pᵃ 阶子群。','Distinct prime-order subgroups intersect trivially; this argument does not automatically extend to arbitrary prime-power orders.')}),
 E('order-twelve','群作用再登场：12 阶群','Group actions return: order 12',String.raw`|G|=12\quad\Longrightarrow\quad G\text{ is not simple}`, '西罗约束给出 n₃=1 或 4。若等于 4，让 G 作用在这四个西罗子群上，把问题送进 S₄。','Sylow gives n₃=1 or 4. In the second case, conjugation on the four Sylow subgroups gives a map to S₄.',{proof:P(B('若 n₃=1，已有正规 3 阶子群。以下设 n₃=4，并反设 G 为单群。','If n₃=1 there is a normal subgroup of order 3. Otherwise suppose, for contradiction, G is simple.'),B('共轭作用得到 ρ:G→S₄。作用传递且四个点不止一个，因此 ρ 不平凡；核正规，由单性得核平凡。','Conjugation gives a nontrivial transitive action on four points. Simplicity forces its kernel to be trivial.'),B('sgn∘ρ:G→C₂ 的核正规；它不可能单射（12>2），所以在单性假设下只能为平凡映射。于是 ρ(G)⊆A₄。','The sign composite cannot be injective into C₂. Simplicity forces it to be trivial, so the image lies in A₄.'),B('两边均为 12 阶，因此 G≅A₄。但 V={e,(12)(34),(13)(24),(14)(23)} 是 A₄ 的真正规子群：乘法封闭，且共轭保持双对换类型。矛盾。','Both groups have order 12, so G≅A₄. But its identity and three double transpositions form a proper normal Klein four subgroup, a contradiction.'))}),
 E('synthesis','群论解题路线','A group-theoretic problem-solving route',String.raw`|G|\to[G:H]\to G\curvearrowright X\qquad N\trianglelefteq G\to G/N`, '先看元素阶与子群指数，再选作用；用轨道—稳定子、类方程和西罗计数找到结构；最后用同态与商群把结构说清楚。','Start with orders and indices, then choose an action. Use orbit–stabilizer, the class equation and Sylow counts to find structure, then express it through homomorphisms and quotients.',{example:B('期中复习任务：分别证明 15 阶群循环、21 阶群不一定交换、30 阶群不单。每一步注明使用哪一条定理以及它的条件。','Review tasks: prove groups of order 15 are cyclic, construct a nonabelian group of order 21, and prove groups of order 30 are not simple. State the hypotheses at each step.'),visual:V('sylow',{order:30,prime:5})})
]);
add('2.7','自由群与群的表达','Free groups and group presentations',[
 E('words','把符号组成词','Words in generators and inverses',String.raw`S^{\pm1}=\{a,a^{-1},b,b^{-1},\ldots\}`, '从生成符号及其形式逆符号拼出有限词。空词代表单位元；相邻的 xx⁻¹ 或 x⁻¹x 可以消去。此节为拓展阅读。','Build finite words from generators and their formal inverses. The empty word is the identity; adjacent inverse pairs cancel. This section is optional reading.',{visual:V('words'),example:B('ab b⁻¹a⁻¹ 消去为空词，但 aba⁻¹b⁻¹ 不能消去；非交换性体现在不能擅自交换字母。','abb⁻¹a⁻¹ reduces to the empty word, whereas aba⁻¹b⁻¹ does not. Letters cannot be freely commuted.')}),
 E('reduction','约化词与唯一性','Reduced words and uniqueness',String.raw`\operatorname{red}(uv)`, '不含相邻逆符号的词叫约化词。可用栈逐字读取：新字母若与栈顶互逆就弹出，否则入栈。结果不依赖消去顺序。','A reduced word has no adjacent inverse pair. A stack reads letters left to right, canceling inverse neighbors. The final reduced word is independent of cancellation order.',{proof:P(B('每次消去都使长度减少 2，因此消去过程一定停止。','Each cancellation decreases length by two, so the process terminates.'),B('两个可消去对若不重叠，消去次序互不影响；若重叠，局部只能是 xx⁻¹x 或 x⁻¹xx⁻¹，两种选择都留下同一个字母。','Disjoint cancellations commute. Overlapping cancellations occur only in xx⁻¹x or x⁻¹xx⁻¹ and give the same result.'),B('对词长归纳：比较两条消去路径的第一步，利用上面的局部相容性合到同一个较短词，再用归纳，得到相同最终约化词。','Induct on word length. The first two cancellation choices can be joined at a shorter word; induction then gives the same reduced form.')),visual:V('words')}),
 E('free-group','自由群的运算','The free-group operation',String.raw`u*v=\operatorname{red}(uv),\qquad (x_1\cdots x_k)^{-1}=x_k^{-1}\cdots x_1^{-1}`, '所有约化词在“拼接后约化”的运算下构成自由群 F(S)。自由指除了群公理迫使的消去外，不加入额外关系。','Reduced words form F(S) under concatenation followed by reduction. Freeness means there are no additional relations beyond cancellations forced by the group axioms.',{proof:P(B('唯一约化性给出 red(red(uv)w)=red(uvw)=red(u red(vw))，因此结合律成立。','Unique reduction gives red(red(uv)w)=red(uvw)=red(u red(vw)), proving associativity.'),B('空词是双侧单位元；词倒序逐字取逆后，与原词拼接可全部消去，得到双侧逆元。','The empty word is a two-sided identity. Reversing and inverting every letter gives a two-sided inverse.')),visual:V('words')}),
 E('universal','自由群的泛性质','The universal property',String.raw`f:S\to G\quad\Longrightarrow\quad\exists!\,\bar f:F(S)\to G`, '任意指定生成符号在群 G 中的像，都唯一延伸为 F(S) 到 G 的同态。只要给出生成元的像，词的像就被迫确定。','Every assignment of generators to elements of a group extends uniquely to a homomorphism from the free group.',{proof:P(B('把词 x₁…xₖ 送到对应像的乘积；形式逆符号送到相应逆元。','Evaluate each word as the product of assigned images, sending inverse symbols to inverses.'),B('消去相邻逆符号不改变乘积，所以约化不改变结果，且拼接对应乘法。得到同态。','Canceling adjacent inverse symbols does not change the product; concatenation becomes multiplication.'),B('任何延伸 f 的同态都必须按此公式作用于每个词，因此唯一。','Any homomorphism extending f must evaluate words this way, giving uniqueness.'))}),
 E('presentation','生成元与关系','Generators and relations',String.raw`\langle S\mid R\rangle=F(S)/\langle\!\langle R\rangle\!\rangle`, '把关系词强制变为单位元，需要商掉它们生成的最小正规子群，称为正规闭包。只商掉普通生成子群未必可行。','To force relator words to become identities, quotient by their normal closure, the smallest normal subgroup containing them. An ordinary generated subgroup may not be normal.',{example:B('Cₙ=⟨a∣aⁿ=e⟩；Dₙ=⟨r,s∣rⁿ=s²=e, srs=r⁻¹⟩。等式 u=v 对应关系词 uv⁻¹=e。','Examples: Cₙ=⟨a∣aⁿ=e⟩ and Dₙ=⟨r,s∣rⁿ=s²=e, srs=r⁻¹⟩. An equation u=v corresponds to the relator uv⁻¹.')}),
 E('verify','关系式为什么恰好定义 Dₙ','Why the presentation gives exactly Dₙ',String.raw`\langle r,s\mid r^n=s^2=e,\ srs=r^{-1}\rangle\cong D_n\quad(n\ge3)`, '验证一组几何变换满足关系，只能得到一个满射；还要证明关系没有留下额外元素，才能完成同构证明。','Checking relations in a geometric group gives a surjection. To prove an isomorphism, also show the presentation leaves no extra elements.',{proof:P(B('由 sr=r⁻¹s 可把每个 s 移到词的右端；rⁿ=e、s²=e 将词约成 rᵏsᵉ，0≤k<n、e∈{0,1}。所以所表达的群至多有 2n 个元素。','Move every s to the right and reduce exponents. Every word becomes rᵏsᵉ, giving at most 2n elements.'),B('正 n 边形的旋转与反射满足这些关系并生成 Dₙ，因此存在到 Dₙ 的满同态。','Geometric rotation and reflection satisfy the relations and generate Dₙ, giving a surjection.'),B('Dₙ 确有 2n 个元素，所以源群至少有 2n 个；上、下界相同，满射于是为同构。','Dₙ has 2n elements, so the upper bound is attained and the surjection is an isomorphism.')),visual:V('polygon')})
],{optional:true});
})();
