/* Original questions, keyed by textbook section; not copied exercise numbers. */
(()=>{
const Q=(zh,en,options,answer,why,whyEn)=>({question:[zh,en],options,answer,reason:[why,whyEn]});
const T=(zh,en,answer,answerEn)=>({question:[zh,en],written:true,reason:[answer,answerEn]});
window.GroupCourseExercises={
'1.3':[
 Q('ℤ₆ 中哪一个集合是加法子群？','Which subset is an additive subgroup of ℤ₆?',['{0,2,4}','{0,1,2}','{1,3,5}','{0,2}'],0,'{0,2,4} 对减法封闭；其余各集不满足子群判别。','The first set is closed under subtraction; the others fail the subgroup criterion.'),
 Q('G 的非空子集 H 对乘法封闭，能立即推出什么？','A nonempty subset H is closed under products. What follows?',[['一定是子群','Always a subgroup'],['H 有限时是子群','A subgroup if H is finite'],['一定正规','Always normal'],['一定交换','Always abelian']],1,'有限性让正幂重复，从而得到单位元与逆元。无限情形可用正整数加法作反例。','Finiteness forces powers to repeat and supplies identity and inverses. Positive integers under addition refute the infinite case.'),
 Q('2ℤ 与 3ℤ 生成的子群是什么？','What subgroup of ℤ is generated by 2ℤ and 3ℤ?',['6ℤ','2ℤ∪3ℤ','ℤ','{0}'],2,'3−2=1 属于所生成子群，因此它包含所有整数。','The generated subgroup contains 3−2=1, so it is all of ℤ.'),
 Q('若 H,K≤G，哪项总成立？','For H,K≤G, which always holds?',[['H∪K≤G','H∪K≤G'],['HK=KH','HK=KH'],['H∩K≤G','H∩K≤G'],['H=K','H=K']],2,'交集含单位元，并继承 ab⁻¹ 的封闭性。','The intersection contains the identity and is closed under ab⁻¹.'),
 T('证明：两个子群的并是子群，当且仅当其中一个包含另一个。','Prove that the union of two subgroups is a subgroup iff one contains the other.','包含方向显然。反向若都不包含，取 h∈H∖K、k∈K∖H。若 H∪K 为子群，则 hk 属于 H 或 K；前者推出 k=h⁻¹(hk)∈H，后者推出 h=(hk)k⁻¹∈K，均矛盾。','Containment makes the union a subgroup. Conversely choose h∈H∖K and k∈K∖H. If hk is in H then k is in H; if it is in K then h is in K. Both contradict the choices.')],
'1.4':[
 Q('ℤ₄ 与 C₂×C₂ 不同构，最直接的理由是什么？','Why are ℤ₄ and C₂×C₂ not isomorphic?', [['阶不同','Different group orders'],['只有前者有 4 阶元素','Only the former has an element of order 4'],['只有前者交换','Only the former is abelian'],['后者没有单位元','The latter has no identity']],1,'同构保持元素阶；两个群都为四阶且交换。','Isomorphisms preserve element orders. Both groups have order four and are abelian.'),
 Q('f:ℤ→2ℤ，f(k)=2k，在加法下是？','Under addition, f:ℤ→2ℤ, k↦2k is?', [['非同态','Not a homomorphism'],['不是满射','Not surjective'],['同构','An isomorphism'],['不是单射','Not injective']],2,'目标是 2ℤ，所以 f 既单又满，并且保持加法。','The codomain is 2ℤ; f is bijective and additive.'),
 Q('凯莱定理为 n 阶群 G 给出什么？','What does Cayley’s theorem give for a group of order n?',[['G≅Sₙ','G≅Sₙ'],['G 同构于 Sₙ 的子群','G is isomorphic to a subgroup of Sₙ'],['G 交换','G is abelian'],['G 循环','G is cyclic']],1,'左正则表示是单射，其像通常只是 Sₙ 的子群。','The left regular representation is injective; its image need not be all of Sₙ.'),
 Q('映射 x↦x⁻¹ 对任意群都是自同构吗？','Is inversion an automorphism of every group?', [['是','Yes'],['恰在交换群时','Exactly for abelian groups'],['仅有限群时','Only for finite groups'],['仅循环群时','Only for cyclic groups']],1,'(xy)⁻¹=y⁻¹x⁻¹。保持乘法等价于所有 x⁻¹、y⁻¹ 交换，也就等价于 G 交换。','Inversion reverses multiplication. It preserves products exactly when the group is abelian.'),
 T('构造 (ℝ,+) 与 (ℝ>0,×) 的同构，并核对三项条件。','Construct an isomorphism (ℝ,+)→(ℝ>0,×) and check its properties.','取 f(x)=exp(x)。exp(x+y)=exp(x)exp(y)，严格单调给出单射，每个正数有实对数给出满射。','Use f(x)=exp(x). It preserves the operation, is injective by strict monotonicity, and is onto by the existence of real logarithms.')],
'1.5':[
 Q('若 |a|=12，则 |a⁸| 等于？','If |a|=12, what is |a⁸|?',['12','8','4','3'],3,'12/gcd(12,8)=3。','12/gcd(12,8)=3.'),
 Q('ℤ₁₂ 的全部生成元是？','Which are all generators of ℤ₁₂?',['1,5,7,11','1,2,3,4','0,4,8','1,11'],0,'生成元对应与 12 互素的剩余类，共 φ(12)=4 个。','Generators are precisely the residues coprime to 12.'),
 Q('12 阶循环群有几个 4 阶子群？','How many subgroups of order 4 does C₁₂ have?',['0','1','3','4'],1,'循环群对群阶的每个正因子都有唯一对应阶子群，这里为 ⟨a³⟩。','There is a unique subgroup for each divisor; here it is ⟨a³⟩.'),
 Q('哪条推论正确？','Which implication is correct?',[['交换 ⇒ 循环','Abelian ⇒ cyclic'],['循环 ⇒ 交换','Cyclic ⇒ abelian'],['有限 ⇒ 循环','Finite ⇒ cyclic'],['子群只有有限个 ⇒ 循环','Finitely many subgroups ⇒ cyclic']],1,'同一元素的幂两两交换；反向可用 C₂×C₂ 否定。','Powers of one element commute. C₂×C₂ refutes the converse.'),
 T('证明：ℤ 的任一非零子群都恰为 dℤ，其中 d 是唯一正整数。','Prove every nonzero subgroup of ℤ is dℤ for a unique positive integer d.','取子群的最小正元素 d。对任意 h，用带余除法 h=qd+r；r=h−qd 仍在子群，0≤r<d，故 r=0。反向 d 的整数倍都在子群。最小正元素的唯一性给出 d 唯一。','Choose the least positive d in the subgroup. Division with remainder forces every h to be divisible by d. All multiples of d belong, and the least positive element is unique.')],
'1.6':[
 Q('先右后左时 (12)(23) 等于？','Using right-to-left composition, (12)(23) equals?',['(123)','(132)','(13)','e'],0,'1→2→3→1，因此是 (123)。','Tracking points gives 1→2→3→1.'),
 Q('(1234)(567) 的阶是多少？','What is the order of (1234)(567)?',['7','12','4','3'],1,'两个轮换不相交，阶为 lcm(4,3)=12。','The disjoint cycles have lengths 4 and 3, giving lcm 12.'),
 Q('(12345) 是奇置换还是偶置换？','Is (12345) odd or even?',[['奇','Odd'],['偶','Even'],['取决于分解','Depends on decomposition'],['没有定义','Undefined']],1,'5 轮换可写为 4 个对换，符号为 +1。','A 5-cycle is a product of four transpositions and has sign +1.'),
 Q('A₄ 中有多少个三轮换？','How many 3-cycles are in A₄?',['4','6','8','12'],2,'选 3 个点有 4 种，每组有两个三轮换，共 8 个。','Choose three points in four ways; each choice gives two cycles.'),
 T('求 σ=(123)(345) 的不相交轮换分解、阶和奇偶性。','Find the disjoint cycle form, order and parity of σ=(123)(345).','逐点计算：1→2→3→4→5→1，所以 σ=(12345)，阶 5，符号 (−1)⁴=+1，为偶置换。','Point tracking gives σ=(12345), of order 5 and sign +1.')],
'1.7':[
 Q('本文 D₅ 的阶是？','What is the order of D₅ in our notation?',['5','10','20','120'],1,'Dₙ 表示正 n 边形完整对称群，含 n 个旋转及 n 个反射。','Dₙ contains n rotations and n reflections.'),
 Q('D₄ 中 sr 等于？','In D₄, sr equals?',['rs','r²s','r³s','r'],2,'由 srs=r⁻¹ 得 sr=r⁻¹s=r³s。','Use sr=r⁻¹s=r³s.'),
 Q('正四面体保定向旋转群同构于？','The rotation group of a tetrahedron is isomorphic to?',['C₁₂','S₄','A₄','D₆'],2,'顶点置换给出恰好 12 个偶置换。','Its vertex action gives exactly the 12 even permutations.'),
 Q('立方体旋转群与 S₄ 的同构用到哪一集合？','Which set gives the cube rotation group an isomorphism with S₄?',[['四条体对角线','Four body-diagonal lines'],['六个面','Six faces'],['八个顶点','Eight vertices'],['十二条边','Twelve edges']],0,'四条体对角线的置换作用是忠实的，源和目标同为 24 阶。','The action on four body diagonals is faithful, and both groups have order 24.'),
 T('利用关系式计算 D₅ 中 (r²s)(r³s)，并解释为什么结果是旋转。','Compute (r²s)(r³s) in D₅ and explain why it is a rotation.','sr³=r⁻³s，所以乘积为 r²r⁻³s²=r⁻¹=r⁴。两个反射复合保持方向，因此是旋转。','Since sr³=r⁻³s, the product is r⁻¹=r⁴. Two reflections compose to an orientation-preserving symmetry.')],
'2.1':[
 Q('ℤ₁₂ 中 H=⟨[4]⟩ 的指数是多少？','What is the index of ⟨[4]⟩ in ℤ₁₂?',['2','3','4','6'],2,'H={0,4,8} 有 3 个元素，指数为 12/3=4。','H has three elements, so the index is four.'),
 Q('左陪集 aH=bH 等价于？','The equality aH=bH is equivalent to?',['b⁻¹a∈H','ab∈H','a=b','ab⁻¹∈H'],0,'由 a=bh 得 b⁻¹a∈H。不能在非交换群中擅自调换次序。','Write a=bh. The order of the factors matters in nonabelian groups.'),
 Q('拉格朗日定理能够保证哪件事？','What does Lagrange’s theorem guarantee?',[['每个因子都有对应阶子群','Every divisor occurs as a subgroup order'],['每个子群阶都整除群阶','Every subgroup order divides the group order'],['同阶子群必相等','Equal-order subgroups coincide'],['每个子群都正规','All subgroups are normal']],1,'定理给出必要整除条件，不是子群存在性定理。','It gives a necessary divisibility condition, not existence for every divisor.'),
 Q('若 |G|=35，G 中能有 6 阶元素吗？','Can a group of order 35 have an element of order 6?',[['能','Yes'],['不能','No'],['只在交换时','Only if abelian'],['无法判断','Undetermined']],1,'元素阶为所生成循环子群的阶，必须整除 35；6 不整除 35。','An element order divides 35, and 6 does not.'),
 T('证明：若 G 有限且 |G| 为奇数，则 g²=e 只能有 g=e。','Show that in a finite group of odd order, g²=e implies g=e.','由 g²=e，g 的阶整除 2；又由拉格朗日定理整除奇数 |G|，所以阶为 1。','The order of g divides both 2 and the odd number |G|, hence equals 1.')],
'2.2':[
 Q('哪一种子群一定正规？','Which subgroup is necessarily normal?',[['阶为 2','Order two'],['指数为 2','Index two'],['循环子群','Cyclic'],['真子群','Proper']],1,'指数 2 时，群外的唯一陪集同时是 G∖H，因此左右陪集相同。','At index two, the only nontrivial left and right cosets both equal G∖H.'),
 Q('D₃/⟨r⟩ 的阶是多少？','What is the order of D₃/⟨r⟩?',['2','3','6','9'],0,'旋转子群有 3 个元素，所以商群阶为 6/3=2。','The rotation subgroup has order three, so the quotient has order two.'),
 Q('商群 G/N 的单位元是什么？','What is the identity of G/N?',['G','e','N','∅'],2,'商群的元素是陪集；单位陪集是 eN=N。','Quotient elements are cosets; the identity is eN=N.'),
 Q('为何在定义 (aN)(bN)=abN 时需要正规性？','Why is normality needed for (aN)(bN)=abN?',[['使 G 有限','To make G finite'],['使代表元选择无关','To make it independent of representatives'],['使 N 循环','To make N cyclic'],['使 G 交换','To make G abelian']],1,'正规性使 b⁻¹n₁b 留在 N，从而换代表后仍得到 abN。','Normality puts b⁻¹n₁b in N, preserving the product coset.'),
 T('在 D₃ 中令 H={e,s}。用 eH=sH 展示陪集乘法并不良定义。','For H={e,s} in D₃, use eH=sH to show coset multiplication is ill-defined.','分别与 rH 相乘，代表 e 给出 rH={r,rs}；代表 s 给出 srH={r²s,r²}，二者不同。','Multiply by rH. Representative e gives {r,rs}, while representative s gives {r²s,r²}; these are different cosets.')],
'2.3':[
 Q('φ:ℤ→ℤ₆，[k] 的自然映射之核为？','What is the kernel of the natural map ℤ→ℤ₆?',['{0}','ℤ₆','6ℤ','ℤ'],2,'核是所有被 6 整除的整数。','The kernel is the set of multiples of six.'),
 Q('同态 φ 单射当且仅当？','A homomorphism φ is injective iff?',[['像为目标群','Its image is the codomain'],['核只有单位元','Its kernel is trivial'],['源群有限','The domain is finite'],['核为源群','Its kernel is the domain']],1,'φ(a)=φ(b) ⇔ b⁻¹a∈ker φ。','Equal images are equivalent to b⁻¹a lying in the kernel.'),
 Q('同态基本定理的正确结论是？','Which is the first isomorphism theorem?',['G/ker φ≅im φ','G≅im φ',['G/ker φ≅K 总成立','G/ker φ≅K always'],'ker φ≅im φ'],0,'只有 φ 满射时，像才等于整个目标群 K。','The image equals K only if φ is surjective.'),
 Q('若 G 有 24 个元素且 |ker φ|=6，则 |im φ| 为？','If |G|=24 and |ker φ|=6, what is |im φ|?',['4','6','18','144'],0,'每个非空纤维都是大小为 6 的核陪集，因此像有 24/6=4 个元素。','Each nonempty fiber has size six, so there are four image elements.'),
 T('证明：若 N◁G，商映射 π:G→G/N 满射且核恰为 N。','Prove the quotient map π:G→G/N is onto with kernel N.','π(g)=gN；π(gh)=ghN=(gN)(hN)，所以保乘法。每个陪集都有代表，故满射。π(g)=N 当且仅当 g∈N，故核为 N。','The map g↦gN preserves products, reaches every coset, and sends g to the identity coset precisely when g∈N.')],
'2.4':[
 Q('ℤ₄×ℤ₆ 中 ([1],[1]) 的阶是多少？','What is the order of ([1],[1]) in ℤ₄×ℤ₆?',['10','12','24','6'],1,'lcm(4,6)=12，而不是两阶的乘积。','It is lcm(4,6)=12, not the product.'),
 Q('哪个群同构于 C₁₂？','Which group is isomorphic to C₁₂?',['C₂×C₆','C₃×C₄','C₂×C₂×C₃','C₆'],1,'3 与 4 互素，C₃×C₄ 是 12 阶循环群。','The coprime orders 3 and 4 give a cyclic product of order 12.'),
 Q('内部直积分解中，哪组条件充分？','Which conditions suffice for an internal direct product?',[['仅 H∩K={e}','Only trivial intersection'],['仅 G=HK','Only G=HK'],['H,K 正规、交平凡且 G=HK','Both normal, trivial intersection, G=HK'],['仅 |G|=|H||K|','Only the order equality']],2,'两个正规子群的交换子落在交集中，故因子交换；其余条件给出双射。','Normality puts mixed commutators in the intersection; the remaining conditions give a bijection.'),
 Q('x≡1 mod 3，x≡2 mod 4 的模 12 解是？','Solve x≡1 mod 3, x≡2 mod 4 modulo 12.',['[2]','[6]','[10]','[11]'],2,'10≡1 mod 3 且 10≡2 mod 4；互素性保证模 12 唯一。','10 satisfies both; coprimality ensures uniqueness modulo 12.'),
 T('证明：若 G×H 循环，则 G、H 都循环。','Prove that if G×H is cyclic, then both factors are cyclic.','设 G×H=⟨(g,h)⟩。投影到第一坐标得到 G=⟨g⟩，投影到第二坐标得到 H=⟨h⟩。逆命题还需要额外条件。','Project a generator (g,h) to each coordinate: every element of G is a power of g, and likewise for H. The converse needs additional hypotheses.')],
'2.5':[
 Q('D₄ 作用在正方形顶点上，一个顶点的稳定子阶为？','For D₄ acting on square vertices, what is a vertex stabilizer order?',['1','2','4','8'],1,'轨道有 4 个顶点，|D₄|=8，所以稳定子阶为 2。','The orbit has four points and |D₄|=8, so the stabilizer has order two.'),
 Q('共轭作用中 x 的稳定子是？','What is the stabilizer of x under conjugation?',['⟨x⟩','Z(G)','C_G(x)','G/Z(G)'],2,'gxg⁻¹=x 等价于 gx=xg，正是中心化子的定义。','The stabilizer equation is equivalent to commuting with x.'),
 Q('非平凡有限 p 群的中心至少有多少个元素？','How many elements must the center of a nontrivial finite p-group have?',['1','p','p²','|G|'],1,'类方程给出 p∣|Z(G)|，而中心非空，故至少为 p。','The class equation gives p∣|Z(G)|, and the center is nonempty.'),
 Q('正方形四顶点二色着色，允许 D₄ 对称，轨道数为？','How many two-coloring orbits of square vertices are there under D₄?',['4','6','8','16'],1,'不动点总数为 48，除以群阶 8 得 6。','The fixed-point counts sum to 48; divide by eight.'),
 T('给出一个传递但不忠实的作用，并计算其核。','Give a transitive but nonfaithful action and compute its kernel.','C₄=ℤ/4ℤ 作用在 ℤ/2ℤ 上：[k]·[x]=[k+x] mod 2。它传递，因为 [1] 交换两个点；核是 {[0],[2]}。','Let C₄ act on ℤ/2ℤ by addition modulo 2. It is transitive and has kernel {[0],[2]}.')],
'2.6':[
 Q('|G|=21 时 n₇ 必须等于？','For |G|=21, what must n₇ equal?',['1','3','7','21'],0,'n₇∣3 且 n₇≡1 mod 7，只可能为 1。','It divides 3 and is congruent to 1 modulo 7.'),
 Q('|G|=12 时西罗条件允许的 n₃ 值为？','For order 12, what values of n₃ do the Sylow constraints allow?',[['仅 1','Only 1'],['1 或 4','1 or 4'],['1 或 3','1 or 3'],['2 或 4','2 or 4']],1,'n₃∣4 且 n₃≡1 mod 3，得到 1、4。','It divides 4 and is congruent to 1 modulo 3: 1 or 4.'),
 Q('西罗 p 子群正规当且仅当？','A Sylow p-subgroup is normal iff?',[['p 最小','p is smallest'],['p 最大','p is largest'],['nₚ=1','nₚ=1'],['G 交换','G is abelian']],2,'唯一保证共轭不变；正规结合西罗共轭性保证唯一。','Uniqueness gives conjugate invariance; normality plus Sylow conjugacy gives uniqueness.'),
 Q('30 阶群若同时 n₅=6、n₃=10，至少需要多少个元素？','If n₅=6 and n₃=10 in a group of order 30, how many elements would be required?',['30','31','44','45'],3,'6×4 个 5 阶元素、10×2 个 3 阶元素，再加单位元，共 45，矛盾。','There would be 24 elements of order 5, twenty of order 3, and the identity: 45.'),
 T('证明：若 |G|=pq，p<q 为素数，且 p 不整除 q−1，则 G 循环。','Prove a group of order pq, with primes p<q and p∤(q−1), is cyclic.','n_q∣p 且 n_q≡1 mod q，所以 n_q=1。n_p∣q，候选为 1,q；假设 p∤q−1 排除 q，故 n_p=1。两个素数阶正规子群交平凡，乘积为 G，于是 G≅C_p×C_q≅C_pq。','Sylow forces n_q=1. The candidates for n_p are 1,q; p∤(q−1) excludes q. Both Sylow subgroups are normal, intersect trivially, and form a cyclic direct product.')],
'2.7':[
 Q('自由群中 ab b⁻¹a⁻¹ 的约化结果是？','Reduce abb⁻¹a⁻¹ in the free group.',['ab','a²','e','aba⁻¹b⁻¹'],2,'先消去 bb⁻¹，再消去 aa⁻¹，得到空词。','Cancel bb⁻¹, then aa⁻¹.'),
 Q('自由群中 (ab)⁻¹ 是？','What is (ab)⁻¹ in the free group?',['a⁻¹b⁻¹','b⁻¹a⁻¹','ab','ba'],1,'乘积取逆要倒序，再逐项取逆。','Reverse the order and invert each factor.'),
 Q('添加关系 R 时，要商掉哪个子群？','Which subgroup must be quotiented out to impose relators R?',[['R 自身','R itself'],['R 的普通生成子群','The ordinary subgroup generated by R'],['R 的正规闭包','The normal closure of R'],['中心','The center']],2,'关系必须在共轭下也成立；正规闭包才保证商群有定义。','Relators must remain trivial under conjugation; normal closure makes the quotient well-defined.'),
 Q('一个生成元的自由群同构于？','The free group on one generator is isomorphic to?',['C₂','ℤ','ℤ²','S₃'],1,'只有 aᵏ（k∈ℤ），且没有非零幂等于单位元的额外关系。','Its reduced words are aᵏ for integers k, with no nonzero power forced to be the identity.'),
 T('为什么证明某些变换满足给定关系，还不能直接断言它们就是这个表达所定义的群？','Why does checking relations in a target group not yet prove that the presentation defines that group?','检查关系只能诱导到目标生成群的满同态，其核仍可能非平凡。还需证明单射，例如先用关系式给出标准形与阶的上界，再和目标群的阶比较。','Checking relations induces a surjective homomorphism onto the generated target; its kernel could be nontrivial. Prove injectivity, for example via normal forms and matching order bounds.')]
};
})();
