(()=>{
'use strict';
const M=window.GroupModels,{range,mod}=M;
const en=()=>window.CourseLanguage.language==='en',t=(a,b)=>en()?b:a;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const palette=['var(--diagram-1,var(--pine))','var(--diagram-2,#b88250)','var(--diagram-3,#638397)','var(--diagram-4,#9c779e)','var(--diagram-5,#aa6057)','var(--diagram-6,#8c9062)'];
const setLabel=(G,H)=>'{'+H.map(G.label).join(', ')+'}';
const select=(id,title,opts,value)=>`<label>${title}<select id="${id}">${opts.map(([v,s])=>`<option value="${v}" ${String(v)===String(value)?'selected':''}>${s}</option>`).join('')}</select></label>`;
const buttons=(G,active=[],attr='element')=>G.elements.map(x=>`<button type="button" data-${attr}="${x}" aria-pressed="${active.includes(x)}">${G.label(x)}</button>`).join('');
const circle=(n,labels,active=[],colors=[],perm=null)=>{
const pts=range(n).map(i=>[240+155*Math.cos(2*Math.PI*i/n-Math.PI/2),205+155*Math.sin(2*Math.PI*i/n-Math.PI/2)]);
return `<svg viewBox="0 0 480 410" role="img" aria-label="${t('有限群元素与变换','Finite group elements and transformations')}"><circle cx="240" cy="205" r="155" fill="none" stroke="var(--line)"/>${perm?pts.map((p,i)=>{const q=pts[perm[i]];return i===perm[i]?'':`<path d="M${p[0]} ${p[1]} Q240 205 ${q[0]} ${q[1]}" fill="none" stroke="${palette[i%6]}" opacity=".55"/>`;}).join(''):''}${pts.map((p,i)=>`<g><circle cx="${p[0]}" cy="${p[1]}" r="${n>12?15:21}" fill="${active.includes(i)?palette[colors[i]??0]:'var(--paper,#f6f3ea)'}" stroke="${palette[colors[i]??0]}" stroke-width="1.6"/><text x="${p[0]}" y="${p[1]+6}" text-anchor="middle" font-size="${n>12?14:18}" fill="${active.includes(i)?'var(--white,#fff)':'var(--ink)'}">${esc(labels[i])}</text></g>`).join('')}</svg>`;
};
const stat=(a,b)=>`<div class="group-metric"><strong>${a}</strong><span>${b}</span></div>`;
const shell=(root,controls)=>{root.innerHTML=`<div class="controls group-controls">${controls}</div><div class="group-stage"></div><div class="group-readout" aria-live="polite"></div>`;return [root.querySelector('.group-stage'),root.querySelector('.group-readout')];};
const options=(ns,prefix='')=>ns.map(n=>[n,prefix+n]);
function subgroup(root,generated=false){
const [stage,out]=shell(root,select('group-model',t('群','Group'),[['z12','ℤ₁₂'],['d3','D₃'],['d4','D₄']],'z12')+`<button id="group-clear">${t('清空','Clear')}</button><button id="group-close">${t('生成子群','Generate subgroup')}</button>`);
let G=M.cyclic(12),S=[0,4,8],derived=null;
function draw(){stage.innerHTML=`<div class="group-elements">${buttons(G,S)}</div>${circle(G.elements.length,G.elements.map(G.label),S)}`;const test=M.subgroup(G,S);out.innerHTML=`<div class="group-equation">${generated?'S':'H'} = ${setLabel(G,S)}</div><p>${test.ok?t('满足子群判别','The subgroup criterion holds'):test.empty?t('空集不是子群','The empty set is not a subgroup'):`${G.label(test.witness[0])} ${G.symbol==='+'?'−':'·'} ${G.label(test.witness[1])}${G.symbol==='+'?'':'⁻¹'} = ${G.label(test.witness[2])} ∉ H`}</p>${derived?`<p>${t('反复补入 ab⁻¹ 后：','After adjoining ab⁻¹ repeatedly: ')}⟨S⟩=${setLabel(G,derived.H)}</p><small>${derived.layers.map(h=>setLabel(G,h)).join(' → ')}</small>`:''}`;}
root.querySelector('#group-model').onchange=e=>{G=e.target.value==='z12'?M.cyclic(12):M.dihedral(e.target.value==='d3'?3:4);S=[G.e];derived=null;draw();};root.querySelector('#group-clear').onclick=()=>{S=[];derived=null;draw();};root.querySelector('#group-close').onclick=()=>{derived=M.generated(G,S);draw();};stage.onclick=e=>{const b=e.target.closest('[data-element]');if(!b)return;const a=+b.dataset.element;S=S.includes(a)?S.filter(x=>x!==a):[...S,a].sort((a,b)=>a-b);derived=null;draw();};draw();
}
function cyclic(root,lattice=false){
const [stage,out]=shell(root,select('cycle-n','n',options([4,5,6,8,9,10,12,15,18]),12)+select('cycle-k',t('元素 k','Element k'),options(range(12)),4)+`<button id="cycle-step">${t('再走一步','Take a step')}</button><button id="cycle-reset">${t('回到起点','Reset')}</button>`);let n=12,k=4,step=0;
function draw(){const H=M.generated(M.cyclic(n),[k]).H,d=M.gcd(n,k),pos=mod(step*k,n);stage.innerHTML=circle(n,range(n),H)+`<div class="group-elements">${lattice?M.divisors(n).map(m=>`<button data-order="${m}" aria-pressed="${n/d===m}">${t('阶','order')} ${m}</button>`).join(''):''}</div>`;out.innerHTML=`<div class="group-metrics">${stat(pos,`${step} × ${k} mod ${n}`)}${stat(n/d,t('元素的阶','Element order'))}${stat(d,t('最大公因数','Greatest common divisor'))}</div><p>⟨${k}⟩=${setLabel(M.cyclic(n),H)}</p><p>${M.gcd(n,k)===1?t('这是整个循环群的生成元。','This element generates the whole group.'):t('只走到一个真子群。','The walk stays in a proper subgroup.')}</p>`;}
root.querySelector('#cycle-n').onchange=e=>{n=+e.target.value;k=mod(k,n);step=0;root.querySelector('#cycle-k').innerHTML=options(range(n)).map(([x,l])=>`<option value="${x}" ${x===k?'selected':''}>${l}</option>`).join('');draw();};root.querySelector('#cycle-k').onchange=e=>{k=+e.target.value;step=0;draw();};root.querySelector('#cycle-step').onclick=()=>{step++;draw();};root.querySelector('#cycle-reset').onclick=()=>{step=0;draw();};stage.onclick=e=>{const b=e.target.closest('[data-order]');if(b){k=mod(n/+b.dataset.order,n);root.querySelector('#cycle-k').value=k;step=0;draw();}};draw();
}
function cosets(root,normal=false){
const presets={z6:[M.cyclic(6),[0,3]],z12:[M.cyclic(12),[0,4,8]],rotation:[M.dihedral(3),[0,1,2]],reflection:[M.dihedral(3),[0,3]]};
const key=normal?'reflection':'z6';const [stage,out]=shell(root,select('coset-case',t('例子','Example'),[['z6','ℤ₆ / {0,3}'],['z12','ℤ₁₂ / {0,4,8}'],['rotation','D₃ · ⟨r⟩'],['reflection','D₃ · ⟨s⟩']],key));let [G,H]=presets[key],g=1;
function draw(){const blocks=M.cosets(G,H),left=M.coset(G,H,g),right=M.coset(G,H,g,true);stage.innerHTML=`<div class="group-elements">${buttons(G,[g])}</div><div class="coset-blocks">${blocks.map((b,i)=>`<div style="--block-color:${palette[i%6]}" class="coset-block ${b.includes(g)?'is-active':''}"><small>${G.label(b[0])}H</small>${setLabel(G,b)}</div>`).join('')}</div>${circle(G.elements.length,G.elements.map(G.label),left,G.elements.map(a=>blocks.findIndex(b=>b.includes(a))))}`;out.innerHTML=`<div class="group-equation">${G.label(g)}H=${setLabel(G,left)}<br>H${G.label(g)}=${setLabel(G,right)}</div><p>${M.equal(left,right)?t('本次左右陪集相同。','These two cosets agree.'):t('本次左右陪集不同：已找到不正规的证据。','These cosets differ: a witness of nonnormality.')}</p><div class="group-metrics">${stat(G.elements.length,'|G|')}${stat(H.length,'|H|')}${stat(blocks.length,'[G:H]')}</div><p>${t('检查全部 g 后：','After checking every g: ')}${M.normal(G,H)?'H ◁ G':'H ⋢ G'}</p>`;}
root.querySelector('#coset-case').onchange=e=>{[G,H]=presets[e.target.value];g=1;draw();};stage.onclick=e=>{const b=e.target.closest('[data-element]');if(b){g=+b.dataset.element;draw();}};draw();
}
function quotient(root){
const [stage,out]=shell(root,select('quotient-case',t('商群','Quotient'),[['z6','ℤ₆ / {0,3}'],['d3','D₃ / ⟨r⟩']],'z6'));let G=M.cyclic(6),H=[0,3],a=1,b=2;
function draw(){const blocks=M.cosets(G,H),A=blocks[a],B=blocks[b],C=M.coset(G,H,G.mul(A[0],B[0])),ci=blocks.findIndex(x=>M.equal(x,C));stage.innerHTML=`<div class="controls">${select('quotient-a','A',blocks.map((s,i)=>[i,setLabel(G,s)]),a)}${select('quotient-b','B',blocks.map((s,i)=>[i,setLabel(G,s)]),b)}</div><div class="group-table-wrap"><table class="group-table"><caption>${t('商群运算表','Quotient operation table')}</caption><thead><tr><th>${G.symbol}</th>${blocks.map((s,i)=>`<th>C${i}</th>`).join('')}</tr></thead><tbody>${blocks.map((x,i)=>`<tr><th>C${i}</th>${blocks.map((y,j)=>`<td ${a===i&&b===j?'class="selected"':''}>C${blocks.findIndex(s=>s.includes(G.mul(x[0],y[0])))}</td>`).join('')}</tr>`).join('')}</tbody></table></div><div class="coset-blocks">${blocks.map((s,i)=>`<div class="coset-block" style="--block-color:${palette[i]}">C${i}=${setLabel(G,s)}</div>`).join('')}</div>`;out.innerHTML=`<div class="group-equation">C${a} ${G.symbol} C${b} = C${ci}</div><p>${t('逐一更换两个代表，所有乘积都落在同一个陪集中：','Every choice of representatives lands in the same product coset:')}</p><div class="group-elements">${A.flatMap(x=>B.map(y=>`<span>${G.label(x)} ${G.symbol} ${G.label(y)} = ${G.label(G.mul(x,y))}</span>`)).join('')}</div>`;stage.querySelector('#quotient-a').onchange=e=>{a=+e.target.value;draw();};stage.querySelector('#quotient-b').onchange=e=>{b=+e.target.value;draw();};}
root.querySelector('#quotient-case').onchange=e=>{G=e.target.value==='z6'?M.cyclic(6):M.dihedral(3);H=e.target.value==='z6'?[0,3]:[0,1,2];a=1;b=e.target.value==='z6'?2:1;draw();};draw();
}
function homomorphism(root){
const [stage,out]=shell(root,select('hom-n',t('目标 ℤₙ','Target ℤₙ'),options([2,3,4,6,12]),6)+select('hom-k',t('乘数 k','Multiplier k'),options([0,1,2,3,4,5]),2));let n=6,k=2;
function draw(){const fibers=range(n).map(y=>range(12).filter(x=>mod(k*x,n)===y)),image=fibers.filter(b=>b.length).length;stage.innerHTML=`<div class="group-equation">φ : ℤ₁₂ → ℤ${n},　[x] ↦ [${k}x]</div><div class="fiber-list">${fibers.map((s,y)=>`<div class="fiber-row ${y===0?'kernel-row':''}"><span>${s.length?'{'+s.join(', ')+'}':'∅'}</span><b>↦</b><strong>[${y}]</strong></div>`).join('')}</div>`;out.innerHTML=`<div class="group-metrics">${stat(fibers[0].length,'|ker φ|')}${stat(image,'|im φ|')}</div><p>12 = ${fibers[0].length} × ${image}</p><p>${t('每个非空纤维都有同样多的元素。空纤维提醒我们：同态不一定满射。','Every nonempty fiber has the same size. Empty fibers show that a homomorphism need not be onto.')}</p>`;}
root.querySelector('#hom-n').onchange=e=>{n=+e.target.value;k=mod(k,n);root.querySelector('#hom-k').innerHTML=range(n).map(x=>`<option value="${x}" ${x===k?'selected':''}>${x}</option>`).join('');draw();};root.querySelector('#hom-k').onchange=e=>{k=+e.target.value;draw();};draw();
}
function product(root){
const [stage,out]=shell(root,select('prod-m','m',options([2,3,4,5,6]),4)+select('prod-n','n',options([2,3,4,5,6]),6)+`<button id="prod-step">+ (1,1)</button><button id="prod-reset">${t('重置','Reset')}</button>`);let m=4,n=6,k=0;
function draw(){const len=M.lcm(m,n);stage.innerHTML=`<svg viewBox="0 0 500 360" role="img" aria-label="${t('直积的两个循环','Two cycles of a direct product')}">${range(n).flatMap(y=>range(m).map(x=>{const visited=range(len).some(i=>mod(i,m)===x&&mod(i,n)===y),active=x===k%m&&y===k%n;return `<circle cx="${70+x*350/Math.max(1,m-1)}" cy="${40+y*265/Math.max(1,n-1)}" r="${active?15:9}" fill="${active?'var(--pine)':visited?palette[1]:'var(--line)'}"/><text x="${70+x*350/Math.max(1,m-1)}" y="${64+y*265/Math.max(1,n-1)}" text-anchor="middle" font-size="13" fill="var(--muted)">(${x},${y})</text>`;})).join('')}</svg>`;out.innerHTML=`<div class="group-equation">${k}(1,1)=(${k%m},${k%n})</div><div class="group-metrics">${stat(len,'|(1,1)|')}${stat(m*n,'|Cₘ × Cₙ|')}</div><p>${len===m*n?t('轨迹经过每一个点：直积为循环群。','The walk visits every point: this product is cyclic.'):t('轨迹只覆盖真子群：没有元素能达到群的总阶。','The walk covers a proper subgroup; no element reaches the total group order.')}</p>`;}
for(const id of ['prod-m','prod-n'])root.querySelector('#'+id).onchange=e=>{if(id==='prod-m')m=+e.target.value;else n=+e.target.value;k=0;draw();};root.querySelector('#prod-step').onclick=()=>{k++;draw();};root.querySelector('#prod-reset').onclick=()=>{k=0;draw();};draw();
}
function permutation(root,regular=false){
const examples=[[1,0,2,3,4],[0,2,1,3,4],[1,2,0,3,4],[0,1,3,4,2],[1,2,3,0,4],[1,0,3,2,4]];let a=0,b=1,step=0;
const [stage,out]=shell(root,regular?select('perm-a','g ∈ ℤ₅',options(range(5)),1):select('perm-a','σ',examples.map((p,i)=>[i,M.cycleLabel(p)]),a)+select('perm-b','τ',examples.map((p,i)=>[i,M.cycleLabel(p)]),b));
function draw(){const A=regular?range(5).map(x=>mod(x+a,5)):examples[a],B=examples[b],C=regular?A:M.compose(A,B),cycles=M.cycles(C),order=cycles.reduce((o,c)=>M.lcm(o,c.length),1);stage.innerHTML=`<div class="permutation-lines">${range(5).map(x=>`<div><span>${x+1}</span><i>→</i>${regular?'':`<span>${B[x]+1}</span><i>→</i>`}<strong>${C[x]+1}</strong></div>`).join('')}</div>${circle(5,range(5).map(i=>i+1),[],range(5).map(i=>cycles.findIndex(c=>c.includes(i))),C)}`;out.innerHTML=`<div class="group-equation">${regular?'λg':'στ'} = ${M.cycleLabel(C)}</div><div class="group-metrics">${stat(order,t('阶','Order'))}${stat((5-cycles.length)%2?'−1':'+1','sgn')}</div><p>${regular?t('将 ℤ₅ 的 0,1,2,3,4 依次标为 1,2,3,4,5。这里的箭头给出左乘（加法）置换。','The elements 0,…,4 of ℤ₅ are labeled 1,…,5 here. Arrows give the left-translation permutation.'):t('每行依次读作 x → τ(x) → σ(τ(x))。同色点属于同一个轮换。','Read each row as x → τ(x) → σ(τ(x)). Equal colors identify one cycle.')}</p>`;}
root.querySelector('#perm-a').onchange=e=>{a=+e.target.value;draw();};if(regular){a=1;}else root.querySelector('#perm-b').onchange=e=>{b=+e.target.value;draw();};draw();
}
function polygon(root,action=false){
let n=4,g=0,base=0,kind='vertices',G=M.dihedral(n);const [stage,out]=shell(root,(action?select('poly-set',t('作用集合','Acted-on set'),[['vertices',t('四个顶点','Four vertices')],['diagonals',t('两条对角线','Two diagonals')]],kind):select('poly-n','n',options([3,4,5,6]),n))+`<button id="poly-r">r</button><button id="poly-s">s</button><button id="poly-reset">e</button>`);
const act=(a,x)=>kind==='diagonals'?mod(G.act(a,x),2):G.act(a,x);
function draw(){const size=kind==='diagonals'?2:n,orbit=[...new Set(G.elements.map(a=>act(a,base)))],stab=G.elements.filter(a=>act(a,base)===base),pts=range(n).map(i=>[240+150*Math.cos(-2*Math.PI*i/n-Math.PI/2),190+150*Math.sin(-2*Math.PI*i/n-Math.PI/2)]);stage.innerHTML=`<svg viewBox="0 0 480 390" role="img" aria-label="${t('正多边形的带标号顶点','Labeled vertices of a regular polygon')}"><polygon points="${pts.map(p=>p.join(',')).join(' ')}" fill="none" stroke="var(--line)" stroke-width="2"/>${kind==='diagonals'?range(2).map(i=>`<line x1="${pts[i][0]}" y1="${pts[i][1]}" x2="${pts[i+2][0]}" y2="${pts[i+2][1]}" stroke="${palette[i]}" stroke-width="${i===act(g,base)?5:2}"/>`).join(''):''}${range(n).map(i=>{const p=pts[G.act(g,i)];return `<g><circle cx="${p[0]}" cy="${p[1]}" r="22" fill="${palette[i%6]}"/><text x="${p[0]}" y="${p[1]+6}" text-anchor="middle" font-size="19" fill="white">${i+1}</text></g>`;}).join('')}</svg><div class="group-elements">${buttons(G,[g])}</div>`;out.innerHTML=`<div class="group-equation">g=${G.label(g)}</div><p>${t('顶点数字记录原来位于该顶点的标号。点击 r 或 s，把新变换复合在左侧。','Labels track the original vertices. Clicking r or s composes the new transformation on the left.')}</p>${action?`<div class="controls">${select('poly-base',t('基点','Base point'),options(range(size).map(i=>i+1)),base+1)}</div><p>G·${base+1}={${orbit.map(x=>x+1).join(', ')}}<br>G<sub>${base+1}</sub>=${setLabel(G,stab)}</p><div class="group-equation">${G.elements.length} = ${orbit.length} × ${stab.length}</div>`:`<p>r<sup>${n}</sup>=s²=e,　srs=r⁻¹</p>`}`;out.querySelector('#poly-base')?.addEventListener('change',e=>{base=+e.target.value-1;draw();});}
root.querySelector('#poly-r').onclick=()=>{g=G.mul(1,g);draw();};root.querySelector('#poly-s').onclick=()=>{g=G.mul(n,g);draw();};root.querySelector('#poly-reset').onclick=()=>{g=0;draw();};root.querySelector('#poly-n')?.addEventListener('change',e=>{n=+e.target.value;G=M.dihedral(n);g=0;draw();});root.querySelector('#poly-set')?.addEventListener('change',e=>{kind=e.target.value;base=0;g=0;draw();});stage.onclick=e=>{const b=e.target.closest('[data-element]');if(b){g=+b.dataset.element;draw();}};draw();
}
function conjugation(root){const G=M.dihedral(3);let x=1;const [stage,out]=shell(root,select('conj-x','x',G.elements.map(x=>[x,G.label(x)]),x));function draw(){const cls=[...new Set(G.elements.map(g=>M.conjugate(G,g,x)))],centralizer=G.elements.filter(g=>G.mul(g,x)===G.mul(x,g));stage.innerHTML=circle(6,G.elements.map(G.label),cls)+`<div class="group-elements">${G.elements.map(g=>`<span>${G.label(g)} · ${G.label(x)} · ${G.label(g)}⁻¹ = ${G.label(M.conjugate(G,g,x))}</span>`).join('')}</div>`;out.innerHTML=`<p>Cl(${G.label(x)})=${setLabel(G,cls)}<br>C<sub>G</sub>(${G.label(x)})=${setLabel(G,centralizer)}</p><div class="group-equation">6 = ${cls.length} × ${centralizer.length}</div><p>${t('全部共轭类给出类方程：','The conjugacy classes give:')} 6 = 1 + 2 + 3</p>`;}root.querySelector('#conj-x').onchange=e=>{x=+e.target.value;draw();};draw();}
function burnside(root){let reflections=true,mask=3;const [stage,out]=shell(root,select('burn-group',t('允许的对称','Allowed symmetries'),[['d4','D₄'],['c4','C₄']],'d4'));
const mini=m=>`<svg viewBox="0 0 80 80" aria-hidden="true"><path d="M15 15H65V65H15Z" stroke="var(--line)" fill="none"/>${[[15,15],[65,15],[65,65],[15,65]].map((p,i)=>`<circle cx="${p[0]}" cy="${p[1]}" r="8" fill="${m>>i&1?'var(--pine)':'var(--paper,#f7f3e9)'}" stroke="var(--pine)"/>`).join('')}</svg>`;
function draw(){const b=M.burnside(reflections),orbit=b.orbits.find(o=>o.includes(mask));stage.innerHTML=`<p>${t('点击任一顶点切换颜色','Click a vertex to change its color')}</p><div class="coloring-controls">${range(4).map(i=>`<button data-color="${i}" aria-label="${t('切换顶点','Toggle vertex')} ${i+1}" aria-pressed="${!!(mask>>i&1)}">${i+1}</button>`).join('')}</div><div class="coloring-orbit">${orbit.map(m=>mini(m)).join('')}</div><p>${t('这个着色的轨道含','This coloring has')} ${orbit.length} ${t('种带标号着色','labeled colorings in its orbit')}</p><div class="group-table-wrap"><table class="group-table"><thead><tr><th>g</th>${b.els.map(g=>`<th>${b.G.label(g)}</th>`).join('')}</tr></thead><tbody><tr><th>|Fix(g)|</th>${b.fixed.map(f=>`<td>${f.length}</td>`).join('')}</tr></tbody></table></div>`;out.innerHTML=`<div class="group-equation">(${b.fixed.map(f=>f.length).join('+')}) / ${b.els.length} = ${b.orbits.length}</div><p>${t('每类选一个代表：','One representative per orbit:')}</p><div class="coloring-orbit">${b.orbits.map(o=>mini(o[0])).join('')}</div>`;}
root.querySelector('#burn-group').onchange=e=>{reflections=e.target.value==='d4';draw();};stage.onclick=e=>{const b=e.target.closest('[data-color]');if(b){mask^=1<<+b.dataset.color;draw();}};draw();}
function sylow(root,config){let n=config.order||12,p=config.prime||3;const ns=[6,8,12,15,18,20,21,24,28,30,36,40,42,56,60,168];const [stage,out]=shell(root,select('syl-n','|G|',options(ns),n)+select('syl-p','p',options(M.primes(n)),p));function draw(){const s=M.sylow(n,p);stage.innerHTML=`<div class="group-equation">${n} = ${p}<sup>${s.a}</sup> × ${s.m}</div><p>${t('先列 m 的正因子，再保留模 p 余 1 的项：','List divisors of m, then keep those congruent to 1 modulo p:')}</p><div class="sylow-candidates">${M.divisors(s.m).map(d=>`<div class="${s.candidates.includes(d)?'survives':'excluded'}"><strong>${d}</strong><small>${d} mod ${p} = ${d%p}</small></div>`).join('')}</div>`;out.innerHTML=`<div class="group-equation">n<sub>${p}</sub> ∈ {${s.candidates.join(', ')}}</div><p>${s.candidates.length===1?t('只剩 1：西罗子群唯一，所以正规。','Only 1 remains: the Sylow subgroup is unique and normal.'):t('还有多个候选：需要更多群作用或元素计数，不能直接断言正规。','Several candidates remain. More action or counting arguments are needed.')}</p><small>${t('候选满足必要条件，不表示每个候选都可实现。','Necessary conditions only; candidates are not guaranteed to occur.')}</small>`;}
root.querySelector('#syl-n').onchange=e=>{n=+e.target.value;p=M.primes(n)[0];root.querySelector('#syl-p').innerHTML=M.primes(n).map(q=>`<option>${q}</option>`).join('');draw();};root.querySelector('#syl-p').onchange=e=>{p=+e.target.value;draw();};draw();}
function words(root){let word='abBA',step=0;const [stage,out]=shell(root,`<label>${t('词（a,b 的逆用 A,B）','Word (A,B denote inverses)')}<input id="word-input" value="abBA" maxlength="48" autocomplete="off" spellcheck="false"></label><button id="word-step">${t('读入一个字母','Read one letter')}</button><button id="word-all">${t('全部约化','Reduce all')}</button><button id="word-reset">${t('重置','Reset')}</button>`);const pretty=w=>w?w.split('').map(c=>c===c.toUpperCase()?c.toLowerCase()+'⁻¹':c).join(' '):'e';function draw(){const r=M.reduceWord(word),current=step?r.steps[step-1].word:'';stage.innerHTML=`<div class="word-stream">${word.split('').map((c,i)=>`<span class="${i<step?'read':''}">${pretty(c)}</span>`).join('')}</div><div class="group-equation word-stack">${pretty(current)}</div><p>${t('已读','Read')} ${step} / ${word.length}</p>`;out.innerHTML=`<p>${step?(r.steps[step-1].cancel?t('新字母与栈顶互逆：消去。','The new letter cancels the stack top.'):t('没有相邻逆符号：压入栈。','No adjacent inverse: push the letter.')):t('从空词开始，逐个读入。','Start with the empty word.')}</p>${step===word.length?`<p>${t('最终约化词：','Final reduced word: ')}${pretty(r.word)}</p>`:''}`;}
root.querySelector('#word-input').oninput=e=>{word=e.target.value.replace(/[^abAB]/g,'');e.target.value=word;step=0;draw();};root.querySelector('#word-step').onclick=()=>{step=Math.min(step+1,word.length);draw();};root.querySelector('#word-all').onclick=()=>{step=word.length;draw();};root.querySelector('#word-reset').onclick=()=>{step=0;draw();};draw();}
function isomorphism(root,orders=false){const [stage,out]=shell(root,orders?'':select('iso-k','[k] ∈ ℤ₄',options(range(4)),1));let k=1;function draw(){if(orders){stage.innerHTML=`<div class="group-table-wrap"><table class="group-table"><thead><tr><th>${t('群','Group')}</th><th>${t('阶 1','Order 1')}</th><th>${t('阶 2','Order 2')}</th><th>${t('阶 4','Order 4')}</th></tr></thead><tbody><tr><th>C₄</th><td>1</td><td>1</td><td>2</td></tr><tr><th>C₂×C₂</th><td>1</td><td>3</td><td>0</td></tr></tbody></table></div>`;out.innerHTML=`<p>${t('表中数字是相应阶元素的个数。任何重新命名都无法改变这两行的差异。','Entries count elements of each order. Renaming cannot change the mismatch.')}</p>`;}else{const roots=['1','i','−1','−i'];stage.innerHTML=`<div class="iso-pair">${circle(4,range(4),[k])}<span>↦</span>${circle(4,roots,[k])}</div>`;out.innerHTML=`<div class="group-equation">[${k}] ↦ i<sup>${k}</sup> = ${roots[k]}</div><p>${t('左边用加法，右边用乘法：把指数相加正好对应把复数相乘。','Addition on the left corresponds to multiplication on the right through exponent addition.')}</p>`;}}root.querySelector('#iso-k')?.addEventListener('change',e=>{k=+e.target.value;draw();});draw();}
window.GroupVisuals={render(root,config){const kind=config.kind;switch(kind){case'subgroup':subgroup(root);break;case'generated':subgroup(root,true);break;case'cyclic':cyclic(root);break;case'lattice':cyclic(root,true);break;case'cosets':cosets(root);break;case'normal':cosets(root,true);break;case'quotient':quotient(root);break;case'homomorphism':homomorphism(root);break;case'product':product(root);break;case'permutation':permutation(root);break;case'regular':permutation(root,true);break;case'polygon':polygon(root);break;case'action':polygon(root,true);break;case'conjugation':conjugation(root);break;case'burnside':burnside(root);break;case'sylow':sylow(root,config);break;case'words':words(root);break;case'isomorphism':isomorphism(root);break;case'orders':isomorphism(root,true);break;default:throw Error('Unknown visual '+kind);}}};
})();
