import Mathlib.Algebra.Polynomial.Coeff
import Mathlib.Algebra.Polynomial.Div
import Mathlib.Algebra.Polynomial.Taylor
import Mathlib.RingTheory.Ideal.Maps
import OAI.AlgebraicGeometry.PlaneCurves.PolynomialJets

namespace OAI

/-!
# Local coefficient ideals and ideal-power order
-/

section

open Polynomial
open scoped BigOperators
namespace Nagata.W18

/-- Coefficients of a member of `(g,W)^m` have the expected divisibility. -/
theorem coefficient_dvd_of_coordinate_ideal_power {R : Type*} [CommRing R]
    (g : R) (m : ℕ) (H : Polynomial R)
    (hH : H ∈ (Ideal.span ({C g, X} : Set (Polynomial R))) ^ m) :
    ∀ J : ℕ, g ^ (m - J) ∣ H.coeff J := by
  classical
  rw [Nagata.Workers.W30.pair_ideal_pow] at hH
  induction hH using Submodule.span_induction with
  | mem z hz =>
    obtain ⟨k, hk, rfl⟩ := hz
    intro J
    rw [← C_pow, coeff_C_mul_X_pow]
    by_cases hJ : J = k
    · subst J
      simp
    · simp [hJ]
  | zero => intro J; simp
  | add p q hp hq ihp ihq =>
    intro J
    rw [coeff_add]
    exact dvd_add (ihp J) (ihq J)
  | smul p q hq ih =>
    intro J
    change g ^ (m - J) ∣ (p * q).coeff J
    rw [coeff_mul]
    apply Finset.dvd_sum
    intro ij hij
    have hsum := Finset.mem_antidiagonal.mp hij
    have hle : m - J ≤ m - ij.2 := by omega
    exact dvd_mul_of_dvd_right ((pow_dvd_pow g hle).trans (ih ij.2)) _

end Nagata.W18

end

section

/-!
# Local top-coefficient and fiber multiplicity

The local algebra in `prop:squares` is performed on actual nested polynomials
`K[U][W]`. Order at `(a,c)` means membership in the power of the genuine
point ideal generated by `U-a` and `W-c`. All subtraction of orders is natural
truncated subtraction.
-/

noncomputable section
open Polynomial
open scoped BigOperators

namespace Nagata.W18

/-- The actual maximal point ideal in the nested bivariate polynomial ring. -/
def nestedPointIdeal {K : Type*} [CommRing K] (a c : K) :
    Ideal (Polynomial (Polynomial K)) :=
  Ideal.span {C (X - C a), X - C (C c)}

/-- Translating the outer variable sends `(U-a,W-c)` to `(U-a,W)`. -/
theorem map_nestedPointIdeal_taylor {K : Type*} [CommRing K] (a c : K) :
    (nestedPointIdeal a c).map (taylorAlgHom (C c)).toRingHom =
      Ideal.span ({C (X - C a), X} : Set (Polynomial (Polynomial K))) := by
  rw [nestedPointIdeal, Ideal.map_span]
  simp only [Set.image_insert_eq, Set.image_singleton]
  change Ideal.span {taylor (C c) (C (X - C a)), taylor (C c) (X - C (C c))} = _
  simp only [taylor_C, map_sub, taylor_X, add_sub_cancel_right]

/-- Translation preserves the coefficient at any index at least the degree. -/
theorem top_coefficient_taylor {R : Type*} [CommRing R]
    (H : Polynomial R) (r : R) (J : ℕ) (hJ : H.natDegree ≤ J) :
    (taylor r H).coeff J = H.coeff J := by
  by_cases heq : H.natDegree = J
  · rw [← heq, coeff_taylor_natDegree]
    rfl
  · have hlt : H.natDegree < J := lt_of_le_of_ne hJ heq
    rw [coeff_eq_zero_of_natDegree_lt hlt,
      coeff_eq_zero_of_natDegree_lt (by simpa only [natDegree_taylor] using hlt)]

/-- Surface order at an arbitrary displacement forces base order `m-J` of
the highest possible fiber coefficient. -/
theorem top_coefficient_base_divisibility {K : Type*} [CommRing K]
    (H : Polynomial (Polynomial K)) (a c : K) (m J : ℕ)
    (hJ : H.natDegree ≤ J) (hH : H ∈ (nestedPointIdeal a c) ^ m) :
    (X - C a) ^ (m - J) ∣ H.coeff J := by
  have h := Ideal.mem_map_of_mem (taylorAlgHom (C c)).toRingHom hH
  rw [Ideal.map_pow, map_nestedPointIdeal_taylor] at h
  have hd := coefficient_dvd_of_coordinate_ideal_power (X - C a) m
    (taylor (C c) H) h J
  rwa [top_coefficient_taylor H (C c) J hJ] at hd

/-- Restriction to the marked base fiber is coefficientwise evaluation `U=a`. -/
def fiberRestriction {K : Type*} [CommRing K] (a : K) :
    Polynomial (Polynomial K) →+* Polynomial K :=
  mapRingHom (evalRingHom a)

/-- Restriction evaluates each base coefficient at the marked point. -/
theorem fiberRestriction_coeff {K : Type*} [CommRing K]
    (H : Polynomial (Polynomial K)) (a : K) (j : ℕ) :
    (fiberRestriction a H).coeff j = (H.coeff j).eval a :=
  Polynomial.coeff_map (evalRingHom a) j

/-- Restriction cannot increase the degree in the fiber variable. -/
theorem fiberRestriction_natDegree_le {K : Type*} [CommRing K]
    (H : Polynomial (Polynomial K)) (a : K) :
    (fiberRestriction a H).natDegree ≤ H.natDegree :=
  Polynomial.natDegree_map_le

/-- A surviving top coefficient is the leading coefficient on the fiber. -/
theorem fiberRestriction_leadingCoeff {K : Type*} [CommRing K]
    (H : Polynomial (Polynomial K)) (a : K) (J : ℕ)
    (hJ : H.natDegree ≤ J) (hne : (H.coeff J).eval a ≠ 0) :
    (fiberRestriction a H).leadingCoeff = (H.coeff J).eval a := by
  have hdeg : (fiberRestriction a H).natDegree = J :=
    natDegree_eq_of_le_of_coeff_ne_zero ((fiberRestriction_natDegree_le H a).trans hJ)
      (by rwa [fiberRestriction_coeff])
  rw [leadingCoeff, hdeg, fiberRestriction_coeff]

/-- The point ideal maps to the principal fiber point ideal `(W-c)`. -/
theorem map_nestedPointIdeal_fiber {K : Type*} [CommRing K] (a c : K) :
    (nestedPointIdeal a c).map (fiberRestriction a) =
      Ideal.span ({X - C c} : Set (Polynomial K)) := by
  rw [nestedPointIdeal, Ideal.map_span]
  simp [fiberRestriction, Set.image_insert_eq, Set.image_singleton,
    Polynomial.map_C, Polynomial.map_X, Polynomial.map_sub, eval_X, eval_C]

/-- Surface ideal-power order restricts to fiber root divisibility, including
when the entire fiber restriction is zero. -/
theorem fiber_power_divides_of_surface_order {K : Type*} [CommRing K]
    (H : Polynomial (Polynomial K)) (a c : K) (m : ℕ)
    (hH : H ∈ (nestedPointIdeal a c) ^ m) :
    (X - C c) ^ m ∣ fiberRestriction a H := by
  have h := Ideal.mem_map_of_mem (fiberRestriction a) hH
  rw [Ideal.map_pow, map_nestedPointIdeal_fiber, Ideal.span_singleton_pow] at h
  exact Ideal.mem_span_singleton.mp h

/-- For nonzero fiber restrictions, the same condition is the actual ordinary
root-multiplicity lower bound. -/
theorem fiber_rootMultiplicity_ge {K : Type*} [CommRing K] [IsDomain K]
    (H : Polynomial (Polynomial K)) (a c : K) (m : ℕ)
    (hH : H ∈ (nestedPointIdeal a c) ^ m) (hne : fiberRestriction a H ≠ 0) :
    m ≤ (fiberRestriction a H).rootMultiplicity c := by
  exact (le_rootMultiplicity_iff hne).mpr
    (fiber_power_divides_of_surface_order H a c m hH)

end Nagata.W18

end
end

end OAI
