import OAI.AlgebraicGeometry.PlaneCurves.HomogeneousIdeals
import OAI.AlgebraicGeometry.PlaneCurves.LineIntersections
import OAI.AlgebraicGeometry.PlaneCurves.LineNormalData
import OAI.AlgebraicGeometry.PlaneCurves.LowDegree

namespace OAI

/-!
# Degree, prime divisors, and universality of cubic equations; Regularity of the image of the cubic embedding
-/

section

/-! A nonunit divisor of a prime equation is itself an equation. This supplies
an algebraic degree exclusion without assuming projective image algebraicity. -/
namespace Nagata.W03
open Nagata.Workers.W25

/-- Vanishing at one actual vector makes a polynomial a nonunit. -/
theorem polynomial_not_isUnit_of_eval_zero
    (L : MvPolynomial (Fin 3) ℂ) (v : Fin 3 → ℂ)
    (hv : MvPolynomial.eval v L = 0) : ¬ IsUnit L := by
  intro hL
  exact (hL.map (MvPolynomial.eval v)).ne_zero hv

/-- A nonunit divisor of a prime relation vanishes on the whole parameter domain. -/
theorem prime_relation_divisor_mem
    (s : Fin 3 → ℂ → ℂ) (G L : MvPolynomial (Fin 3) ℂ)
    (hG : Prime G) (hrel : G ∈ polynomialRelationIdeal s)
    (hL : ¬ IsUnit L) (hdiv : L ∣ G) : L ∈ polynomialRelationIdeal s := by
  have hassoc : Associated G L := (hG.irreducible.dvd_iff.mp hdiv).resolve_left hL
  obtain ⟨Q, hQ⟩ := hassoc.dvd
  rw [hQ]
  exact Ideal.mul_mem_right _ _ hrel

/-- A prime relation cannot be divisible by a polynomial which has one zero
but also has a witnessed nonzero value on the parameterized image. -/
theorem prime_relation_not_dvd_of_zero_and_nonzero
    (s : Fin 3 → ℂ → ℂ) (G L : MvPolynomial (Fin 3) ℂ)
    (hG : Prime G) (hrel : G ∈ polynomialRelationIdeal s)
    (v : Fin 3 → ℂ) (hv : MvPolynomial.eval v L = 0)
    (hw : ∃ z : ℂ, z ≠ 0 ∧ MvPolynomial.eval (fun i => s i z) L ≠ 0) :
    ¬ L ∣ G := by
  intro hdiv
  have hmem := prime_relation_divisor_mem s G L hG hrel
    (polynomial_not_isUnit_of_eval_zero L v hv) hdiv
  obtain ⟨z, hz, hwz⟩ := hw
  exact hwz ((mem_polynomialRelationIdeal s L).mp hmem z hz)

end Nagata.W03

end

section

noncomputable section
namespace Nagata.W03
open Nagata.Workers.W25 Nagata.W07 Nagata.W08 Nagata.W21 Nagata.W16
open Nagata.ProjectiveGeometry

/-- Every prescribed image point lies on a three-point line that cannot divide
a prime equation of the actual section map. -/
theorem actual_prime_relation_threePointLine {τ : ℝ}
    (hτ : 0 < τ) (hτone : τ < 1) {γ : ℂ} (hγ : γ ≠ 0)
    (G : MvPolynomial (Fin 3) ℂ) (hG : Prime G)
    (hhom : G.IsHomogeneous G.totalDegree)
    (hrel : G ∈ polynomialRelationIdeal
      (fun i => (actualCubicBasis hτ hτone hγ i).val))
    (q : TorusPoint (cubicPeriod hτ)) :
    ∃ (L : MvPolynomial (Fin 3) ℂ) (p : Fin 3 → PlanePoint),
      L ≠ 0 ∧ L.IsHomogeneous 1 ∧ Function.Injective p ∧
      p 0 = actualCubicMap hτ hτone hγ q ∧
      (∀ i, MvPolynomial.eval (p i).rep L = 0) ∧
      (∀ i, MvPolynomial.eval (p i).rep G = 0) ∧ ¬ L ∣ G := by
  obtain ⟨L, p, hL, hLhom, hinj, hp0, himg, hLzero, hw⟩ :=
    exists_threePointLine_through_image hτ hτone hγ q
  refine ⟨L, p, hL, hLhom, hinj, hp0, hLzero, ?_, ?_⟩
  · intro i
    obtain ⟨qi, hqi⟩ := himg i
    rw [← hqi]
    exact cubicTorusMap_on_curve (cubicPeriod hτ) (actualCubicBasis hτ hτone hγ)
      (fun _ hz => actualCubic_eval_kernel_dimension hτ hτone hγ hz)
      ⟨G, hhom, hG.ne_zero⟩ ((mem_polynomialRelationIdeal _ _).mp hrel) qi
  · exact prime_relation_not_dvd_of_zero_and_nonzero _ G L hG hrel
      (p 0).rep (hLzero 0) hw

end Nagata.W03

end
end

section

noncomputable section
namespace Nagata.W03
open Nagata.Workers.W25 Nagata.W07 Nagata.W08 Nagata.W21

/-- A prime homogeneous equation of the actual complete section map, with
total degree at most three, has total degree exactly three. -/
theorem actual_prime_relation_totalDegree_eq_three {τ : ℝ}
    (hτ : 0 < τ) (hτone : τ < 1) {γ : ℂ} (hγ : γ ≠ 0)
    (G : MvPolynomial (Fin 3) ℂ) (hG : Prime G)
    (hhom : G.IsHomogeneous G.totalDegree) (hle : G.totalDegree ≤ 3)
    (hrel : G ∈ polynomialRelationIdeal
      (fun i => (actualCubicBasis hτ hτone hγ i).val)) :
    G.totalDegree = 3 := by
  by_contra hne
  have hsmall : G.totalDegree ≤ 2 := by omega
  obtain ⟨L, p, hL, hLhom, hinj, _, hLzero, hGzero, hnotdiv⟩ :=
    actual_prime_relation_threePointLine hτ hτone hγ G hG hhom hrel
      (torusPointMk (cubicPeriod hτ) 1)
  exact hnotdiv (Nagata.Workers.W14.homogeneous_line_dvd_of_three_projective_zeros
    L G hLhom hL hhom hsmall p hinj hLzero hGzero)

/-- The pointwise ideal of all polynomial relations of the actual section map
is generated by a genuine prime homogeneous cubic of exact total degree three. -/
theorem exists_actual_prime_cubic_generator {τ : ℝ}
    (hτ : 0 < τ) (hτone : τ < 1) {γ : ℂ} (hγ : γ ≠ 0) :
    ∃ G : MvPolynomial (Fin 3) ℂ,
      Prime G ∧ G.IsHomogeneous 3 ∧ G.totalDegree = 3 ∧
      polynomialRelationIdeal
        (fun i => (actualCubicBasis hτ hτone hγ i).val) = Ideal.span {G} ∧
      (∀ z : ℂ, z ≠ 0 →
        MvPolynomial.eval (cubicEvaluationVector (actualCubicBasis hτ hτone hγ) z) G = 0) ∧
      (∀ P : MvPolynomial (Fin 3) ℂ, ¬ G ∣ P →
        ∃ z : ℂ, z ≠ 0 ∧
          MvPolynomial.eval (cubicEvaluationVector (actualCubicBasis hτ hτone hγ) z) P ≠ 0) := by
  obtain ⟨G, hG, hhom, _, hle, hI, hnoncancel⟩ :=
    exists_actual_relation_generator_with_noncancellation hτ hτone hγ
      (actualCubicBasis hτ hτone hγ)
  have hrel : G ∈ polynomialRelationIdeal
      (fun i => (actualCubicBasis hτ hτone hγ i).val) := by
    rw [hI]
    exact Ideal.subset_span (Set.mem_singleton G)
  have hdegree := actual_prime_relation_totalDegree_eq_three hτ hτone hγ G hG hhom hle hrel
  have hhom3 : G.IsHomogeneous 3 := by simpa only [hdegree] using hhom
  exact ⟨G, hG, hhom3, hdegree, hI,
    (mem_polynomialRelationIdeal _ _).mp hrel, hnoncancel⟩

end Nagata.W03

end
end

section

namespace Nagata.W21
open Nagata.W03 Nagata.Workers.W25 Nagata.W07 Nagata.W08

 theorem actual_prime_cubic_regular_at_image {τ : ℝ}
    (hτ : 0 < τ) (hτone : τ < 1) {γ : ℂ} (hγ : γ ≠ 0)
    (G : MvPolynomial (Fin 3) ℂ) (hG : Prime G)
    (hhom : G.IsHomogeneous 3) (hdegree : G.totalDegree = 3)
    (hrel : G ∈ polynomialRelationIdeal
      (fun i => (actualCubicBasis hτ hτone hγ i).val))
    (q : TorusPoint (cubicPeriod hτ)) :
    ∃ j, MvPolynomial.eval (actualCubicMap hτ hτone hγ q).rep
      (MvPolynomial.pderiv j G) ≠ 0 := by
  by_contra hsing
  push Not at hsing
  obtain ⟨L,p,hL,hLhom,hinj,hp0,hLzero,hGzero,hnotdiv⟩ :=
    actual_prime_relation_threePointLine hτ hτone hγ G hG
      (by simpa only [hdegree] using hhom) hrel q
  apply hnotdiv
  apply Nagata.Workers.W14.homogeneous_line_dvd_cubic_of_singular_three_projective_zeros
    L G hLhom hL hhom p hinj hLzero hGzero
  intro j
  rw [hp0]
  exact hsing j

/-- A genuine prime cubic with the exact relation ideal, noncancellation, and
nonzero homogeneous gradient at every actual section evaluation vector. -/
 theorem exists_actual_regular_prime_cubic {τ : ℝ}
    (hτ : 0 < τ) (hτone : τ < 1) {γ : ℂ} (hγ : γ ≠ 0) :
    ∃ G : MvPolynomial (Fin 3) ℂ,
      Prime G ∧ G.IsHomogeneous 3 ∧ G.totalDegree = 3 ∧
      polynomialRelationIdeal
        (fun i => (actualCubicBasis hτ hτone hγ i).val) = Ideal.span {G} ∧
      (∀ z : ℂ, z ≠ 0 →
        MvPolynomial.eval (cubicEvaluationVector (actualCubicBasis hτ hτone hγ) z) G = 0) ∧
      (∀ z : ℂ, z ≠ 0 → ∃ j,
        MvPolynomial.eval (cubicEvaluationVector (actualCubicBasis hτ hτone hγ) z)
          (MvPolynomial.pderiv j G) ≠ 0) ∧
      (∀ P : MvPolynomial (Fin 3) ℂ, ¬ G ∣ P → ∃ z : ℂ, z ≠ 0 ∧
        MvPolynomial.eval (cubicEvaluationVector (actualCubicBasis hτ hτone hγ) z) P ≠ 0) := by
  obtain ⟨G,hG,hhom,hdegree,hI,hzero,hnoncancel⟩ :=
    exists_actual_prime_cubic_generator hτ hτone hγ
  refine ⟨G,hG,hhom,hdegree,hI,hzero,?_,hnoncancel⟩
  intro z hz
  apply (actualCubicMap_gradient_iff hτ hτone hγ G hhom (Units.mk0 z hz)).mp
  apply actual_prime_cubic_regular_at_image hτ hτone hγ G hG hhom hdegree
  rw [hI]
  exact Ideal.subset_span (Set.mem_singleton G)

end Nagata.W21

end

section

/-!
# Unconditional universal-system exclusion in degree at most 3m
-/
noncomputable section
namespace Nagata.W03.LowDegree
open Polynomial
open Nagata.W04.ReducibleSquare Nagata.W06.LineArrangement

/-- Coefficientwise component restriction agrees with the finite normal sum
when the actual polynomial has no terms above floor(d/3). -/
theorem lineNormalPolynomial_coeff_eq_map
    (F : Polynomial (MvPolynomial (Fin 3) ℂ)) (d i : ℕ)
    (hbound : ∀ j, d / 3 < j → F.coeff j = 0) :
    lineNormalPolynomial F.coeff d i = F.map (lineRestriction (i : ℂ)) := by
  classical
  ext j
  by_cases hj : j ≤ d / 3
  · rw [coeff_lineNormalPolynomial F.coeff d i j hj, Polynomial.coeff_map]
  · have hjgt : d / 3 < j := by omega
    simp [lineNormalPolynomial, Polynomial.finsetSum_coeff, Polynomial.coeff_monomial,
      (show ¬ j < d / 3 + 1 by omega), hbound j hjgt]

/-- For every r≥10, genuine universal equal-multiplicity plane systems have
degree strictly greater than 3m. Both d<3m and d=3m are excluded. No positivity
assumption on d is needed for this stronger statement. -/
theorem cubic_universalSupport_degree_gt (r d m : ℕ) (hr : 10 ≤ r) (hm : 0 < m)
    (hU : Nagata.W13.UniversalSupport r d (fun _ => m)) : 3 * m < d := by
  have hcount : 3 * 3 + (r - 9) = r := by omega
  have hU' : Nagata.W13.UniversalSupport (3 * 3 + (r - 9)) d (fun _ => m) := by
    exact Eq.mpr (congrArg (fun n => Nagata.W13.UniversalSupport n d (fun _ => m)) hcount) hU
  let displacement : Fin (3 * 3 + (r - 9)) → ℂ := fun b =>
    triangleDisplacement ((configurationIndexEquiv 3 (r - 9)).symm b)
  obtain ⟨F, hhom, hweight, hnonzero, horder⟩ :=
    Nagata.Workers.W17.universalSupport_line_normal_polynomial hU'
      (Nagata.Workers.W24.homogeneousLineUnion ℂ 3) 3
      (Nagata.Workers.W24.homogeneousLineUnion_homogeneous 3) (by decide)
      (Nagata.Workers.W14.orderedLineScalar 3 (r - 9) (by decide))
      (fun b => (orderedAffinePoint 3 (r - 9) b).1) displacement
      (Nagata.Workers.W14.orderedLine_graph_injective 3 (r - 9) (by decide))
      (Nagata.Workers.W14.orderedLine_restriction_zero 3 (r - 9) (by decide))
      (Nagata.Workers.W14.orderedLine_partial_ne_zero 3 (r - 9) (by decide))
  have hbound : ∀ j, d / 3 < j → F.coeff j = 0 := by
    intro j hj
    by_contra hne
    have hw := hweight j hne
    omega
  apply degree_gt_three_mul_on_triangle_configuration r d m hr hm F.coeff
    (fun j _ => hhom j)
    (quotientNormalPolynomial_ne_zero_of_map_ne_zero F d
      (Nagata.Workers.W24.homogeneousLineUnion ℂ 3) hbound hnonzero)
  intro p
  rw [lineNormalPolynomial_coeff_eq_map F d (triangleComponent p) hbound]
  have h := horder ((configurationIndexEquiv 3 (r - 9)) p)
  cases p <;>
    simpa [displacement, triangleComponent, triangleBasePoint, triangleDisplacement,
      Nagata.Workers.W14.orderedLineScalar, Nagata.Workers.W14.orderedLineIndex,
      orderedAffinePoint, mixedPoint] using h

/-- The exact positive-degree manuscript formulation. -/
theorem cubic_low_degree (r d m : ℕ) (hr : 10 ≤ r) (_hd : 0 < d) (hm : 0 < m)
    (hU : Nagata.W13.UniversalSupport r d (fun _ => m)) : 3 * m < d :=
  cubic_universalSupport_degree_gt r d m hr hm hU

end Nagata.W03.LowDegree

end
end

end OAI
