module
public import Mathlib.Algebra.DirectSum.Module
public import Mathlib.RingTheory.Finiteness.Basic

@[expose] public section
namespace Negativity
open scoped DirectSum
universe u v
noncomputable section

/-- A finite module whose elements are genuinely graded is generated by
homogeneous elements of bounded degree. This uses the actual finite supports
of a finite generating set; no degree-bound premise is assumed. -/
theorem actual_finite_graded_module_generator_bound
    {R : Type u} [Semiring R] {M : ℕ → Type v} [∀ n, AddCommMonoid (M n)]
    [Module R (⨁ n, M n)] [Module.Finite R (⨁ n, M n)] :
    ∃ c : ℕ, Submodule.span R
      {x : ⨁ n, M n | ∃ d : ℕ, d ≤ c ∧ ∃ m : M d, x = DirectSum.of M d m} = ⊤ := by
  classical
  obtain ⟨s, hs⟩ := (Module.Finite.fg_top (R := R) (M := ⨁ n, M n))
  let c : ℕ := s.sup fun x => x.support.sup id
  refine ⟨c, eq_top_iff.mpr ?_⟩
  rw [← hs, Submodule.span_le]
  intro x hx
  change x ∈ s at hx
  rw [← DirectSum.sum_support_of x]
  apply Submodule.sum_mem
  intro d hd
  apply Submodule.subset_span
  refine ⟨d, ?_, x d, rfl⟩
  exact (Finset.le_sup (f := id) hd).trans
    (Finset.le_sup (f := fun x : ⨁ n, M n => x.support.sup id) hx)

#print axioms actual_finite_graded_module_generator_bound
end
end Negativity
