(() => {
  "use strict";

  const $ = (selector) => document.querySelector(selector);
  const $$ = (selector) => [...document.querySelectorAll(selector)];
  const canvas = $("#gameCanvas");
  const ctx = canvas.getContext("2d");
  const W = 720;
  const H = 1280;
  const CORE_Y = 1120;
  const TAU = Math.PI * 2;
  const ACCOUNT_KEY = "endless-defense-accounts-v1";
  const SETTINGS_KEY = "endless-defense-settings-v1";
  const SAVE_VERSION = 2;
  const COLORS = { cyan:"#5ce6ff", gold:"#ffd16f", danger:"#ff5e78", green:"#64efb5", violet:"#a98aff", bullet:"#ffd16f", laser:"#ff5f7c", missile:"#ff934f", frost:"#61ddff", arc:"#ad8cff" };

  const TURRET_DEFS = {
    bullet: { name:"子弹主炮", glyph:"●", x:360, y:1082, color:COLORS.bullet, damage:15, cooldown:.48, range:720 },
    laser: { name:"激光炮", glyph:"╱", x:120, y:1060, color:COLORS.laser, damage:6, cooldown:.23, range:690 },
    missile: { name:"导弹炮", glyph:"▲", x:600, y:1060, color:COLORS.missile, damage:46, cooldown:1.7, range:760 },
    frost: { name:"冰霜炮", glyph:"✣", x:245, y:1110, color:COLORS.frost, damage:9, cooldown:1.18, range:210 },
    arc: { name:"电弧炮", glyph:"ϟ", x:475, y:1110, color:COLORS.arc, damage:16, cooldown:.88, range:650 }
  };

  const ENEMY_TYPES = {
    swarm: { name:"游群", hp:.72, speed:1.08, radius:11, damage:4, coin:3, score:12, color:"#eb698e" },
    runner: { name:"疾行体", hp:.56, speed:1.72, radius:10, damage:5, coin:4, score:18, color:"#ffad66" },
    tank: { name:"重甲体", hp:3.15, speed:.57, radius:20, damage:14, coin:9, score:44, color:"#a17be8" },
    shield: { name:"护罩体", hp:1.75, speed:.78, radius:16, damage:9, coin:7, score:32, color:"#65aef6", shield:.55 },
    shooter: { name:"星潮炮手", hp:2.35, speed:.72, radius:17, damage:5, coin:11, score:58, color:"#ff6677", ranged:true },
    bounty: { name:"限时猎物", hp:2.1, speed:.95, radius:18, damage:11, coin:14, score:78, color:"#ffd16f", bounty:true },
    boss: { name:"星潮主宰", hp:29, speed:.39, radius:38, damage:38, coin:60, score:720, color:"#ff4f70", boss:true }
  };

  const CARD_COLORS = { "弹道":COLORS.bullet, "激光":COLORS.laser, "导弹":COLORS.missile, "冰霜":COLORS.frost, "电弧":COLORS.arc, "生存":COLORS.green, "功能":COLORS.violet, "经济":COLORS.gold };
  const CARDS = [
    { id:"caliber", name:"增压弹芯", glyph:"◆", rarity:"基础", tags:["弹道"], max:5, desc:(r)=>`子弹炮伤害提高 ${25+r*4}%。`, note:"稳定放大初始炮塔与穿透收益。" },
    { id:"rapid", name:"高速供弹", glyph:"»", rarity:"基础", tags:["弹道"], max:5, desc:(r)=>`子弹炮射速提高 ${18+r*3}%。`, note:"提高暴击、易伤和吸血的触发频率。" },
    { id:"pierce", name:"相位穿透", glyph:"→", rarity:"进阶", tags:["弹道"], max:3, minWave:2, desc:(r)=>`子弹额外穿透 ${1+r} 个敌人。`, note:"纵向敌群越密集，收益越高。" },
    { id:"split_round", name:"分裂弹头", glyph:"Y", rarity:"稀有", tags:["弹道"], max:2, req:["pierce"], minWave:4, desc:(r)=>`子弹命中后有 ${28+r*12}% 概率分裂攻击附近目标。`, note:"让单体弹道补足横向覆盖。" },
    { id:"crit_training", name:"弱点校准", glyph:"◎", rarity:"进阶", tags:["弹道"], max:4, minWave:2, desc:(r)=>`全炮塔暴击率提高 ${6+r*2}%。`, note:"与易伤和金币暴击升级相乘。" },
    { id:"expose", name:"破甲标记", glyph:"◇", rarity:"进阶", tags:["弹道","功能"], max:3, minWave:3, desc:(r)=>`命中有 ${9+r*3}% 概率施加易伤，使目标多承受 18% 伤害。`, note:"易伤最多叠加 5 层。" },
    { id:"execution", name:"处决窗口", glyph:"⌁", rarity:"稀有", tags:["弹道","功能"], max:2, req:["expose"], minWave:5, desc:(r)=>`易伤目标低于 ${12+r*6}% 生命时直接处决（首领效果减半）。`, note:"避免高压波次残血推进。" },
    { id:"frost_ammo", name:"低温弹药", glyph:"✣", rarity:"进阶", tags:["弹道","冰霜"], max:3, minWave:3, desc:(r)=>`子弹有 ${18+r*7}% 概率减速目标 ${24+r*5}%。`, note:"在尚未获得冰霜炮前提供点状控制。" },

    { id:"turret_laser", name:"部署：激光炮", glyph:"╱", rarity:"炮塔", tags:["激光"], max:1, minWave:1, unlock:"laser", desc:()=>"在左侧部署持续高频激光炮。", note:"擅长叠加易伤并处理高生命目标。" },
    { id:"laser_power", name:"聚焦透镜", glyph:"◉", rarity:"进阶", tags:["激光"], max:4, req:["turret_laser"], desc:(r)=>`激光伤害提高 ${28+r*7}%。`, note:"直接提升激光炮持续输出。" },
    { id:"laser_melt", name:"熔甲光束", glyph:"⌇", rarity:"稀有", tags:["激光","功能"], max:3, req:["turret_laser"], minWave:3, desc:(r)=>`激光每 ${5-r} 次命中叠加一层易伤。`, note:"让激光成为稳定的易伤发生器。" },

    { id:"turret_missile", name:"部署：导弹炮", glyph:"▲", rarity:"炮塔", tags:["导弹"], max:1, minWave:1, unlock:"missile", desc:()=>"在右侧部署范围爆炸导弹炮。", note:"慢速重击，专门清理密集敌群。" },
    { id:"missile_cluster", name:"子母弹舱", glyph:"✦", rarity:"进阶", tags:["导弹"], max:3, req:["turret_missile"], desc:(r)=>`导弹爆炸半径提高 ${25+r*10}%，伤害提高 ${16+r*5}%。`, note:"强化范围覆盖和金币收割。" },
    { id:"missile_burn", name:"燃烧战斗部", glyph:"◈", rarity:"稀有", tags:["导弹"], max:3, req:["turret_missile"], minWave:3, desc:(r)=>`导弹使目标燃烧 ${3+r*.5} 秒。`, note:"持续伤害能稳定触发吸血。" },

    { id:"turret_frost", name:"部署：冰霜炮", glyph:"✣", rarity:"炮塔", tags:["冰霜"], max:1, minWave:1, unlock:"frost", desc:()=>"在防线中央部署范围冰霜炮。", note:"周期性减速范围内全部敌人。" },
    { id:"frost_field", name:"范围寒潮", glyph:"❄", rarity:"进阶", tags:["冰霜"], max:4, req:["turret_frost"], desc:(r)=>`冰霜炮范围提高 ${18+r*7}%，减速强度提高 ${8+r*4}%，形成范围减速。`, note:"从点状减速升级为大范围控场。" },
    { id:"brittle", name:"脆化装甲", glyph:"✧", rarity:"稀有", tags:["冰霜","功能"], max:3, req:["turret_frost"], minWave:3, desc:(r)=>`减速目标额外承受 ${14+r*5}% 伤害。`, note:"把控制时间转化为输出窗口。" },

    { id:"turret_arc", name:"部署：电弧炮", glyph:"ϟ", rarity:"炮塔", tags:["电弧"], max:1, minWave:2, unlock:"arc", desc:()=>"部署可以连续跳跃的电弧炮。", note:"擅长处理纵向与横向混合敌群。" },
    { id:"chain", name:"增殖电弧", glyph:"↯", rarity:"进阶", tags:["电弧"], max:4, req:["turret_arc"], desc:(r)=>`电弧额外跳跃 ${1+r} 次。`, note:"每次跳跃都会记录独立伤害。" },
    { id:"overload", name:"高压过载", glyph:"⚡", rarity:"稀有", tags:["电弧"], max:3, req:["turret_arc"], minWave:4, desc:(r)=>`电弧伤害提高 ${30+r*10}%，并有概率短暂眩晕。`, note:"让连锁伤害兼具控制。" },

    { id:"lifesteal", name:"生命虹吸", glyph:"♥", rarity:"生存", tags:["生存"], max:4, minWave:2, desc:(r)=>`获得吸血：造成伤害的 ${0.6+r*.35}% 转化为生命。`, note:"高频、多目标和持续伤害都会提高治疗量。" },
    { id:"barrier", name:"相位护盾", glyph:"⬡", rarity:"生存", tags:["生存"], max:4, desc:(r)=>`护盾上限提高 ${20+r*10}，选取时立即补充护盾。`, note:"护盾优先吸收漏怪和敌方炮火。" },
    { id:"shield_regen", name:"护盾再生", glyph:"+", rarity:"生存", tags:["生存"], max:3, req:["barrier"], minWave:3, desc:(r)=>`脱离受击 4 秒后，每秒恢复 ${2+r*1.5} 护盾。`, note:"对抗第 8 波后敌方远程攻击。" },
    { id:"emergency_repair", name:"应急维修", glyph:"✚", rarity:"生存", tags:["生存"], max:3, desc:(r)=>`立即恢复 ${18+r*9} 生命，并使每波结束恢复少量生命。`, note:"即时保命功能卡。", instant:"repair" },
    { id:"blood_bargain", name:"禁忌洞见", glyph:"◐", rarity:"功能", tags:["功能","生存"], max:1, minWave:3, desc:()=>"今后每次三选一永久增加 1 次刷新，但立即牺牲当前生命值 50%。", note:"强力牌池功能卡；需要吸血或护盾支撑。", instant:"bargain" },
    { id:"gold_magnet", name:"战利品磁场", glyph:"¤", rarity:"经济", tags:["经济"], max:3, minWave:2, desc:(r)=>`敌人掉落金币提高 ${25+r*15}%。`, note:"为军械升级提供长期资源。" },
    { id:"bounty_intel", name:"猎杀情报", glyph:"⌖", rarity:"功能", tags:["功能","经济"], max:2, minWave:4, desc:(r)=>`限时猎物的奖励金币提高 ${60+r*40}%，倒计时延长 ${2+r} 秒。`, note:"提高额外选牌奖励的稳定性。" },

    { id:"blood_engine", name:"鲜血引擎", glyph:"♥", rarity:"组合", tags:["生存","功能"], max:1, req:["lifesteal","blood_bargain"], minWave:4, combo:true, desc:()=>"生命低于 50% 时吸血翻倍；溢出治疗转化为护盾。", note:"用危险生命线换取持续运转。" },
    { id:"laser_lock", name:"锁定熔解", glyph:"◎", rarity:"组合", tags:["激光","功能"], max:1, req:["laser_melt","expose"], minWave:5, combo:true, desc:()=>"激光攻击易伤目标时伤害逐步提高，最多 80%。", note:"单体持续输出核心。" },
    { id:"thermal_warhead", name:"冷热战斗部", glyph:"◈", rarity:"组合", tags:["导弹","冰霜"], max:1, req:["missile_burn","frost_field"], minWave:5, combo:true, desc:()=>"导弹命中减速目标时，额外造成其最大生命 5% 的伤害。", note:"专门处理重甲、炮手与首领。" },
    { id:"shatter", name:"范围碎裂", glyph:"✧", rarity:"组合", tags:["冰霜","功能"], max:1, req:["frost_field","brittle"], minWave:5, combo:true, desc:()=>"减速敌人死亡时爆裂，对附近敌人造成范围伤害并延续减速。", note:"大范围减速形成连锁清场。" },
    { id:"storm_array", name:"风暴阵列", glyph:"☇", rarity:"组合", tags:["电弧"], max:1, req:["chain","overload"], minWave:6, combo:true, desc:()=>"每 18 次电弧命中触发全场雷击。", note:"跳跃次数转化为全屏爆发。" },
    { id:"fortress", name:"不落壁垒", glyph:"⬢", rarity:"组合", tags:["生存"], max:1, req:["barrier","shield_regen"], minWave:5, combo:true, desc:()=>"护盾上限提高 50%，满护盾时所有炮塔伤害提高 20%。", note:"把防御资源转化为输出。" }
  ];
  const CARD_MAP = Object.fromEntries(CARDS.map((card)=>[card.id,card]));
  const TURRET_CARD = { laser:"turret_laser", missile:"turret_missile", frost:"turret_frost", arc:"turret_arc" };

  const STAT_INFO = {
    "子弹炮":COLORS.bullet, "激光炮":COLORS.laser, "导弹炮":COLORS.missile, "燃烧":COLORS.missile,
    "冰霜炮":COLORS.frost, "电弧炮":COLORS.arc, "风暴阵列":"#d8c9ff", "范围碎裂":"#baf4ff", "冷热战斗部":"#ffb26f",
    "吸血":COLORS.green, "鲜血引擎":"#ff7f94", "护盾再生":COLORS.cyan, "应急维修":COLORS.green, "波次维修":"#8ee9c3", "炮塔屏障":"#8ff4ff"
  };

  const MUSIC_TRACKS = [
    ["Sun Mother","assets/music/sun-mother.ogg"], ["The Somnium","assets/music/the-somnium.ogg"],
    ["Ether","assets/music/ether.ogg"], ["Wither Away","assets/music/wither-away.ogg"],
    ["Afterlife","assets/music/afterlife.ogg"], ["Mesa","assets/music/mesa.ogg"],
    ["Subterranean","assets/music/subterranean.ogg"], ["The Long Sleep","assets/music/the-long-sleep.ogg"],
    ["Black Desert","assets/music/black-desert.ogg"], ["Hawking's Waltz","assets/music/hawkings-waltz.ogg"],
    ["Oceans of Time","assets/music/oceans-of-time.ogg"], ["The Rising Dawn Bellows Like Thunder","assets/music/the-rising-dawn-bellows-like-thunder.ogg"],
    ["City of Ghosts","assets/music/city-of-ghosts.ogg"], ["Passage","assets/music/passage.ogg"]
  ].map(([title,src])=>({title,src}));

  const SHOP_DEFS = [
    { id:"damage", name:"基础攻击力", desc:"所有炮塔伤害 +10%", base:38, scale:1.5 },
    { id:"crit", name:"暴击率", desc:"所有炮塔暴击率 +2%", base:52, scale:1.62 },
    { id:"critDamage", name:"暴击伤害", desc:"暴击倍率 +15%", base:66, scale:1.68 },
    { id:"rate", name:"攻击速度", desc:"所有炮塔攻击速度 +6%", base:58, scale:1.64 }
  ];

  const DEFAULT_SETTINGS = {fontScale:125,pauseOnDraft:true,musicMode:"sequential"};
  const TARGET_MODES = [
    {id:"nearest",name:"最近"},{id:"farthest",name:"最远"},{id:"highestHp",name:"血最多"},{id:"lowestHp",name:"血最少"}
  ];
  const DEFAULT_TARGET_MODE = {bullet:"nearest",laser:"highestHp",missile:"lowestHp",frost:"nearest",arc:"highestHp"};
  function loadSettings(){try{return {...DEFAULT_SETTINGS,...JSON.parse(localStorage.getItem(SETTINGS_KEY)||"{}")};}catch{return {...DEFAULT_SETTINGS};}}

  const state = {
    started:false, paused:true, drafting:false, gameOver:false, selectingCard:false,
    wave:0, waveTarget:0, waveSpawned:0, waveResolved:0, spawnTimer:0, waveEnding:false, waveEndTimer:0, startDelay:0,
    elapsed:0, score:0, kills:0, coreHp:100, coreMax:100, shield:0, shieldMax:0, lastDamageTime:-99, globalBarrierHp:90, globalBarrierMax:90, globalBarrierCooldown:0,
    coins:0, shop:{damage:0,crit:0,critDamage:0,rate:0}, cards:new Map(), tagCounts:{}, offerBonus:0, bonusOfferSlots:0,
    turrets:{}, enemies:[], projectiles:[], particles:[], beams:[], nextEnemyId:1, nextProjectileId:1,
    currentOffers:[], rerolled:false, rerollsLeft:0, best:{wave:0,score:0}, music:true, sound:true, musicIndex:0, lastTime:0, saveAccumulator:0,
    stats:{damage:{},healing:{},events:[],peakDps:0}, settings:loadSettings(), accountStore:loadAccountStore(), authenticated:false, pendingAccountId:null, panelWasPaused:false
  };

  function cardRank(id){return state.cards.get(id)||0;}
  function hasCard(id){return cardRank(id)>0;}
  function formatTime(seconds){const m=Math.floor(seconds/60),s=Math.floor(seconds%60);return `${String(m).padStart(2,"0")}:${String(s).padStart(2,"0")}`;}
  function clamp(value,min,max){return Math.max(min,Math.min(max,value));}
  function escapeHtml(text){return String(text).replace(/[&<>'"]/g,(char)=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"})[char]);}
  function showToast(text){const toast=$("#statusToast");toast.textContent=text;toast.classList.add("show");clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>toast.classList.remove("show"),1900);}
  function persistSettings(){try{localStorage.setItem(SETTINGS_KEY,JSON.stringify(state.settings));}catch{/* optional preference */}}
  function applySettings(){const scale=clamp(Number(state.settings.fontScale)||DEFAULT_SETTINGS.fontScale,100,160);state.settings.fontScale=scale;if(!["sequential","random"].includes(state.settings.musicMode))state.settings.musicMode="sequential";document.documentElement.style.setProperty("--ui-font-scale",String(scale/100));if($("#fontScaleInput"))$("#fontScaleInput").value=scale;if($("#fontScaleValue"))$("#fontScaleValue").textContent=`${scale}%`;if($("#pauseOnDraftInput"))$("#pauseOnDraftInput").checked=!!state.settings.pauseOnDraft;if($("#musicModeInput"))$("#musicModeInput").value=state.settings.musicMode;updateTrackLabel();}
  function updateFontScale(value){state.settings.fontScale=clamp(Number(value)||DEFAULT_SETTINGS.fontScale,100,160);applySettings();persistSettings();}
  function updateDraftPause(value){state.settings.pauseOnDraft=!!value;if(state.drafting){state.paused=state.settings.pauseOnDraft;syncPauseUI();}persistSettings();}
  function updateMusicMode(value){state.settings.musicMode=value==="random"?"random":"sequential";applySettings();persistSettings();showToast(state.settings.musicMode==="random"?"背景音乐：随机播放":"背景音乐：顺序循环");}
  function resetSettings(){state.settings={...DEFAULT_SETTINGS};applySettings();persistSettings();showToast("设置已恢复默认");}

  function loadAccountStore(){try{const saved=JSON.parse(localStorage.getItem(ACCOUNT_KEY));if(saved&&Array.isArray(saved.accounts))return {currentId:saved.currentId||null,accounts:saved.accounts};}catch{/* clean archive */}return {currentId:null,accounts:[]};}
  function persistAccountStore(){try{localStorage.setItem(ACCOUNT_KEY,JSON.stringify(state.accountStore));}catch{showToast("本机存储空间不足");}}
  function activeAccount(){if(!state.authenticated)return null;return state.accountStore.accounts.find((account)=>account.id===state.accountStore.currentId)||null;}
  async function hashPin(pin,salt){try{const bytes=new TextEncoder().encode(`${salt}:${pin}:endless-local`);const digest=await crypto.subtle.digest("SHA-256",bytes);return [...new Uint8Array(digest)].map((byte)=>byte.toString(16).padStart(2,"0")).join("");}catch{let hash=2166136261;for(const char of `${salt}:${pin}:endless-local`){hash^=char.charCodeAt(0);hash=Math.imul(hash,16777619);}return `fallback-${(hash>>>0).toString(16)}`;}}
  function validRun(run){return run?.version===SAVE_VERSION;}
  function renderProfiles(){const accounts=state.accountStore.accounts;$("#profileList").innerHTML=accounts.length?accounts.map((account)=>{const selected=account.id===state.pendingAccountId;const last=account.id===state.accountStore.currentId;const run=validRun(account.run)?`存档：第 ${account.run.wave} 波 · ${formatTime(account.run.elapsed||0)}`:account.run?"旧版记录需重新开始":"暂无进行中存档";return `<button class="profile-option ${selected?"active":""}" data-account="${account.id}" type="button"><i>${escapeHtml(account.name.slice(0,1).toUpperCase())}</i><span><b>${escapeHtml(account.name)}</b><small>${run}</small></span><em>${last?"上次登录":"选择"}</em></button>`;}).join(""):'<div class="profile-empty">这台设备还没有账号，请创建指挥官。</div>';$$('.profile-option').forEach((button)=>button.addEventListener("click",()=>selectAccount(button.dataset.account)));$("#loginArea").classList.toggle("hidden",!state.pendingAccountId);}
  function selectAccount(id){if(!state.accountStore.accounts.some((account)=>account.id===id))return;state.pendingAccountId=id;$("#loginPin").value="";$("#loginMessage").textContent="";renderProfiles();requestAnimationFrame(()=>$("#loginPin").focus());}
  function updateAccountUI(){const account=activeAccount();const letter=account?account.name.slice(0,1).toUpperCase():"?";$("#accountAvatar").textContent=letter;$("#startAccountAvatar").textContent=letter;$("#startAccountName").textContent=account?.name||"未登录";$("#accountClose").classList.toggle("hidden",!account);$("#logoutButton").classList.toggle("hidden",!account);$("#saveButton").disabled=!account||!state.started||state.gameOver;$("#loadButton").disabled=!validRun(account?.run);}
  function openAccountPanel(required=false){if(state.started&&!state.gameOver){saveRun(false);state.panelWasPaused=state.paused;state.paused=true;}const remembered=state.accountStore.currentId;state.pendingAccountId=state.accountStore.accounts.some((account)=>account.id===remembered)?remembered:state.accountStore.accounts[0]?.id||null;renderProfiles();updateAccountUI();$("#loginPin").value="";$("#loginMessage").textContent="";$("#createAccountMessage").textContent="";$("#accountClose").classList.toggle("hidden",required||!state.authenticated);$("#accountOverlay").classList.add("show");syncPauseUI();}
  function closeAccountPanel(){if(!state.authenticated)return;$("#accountOverlay").classList.remove("show");if(state.started&&!state.gameOver&&!state.drafting)state.paused=state.panelWasPaused;syncPauseUI();}
  async function loginSelectedAccount(){const account=state.accountStore.accounts.find((item)=>item.id===state.pendingAccountId),pin=$("#loginPin").value.trim();if(!account||!/^\d{4}$/.test(pin)){$("#loginMessage").textContent="请输入 4 位数字口令";return;}const digest=await hashPin(pin,account.id);if(digest!==account.pinHash){$("#loginMessage").textContent="口令不正确";return;}state.authenticated=true;state.accountStore.currentId=account.id;account.lastLoginAt=Date.now();account.best||={wave:0,score:0};state.best={...account.best};persistAccountStore();$("#accountOverlay").classList.remove("show");updateAccountUI();showStartScreen();playSound("card");}
  async function createAccount(event){event.preventDefault();const name=$("#newAccountName").value.trim(),pin=$("#newAccountPin").value.trim();if(name.length<2||name.length>12){$("#createAccountMessage").textContent="名称需要 2–12 个字符";return;}if(!/^\d{4}$/.test(pin)){$("#createAccountMessage").textContent="口令必须是 4 位数字";return;}if(state.accountStore.accounts.some((account)=>account.name.toLowerCase()===name.toLowerCase())){$("#createAccountMessage").textContent="这个名称已经存在";return;}const id=`acct-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,8)}`;const account={id,name,pinHash:await hashPin(pin,id),createdAt:Date.now(),lastLoginAt:Date.now(),best:{wave:0,score:0},run:null};state.accountStore.accounts.push(account);state.accountStore.currentId=id;state.authenticated=true;state.best={wave:0,score:0};persistAccountStore();$("#createAccountForm").reset();$("#accountOverlay").classList.remove("show");updateAccountUI();showStartScreen();playSound("start");}
  function logoutAccount(){if(state.started&&!state.gameOver)saveRun(false);state.authenticated=false;state.started=false;state.paused=true;$("#startOverlay").classList.remove("show");$("#draftOverlay").classList.remove("show");updateAccountUI();openAccountPanel(true);}
  function saveBest(){const account=activeAccount();if(state.wave>state.best.wave||state.score>state.best.score)state.best={wave:Math.max(state.best.wave,state.wave),score:Math.max(state.best.score,state.score)};if(account){account.best={...state.best};account.lastPlayedAt=Date.now();persistAccountStore();}$("#bestRecord").textContent=`第 ${state.best.wave} 波 · ${state.best.score.toLocaleString()} 分`;}

  function serializeRun(){return {version:SAVE_VERSION,savedAt:Date.now(),wave:state.wave,waveTarget:state.waveTarget,waveSpawned:state.waveSpawned,waveResolved:state.waveResolved,spawnTimer:state.spawnTimer,waveEnding:state.waveEnding,waveEndTimer:state.waveEndTimer,startDelay:state.startDelay,drafting:state.drafting,elapsed:state.elapsed,score:state.score,kills:state.kills,coreHp:state.coreHp,coreMax:state.coreMax,shield:state.shield,shieldMax:state.shieldMax,globalBarrierHp:state.globalBarrierHp,globalBarrierMax:state.globalBarrierMax,globalBarrierCooldown:state.globalBarrierCooldown,coins:state.coins,shop:{...state.shop},cards:[...state.cards.entries()],offerBonus:state.offerBonus,bonusOfferSlots:state.bonusOfferSlots,turrets:Object.fromEntries(Object.entries(state.turrets).map(([id,turret])=>[id,{active:turret.active,cooldown:turret.cooldown,shots:turret.shots,targetMode:turret.targetMode}])),enemies:state.enemies.filter((enemy)=>!enemy.dead).map(({type,...enemy})=>enemy),nextEnemyId:state.nextEnemyId,stats:{damage:state.stats.damage,healing:state.stats.healing,peakDps:state.stats.peakDps}};}
  function saveRun(manual=false){const account=activeAccount();if(!account||!state.started||state.gameOver)return false;account.run=serializeRun();account.lastPlayedAt=Date.now();persistAccountStore();if(manual){showToast(`已保存 · 第 ${state.wave} 波`);playSound("card");}updateAccountUI();return true;}
  function loadRun(){const account=activeAccount(),run=account?.run;if(!validRun(run)){showToast("没有兼容的存档");return;}Object.assign(state,{started:true,paused:false,drafting:false,gameOver:false,selectingCard:false,wave:run.wave,waveTarget:run.waveTarget,waveSpawned:run.waveSpawned,waveResolved:run.waveResolved,spawnTimer:run.spawnTimer,waveEnding:!!run.waveEnding,waveEndTimer:run.waveEndTimer||0,startDelay:run.startDelay||0,elapsed:run.elapsed||0,score:run.score||0,kills:run.kills||0,coreHp:run.coreHp??100,coreMax:run.coreMax||100,shield:run.shield||0,shieldMax:run.shieldMax||0,coins:run.coins||0,shop:{damage:0,crit:0,critDamage:0,rate:0,...run.shop},cards:new Map(run.cards||[]),offerBonus:run.offerBonus||0,bonusOfferSlots:run.bonusOfferSlots||0,enemies:(run.enemies||[]).map((enemy)=>({...enemy,type:ENEMY_TYPES[enemy.typeId],dead:false,hit:0})),projectiles:[],particles:[],beams:[],nextEnemyId:run.nextEnemyId||1,saveAccumulator:0,stats:{damage:{...(run.stats?.damage||{})},healing:{...(run.stats?.healing||{})},events:[],peakDps:run.stats?.peakDps||0}});state.globalBarrierMax=run.globalBarrierMax||barrierCapacity();state.globalBarrierHp=run.globalBarrierHp??state.globalBarrierMax;state.globalBarrierCooldown=run.globalBarrierCooldown||0;state.turrets=makeTurrets(run.turrets);rebuildTags();$("#startOverlay").classList.remove("show");$("#loadConfirmOverlay").classList.remove("show");updateAllUI();if(run.drafting)showDraft();else{showToast(`已加载第 ${state.wave} 波存档`);syncPauseUI();}startBackgroundMusic();}
  function requestLoadRun(){const run=activeAccount()?.run;if(!validRun(run)){showToast("没有兼容的存档");return;}state.panelWasPaused=state.paused;if(state.started&&!state.gameOver)state.paused=true;$("#confirmLoadWave").textContent=String(run.wave).padStart(2,"0");$("#confirmLoadTime").textContent=formatTime(run.elapsed||0);$("#loadConfirmOverlay").classList.add("show");syncPauseUI();}
  function cancelLoadRun(){$("#loadConfirmOverlay").classList.remove("show");if(state.started&&!state.gameOver&&!state.drafting)state.paused=state.panelWasPaused;syncPauseUI();}
  function discardRun(){const account=activeAccount();if(account){account.run=null;persistAccountStore();}renderStartChoice();showToast("上次记录已放弃");}
  function renderStartChoice(){const run=activeAccount()?.run,hasRun=validRun(run);$("#resumePanel").classList.toggle("hidden",!hasRun);$("#newRunButton").classList.toggle("hidden",hasRun);if(hasRun){$("#resumeWave").textContent=String(run.wave).padStart(2,"0");$("#resumeTime").textContent=formatTime(run.elapsed||0);$("#resumeCards").textContent=(run.cards||[]).reduce((sum,item)=>sum+Number(item[1]||0),0);$("#resumeCoins").textContent=run.coins||0;}}
  function showStartScreen(){if(!state.authenticated){openAccountPanel(true);return;}state.started=false;state.paused=true;state.drafting=false;$("#draftOverlay").classList.remove("show");$("#resultOverlay").classList.remove("show");saveBest();renderStartChoice();$("#startOverlay").classList.add("show");updateAccountUI();syncPauseUI();}

  function makeTurrets(saved=null){return Object.fromEntries(Object.entries(TURRET_DEFS).map(([id,def])=>{const stored=saved?.[id];return [id,{...def,id,active:id==="bullet"||!!stored?.active,cooldown:stored?.cooldown??Math.random()*.25,shots:stored?.shots||0,recoil:0,targetMode:stored?.targetMode||DEFAULT_TARGET_MODE[id]}];}));}
  function resetGame(){const account=activeAccount();if(account)account.run=null;Object.assign(state,{started:true,paused:false,drafting:false,gameOver:false,selectingCard:false,wave:0,waveTarget:0,waveSpawned:0,waveResolved:0,waveEnding:false,waveEndTimer:0,startDelay:0,elapsed:0,score:0,kills:0,coreHp:100,coreMax:100,shield:0,shieldMax:0,lastDamageTime:-99,globalBarrierHp:90,globalBarrierMax:90,globalBarrierCooldown:0,coins:0,shop:{damage:0,crit:0,critDamage:0,rate:0},cards:new Map(),tagCounts:{},offerBonus:0,bonusOfferSlots:0,enemies:[],projectiles:[],particles:[],beams:[],nextEnemyId:1,nextProjectileId:1,currentOffers:[],rerolled:false,saveAccumulator:0,stats:{damage:{},healing:{},events:[],peakDps:0}});state.turrets=makeTurrets();$("#startOverlay").classList.remove("show");$("#resultOverlay").classList.remove("show");startNextWave();updateAllUI();syncPauseUI();saveRun(false);startBackgroundMusic();playSound("start");}

  function rebuildTags(){state.tagCounts={};for(const [id,rank] of state.cards)(CARD_MAP[id]?.tags||[]).forEach((tag)=>state.tagCounts[tag]=(state.tagCounts[tag]||0)+rank);updateDerivedDefense();}
  function updateDerivedDefense(){const barrier=cardRank("barrier");state.shieldMax=barrier?barrier*20+barrier*Math.max(0,barrier-1)*10:0;if(hasCard("fortress"))state.shieldMax=Math.round(state.shieldMax*1.5);state.shield=Math.min(state.shield,state.shieldMax);}
  function addCard(id){const card=CARD_MAP[id];if(!card)return;const previous=cardRank(id),rank=Math.min(card.max,previous+1);state.cards.set(id,rank);if(card.unlock&&state.turrets[card.unlock])state.turrets[card.unlock].active=true;if(card.instant==="repair")healCore(18+rank*9,"应急维修");if(card.instant==="bargain"&&previous===0){state.coreHp=Math.max(1,state.coreHp*.5);state.offerBonus+=1;showToast("禁忌洞见：当前生命 -50% · 每次选牌刷新 +1");}rebuildTags();if(card.id==="barrier"){state.shield=Math.min(state.shieldMax,state.shield+20+rank*8);}if(card.combo)showCombo(card);playSound(card.combo?"combo":"card");updateAllUI();}
  function showCombo(card){$("#comboBannerName").textContent=card.name;$("#comboBanner").classList.add("show");clearTimeout(showCombo.timer);showCombo.timer=setTimeout(()=>$("#comboBanner").classList.remove("show"),2600);}
  function eligibleCards(){return CARDS.filter((card)=>cardRank(card.id)<card.max&&(card.minWave||1)<=state.wave&&(!card.req||card.req.every(hasCard)));}
  function cardWeight(card){let weight=1+Math.random()*2;if(cardRank(card.id))weight+=7;if(card.combo)weight+=13;if(card.unlock)weight+=state.wave<=4?12:4;for(const tag of card.tags)weight+=(state.tagCounts[tag]||0)*1.7;if(card.id==="lifesteal"&&hasCard("blood_bargain"))weight+=9;if(card.id==="barrier"&&state.wave>=6)weight+=4;return weight;}
  function generateOffers(){const eligible=eligibleCards(),scored=eligible.map((card)=>({card,score:cardWeight(card)+Math.random()*3})).sort((a,b)=>b.score-a.score),offers=[];const missingTurrets=CARDS.filter((card)=>card.unlock&&!hasCard(card.id)&&(card.minWave||1)<=state.wave);if(missingTurrets.length&&state.wave<=5)offers.push(missingTurrets[Math.floor(Math.random()*missingTurrets.length)]);const combo=scored.find((item)=>item.card.combo&&!offers.includes(item.card));if(combo)offers.push(combo.card);for(const item of scored){if(offers.length>=3)break;if(!offers.includes(item.card))offers.push(item.card);}state.currentOffers=offers.slice(0,3);renderDraft();}
  function renderDraft(){$("#cardChoices").innerHTML=state.currentOffers.map((card)=>{const current=cardRank(card.id),color=CARD_COLORS[card.tags[0]]||COLORS.cyan;return `<button class="draft-card ${card.combo?"combo":""}" data-card="${card.id}" style="--card-color:${color}" type="button"><span class="card-top"><b>${card.rarity.toUpperCase()}</b><em>${current?`LV.${current} → ${current+1}`:"NEW"}${card.max>1?` / ${card.max}`:""}</em></span><i class="glyph">${card.glyph}</i><h3>${card.name}</h3><span class="tags">${card.tags.join(" · ")}</span><p>${card.desc(current)}</p><small>${card.note}</small></button>`;}).join("");$$('.draft-card').forEach((button)=>button.addEventListener("click",()=>chooseCard(button.dataset.card)));$("#offerCountText").textContent=`${state.currentOffers.length} 选 1`;}
  function chooseCard(id){if(!state.drafting||state.selectingCard)return;state.selectingCard=true;$$('.draft-card').forEach((button)=>button.disabled=true);$("#draftOverlay").classList.remove("show");requestAnimationFrame(()=>{addCard(id);state.drafting=false;state.paused=false;state.bonusOfferSlots=0;repairAfterWave();startNextWave();state.selectingCard=false;syncPauseUI();saveRun(false);});}
  function repairAfterWave(){const rank=cardRank("emergency_repair");if(rank)healCore(2+rank*2,"波次维修");}
  function showDraft(){if(state.gameOver||state.drafting)return;state.drafting=true;state.paused=!!state.settings.pauseOnDraft;state.rerolled=false;state.rerollsLeft=1+state.offerBonus+state.bonusOfferSlots;$("#clearedWave").textContent=state.wave;$("#draftReason").textContent=state.offerBonus?`固定三选一 · 禁忌洞见提供 ${state.offerBonus} 次额外刷新`:"固定三选一 · 至少一张卡会延续或扩展当前构筑";$("#bountyRewardText").textContent=state.bonusOfferSlots?`限时击杀奖励：本次刷新 +${state.bonusOfferSlots}`:"";$("#rerollButton").disabled=false;$("#rerollButton").textContent=`↻ 刷新（剩余 ${state.rerollsLeft}）`;generateOffers();$("#draftOverlay").classList.add("show");syncPauseUI();saveRun(false);playSound("wave");}

  function startNextWave(){state.wave+=1;state.waveTarget=Math.floor(8+state.wave*2.35+Math.pow(state.wave,1.08));Object.assign(state,{waveSpawned:0,waveResolved:0,spawnTimer:.35,startDelay:.8,waveEnding:false,waveEndTimer:0});const capacity=barrierCapacity();state.globalBarrierMax=capacity;state.globalBarrierHp=state.wave===1?capacity:Math.min(capacity,Math.max(0,state.globalBarrierHp)+capacity*.4);state.globalBarrierCooldown=0;$("#phaseText").textContent=state.wave%10===0?"首领波次":state.wave>=8?"敌方火力已上线":"星潮推进";saveRun(false);updateUI(true);}
  function waveBaseHp(){return 36*Math.pow(1.15,state.wave-1)*(1+Math.max(0,state.wave-20)*.018);}
  function barrierCapacity(){return Math.round(78+waveBaseHp()*1.35);}
  function barrierSurfaceY(x){const normalized=clamp((x-W/2)/(W/2-12),-1,1);return 1092-182*Math.sqrt(Math.max(0,1-normalized*normalized));}
  function pickEnemyType(index){if(state.wave%10===0&&index===state.waveTarget-1)return "boss";if(state.wave>=3&&index===Math.floor(state.waveTarget*.42))return "bounty";const roll=Math.random();if(state.wave>=8&&roll<.13)return "shooter";if(state.wave>=6&&roll<.25)return "shield";if(state.wave>=4&&roll<.39)return "tank";if(state.wave>=2&&roll<.62)return "runner";return "swarm";}
  function spawnEnemy(typeId=null){const id=typeId||pickEnemyType(state.waveSpawned),type=ENEMY_TYPES[id],maxHp=waveBaseHp()*type.hp*(type.boss?1+state.wave*.04:1);state.enemies.push({id:state.nextEnemyId++,typeId:id,type,x:58+Math.random()*(W-116),y:-45,maxHp,hp:maxHp,shield:type.shield?maxHp*type.shield:0,speed:(39+Math.min(24,state.wave*.62))*type.speed,drift:(Math.random()-.5)*14,sway:8+Math.random()*18,phase:Math.random()*TAU,slow:0,slowPower:0,stun:0,burn:0,burnDps:0,vulnerable:0,vulnerableTime:0,bountyTime:type.bounty?14+cardRank("bounty_intel")*(2+cardRank("bounty_intel")):0,stopY:type.ranged?390+Math.random()*220:null,attackTimer:type.ranged?2.2+Math.random():0,dead:false,hit:0});}
  function updateSpawns(dt){if(state.waveEnding||state.waveSpawned>=state.waveTarget)return;state.spawnTimer-=dt;if(state.spawnTimer<=0){spawnEnemy();state.waveSpawned+=1;state.spawnTimer=Math.max(.18,.78-state.wave*.012)*(state.wave%10===0?1.2:1);}}
  function selectTarget(turret,range=turret.range){const candidates=state.enemies.filter((enemy)=>!enemy.dead&&Math.hypot(enemy.x-turret.x,enemy.y-turret.y)<=range),mode=turret.targetMode||DEFAULT_TARGET_MODE[turret.id];if(!candidates.length)return null;const distance=(enemy)=>Math.hypot(enemy.x-turret.x,enemy.y-turret.y),health=(enemy)=>enemy.hp+enemy.shield;candidates.sort((a,b)=>{let delta=0;if(mode==="nearest")delta=distance(a)-distance(b);else if(mode==="farthest")delta=distance(b)-distance(a);else if(mode==="highestHp")delta=health(b)-health(a);else delta=health(a)-health(b);return delta||b.y-a.y;});return candidates[0];}
  function setTurretTargetMode(id,mode){const turret=state.turrets[id];if(!turret||!TARGET_MODES.some((item)=>item.id===mode))return;turret.targetMode=mode;showToast(`${turret.name}：优先攻击${TARGET_MODES.find((item)=>item.id===mode).name}`);saveRun(false);}
  function shopDamage(){return 1+state.shop.damage*.1;}
  function shopRate(){return 1+state.shop.rate*.06;}
  function critChance(){return .05+cardRank("crit_training")*.06+state.shop.crit*.02;}
  function critMultiplier(){return 1.8+state.shop.critDamage*.15;}
  function rollDamage(base){const critical=Math.random()<critChance();return {amount:base*shopDamage()*(hasCard("fortress")&&state.shieldMax&&state.shield>=state.shieldMax*.98?1.2:1)*(critical?critMultiplier():1),critical};}
  function fireTurret(turret){const target=selectTarget(turret);if(!target)return;turret.shots+=1;turret.recoil=1;if(turret.id==="bullet"){const base=turret.damage*(1+cardRank("caliber")*.25);spawnProjectile("bullet",turret,target,rollDamage(base),COLORS.bullet);if(cardRank("split_round")&&Math.random()<.16+cardRank("split_round")*.12){const other=state.enemies.find((enemy)=>!enemy.dead&&enemy.id!==target.id&&Math.hypot(enemy.x-target.x,enemy.y-target.y)<150);if(other)spawnProjectile("bullet",turret,other,rollDamage(base*.62),COLORS.bullet);}}
    else if(turret.id==="laser"){const base=turret.damage*(1+cardRank("laser_power")*.28);const rolled=rollDamage(base);damageEnemy(target,rolled.amount,"激光炮",{critical:rolled.critical});state.beams.push({x1:turret.x,y1:turret.y-28,x2:target.x,y2:target.y,color:COLORS.laser,life:.11,maxLife:.11,style:"laser"});spawnSparks(target.x,target.y,COLORS.laser,3,55);const melt=cardRank("laser_melt");if(melt&&turret.shots%Math.max(2,5-melt)===0)applyVulnerability(target,1);}
    else if(turret.id==="missile"){const rank=cardRank("missile_cluster"),base=turret.damage*(1+rank*.16);spawnProjectile("missile",turret,target,rollDamage(base),COLORS.missile);spawnSparks(turret.x,turret.y-34,COLORS.missile,5,65);}
    else if(turret.id==="frost"){const rank=cardRank("frost_field"),radius=turret.range*(1+rank*.18);for(const enemy of state.enemies){if(enemy.dead||Math.hypot(enemy.x-turret.x,enemy.y-turret.y)>radius)continue;const rolled=rollDamage(turret.damage);damageEnemy(enemy,rolled.amount,"冰霜炮",{critical:rolled.critical});applySlow(enemy,.28+rank*.08,2.1);spawnSparks(enemy.x,enemy.y,COLORS.frost,2,38);}state.particles.push({type:"ring",x:turret.x,y:turret.y,r:20,maxR:radius,life:.45,maxLife:.45,color:COLORS.frost});}
    else if(turret.id==="arc"){let current=target,origin={x:turret.x,y:turret.y-22};const hit=new Set(),jumps=2+cardRank("chain");for(let i=0;i<jumps&&current;i++){hit.add(current.id);const rolled=rollDamage(turret.damage*(1+cardRank("overload")*.3)*Math.pow(.82,i));damageEnemy(current,rolled.amount,"电弧炮",{critical:rolled.critical});if(cardRank("overload")&&Math.random()<.04*cardRank("overload"))current.stun=Math.max(current.stun,.35);state.beams.push({x1:origin.x,y1:origin.y,x2:current.x,y2:current.y,color:COLORS.arc,life:.16,maxLife:.16,style:"lightning"});spawnSparks(current.x,current.y,COLORS.arc,3,55);const previous=current,next=state.enemies.filter((enemy)=>!enemy.dead&&!hit.has(enemy.id)&&Math.hypot(enemy.x-previous.x,enemy.y-previous.y)<160).sort((a,b)=>Math.hypot(a.x-previous.x,a.y-previous.y)-Math.hypot(b.x-previous.x,b.y-previous.y))[0];origin={x:previous.x,y:previous.y};current=next;}if(hasCard("storm_array")){state.arcHits=(state.arcHits||0)+hit.size;if(state.arcHits>=18){state.arcHits=0;stormStrike();}}}
  }
  function spawnProjectile(type,turret,target,rolled,color){state.projectiles.push({id:state.nextProjectileId++,type,x:turret.x,y:turret.y-24,targetId:target.id,damage:rolled.amount,critical:rolled.critical,color,speed:type==="missile"?410:900,pierce:type==="bullet"?cardRank("pierce"):0,hitIds:[],angle:Math.atan2(target.y-turret.y,target.x-turret.x),dead:false});}
  function updateTurrets(dt){for(const turret of Object.values(state.turrets)){if(!turret.active)continue;turret.cooldown-=dt;turret.recoil=Math.max(0,turret.recoil-dt*6);if(turret.cooldown<=0){fireTurret(turret);turret.cooldown=TURRET_DEFS[turret.id].cooldown/shopRate()/(turret.id==="bullet"?1+cardRank("rapid")*.18:1);}}}
  function updateProjectiles(dt){for(const projectile of state.projectiles){if(projectile.dead)continue;const target=state.enemies.find((enemy)=>enemy.id===projectile.targetId&&!enemy.dead);if(!target){projectile.dead=true;continue;}const dx=target.x-projectile.x,dy=target.y-projectile.y,distance=Math.hypot(dx,dy),step=projectile.speed*dt;projectile.angle=Math.atan2(dy,dx);if(distance<=step+target.type.radius){impactProjectile(projectile,target);continue;}projectile.x+=dx/distance*step;projectile.y+=dy/distance*step;if(projectile.type==="missile"&&Math.random()<.7)state.particles.push({type:"smoke",x:projectile.x-Math.cos(projectile.angle)*10,y:projectile.y-Math.sin(projectile.angle)*10,r:2,maxR:9,life:.28,maxLife:.28,color:"#8ba4ad"});}state.projectiles=state.projectiles.filter((projectile)=>!projectile.dead);}
  function impactProjectile(projectile,target){if(projectile.type==="missile"){const rank=cardRank("missile_cluster"),radius=72*(1+rank*.25);for(const enemy of state.enemies){if(enemy.dead||Math.hypot(enemy.x-target.x,enemy.y-target.y)>radius)continue;damageEnemy(enemy,projectile.damage,"导弹炮",{critical:projectile.critical});if(cardRank("missile_burn")){enemy.burn=3+cardRank("missile_burn")*.5;enemy.burnDps=Math.max(enemy.burnDps,projectile.damage*.14);}if(hasCard("thermal_warhead")&&enemy.slow>0)damageEnemy(enemy,enemy.maxHp*.05,"冷热战斗部");}state.particles.push({type:"burst",x:target.x,y:target.y,r:8,maxR:radius,life:.42,maxLife:.42,color:COLORS.missile});state.particles.push({type:"burst",x:target.x,y:target.y,r:4,maxR:radius*.55,life:.24,maxLife:.24,color:"#ffe8a8"});spawnSparks(target.x,target.y,COLORS.missile,14,150);projectile.dead=true;return;}damageEnemy(target,projectile.damage,"子弹炮",{critical:projectile.critical});spawnSparks(target.x,target.y,COLORS.bullet,2,46);const frost=cardRank("frost_ammo");if(frost&&Math.random()<.11+frost*.07)applySlow(target,.19+frost*.05,1.7);const expose=cardRank("expose");if(expose&&Math.random()<.06+expose*.03)applyVulnerability(target,1);projectile.hitIds.push(target.id);if(projectile.pierce>0){projectile.pierce-=1;const next=state.enemies.filter((enemy)=>!enemy.dead&&!projectile.hitIds.includes(enemy.id)&&enemy.y<target.y+80).sort((a,b)=>Math.hypot(a.x-target.x,a.y-target.y)-Math.hypot(b.x-target.x,b.y-target.y))[0];if(next){projectile.targetId=next.id;return;}}projectile.dead=true;}
  function applySlow(enemy,power,duration){enemy.slowPower=Math.max(enemy.slowPower,power);enemy.slow=Math.max(enemy.slow,duration);}
  function applyVulnerability(enemy,stacks=1){enemy.vulnerable=Math.min(5,enemy.vulnerable+stacks);enemy.vulnerableTime=4;}
  function stormStrike(){const targets=state.enemies.filter((enemy)=>!enemy.dead).sort((a,b)=>b.y-a.y).slice(0,10);for(const enemy of targets){damageEnemy(enemy,28*shopDamage(),"风暴阵列");state.beams.push({x1:enemy.x,y1:0,x2:enemy.x,y2:enemy.y,color:"#d8c9ff",life:.22,maxLife:.22,style:"lightning"});spawnSparks(enemy.x,enemy.y,"#d8c9ff",8,115);}showToast("风暴阵列 · 全场雷击");}
  function recordStat(kind,source,amount){if(!Number.isFinite(amount)||amount<=0)return;state.stats[kind][source]=(state.stats[kind][source]||0)+amount;state.stats.events.push({t:state.elapsed,kind,source,amount});if(state.stats.events.length>1400)state.stats.events.splice(0,300);}
  function damageEnemy(enemy,amount,source,options={}){if(!enemy||enemy.dead||amount<=0)return 0;let multiplier=1+enemy.vulnerable*.18;if(enemy.slow>0&&cardRank("brittle"))multiplier*=1+cardRank("brittle")*.14;if(source==="激光炮"&&hasCard("laser_lock"))multiplier*=1+Math.min(.8,enemy.vulnerable*.16);let final=amount*multiplier;if(enemy.shield>0){const absorbed=Math.min(enemy.shield,final);enemy.shield-=absorbed;final-=absorbed;}const dealt=Math.min(enemy.hp,final);enemy.hp-=final;enemy.hit=.12;recordStat("damage",source,dealt);if(options.critical||!(enemy.numberCooldown>0)){addParticleText(enemy.x+(Math.random()-.5)*12,enemy.y-8,`${options.critical?"暴击 ":"-"}${Math.round(dealt)}`,options.critical?COLORS.gold:(STAT_INFO[source]||COLORS.cyan));enemy.numberCooldown=options.critical ? .22 : .12;}const steal=cardRank("lifesteal");if(steal&&!options.noLifesteal){let healing=dealt*(.0025+steal*.0035);if(hasCard("blood_engine")&&state.coreHp/state.coreMax<.5)healing*=2;healCore(healing,hasCard("blood_engine")?"鲜血引擎":"吸血",hasCard("blood_engine"));}if(cardRank("execution")&&enemy.vulnerable>0&&!enemy.type.boss&&enemy.hp/enemy.maxHp<.06+cardRank("execution")*.06)enemy.hp=0;if(enemy.type.boss&&cardRank("execution")&&enemy.vulnerable>0&&enemy.hp/enemy.maxHp<.03+cardRank("execution")*.03)enemy.hp=0;if(enemy.hp<=0)killEnemy(enemy,source);return dealt;}
  function healCore(amount,source,overflowShield=false){if(amount<=0)return 0;const healed=Math.min(amount,state.coreMax-state.coreHp);state.coreHp+=healed;if(healed>0)recordStat("healing",source,healed);const overflow=amount-healed;if(overflowShield&&overflow>0&&state.shieldMax>state.shield){const gained=Math.min(overflow,state.shieldMax-state.shield);state.shield+=gained;recordStat("healing",source,gained);return healed+gained;}return healed;}
  function gainShield(amount,source){const gained=Math.min(amount,state.shieldMax-state.shield);if(gained>0){state.shield+=gained;recordStat("healing",source,gained);}return gained;}
  function damageCore(amount,source="突破伤害"){state.lastDamageTime=state.elapsed;let remaining=amount;if(state.shield>0){const absorbed=Math.min(state.shield,remaining);state.shield-=absorbed;remaining-=absorbed;}state.coreHp-=remaining;state.particles.push({type:"flash",x:360,y:CORE_Y,r:15,maxR:180,life:.38,maxLife:.38,color:COLORS.danger});playSound("damage");if(source==="敌方炮火")showToast(`敌方炮手命中防线 -${Math.round(amount)}`);if(state.coreHp<=0)endGame();}
  function killEnemy(enemy,source){if(enemy.dead)return;enemy.dead=true;state.kills+=1;state.waveResolved+=1;const goldBoost=1+cardRank("gold_magnet")*.25;let coins=Math.ceil(enemy.type.coin*goldBoost);if(enemy.type.bounty)coins+=cardRank("bounty_intel")*8;state.coins+=coins;state.score+=Math.round(enemy.type.score*(1+state.wave*.025));if(enemy.type.bounty&&enemy.bountyTime>0){state.bonusOfferSlots=Math.min(2,state.bonusOfferSlots+1);state.coins+=Math.round(20*(1+cardRank("bounty_intel")*.6));showToast("限时击杀成功 · 下次三选一刷新 +1");playSound("combo");}if(hasCard("shatter")&&enemy.slow>0){for(const other of state.enemies){if(other.dead||other.id===enemy.id||Math.hypot(other.x-enemy.x,other.y-enemy.y)>105)continue;damageEnemy(other,enemy.maxHp*.08,"范围碎裂");applySlow(other,.28,1.5);}}state.particles.push({type:"burst",x:enemy.x,y:enemy.y,r:4,maxR:38,life:.28,maxLife:.28,color:enemy.type.color});spawnSparks(enemy.x,enemy.y,enemy.type.color,enemy.type.boss?18:7,enemy.type.boss?150:90);}
  function resolveBarrierCollision(enemy){const surfaceY=barrierSurfaceY(enemy.x);if(state.globalBarrierHp<=0||enemy.y+enemy.type.radius<surfaceY||enemy.y-enemy.type.radius>surfaceY+16)return false;const integrity=enemy.hp+enemy.shield,power=state.globalBarrierHp;state.globalBarrierHp=Math.max(0,state.globalBarrierHp-integrity);if(state.globalBarrierHp<=0)state.globalBarrierCooldown=7;damageEnemy(enemy,power,"炮塔屏障",{noLifesteal:true});state.particles.push({type:"burst",x:enemy.x,y:surfaceY,r:8,maxR:68,life:.38,maxLife:.38,color:COLORS.cyan});spawnSparks(enemy.x,surfaceY,COLORS.cyan,12,135);addParticleText(enemy.x,surfaceY-14,`全域屏障 -${Math.round(Math.min(integrity,power))}`,COLORS.cyan);playSound("damage");return true;}
  function updateEnemies(dt){for(const enemy of state.enemies){if(enemy.dead)continue;enemy.hit=Math.max(0,enemy.hit-dt);enemy.numberCooldown=Math.max(0,(enemy.numberCooldown||0)-dt);enemy.slow=Math.max(0,enemy.slow-dt);enemy.stun=Math.max(0,enemy.stun-dt);enemy.vulnerableTime=Math.max(0,enemy.vulnerableTime-dt);if(!enemy.vulnerableTime)enemy.vulnerable=0;if(enemy.bountyTime>0)enemy.bountyTime=Math.max(0,enemy.bountyTime-dt);if(enemy.burn>0){enemy.burn-=dt;damageEnemy(enemy,enemy.burnDps*dt,"燃烧");if(enemy.dead)continue;}if(resolveBarrierCollision(enemy)&&enemy.dead)continue;if(enemy.stun>0)continue;const slowed=enemy.slow>0?1-enemy.slowPower:1;if(enemy.type.ranged&&enemy.y>=enemy.stopY){enemy.attackTimer-=dt;if(enemy.attackTimer<=0){enemy.attackTimer=Math.max(1.25,3.1-state.wave*.03);damageCore(enemy.type.damage,"敌方炮火");state.beams.push({x1:enemy.x,y1:enemy.y,x2:360,y2:CORE_Y,color:COLORS.danger,life:.2,maxLife:.2,style:"laser"});}continue;}enemy.y+=enemy.speed*slowed*dt;enemy.x+=Math.sin(state.elapsed*1.1+enemy.phase)*enemy.drift*dt;enemy.x=clamp(enemy.x,35,W-35);if(enemy.y>=CORE_Y){enemy.dead=true;state.waveResolved+=1;damageCore(enemy.type.damage,"突破伤害");}}state.enemies=state.enemies.filter((enemy)=>!enemy.dead);}
  function updateDefense(dt){const regen=cardRank("shield_regen");if(regen&&state.shield<state.shieldMax&&state.elapsed-state.lastDamageTime>4)gainShield((.5+regen*1.5)*dt,"护盾再生");if(state.globalBarrierHp<=0){state.globalBarrierCooldown=Math.max(0,state.globalBarrierCooldown-dt);if(!state.globalBarrierCooldown)state.globalBarrierHp=Math.min(state.globalBarrierMax,state.globalBarrierMax*.25);}else if(state.globalBarrierHp<state.globalBarrierMax)state.globalBarrierHp=Math.min(state.globalBarrierMax,state.globalBarrierHp+state.globalBarrierMax*.012*dt);}
  function spawnSparks(x,y,color,count=6,force=80){for(let i=0;i<count;i++){const angle=Math.random()*TAU,speed=force*(.35+Math.random()*.8);state.particles.push({type:"spark",x,y,vx:Math.cos(angle)*speed,vy:Math.sin(angle)*speed,size:1+Math.random()*2.4,color,life:.22+Math.random()*.28,maxLife:.5});}}
  function updateEffects(dt){for(const beam of state.beams)beam.life-=dt;state.beams=state.beams.filter((beam)=>beam.life>0);for(const particle of state.particles){particle.life-=dt;if(particle.type==="text")particle.y-=34*dt;else if(particle.type==="spark"){particle.x+=particle.vx*dt;particle.y+=particle.vy*dt;particle.vx*=Math.pow(.06,dt);particle.vy=particle.vy*Math.pow(.09,dt)+70*dt;}}state.particles=state.particles.filter((particle)=>particle.life>0).slice(-360);}
  function addParticleText(x,y,text,color){state.particles.push({type:"text",x,y,text,color,life:.65,maxLife:.65});}

  function update(dt){if(!state.started||state.paused||state.gameOver)return;const scaled=Math.min(dt,.05);state.elapsed+=scaled;state.saveAccumulator+=scaled;if(state.saveAccumulator>=10){state.saveAccumulator=0;saveRun(false);}if(state.startDelay>0)state.startDelay-=scaled;else updateSpawns(scaled);updateEnemies(scaled);updateTurrets(scaled);updateProjectiles(scaled);updateDefense(scaled);updateEffects(scaled);if(!state.drafting&&!state.waveEnding&&state.waveSpawned>=state.waveTarget&&state.enemies.length===0){state.waveEnding=true;state.waveEndTimer=.7;$("#phaseText").textContent="波次肃清";}if(!state.drafting&&state.waveEnding){state.waveEndTimer-=scaled;if(state.waveEndTimer<=0){state.waveEnding=false;showDraft();}}}

  function shopCost(def){return Math.round(def.base*Math.pow(def.scale,state.shop[def.id]));}
  function buyShopUpgrade(id){const def=SHOP_DEFS.find((item)=>item.id===id);if(!def)return;const cost=shopCost(def);if(state.coins<cost){showToast("金币不足");return;}state.coins-=cost;state.shop[id]+=1;renderShop();updateUI(true);playSound("card");saveRun(false);}
  function renderShop(){$("#shopCoins").textContent=state.coins.toLocaleString();$("#shopItems").innerHTML=SHOP_DEFS.map((def)=>{const level=state.shop[def.id],cost=shopCost(def);return `<div class="shop-item"><div><h3>${def.name} · LV.${level}</h3><p>${def.desc}</p></div><button data-shop="${def.id}" type="button" ${state.coins<cost?"disabled":""}>${cost} 金币</button></div>`;}).join("");$$('[data-shop]').forEach((button)=>button.addEventListener("click",()=>buyShopUpgrade(button.dataset.shop)));$("#shopLevel").textContent=Object.values(state.shop).reduce((a,b)=>a+b,0);}
  function renderLibrary(){const owned=[...state.cards.entries()];$("#ownedCardKinds").textContent=owned.length;$("#ownedCardRanks").textContent=owned.reduce((sum,item)=>sum+item[1],0);$("#ownedCombos").textContent=CARDS.filter((card)=>card.combo&&hasCard(card.id)).length;$("#libraryCards").innerHTML=CARDS.map((card)=>{const rank=cardRank(card.id),ready=!rank&&card.req?.every(hasCard),color=CARD_COLORS[card.tags[0]]||COLORS.cyan;return `<article class="library-card ${rank?"owned":""} ${ready?"combo-ready":""}" style="--card-color:${color}"><header><h3>${card.glyph} ${card.name}</h3><b>${rank?`LV.${rank}/${card.max}`:ready?"可合成":"未拥有"}</b></header><p>${card.desc(Math.max(0,rank-1))}</p></article>`;}).join("");}
  function currentRate(kind){const cutoff=state.elapsed-10;return state.stats.events.filter((event)=>event.kind===kind&&event.t>=cutoff).reduce((sum,event)=>sum+event.amount,0)/Math.min(10,Math.max(1,state.elapsed));}
  function renderMeters(kind,target){const data=state.stats[kind],entries=Object.entries(data).sort((a,b)=>b[1]-a[1]),total=entries.reduce((sum,item)=>sum+item[1],0);$(target).innerHTML=entries.length?entries.map(([source,amount])=>{const share=total?amount/total:0,color=STAT_INFO[source]||COLORS.cyan;return `<div class="meter-row" style="--meter-color:${color}"><i style="width:${share*100}%"></i><div><b>${source}</b><span>${Math.round(amount).toLocaleString()}</span><small>${(share*100).toFixed(1)}%</small></div></div>`;}).join(""):'<div class="meter-empty">尚无记录</div>';}
  function updateStatsUI(){const totalDamage=Object.values(state.stats.damage).reduce((a,b)=>a+b,0),totalHealing=Object.values(state.stats.healing).reduce((a,b)=>a+b,0),dps=currentRate("damage"),hps=currentRate("healing");state.stats.peakDps=Math.max(state.stats.peakDps,dps);$("#totalDamage").textContent=Math.round(totalDamage).toLocaleString();$("#currentDps").textContent=Math.round(dps).toLocaleString();$("#totalHealing").textContent=Math.round(totalHealing).toLocaleString();$("#currentHps").textContent=hps.toFixed(1);$("#dpsText").textContent=Math.round(dps).toLocaleString();$("#combatDpsMini").textContent=Math.round(dps);renderMeters("damage","#damageMeters");renderMeters("healing","#healingMeters");}

  function updateTurretRack(){$("#turretRack").innerHTML=`<div class="global-barrier-status"><span>全域屏障</span><b id="globalBarrierRackValue">${Math.ceil(state.globalBarrierHp)} / ${state.globalBarrierMax}</b></div>`+Object.values(state.turrets).map((turret)=>`<div class="turret-chip ${turret.active?"active":""}" style="--turret-color:${turret.color}"><i>${turret.glyph}</i><b>${turret.name}</b><small>${turret.active?"在线":"待卡牌解锁"}</small><div class="target-radios" role="radiogroup" aria-label="${turret.name}攻击优先级">${TARGET_MODES.map((mode)=>`<label><input data-target-radio="${turret.id}" type="radio" name="target-${turret.id}" value="${mode.id}" ${turret.targetMode===mode.id?"checked":""} ${turret.active?"":"disabled"}><span>${mode.name}</span></label>`).join("")}</div></div>`).join("");$$('[data-target-radio]').forEach((radio)=>radio.addEventListener("change",()=>{if(radio.checked)setTurretTargetMode(radio.dataset.targetRadio,radio.value);}));}
  function updateUI(force=false){$("#waveText").textContent=String(Math.max(1,state.wave)).padStart(2,"0");$("#timeText").textContent=formatTime(state.elapsed);$("#coinText").textContent=state.coins.toLocaleString();$("#coreText").textContent=`${Math.ceil(Math.max(0,state.coreHp))} / ${state.coreMax}`;$("#shieldText").textContent=`${Math.ceil(state.shield)} / ${state.shieldMax}`;$("#coreBar").style.width=`${clamp(state.coreHp/state.coreMax*100,0,100)}%`;$("#shieldBar").style.width=`${state.shieldMax?clamp(state.shield/state.shieldMax*100,0,100):0}%`;const progress=state.waveTarget?state.waveResolved/state.waveTarget*100:0;$("#waveBar").style.width=`${clamp(progress,0,100)}%`;$("#enemyText").textContent=`${Math.max(0,state.waveTarget-state.waveResolved)} 敌军`;$("#cardCount").textContent=[...state.cards.values()].reduce((a,b)=>a+b,0);$("#saveButton").disabled=!state.authenticated||!state.started||state.gameOver;$("#loadButton").disabled=!validRun(activeAccount()?.run);if($("#globalBarrierRackValue"))$("#globalBarrierRackValue").textContent=`${Math.ceil(state.globalBarrierHp)} / ${state.globalBarrierMax}`;if(force){updateTurretRack();renderShop();renderLibrary();}}
  function updateAllUI(){updateUI(true);updateStatsUI();updateAccountUI();}

  function drawBackground(time){const gradient=ctx.createLinearGradient(0,0,0,H);gradient.addColorStop(0,"#071522");gradient.addColorStop(.58,"#050d16");gradient.addColorStop(1,"#081019");ctx.fillStyle=gradient;ctx.fillRect(0,0,W,H);ctx.strokeStyle="rgba(92,230,255,.055)";ctx.lineWidth=1;for(let x=40;x<W;x+=80){ctx.beginPath();ctx.moveTo(x,155);ctx.lineTo(x,CORE_Y+40);ctx.stroke();}const scroll=(time*.02)%70;for(let y=170-scroll;y<CORE_Y;y+=70){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke();}ctx.strokeStyle="rgba(255,94,120,.18)";ctx.setLineDash([10,10]);ctx.beginPath();ctx.moveTo(0,CORE_Y);ctx.lineTo(W,CORE_Y);ctx.stroke();ctx.setLineDash([]);}
  function tracePolygon(sides,radius,rotation=-Math.PI/2){ctx.beginPath();for(let i=0;i<sides;i++){const angle=rotation+i*TAU/sides,x=Math.cos(angle)*radius,y=Math.sin(angle)*radius;i?ctx.lineTo(x,y):ctx.moveTo(x,y);}ctx.closePath();}
  function drawCore(){
    ctx.fillStyle="rgba(92,230,255,.065)";ctx.fillRect(0,CORE_Y,W,H-CORE_Y);
    ctx.strokeStyle="rgba(92,230,255,.38)";ctx.lineWidth=1.5;ctx.beginPath();ctx.moveTo(0,CORE_Y+3);ctx.lineTo(W,CORE_Y+3);ctx.stroke();
    ctx.save();ctx.translate(360,1160);const warning=state.coreHp/state.coreMax<.3,color=warning?COLORS.danger:COLORS.cyan,pulse=.72+Math.sin(state.elapsed*2.4)*.12;
    ctx.shadowColor=color;ctx.shadowBlur=16;ctx.strokeStyle=color;ctx.globalAlpha=.24;ctx.lineWidth=2;for(let i=0;i<3;i++){ctx.beginPath();ctx.arc(0,0,58+i*8,-1.1+i*.2,1.05+i*.2);ctx.stroke();ctx.beginPath();ctx.arc(0,0,58+i*8,2.05+i*.2,4.2+i*.2);ctx.stroke();}
    ctx.globalAlpha=1;ctx.shadowBlur=0;tracePolygon(8,51,Math.PI/8);ctx.fillStyle="#071621";ctx.fill();ctx.strokeStyle=color;ctx.lineWidth=2.2;ctx.stroke();
    tracePolygon(8,39,Math.PI/8);ctx.fillStyle="#0c2230";ctx.fill();ctx.strokeStyle="rgba(210,247,255,.28)";ctx.lineWidth=1;ctx.stroke();
    ctx.save();ctx.rotate(state.elapsed*.16);for(let i=0;i<8;i++){ctx.rotate(TAU/8);ctx.fillStyle=i%2?"#0d2a38":"#123544";ctx.fillRect(43,-4,18,8);ctx.strokeStyle=color;ctx.strokeRect(43,-4,18,8);}ctx.restore();
    const reactor=ctx.createRadialGradient(0,0,2,0,0,23);reactor.addColorStop(0,"#e9fdff");reactor.addColorStop(.18,color);reactor.addColorStop(.5,"rgba(92,230,255,.2)");reactor.addColorStop(1,"rgba(3,12,20,0)");ctx.globalAlpha=pulse;ctx.fillStyle=reactor;ctx.beginPath();ctx.arc(0,0,24,0,TAU);ctx.fill();ctx.globalAlpha=1;
    tracePolygon(4,12,Math.PI/4);ctx.fillStyle="#bff7ff";ctx.fill();ctx.strokeStyle="#fff";ctx.lineWidth=1;ctx.stroke();
    ctx.fillStyle=warning?COLORS.danger:COLORS.green;for(let i=-1;i<=1;i++){ctx.beginPath();ctx.arc(i*9,31,2.2,0,TAU);ctx.fill();}
    ctx.restore();
  }
  function drawTurretMount(turret,radius){
    ctx.save();ctx.shadowColor=turret.color;ctx.shadowBlur=11;ctx.globalAlpha=.28;ctx.strokeStyle=turret.color;ctx.lineWidth=4;ctx.beginPath();ctx.arc(0,0,radius+5,.25,2.55);ctx.stroke();ctx.beginPath();ctx.arc(0,0,radius+5,3.4,5.75);ctx.stroke();ctx.restore();
    tracePolygon(8,radius,Math.PI/8);ctx.fillStyle="#07141e";ctx.fill();ctx.strokeStyle=turret.color;ctx.lineWidth=2;ctx.stroke();
    tracePolygon(8,radius-7,Math.PI/8);ctx.fillStyle="#0d2330";ctx.fill();ctx.strokeStyle="rgba(220,248,255,.2)";ctx.lineWidth=1;ctx.stroke();
    ctx.fillStyle=turret.color;for(let i=0;i<4;i++){const angle=Math.PI/4+i*Math.PI/2;ctx.beginPath();ctx.arc(Math.cos(angle)*(radius-4),Math.sin(angle)*(radius-4),2,0,TAU);ctx.fill();}
  }
  function drawTurretWeapon(turret){
    const color=turret.color;
    if(turret.id==="bullet"){
      ctx.fillStyle="#102b39";ctx.strokeStyle=color;ctx.lineWidth=1.5;ctx.fillRect(-17,-25,34,27);ctx.strokeRect(-17,-25,34,27);
      for(const x of [-10,4]){ctx.fillStyle="#162d38";ctx.fillRect(x,-52,7,30);ctx.strokeRect(x,-52,7,30);ctx.fillStyle=color;ctx.fillRect(x-1,-55,9,4);}
      ctx.fillStyle="#061018";ctx.beginPath();ctx.arc(0,2,13,0,TAU);ctx.fill();ctx.stroke();ctx.fillStyle=color;ctx.beginPath();ctx.arc(0,2,5.5,0,TAU);ctx.fill();
      ctx.strokeStyle="rgba(255,255,255,.34)";ctx.beginPath();ctx.arc(0,2,9,-.8,.8);ctx.stroke();
    }else if(turret.id==="laser"){
      ctx.fillStyle="#152531";ctx.strokeStyle=color;ctx.lineWidth=1.4;tracePolygon(6,15,Math.PI/6);ctx.fill();ctx.stroke();
      ctx.fillRect(-5,-43,10,32);ctx.strokeRect(-5,-43,10,32);ctx.fillStyle=color;tracePolygon(4,8,Math.PI/4);ctx.fill();
      ctx.fillStyle="#08131d";ctx.strokeStyle=color;ctx.fillRect(-18,-17,8,20);ctx.strokeRect(-18,-17,8,20);ctx.fillRect(10,-17,8,20);ctx.strokeRect(10,-17,8,20);
      ctx.shadowColor=color;ctx.shadowBlur=12;ctx.fillStyle="#fff";ctx.fillRect(-2,-48,4,8);ctx.shadowBlur=0;
    }else if(turret.id==="missile"){
      ctx.fillStyle="#132632";ctx.strokeStyle=color;ctx.lineWidth=1.4;ctx.fillRect(-20,-30,17,36);ctx.strokeRect(-20,-30,17,36);ctx.fillRect(3,-30,17,36);ctx.strokeRect(3,-30,17,36);
      for(const x of [-14,-8,8,14]){ctx.fillStyle="#07131c";ctx.beginPath();ctx.arc(x,-22,3.4,0,TAU);ctx.fill();ctx.stroke();ctx.fillStyle=color;ctx.beginPath();ctx.arc(x,-22,1.3,0,TAU);ctx.fill();}
      ctx.fillStyle=color;ctx.beginPath();ctx.moveTo(-19,-34);ctx.lineTo(-3,-34);ctx.lineTo(-11,-43);ctx.closePath();ctx.fill();ctx.beginPath();ctx.moveTo(3,-34);ctx.lineTo(19,-34);ctx.lineTo(11,-43);ctx.closePath();ctx.fill();
    }else if(turret.id==="frost"){
      ctx.strokeStyle=color;ctx.lineWidth=3;for(let i=0;i<3;i++){ctx.save();ctx.rotate(i*TAU/3);ctx.beginPath();ctx.moveTo(0,-8);ctx.lineTo(0,-31);ctx.lineTo(6,-38);ctx.stroke();ctx.restore();}
      ctx.shadowColor=color;ctx.shadowBlur=15;tracePolygon(6,12,Math.PI/6);ctx.fillStyle="#d9fbff";ctx.fill();ctx.shadowBlur=0;ctx.strokeStyle="#fff";ctx.lineWidth=1;ctx.stroke();ctx.fillStyle=color;ctx.beginPath();ctx.arc(0,0,4,0,TAU);ctx.fill();
    }else{
      ctx.strokeStyle=color;ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,0,15,0,TAU);ctx.stroke();ctx.beginPath();ctx.arc(0,0,9,0,TAU);ctx.stroke();
      ctx.fillStyle="#11232e";ctx.fillRect(-18,-11,7,26);ctx.strokeRect(-18,-11,7,26);ctx.fillRect(11,-11,7,26);ctx.strokeRect(11,-11,7,26);
      ctx.beginPath();ctx.moveTo(-14,-13);ctx.lineTo(-8,-27);ctx.lineTo(0,-18);ctx.lineTo(8,-31);ctx.lineTo(14,-14);ctx.stroke();ctx.shadowColor=color;ctx.shadowBlur=11;ctx.fillStyle="#fff";ctx.beginPath();ctx.arc(0,0,4,0,TAU);ctx.fill();ctx.shadowBlur=0;
    }
  }
  function drawGlobalBarrier(){
    const ratio=state.globalBarrierMax?clamp(state.globalBarrierHp/state.globalBarrierMax,0,1):0;if(ratio<=0)return;
    const damage=1-ratio,color=ratio<.28?COLORS.danger:ratio<.55?COLORS.gold:COLORS.cyan;
    const domePath=(offset=0)=>{ctx.beginPath();ctx.moveTo(8,1092+offset);ctx.bezierCurveTo(76,930+offset,205,910+offset,360,910+offset);ctx.bezierCurveTo(515,910+offset,644,930+offset,712,1092+offset);};
    ctx.save();
    const glass=ctx.createLinearGradient(0,900,0,1115);glass.addColorStop(0,"rgba(210,250,255,.015)");glass.addColorStop(.48,`rgba(92,230,255,${.025+.035*ratio})`);glass.addColorStop(1,`rgba(92,230,255,${.09+.05*ratio})`);domePath();ctx.lineTo(712,1117);ctx.lineTo(8,1117);ctx.closePath();ctx.fillStyle=glass;ctx.fill();
    ctx.shadowColor=color;ctx.shadowBlur=26;for(const layer of [{o:-5,w:16,a:.07},{o:0,w:9,a:.16},{o:5,w:4,a:.68},{o:9,w:1.5,a:1}]){domePath(layer.o);ctx.strokeStyle=layer.o===9?"rgba(235,254,255,.9)":color;ctx.lineWidth=layer.w;ctx.globalAlpha=layer.a*(.62+.38*ratio);ctx.stroke();}
    domePath(14);ctx.setLineDash([34,13,8,13]);ctx.strokeStyle=color;ctx.lineWidth=2;ctx.globalAlpha=.22+.28*ratio;ctx.stroke();ctx.setLineDash([]);
    ctx.globalAlpha=.52*ratio;ctx.strokeStyle="#fff";ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(218,926);ctx.bezierCurveTo(286,912,352,914,416,918);ctx.stroke();
    const crackCount=Math.floor(damage*13);ctx.shadowBlur=7;ctx.strokeStyle=ratio<.35?"#ffc5ce":"#d9fbff";ctx.lineWidth=1.2;ctx.globalAlpha=.25+damage*.7;for(let i=0;i<crackCount;i++){const x=62+(i*97)%596,y=barrierSurfaceY(x)+7,length=22+damage*62,dir=i%2?-1:1;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+dir*(7+(i%3)*4),y+length*.28);ctx.lineTo(x-dir*(5+(i%4)*3),y+length*.55);ctx.lineTo(x+dir*(11+(i%2)*7),y+length);ctx.stroke();ctx.beginPath();ctx.moveTo(x+dir*5,y+length*.3);ctx.lineTo(x-dir*(14+i%5*3),y+length*.48);ctx.stroke();if(damage>.52){ctx.beginPath();ctx.moveTo(x-dir*3,y+length*.56);ctx.lineTo(x+dir*(22+i%4*4),y+length*.72);ctx.stroke();}}
    ctx.restore();
    const badgeY=956;ctx.save();ctx.shadowColor=color;ctx.shadowBlur=16;ctx.fillStyle="rgba(3,13,21,.78)";ctx.strokeStyle=color;ctx.lineWidth=2;ctx.fillRect(W/2-76,badgeY-24,152,49);ctx.strokeRect(W/2-76,badgeY-24,152,49);ctx.fillStyle=color;ctx.textAlign="center";ctx.font="700 10px 'Microsoft YaHei UI'";ctx.fillText("全域屏障",W/2,badgeY-7);ctx.font="800 18px Consolas";ctx.fillText(`${Math.ceil(state.globalBarrierHp)} / ${state.globalBarrierMax}`,W/2,badgeY+15);ctx.restore();ctx.textAlign="left";
  }
  function drawTurrets(){drawGlobalBarrier();for(const turret of Object.values(state.turrets)){if(!turret.active)continue;const radius=turret.id==="bullet"?34:29,target=selectTarget(turret),aim=target?Math.atan2(target.y-turret.y,target.x-turret.x)+Math.PI/2:0;ctx.save();ctx.translate(turret.x,turret.y);drawTurretMount(turret,radius);ctx.rotate(aim);ctx.translate(0,turret.recoil*5);drawTurretWeapon(turret);ctx.restore();if(turret.id==="frost"&&cardRank("frost_field")){ctx.strokeStyle="rgba(97,221,255,.1)";ctx.lineWidth=1;ctx.beginPath();ctx.arc(turret.x,turret.y,turret.range*(1+cardRank("frost_field")*.18),0,TAU);ctx.stroke();}}}
  function drawEnemies(){for(const enemy of state.enemies){const radius=enemy.type.radius;ctx.save();ctx.translate(enemy.x,enemy.y);ctx.fillStyle=enemy.hit?"#fff":enemy.type.color;ctx.strokeStyle=enemy.vulnerable?COLORS.gold:enemy.type.bounty&&enemy.bountyTime>0?COLORS.gold:"rgba(255,255,255,.25)";ctx.lineWidth=enemy.type.boss?3:1.4;ctx.beginPath();if(enemy.type.ranged){ctx.rect(-radius,-radius,radius*2,radius*2);}else{ctx.arc(0,0,radius,0,TAU);}ctx.fill();ctx.stroke();if(enemy.type.ranged){ctx.strokeStyle=COLORS.danger;ctx.beginPath();ctx.moveTo(-7,0);ctx.lineTo(7,0);ctx.moveTo(0,-7);ctx.lineTo(0,7);ctx.stroke();}if(enemy.type.bounty&&enemy.bountyTime>0){ctx.strokeStyle=COLORS.gold;ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,0,radius+8,-Math.PI/2,-Math.PI/2+TAU*Math.min(1,enemy.bountyTime/(14+cardRank("bounty_intel")*(2+cardRank("bounty_intel")))));ctx.stroke();ctx.fillStyle=COLORS.gold;ctx.font="8px Consolas";ctx.textAlign="center";ctx.fillText(`${enemy.bountyTime.toFixed(1)}s`,0,-radius-12);}if(enemy.slow>0){ctx.strokeStyle=COLORS.frost;ctx.beginPath();ctx.arc(0,0,radius+4,0,TAU);ctx.stroke();}ctx.restore();const hpWidth=enemy.type.boss?72:enemy.type.ranged?42:32;ctx.fillStyle="rgba(0,0,0,.7)";ctx.fillRect(enemy.x-hpWidth/2,enemy.y-radius-9,hpWidth,3);ctx.fillStyle=enemy.type.color;ctx.fillRect(enemy.x-hpWidth/2,enemy.y-radius-9,hpWidth*clamp(enemy.hp/enemy.maxHp,0,1),3);}}
  function drawProjectiles(){for(const projectile of state.projectiles){ctx.save();ctx.translate(projectile.x,projectile.y);ctx.rotate(projectile.angle||0);if(projectile.type==="missile"){ctx.shadowColor=projectile.color;ctx.shadowBlur=12;ctx.fillStyle="#d8edf2";ctx.strokeStyle=projectile.color;ctx.lineWidth=1.2;ctx.beginPath();ctx.moveTo(12,0);ctx.lineTo(5,-4);ctx.lineTo(-8,-4);ctx.lineTo(-11,0);ctx.lineTo(-8,4);ctx.lineTo(5,4);ctx.closePath();ctx.fill();ctx.stroke();ctx.fillStyle=projectile.color;ctx.beginPath();ctx.moveTo(-5,-4);ctx.lineTo(-11,-9);ctx.lineTo(-9,0);ctx.lineTo(-11,9);ctx.lineTo(-5,4);ctx.closePath();ctx.fill();ctx.fillStyle="#fff0a8";ctx.beginPath();ctx.moveTo(-10,-2.5);ctx.lineTo(-19,0);ctx.lineTo(-10,2.5);ctx.closePath();ctx.fill();}else{ctx.shadowColor=projectile.color;ctx.shadowBlur=9;ctx.strokeStyle=projectile.color;ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(-13,0);ctx.lineTo(4,0);ctx.stroke();ctx.fillStyle="#fff";ctx.beginPath();ctx.arc(5,0,2.2,0,TAU);ctx.fill();}ctx.restore();}}
  function drawEffects(){for(const beam of state.beams){const alpha=clamp(beam.life/beam.maxLife,0,1);ctx.save();ctx.globalAlpha=alpha;ctx.shadowColor=beam.color;ctx.shadowBlur=beam.style==="lightning"?18:12;if(beam.style==="lightning"){for(const width of [8,3,1]){ctx.strokeStyle=width===1?"#fff":beam.color;ctx.lineWidth=width;ctx.globalAlpha=alpha*(width===8?.15:width===3?.65:1);ctx.beginPath();ctx.moveTo(beam.x1,beam.y1);const segments=7;for(let i=1;i<segments;i++){const t=i/segments,x=beam.x1+(beam.x2-beam.x1)*t+(Math.sin(i*12.47+state.elapsed*41)*9),y=beam.y1+(beam.y2-beam.y1)*t+(Math.cos(i*8.13+state.elapsed*37)*7);ctx.lineTo(x,y);}ctx.lineTo(beam.x2,beam.y2);ctx.stroke();}}else{for(const [width,a] of [[10,.12],[5,.42],[2,1]]){ctx.globalAlpha=alpha*a;ctx.strokeStyle=width===2?"#fff":beam.color;ctx.lineWidth=width;ctx.beginPath();ctx.moveTo(beam.x1,beam.y1);ctx.lineTo(beam.x2,beam.y2);ctx.stroke();}}ctx.restore();}for(const particle of state.particles){const alpha=clamp(particle.life/particle.maxLife,0,1);ctx.save();ctx.globalAlpha=alpha;ctx.strokeStyle=particle.color;ctx.fillStyle=particle.color;ctx.shadowColor=particle.color;ctx.shadowBlur=particle.type==="spark"?8:4;if(particle.type==="text"){ctx.font=`800 ${particle.text.startsWith("暴击")?16:13}px 'Microsoft YaHei UI'`;ctx.textAlign="center";ctx.lineWidth=3;ctx.strokeStyle="rgba(0,0,0,.78)";ctx.strokeText(particle.text,particle.x,particle.y);ctx.fillStyle=particle.color;ctx.fillText(particle.text,particle.x,particle.y);}else if(particle.type==="spark"){ctx.lineWidth=particle.size;ctx.beginPath();ctx.moveTo(particle.x,particle.y);ctx.lineTo(particle.x-particle.vx*.045,particle.y-particle.vy*.045);ctx.stroke();}else{const progress=1-alpha,r=particle.r+(particle.maxR-particle.r)*progress;ctx.lineWidth=particle.type==="burst"?3:1.5;ctx.beginPath();ctx.arc(particle.x,particle.y,r,0,TAU);ctx.stroke();if(particle.type==="smoke"){ctx.globalAlpha=alpha*.14;ctx.fill();}}ctx.restore();}ctx.textAlign="left";}
  function draw(time){ctx.clearRect(0,0,W,H);drawBackground(time);drawCore();drawEnemies();drawProjectiles();drawEffects();drawTurrets();}

  const backgroundMusic=$("#backgroundMusic");
  let audioContext=null;
  function updateTrackLabel(){const track=MUSIC_TRACKS[state.musicIndex]||MUSIC_TRACKS[0];if($("#currentTrackName"))$("#currentTrackName").textContent=`当前：${track.title}`;if($("#musicButton"))$("#musicButton").title=`背景音乐：${track.title}`;}
  function loadMusicTrack(index,autoplay=true){state.musicIndex=(index+MUSIC_TRACKS.length)%MUSIC_TRACKS.length;const track=MUSIC_TRACKS[state.musicIndex];if(!backgroundMusic.src.endsWith(track.src))backgroundMusic.src=track.src;updateTrackLabel();if(autoplay)startBackgroundMusic();}
  function nextMusicTrack(){let next=(state.musicIndex+1)%MUSIC_TRACKS.length;if(state.settings.musicMode==="random"&&MUSIC_TRACKS.length>1){do{next=Math.floor(Math.random()*MUSIC_TRACKS.length);}while(next===state.musicIndex);}loadMusicTrack(next,true);}
  function syncBackgroundVolume(){
    backgroundMusic.volume = state.music
      ? (state.paused || state.drafting || !state.started ? .18 : .32)
      : 0;
  }
  function startBackgroundMusic(){if(!state.music)return;if(!backgroundMusic.getAttribute("src"))loadMusicTrack(state.musicIndex,false);syncBackgroundVolume();const promise=backgroundMusic.play();if(promise?.catch)promise.catch(()=>{/* wait for the next user gesture */});}
  function stopBackgroundMusic(){backgroundMusic.pause();}
  function playSound(kind){if(!state.sound)return;try{audioContext||=new(window.AudioContext||window.webkitAudioContext)();if(audioContext.state==="suspended")audioContext.resume();const now=audioContext.currentTime,osc=audioContext.createOscillator(),gain=audioContext.createGain(),preset={shot:[520,.025,"square"],card:[620,.18,"triangle"],combo:[330,.35,"sine"],wave:[440,.24,"triangle"],start:[220,.35,"sine"],damage:[120,.15,"sawtooth"],end:[110,.5,"triangle"]}[kind]||[380,.06,"sine"];osc.type=preset[2];osc.frequency.setValueAtTime(preset[0],now);osc.frequency.exponentialRampToValueAtTime(Math.max(60,preset[0]*1.3),now+preset[1]);gain.gain.setValueAtTime(kind === "shot" ? .018 : .035, now);gain.gain.exponentialRampToValueAtTime(.0001,now+preset[1]);osc.connect(gain);gain.connect(audioContext.destination);osc.start(now);osc.stop(now+preset[1]);}catch{/* optional */}}
  function syncPauseUI(){$("#pauseIcon").textContent=state.paused?"▶":"Ⅱ";$("#pauseButton").classList.toggle("active",state.paused);$("#pauseVeil").classList.toggle("hidden",!state.paused||state.drafting||!state.started);syncBackgroundVolume();}
  function togglePause(){if(!state.started||state.gameOver||state.drafting)return;state.paused=!state.paused;syncPauseUI();showToast(state.paused?"推演暂停":"战斗继续");}
  function closeRails(){const app=$(".portrait-app");app.classList.remove("left-open","right-open");$("#leftRailToggle").setAttribute("aria-expanded","false");$("#rightRailToggle").setAttribute("aria-expanded","false");}
  function toggleRail(side){const app=$(".portrait-app"),className=`${side}-open`,next=!app.classList.contains(className);closeRails();if(next){app.classList.add(className);$(`#${side}RailToggle`).setAttribute("aria-expanded","true");}}
  function openPanel(id,render){closeRails();if(state.started&&!state.gameOver){state.panelWasPaused=state.paused;state.paused=true;}render?.();$(`#${id}`).classList.add("show");syncPauseUI();}
  function closePanel(id){$(`#${id}`).classList.remove("show");if(state.started&&!state.gameOver&&!state.drafting)state.paused=state.panelWasPaused;syncPauseUI();}
  function endGame(){if(state.gameOver)return;state.gameOver=true;state.paused=true;saveBest();const account=activeAccount();if(account){account.run=null;persistAccountStore();}$("#resultWave").textContent=state.wave;$("#resultKills").textContent=state.kills.toLocaleString();$("#resultScore").textContent=state.score.toLocaleString();$("#resultDps").textContent=Math.round(state.stats.peakDps).toLocaleString();setTimeout(()=>$("#resultOverlay").classList.add("show"),400);syncPauseUI();playSound("end");}

  function bindEvents(){
    $("#newRunButton").addEventListener("click",resetGame);$("#continueRunButton").addEventListener("click",loadRun);$("#discardRunButton").addEventListener("click",discardRun);$("#resultRestart").addEventListener("click",showStartScreen);
    $("#saveButton").addEventListener("click",()=>saveRun(true));$("#loadButton").addEventListener("click",requestLoadRun);$("#cancelLoadButton").addEventListener("click",cancelLoadRun);$("#confirmLoadButton").addEventListener("click",loadRun);$("#pauseButton").addEventListener("click",togglePause);$("#leftRailToggle").addEventListener("click",()=>toggleRail("left"));$("#rightRailToggle").addEventListener("click",()=>toggleRail("right"));$("#gameCanvas").addEventListener("click",closeRails);
    $("#musicButton").addEventListener("click",()=>{state.music=!state.music;$("#musicIcon").textContent=state.music?"♫":"×";$("#musicButton").classList.toggle("muted",!state.music);state.music?startBackgroundMusic():stopBackgroundMusic();});
    $("#soundButton").addEventListener("click",()=>{state.sound=!state.sound;$("#soundIcon").textContent=state.sound?"✦":"×";$("#soundButton").classList.toggle("muted",!state.sound);});
    $("#accountButton").addEventListener("click",()=>openAccountPanel(false));$("#startAccountButton").addEventListener("click",()=>openAccountPanel(false));$("#accountClose").addEventListener("click",closeAccountPanel);$("#loginAccountButton").addEventListener("click",loginSelectedAccount);$("#loginPin").addEventListener("keydown",(event)=>{if(event.key==="Enter")loginSelectedAccount();});$("#createAccountForm").addEventListener("submit",createAccount);$("#logoutButton").addEventListener("click",logoutAccount);
    $("#libraryButton").addEventListener("click",()=>openPanel("libraryOverlay",renderLibrary));$("#shopButton").addEventListener("click",()=>openPanel("shopOverlay",renderShop));$("#helpButton").addEventListener("click",()=>openPanel("helpOverlay"));$("#settingsButton").addEventListener("click",()=>openPanel("settingsOverlay",applySettings));$$('[data-close]').forEach((button)=>button.addEventListener("click",()=>closePanel(button.dataset.close)));
    $("#fontScaleInput").addEventListener("input",(event)=>updateFontScale(event.target.value));$("#pauseOnDraftInput").addEventListener("change",(event)=>updateDraftPause(event.target.checked));$("#musicModeInput").addEventListener("change",(event)=>updateMusicMode(event.target.value));$("#resetSettingsButton").addEventListener("click",resetSettings);backgroundMusic.addEventListener("ended",nextMusicTrack);
    $("#rerollButton").addEventListener("click",()=>{if(state.rerollsLeft<=0)return;state.rerollsLeft-=1;$("#rerollButton").disabled=state.rerollsLeft<=0;$("#rerollButton").textContent=state.rerollsLeft?`↻ 刷新（剩余 ${state.rerollsLeft}）`:"刷新次数已用完";generateOffers();});window.addEventListener("keydown",(event)=>{if(event.code==="Space"){event.preventDefault();togglePause();}});document.addEventListener("visibilitychange",()=>{if(document.hidden&&state.started&&!state.gameOver){saveRun(false);state.paused=true;syncPauseUI();}});window.addEventListener("beforeunload",()=>saveRun(false));window.addEventListener("resize",resizeCanvas);
  }
  function resizeCanvas(){const dpr=Math.min(1.35,window.devicePixelRatio||1);canvas.width=W*dpr;canvas.height=H*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);}
  let uiAccumulator=0,statsAccumulator=0,lastDraw=0;
  function loop(time){const dt=state.lastTime?(time-state.lastTime)/1000:0;state.lastTime=time;update(dt);uiAccumulator+=dt;statsAccumulator+=dt;if(uiAccumulator>.18){uiAccumulator=0;updateUI();}if(statsAccumulator>.6){statsAccumulator=0;updateStatsUI();}const active=state.started&&!state.paused&&!state.gameOver,interval=active?1000/60:1000/18;if(time-lastDraw>=interval){lastDraw=time;draw(time);}requestAnimationFrame(loop);}
  function init(){state.turrets=makeTurrets();resizeCanvas();bindEvents();applySettings();loadMusicTrack(0,false);renderProfiles();updateAllUI();$("#startOverlay").classList.remove("show");openAccountPanel(true);draw(0);requestAnimationFrame(loop);}
  init();
})();
