import FiniteEvaluation
import Mathlib.RingTheory.Adjoin.Polynomial.Basic
import Mathlib.Topology.UniformSpace.DiscreteUniformity

noncomputable section
namespace JordanSize

variable {A : Type*} [Ring A] [Algebra ℚ A]

/-- The finite logarithm of `1 + D`, valid in noncommutative algebras too. -/
def operatorLog (D : A) (k : ℕ) : A :=
  ∑ i ∈ Finset.range k,
    (if i = 0 then 0 else (-1 : ℚ) ^ (i + 1) / i) • D ^ i

lemma operatorLog_map {B : Type*} [Ring B] [Algebra ℚ B]
    (f : A →+* B) (D : A) (k : ℕ) :
    f (operatorLog D k) = operatorLog (f D) k := by
  simp only [operatorLog, map_sum, map_rat_smul, map_pow]

theorem operatorLog_nilpotent (D : A) (hD : IsNilpotent D) (k : ℕ) :
    IsNilpotent (operatorLog D k) := by
  apply Commute.isNilpotent_sum
  · intro i hi
    by_cases h : i = 0
    · simp [h]
    · exact (hD.pow_of_pos h).smul _
  · intro i j hi hj
    exact ((Commute.refl D).pow_pow i j).smul_left _ |>.smul_right _

/-- No topology is assumed. The calculation takes place in the commutative
subalgebra generated by D, equipped locally with the discrete uniformity. -/
theorem operatorExpLog (D : A) (k : ℕ) (hk : D ^ k = 0) :
    IsNilpotent.exp (operatorLog D k) = 1 + D := by
  let d : Algebra.adjoin ℚ {D} := ⟨D, Algebra.self_mem_adjoin_singleton ℚ D⟩
  have hd : d ^ k = 0 := by
    apply Subtype.ext
    simpa [d] using hk
  letI : UniformSpace ℚ := ⊥
  letI : UniformSpace (Algebra.adjoin ℚ {D}) := ⊥
  have h := finiteExpLog d k hd (continuous_of_discreteTopology)
  have hlog : ((finiteLog d k : Algebra.adjoin ℚ {D}) : A) = operatorLog D k := by
    change (Algebra.adjoin ℚ {D}).val
      (∑ i ∈ Finset.range k, (if i = 0 then 0 else (-1 : ℚ) ^ (i+1) / i) • d^i) = _
    rw [map_sum]
    unfold operatorLog
    apply Finset.sum_congr rfl
    intro i hi
    by_cases h : i = 0 <;> simp [h, d]
  have he : IsNilpotent.exp (operatorLog D k) =
      ((IsNilpotent.exp (finiteLog d k) : Algebra.adjoin ℚ {D}) : A) := by
    rw [← hlog]
    exact (IsNilpotent.map_exp (finiteLog_nilpotent d ⟨k, hd⟩ k)
      (Algebra.adjoin ℚ {D}).val).symm
  rw [he]
  exact congrArg (fun x : Algebra.adjoin ℚ {D} => (x : A)) h

/-- The other inverse identity, again without any topological hypothesis. -/
theorem operatorLogExp (D : A) (hD : IsNilpotent D) (k : ℕ)
    (hk : (IsNilpotent.exp D - 1)^k = 0) :
    operatorLog (IsNilpotent.exp D - 1) k = D := by
  let d : Algebra.adjoin ℚ {D} := ⟨D, Algebra.self_mem_adjoin_singleton ℚ D⟩
  have hd : IsNilpotent d := by
    obtain ⟨m, hm⟩ := hD
    exact ⟨m, Subtype.ext (by simpa [d] using hm)⟩
  letI : UniformSpace ℚ := ⊥
  letI : UniformSpace (Algebra.adjoin ℚ {D}) := ⊥
  have hm : Continuous (algebraMap ℚ (Algebra.adjoin ℚ {D})) :=
    continuous_of_discreteTopology
  have hmap := hd.map_exp (Algebra.adjoin ℚ {D}).val
  have hk' : (IsNilpotent.exp d - 1)^k = 0 := by
    apply Subtype.ext
    change (Algebra.adjoin ℚ {D}).val ((IsNilpotent.exp d - 1)^k) = 0
    rw [map_pow, map_sub, map_one, hmap]
    exact hk
  have h := evaluated_log_exp d hd hm
  rw [evaluatedExp_eq_finite d hd hm,
    evaluatedLog_eq_finite (IsNilpotent.exp d - 1) k hk' hm] at h
  have h' := congrArg (Algebra.adjoin ℚ {D}).val h
  change (Algebra.adjoin ℚ {D}).val
    (operatorLog (IsNilpotent.exp d - 1) k) = D at h'
  have hmapLog := operatorLog_map (Algebra.adjoin ℚ {D}).val.toRingHom
    (IsNilpotent.exp d - 1) k
  change (Algebra.adjoin ℚ {D}).val (operatorLog (IsNilpotent.exp d - 1) k) = _ at hmapLog
  rw [hmapLog, map_sub, map_one] at h'
  change operatorLog ((Algebra.adjoin ℚ {D}).val (IsNilpotent.exp d) - 1) k = D at h'
  rw [hmap] at h'
  exact h'

/-- The finite exponential is injective on nilpotent elements. -/
theorem nilpotent_exp_injective {D E : A} (hD : IsNilpotent D) (hE : IsNilpotent E)
    (h : IsNilpotent.exp D = IsNilpotent.exp E) : D = E := by
  obtain ⟨k, hk⟩ := hD.isNilpotent_exp_sub_one
  have hkE : (IsNilpotent.exp E - 1)^k = 0 := by rw [← h]; exact hk
  rw [← operatorLogExp D hD k hk, ← operatorLogExp E hE k hkE, h]

end JordanSize
#print axioms JordanSize.operatorLog_nilpotent
#print axioms JordanSize.operatorExpLog
#print axioms JordanSize.operatorLogExp
#print axioms JordanSize.nilpotent_exp_injective
