import {greatWall} from '../great-wall.mjs';
import test from 'node:test';
import assert from 'node:assert/strict';
import * as T from '../../3d/vendor/three.module.js';
import {planConstruction,constructionTiming,riseProgress,readBuildSeconds} from '../construction.mjs';
import {clockAngles} from '../workshop-clock.mjs';
import {replaceDomain,enrichDomain} from '../enchanted-domains.mjs';
import {AtlasScene} from '../../test-module/scene.mjs';
function builder(){const a=Object.create(AtlasScene.prototype);a.materials=Object.fromEntries(['stone','paper','dark','gold','wood','jade','brass','red'].map(n=>[n,new T.MeshStandardMaterial()]));a.rotating=[];a.detailMotion=[];return a;}
test('every domain staggers scenery across the chosen interval after its independent board lift',()=>{for(let index=0;index<8;index++){const a=builder(),p=new T.Group(),lift=new T.Group();p.add(lift);if(index===7)greatWall(a,p);else{replaceDomain(a,p,index);enrichDomain(a,p,index);}p.updateMatrixWorld(true);const meshes=[];p.traverse(o=>{if(o.isMesh)meshes.push([o,o.matrixWorld.clone()]);});const parts=planConstruction(p,lift,a);p.updateMatrixWorld(true);for(const [mesh,matrix]of meshes)assert.ok(mesh.matrixWorld.elements.every((v,i)=>Math.abs(v-matrix.elements[i])<1e-9));for(const seconds of [5,15,45]){const scenery=parts.filter(p=>p.decoration).map(p=>constructionTiming(p,seconds));assert.ok(scenery.length>2);assert.equal(new Set(scenery.map(s=>s.delay)).size,scenery.length);assert.ok(scenery.every(s=>s.delay+s.duration<=seconds+1.35+1e-9));assert.ok(Math.abs(Math.max(...scenery.map(s=>s.delay+s.duration))-seconds-1.35)<1e-9);const board=constructionTiming(parts.at(-1),seconds);assert.equal(board.delay,0);assert.ok(scenery.every(s=>s.delay>=board.duration+.15));}for(const skater of a.iceSkaters||[])assert.ok(skater.root.children.length>0);}});
test('two-stage rise pauses exactly halfway and remains monotone',()=>{assert.equal(riseProgress(.45,true),.5);assert.equal(riseProgress(.55,true),.5);assert.equal(riseProgress(0,true),0);assert.equal(riseProgress(1,true),1);let last=0;for(let u=0;u<=1;u+=.01){const current=riseProgress(u,true);assert.ok(current>=last);last=current;}assert.equal(readBuildSeconds({getItem:()=>null}),15);assert.equal(readBuildSeconds({getItem:()=>25}),25);assert.equal(readBuildSeconds({getItem:()=>100}),45);});
test('clock hands show actual local time, including fractional minutes and seconds',()=>{const noon=clockAngles(new Date(2026,8,21,12,0,0));assert.equal(Math.abs(noon.hour),0);const angles=clockAngles(new Date(2026,8,21,3,30,15,500));assert.ok(Math.abs(angles.second+15.5*Math.PI/30)<1e-9);assert.ok(Math.abs(angles.minute+(30+15.5/60)*Math.PI/30)<1e-9);assert.ok(Math.abs(angles.hour+(3+(30+15.5/60)/60)*Math.PI/6)<1e-9);});
