const {chromium}=require('playwright'),assert=require('node:assert/strict');
const model=require('../../../courses/abstract-algebra/2026-fall/lesson-1/associativity-sudoku.js');
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true}),p=await browser.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'}),errors=[];p.on('pageerror',e=>errors.push(e.message));const base=process.env.SUDOKU_TEST_URL||'http://127.0.0.1:8781/visuals/group-sudoku/';
// Test instrumentation stays outside production code.
await p.route('**/group-sudoku/app.mjs*',async r=>{const res=await r.fetch();await r.fulfill({response:res,body:(await res.text()).replace('world=new SudokuAtlas(canvas)','world=window.__atlas=new SudokuAtlas(canvas)')});});
await p.goto(base);await p.waitForFunction(()=>document.body.dataset.phase==='playing'&&window.__atlas);await p.locator('#loading').waitFor({state:'hidden'});assert.equal(await p.locator('.map-fallback').count(),0);
const radius=()=>p.evaluate(()=>__atlas.camera.position.distanceTo(__atlas.currentTarget)),target=()=>p.evaluate(()=>__atlas.currentTarget.toArray());const initialRadius=await radius();let start=await target();
for(const [key,axis,sign]of [['ArrowUp',2,-1],['ArrowDown',2,1],['ArrowLeft',0,-1],['ArrowRight',0,1]]){start=await target();await p.keyboard.down(key);await p.waitForTimeout(400);await p.keyboard.up(key);const end=await target();assert((end[axis]-start[axis])*sign>1);assert(Math.abs(await radius()-initialRadius)<.01);assert(Math.abs(end[1]-start[1])<.01);}
let stopped=await target();await p.waitForTimeout(150);assert.deepEqual(await target(),stopped);
await p.locator('[data-board-cell="0"]').focus();await p.keyboard.press('Shift+ArrowDown');assert.equal(await p.locator('[data-board-cell][aria-pressed="true"]').getAttribute('data-board-cell'),'2');await p.keyboard.press('Shift+ArrowRight');assert.equal(await p.locator('[data-board-cell][aria-pressed="true"]').getAttribute('data-board-cell'),'3');start=await target();await p.keyboard.down('ArrowUp');await p.waitForTimeout(200);await p.keyboard.up('ArrowUp');assert((await target())[2]<start[2]);assert.equal(await p.locator('[data-board-cell][aria-pressed="true"]').getAttribute('data-board-cell'),'3');
await p.keyboard.down('ArrowUp');await p.waitForTimeout(100);await p.evaluate(()=>window.dispatchEvent(new Event('blur')));await p.keyboard.up('ArrowUp');stopped=await target();await p.waitForTimeout(100);assert.deepEqual(await target(),stopped);
await p.locator('#settingsToggle').click();await p.locator('#buildTime').focus();start=await target();await p.keyboard.press('ArrowDown');await p.waitForTimeout(100);assert.deepEqual(await target(),start);await p.locator('#settingsToggle').click();
// Start at the mechanical realm while earlier progress is valid and retained.
const finished=Object.fromEntries([2,3,4,5].map(n=>[n,model.completeForced(model.initial(n)).values]));await p.evaluate(data=>localStorage.setItem('shengmeng-group-sudoku-campaign-v1',JSON.stringify({finished:data,boards:{}})),finished);await p.reload();await p.waitForFunction(()=>document.body.dataset.phase==='playing'&&__atlas.selected===4);assert.equal(await p.evaluate(()=>__atlas.boards[4].lift.position.y),.8);assert.equal(await p.locator('[data-board-cell]').count(),36);
await p.locator('#settingsToggle').click();await p.locator('#motion').uncheck();await p.locator('#settingsToggle').click();const gearBefore=await p.evaluate(()=>__atlas.rotating.filter(x=>x.object.userData.gearTrain).map(x=>x.object.rotation.y));await p.waitForTimeout(300);const gearAfter=await p.evaluate(()=>__atlas.rotating.filter(x=>x.object.userData.gearTrain).map(x=>x.object.rotation.y));assert(gearAfter[0]>gearBefore[0]&&gearAfter[1]<gearBefore[1]);
await p.setViewportSize({width:390,height:844});await p.waitForTimeout(1900);assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.screenshot({path:'/private/tmp/sudoku-mobile.png'});await p.locator('#language').click();assert.match(await p.locator('.sudoku-status').innerText(),/N\/S\/W\/E/);
assert.deepEqual(errors,[]);console.log('PASS: cardinal pan, key release, blur, Shift selection, form controls, assembly, meshing gears, mobile and bilingual hints');await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
