const {chromium}=require('playwright'),assert=require('node:assert/strict');
const model=require('../../../courses/abstract-algebra/2026-fall/lesson-1/associativity-sudoku.js');
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true}),p=await browser.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'}),errors=[];p.on('pageerror',e=>errors.push(e.message));const base=process.env.SUDOKU_TEST_URL||'http://127.0.0.1:8781/visuals/group-sudoku/';
// Test instrumentation stays outside production code.
await p.route('**/group-sudoku/app.mjs*',async r=>{const res=await r.fetch();await r.fulfill({response:res,body:(await res.text()).replace('world=new SudokuAtlas(canvas)','world=window.__atlas=new SudokuAtlas(canvas)')});});
await p.goto(base);await p.waitForFunction(()=>document.body.dataset.phase==='playing'&&window.__atlas);await p.locator('#loading').waitFor({state:'hidden'});assert.equal(await p.locator('.map-fallback').count(),0);
const radius=()=>p.evaluate(()=>__atlas.camera.position.distanceTo(__atlas.currentTarget));let start=await radius();await p.keyboard.down('ArrowUp');await p.waitForTimeout(650);await p.keyboard.up('ArrowUp');const near=await radius();assert(near<start*.85);await p.keyboard.down('ArrowDown');await p.waitForTimeout(400);await p.keyboard.up('ArrowDown');assert(await radius()>near);let stopped=await radius();await p.waitForTimeout(150);assert(Math.abs(await radius()-stopped)<.01);
await p.locator('[data-board-cell="0"]').focus();await p.keyboard.press('Shift+ArrowDown');assert.equal(await p.locator('[data-board-cell][aria-pressed="true"]').getAttribute('data-board-cell'),'2');start=await radius();await p.keyboard.down('ArrowUp');await p.waitForTimeout(200);await p.keyboard.up('ArrowUp');assert(await radius()<start);assert.equal(await p.locator('[data-board-cell][aria-pressed="true"]').getAttribute('data-board-cell'),'2');
await p.keyboard.down('ArrowUp');await p.waitForTimeout(100);await p.evaluate(()=>window.dispatchEvent(new Event('blur')));await p.keyboard.up('ArrowUp');stopped=await radius();await p.waitForTimeout(100);assert(Math.abs(await radius()-stopped)<.01);
await p.locator('#settingsToggle').click();await p.locator('[name=mapStyle]').first().focus();start=await radius();await p.keyboard.press('ArrowDown');await p.waitForTimeout(100);assert(Math.abs(await radius()-start)<.01);await p.locator('#settingsToggle').click();
// Start at the mechanical realm while earlier progress is valid and retained.
const finished=Object.fromEntries([2,3,4,5].map(n=>[n,model.completeForced(model.initial(n)).values]));await p.evaluate(data=>localStorage.setItem('shengmeng-group-sudoku-campaign-v1',JSON.stringify({finished:data,boards:{}})),finished);await p.reload();await p.waitForFunction(()=>document.body.dataset.phase==='playing'&&__atlas.selected===4);assert.equal(await p.evaluate(()=>__atlas.boards[4].lift.position.y),.8);assert.equal(await p.locator('[data-board-cell]').count(),36);
await p.locator('#settingsToggle').click();await p.locator('#motion').uncheck();await p.locator('#settingsToggle').click();const gearBefore=await p.evaluate(()=>__atlas.rotating.filter(x=>x.object.userData.gearTrain).map(x=>x.object.rotation.y));await p.waitForTimeout(300);const gearAfter=await p.evaluate(()=>__atlas.rotating.filter(x=>x.object.userData.gearTrain).map(x=>x.object.rotation.y));assert(gearAfter[0]>gearBefore[0]&&gearAfter[1]<gearBefore[1]);
await p.setViewportSize({width:390,height:844});await p.waitForTimeout(1900);assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.screenshot({path:'/private/tmp/sudoku-mobile.png'});await p.locator('#language').click();assert.match(await p.locator('.sudoku-status').innerText(),/Dolly/);
assert.deepEqual(errors,[]);console.log('PASS: dolly, key release, blur, Shift selection, form controls, assembly, meshing gears, mobile and bilingual hints');await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
