import test from 'node:test';
import assert from 'node:assert/strict';
import * as T from '../../3d/vendor/three.module.js';
import {analyseMusic} from '../music.mjs';
import {fountainHeight,installPalaceFountains,updatePalaceFountains} from '../palace-fountains.mjs';
import {compoundGearTrain,crankSlider,clockworkCity,updateClockwork} from '../clockwork.mjs';
import {AtlasScene} from '../../test-module/scene.mjs';
import {batchBuiltDomain} from '../static-batches.mjs';
function builder(){const a=Object.create(AtlasScene.prototype);a.materials=Object.fromEntries(['stone','paper','dark','gold','wood','jade','brass','red'].map(n=>[n,new T.MeshStandardMaterial()]));a.rotating=[];a.detailMotion=[];return a;}
test('actual audio amplitude and bass alter bounded fountain height; silence is a calm base',()=>{const silence=analyseMusic(new Float32Array(512),new Uint8Array(256));assert.deepEqual(silence,{energy:0,bass:0});const spectrum=new Uint8Array(256);spectrum.fill(200,1,4);const strong=analyseMusic(Float32Array.from({length:512},(_,i)=>Math.sin(i*.2)*.2),spectrum);assert.ok(strong.energy>.5&&strong.bass>.5);assert.ok(fountainHeight('crown',strong.energy,strong.bass)>fountainHeight('crown',0,0)+1);const a=builder(),p=new T.Group();installPalaceFountains(a,p);assert.equal(a.palaceFountains.jets.length,26);updatePalaceFountains(a.palaceFountains,3,strong,false,true);for(const j of a.palaceFountains.jets)assert.ok([...j.line.geometry.attributes.position.array].every(Number.isFinite));updatePalaceFountains(a.palaceFountains,7,strong,true,true);const frozen=a.palaceFountains.jets[0].line.geometry.attributes.position.array.slice();updatePalaceFountains(a.palaceFountains,50,strong,true,true);assert.deepEqual(a.palaceFountains.jets[0].line.geometry.attributes.position.array,frozen);assert.equal(a.palaceFountains.jets[0].particles.visible,false);});
test('all branch gear contacts match pitch distance and tangential speed',()=>{const gears=compoundGearTrain();assert.equal(gears.length,25);for(const g of gears){if(g.parent===null)continue;const parent=gears[g.parent];assert.ok(Math.abs(Math.hypot(g.x-parent.x,g.z-parent.z)-g.radius-parent.radius)<1e-9);assert.ok(Math.abs(g.radius*g.speed+parent.radius*parent.speed)<1e-9);}});
test('crank rods keep constant length; piston and hoist survive static batching',()=>{for(let t=0;t<Math.PI*2;t+=.05){const q=crankSlider(t);assert.ok(Math.abs(Math.hypot(q.x,q.slider-q.y)-1.8)<1e-9);}const a=builder(),p=new T.Group();clockworkCity(a,p);const board={content:p,lift:new T.Group(),glow:new T.Group()};batchBuiltDomain(a,board);for(const m of a.machineMotion)m.root.traverse(o=>assert.ok(!board.batchedSources.includes(o)));updateClockwork(a.machineMotion,0,false);const lift=a.machineMotion.find(m=>m.kind==='hoist').root;const before=lift.position.y;updateClockwork(a.machineMotion,4,false);assert.ok(lift.position.y>before+1);updateClockwork(a.machineMotion,100,true);assert.equal(lift.position.y,.65);});
