import {nodes,statusLabels} from './graph-data.js?v=20261001-formal-1';
const byId = new Map(nodes.map(n=>[n.id,n]));
const graph=document.querySelector('#graph'), svg=document.querySelector('#edges');
const safe=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let selected='proper',history=[],step=0,activeTab='overview',snapshot=null;
function closure(id,out=new Set()){if(out.has(id))return out;out.add(id);byId.get(id).deps.forEach(d=>closure(d,out));return out;}
function depButton(n){return `<button class="dep-link" data-select="${n.id}">${safe(n.title)}<span class="${n.status}">${statusLabels[n.status]}</span></button>`;}
nodes.forEach(n=>{const b=document.createElement('button');b.type='button';b.className=`node ${n.status}`;b.style.left=n.x+'px';b.style.top=n.y+'px';b.dataset.node=n.id;b.setAttribute('aria-pressed','false');b.innerHTML=`<b>${safe(n.title)}</b><small class="${n.status}">${statusLabels[n.status]}</small>`;b.addEventListener('click',()=>select(n.id));graph.append(b);});
svg.innerHTML='<defs><marker id="arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse"><path d="M 0 0 L 10 5 L 0 10 z" fill="#7997a3"/></marker></defs>';
nodes.forEach(n=>n.deps.forEach(id=>{const d=byId.get(id),p=document.createElementNS('http://www.w3.org/2000/svg','path');let x1=d.x+232,y1=d.y+43,x2=n.x,y2=n.y+43;if(d.x===n.x){x1=d.x+116;y1=d.y+87;x2=n.x+116;y2=n.y;}
const bend=Math.max(40,Math.abs(x2-x1)*.45);p.setAttribute('d',`M${x1},${y1} C${x1+bend},${y1} ${x2-bend},${y2} ${x2},${y2}`);p.setAttribute('marker-end','url(#arrow)');p.classList.add('edge');if(d.status==='assumption')p.classList.add('assumed');p.dataset.from=id;p.dataset.to=n.id;svg.append(p);}));
function paint(){const scope=document.querySelector('#scope').value,chain=closure(selected);graph.querySelectorAll('.node').forEach(b=>{const n=byId.get(b.dataset.node);b.setAttribute('aria-pressed',String(n.id===selected));const dim=scope==='path'?!chain.has(n.id):scope==='open'?!['assumption','pending'].includes(n.status):false;b.classList.toggle('dimmed',dim);});svg.querySelectorAll('.edge').forEach(p=>{const on=chain.has(p.dataset.from)&&chain.has(p.dataset.to);p.classList.toggle('active',on);p.style.display=scope==='open'?'none':'';p.style.opacity=scope==='path'&&!on?'0':'';});document.querySelector('#back').disabled=!history.length;}
function sourcePanel(n){const el=document.querySelector('#sourcePanel');if(!n.decl){el.innerHTML='<p class="notice">此节点尚无完成的 Lean 几何证明。图中的中文论证不能替代形式化验证。</p><a class="button" href="#paper-'+n.paper+'">阅读原始证明 →</a>';return;}
if(!snapshot){el.innerHTML='<p>正在读取源码快照…</p>';return;}
const source=snapshot.declarations[n.decl];if(!source){el.innerHTML='<p class="error">缺少对应源码，不能展示验证标记。</p>';return;}
el.innerHTML=`<div class="source-name">Negativity.${safe(n.decl)}</div><p class="text-small">${safe(source.path)} · 第 ${source.line} 行</p><div class="actions"><a class="button small" href="source/${safe(source.path)}" download>下载源码</a><a class="button small" href="https://github.com/birationalclass/shengmeng/blob/main/formalization/negativity/source/${safe(source.path)}#L${source.line}" target="_blank" rel="noopener">GitHub 定位 ↗</a></div><pre class="source-code"><code>${source.code.split('\n').map((l,i)=>`<span class="source-line"><em>${i+source.line}</em>${safe(l)}</span>`).join('')}</code></pre><p>参数假设请看定理完整类型。依赖仅含 Lean 常用基础公理，不意味着这些参数假设已从几何得到证明。</p>`;}
function renderStep(){const n=byId.get(selected),s=n.steps[step];document.querySelector('#stepsPanel').innerHTML=`<p class="text-small">${n.decl?'已验证源码的阅读导览':'原始数学证明 / 待完成计划'} · 非实时 Lean 执行</p><div class="stepper"><button class="button small" id="prevStep" ${step===0?'disabled':''}>← 上一步</button><span>${step+1} / ${n.steps.length}</span><button class="button small" id="nextStep" ${step===n.steps.length-1?'disabled':''}>下一步 →</button></div><div class="step-body"><h3>${safe(s[0])}</h3><p>${safe(s[1])}</p>${s[2]?`<div class="step-code">${safe(s[2])}</div>`:''}</div><a class="text-button" href="#paper-${n.paper}">对应原始证明 ↘</a>`;document.querySelector('#prevStep').onclick=()=>{step--;renderStep();};document.querySelector('#nextStep').onclick=()=>{step++;renderStep();};}
function renderDetail(){const n=byId.get(selected);document.querySelector('#detailHeader').innerHTML=`<span class="pill ${n.status}">${statusLabels[n.status]}</span><h2>${safe(n.title)}</h2><p class="statement">${safe(n.statement)}</p><p>${safe(n.scope)}</p>`;
const unfinished=[...closure(selected)].map(id=>byId.get(id)).filter(n=>n.status==='assumption');
document.querySelector('#overviewPanel').innerHTML=`<h3>为了得到这个结论，先需要</h3><div class="dep-list">${n.deps.length?n.deps.map(id=>depButton(byId.get(id))).join(''):'<p class="empty">没有其他项目节点；使用 mathlib 基础与下列明确输入。</p>'}</div><h3>${n.status==='assumption'?'尚需建立的几何内容':'当前输入 / 假设'}</h3><ul>${n.inputs.map(s=>`<li>${safe(s)}</li>`).join('')}</ul>${unfinished.length?`<h3>沿这条路径，仍需承认的几何输入 · ${unfinished.length}</h3><p class="notice">琥珀色表示显式假设或待补的几何桥接，不是代码中的新增 axiom。</p><div class="dep-list">${unfinished.map(depButton).join('')}</div>`:'<p class="empty">本模型层没有未证明的几何依赖；其参数条件仍须满足。</p>'}<h3>接下来哪些结论使用它</h3><div class="dep-list">${nodes.filter(m=>m.deps.includes(n.id)).map(depButton).join('')||'<span class="text-small">这是当前图谱的最终目标。</span>'}</div>`;
renderStep();sourcePanel(n);paint();}
function select(id,record=true){if(!byId.has(id))return;if(record&&id!==selected)history.push(selected);selected=id;step=0;window.history.replaceState(null,'',`#node=${id}`);renderDetail();if(matchMedia('(max-width:1100px)').matches)document.querySelector('#detail').scrollIntoView({behavior:'smooth',block:'start'});}
document.addEventListener('click',e=>{const b=e.target.closest('[data-select]');if(b)select(b.dataset.select);});
document.querySelector('#back').onclick=()=>{if(history.length)select(history.pop(),false);};document.querySelector('#scope').onchange=paint;
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{activeTab=b.dataset.tab;document.querySelectorAll('[data-tab]').forEach(t=>t.setAttribute('aria-selected',String(t===b)));['overview','steps','source'].forEach(t=>document.querySelector('#'+t+'Panel').hidden=t!==activeTab);});
document.querySelector('#expandGraph').onclick=e=>{const expanded=document.querySelector('.atlas').classList.toggle('expanded');e.currentTarget.setAttribute('aria-pressed',String(expanded));e.currentTarget.textContent=expanded?'恢复分栏':'展开图谱';};
document.querySelector('.pdf-view').addEventListener('toggle',e=>{const f=e.currentTarget.querySelector('iframe');if(e.currentTarget.open&&!f.src)f.src=f.dataset.src;});
if(location.hash.startsWith('#node=')){const id=location.hash.slice(6);if(byId.has(id))selected=id;}
renderDetail();
fetch('snapshot.json?v=20261001-formal-1').then(r=>{if(!r.ok)throw new Error('HTTP '+r.status);return r.json();}).then(data=>{snapshot=data;sourcePanel(byId.get(selected));document.querySelector('#evidenceContent').innerHTML=`<div class="evidence-grid"><div><b>lake build ✓</b><small>当前源码快照 · 本地验证</small></div><div><b>8 个核心定理</b><small>公理检查无 sorryAx</small></div><div><b>${safe(data.checkedAt)}</b><small>验证日期 · 中国标准时间</small></div></div><p>Lean <code>${safe(data.lean)}</code> · mathlib <code>${safe(data.mathlib.slice(0,12))}</code></p><p>公理依赖：<code>propext · Classical.choice · Quot.sound</code>。没有新增几何公理；未完成内容仍是显式参数或规划节点。</p><div class="actions"><a class="button" href="verification.txt">完整验证日志 ↗</a><a class="button" href="snapshot.json">源码 SHA-256 清单 ↗</a><a class="button" href="source/CheckAxioms.lean">公理检查脚本 ↗</a></div><details><summary>公开源码的指纹</summary><ul class="evidence-list">${data.files.map(f=>`<li><a href="source/${safe(f.path)}">${safe(f.path)}</a><br><code>${safe(f.sha256)}</code></li>`).join('')}</ul></details>`;}).catch(err=>{document.querySelector('#evidenceContent').innerHTML='<p class="error">验证记录加载失败，请刷新或下载工程核查。</p>';document.querySelector('#sourcePanel').innerHTML='<p class="error">源码快照加载失败。</p>';console.error(err);});
