// This is a mathematical commutative square, independent of the graph camera.
export function curveDiagramPanel(node, english) {
  if (!['projection', 'pullbackdiagram'].includes(node.id)) return '';
  const title = english ? 'Restrict to the curve: the commutative square' : '限制到曲线：交换图';
  const label = english ? 'Γ maps into X′; C maps into X; h and π make the square commute.' : 'Γ 嵌入 X′，像曲线 C 嵌入 X；h 与 π 构成交换图。';
  return `<section class="curve-diagram-panel">
    <h3>${title}</h3>
    <p>${english ? 'For a curve image C=π(Γ), h=π|Γ and π∘i=j∘h.' : '当 C=π(Γ) 是曲线时，h=π|Γ，且 π∘i=j∘h。'}</p>
    <svg class="curve-square" viewBox="0 0 320 165" role="img" aria-label="${label}">
      <defs><marker id="curve-square-arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse"><path d="M 0 0 L 10 5 L 0 10 z" fill="currentColor"/></marker></defs>
      <g fill="none" stroke="currentColor" stroke-width="1.5" marker-end="url(#curve-square-arrow)">
        <path d="M 67 30 H 253"/><path d="M 67 139 H 253"/>
        <path d="M 43 52 V 115"/><path d="M 278 52 V 115"/>
      </g>
      <g fill="currentColor" text-anchor="middle" class="curve-square-objects"><text x="43" y="38">Γ</text><text x="278" y="38">X′</text><text x="43" y="147">C</text><text x="278" y="147">X</text></g>
      <g fill="currentColor" text-anchor="middle" class="curve-square-maps"><text x="160" y="22">i</text><text x="160" y="130">j</text><text x="24" y="88">h</text><text x="299" y="88">π</text></g>
    </svg>
    <div class="formula">i<sup>*</sup>π<sup>*</sup>𝒪<sub>X</sub>(D) ≅ h<sup>*</sup>j<sup>*</sup>𝒪<sub>X</sub>(D)</div>
    <p>${english ? 'The chosen route defines degree directly by Cartier local orders on the normalization. The displayed global projection equalities below remain goals.' : '采用的路线是在正规化上直接求 Cartier 局部阶数。下方显示的全局投影等式仍是待证明目标。'}</p>
    <div class="formula">(π<sup>*</sup>D) · Γ = deg(h<sup>*</sup>L)</div>
    <div class="formula">D · π<sub>*</sub>[Γ] = [k(Γ):k(C)] deg(L)</div>
    <ol class="curve-proof-stages">
      <li class="curve-stage-done"><span>✓</span><div><b>${english ? 'Pullback around the square: verified' : '交换图的拉回同构：已验证'}</b><p>${english ? 'Actual Scheme modules; only the commutativity of the square is required.' : '使用真实 Scheme 模层，只要求上面的交换关系。'}</p><button class="text-button" data-select="pullbackdiagram">${english ? 'Read the Lean proof →' : '查看 Lean 证明 →'}</button></div></li>
      <li class="curve-stage-done"><span>✓</span><div><b>${english ? 'Point divisors and multiplicity: verified' : '点除子与重数计数：已验证'}</b><p>m<sub>q</sub> = length(𝒪<sub>Γ,q</sub> ⊗<sub>𝒪<sub>C,p</sub></sub> k(p))<br>Σ m<sub>q</sub>[k(q):k] = r[k(p):k].</p><button class="text-button" data-select="pointtensor">${english ? 'Point pullback and counting proof →' : '点拉回与计数证明 →'}</button></div></li>
      <li class="curve-stage-done"><span>✓</span><div><b>${english ? 'Finite signed divisors: verified' : '有限带符号除子：已验证'}</b><div class="formula">deg(h<sup>*</sup>D) = [L:K] deg(D)</div><p>${english ? 'Actual tensor lengths extend by additivity. Principal pullback, support and effectivity are proved. Over an algebraically closed field the multiplicity sum is [L:K], including inseparable degree.' : '实际张量长度经可加性延伸；主除子拉回、支撑及有效性已证明。代数闭域下重数总和为 [L:K]，包含不可分次数。'}</p><button class="text-button" data-select="affinedivisor">${english ? 'Read the finite-divisor proof →' : '查看有限除子的证明 →'}</button></div></li>
      <li class="curve-stage-done"><span>✓</span><div><b>${english ? 'Norm/valuation product formula: verified' : '范数／赋值乘积公式：已验证'}</b><p>${english ? 'Actual integral closures, their finiteness, normalized infinity orders and norm/divisor identities are constructed in arbitrary characteristic with a separable parameter. Infinity residue fields and uniform base-field weights are now proved. All finite/infinity primes are now exhaustively and disjointly classified, and the sum is transported to actual curve closed-point orders with an explicit compatible finite separable parameter.' : '任意特征下，以可分参数构造实际整闭包、有限性、归一化无穷远阶数及范数主除子等式。无穷远剩余域与统一底域权重现已证明；全部有限／无穷远素点现已完整且互斥地分类，并在显式相容有限可分参数下搬运到实际曲线闭点的阶数总和。'}</p><button class="text-button" data-select="functionproduct">${english ? 'Read the norm/valuation proof →' : '查看范数／赋值证明 →'}</button></div></li>
      <li class="curve-stage-done"><span>✓</span><div><b>${english ? 'Actual Cartier restriction and moving: verified' : '真实 Cartier 限制与移动：已验证'}</b><p>${english ? 'Use actual generic stalk units without assuming dominance. Effective restrictions have nonnegative order sum, positive on meeting support. Principal moving constructs restriction even for a curve in the original support. Principal-move degree invariance is now proved on the actual proper normal curve, without an extra parameter input.' : '使用真实泛点 stalk 单位，不假定 dominant。有效限制阶数和非负，相交则严格正。主除子移动为原来包含在支撑中的曲线也构造限制；主除子移动的次数不变现已在实际 proper 正规曲线上证明，相容有限可分参数现已从实际曲线构造。'}</p><button class="text-button" data-select="cartiercurve">${english ? 'Read the Cartier-order proof →' : '查看 Cartier 阶数证明 →'}</button></div></li>
      <li class="curve-stage-done"><span>✓</span><div><b>${english ? 'Hartshorne I.6: actual centers and orders verified' : 'Hartshorne I.6：真实中心及阶数已验证'}</b><p>${english ? 'Construct unique centers of actual function-field valuation rings on the proper normal curve. Actual closed-point DVRs give the inverse bijection, and the actual stalk isomorphisms preserve every rational local order. The finite/infinity classification and actual total-sum transport are now proved. The parameter and actual proper normal-curve Cartier pullback degree are proved; actual nonnormal source normalization and real-presentation independence are proved; actual nonnormal-target lifting is proved; restriction compatibility and cycle identification remain open.' : '在实际 proper 正规曲线上构造函数域赋值环的唯一中心；实际闭点 DVR 构造反向双射，真实 stalk 同构保持每个有理函数的局部阶数。有限／无穷远素点分类及实际全部点求和现已证明；相容可分参数现已从实际曲线构造；完整曲线 Cartier 次数公式、点像零值与移动选择无关均已完成；非正规源曲线的实际正规化与实表示独立性均已证明；实际非正规目标的正规化提升已经完成；还需限制相容性和 cycle 识别。'}</p><button class="text-button" data-select="curveplaces">${english ? 'Read the actual curve-point proof →' : '查看实际曲线闭点证明 →'}</button></div></li>
      <li class="curve-stage-done"><span>✓</span><div><b>${english ? 'Actual principal degree and Cartier moving: verified' : '实际主除子次数与 Cartier 移动：已验证'}</b><p>${english ? 'Every actual curve closed point occurs exactly once. Its coefficient is the actual normalized DVR order, the principal sum is zero, and principal Cartier moving preserves degree. The compatible finite separable parameter is now constructed from actual one-dimensional finite-type Scheme geometry; the final curve theorem has no parameter input.' : '每个实际曲线闭点恰好出现一次，其系数等于真实归一化 DVR 阶数；主除子阶数总和为零，Cartier 主除子移动次数不变。相容参数已从实际曲线构造，无需额外参数输入。'}</p><button class="text-button" data-select="curveprincipal">${english ? 'Read the actual curve-degree theorem →' : '查看实际曲线次数定理 →'}</button></div></li>
      <li class="curve-stage-done"><span>✓</span><div><b>${english ? 'Proper normal-curve Cartier degree: verified' : 'proper 正规曲线 Cartier 次数：已验证'}</b><div class="formula">deg(h<sup>*</sup>D) = [k(Γ):k(C)] deg(D)</div><p>${english ? 'Actual proper dominant complete normal curves now satisfy global Cartier pullback degree, including inseparable degree. Finiteness, all actual fiber points and local equations are derived. Choice-independent actual Cartier intersection, point-image zero and effective-divisor signs are now proved. Ambient pullback composition and arbitrary real-presentation independence are proved. Actual source normalization is proved; actual nonnormal-target lifting is proved; local restriction compatibility and actual image-curve/cycle identification remain open. The full ambient projection formula is unfinished.' : '实际 proper dominant 完整正规曲线的全局 Cartier 拉回次数已证明，包含不可分次数；有限性、全部实际纤维点和局部方程均已导出。选择无关的实际 Cartier 交数、点像零值及有效除子正性现已完成；拉回复合相容性和任意实表示独立性已证明；实际源曲线正规化已完成；已完成非正规目标的提升；尚缺限制相容性与 cycle 识别，完整环境投影公式仍未完成。'}</p></div></li>
      <li class="curve-stage-done"><span>✓</span><div><b>${english ? 'Actual intersection and contracted-curve zero: verified' : '真实交数与压缩曲线零值：已验证'}</b><p>${english ? 'Construct Cartier intersection by actual local orders. Any two permitted ambient moves give equal degree; if the actual image is one point, the intersection is zero. The proper dominant normal-curve degree formula is now connected to this same definition.' : '由真实局部阶数构造 Cartier 交数；任意两次合法环境移动给出同一次数，实际像为点时交数为零。proper dominant 正规曲线的次数倍公式也已接入这个交数定义。'}</p><button class="text-button" data-select="actualintersection">${english ? 'Read the actual intersection theorem →' : '查看真实交数定理 →'}</button></div></li>
      <li class="curve-stage-done"><span>✓</span><div><b>${english ? 'Actual real intersection and ambient pullback: verified' : '真实实交数与环境拉回：已验证'}</b><p>${english ? 'Integer additivity, independence under arbitrary real Cartier presentations and affine covers, effective real-divisor signs, and genuine ambient pullback composition are now proved. Actual normalization is now constructed. Actual lifting is proved. Restriction compatibility and cycle identification remain required for the full ambient projection formula.' : '整数可加性、任意实 Cartier 生成元与仿射覆盖的表示独立性、有效实除子正性和真实环境拉回复合均已证明；实际正规化现已构造；实际提升已完成；完整环境投影公式仍需限制相容性及 cycle 识别。'}</p><button class="text-button" data-select="realpresentation">${english ? 'Read the actual real-presentation proof →' : '查看真实实表示证明 →'}</button></div></li>
      <li class="curve-stage-done"><span>✓</span><div><b>${english ? 'Actual finite normalization and nonnormal-source degree: verified' : '实际有限正规化与非正规源次数：已验证'}</b><p>${english ? 'Actual normalization is finite, birational, normal and surjective. Intersection, real-presentation independence and signs now include nonnormal complete source curves. The degree formula to a normal target uses the original full function-field degree; actual lifting to nonnormal target normalizations is proved; restriction compatibility and cycle identification remain open.' : '实际正规化有限、双有理、正规且满射。真实交数、实表示独立与正性已包含非正规完整整源曲线；到正规目标的次数公式使用原函数域的全次数。非正规目标的实际提升已完成；沿提升的限制相容性与 cycle 识别仍待完成。'}</p><button class="text-button" data-select="curvenormalization">${english ? 'Read actual normalization →' : '查看实际正规化证明 →'}</button></div></li>
      <li class="curve-stage-done"><span>✓</span><div><b>${english ? 'Actual normalization lift and full degree invariant: verified' : '实际正规化提升与全次数不变：已验证'}</b><p>${english ? 'Both original curves may be nonnormal. Construct the actual finite dominant lift, prove its commuting square, and identify the full function-field degrees, including inseparable maps. Local restriction compatibility and image-cycle identification remain open.' : '两条原曲线都可非正规。实际有限 dominant 提升、交换图及全函数域次数不变都已证明，包含不可分映射。局部限制相容性与像曲线 cycle 识别仍待完成。'}</p><button class="text-button" data-select="curvenormalizationlift">${english ? 'Read the actual commuting square →' : '查看实际交换图证明 →'}</button></div></li>
    </ol>
  </section>`;
}
