export const statusLabels = {done:'✓ 模型内已验证',conditional:'◐ 条件式已验证',assumption:'◇ 暂作假设',pending:'○ 待完成目标'};
export const nodes = [
{id:'max',title:'有限系数 · 最大比值',status:'done',x:20,y:60,deps:[],decl:'exists_effective_shift',file:'Numerical.lean',paper:'projective',statement:'存在 e > 0，使 d + e·a 逐项非负，并在某个原负系数位置等于零。',scope:'有限支撑实系数模型。已证明全部有限最大值论证；不要求指标类型本身有限。',inputs:['a 的所有系数非负。','若 dᵢ < 0，则 aᵢ > 0；d 存在负系数。'],steps:[['构造有限负支撑','从 d 的有限支撑筛选 dᵢ < 0 的指标。','let s := d.support.filter (fun i => d i < 0)'],['取得最大比值','在有限非空集合上选取 −dᵢ/aᵢ 的最大值。','s.exists_max_image (fun i => -d i / a i) hs'],['证明逐项非负','负项使用最大值不等式；非负项使用 e > 0 与 aᵢ ≥ 0。','(div_le_iff₀ hai).mp hle'],['找到归零分量','最大比值对应的指标 j 满足 dⱼ + e·aⱼ = 0。','div_mul_cancel₀']]},
{id:'least',title:'最小有效平移量',status:'done',x:278,y:60,deps:['max'],decl:'exists_least_effective_shift',file:'Coefficients.lean',paper:'projective',statement:'对所有 t ≥ 0，d+t·a 有效，当且仅当 e ≤ t。',scope:'强化已验证的系数引理：不仅存在可行 e，而且它是有效平移的阈值。',inputs:['与最大比值引理相同的系数条件。'],steps:[['复用最大比值引理','取得 e、有效性与归零指标 j。','exists_effective_shift d a ha hcover hneg'],['证明必要性','若 d+t·a 有效，用 j 处的等式和 aⱼ > 0 推得 e ≤ t。','nlinarith'],['证明充分性','t ≥ e 且 aᵢ ≥ 0，所以 d+t·a 的每项至少为 d+e·a。','mul_le_mul_of_nonneg_right hle (ha i)']]},
{id:'push',title:'系数推出保持有效',status:'done',x:20,y:175,deps:[],decl:'effective_push',file:'Coefficients.lean',paper:'projective',statement:'给定单射 strict : J → I，取 strict(j) 处的系数定义推出；非负系数仍非负。',scope:'真正实现了有限支撑系数的推出模型。它与概形 cycle 推出的对应还需要几何桥接。',inputs:['strict 是单射，代表底上分量的严格变换。','输入系数向量有效。'],steps:[['定义系数推出','用 Finsupp.comapDomain 沿 strict 读取系数。','birationalPush strict hinj d'],['逐项验证','对每个 j，所需非负性就是 d 在 strict(j) 处的非负性。','exact hd (strict j)']]},
{id:'negative',title:'负系数 ⇒ exceptional',status:'done',x:278,y:175,deps:['push'],decl:'negative_is_exceptional',file:'Coefficients.lean',paper:'projective',statement:'系数推出有效时，任何负系数指标都不在 strict 的像中。',scope:'ExceptionalIndex 的定义是“不在 strict 像中”。尚未把这个定义认同为概形上的 exceptional prime divisor。',inputs:['系数推出有效。','所选系数 dᵢ < 0。'],steps:[['假设不是 exceptional','若 i = strict(j)，其系数等于推出在 j 处的系数。','rintro ⟨j, rfl⟩'],['非负与负矛盾','推出有效给 dᵢ ≥ 0，与给定负系数矛盾。','(not_lt_of_ge (hpush j)) hi']]},
{id:'antiample',title:'E 的存在性',status:'assumption',x:20,y:290,deps:[],paper:'antiample',statement:'在仿射底上构造有效 Cartier 除子 E，使 −E 相对 ample。',scope:'原稿 Lemma 1.1；当前尚未形式化截面、Cartier 除子与相对 ample 的这条构造链。',inputs:['待建设：O(−A)、直接像与仿射底上的非零截面。','当前定理参数中只给定 E 和 hE、hanti；并未证明这样的 E 存在。'],steps:[['选 ample 除子','由 projective 取 f-ample Cartier 除子 A。'],['寻找截面','f∗O(−A) 泛秩为一，仿射底上取非零全局截面 s。'],['定义 E','令 E = −A + div(s)，有效且 −E ∼ A。']]},
{id:'strict',title:'几何严格变换与 cycle 推出',status:'assumption',x:20,y:410,deps:[],paper:'projective',statement:'把 strict 单射、ExceptionalIndex 与实际双有理态射的严格变换、exceptional prime 和 cycle 推出对应起来。',scope:'系数模型已定义；这一几何一致性还没有证明。',inputs:['正规双有理态射在余维一处的性质。','实际 cycle 推出系数与严格变换系数的一致性。'],steps:[['构造严格变换','给底上每个素除子指定唯一的非 exceptional 严格变换。'],['核对推出系数','证明函数域次数和维数条件给出当前的系数推出模型。']]},
{id:'cover',title:'exceptional 点的曲线覆盖',status:'assumption',x:20,y:530,deps:[],paper:'support',statement:'exceptional locus 中的点位于被 f 压缩的完整曲线上。',scope:'需要正规底上的同构判据、正维射影纤维和曲线存在性。当前为显式覆盖假设。',inputs:['Zariski 主定理的相关推论。','正维射影纤维中经过点的曲线。'],steps:[['识别非准有限处','正规底上的 proper birational 映射在准有限处是同构。'],['取纤维内曲线','在正维射影纤维中取经过给定点的曲线。']]},
{id:'intersection',title:'真实交数与正性接口',status:'assumption',x:20,y:650,deps:[],paper:'projective',statement:'把线性泛函解释成 D·C，并证明 nef、ample、有效性给出的交数符号。',scope:'目前的 intersection 是给定的线性映射；没有从 Cartier 除子和曲线定义构造它。',inputs:['−D nef ⇒ D·C ≤ 0；−E ample ⇒ E·C < 0。','有效 B 且 C 不在支撑内 ⇒ B·C ≥ 0。','若还相交 ⇒ B·C > 0。'],steps:[['构造交数','定义 Cartier/R-Cartier 除子在曲线上的次数并证明线性。'],['接通符号','证明相对正性和支撑条件蕴含所需非负或严格负不等式。']]},
{id:'curves',title:'在归零分量中找到曲线',status:'assumption',x:20,y:770,deps:[],paper:'projective',statement:'exceptional 分量 F 在 B 中系数为零时，存在 F 中不被 Supp B 包含的压缩曲线。',scope:'当前用 hcurve 明确表达曲线存在，用 hinter 单独表达交数非负。',inputs:['素分量与支撑、闭点及曲线的几何关系。'],steps:[['选择支撑外的点','取 x ∈ F ∖ Supp B。'],['选择压缩曲线','取 F 中经过 x 的压缩曲线 C，于是 C 不包含在 Supp B 中。']]},
{id:'connected',title:'连通纤维与相交曲线',status:'assumption',x:20,y:890,deps:[],paper:'fiber',statement:'若纤维与支撑相交却不被包含，可找到纤维内与支撑相交但不被其包含的曲线。',scope:'不能只靠一般拓扑连通性断言曲线存在。Stein 分解及射影几何部分尚未接入。',inputs:['正规底上的 proper birational 映射的连通纤维。','连通射影纤维中的曲线存在引理。'],steps:[['连通性','由 Stein 分解得到几何连通纤维。'],['找到跨越支撑的曲线','先找到遇到支撑但不被包含的分量，再在其中取曲线。']]},
{id:'support',title:'支撑包含的条件式证明',status:'conditional',x:278,y:290,deps:['cover','intersection'],decl:'exceptional_subset_support',file:'Interfaces.lean',paper:'support',statement:'由曲线覆盖与交数符号推出 exc ⊆ supp。',scope:'Lean 验证的是集合与实数不等式层的推导；覆盖和交数符号仍是参数。',inputs:['hcover：每个 exceptional 点位于一条测试曲线上。','hanti：测试曲线的 degree < 0。','hnonneg：曲线不包含在 supp 中则 degree ≥ 0。'],steps:[['经过每个点取曲线','对 x ∈ exc，由覆盖取 C 经过 x。','hcover x hx'],['曲线必须在支撑内','否则得到 degree C ≥ 0，与 degree C < 0 矛盾。','(not_lt_of_ge (hnonneg c h)) (hanti c)'],['回到原点','x 位于该曲线，因而位于 supp。','exact hsub hc']]},
{id:'core',title:'数值 negativity 核心',status:'conditional',x:278,y:530,deps:['max','antiample','support','curves','intersection'],decl:'effective_of_curve_tests',file:'Numerical.lean',paper:'projective',statement:'给定 E 的系数与曲线交数条件，反证法推出 D 的所有系数非负。',scope:'所有曲线、线性映射与符号条件均出现在定理参数中。此处的几何依赖边表示这些参数的预期来源。',inputs:['hE、hcover：E 有效，且在 D 的负系数位置严格为正。','hnef、hanti：交数符号。','hcurve：归零的负分量可提供非负交数测试。'],steps:[['反设 D 不有效','调用最大比值引理得到 e、有效平移及归零分量。','exists_effective_shift'],['测试有效平移','由显式曲线假设得到 C，使 (D+eE)·C ≥ 0。','hcurve (D + e • E) j'],['线性展开得到矛盾','线性给 D·C + e(E·C)，而两项之和严格小于零。','simp only [map_add, map_smul, smul_eq_mul] at hc; linarith']]},
{id:'iff',title:'有效 ⇔ 推出有效',status:'conditional',x:536,y:175,deps:['negative','core'],decl:'effective_iff_push_effective',file:'Interfaces.lean',paper:'projective',statement:'在 strict 系数模型与明确的曲线接口下，D 有效当且仅当其推出有效。',scope:'本页主要已验证结果。它不是已完成的概形版 projective negativity lemma。',inputs:['strict 与 hinj；coeff 和 intersection 两个线性接口。','hE、hcover、hnef、hanti。','hcurve：存在避开支撑的测试曲线；hinter：其交数非负。'],steps:[['正向：推出保持有效','逐项应用 effective_push。','exact effective_push strict hinj'],['反向：负系数为 exceptional','用推出有效导出负指标不在 strict 的像中。','negative_is_exceptional strict hinj hpush hi'],['把曲线接口接到数值定理','先用 hcurve 取曲线，再用 hinter 得非负交数，应用数值核心。','effective_of_curve_tests; exact ⟨c, hinter B c hB hc⟩']]},
{id:'projective',title:'真正的 projective 版本 (1)',status:'pending',x:536,y:410,deps:['iff','strict','antiample','intersection','curves','support'],paper:'projective',statement:'对正规簇间 projective birational f 和 −D 相对 nef 的 R-Cartier 除子：D ≥ 0 ⇔ f∗D ≥ 0。',scope:'完整几何陈述尚未成为本项目中的 Lean 定理。',inputs:['需将所有模型接口实例化为实际代数几何对象。'],steps:[['构造几何对象','定义或接入 Cartier 除子、cycle 系数和实际交数。'],['消除琥珀色输入','逐项证明 strict、E、曲线与交数假设。'],['应用条件式定理','实例化已验证的 effective_iff_push_effective。']]},
{id:'fiber',title:'纤维二择一的条件式证明',status:'conditional',x:278,y:770,deps:['connected','intersection'],decl:'fiber_support_dichotomy',file:'Interfaces.lean',paper:'fiber',statement:'纤维与支撑不相交，或者整个纤维包含于支撑。',scope:'集合层的反证推导已验证。曲线存在和严格正交数尚未从几何证明。',inputs:['hcurve：部分相交时存在适当的纤维内曲线。','hpositive：相交但不包含支撑给正 degree。','hnef：纤维内曲线的 degree ≤ 0。'],steps:[['区分相交与否','不相交时直接结束。','by_cases hmeet : (fiber ∩ supp).Nonempty'],['反设不被支撑包含','调用 hcurve 取得相交但不被包含的曲线。','hcurve hmeet hsub'],['正交数与 nef 矛盾','同一条曲线的 degree 既 > 0 又 ≤ 0。','(not_lt_of_ge (hnef c hcf)) (hpositive c hcmeet hcs)']]},
{id:'projective2',title:'真正的纤维支撑结论 (2)',status:'pending',x:536,y:650,deps:['fiber','connected','intersection'],paper:'fiber',statement:'对有效 D，f 的每个纤维要么不遇到 Supp D，要么包含于其中。',scope:'还需把集合模型中的 fiber、supp、curve、degree 解释为实际几何对象。',inputs:['真实纤维、支撑和曲线的接口桥接。'],steps:[['接通几何输入','证明连通纤维中的曲线存在及严格正交数。'],['实例化条件式结论','应用 fiber_support_dichotomy。']]},
{id:'chow',title:'Chow 改造与推拉下降',status:'assumption',x:278,y:930,deps:[],paper:'proper',statement:'用正规化的 Chow 改造转到 projective，并用交数与支撑的推拉公式下降。',scope:'相对 Chow 引理与需要的推拉公式尚未形式化。',inputs:['正规 projective 改造存在性。','π∗π∗D = D（第一个为推出、第二个为拉回）的精确形式。','投影公式、有效性拉回、支撑拉回与纤维满射。'],steps:[['转到射影态射','构造 π : X′ → X，使 f ∘ π projective。'],['应用射影版本','将 D 拉回到 X′，核对 nef 与推出条件。'],['下降结论','用 cycle 推出恒等式和支撑的满射下降返回 X。']]},
{id:'proper',title:'Proper negativity lemma',status:'pending',x:536,y:890,deps:['projective','projective2','chow'],paper:'proper',statement:'完整目标：正规簇间 proper birational 态射的 negativity lemma 及纤维支撑结论。',scope:'完整目标尚未完成。绿色与蓝绿色节点显示已验证的组成部分；琥珀色节点是需要补齐的几何输入。',inputs:['先完成 projective 版本，再完成 Chow 与推拉归约。'],steps:[['射影版本','完成有效性等价及纤维支撑二择一。'],['Chow 归约','把 proper 问题提升到 projective 模型。'],['下降至原簇','通过推出及支撑关系得到最终结论。']]}
];

const find=id=>nodes.find(n=>n.id===id);
Object.assign(find('chow'),{title:'Chow 改造与几何推拉性质',statement:'剩余几何输入：正规 Chow 改造的存在，以及真实除子的投影公式、推拉恒等式和支撑拉回。',scope:'下降的逻辑与集合步骤已分离并验证；此节点仅保留尚未证明的几何性质。'});
Object.assign(find('proper'),{y:1410,deps:['properreduce','fiberdown','chow']});
nodes.push(
{id:'coefflaws',title:'系数推出的复合与核',status:'done',x:20,y:1050,deps:['push'],decl:'push_comp',related:['push_zero_iff_exceptional_support','effective_both_signs_iff_zero','push_embDomain','push_add_exceptional','effective_descends_coefficients'],file:'Descent.lean',paper:'proper',statement:'系数推出可复合；零推出等价于 exceptional 支撑；exceptional 项不改变推出。',scope:'六条系数模型定理已验证。嵌入系数的 section 是模型构造，还不是几何 Cartier 拉回。',inputs:['严格变换的单射。','所有系数有限支撑。'],steps:[['复合与核','逐项读取严格变换系数，证明复合公式与零推出的刻画。'],['推拉与 exceptional 项','嵌入系数后推出返回原值；只加 exceptional 系数不改变推出。'],['有效性下降','复用已验证的推出保持有效性。']]},
{id:'projection',title:'真实曲线的投影公式',status:'assumption',x:20,y:1170,deps:[],paper:'proper',statement:'被改造压缩的曲线拉回交数为零；其余曲线给出非负次数倍的原交数。',scope:'实际交数的投影公式仍待几何形式化；其符号推论已在相邻节点完成。',inputs:['真实的 Cartier 拉回与曲线次数。'],steps:[['分类曲线','区分被改造压缩的曲线与映到曲线的情形。'],['投影公式','分别证明交数为零或次数倍公式。']]},
{id:'nefpull',title:'nef 符号沿拉回传递',status:'conditional',x:278,y:1050,deps:['projection'],decl:'nonpositive_pullback',related:['nonpositive_smul'],file:'Descent.lean',paper:'proper',statement:'投影公式的零值或非负倍数条件推出拉回后的交数仍非正。',scope:'符号推导已验证；实际投影公式仍是明确参数。',inputs:['原交数非正。','拉回交数为零，或原交数的非负倍数。'],steps:[['曲线分情况','压缩曲线使用零交数，其余使用非负倍数。'],['保持符号','非负数乘非正数仍非正。']]},
{id:'effdown',title:'有效性沿推出下降',status:'conditional',x:278,y:1170,deps:['push','chow'],decl:'effective_descends',file:'Descent.lean',paper:'proper',statement:'推出保持有效且 push(pull D)=D 时，拉回有效推出原除子有效。',scope:'下降组合已验证；实际除子的推拉恒等式仍需建立。',inputs:['push(pull D)=D。','推出保持有效性。'],steps:[['推出有效拉回','先应用推出保持有效性。'],['代入恒等式','用 push(pull D)=D 返回原除子。']]},
{id:'setdown',title:'满射下的集合关系下降',status:'done',x:278,y:1290,deps:[],decl:'support_dichotomy_descends',related:['subset_iff_preimage_subset','disjoint_iff_preimage_disjoint','composite_fiber'],file:'Descent.lean',paper:'proper',statement:'任意满射的逆像反映包含与不相交；支撑二择一因此下降。',scope:'纯集合层已完整验证，不需要额外几何假设。',inputs:['映射满射。'],steps:[['取原像','每个底空间点取一个原像，反映集合关系。'],['二择一下降','分别下降不相交和包含。']]},
{id:'properreduce',title:'proper 到 projective 的归约',status:'conditional',x:536,y:1170,deps:['projective','effdown','nefpull','chow'],decl:'negativity_descends',file:'Descent.lean',paper:'proper',statement:'在改造及推拉条件下，射影 negativity 结论推出 proper 的有效性等价。',scope:'归约逻辑已验证。Chow 存在性与几何公式是参数，射影几何定理也仍未完成。',inputs:['推拉恒等式与推出的交换关系。','nef 拉回保持和射影 negativity 结论。'],steps:[['上升','拉回 D 并传递 nef 与底上的有效推出。'],['射影结论','对拉回应用射影 negativity。'],['下降','沿推出恢复 D 的有效性。']]},
{id:'fiberdown',title:'纤维支撑二择一下降',status:'conditional',x:536,y:1290,deps:['setdown','projective2','chow'],decl:'fiber_dichotomy_descends',file:'Descent.lean',paper:'proper',statement:'满射改造上每个复合纤维的支撑二择一，下降到底上每个纤维。',scope:'纤维与集合的归约已验证；支撑等于逆像与射影纤维结论仍需几何证明。',inputs:['改造满射。','上方支撑是下方支撑的逆像。','上方每个纤维满足二择一。'],steps:[['复合纤维','复合纤维等于原纤维的逆像。'],['满射下降','应用已验证的集合二择一下降。']]}
);

Object.assign(nodes.find(n=>n.id==='projection'),{
  deps:['geomcycle'],statement:'需要证明 (π*D)·Γ = D·π_*[Γ]，由此得到 −π*D 的相对 nef 性。',
  scope:'完整的几何交数等式尚待形式化。真实 Scheme-cycle 推出的基础部分已验证；nef 符号推论也已验证。',
  inputs:['π:X′→X 是 proper birational，f:X→Y，g=f∘π。D 为 X 上的 R-Cartier 除子。','Γ⊂X′ 是满足 g(Γ) 为点的完整整曲线。','需建立 Cartier 拉回与曲线交数的投影公式，而不只是给交数一个线性接口。'],
  steps:[['若 π 压缩 Γ','π_*[Γ]=0，需证明 (π*D)·Γ=0。'],['若 π(Γ)=C 是曲线','令 r=[k(Γ):k(C)]>0，需证明 (π*D)·Γ=r(D·C)。'],['推出 nef 拉回','此时 C 被 f 压缩，D·C≤0，所以 (π*D)·Γ≤0。']]
});
nodes.find(n=>n.id==='projection').precise={
  zh:{setup:'π:X′→X，f:X→Y，g=f∘π；D 是 X 上的 R-Cartier 除子。Γ⊂X′ 是被 g 压缩的完整整曲线。',zero:'若 π(Γ) 是点：',curve:'若 π(Γ)=C 是曲线：',degree:'r=[k(Γ):k(C)]>0。这里 r 是函数域扩张次数。',use:'因为 g 压缩 Γ，曲线 C 也被 f 压缩。−D 为 f-nef 意味着 D·C≤0，因此以上两种情形都给 (π*D)·Γ≤0，即 −π*D 为 g-nef。',gap:'已证明 cycle 推出的零值／次数权重性质。还需构造实际 Cartier 拉回和曲线交数，并证明上面的等式。'},
  en:{setup:'π:X′→X, f:X→Y, g=f∘π. D is an R-Cartier divisor on X. Γ⊂X′ is a proper integral curve contracted by g.',zero:'If π(Γ) is a point:',curve:'If π(Γ)=C is a curve:',degree:'r=[k(Γ):k(C)]>0 is the function-field extension degree.',use:'Since g contracts Γ, f contracts C. Relative nefness of −D gives D·C≤0. Both cases yield (π*D)·Γ≤0, so −π*D is g-nef.',gap:'The zero / degree weights in actual scheme-cycle pushforward are proved. Actual Cartier pullback and curve intersection, and the displayed identity, remain to be constructed and proved.'}
};
nodes.push({id:'geomcycle',title:'真实 Scheme-cycle 的推出',status:'done',x:20,y:1290,deps:[],decl:'scheme_cycle_map_effective',related:['scheme_mapCoeff_zero_of_drop','scheme_mapCoeff_of_same_weight','scheme_cycle_map_zero_of_drop'],file:'GeometricCycles.lean',paper:'proper',statement:'直接对 mathlib 的 AlgebraicCycle 与 Scheme 态射，证明推出保持有效，以及降维为零、同维按剩余域次数计重。',scope:'这四条结果使用真实 Scheme-cycle API。它们还不包含 Cartier 拉回和曲线交数的完整射影公式。',inputs:['Scheme 态射 f 的 QuasiCompact 条件。','权重函数 wx,wy 指定维数／余维数。','cycle 的系数为实数；有效性为逐点非负。'],steps:[['推出保持有效','每项都是非负系数乘自然数次数权重，再取有限和。'],['降维为零','wx(x)≠wy(f(x)) 时，mapCoeff 的定义给权重 0。'],['同维按次数计重','wx(x)=wy(f(x)) 时，权重等于 f.residueDegree(x)。']]});

// Projection input refinement: distinguish proved cycle algebra from actual Cartier geometry.
nodes.find(n=>n.id==='geomcycle').related.push('scheme_cycle_map_single','scheme_curve_push_of_same_weight','scheme_curve_push_of_drop');
nodes.find(n=>n.id==='geomcycle').scope='使用真实 Scheme-cycle API，已证明有效性与单分量推出的零值／次数倍公式。权重函数仍须由实际维数选定；不包含 Cartier 交数兼容性。';
nodes.push({id:'realspan',title:'射影公式的实线性延伸',status:'done',x:20,y:1450,deps:[],decl:'projection_formula_on_real_span',file:'Projection.lean',paper:'proper',statement:'两个实线性映射在 Cartier 生成元上相等，则在其张成空间上相等。',scope:'实线性代数步骤已验证。实际 Cartier 生成元、拉回和交数映射仍需几何构造。',inputs:['拉回及两侧交数是实线性映射。','D 属于 Cartier 生成元的实线性张成。','在 Cartier 生成元上已建立射影公式。'],steps:[['比较线性映射','把两侧视为同一实向量空间到实数的线性映射。'],['在生成元上验证','Cartier 生成元上的等式是明确输入。'],['延伸','LinearMap.eqOn_span 将等式延伸到每个有限实线性组合。']]});
nodes.find(n=>n.id==='projection').deps=['geomcycle','realspan'];
nodes.find(n=>n.id==='projection').precise.zh.gap='单曲线 cycle 的零值／次数倍推出，以及从 Cartier 生成元到实线性张成的延伸均已证明。唯一尚未建立的交数兼容性是：对 Cartier 生成元 A，up(single x 1)=down(map π wx wy (single x 1))。这里 up 是 π*A 的真实交数，down 是 A 的真实交数；这两个映射仍需几何构造。';
nodes.find(n=>n.id==='projection').precise.en.gap='Single-curve cycle pushforward and extension from Cartier generators to their real span are proved. The remaining intersection compatibility is up(single x 1)=down(map π wx wy (single x 1)) for each Cartier generator A. Here up must be actual intersection with π*A and down actual intersection with A; these geometric maps still need construction.';
nodes.push({id:'projectioncases',title:'由 cycle 推出交数两种情形',status:'conditional',x:278,y:1450,deps:['projection','geomcycle'],decl:'projection_cases_from_cycle_push',file:'Projection.lean',paper:'proper',statement:'给定真实交数与 cycle 推出的兼容等式，推导压缩曲线交数为零、同维曲线交数为剩余域次数倍。',scope:'两种情形由实际 AlgebraicCycle.map 推导，已不再单独假设一个零值／倍数的析取。交数兼容性仍是 hcompat 参数。',inputs:['up/down 是 cycle 上的交数加法映射。','hcompat：up([Γ])=down(π_*[Γ])。','权重对应实际曲线及其像的维数。'],steps:[['cycle 推出','直接使用真实 Scheme-cycle 的单分量推出公式。'],['交数加法性','交数加法映射把自然数倍 cycle 变为次数倍交数。'],['得到两种情形','权重下降给零，同权重给 residueDegree 倍数。']]});
Object.assign(nodes.find(n=>n.id==='nefpull'),{deps:['projectioncases'],decl:'nonpositive_pullback_from_cycle_push',related:['nonpositive_pullback','nonpositive_smul'],file:'Projection.lean',statement:'从真实 cycle 推出与交数兼容性推导非正交数沿拉回保持。',scope:'已验证实际 Scheme-cycle API 上的条件式符号传递。原有析取输入已由 cycle 两种情形取代；交数兼容性和像曲线可测试性仍为参数。',inputs:['hcompat：上方交数等于下方对推出 cycle 的交数。','同维像曲线是底上允许测试的压缩曲线。','底上测试曲线交数非正。']});
nodes.push({id:'pushpull',title:'真实除子的推拉恒等式',status:'assumption',x:20,y:1570,deps:[],paper:'proper',statement:'π 为正规簇间 proper birational 态射，D 为 R-Cartier 除子，需要建立 π_*(π*D)=D。',scope:'尚需构造真实 Cartier 拉回及其 underlying Weil cycle，并证明在每个底上素除子处的推出系数恢复原系数。',inputs:['pull D 是实际 Cartier 拉回，不能仅选取任意有效 cycle。','在非例外严格变换上的系数与剩余域次数恢复 D。','例外分量因维数下降而不贡献推出。'],steps:[['核对严格变换','每个底上素除子的非例外严格变换给原系数。'],['核对例外分量','维数下降的例外分量推出为零。'],['cycle 等式','逐素除子比较系数，证明 π_*(π*D)=D。']]});
Object.assign(nodes.find(n=>n.id==='effdown'),{deps:['geomcycle','pushpull'],decl:'scheme_effective_descends',related:['effective_descends'],file:'Projection.lean',statement:'真实 Scheme-cycle 的推出已保持有效；若 π_*(π*D)=D 且 π*D 有效，则 D 有效。',scope:'有效性下降已接入实际 AlgebraicCycle.map。尚待几何证明的 map-property 输入只有 hleft，即实际 Cartier 拉回的推拉恒等式；hlifted 是应用此定理时的已知条件。',inputs:['hleft：AlgebraicCycle.map π wx wy lifted = D，其中 lifted 是 π*D 的 underlying cycle。','hlifted：CycleEffective lifted，即拉回除子已有效。','推出保持有效已由 scheme_cycle_map_effective 证明，不再假设。'],steps:[['使用已证明的推出有效性','将有效 lifted 经真实 AlgebraicCycle.map 推出，得到有效的 π_*lifted。'],['代入唯一待补恒等式','用 hleft：π_*lifted=D，得到 D 有效。']]});
