import {t,english,englishStatuses} from './i18n.js?v=20261001-formal-6';
// Perspective projection of the same curated proof DAG; no new proof dependencies.
export function createSpatialGraph({host,nodes,select,relation}) {
  const byId=new Map(nodes.map(n=>[n.id,n])), depths=new Map();
  function depth(id){if(!depths.has(id))depths.set(id,Math.max(-1,...byId.get(id).deps.map(depth))+1);return depths.get(id);}
  nodes.forEach(n=>depth(n.id));
  const maxDepth=Math.max(...depths.values());
  const positions=new Map(nodes.map(n=>[n.id,{x:(n.x-278)*1.3,y:(n.y-(Math.max(...nodes.map(m=>m.y))+60)/2)*1.08,z:(depth(n.id)-maxDepth/2)*145}]));
  host.innerHTML=`<div class="spatial-controls"><button class="button small" data-camera="reset">重置视角</button><button class="button small" data-camera="focus" aria-pressed="false">聚焦依赖链</button><button class="button small" data-camera="direct" aria-pressed="false">只看直接前提</button><button class="button small" data-camera="in" aria-label="放大三维图">＋</button><button class="button small" data-camera="out" aria-label="缩小三维图">−</button><label>定位节点 <select id="spatialSelect">${nodes.map(n=>`<option value="${n.id}">${n.title}</option>`).join('')}</select></label></div><div class="spatial-stage" tabindex="0" role="region" aria-label="三维证明依赖图。拖动旋转，滚轮缩放；键盘方向键旋转，加减键缩放。"><canvas aria-hidden="true"></canvas><div class="spatial-cards"></div><div class="spatial-axis" aria-hidden="true">横向：证明类别 · 纵向：步骤位置<br>纵深：依赖推导层级</div></div><p class="spatial-hint">拖动旋转 · 滚轮或 ＋／− 缩放 · 点击节点查看证明。3D 层次仅表示推导深度，验证状态仍由颜色表示。</p>`;
  const stage=host.querySelector('.spatial-stage'),canvas=stage.querySelector('canvas'),ctx=canvas.getContext('2d'),cards=stage.querySelector('.spatial-cards'),picker=host.querySelector('select');
  const buttons=new Map();
  nodes.forEach(n=>{const b=document.createElement('button');b.className=`spatial-node ${n.status}`;b.dataset.spatialNode=n.id;b.innerHTML=`<b></b><small></small><span class="relation-tag"></span>`;b.querySelector('b').textContent=n.title;b.querySelector('small').textContent=english?englishStatuses[n.status]:({done:'✓ 模型内已验证',conditional:'◐ 条件式已验证',assumption:'◇ 暂作假设',pending:'○ 待完成目标'})[n.status];b.addEventListener('click',e=>{if(e.detail===0)select(n.id);});cards.append(b);buttons.set(n.id,b);});
  let yaw=-.38,pitch=.12,zoom=1,focused=false,directOnly=false,current='proper',scope='all',frame=0,pointer=null;
  const labels={selected:'当前结论',direct:'直接前提',indirect:'间接前提',other:'非当前依赖'};
  function schedule(){if(!frame)frame=requestAnimationFrame(draw);}
  function project(p,c,w,h,fit){const x=p.x-c.x,y=p.y-c.y,z=p.z-c.z;const rx=x*Math.cos(yaw)+z*Math.sin(yaw),rz=-x*Math.sin(yaw)+z*Math.cos(yaw);const ry=y*Math.cos(pitch)-rz*Math.sin(pitch),zz=y*Math.sin(pitch)+rz*Math.cos(pitch);const scale=fit*zoom*1500/(1500+zz);return{x:w/2+rx*scale,y:h/2+ry*scale,z:zz,scale};}
  function draw(){frame=0;if(host.hidden)return;const w=stage.clientWidth,h=stage.clientHeight,dpr=Math.min(devicePixelRatio||1,2);canvas.width=w*dpr;canvas.height=h*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);
    const relevant=nodes.filter(n=>directOnly?['selected','direct'].includes(relation(n.id)):relation(n.id)!=='other'),layout=focused||directOnly?relevant:nodes;
    const center={x:0,y:0,z:0};layout.forEach(n=>{const p=positions.get(n.id);center.x+=p.x/layout.length;center.y+=p.y/layout.length;center.z+=p.z/layout.length;});
    const rotated=layout.map(n=>{const p=positions.get(n.id),x=p.x-center.x,y=p.y-center.y,z=p.z-center.z;const rx=x*Math.cos(yaw)+z*Math.sin(yaw),rz=-x*Math.sin(yaw)+z*Math.cos(yaw);return{x:rx,y:y*Math.cos(pitch)-rz*Math.sin(pitch)};});const span=axis=>Math.max(...rotated.map(p=>p[axis]))-Math.min(...rotated.map(p=>p[axis]));const fit=Math.min((w-55)/(span('x')+300),(h-120)/(span('y')+190),1.15),points=new Map(nodes.map(n=>[n.id,project(positions.get(n.id),center,w,h,fit)]));
    // Light depth-plane lattice supplies orientation without adding semantic edges.
    ctx.strokeStyle='#2a414b';ctx.lineWidth=.7;ctx.globalAlpha=.35;
    for(let k=0;k<=maxDepth;k++){const z=(k-maxDepth/2)*145;const corners=[[-410,-550],[410,-550],[410,550],[-410,550]].map(([x,y])=>project({x,y,z},center,w,h,fit));ctx.beginPath();corners.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.closePath();ctx.stroke();}
    nodes.forEach(n=>n.deps.forEach(id=>{const a=points.get(id),b=points.get(n.id),on=relation(id)!=='other'&&relation(n.id)!=='other';if(focused&&!on||directOnly&&n.id!==current||scope==='open')return;ctx.globalAlpha=on?.85:.055;ctx.strokeStyle=on?'#b4eaf4':'#607b87';ctx.lineWidth=n.id===current?2.6:1.3;ctx.setLineDash(byId.get(id).status==='assumption'?[5,4]:[]);const dy=b.y-a.y,dx=b.x-a.x,length=Math.hypot(dx,dy);if(length<1)return;const ux=dx/length,uy=dy/length;const end={x:b.x-ux*65*b.scale,y:b.y-uy*32*b.scale};ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(end.x,end.y);ctx.stroke();ctx.setLineDash([]);ctx.beginPath();ctx.moveTo(end.x,end.y);ctx.lineTo(end.x-ux*9+uy*4,end.y-uy*9-ux*4);ctx.lineTo(end.x-ux*9-uy*4,end.y-uy*9+ux*4);ctx.closePath();ctx.fillStyle=ctx.strokeStyle;ctx.fill();}));ctx.globalAlpha=1;
    nodes.forEach(n=>{const b=buttons.get(n.id),p=points.get(n.id),r=relation(n.id);b.dataset.relation=r;b.setAttribute('aria-pressed',String(r==='selected'));b.querySelector('.relation-tag').textContent=t(labels[r]);b.title=n.title;b.hidden=(directOnly&&!['selected','direct'].includes(r))||(focused&&r==='other')||(scope==='path'&&r==='other')||(scope==='open'&&!['assumption','pending'].includes(n.status));const sf=Math.max(r==='selected'?.78:.26,Math.min(1.3,p.scale))*(parseFloat(getComputedStyle(document.documentElement).getPropertyValue('--node-base-font'))/16||1.125);b.style.left=Math.round(p.x)+'px';b.style.top=Math.round(p.y)+'px';b.style.transform='translate(-50%,-50%)';b.style.width=226*sf+'px';b.style.height=112*sf+'px';b.style.padding=9*sf+'px '+12*sf+'px';const title=b.querySelector('b'),status=b.querySelector('small'),tag=b.querySelector('.relation-tag');title.style.fontSize=16*sf+'px';title.style.height=42*sf+'px';status.style.fontSize=12*sf+'px';status.style.marginTop=4*sf+'px';tag.style.fontSize=11*sf+'px';tag.style.marginTop=5*sf+'px';b.style.zIndex=String(r==='selected'?4500:Math.round(2000-p.z));});
  }
  stage.addEventListener('pointerdown',e=>{if(e.button!==0)return;pointer={id:e.pointerId,x:e.clientX,y:e.clientY,startX:e.clientX,startY:e.clientY,node:e.target.closest('[data-spatial-node]')?.dataset.spatialNode};stage.setPointerCapture(e.pointerId);stage.classList.add('dragging');});
  stage.addEventListener('pointermove',e=>{if(!pointer||e.pointerId!==pointer.id)return;yaw+=(e.clientX-pointer.x)*.005;pitch=Math.max(-.8,Math.min(.8,pitch+(e.clientY-pointer.y)*.004));pointer.x=e.clientX;pointer.y=e.clientY;schedule();});
  function release(e){if(!pointer||e.pointerId!==pointer.id)return;const click=Math.hypot(e.clientX-pointer.startX,e.clientY-pointer.startY)<6,id=pointer.node;pointer=null;stage.classList.remove('dragging');if(e.type==='pointerup'&&click&&id)select(id);}
  stage.addEventListener('pointerup',release);stage.addEventListener('pointercancel',release);
  function changeZoom(factor){zoom=Math.max(.55,Math.min(2.8,zoom*factor));schedule();}
  stage.addEventListener('wheel',e=>{e.preventDefault();changeZoom(Math.exp(-e.deltaY*.001));},{passive:false});
  stage.addEventListener('keydown',e=>{if(e.target!==stage)return;const keys=['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','+','=','-'];if(!keys.includes(e.key))return;e.preventDefault();if(e.key==='ArrowLeft')yaw-=.1;else if(e.key==='ArrowRight')yaw+=.1;else if(e.key==='ArrowUp')pitch=Math.max(-.8,pitch-.1);else if(e.key==='ArrowDown')pitch=Math.min(.8,pitch+.1);else changeZoom(e.key==='-'?.9:1.1);schedule();});
  host.querySelectorAll('[data-camera]').forEach(b=>b.onclick=()=>{const action=b.dataset.camera;if(action==='reset'){yaw=-.38;pitch=.12;zoom=1;focused=false;directOnly=false;host.querySelector('[data-camera="direct"]').setAttribute('aria-pressed','false');host.querySelector('[data-camera="focus"]').setAttribute('aria-pressed','false');}else if(action==='focus'){focused=!focused;b.setAttribute('aria-pressed',String(focused));}else if(action==='direct'){directOnly=!directOnly;b.setAttribute('aria-pressed',String(directOnly));}else changeZoom(action==='in'?1.15:1/1.15);schedule();});
  picker.onchange=()=>select(picker.value);new ResizeObserver(schedule).observe(stage);
  window.addEventListener('typographychange',schedule);
  return {update(id,range){current=id;scope=range;picker.value=id;schedule();},show(){schedule();}};
}
