import {t} from './i18n.js?v=20261001-formal-4';
// Viewer-only node editor: sockets and links always use the curated proof DAG.
export function createNodeEditor({viewport,graph,svg,nodes,select,selected}) {
  const byId=new Map(nodes.map(n=>[n.id,n])),ranks=new Map(),layout=new Map();
  function rank(id){if(!ranks.has(id))ranks.set(id,Math.max(-1,...byId.get(id).deps.map(rank))+1);return ranks.get(id);}
  nodes.forEach(n=>rank(n.id));
  let factor=1;
  function buildLayout(){factor=parseFloat(getComputedStyle(document.documentElement).getPropertyValue('--node-base-font'))/16||1.125;layout.clear();for(let r=0;r<=Math.max(...ranks.values());r++){let y=65;nodes.filter(n=>rank(n.id)===r).forEach(n=>{const h=Math.max(150,104+n.deps.length*22)*factor;layout.set(n.id,{x:65+r*380*factor,y,h});y+=h+44*factor;});}}
  buildLayout();
  graph.querySelectorAll('.column-label').forEach(e=>e.remove());
  nodes.forEach(n=>{const p=layout.get(n.id),b=graph.querySelector(`[data-node="${n.id}"]`);b.style.left=p.x+'px';b.style.top=p.y+'px';b.style.height=p.h+'px';b.style.setProperty('--node-x',p.x+'px');b.style.setProperty('--node-y',p.y+'px');b.innerHTML='';const heading=document.createElement('b');heading.className='node-heading';heading.textContent=n.title;b.append(heading);const sockets=document.createElement('div');sockets.className='node-sockets';
    if(!n.deps.length){const row=document.createElement('span');row.className='node-input empty-input';row.textContent=t('基础输入');sockets.append(row);}n.deps.forEach(id=>{const row=document.createElement('span');row.className='node-input';row.textContent=byId.get(id).title;row.title=byId.get(id).title;sockets.append(row);});b.append(sockets);const output=document.createElement('span');output.className='node-output';output.textContent=t('结论');b.append(output);const status=document.createElement('small');status.className=n.status;status.textContent=t(({done:'✓ 模型内已验证',conditional:'◐ 条件式已验证',assumption:'◇ 暂作假设',pending:'○ 待完成目标'})[n.status]);b.append(status);const rel=document.createElement('span');rel.className='relation-tag';b.append(rel);});
  const wires=document.createElementNS('http://www.w3.org/2000/svg','g');svg.querySelectorAll('.edge').forEach(e=>wires.append(e));svg.append(wires);
  function updateLinks(){wires.querySelectorAll('.edge').forEach(edge=>{const a=layout.get(edge.dataset.from),n=byId.get(edge.dataset.to),b=layout.get(n.id);const x=a.x+300*factor,y=a.y+64*factor,x2=b.x,y2=b.y+(64+22*n.deps.indexOf(edge.dataset.from))*factor,bend=Math.max(75*factor,(x2-x)*.5);edge.setAttribute('d',`M ${x} ${y} C ${x+bend} ${y}, ${x2-bend} ${y2}, ${x2} ${y2}`);edge.removeAttribute('marker-end');});}
  updateLinks();
  let zoom=1,x=0,y=0,drag=null,space=false,lastFrame='selected';
  const controls=document.createElement('div');controls.className='editor-navigation';controls.innerHTML=`<button class="button small" data-frame="all" title="${t('显示全部 · Home')}">${t('显示全部')}</button><button class="button small" data-frame="selected" title="${t('聚焦所选 · 小数点键')}">${t('聚焦所选')}</button><button class="button small" data-node-zoom="in" aria-label="${t('放大')}">＋</button><button class="button small" data-node-zoom="out" aria-label="${t('缩小')}">−</button><output aria-label="${t('缩放比例')}">100%</output>`;viewport.append(controls);
  const output=controls.querySelector('output');viewport.tabIndex=0;viewport.setAttribute('role','region');viewport.setAttribute('aria-label',t('节点编辑区：拖动空白平移，滚轮缩放，Home 显示全部，小数点键聚焦。'));
  function paint(){graph.style.transform='none';graph.style.width=viewport.clientWidth+'px';graph.style.minHeight=viewport.clientHeight+'px';graph.style.setProperty('--node-unit',zoom*factor);graph.style.setProperty('--view-x',x+'px');graph.style.setProperty('--view-y',y+'px');nodes.forEach(n=>{const p=layout.get(n.id),b=graph.querySelector(`[data-node="${n.id}"]`);b.style.setProperty('--node-x',Math.round(p.x*zoom+x)+'px');b.style.setProperty('--node-y',Math.round(p.y*zoom+y)+'px');b.style.width=(300*factor*zoom)+'px';b.style.height=(p.h*zoom)+'px';});svg.style.width=viewport.clientWidth+'px';svg.style.height=viewport.clientHeight+'px';wires.setAttribute('transform',`translate(${x} ${y}) scale(${zoom})`);output.textContent=Math.round(zoom*100)+'%';viewport.style.backgroundSize=(32*zoom)+'px '+(32*zoom)+'px';viewport.style.backgroundPosition=x+'px '+y+'px';}
  function frame(mode=lastFrame){lastFrame=mode;const id=selected(),ids=mode==='all'?nodes.map(n=>n.id):[id,...byId.get(id).deps];const pts=ids.map(id=>layout.get(id)),loX=Math.min(...pts.map(p=>p.x))-45,loY=Math.min(...pts.map(p=>p.y))-45,hiX=Math.max(...pts.map(p=>p.x))+345*factor,hiY=Math.max(...pts.map(p=>p.y+p.h))+45;const w=viewport.clientWidth,h=viewport.clientHeight-50;if(!w||!h)return;zoom=Math.min(w/(hiX-loX),h/(hiY-loY),1.1);x=(w-(hiX-loX)*zoom)/2-loX*zoom;y=(h-(hiY-loY)*zoom)/2-loY*zoom;paint();}
  function scale(f,cx=viewport.clientWidth/2,cy=viewport.clientHeight/2){const next=Math.max(.18,Math.min(2.2,zoom*f));x=cx-(cx-x)*next/zoom;y=cy-(cy-y)*next/zoom;zoom=next;paint();}
  viewport.addEventListener('wheel',e=>{e.preventDefault();const box=viewport.getBoundingClientRect();scale(Math.exp(-e.deltaY*.0015),e.clientX-box.left,e.clientY-box.top);},{passive:false});
  viewport.addEventListener('pointerdown',e=>{if(e.target.closest('.editor-navigation'))return;if(e.button!==1&&e.button!==0)return;if(e.target.closest('.node')&&!space&&e.button!==1)return;drag={id:e.pointerId,x:e.clientX,y:e.clientY};viewport.setPointerCapture(e.pointerId);viewport.classList.add('panning');e.preventDefault();});
  viewport.addEventListener('pointermove',e=>{if(!drag||e.pointerId!==drag.id)return;x+=e.clientX-drag.x;y+=e.clientY-drag.y;drag.x=e.clientX;drag.y=e.clientY;paint();});
  const end=()=>{drag=null;viewport.classList.remove('panning');};viewport.addEventListener('pointerup',end);viewport.addEventListener('pointercancel',end);
  viewport.addEventListener('keydown',e=>{if(e.target.closest('input,select'))return;if(e.code==='Space'){space=true;e.preventDefault();}else if(e.key==='Home'){e.preventDefault();frame('all');}else if(e.key==='.'||e.code==='NumpadDecimal'){e.preventDefault();frame('selected');}else if(['+','=','-'].includes(e.key)){e.preventDefault();scale(e.key==='-'?.85:1.15);}else if(e.key.startsWith('Arrow')){e.preventDefault();if(e.key==='ArrowLeft')x+=45;if(e.key==='ArrowRight')x-=45;if(e.key==='ArrowUp')y+=45;if(e.key==='ArrowDown')y-=45;paint();}});viewport.addEventListener('keyup',()=>space=false);viewport.addEventListener('blur',()=>space=false);
  controls.querySelectorAll('[data-frame]').forEach(b=>b.onclick=()=>frame(b.dataset.frame));controls.querySelectorAll('[data-node-zoom]').forEach(b=>b.onclick=()=>scale(b.dataset.nodeZoom==='in'?1.15:1/1.15));new ResizeObserver(()=>frame()).observe(viewport);
  window.addEventListener('typographychange',()=>{const prior=layout.get(selected()),cx=(prior.x+150*factor)*zoom+x,cy=(prior.y+prior.h/2)*zoom+y;buildLayout();updateLinks();const next=layout.get(selected());x=cx-(next.x+150*factor)*zoom;y=cy-(next.y+next.h/2)*zoom;paint();});
  return {show(){requestAnimationFrame(()=>frame());},selectionChanged(){if(lastFrame==='selected')requestAnimationFrame(()=>frame('selected'));},frame};
}
