import {t} from './i18n.js?v=20261004-formal-42';
const defaults={node:18,detail:17,ui:14,width:390};
export function installSettings(){
  let stored={};try{stored=JSON.parse(localStorage.getItem('formalization-typography')||'{}');}catch{}
  const ranges={node:[14,26],detail:[14,24],ui:[11,18],width:[320,560]},values={};
  for(const key in defaults){const value=Number(stored[key]);values[key]=Number.isFinite(value)?Math.min(ranges[key][1],Math.max(ranges[key][0],value)):defaults[key];}
  let panAnimation=true;try{panAnimation=JSON.parse(localStorage.getItem('formalization-motion')||'{}').pan!==false;}catch{}
  const button=document.createElement('button');button.id='settingsToggle';button.className='icon-button';button.setAttribute('aria-label',t('设置'));button.title=t('设置');button.innerHTML='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><path d="m9 3-1 3-3 1-2 5 2 5 3 1 1 3h6l1-3 3-1 2-5-2-5-3-1-1-3Z"/><circle cx="12" cy="12" r="3"/></svg>';document.querySelector('.transport').prepend(button);
  const dialog=document.createElement('dialog');dialog.className='typography-settings';dialog.setAttribute('aria-labelledby','settingsTitle');dialog.innerHTML=`<div class="settings-heading"><h2 id="settingsTitle">${t('阅读设置')}</h2><button id="closeSettings" class="button small">${t('关闭')}</button></div><p>${t('字号独立于图谱缩放，设置自动保存在本机。')}</p>${[['node','节点字号'],['detail','证明详情字号'],['ui','工具栏字号'],['width','详情面板宽度']].map(([key,label])=>`<label for="font-${key}">${t(label)}<output id="value-${key}"></output><input id="font-${key}" type="range" min="${ranges[key][0]}" max="${ranges[key][1]}" step="${key==='width'?10:1}" value="${values[key]}"></label>`).join('')}<label class="motion-setting" for="panAnimation"><span>${t('选中卡片时平滑定位')}</span><input id="panAnimation" type="checkbox" ${panAnimation?'checked':''}></label><p class="motion-help">${t('平移自然加速与减速；关闭后即时定位。')}</p><div class="font-preview">Aa · Γ · π*D<br>${t('数学证明的阅读预览')}</div><button id="resetTypography" class="button">${t('恢复默认')}</button>`;document.body.append(dialog);
  function apply(){for(const key in values){document.documentElement.style.setProperty(key==='width'?'--detail-width':'--'+key+'-base-font',values[key]+'px');dialog.querySelector('#value-'+key).textContent=values[key]+' px';}localStorage.setItem('formalization-typography',JSON.stringify(values));window.dispatchEvent(new CustomEvent('typographychange',{detail:{...values}}));}
  function applyMotion(){document.documentElement.dataset.panAnimation=String(panAnimation);localStorage.setItem('formalization-motion',JSON.stringify({pan:panAnimation}));window.dispatchEvent(new CustomEvent('motionchange',{detail:{pan:panAnimation}}));}
  dialog.querySelector('#panAnimation').onchange=e=>{panAnimation=e.target.checked;applyMotion();};applyMotion();
  for(const key in values)dialog.querySelector('#font-'+key).oninput=e=>{values[key]=Number(e.target.value);apply();};
  button.onclick=()=>dialog.showModal();dialog.querySelector('#closeSettings').onclick=()=>dialog.close();dialog.querySelector('#resetTypography').onclick=()=>{Object.assign(values,defaults);panAnimation=true;dialog.querySelector('#panAnimation').checked=true;applyMotion();for(const key in values)dialog.querySelector('#font-'+key).value=values[key];apply();};apply();
}
