const local=/^(localhost|127\.0\.0\.1)$/.test(location.hostname),testMode=local?new URLSearchParams(location.search).get('social'):null;
const API=testMode==='local'?'http://127.0.0.1:8783':'https://birationalclass-d3fw2j6t76955af0-1493130792.ap-shanghai.app.tcloudbase.com'+(testMode==='test'?'/refuge-test':'/refuge');
const $=id=>document.getElementById(id);
let generation=0,user=null,mode='login',busy=false,chatOpen=false,pollTimer,fadeTimer,latest=0,pending=null;
const seen=new Set();
async function request(path,data){
 const response=await fetch(API+'/api/'+path,{method:data?'POST':'GET',credentials:'include',headers:data?{'Content-Type':'application/json'}:{},body:data?JSON.stringify(data):undefined,signal:AbortSignal.timeout(12000)});
 const result=await response.json();if(!response.ok){const error=new Error(result.error||'连接暂不可用');error.status=response.status;throw error;}return result;
}
function message(error){return error.name==='TimeoutError'||error instanceof TypeError?'连接暂不可用，请重试':error.message;}
function setUser(value){generation++;user=value;document.querySelectorAll('[data-account-open]').forEach(el=>{if(el.id!=='socialAccountToggle')el.textContent=value?value.name:'登录 / 注册';});$('socialAccountName').textContent=value?.name||'';$('socialAdminOpen').hidden=value?.role!=='admin';$('socialAdminPanel').hidden=true;$('socialAdminRows').replaceChildren();$('socialAuthForm').hidden=!!value;$('socialAccountView').hidden=!value;if(!value){seen.clear();$('socialMessages').replaceChildren();latest=0;}clearTimeout(pollTimer);if(value)poll();}
function setMode(value){mode=value;$('socialAuthTitle').textContent=value==='register'?'加入书院':'欢迎回来';$('socialSubmit').textContent=value==='register'?'创建账号':'登录';$('socialSwitch').textContent=value==='register'?'已有账号 · 登录':'创建一个账号';$('socialPassword').autocomplete=value==='register'?'new-password':'current-password';$('socialPassword').minLength=value==='register'?8:1;$('socialPassword').placeholder=value==='register'?'至少 8 位':'输入密码';$('socialAuthStatus').textContent='';}
function openAccount(){window.dispatchEvent(new Event('refuge-social-focus'));$('socialDialog').showModal();setMode(mode);if(!user)$('socialName').focus();else $('socialClose').focus();}
function closeAccount(){$('socialDialog').close();$('world').focus({preventScroll:true});}
function activity(){clearTimeout(fadeTimer);$('socialChat').classList.add('recent');fadeTimer=setTimeout(()=>{if(!chatOpen)$('socialChat').classList.remove('recent');},9000);}
function openChat(){if($('world').dataset.entered!=='true')return;if(!user){openAccount();return;}chatOpen=true;window.dispatchEvent(new Event('refuge-social-focus'));$('socialChat').classList.add('expanded');$('socialComposer').hidden=false;$('socialChatToggle').setAttribute('aria-expanded','true');$('socialInput').focus();activity();poll();}
function closeChat(){chatOpen=false;$('socialChat').classList.remove('expanded');$('socialComposer').hidden=true;$('socialChatToggle').setAttribute('aria-expanded','false');$('world').focus({preventScroll:true});activity();}
function addMessages(messages,initial=false){for(const item of messages){if(seen.has(item.id))continue;seen.add(item.id);const row=document.createElement('p'),name=document.createElement('b'),text=document.createElement('span'),time=document.createElement('time');time.dateTime=new Date(item.createdAt).toISOString();time.textContent=new Date(item.createdAt).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit',hour12:false});time.title=new Date(item.createdAt).toLocaleString('zh-CN');row.className=item.mine?'own':'';name.textContent=item.name;text.textContent=item.text;row.append(time,name,text);$('socialMessages').append(row);if(!initial&&item.createdAt>latest)activity();latest=Math.max(latest,item.createdAt);}while($('socialMessages').children.length>50)$('socialMessages').firstElementChild.remove();$('socialMessages').scrollTop=$('socialMessages').scrollHeight;}
let polling=false,lastActivity=Date.now();
for(const type of ['pointerdown','keydown'])addEventListener(type,()=>{const idle=Date.now()-lastActivity>120000;lastActivity=Date.now();if(idle)poll();},{passive:true});
async function poll(){clearTimeout(pollTimer);if(!user||document.hidden||polling||$('world').dataset.entered!=='true'||Date.now()-lastActivity>120000)return;polling=true;const version=generation;try{const data=await request('messages');if(version!==generation)return;addMessages(data.messages,!seen.size);$('socialChatStatus').textContent='';}catch(e){if(e.status===401){setUser(null);$('socialChatStatus').textContent='登录已过期';}else $('socialChatStatus').textContent='连接中…';}finally{polling=false;if(user)pollTimer=setTimeout(poll,chatOpen?5000:60000);}}
const shell=document.createElement('div');shell.id='refugeSocial';shell.innerHTML=`
<button id="socialChatToggle" class="chrome" aria-label="全体聊天" aria-expanded="false">交谈 <kbd>↵</kbd></button>
<button id="socialAccountToggle" class="icon-button" data-account-open aria-label="账号管理" aria-haspopup="dialog" aria-controls="socialDialog" title="账号管理" data-tip="账号管理"><svg viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="8" r="3.5"/><path d="M4.5 21v-2a7.5 7.5 0 0 1 15 0v2"/></svg></button>
<section id="socialChat" aria-label="书院全体聊天"><div class="social-chat-heading" id="socialDragHandle" title="拖动聊天窗口"><span>书院 <i>/</i> 全体</span><button id="socialChatClose" aria-label="收起聊天">×</button></div><div id="socialMessages" role="log" aria-live="polite" aria-relevant="additions"></div><p id="socialChatStatus" role="status"></p><form id="socialComposer" hidden><label for="socialInput">全体</label><input id="socialInput" maxlength="300" autocomplete="off" placeholder="说点什么…" aria-label="聊天消息"><button id="socialSend" aria-label="发送消息">↵</button></form></section>
<dialog id="socialDialog" aria-labelledby="socialAuthTitle"><button id="socialClose" aria-label="关闭账号窗口">×</button><p class="social-eyebrow">MATH REFUGE / ACCOUNT</p><h2 id="socialAuthTitle">欢迎回来</h2><form id="socialAuthForm"><label for="socialName">账号</label><input id="socialName" name="username" autocomplete="username" minlength="3" maxlength="24" required placeholder="3–24 字，中文、字母或数字"><label for="socialPassword">密码</label><div class="social-password"><input id="socialPassword" name="password" type="password" autocomplete="current-password" minlength="8" maxlength="128" required placeholder="至少 8 位"><button id="socialReveal" type="button" aria-label="显示密码" aria-pressed="false">显示</button></div><label class="social-remember"><input id="socialRemember" type="checkbox" checked>记住我 <span>30 天</span></label><button id="socialSubmit" type="submit">登录 <span>↗</span></button><button id="socialSwitch" type="button">创建一个账号</button></form><div id="socialAccountView" hidden><p id="socialAccountName"></p><p class="social-account-note">已登录书院</p><button id="socialAdminOpen" hidden>管理账号</button><section id="socialAdminPanel" hidden aria-label="账号与最近登录"><div class="admin-heading"><span>账号与最近登录</span><button id="socialAdminRefresh" type="button">刷新</button></div><div id="socialAdminRows"></div><button id="socialAdminMore" hidden>更多账号</button><p id="socialAdminStatus" role="status"></p></section><button id="socialLogout">退出登录</button></div><p id="socialAuthStatus" role="status"></p><button id="socialGuest">继续漫步</button></dialog>`;document.body.append(shell);document.querySelector('.transport').append($('socialAccountToggle'));
for(const root of [$('loading'),$('error')]){const button=document.createElement('button');button.className='arrival-account';button.dataset.accountOpen='';button.textContent='登录 / 注册';root.append(button);}
document.querySelectorAll('[data-account-open]').forEach(button=>button.addEventListener('click',openAccount));
$('socialClose').onclick=closeAccount;$('socialGuest').onclick=closeAccount;$('socialSwitch').onclick=()=>setMode(mode==='login'?'register':'login');
$('socialReveal').onclick=()=>{const show=$('socialPassword').type==='password';$('socialPassword').type=show?'text':'password';$('socialReveal').textContent=show?'隐藏':'显示';$('socialReveal').setAttribute('aria-pressed',String(show));};
$('socialAuthForm').onsubmit=async event=>{event.preventDefault();if(busy)return;busy=true;$('socialSubmit').disabled=true;$('socialAuthStatus').textContent='连接中…';try{const result=await request(mode,{name:$('socialName').value,password:$('socialPassword').value,remember:$('socialRemember').checked});const verified=await request('session').catch(error=>{if(error.status===401){setMode('login');throw new Error('浏览器未保留登录 Cookie，请允许此站点 Cookie 后登录');}throw error;});setUser(verified.user||result.user);$('socialPassword').value='';$('socialAuthStatus').textContent=mode==='register'?'已创建账号并登录':'已登录';closeAccount();}catch(error){$('socialAuthStatus').textContent=message(error);}finally{busy=false;$('socialSubmit').disabled=false;}};
$('socialLogout').onclick=async()=>{try{await request('logout',{});setUser(null);closeChat();setMode('login');$('socialName').focus();}catch(error){$('socialAuthStatus').textContent=message(error);}};
$('socialChatToggle').onclick=()=>chatOpen?closeChat():openChat();$('socialChatClose').onclick=closeChat;
$('socialComposer').onsubmit=async event=>{event.preventDefault();const text=$('socialInput').value.trim();if(!text||$('socialSend').disabled)return;$('socialSend').disabled=true;pending=pending?.text===text?pending:{id:crypto.randomUUID(),text};try{const result=await request('messages',pending);addMessages([result.message]);$('socialInput').value='';pending=null;$('socialChatStatus').textContent='';}catch(error){$('socialChatStatus').textContent=message(error);}finally{$('socialSend').disabled=false;$('socialInput').focus();}};
window.addEventListener('keydown',event=>{if(event.isComposing||$('socialDialog').open)return;const typing=/INPUT|TEXTAREA|SELECT/.test(event.target.tagName)||event.target.isContentEditable;if(chatOpen&&event.key==='Escape'){event.preventDefault();event.stopImmediatePropagation();closeChat();}else if(event.key==='Enter'&&!typing&&!event.target.closest('button,a,dialog')){event.preventDefault();event.stopImmediatePropagation();openChat();}},true);
$('socialDialog').addEventListener('cancel',()=>{$('world').focus({preventScroll:true});});
document.addEventListener('visibilitychange',()=>{clearTimeout(pollTimer);if(!document.hidden)poll();});
new MutationObserver(()=>{const entered=$('world').dataset.entered==='true';shell.classList.toggle('in-scene',entered);if(entered)poll();}).observe($('world'),{attributes:true,attributeFilter:['data-entered']});
request('session').then(data=>setUser(data.user)).catch(()=>{});

// Pointer capture keeps dragging stable across the scene canvas and touch screens.
const chat=$('socialChat'),handle=$('socialDragHandle');let drag=null;
function place(x,y){const r=chat.getBoundingClientRect(),left=Math.max(8,Math.min(innerWidth-r.width-8,x)),top=Math.max(8,Math.min(innerHeight-r.height-8,y));chat.style.left=left+'px';chat.style.top=top+'px';chat.style.bottom='auto';return {x:left,y:top};}
try{const saved=JSON.parse(localStorage.getItem('refuge-chat-position'));if(saved&&Number.isFinite(saved.x)&&Number.isFinite(saved.y)){chat.style.left=Math.max(8,Math.min(innerWidth-408,saved.x))+'px';chat.style.top=Math.max(8,Math.min(innerHeight-300,saved.y))+'px';chat.style.bottom='auto';}}catch{}
handle.addEventListener('pointerdown',event=>{if(event.target.closest('button')||event.button!==0)return;event.preventDefault();const r=chat.getBoundingClientRect();drag={dx:event.clientX-r.left,dy:event.clientY-r.top};handle.setPointerCapture(event.pointerId);});
handle.addEventListener('pointermove',event=>{if(drag)place(event.clientX-drag.dx,event.clientY-drag.dy);});
function endDrag(event){if(!drag)return;drag=null;if(handle.hasPointerCapture(event.pointerId))handle.releasePointerCapture(event.pointerId);const r=chat.getBoundingClientRect();try{localStorage.setItem('refuge-chat-position',JSON.stringify({x:r.left,y:r.top}));}catch{}}
handle.addEventListener('pointerup',endDrag);handle.addEventListener('pointercancel',endDrag);
addEventListener('resize',()=>{if(chat.style.top){const r=chat.getBoundingClientRect();place(r.left,r.top);}});

let adminNext=null,adminBusy=false;
async function loadAccounts(more=false){
 if(adminBusy||user?.role!=='admin')return;adminBusy=true;$('socialAdminStatus').textContent='加载中…';
 try{const data=await request('admin/users',{after:more?adminNext:''});if(user?.role!=='admin')return;if(!more)$('socialAdminRows').replaceChildren();
 for(const account of data.users){const row=document.createElement('div');row.className='admin-row';const name=document.createElement('b'),time=document.createElement('small'),state=document.createElement('small');name.textContent=account.name+(account.role==='admin'?' · 管理员':'');time.textContent=account.lastLoginAt?'最近登录 '+new Date(account.lastLoginAt).toLocaleString('zh-CN'):'尚未登录';const update=until=>{state.textContent=until>Date.now()?'禁言至 '+new Date(until).toLocaleString('zh-CN'):'可发言';};update(account.mutedUntil);row.append(name,time,state);
 if(account.role!=='admin'){const controls=document.createElement('div'),select=document.createElement('select'),apply=document.createElement('button');select.setAttribute('aria-label',account.name+' 禁言时长');for(const [value,label] of [[3600,'禁言 1 小时'],[86400,'禁言 1 天'],[604800,'禁言 7 天'],[0,'解除禁言']]){const option=document.createElement('option');option.value=value;option.textContent=label;select.append(option);}apply.textContent='应用';apply.onclick=async()=>{apply.disabled=true;try{const result=await request('admin/mute',{userId:account.id,seconds:Number(select.value)});update(result.user.mutedUntil);$('socialAdminStatus').textContent=account.name+' · 已更新';}catch(e){$('socialAdminStatus').textContent=message(e);}finally{apply.disabled=false;}};controls.append(select,apply);row.append(controls);}
 $('socialAdminRows').append(row);}
 adminNext=data.next;$('socialAdminMore').hidden=!adminNext;$('socialAdminStatus').textContent='';
 }catch(e){$('socialAdminStatus').textContent=message(e);}finally{adminBusy=false;}
}
$('socialAdminOpen').onclick=()=>{$('socialAdminPanel').hidden=!$('socialAdminPanel').hidden;if(!$('socialAdminPanel').hidden)loadAccounts();};
$('socialAdminRefresh').onclick=()=>loadAccounts();$('socialAdminMore').onclick=()=>loadAccounts(true);
