import {renderChatText} from './chat-format.js?v=ai-66';
const local=/^(localhost|127\.0\.0\.1)$/.test(location.hostname),testMode=local?new URLSearchParams(location.search).get('social'):null;
const API=testMode==='local'?'http://127.0.0.1:8783':'https://birationalclass-d3fw2j6t76955af0-1493130792.ap-shanghai.app.tcloudbase.com'+(testMode==='test'?'/refuge-test':'/refuge');
const $=id=>document.getElementById(id);
let generation=0,user=null,mode='login',busy=false,chatOpen=false,pollTimer,fadeTimer,latest=0;
const seen=new Set();
async function request(path,data){
 const response=await fetch(API+'/api/'+path,{method:data?'POST':'GET',credentials:'include',headers:data?{'Content-Type':'application/json'}:{},body:data?JSON.stringify(data):undefined,signal:AbortSignal.timeout(path==='ai/start'?55000:12000)});
 const result=await response.json();if(!response.ok){const error=new Error(result.error||'连接暂不可用');error.status=response.status;throw error;}return result;
}
function message(error){return error.name==='TimeoutError'||error instanceof TypeError?'连接暂不可用，请重试':error.message;}
function setUser(value){generation++;user=value;const entryAccount=$('loading').querySelector('.arrival-account');entryAccount.hidden=!value;if(value)$('loading').querySelector('.arrival-entry').prepend(entryAccount);else $('loading').append(entryAccount);document.querySelectorAll('[data-account-open]').forEach(el=>{if(el.id!=='socialAccountToggle')el.textContent=value?value.name:'登录 / 注册';});$('socialAccountName').textContent=value?.name||'';$('socialAdminOpen').hidden=value?.role!=='admin';$('socialAISettings').hidden=value?.role!=='admin';$('socialAdminPanel').hidden=true;$('socialAdminRows').replaceChildren();$('socialAuthForm').hidden=!!value;$('socialAccountView').hidden=!value;for(const t of aiTimers.values())clearTimeout(t);aiTimers.clear();aiRows.clear();aiHistoryLoadedFor=null;if(!value){seen.clear();$('socialMessages').replaceChildren();latest=0;}clearTimeout(pollTimer);if(value){poll();loadAIHistory();}}
function setMode(value){mode=value;$('socialAuthTitle').textContent=value==='register'?'加入书院':'欢迎回来';$('socialSubmit').textContent=value==='register'?'创建账号':'登录';$('socialSwitch').textContent=value==='register'?'已有账号 · 登录':'创建一个账号';$('socialPassword').autocomplete=value==='register'?'new-password':'current-password';$('socialPassword').minLength=value==='register'?8:1;$('socialPassword').placeholder=value==='register'?'至少 8 位':'输入密码';$('socialAuthStatus').textContent='';}
function openAccount(){$('socialDialog').classList.toggle('arrival-login',$('world').dataset.entered!=='true');window.dispatchEvent(new Event('refuge-social-focus'));$('socialDialog').showModal();setMode(mode);if(!user)$('socialName').focus();else $('socialClose').focus();}
function closeAccount(){$('socialDialog').close();$('world').focus({preventScroll:true});}
function activity(){clearTimeout(fadeTimer);$('socialChat').classList.add('recent');fadeTimer=setTimeout(()=>{if(!chatOpen)$('socialChat').classList.remove('recent');},9000);}
function openChat(){if($('world').dataset.entered!=='true')return;if(!user){openAccount();return;}if(chatOpen){$('socialInput').focus();return;}const anchor=$('socialChatToggle').getBoundingClientRect();chatOpen=true;window.dispatchEvent(new Event('refuge-social-focus'));$('socialChat').classList.add('expanded');$('socialComposer').hidden=false;if(!chat.hasAttribute('data-default-position'))place(anchor.left,anchor.top);$('socialChatToggle').setAttribute('aria-expanded','true');$('socialChatToggle').hidden=true;$('socialInput').focus();activity();poll();}
function positionChatIcon(x,y){const icon=$('socialChatToggle');chat.removeAttribute('data-default-position');icon.removeAttribute('data-default-position');icon.style.left=Math.max(8,Math.min(innerWidth-42,x))+'px';icon.style.top=Math.max(8,Math.min(innerHeight-42,y))+'px';if(!chatOpen){const panel=$('socialChat');panel.style.left=icon.style.left;panel.style.top=icon.style.top;panel.style.bottom='auto';}}
function closeChat(){if(chatOpen&&!chat.hasAttribute('data-default-position')){const r=$('socialChat').getBoundingClientRect();positionChatIcon(r.left,r.top);}chatOpen=false;$('socialChat').classList.remove('expanded');$('socialComposer').hidden=true;$('socialChatToggle').setAttribute('aria-expanded','false');$('socialChatToggle').hidden=false;$('world').focus({preventScroll:true});activity();}
function fadeMessage(row){row.classList.add('fresh');setTimeout(()=>row.classList.remove('fresh'),9000);}
function addMessages(messages,initial=false){for(const item of messages){if(seen.has(item.id))continue;seen.add(item.id);const row=document.createElement('p'),name=document.createElement('b'),text=document.createElement('span'),time=document.createElement('time');time.dateTime=new Date(item.createdAt).toISOString();time.textContent=new Date(item.createdAt).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit',hour12:false});time.title=new Date(item.createdAt).toLocaleString('zh-CN');row.className=item.mine?'own':'';name.textContent=item.name;text.className='message-body';renderChatText(text,item.text);row.append(time,name,text);$('socialMessages').append(row);if(!initial)fadeMessage(row);if(!initial&&item.createdAt>latest)activity();latest=Math.max(latest,item.createdAt);}const publicRows=[...$('socialMessages').children].filter(row=>!row.dataset.aiId&&!row.classList.contains('ai-question'));while(publicRows.length>50)publicRows.shift().remove();$('socialMessages').scrollTop=$('socialMessages').scrollHeight;}
let polling=false,lastActivity=Date.now();
for(const type of ['pointerdown','keydown'])addEventListener(type,()=>{const idle=Date.now()-lastActivity>120000;lastActivity=Date.now();if(idle)poll();},{passive:true});
async function poll(){clearTimeout(pollTimer);if(!user||document.hidden||polling||$('world').dataset.entered!=='true'||Date.now()-lastActivity>120000)return;polling=true;const version=generation;try{const data=await request('messages');if(version!==generation)return;addMessages(data.messages,!seen.size);$('socialChatStatus').textContent='';}catch(e){if(e.status===401){setUser(null);$('socialChatStatus').textContent='登录已过期';}else $('socialChatStatus').textContent='连接中…';}finally{polling=false;if(user)pollTimer=setTimeout(poll,chatOpen?5000:60000);}}
const shell=document.createElement('div');shell.id='refugeSocial';shell.innerHTML=`
<button id="socialChatToggle" class="chrome icon-button" aria-label="拖动聊天位置，按回车聊天" aria-controls="socialChat" aria-expanded="false" title="拖动调整位置 · Enter 聊天" data-tip="Enter 聊天"><svg viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M5 4.5h14a2 2 0 0 1 2 2v9a2 2 0 0 1-2 2H9l-5 3v-3H5a2 2 0 0 1-2-2v-9a2 2 0 0 1 2-2Z"/><path d="M7.5 9h9M7.5 13h6"/></svg></button>
<button id="socialAccountToggle" class="icon-button" data-account-open aria-label="账号管理" aria-haspopup="dialog" aria-controls="socialDialog" title="账号管理" data-tip="账号管理"><svg viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="8" r="3.5"/><path d="M4.5 21v-2a7.5 7.5 0 0 1 15 0v2"/></svg></button>
<section id="socialChat" aria-label="书院全体聊天"><div class="social-chat-heading" id="socialDragHandle" title="拖动聊天窗口"><button id="socialAI" type="button" title="将当前三维画面发送给所选 AI，仅自己可见" aria-label="AI 解释当前画面">✧ <span>AI</span></button><button id="socialChatSettings" type="button" aria-label="聊天控制面板" title="聊天控制面板">⋯</button><button id="socialChatClose" aria-label="收起聊天">×</button></div><section id="socialChatPanel" hidden><label>AI 服务 <select id="socialProvider"><option value="openai">OpenAI</option><option value="qwen">通义千问</option></select></label><p id="socialProviderStatus"></p><small>仅点击 AI 时发送当前三维画面，解释仅自己可见。</small><form id="socialAISettings" hidden><label>模型 <input id="socialAIModel" autocomplete="off" placeholder="gpt-6-sol"></label><label>API Key <input id="socialAIKey" type="password" autocomplete="new-password" placeholder="仅保存在服务器"></label><button type="submit">保存 AI 配置</button></form></section><div id="socialMessages" role="log" aria-live="polite" aria-relevant="additions"></div><p id="socialChatStatus" role="status"></p><form id="socialComposer" hidden><textarea id="socialInput" rows="2" maxlength="300" placeholder="发送消息，或输入问题后点击 AI…" aria-label="聊天消息"></textarea><button id="socialSend" aria-label="发送消息">↵</button></form><button id="socialResize" type="button" aria-label="调整聊天窗口大小，方向键微调" title="拖动调整大小"><svg viewBox="0 0 16 16" aria-hidden="true"><path d="M5 13 13 5M9 13l4-4"/></svg></button></section>
<dialog id="socialDialog" aria-labelledby="socialAuthTitle"><button id="socialClose" aria-label="关闭账号窗口">×</button><p class="social-eyebrow">MATH REFUGE / ACCOUNT</p><h2 id="socialAuthTitle">欢迎回来</h2><form id="socialAuthForm"><label for="socialName">账号</label><input id="socialName" name="username" autocomplete="username" minlength="3" maxlength="24" required placeholder="3–24 字，中文、字母或数字"><label for="socialPassword">密码</label><div class="social-password"><input id="socialPassword" name="password" type="password" autocomplete="current-password" minlength="8" maxlength="128" required placeholder="至少 8 位"><button id="socialReveal" type="button" aria-label="显示密码" aria-pressed="false">显示</button></div><label class="social-remember"><input id="socialRemember" type="checkbox" checked>记住我 <span>30 天</span></label><button id="socialSubmit" type="submit">登录 <span>↗</span></button><button id="socialSwitch" type="button">创建一个账号</button></form><div id="socialAccountView" hidden><p id="socialAccountName"></p><p class="social-account-note">已登录书院</p><button id="socialAdminOpen" hidden>管理账号</button><section id="socialAdminPanel" hidden aria-label="账号与最近登录"><div class="admin-heading"><span>账号与最近登录</span><button id="socialAdminRefresh" type="button">刷新</button></div><div id="socialAdminRows"></div><button id="socialAdminMore" hidden>更多账号</button><p id="socialAdminStatus" role="status"></p></section><button id="socialLogout">退出登录</button></div><p id="socialAuthStatus" role="status"></p><button id="socialGuest">继续漫步</button></dialog>`;document.body.append(shell);document.querySelector('.transport').insertBefore($('socialAccountToggle'),$('settingsButton'));
for(const root of [$('loading'),$('error')]){const button=document.createElement('button');button.className='arrival-account';button.hidden=root===$('loading');button.dataset.accountOpen='';button.textContent='登录 / 注册';root.append(button);}
document.querySelectorAll('[data-account-open]').forEach(button=>button.addEventListener('click',openAccount));
$('socialClose').onclick=closeAccount;$('socialGuest').onclick=()=>{closeAccount();if($('world').dataset.entered!=='true'){window.refugeBoot?.prepareAudio();window.refugeBoot?.auth('guest');window.refugeBoot?.requestEntry();}};$('socialSwitch').onclick=()=>setMode(mode==='login'?'register':'login');
$('socialReveal').onclick=()=>{const show=$('socialPassword').type==='password';$('socialPassword').type=show?'text':'password';$('socialReveal').textContent=show?'隐藏':'显示';$('socialReveal').setAttribute('aria-pressed',String(show));};
$('socialAuthForm').onsubmit=async event=>{event.preventDefault();if(busy)return;if($('world').dataset.entered!=='true')window.refugeBoot?.prepareAudio();busy=true;$('socialSubmit').disabled=true;$('socialAuthStatus').textContent='连接中…';try{const result=await request(mode,{name:$('socialName').value,password:$('socialPassword').value,remember:$('socialRemember').checked});const verified=await request('session').catch(error=>{if(error.status===401){setMode('login');throw new Error('浏览器未保留登录 Cookie，请允许此站点 Cookie 后登录');}throw error;});setUser(verified.user||result.user);$('socialPassword').value='';$('socialAuthStatus').textContent=mode==='register'?'已创建账号并登录':'已登录';closeAccount();if($('world').dataset.entered!=='true'){window.refugeBoot?.auth('authenticated');window.refugeBoot?.requestEntry();}}catch(error){$('socialAuthStatus').textContent=message(error);}finally{busy=false;$('socialSubmit').disabled=false;}};
$('socialLogout').onclick=async()=>{try{await request('logout',{});setUser(null);closeChat();setMode('login');$('socialName').focus();}catch(error){$('socialAuthStatus').textContent=message(error);}};
$('socialChatToggle').onclick=event=>{if(bubbleMoved&&event.detail!==0){bubbleMoved=false;return;}$('world').focus({preventScroll:true});};$('socialChatClose').onclick=closeChat;
function sendOptimistic(text){
 const payload={id:crypto.randomUUID(),text},version=generation,row=document.createElement('p'),time=document.createElement('time'),name=document.createElement('b'),body=document.createElement('span'),status=document.createElement('button');
 row.className='own social-pending';time.dateTime=new Date().toISOString();time.title='本机时间 · 等待服务器确认';time.textContent=new Date().toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit',hour12:false});name.textContent=user.name;body.className='message-body';renderChatText(body,text);status.type='button';row.append(time,name,body,status);$('socialMessages').append(row);fadeMessage(row);$('socialMessages').scrollTop=$('socialMessages').scrollHeight;activity();
 async function deliver(){status.disabled=true;status.className='social-sending';status.textContent='';status.setAttribute('aria-label','发送中');status.title='发送中';
 try{const result=await request('messages',payload);if(version!==generation)return;row.remove();addMessages([result.message]);}
 catch(error){if(version!==generation)return;status.disabled=false;status.className='social-send-retry';status.textContent='重试';status.setAttribute('aria-label','发送失败，点击重试');status.title=message(error);}
 }
 status.onclick=deliver;deliver();
}
$('socialComposer').onsubmit=event=>{event.preventDefault();const text=$('socialInput').value.trim();if(!text||!user)return;$('socialInput').value='';$('socialInput').focus();sendOptimistic(text);};
window.addEventListener('keydown',event=>{if(event.isComposing||$('socialDialog').open)return;const typing=/INPUT|TEXTAREA|SELECT/.test(event.target.tagName)||event.target.isContentEditable;if(chatOpen&&event.key==='Escape'){event.preventDefault();event.stopImmediatePropagation();closeChat();}else if(event.key==='Enter'&&!typing&&(!event.target.closest('button,a,dialog')||event.target.id==='socialChatToggle')){event.preventDefault();event.stopImmediatePropagation();openChat();}},true);
$('socialDialog').addEventListener('cancel',()=>{$('world').focus({preventScroll:true});});
document.addEventListener('visibilitychange',()=>{clearTimeout(pollTimer);if(!document.hidden)poll();});
new MutationObserver(()=>{const entered=$('world').dataset.entered==='true';shell.classList.toggle('in-scene',entered);if(entered)poll();}).observe($('world'),{attributes:true,attributeFilter:['data-entered']});
let entryLoginPending=false,entryLoginError='';
function showEntryLogin(){
 if(!entryLoginPending||!window.refugeBoot?.previewReady||$('world').dataset.entered==='true')return;
 entryLoginPending=false;openAccount();if(entryLoginError)$('socialAuthStatus').textContent=entryLoginError;
}
window.addEventListener('refuge-preview-ready',showEntryLogin);
window.addEventListener('refuge-login',()=>{entryLoginPending=true;showEntryLogin();});
request('session').then(data=>{setUser(data.user);window.refugeBoot?.auth(data.user?'authenticated':'anonymous');if(!data.user){entryLoginPending=true;showEntryLogin();}}).catch(error=>{window.refugeBoot?.auth('anonymous');entryLoginPending=true;if(error.status!==401)entryLoginError='自动登录暂不可用，可手动登录或继续漫步。';showEntryLogin();});

// Pointer capture keeps dragging stable across the scene canvas and touch screens.
const chat=$('socialChat'),handle=$('socialDragHandle');let drag=null;
function place(x,y){const r=chat.getBoundingClientRect();chat.removeAttribute('data-default-position');const left=Math.max(8,Math.min(innerWidth-r.width-8,x)),top=Math.max(8,Math.min(innerHeight-r.height-8,y));chat.style.left=left+'px';chat.style.top=top+'px';chat.style.bottom='auto';return {x:left,y:top};}
// The default dock sits just above the bottom navigation. Explicit drags keep their saved position.
chat.setAttribute('data-default-position','');$('socialChatToggle').setAttribute('data-default-position','');
function layoutDefaultChat(){
 const footer=document.querySelector('footer');
 const top=footer?.getBoundingClientRect().top??innerHeight;
 shell.style.setProperty('--chat-bottom',Math.max(24,innerHeight-top+16)+'px');
}
const chatLayoutObserver=new ResizeObserver(layoutDefaultChat);
for(const el of document.querySelectorAll('footer'))chatLayoutObserver.observe(el);
layoutDefaultChat();
try{const saved=JSON.parse(localStorage.getItem('refuge-chat-position-v2'));if(saved&&Number.isFinite(saved.x)&&Number.isFinite(saved.y))positionChatIcon(saved.x,saved.y);}catch{}
handle.addEventListener('pointerdown',event=>{if(event.target.closest('button')||event.button!==0)return;event.preventDefault();const r=chat.getBoundingClientRect();drag={dx:event.clientX-r.left,dy:event.clientY-r.top};handle.setPointerCapture(event.pointerId);});
handle.addEventListener('pointermove',event=>{if(drag)place(event.clientX-drag.dx,event.clientY-drag.dy);});
function endDrag(event){if(!drag)return;drag=null;if(handle.hasPointerCapture(event.pointerId))handle.releasePointerCapture(event.pointerId);const r=chat.getBoundingClientRect();try{localStorage.setItem('refuge-chat-position-v2',JSON.stringify({x:r.left,y:r.top}));}catch{}}
handle.addEventListener('pointerup',endDrag);handle.addEventListener('pointercancel',endDrag);
addEventListener('resize',()=>{layoutDefaultChat();const automatic=chat.hasAttribute('data-default-position'),icon=$('socialChatToggle');if(!automatic){const r=(chatOpen?chat:icon).getBoundingClientRect();positionChatIcon(r.left,r.top);}if(chat.dataset.resized)sizeChat(parseFloat(chat.style.width),parseFloat(chat.style.getPropertyValue('--chat-height')),false);if(chatOpen&&!automatic){const r=chat.getBoundingClientRect();place(r.left,r.top);}});

let adminNext=null,adminBusy=false;
async function loadAccounts(more=false){
 if(adminBusy||user?.role!=='admin')return;adminBusy=true;$('socialAdminStatus').textContent='加载中…';
 try{const data=await request('admin/users',{after:more?adminNext:''});if(user?.role!=='admin')return;if(!more)$('socialAdminRows').replaceChildren();
 for(const account of data.users){const row=document.createElement('div');row.className='admin-row';const name=document.createElement('b'),time=document.createElement('small'),state=document.createElement('small');name.textContent=account.name+(account.role==='admin'?' · 管理员':'');time.textContent=account.lastLoginAt?'最近登录 '+new Date(account.lastLoginAt).toLocaleString('zh-CN'):'尚未登录';const update=until=>{state.textContent=until>Date.now()?'禁言至 '+new Date(until).toLocaleString('zh-CN'):'可发言';};update(account.mutedUntil);row.append(name,time,state);
 if(account.role!=='admin'){const controls=document.createElement('div'),select=document.createElement('select'),apply=document.createElement('button');select.setAttribute('aria-label',account.name+' 禁言时长');for(const [value,label] of [[3600,'禁言 1 小时'],[86400,'禁言 1 天'],[604800,'禁言 7 天'],[0,'解除禁言']]){const option=document.createElement('option');option.value=value;option.textContent=label;select.append(option);}apply.textContent='应用';apply.onclick=async()=>{apply.disabled=true;try{const result=await request('admin/mute',{userId:account.id,seconds:Number(select.value)});update(result.user.mutedUntil);$('socialAdminStatus').textContent=account.name+' · 已更新';}catch(e){$('socialAdminStatus').textContent=message(e);}finally{apply.disabled=false;}};controls.append(select,apply);row.append(controls);}
 $('socialAdminRows').append(row);}
 adminNext=data.next;$('socialAdminMore').hidden=!adminNext;$('socialAdminStatus').textContent='';
 }catch(e){$('socialAdminStatus').textContent=message(e);}finally{adminBusy=false;}
}
$('socialAdminOpen').onclick=()=>{$('socialAdminPanel').hidden=!$('socialAdminPanel').hidden;if(!$('socialAdminPanel').hidden)loadAccounts();};
$('socialAdminRefresh').onclick=()=>loadAccounts();$('socialAdminMore').onclick=()=>loadAccounts(true);

// The compact bubble shares the expanded window's saved anchor.
const bubble=$('socialChatToggle');let bubbleDrag=null,bubbleMoved=false;
bubble.style.touchAction='none';
bubble.addEventListener('pointerdown',event=>{if(event.button!==0)return;const r=bubble.getBoundingClientRect();bubbleMoved=false;bubbleDrag={x:event.clientX,y:event.clientY,left:r.left,top:r.top};bubble.setPointerCapture(event.pointerId);});
bubble.addEventListener('pointermove',event=>{if(!bubbleDrag)return;const dx=event.clientX-bubbleDrag.x,dy=event.clientY-bubbleDrag.y;if(!bubbleMoved&&Math.hypot(dx,dy)<4)return;bubbleMoved=true;positionChatIcon(bubbleDrag.left+dx,bubbleDrag.top+dy);});
function finishBubbleDrag(event){if(!bubbleDrag)return;bubbleDrag=null;if(bubble.hasPointerCapture(event.pointerId))bubble.releasePointerCapture(event.pointerId);if(bubbleMoved){const r=bubble.getBoundingClientRect();try{localStorage.setItem('refuge-chat-position-v2',JSON.stringify({x:r.left,y:r.top}));}catch{}}}
bubble.addEventListener('pointerup',finishBubbleDrag);bubble.addEventListener('pointercancel',finishBubbleDrag);

const resizeHandle=$('socialResize');let chatResize=null;
function sizeChat(width,height,atAnchor=true){const r=chat.getBoundingClientRect(),maxWidth=Math.min(912,Math.max(80,innerWidth-(atAnchor?r.left:16)-16)),maxHeight=Math.min(480,Math.max(80,innerHeight-(atAnchor?r.top:8)-8));chat.style.width=Math.min(maxWidth,Math.max(280,width))+'px';chat.style.setProperty('--chat-height',Math.min(maxHeight,Math.max(180,height))+'px');chat.dataset.resized='true';}
function saveChatSize(){try{if(!chat.hasAttribute('data-default-position')){const r=chat.getBoundingClientRect();localStorage.setItem('refuge-chat-position-v2',JSON.stringify({x:r.left,y:r.top}));}localStorage.setItem('refuge-chat-size',JSON.stringify({width:parseFloat(chat.style.width),height:parseFloat(chat.style.getPropertyValue('--chat-height'))}));}catch{}}
try{const saved=JSON.parse(localStorage.getItem('refuge-chat-size'));if(saved&&Number.isFinite(saved.width)&&Number.isFinite(saved.height))sizeChat(saved.width,saved.height,false);}catch{}
resizeHandle.addEventListener('pointerdown',event=>{if(event.button!==0)return;event.preventDefault();event.stopPropagation();const r=chat.getBoundingClientRect();chatResize={x:event.clientX,y:event.clientY,width:r.width,height:r.height};resizeHandle.setPointerCapture(event.pointerId);});
resizeHandle.addEventListener('pointermove',event=>{if(chatResize){if(chat.hasAttribute('data-default-position')){const r=chat.getBoundingClientRect();place(r.left,r.top);}sizeChat(chatResize.width+event.clientX-chatResize.x,chatResize.height+event.clientY-chatResize.y);}});
function endChatResize(event){if(!chatResize)return;chatResize=null;if(resizeHandle.hasPointerCapture(event.pointerId))resizeHandle.releasePointerCapture(event.pointerId);saveChatSize();}
resizeHandle.addEventListener('pointerup',endChatResize);resizeHandle.addEventListener('pointercancel',endChatResize);
resizeHandle.addEventListener('keydown',event=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(event.key))return;event.preventDefault();event.stopPropagation();const r=chat.getBoundingClientRect(),step=event.shiftKey?40:10;sizeChat(r.width+(event.key==='ArrowRight'?step:event.key==='ArrowLeft'?-step:0),r.height+(event.key==='ArrowDown'?step:event.key==='ArrowUp'?-step:0));saveChatSize();});

$('socialInput').addEventListener('keydown',event=>{if(event.key==='Enter'&&!event.shiftKey&&!event.isComposing){event.preventDefault();event.stopPropagation();$('socialComposer').requestSubmit();}});
let aiProviders=[],aiBusy=false,aiHistoryLoadedFor=null;const aiRows=new Map(),aiTimers=new Map();
function aiNotice(text){$('socialChatStatus').textContent=text;}
function showProvider(){const p=aiProviders.find(p=>p.id===$('socialProvider').value);$('socialProviderStatus').textContent=p?.configured?'已配置 · '+p.model:'尚未配置';$('socialAIModel').value=p?.model||($('socialProvider').value==='qwen'?'qwen-vl-plus':'gpt-6-sol');$('socialAIKey').value='';}
async function loadProviders(){try{aiProviders=(await request('ai/providers')).providers;showProvider();}catch(e){$('socialProviderStatus').textContent=message(e);}}
$('socialChatSettings').onclick=()=>{$('socialChatPanel').hidden=!$('socialChatPanel').hidden;if(!$('socialChatPanel').hidden)loadProviders();};
try{$('socialProvider').value=localStorage.getItem('refuge-ai-provider')||'openai';}catch{}
$('socialProvider').onchange=()=>{showProvider();try{localStorage.setItem('refuge-ai-provider',$('socialProvider').value);}catch{}};
$('socialAISettings').onsubmit=async event=>{event.preventDefault();const button=event.target.querySelector('button');button.disabled=true;try{await request('admin/ai',{provider:$('socialProvider').value,model:$('socialAIModel').value.trim(),key:$('socialAIKey').value.trim()});$('socialAIKey').value='';await loadProviders();$('socialProviderStatus').textContent+=' · 已保存';}catch(e){$('socialProviderStatus').textContent=message(e);}finally{button.disabled=false;}};
function drawAI(job){let row=aiRows.get(job.id);if(!row){row=document.createElement('p');row.className='ai-message';row.dataset.aiId=job.id;if(job.question){const q=document.createElement('p'),label=document.createElement('b'),content=document.createElement('span');q.className='own ai-question';label.textContent='你 · 仅自己可见';content.className='message-body';renderChatText(content,job.question);q.append(label,content);row.privateQuestion=q;$('socialMessages').append(q);}const name=document.createElement('b'),time=document.createElement('time'),body=document.createElement('span');name.textContent='✧ 书院 AI · 仅自己可见';body.className='message-body';row.append(time,name,body);aiRows.set(job.id,row);$('socialMessages').append(row);}const time=row.querySelector('time');time.textContent=new Date(job.updatedAt||job.createdAt).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'});time.title=new Date(job.createdAt).toLocaleString('zh-CN');const body=row.querySelector('.message-body');renderChatText(body,job.status==='completed'?job.text:job.status==='failed'?job.error||'AI 请求失败，请重试':['incomplete','cancelled'].includes(job.status)?'AI 未完成回答，请重新请求。':'正在理解画面…');row.classList.toggle('ai-working',!['completed','failed','incomplete','cancelled'].includes(job.status));$('socialMessages').scrollTop=$('socialMessages').scrollHeight;return row;}
function watchAI(job,version,failures=0){if(['completed','failed','incomplete','cancelled'].includes(job.status))return;clearTimeout(aiTimers.get(job.id));aiTimers.set(job.id,setTimeout(async()=>{if(version!==generation)return;try{const next=(await request('ai/poll',{id:job.id})).job;if(version!==generation)return;const row=drawAI(next);if(next.status==='completed'){fadeMessage(row);activity();}watchAI(next,version);}catch(e){if(version!==generation)return;aiNotice(message(e));if(failures<5&&e.status!==401)watchAI(job,version,failures+1);}},Math.min(30000,4000*2**failures)));}
async function loadAIHistory(){const id=user?.id,version=generation;if(!id)return;if(aiHistoryLoadedFor!==id){aiRows.clear();for(const t of aiTimers.values())clearTimeout(t);aiTimers.clear();}try{const {jobs}=await request('ai/history');if(version!==generation)return;aiHistoryLoadedFor=id;for(const job of jobs){drawAI(job);watchAI(job,version);}}catch{}}
$('socialAI').onclick=async()=>{if(aiBusy||!user)return;aiBusy=true;$('socialAI').disabled=true;const version=generation,id=crypto.randomUUID(),question=$('socialInput').value.trim()||'请解释当前画面，优先讲解其中可见的数学内容。';let preview;
 try{aiNotice('正在截取画面…');if(typeof window.refugeCaptureFrame!=='function')throw Error('场景尚未准备好');const image=window.refugeCaptureFrame();preview=drawAI({id,question,status:'starting',createdAt:Date.now()});preview.querySelector('.message-body').textContent='正在发送画面…';const result=await request('ai/start',{id,provider:$('socialProvider').value||'openai',image,question});if(version!==generation)return;preview.privateQuestion?.remove();preview.remove();aiRows.delete(id);if($('socialInput').value.trim()===question)$('socialInput').value='';const row=drawAI(result.job);if(result.job.status==='completed'){fadeMessage(row);activity();}watchAI(result.job,version);aiNotice('');
 }catch(e){if(version!==generation)return;if(preview){preview.classList.remove('ai-working');preview.querySelector('.message-body').textContent=message(e);}aiNotice(message(e));}finally{aiBusy=false;$('socialAI').disabled=false;}};
