import * as T from '../3d/vendor/three.module.js';
export function beaconProgress(values){const filled=values.filter(v=>Number.isInteger(v)&&v>=1&&v<=9).length;return {filled,total:81,wallLit:filled===81?8:Math.floor(filled*8/81)};}
export function installBoardBeacons(lift){
 const root=new T.Group();root.userData.landmark='nine-by-nine-beacon-pieces';lift.add(root);
 const stone=new T.MeshStandardMaterial({color:0xaaa895,roughness:.8}),cap=new T.MeshStandardMaterial({color:0xc9c2a4,roughness:.67}),dark=new T.MeshStandardMaterial({color:0x514d41,roughness:.9});
 const centers=Array.from({length:81},(_,k)=>({x:((44+(k%9+1.5)*106.4)/1152-.5)*10.8,z:((44+(Math.floor(k/9)+1.5)*106.4)/1152-.5)*10.8-.18}));
 // Shared geometry keeps 81 detailed pieces inexpensive even before scenery batching.
 const sections=[[[.42,.045,.38],[0,.822,0],cap],[[.30,.22,.28],[0,.955,0],stone],[[.39,.04,.36],[0,1.083,0],cap],[[.12,.07,.06],[0,1.11,-.15],stone],[[.12,.07,.06],[0,1.11,.15],stone],[[.06,.07,.12],[-.165,1.11,0],stone],[[.06,.07,.12],[.165,1.11,0],stone],[[.075,.10,.011],[0,.963,.146],dark]];
 const instances=[],matrix=new T.Matrix4();for(const [size,offset,material]of sections){const mesh=new T.InstancedMesh(new T.BoxGeometry(...size),material,81);centers.forEach((c,i)=>{matrix.makeTranslation(c.x+offset[0],offset[1],c.z+offset[2]);mesh.setMatrixAt(i,matrix);});mesh.computeBoundingSphere();root.add(mesh);instances.push(mesh);}
 const flameMaterial=new T.MeshBasicMaterial({color:0xff951f}),coreMaterial=new T.MeshBasicMaterial({color:0xffd35a}),emberMaterial=new T.MeshBasicMaterial({color:0xffcd69});const flameGeometry=new T.ConeGeometry(.10,.36,5),coreGeometry=new T.ConeGeometry(.056,.25,5),emberGeometry=new T.SphereGeometry(.013,4,3);
 const pieces=centers.map((c,index)=>{const fire=new T.Group();root.add(fire);fire.position.set(c.x,1.105,c.z);const outer=new T.Mesh(flameGeometry,flameMaterial);outer.position.y=.18;const inner=new T.Mesh(coreGeometry,coreMaterial);inner.position.set(.01,.125,.014);fire.add(outer,inner);const embers=Array.from({length:2},()=>{const m=new T.Mesh(emberGeometry,emberMaterial);fire.add(m);return m;});fire.visible=false;return {fire,embers,index,active:false,ignition:0};});return {root,pieces,instances,filled:0};
}
export function syncBoardBeacons(board,values,wall=[]){if(!board)return;const state=beaconProgress(values);board.filled=state.filled;const litColor=new T.Color(0xffcf86),unlitColor=new T.Color(0x70818a);for(const mesh of board.instances){values.forEach((v,i)=>mesh.setColorAt(i,Number.isInteger(v)&&v>=1&&v<=9?litColor:unlitColor));if(mesh.instanceColor)mesh.instanceColor.needsUpdate=true;}board.pieces.forEach((p,i)=>{const active=Number.isInteger(values[i])&&values[i]>=1&&values[i]<=9;if(active&&!p.active)p.ignition=0;p.active=active;p.fire.visible=active;if(!active)p.ignition=0;});wall.forEach((p,i)=>p.fire.visible=i<state.wallLit);return state;}
export function updateBoardBeacons(board,time,dt,reduced=false){if(!board)return;for(const p of board.pieces){if(!p.active)continue;p.ignition=reduced?1:Math.min(1,p.ignition+dt*3.5);const flicker=reduced?1:.90+.12*Math.sin(time*7+p.index*1.7)+.07*Math.sin(time*13+p.index);p.fire.scale.set(1,Math.max(.02,p.ignition*flicker),1);p.fire.rotation.y=reduced?0:time*.75+p.index;for(let j=0;j<p.embers.length;j++){const u=(time*.8+j*.5+p.index*.17)%1;p.embers[j].visible=!reduced;p.embers[j].position.set(Math.sin(u*6+p.index)*.06,.16+u*.30,Math.cos(u*7+p.index)*.045);p.embers[j].scale.setScalar(1-u);}}}
