/* Generated by scripts/build-lesson-data.cjs; edit exercises.js instead. */
/* Guided variations of the exercises in the supplied third-edition textbook. */
(()=>{
  const banks=window.CurrentLessonExercises;
  window.TextbookExercises={render(scene,bookId){
    const bank=banks[bookId];let q=0,answers=bank.map(()=>null),step=-1;
    const language=()=>window.CourseLanguage?.language==='en'?1:0;
    function go(index){q=Math.max(0,Math.min(bank.length,index));step=-1;draw();window.dispatchEvent(new Event('lesson-quiz-jump'));}
    function draw(){
      const l=language(),t=pair=>pair[l],reference=x=>l?x.ref.replace('综合变式','combined variation').replace('运算变式','operation variation').replace('方幂变式','power variation').replace('条件变式','assumption variation').replace('变式','variation'):x.ref;
      let status=document.querySelector('.quiz-status');
      if(!status){status=document.createElement('nav');status.className='quiz-status';document.querySelector('.experiment-head').append(status);}
      status.setAttribute('aria-label',l?'Answer status':'答题状态');
      status.innerHTML=`<span class="quiz-status-count">${l?'Answered':'已答'} ${answers.filter(a=>a!==null).length}/${bank.length}</span><div class="quiz-status-dots">${bank.map((x,i)=>{const state=answers[i]===null?'unanswered':answers[i]===x.answer?'correct':'incorrect',label={unanswered:['未作答','Unanswered'],correct:['正确','Correct'],incorrect:['待订正','Review needed']}[state][l];return `<button type="button" data-quiz-jump="${i}" data-state="${state}" aria-current="${q===i?'step':'false'}" aria-label="${l?'Variation':'演化题'} ${i+1} · ${label}" title="${reference(x)} · ${label}"></button>`;}).join('')}</div>`;
      status.onclick=e=>{const target=e.target.closest('[data-quiz-jump]');if(target)go(+target.dataset.quizJump);};
      if(q===bank.length){
        scene.innerHTML=`<div class="quiz-end"><h3>${l?'Exercise review':'练习回顾'}</h3><p>${l?'Answered':'已作答'} ${answers.filter(a=>a!==null).length} / ${bank.length} · ${l?'Correct':'正确'} ${answers.filter((a,i)=>a===bank[i].answer).length} / ${bank.length}</p><ol class="quiz-summary">${bank.map((x,i)=>`<li>${answers[i]===null?(l?'Unanswered':'未作答'):answers[i]===x.answer?'✓':'↺'} ${reference(x)} · ${t(x.title)}</li>`).join('')}</ol><div class="controls"><button id="quiz-return" type="button">${l?'Back to exercises':'返回习题'}</button><button id="quiz-retry" type="button">${l?'Try again':'重新练习'}</button></div></div>`;
        scene.querySelector('#quiz-return').onclick=()=>go(bank.length-1);scene.querySelector('#quiz-retry').onclick=()=>{answers=bank.map(()=>null);go(0);};return;
      }
      const x=bank[q],answered=answers[q]!==null,difficulty={basic:['基础','Basic'],intermediate:['进阶','Intermediate'],challenge:['挑战','Challenge']}[x.difficulty][l];
      scene.innerHTML=`<div class="quiz-number">${l?'Exercise':'习题'} ${reference(x)}</div><p class="quiz-progress">${l?'Variation':'演化题'} ${q+1} / ${bank.length} <span class="exercise-difficulty" data-level="${x.difficulty}">${difficulty}</span></p><h3 class="quiz-question">${t(x.title)}</h3><p class="exercise-question">${t(x.q)}</p><div class="quiz-options">${x.options.map((option,i)=>`<button type="button" data-answer="${i}" ${answered?'disabled':''} class="${answered?(i===x.answer?'correct':i===answers[q]?'incorrect':''):''}">${'ABCD'[i]} · ${t(option)}</button>`).join('')}</div>${answered?`<div class="quiz-feedback"><b>${answers[q]===x.answer?(l?'Correct. ':'判断正确。'):(l?'Review the reason. ':'再看关键理由。')}</b>${t(x.reason)}</div><div class="exercise-proof"><p class="section-small">${l?'Proof in steps':'证明分步'}</p>${step>=0?`<p class="criteria-step">${t(x.proof[step])}</p>`:''}<button type="button" id="exercise-proof-next" data-proof-complete="${step>=x.proof.length-1}">${step<x.proof.length-1?(l?'Reveal the next step':'展开下一步'):(l?'Restart the proof':'重看证明')}</button><span class="hint"> ${Math.max(0,step+1)}/${x.proof.length}</span></div><p class="insight">${l?'Return to the textbook: ':'回到教材：'}${t(x.extension)}</p>`:''}<div class="controls quiz-navigation"><button type="button" id="quiz-prev" ${q===0?'disabled':''}>${l?'Previous exercise':'上一题'}</button><button type="button" id="quiz-next">${q===bank.length-1?(l?'Review':'学习回顾'):(l?'Next exercise':'下一题')}</button></div>`;
      scene.querySelectorAll('[data-answer]').forEach(button=>button.onclick=()=>{answers[q]=+button.dataset.answer;draw();});
      scene.querySelector('#exercise-proof-next')?.addEventListener('click',()=>{step=step<x.proof.length-1?step+1:0;draw();});
      scene.querySelector('#quiz-prev').onclick=()=>go(q-1);scene.querySelector('#quiz-next').onclick=()=>go(q+1);
    }
    const rerender=()=>{if(scene.dataset.lessonScene==='check')draw();};
    window.addEventListener('course-language',rerender);
    window.addEventListener('lesson-topic',()=>window.removeEventListener('course-language',rerender),{once:true});
    draw();
  },banks};
})();
