/* Guided variations of the exercises in the supplied third-edition textbook. */
(()=>{
  const banks={
    '1.1':[
      {ref:'1-1 · 1(1)、2',title:['反例与证明漏洞','Counterexamples and a proof gap'],q:['在 S = {a,b} 上取 R = {(a,a)}。它满足哪些性质？','On S = {a,b}, let R = {(a,a)}. Which properties hold?'],options:[['对称、传递，但不反身','Symmetric and transitive, but not reflexive'],['反身、对称，但不传递','Reflexive and symmetric, but not transitive'],['三条性质全部满足','All three properties']],answer:0,reason:['b 与自身没有关系，因此不反身。唯一的有序对 (a,a) 满足对称性与传递性的要求。','Reflexivity fails at b. The only ordered pair, (a,a), satisfies the requirements for symmetry and transitivity.'],proof:[['对称性：若 xRy，则 x = y = a，所以 yRx。','Symmetry: xRy implies x = y = a, hence yRx.'],['传递性：若 xRy 且 yRz，则 x = y = z = a，所以 xRz。','Transitivity: xRy and yRz force x = y = z = a, hence xRz.'],['教材习题 2 的错误在于：对每个 a，未必存在 b 使 aRb。不能从一个没有保证的前提出发证明 aRa。','The error in Exercise 2 is assuming that each a is related to some b. That existence has not been established.']],extension:['再构造“只缺对称性”和“只缺传递性”的关系。','Construct relations that fail only symmetry and only transitivity.'],anchor:'relation'},
      {ref:'1-1 · 4',title:['映射的纤维','Fibres of a map'],q:['取 φ: ℤ → ℤ，φ(n) = n²，规定 a ∼ b ⇔ φ(a) = φ(b)。[3] 是什么？','Let φ: ℤ → ℤ, φ(n) = n², and define a ∼ b iff φ(a) = φ(b). What is [3]?'],options:[['{3}','{3}'],['{−3,3}','{−3,3}'],['所有奇数','All odd integers']],answer:1,reason:['n² = 9 的整数解恰为 ±3。一个等价类是映射取相同值的全部原像。','The integer solutions of n² = 9 are exactly ±3. An equivalence class is a fibre of the map.'],proof:[['φ(a) = φ(a)，所以反身性成立。','φ(a) = φ(a), so the relation is reflexive.'],['等号的对称性与传递性分别给出关系的对称性与传递性。','Symmetry and transitivity follow from the corresponding properties of equality.'],['一般地，[a] = φ⁻¹({φ(a)})；本例中 a ≠ 0 时为 {−a,a}，[0] = {0}。','In general, [a] = φ⁻¹({φ(a)}). Here [a] = {−a,a} for a ≠ 0, while [0] = {0}.']],extension:['把 φ 改成“除以 4 的余数”，写出各个等价类。','Replace φ by the remainder modulo 4 and describe every class.'],anchor:'quotient'},
      {ref:'1-1 · 5',title:['按子集大小分类','Classifying subsets by size'],q:['把教材中的四元素集先缩为 A = {1,2,3}。子集按元素个数等价，商集有多少个元素？','Start with A = {1,2,3}, one element smaller than the textbook example. Subsets are equivalent when they have the same size. How many elements are in the quotient?'],options:[['3','3'],['4','4'],['8','8']],answer:1,reason:['子集大小只能为 0、1、2、3，对应四个类。8 是全部子集的数量，不是类的数量。','The possible sizes are 0, 1, 2 and 3, giving four classes. Eight counts the subsets, not the classes.'],proof:[['把大小为 k 的子集收集成 Cₖ，其中 k = 0,1,2,3。','Let Cₖ consist of all subsets of size k, for k = 0,1,2,3.'],['这些类非空、互不相交，且覆盖 P(A)；每个子集恰有一个大小。','The classes are nonempty, disjoint and cover P(A), since each subset has exactly one size.'],['商集是 {C₀,C₁,C₂,C₃}。推广到 n 元集，商集有 n+1 个元素。','The quotient is {C₀,C₁,C₂,C₃}. For an n-element set, it has n+1 elements.']],extension:['回到教材的 A = {1,2,3,4}，列出各类及每类所含子集数。','Return to A = {1,2,3,4}; list the classes and count the subsets in each.'],anchor:'partition'},
      {ref:'1-1 · 6',title:['有理数模整数','Rational numbers modulo integers'],q:['在 ℚ 上规定 a ∼ b ⇔ a − b ∈ ℤ。哪一个数与 1/3 同类？','On ℚ, define a ∼ b iff a − b ∈ ℤ. Which number is equivalent to 1/3?'],options:[['4/3','4/3'],['1/2','1/2'],['−1/3','−1/3']],answer:0,reason:['4/3 − 1/3 = 1 是整数。这个等价类是 1/3 + ℤ。','The difference 4/3 − 1/3 = 1 is an integer. The class is 1/3 + ℤ.'],proof:[['0 ∈ ℤ，整数的相反数与和仍为整数，分别保证三条性质。','Zero is an integer, and integers are closed under negation and addition; these facts prove the three properties.'],['每个类为 q + ℤ，其中 q ∈ ℚ。','Every class has the form q + ℤ, with q ∈ ℚ.'],['每个类在 ℚ ∩ [0,1) 内有唯一代表元，即有理数的小数部分。','Each class has a unique representative in ℚ ∩ [0,1), its fractional part.']],extension:['说明为什么使用 [0,1] 作代表元区间会发生重复。','Explain why using [0,1] would duplicate a representative.'],anchor:'quotient'}
    ],
    '1.2':[
      {ref:'1-2 · 5',title:['平移后的加法','Shifted addition'],q:['把教材的常数 2 改为 3：在 ℤ 上定义 a ⊕ b = a+b−3。单位元和 a 的逆元分别是什么？','Replace the textbook constant 2 by 3: define a ⊕ b = a+b−3 on ℤ. What are the identity and the inverse of a?'],options:[['0 与 −a','0 and −a'],['3 与 6−a','3 and 6−a'],['3 与 3−a','3 and 3−a']],answer:1,reason:['a ⊕ 3 = a；a ⊕ (6−a) = 3。逆运算必须回到这个运算的单位元。','a ⊕ 3 = a and a ⊕ (6−a) = 3. Inverses must return the identity of this operation.'],proof:[['封闭性：a+b−3 仍为整数。','Closure: a+b−3 is an integer.'],['(a ⊕ b) ⊕ c = a+b+c−6 = a ⊕ (b ⊕ c)。','(a ⊕ b) ⊕ c = a+b+c−6 = a ⊕ (b ⊕ c).'],['3 是双侧单位元；6−a 是 a 的双侧逆元。因此构成交换群。','The identity is 3 and the inverse of a is 6−a. This is an abelian group.']],extension:['推广到 a ⊕ b = a+b−c，求单位元与逆元，再完成教材 c = 2 的证明。','Generalize to a ⊕ b = a+b−c, then complete the textbook case c = 2.'],anchor:'axioms'},
      {ref:'1-2 · 6(2)',title:['从运算表求逆元','Reading inverses from a table'],q:['在模 7 非零剩余类的乘法群 U(7) 中，[3] 的逆元是什么？','In the multiplicative group U(7) of nonzero residue classes modulo 7, what is the inverse of [3]?'],options:[['[2]','[2]'],['[4]','[4]'],['[5]','[5]']],answer:2,reason:['3 × 5 = 15 ≡ 1 (mod 7)，所以 [3][5] = [1]。','3 × 5 = 15 ≡ 1 (mod 7), so [3][5] = [1].'],proof:[['运算表第 [3] 行依次为 [3]、[6]、[2]、[5]、[1]、[4]。','The [3] row is [3], [6], [2], [5], [1], [4].'],['单位元 [1] 出现在第 [5] 列，所以候选逆元是 [5]。','The identity [1] occurs in column [5], giving the candidate inverse [5].'],['剩余类乘法可交换，因此另一侧也有 [5][3] = [1]。','Residue-class multiplication is commutative, so [5][3] = [1] as well.']],extension:['完整写出 U(7) 的运算表，并圈出每行的单位元。','Complete the multiplication table of U(7) and mark the identity in each row.'],anchor:'axioms'},
      {ref:'1-2 · 10',title:['多个因子的逆','Inverting a product'],q:['在任意群中，(abc)⁻¹ 应当写成哪一种顺序？','In an arbitrary group, which order gives (abc)⁻¹?'],options:[['a⁻¹b⁻¹c⁻¹','a⁻¹b⁻¹c⁻¹'],['c⁻¹b⁻¹a⁻¹','c⁻¹b⁻¹a⁻¹'],['b⁻¹a⁻¹c⁻¹','b⁻¹a⁻¹c⁻¹']],answer:1,reason:['撤销操作时次序反转。这里只使用结合律，不交换不同因子。','Undo the factors in reverse order. Associativity is used without commuting different factors.'],proof:[['(abc)(c⁻¹b⁻¹a⁻¹) = ab(cc⁻¹)b⁻¹a⁻¹ = a(bb⁻¹)a⁻¹ = e。','(abc)(c⁻¹b⁻¹a⁻¹) = ab(cc⁻¹)b⁻¹a⁻¹ = a(bb⁻¹)a⁻¹ = e.'],['反向相乘也得到 e，因此它是双侧逆元。','Multiplying in the reverse direction also gives e, so it is a two-sided inverse.'],['把三个因子推广到 r 个因子，可用归纳法完成教材习题。','Extend from three factors to r factors by induction.']],extension:['独立写出归纳步骤，并标明逆元唯一性用在哪里。','Write the induction step and identify where uniqueness of inverses is used.'],anchor:'properties'},
      {ref:'1-2 · 11',title:['由单侧等式推回另一侧','From one-sided to two-sided'],q:['已知 G 是群且 ab = e。怎样推出 b = a⁻¹？','Suppose G is a group and ab = e. How can we obtain b = a⁻¹?'],options:[['等式两侧左乘 a⁻¹','Multiply both sides on the left by a⁻¹'],['直接交换 a 与 b','Simply commute a and b'],['等式两侧左乘 b','Multiply both sides on the left by b']],answer:0,reason:['a⁻¹(ab) = a⁻¹e，经结合律化为 b = a⁻¹。','a⁻¹(ab) = a⁻¹e; associativity simplifies this to b = a⁻¹.'],proof:[['群中 a 的双侧逆元已存在。左乘 a⁻¹，得到 b = a⁻¹。','The two-sided inverse of a already exists in the group. Left multiplication gives b = a⁻¹.'],['于是 ba = a⁻¹a = e。','Therefore ba = a⁻¹a = e.']],extension:['区分“已经知道是群”和“正要证明是群”时能使用的条件。','Distinguish assumptions available inside a known group from assumptions in a group-recognition proof.'],anchor:'properties'},
      {ref:'1-2 · 12、13',title:['平方公式与交换性','Squares and commutativity'],q:['若群中对所有 a、b 都有 (ab)² = a²b²，怎样从 abab = aabb 得到交换性？','If (ab)² = a²b² for every a,b in a group, how does abab = aabb imply commutativity?'],options:[['左消去 a，再右消去 b','Cancel a on the left, then b on the right'],['直接删去相同字母，不考虑位置','Delete matching letters regardless of position'],['结合律本身就是交换律','Associativity already means commutativity']],answer:0,reason:['依次得到 bab = abb 与 ba = ab。消去必须在同一侧进行。','The two steps give bab = abb, then ba = ab. Cancellation must occur on the same side.'],proof:[['若 G 交换，则 abab = aabb，所以平方公式成立。','If G is abelian, abab = aabb, so the identity holds.'],['反过来，由对所有 a、b 成立的平方公式，两次消去得到 ba = ab。','Conversely, applying cancellation twice to the identity gives ba = ab for all a,b.'],['习题 12 中每个 x 满足 x² = e，因此 a²b² = e = (ab)²，可应用上述结论。','In Exercise 12, every x satisfies x² = e. Thus a²b² = e = (ab)², and the result applies.']],extension:['用 D₃ 中的 r、s 给出一般群不满足平方公式的反例。','Use r and s in D₃ to show that the square identity fails in a general group.'],anchor:'powers'},
      {ref:'1-2 · 15',title:['右侧条件判别群','Recognizing a group from right-sided conditions'],q:['已有结合律、右单位元 e，且每个 a 有右逆元 a′。证明还需要推出什么？','Assume associativity, a right identity e, and a right inverse a′ for every a. What remains to be proved?'],options:[['只需证明交换律','Only commutativity'],['e 也是左单位元，a′ 也是左逆元','e is also a left identity and a′ is also a left inverse'],['集合必须有限','The set must be finite']],answer:1,reason:['要验证教材的群定义，须将同侧条件升级为双侧条件。交换性和有限性都不是要求。','The group definition requires two-sided identities and inverses. Neither commutativity nor finiteness is required.'],proof:[['取 a′ 的右逆元 a″，即 aa′ = e，a′a″ = e。','Take a right inverse a″ of a′: aa′ = e and a′a″ = e.'],['a′a = (a′a)e = (a′a)(a′a″) = a′(aa′)a″ = (a′e)a″ = a′a″ = e。','a′a = (a′a)e = (a′a)(a′a″) = a′(aa′)a″ = (a′e)a″ = a′a″ = e.'],['ea = (aa′)a = a(a′a) = ae = a。因此两侧条件都成立。','ea = (aa′)a = a(a′a) = ae = a. Both conditions are now two-sided.']],extension:['对照定理 1.2.3 的左侧证明，指出两份证明的对应步骤。','Compare the argument with the left-sided proof of Theorem 1.2.3.'],anchor:'criteria'}
    ]
  };
  window.TextbookExercises={render(scene,bookId){
    const bank=banks[bookId];let q=0,answers=bank.map(()=>null),step=-1;
    const language=()=>window.CourseLanguage?.language==='en'?1:0;
    function draw(){
      const l=language(),t=pair=>pair[l];
      if(q===bank.length){scene.innerHTML=`<div class="quiz-end"><h3>${l?'Section practice completed':'本节教材练习完成'}</h3><p>${l?'Correct on first attempt':'首次作答正确'} ${answers.filter((a,i)=>a===bank[i].answer).length} / ${bank.length}</p><ol>${bank.map((x,i)=>`<li>${answers[i]===x.answer?'✓':'↺'} ${x.ref} · ${t(x.title)}</li>`).join('')}</ol><button id="quiz-retry" type="button">${l?'Try again':'重新练习'}</button></div>`;scene.querySelector('#quiz-retry').onclick=()=>{q=0;answers=bank.map(()=>null);step=-1;draw();};return;}
      const x=bank[q],answered=answers[q]!==null;
      scene.innerHTML=`<p class="quiz-progress">${l?'Adapted from textbook exercise':'教材习题演化'} ${x.ref} · ${q+1}/${bank.length}</p><h3 class="quiz-question">${t(x.title)}</h3><p class="exercise-question">${t(x.q)}</p><div class="quiz-options">${x.options.map((option,i)=>`<button type="button" data-answer="${i}" ${answered?'disabled':''} class="${answered?(i===x.answer?'correct':i===answers[q]?'incorrect':''):''}">${'ABC'[i]} · ${t(option)}</button>`).join('')}</div>${answered?`<div class="quiz-feedback"><b>${answers[q]===x.answer?(l?'Correct. ':'判断正确。'):(l?'Review the reason. ':'再看关键理由。')}</b>${t(x.reason)}</div><div class="exercise-proof"><p class="section-small">${l?'Proof in steps':'证明分步'}</p>${step>=0?`<p class="criteria-step">${t(x.proof[step])}</p>`:''}<button type="button" id="exercise-proof-next">${step<x.proof.length-1?(l?'Reveal the next step':'展开下一步'):(l?'Restart the proof':'重看证明')}</button><span class="hint"> ${Math.max(0,step+1)}/${x.proof.length}</span></div><p class="insight">${l?'Return to the textbook: ':'回到教材：'}${t(x.extension)}</p>`:''}<div class="controls"><button type="button" id="quiz-prev" ${q===0?'disabled':''}>${l?'Previous exercise':'上一题'}</button><button type="button" id="quiz-next" ${answered?'':'disabled'}>${q===bank.length-1?(l?'Review':'学习回顾'):(l?'Next exercise':'下一题')}</button></div>`;
      scene.querySelectorAll('[data-answer]').forEach(button=>button.onclick=()=>{answers[q]=+button.dataset.answer;draw();});
      scene.querySelector('#exercise-proof-next')?.addEventListener('click',()=>{step=step<x.proof.length-1?step+1:0;draw();});
      scene.querySelector('#quiz-prev').onclick=()=>{q--;step=-1;draw();};scene.querySelector('#quiz-next').onclick=()=>{q++;step=-1;draw();};
    }
    const rerender=()=>{if(scene.dataset.lessonScene==='check')draw();};
    window.addEventListener('course-language',rerender);
    window.addEventListener('lesson-topic',()=>{window.removeEventListener('course-language',rerender);},{once:true});
    draw();
  },banks};
})();
