const t=String.raw;
export const lessons=[
 {title:'一个双复形，两种微分',tag:'STARTING DATA',f:[t`\delta_1:K^{p,q}\to K^{p+1,q}`,t`\delta_2:K^{p,q}\to K^{p,q+1}`,t`\delta_1^2=\delta_2^2=0`,t`\delta_1\delta_2+\delta_2\delta_1=0`],text:'每个节点是一个向量空间，不是一个向量。横箭头增加第一指标，纵箭头增加第二指标。两条复合路径互为相反数。',note:'使用方向按钮突出横箭头或纵箭头；悬停时对应的实线箭头会高亮。图是示意窗口，窗口以外不自动取零。',proof:'对任意 a，两条路径给出 δ₂δ₁a 与 δ₁δ₂a。只有它们相加为零，总微分的平方才为零。'},
 {title:'总次数：沿对角线直和',tag:'THE TOTAL COMPLEX',f:[t`C^n:=\operatorname{Tot}^nK=\bigoplus_{i=0}^{n}K^{i,n-i}`,t`D:=\delta_1+\delta_2`,t`D:C^n\longrightarrow C^{n+1}`],text:'第一象限条件使每条总次数对角线只有有限项。选择 n，查看 Cⁿ 的所有直和因子；两种微分都把总次数提高一。',note:'金色对角线表示总次数 i+j=n。箭头的像落在下一条对角线上。',proof:'D²=δ₁²+(δ₁δ₂+δ₂δ₁)+δ₂²=0，因此 (C,D) 是一个上链复形。'},
 {title:'滤过：对角线上的一段',tag:'THE COLUMN FILTRATION',f:[t`F^pC^n:=\bigoplus_{i=p}^{n}K^{i,n-i}`,t`F^{p+1}C^n\subseteq F^pC^n`,t`D(F^pC^n)\subseteq F^pC^{n+1}`],text:'斜虚线框只圈住总次数 n 中第一指标不小于 p 的部分，终点是位置 (n,0) 的项。增加 p 就移去最左边的一项。',note:'p=n+1 时框内没有项，Fⁿ⁺¹Cⁿ=0；p=0 时得到整个 Cⁿ。右端 (n,0) 的项始终显示。',proof:'δ₁ 将 i 变成 i+1；δ₂ 保持 i。因此从 i≥p 出发，两者的像仍有第一指标 ≥p。注意 D 的像在总次数 n+1，未必留在原来的斜框内。'},
 {title:'E₀：先定义商，再识别',tag:'ASSOCIATED GRADED',f:[t`E_0^{p,q}:=\frac{F^pC^{p+q}}{F^{p+1}C^{p+q}}`,t`F^pC^{p+q}=K^{p,q}\oplus F^{p+1}C^{p+q}`,t`E_0^{p,q}\cong K^{p,q}`],text:'取商消去第一指标大于 p 的分量。这里的自然同构由取第 p 列分量给出，不需要选择补空间。',note:'亮起的单项表示自然识别后的 Kᵖᑫ；淡出的各项仍属于原双复形，并非被删除。这里 q=n−p。',proof:'投影 FᵖCⁿ→Kᵖⁿ⁻ᵖ 是满射，其核恰为 Fᵖ⁺¹Cⁿ。第一同构定理给出所示自然同构。'},
 {title:'E₁：对纵向微分求上同调',tag:'VERTICAL COHOMOLOGY',f:[t`d_0^{p,q}:E_0^{p,q}\longrightarrow E_0^{p,q+1}`,t`d_0^{p,q}\big(a+F^{p+1}C^{p+q}\big)\ :=Da+F^{p+1}C^{p+q+1}`,t`a\in F^pC^{p+q}`,t`E_1^{p,q}:=H^q(E_0^{p,\bullet},d_0)`],text:'D 先诱导商上的 d₀。δ₁ 的像位于下一列，在关联分次中为零，所以 d₀ 识别为 δ₂。逐列取上同调得到 E₁。',note:'E₀ 层上的微分是 d₀；逐列上同调给出 E₁。d₀ 属于 E₀，不是 E₁ 上的箭头。',proof:'D 保持 F，因此 d₀([a])=[Da] 良定义。在 E₀≅K 的识别下 d₀=δ₂，故 E₁=H(E₀,d₀) 就是逐列上同调。'},
 {title:'E₂：对诱导的横向微分求上同调',tag:'HORIZONTAL COHOMOLOGY ON E₁',f:[t`d_1:E_1^{p,q}\to E_1^{p+1,q}`,t`d_1^{p,q}[a]_1:=[\delta_1a]_1,\qquad a\in K^{p,q},\ \delta_2a=0`,t`E_2^{p,q}:=H^p(E_1^{\bullet,q},d_1)`],text:'这里的节点已经是垂直上同调。横箭头是 δ₁ 诱导的 d₁。不能把原来的 K 上的横向微分和 E₁ 上的 d₁ 当成同一个定义域上的映射。',note:'E₁ 层上的微分是 d₁；取其上同调得到 E₂。d₁ 始终属于 E₁ 层。',proof:'若 δ₂a=0，则 δ₂δ₁a=−δ₁δ₂a=0。将 a 换为 a+δ₂b 后，δ₁a 改变为 δ₁a−δ₂δ₁b；它们相差一个垂直边界。因此 d₁ 良定义。'},
 {title:'一般页：D 在不同商上诱导 dᵣ',tag:'FILTERED CYCLES AND BOUNDARIES',f:[t`Z_r^{p,q}:=F^pC^{p+q}\cap D^{-1}(F^{p+r}C^{p+q+1})`,t`B_r^{p,q}:=F^pC^{p+q}\cap D(F^{p-r}C^{p+q-1})`,t`E_r^{p,q}:=\frac{Z_r^{p,q}}{Z_{r-1}^{p+1,q-1}+B_{r-1}^{p,q}}\quad(r\ge1)`,t`\begin{gathered}d_r^{p,q}:E_r^{p,q}\longrightarrow E_r^{p+r,q-r+1}\\ d_r^{p,q}[a]_r:=[Da]_r,\quad a\in Z_r^{p,q}\end{gathered}`,t`E_{r+1}^{p,q}\cong\frac{\ker d_r^{p,q}}{\operatorname{im}d_r^{p-r,q+r-1}}`],text:'第 r 页的微分仍来自同一个 D。分子要求微分至少落到右边第 r 列；分母控制哪些代表元在本页等价。',note:'调节 r，金色箭头的位移始终是 (r,1−r)。一般页先由滤过复形定义；不是从 E₁ 的维数猜出来。',proof:'D 将分子映到目标分子，并将分母映到目标分母，因而诱导 dᵣ。继承 D²=0 后，再由核与像的商得到 Eᵣ₊₁≅H(Eᵣ,dᵣ)。完整商空间证明见讲义 §3。'}
];
export const convergence=[
 {title:'上同调先有一个滤过',tag:'THE TARGET',f:[t`H^n:=H^n(C^\bullet,D)`,t`F^pH^n:=\operatorname{im}\big(H^n(F^pC^\bullet,D)\to H^n(C^\bullet,D)\big)`,t`\operatorname{Gr}_F^pH^n:=F^pH^n/F^{p+1}H^n`],text:'FᵖHⁿ 由拥有 FᵖCⁿ 中闭代表元的类组成。它不是在看到稳定页后人为选择的滤过。图中展示一般构造；精确例子另在诱导信息中查看。',note:'调节 n、p，先定位可用闭代表元的滤过层，再观察总上同调中的像。',proof:'所有边界都在总复形中取模：一个位于 FᵖC 的闭链，也可能是从更左边来的总边界。因此需要使用 H(FᵖC)→H(C) 的像。'},
 {title:'有界性：最终得到真正的闭链',tag:'WHY THE PAGES STABILIZE',f:[t`F^{p+r}C^{n+1}=0\quad(r\gg0)`,t`Z_r^{p,q}=Z_\infty^{p,q}:=F^pC^n\cap\ker D`,t`B_r^{p,q}=B_\infty^{p,q}:=F^pC^n\cap\operatorname{im}D`],text:'对固定总次数，大到一定程度的滤过项为零；充分靠左的滤过项则是整个空间。这正是有限性在收敛证明中的用途。',note:'此处 E∞ 的下标表示稳定结果，不是让计算机执行无限次。第一象限下每个固定位置在足够大的页数后稳定。',proof:'当 Fᵖ⁺ʳCⁿ⁺¹=0 时，Da∈Fᵖ⁺ʳ 等价于 Da=0。当 Fᵖ⁻ʳCⁿ⁻¹=Cⁿ⁻¹ 时，Bᵣ 包含落在 FᵖCⁿ 内的所有总边界。'},
 {title:'构造收敛映射',tag:'THE CANONICAL MAP',f:[t`E_\infty^{p,q}:=\frac{Z_\infty^{p,q}}{Z_\infty^{p+1,q-1}+B_\infty^{p,q}}`,t`\theta^{p,q}:E_\infty^{p,q}\longrightarrow\operatorname{Gr}_F^pH^{p+q}`,t`\theta^{p,q}([a]_\infty):=[a]_H+F^{p+1}H^{p+q}`],text:'同一个闭代表元 a 在两边有不同的等价关系。θ 把稳定页的类送到总上同调的滤过商。',note:'比较映射使用同一个闭代表元；两边的分母对应两种取商操作。',proof:'分母中的 B∞ 是总边界，进入 H 后为零；分母中的 Z∞ᵖ⁺¹ 是下一层的闭链，进入 Gr 后为零。因此映射良定义，且由 FᵖH 的定义可知满射。'},
 {title:'核的计算：为什么是同构',tag:'THE CONVERGENCE THEOREM',f:[t`[a]_H\in F^{p+1}H^n\iff a=b+Dc`,t`b\in F^{p+1}C^n,\quad Db=0,\quad c\in C^{n-1}`,t`\ker\big(Z_\infty^{p,q}\to\operatorname{Gr}_F^pH^n\big)`,t`=Z_\infty^{p+1,q-1}+B_\infty^{p,q}`,t`E_\infty^{p,q}\xrightarrow[\theta^{p,q}]{\sim}\operatorname{Gr}_F^pH^{p+q}`],text:'核恰好就是定义 E∞ 时除去的子空间。第一同构定理完成证明，而不只是比较两边维数。',note:'这一步通过计算核，把“页的稳定”与“总上同调”联系起来，而不是只比较维数。',proof:'若 a 的类位于 Fᵖ⁺¹Hⁿ，则可取更高滤过中的闭链 b 表示同一个类，于是 a−b=Dc。反过来这样的分解显然映到零。'},
 {title:'读出商空间，不擅自拆开 H',tag:'WHAT CONVERGENCE MEANS',f:[t`E_r^{p,q}\Longrightarrow H^{p+q}(C,D)`,t`0\to F^{p+1}H^n\to F^pH^n\to E_\infty^{p,n-p}\to0`],text:'⇒ 表示稳定页识别为滤过商，并不是一条从 Eᵣ 到 H 的线性映射。向量空间的短正合列可以分裂，但这里没有指定典范分裂。',note:'区分：固定位置稳定；从某页起所有微分为零（退化）；稳定项识别为目标滤过商（收敛）。',proof:'自然性：若 TD=DT 且 T 保持 F，则 Tᵣ[a]ᵣ=[Ta]ᵣ。θ 两侧的作用都由同一个 Ta 给出，故 θ 与诱导作用交换。一般的 H 上的线性映射并不自动给出各页的作用。'}
];

export const initial=[
 {...lessons[0],title:'双复形与总复形',tag:'INITIAL DATA',note:''}
];

export const totalCohomology={title:'先取总复形的上同调',tag:'COHOMOLOGY / THE TARGET',f:[t`Z^n:=\ker(D:C^n\to C^{n+1})`,t`B^n:=\operatorname{im}(D:C^{n-1}\to C^n)\subseteq Z^n`,t`H^n(C,D):=Z^n/B^n`,t`[a]_H=[a+Db]_H\quad(a\in Z^n,\ b\in C^{n-1})`],text:'D²=0 保证每个边界都是闭链，所以这个商空间有定义。Hⁿ 是最终要理解的对象；接下来借助滤过构造 Eᵣ，逐步读出 Hⁿ 的关联分次。',note:'在原坐标图上沿对角线观察总微分。这里的 Hⁿ 是总上同调，不能把它放进某一个 Kᵖᑫ 节点。',proof:'如果 a=Db，那么 Da=D²b=0，故 im D ⊆ ker D。两个闭链给出同一个上同调类，当且仅当它们相差一个边界。'};
