import {cycleDefinition,boundaryDefinition,pageQuotientTex,generalPageDefinition} from './filtered-notation.js?v=89';
import {replaceMathContent} from './math-transitions.js?v=64';
import {cohomologyExposition} from './cohomology-view.js?v=76';
// This panel owns its proof steps. Navigating a proof never advances a notebook
// statement, changes a page, or cancels a diagram animation.
export function createDifferentialProof({board,math,language}){
 const R=String.raw,t=(zh,en)=>language()==='en'?en:zh;
 let context=null,key='',topic='d0',steps={e0:0,e1:0,er:0,d0:0,d1:0,dr:0},phase=3;
 const explanations={
  e0:[
   {name:['性质：关联分次','Property: associated graded'],f:[R`n=p+q,\qquad Z_0^{p,q}=F^pC^n`,R`Z_{-1}^{p+1,q-1}=F^{p+1}C^n`,R`B_{-1}^{p,q}=D(F^{p+1}C^{n-1})\subseteq F^{p+1}C^n`,R`Z_{-1}^{p+1,q-1}+B_{-1}^{p,q}=F^{p+1}C^n`,R`E_0^{p,q}=\frac{F^pC^n}{F^{p+1}C^n}=\operatorname{Gr}_F^pC^n`],note:['证明：D 保持滤过，故 Z₀ 的像条件自动成立；Z₋₁ 的条件更弱，也自动成立。B₋₁ 已在下一层滤过中，故分母就是下一层。−1 只是 Z、B 的辅助指标，不表示存在 E₋₁ 页。','Proof: D preserves the filtration, so the condition for Z₀ is automatic, as is the weaker condition for Z₋₁. B₋₁ already lies in the next filtration layer, so the denominator is that layer. The index −1 is auxiliary for Z and B; it does not introduce an E₋₁ page.']},
   {name:['元素与记号','Elements and notation'],f:[R`[a]_0:=a+F^{p+1}C^{p+q}\in E_0^{p,q},\quad a\in F^pC^{p+q}`,R`\begin{array}{rcl}\Phi_0^{p,q}:K^{p,q}&\xrightarrow{\sim}&E_0^{p,q}\\a&\longmapsto&[a]_0\end{array}`],note:['当 a∈K^{p,q} 时，先通过直和因子的自然嵌入将 a 视为 F^pC^{p+q} 中的元素，再取陪集。此处 [a]₀ 是滤过商中的类，无须 a 满足闭性条件。','For a∈K^{p,q}, first regard a as an element of F^pC^{p+q} via the natural inclusion of the direct summand, then take its coset. Here [a]₀ is a class in a filtration quotient; no cocycle condition on a is required.']},
   {name:['同构与逆映射','The isomorphism and its inverse'],f:[R`n=p+q,\qquad F^pC^n=K^{p,q}\oplus F^{p+1}C^n`,R`a=\sum_{i\ge p}a_i,\qquad a_i\in K^{i,n-i}`,R`(\Phi_0^{p,q})^{-1}([a]_0):=a_p`],note:['每个陪集都有唯一一个属于 K^{p,q} 的代表元，因此该映射是典范同构。E₀ 的定义仍然是商空间；动画采用此同构在同一位置标示两者。','Every coset has exactly one representative in K^{p,q}, so the map is a canonical isomorphism. E₀ remains defined as a quotient; the animation uses this identification to label both at the same position.']},
   {name:['代表元无关','Independence of representative'],f:[R`a,a'\in F^pC^{p+q}`,R`[a']_0=[a]_0\iff a'-a\in F^{p+1}C^{p+q}`,R`a'-a\in F^{p+1}C^{p+q}\iff a'_p=a_p`],note:['更高列的分量不会改变第 p 列分量，故逆映射不依赖代表元。','Higher-column components do not change the column-p component, so the inverse is independent of the representative.']},
   {name:['统一的滤过构造','One filtered construction'],f:[generalPageDefinition,R`Z_{r-1}^{p+1,q-1}=Z_r^{p,q}\cap F^{p+1}C^{p+q}`,R`Z_{r-1}^{p+1,q-1}+B_{r-1}^{p,q}\subseteq Z_r^{p,q}`],note:['Z、B 的同一子空间公式延伸至辅助指标 −1 后，所有 r≥0 的页都由同一个商定义。分母第一项满足同样的像条件，边界项因 D²=0 而闭，所以商有定义。Gr 是关联分次的记号，不含页数 r。','Extending the same subspace formulas for Z and B to the auxiliary index −1 gives one quotient definition for all r≥0. The first denominator term satisfies the same image condition, and boundaries are closed by D²=0, so the quotient is defined. Gr denotes associated graded, not a page index.']}

  ],
  d0:[
   {name:['诱导到商','Descend to the quotient'],f:[R`d_0:=\operatorname{Gr}_F D,\qquad a,a'\in F^pC^n`,R`D(F^{p+1}C^n)\subseteq F^{p+1}C^{n+1}`,R`a'-a\in F^{p+1}C^n\ \Longrightarrow\ Da'-Da\in F^{p+1}C^{n+1}`,R`d_0^{p,q}[a]_0:=[Da]_0,\qquad n=p+q`],note:["D 保持下一层滤过，故 d₀ 不依赖代表元。左侧为每个陪集选取唯一的 $a\\in K^{p,q}$；一般代表元属于 $F^pC^{p+q}$。", "D preserves the next filtration layer, so d₀ is independent of the representative. On the left choose the unique $a\\in K^{p,q}$ in each coset; a general representative belongs to $F^pC^{p+q}$."]},
   {name:['只保留纵向分量','The vertical component survives'],f:[R`a\in K^{p,q},\qquad Da=\delta_1^{p,q}a+\delta_2^{p,q}a`,R`\delta_1^{p,q}a\in K^{p+1,q}\subseteq F^{p+1}C^{p+q+1}`,R`[Da]_0=[\delta_2^{p,q}a]_0`],note:['横向分量在商中为零；这并不是总复形上 D=δ₂。','The horizontal component vanishes in the quotient; this does not mean D=δ₂ on the total complex.']},
   {name:['与同构相容','Compatibility with the isomorphism'],f:[R`d_0^{p,q}\circ\Phi_0^{p,q}=\Phi_0^{p,q+1}\circ\delta_2^{p,q}`,R`d_0^{p,q}=\Phi_0^{p,q+1}\circ\delta_2^{p,q}\circ(\Phi_0^{p,q})^{-1}`,R`(K^{\bullet,\bullet},\delta_2)\cong(E_0^{\bullet,\bullet},d_0)`],note:['d₀ 对应 δ₂，而非总微分 D。一般只需滤过复形 (C,F,D) 即可构造 (E₀,d₀)，无须预先将 D 分解。','d₀ corresponds to δ₂, not the total differential D. In general the filtered complex (C,F,D) defines (E₀,d₀) without a prior decomposition of D.']},
   {name:['平方为零','Square zero'],f:[R`d_0^{p,q+1}d_0^{p,q}[a]_0=[D^2a]_0=0`],note:['D²=0 下降为商上的 d₀²=0。','D²=0 descends to d₀²=0 on the quotient.']}
  ],
  e1:[
   {name:["滤过商定义", "Filtered-quotient definition"],f:[R`Z_1^{p,q}:=F^pC^{p+q}\cap D^{-1}(F^{p+1}C^{p+q+1})`,R`B_0^{p,q}:=F^pC^{p+q}\cap D(F^pC^{p+q-1})`,pageQuotientTex(1),R`Z_0^{p+1,q-1}=F^{p+1}C^{p+q}`],note:["这直接用总复形的滤过与 D 定义。D 保持滤过，故分母包含于分子。", "This uses the filtration and D on the total complex directly. Preservation of the filtration puts the denominator inside the numerator."]},
   {name:["性质：前一页上同调", "Property: preceding-page cohomology"],f:[R`E_1^{p,q}\xrightarrow[\sim]{\Psi_1^{p,q}}H^q(E_0^{p,\bullet},d_0)=\frac{\ker(d_0^{p,q})}{\operatorname{im}(d_0^{p,q-1})}`,R`E_1^{p,q}\cong H^q(K^{p,\bullet},\delta_2)`],note:["$E_1$ 与前一页的上同调自然同构，这是滤过商定义的性质。第二个同构由 $\\Phi_0$ 与纵向微分的相容性得到。", "The natural identification with preceding-page cohomology is a property of the filtered quotient. The identification with vertical cohomology follows from compatibility of $\\Phi_0$ with the vertical differential."]},
   {name:["元素与代表元", "Elements and representatives"],f:[R`[a]_1:=a+(F^{p+1}C^{p+q}+B_0^{p,q}),\quad a\in Z_1^{p,q}`,R`\Psi_1^{p,q}([a]_1)=[a]_0+\operatorname{im}(d_0^{p,q-1})`,R`a,a'\in K^{p,q},\quad\delta_2a=\delta_2a'=0`,R`[a]_1=[a']_1\iff a'-a\in\operatorname{im}(\delta_2^{p,q-1})`],note:["一般代表元是总上链；也可以取第 p 列的纵向闭元为代表。最后一行的等价只针对这样的 K 中代表元。", "A general representative is a total cochain. One may also choose a vertical cocycle in column p; the last equivalence concerns these representatives in K."]}
  ],
  d1:[
   {name:['闭代表元','Closed representatives'],f:[R`a\in K^{p,q},\quad\delta_2a=0`,R`\delta_2\delta_1a=-\delta_1\delta_2a=0`],note:['反交换关系保证 δ₁a 仍为纵向闭元。','Anticommutation makes δ₁a a vertical cocycle.']},
   {name:['代表元无关','Independence of representative'],f:[R`a'=a+\delta_2b,\qquad b\in K^{p,q-1}`,R`\delta_1a'-\delta_1a=-\delta_2\delta_1b`,R`[\delta_1a']_1=[\delta_1a]_1`],note:['差值是一个纵向边界，所以 d₁ 不依赖闭代表元的选择。','The difference is a vertical boundary, so d₁ is independent of the closed representative.']},
   {name:['由 D 给出','Induced by D'],f:[R`Da=\delta_1a\in F^{p+1}C^{p+q+1}`,R`d_1^{p,q}[a]_1=[Da]_1=[\delta_1a]_1`,R`d_1^{p+1,q}d_1^{p,q}[a]_1=[\delta_1^2a]_1=0`],note:['这与 D 诱导的定义一致。','This agrees with the definition induced by D.']}
  ],
  er:[
   {name:["滤过商定义", "Filtered-quotient definition"],f:[cycleDefinition,R`${boundaryDefinition},\quad s\ge-1`,R`N_r^{p,q}:=Z_{r-1}^{p+1,q-1}+B_{r-1}^{p,q}`,generalPageDefinition],note:["$C^\\bullet=\\operatorname{Tot}K$，$D=\\delta_1+\\delta_2$；Z、B 是总上链空间中的子空间。定义依赖原滤过复形 $(C^\\bullet,F,D)$，并非只依赖单个 K 小块。$r=1$ 时 $Z_0^{p+1,q-1}=F^{p+1}C^{p+q}$，见 2.5。", "Here $C^\\bullet=\\operatorname{Tot}K$ and $D=\\delta_1+\\delta_2$; Z and B are subspaces of total cochains. The definition uses $(C^\\bullet,F,D)$, not just a single K-term. At $r=1$, $Z_0^{p+1,q-1}=F^{p+1}C^{p+q}$, as in 2.5."]},
   {name:["本页的元素", "Elements of this page"],f:[R`[a]_r:=a+N_r^{p,q}\in E_r^{p,q},\qquad a\in Z_r^{p,q}`,R`[a]_r=[a']_r\iff a'-a\in N_r^{p,q}`,R`N_r^{p,q}\subseteq Z_r^{p,q}`],note:["代表元 a 可以含多个 K 分量，只要求 Da 落入指定滤过层。分母的高滤过部分满足同一条件，边界部分由 $D^2=0$ 满足闭性，因此商空间有定义。", "The representative may have several K-components; its differential must lie in the specified filtration. The higher-filtration part of the denominator satisfies this condition, and the boundary part is closed by $D^2=0$, so the quotient is defined."]},
   {name:["性质：前一页上同调", "Property: preceding-page cohomology"],f:[R`E_r^{p,q}\xrightarrow[\sim]{\Psi_r^{p,q}}H^{p,q}(E_{r-1},d_{r-1})\quad(r\ge1)`,R`H^{p,q}(E_{r-1},d_{r-1}):=\frac{\ker(d_{r-1}^{p,q})}{\operatorname{im}(d_{r-1}^{p-r+1,q+r-2})}`,R`\Psi_r^{p,q}([a]_r)=[a]_{r-1}+\operatorname{im}(d_{r-1}^{p-r+1,q+r-2})`],note:["$\\Psi_r$ 是自然同构。抽象谱序列把此同构关系列为定义条件；在这里从滤过复形出发，它是需要证明的性质。$r=1$ 时使用 2.3 的 $[a]_0$。", "$\\Psi_r$ is a natural isomorphism. The abstract definition requires this relationship; for the present filtered-complex construction it is a property to prove. At $r=1$ use $[a]_0$ from 2.3."]},
   {name:["证明：满射", "Proof: surjectivity"],f:[R`r\ge2,\quad\eta_{r-1}(a):=[a]_{r-1}`,R`\eta_{r-1}^{-1}(\ker d_{r-1})=Z_r^{p,q}+Z_{r-2}^{p+1,q-1}`,R`\eta_{r-1}(Z_r^{p,q})=\ker d_{r-1}`],note:["闭类的代表元 b 满足 $Db=u+Dv$，其中 u 在 $F^{p+r}C^{p+q+1}$ 中，v 在 $Z_{r-2}^{p+1,q-1}$ 中。换成 $a=b-v$ 就得到 $Z_r$ 中的代表，且不改变前一页的类。$r=1$ 的同一结论直接来自 d₀ 的定义。", "For a closed class represented by b, write $Db=u+Dv$ with u in $F^{p+r}C^{p+q+1}$ and v in $Z_{r-2}^{p+1,q-1}$. Replacing b by $a=b-v$ gives a representative in $Z_r$ of the same class. For $r=1$ this follows directly from the definition of d₀."]},
   {name:["证明：核与同构", "Proof: kernel and isomorphism"],f:[R`\gamma_r:Z_r^{p,q}\longrightarrow H^{p,q}(E_{r-1},d_{r-1})`,R`\gamma_r(a):=[a]_{r-1}+\operatorname{im}d_{r-1}`,R`\ker\gamma_r=Z_{r-1}^{p+1,q-1}+B_{r-1}^{p,q}=N_r^{p,q}`,R`E_r^{p,q}=Z_r^{p,q}/N_r^{p,q}\xrightarrow[\sim]{\Psi_r^{p,q}}H^{p,q}(E_{r-1},d_{r-1})`],note:["核中的 a 可写成 z+b，其中 z 属于 $F^{p+1}$，b 属于 $B_{r-1}$。因为 $Db=0$、Da 在 $F^{p+r}$ 中，z 属于 $Z_{r-1}^{p+1,q-1}$；反向包含也成立。结合满射性，由第一同构定理得到 $\\Psi_r$。", "An element a in the kernel has the form z+b with z in $F^{p+1}$ and b in $B_{r-1}$. Since $Db=0$ and Da lies in $F^{p+r}$, z lies in $Z_{r-1}^{p+1,q-1}$; the reverse inclusion also holds. Surjectivity and the first isomorphism theorem give $\\Psi_r$."]}
  ],
  dr:[
   {name:['新微分的来源','Source of the new differential'],f:[R`E_r^{p,q}\cong\frac{\ker(d_{r-1}^{p,q})}{\operatorname{im}(d_{r-1}^{p-r+1,q+r-2})}`,R`d_{r-1}|_{\ker d_{r-1}}=0`,R`d_r^{p,q}[a]_r:=[Da]_r,\qquad a\in Z_r^{p,q}`],note:['前一页的微分在闭元上已经为零，直接将它传到上同调只能得到零映射，不能据此得到新的 dᵣ。需返回原滤过复形，选取本页的总上链代表元 a，再施加 D。a 属于左侧标注的 Zᵣ，一般含有多个 K 分量，不能限定为单个 K 小块中的元素。','The preceding differential already vanishes on its cocycles, so descending that map to cohomology only gives zero, not the new dᵣ. Return to the original filtered complex, choose a total-cochain representative a for the current page, and apply D. As indicated on the left, a belongs to Zᵣ and may have several K-components; it need not lie in a single K-term.']},
   {name:['相同前页，不同微分','Same preceding page, different differential'],f:[R`\lambda\in\{0,1\},\quad K^{0,1}:=\langle x\rangle,\quad K^{1,0}:=\langle y\rangle`,R`K^{1,1}:=\langle u\rangle,\qquad K^{2,0}:=\langle z\rangle`,R`\delta_1x=u,\qquad\delta_2y=-u,\qquad\delta_1y=\lambda z`,R`E_1^{0,1}=\langle[x]_1\rangle,\quad E_1^{2,0}=\langle[z]_1\rangle,\quad d_1=0`,R`x+y\in Z_2^{0,1},\qquad D(x+y)=\lambda z`,R`d_2^{0,1}[x+y]_2=\lambda[z]_2`],note:['各空间均为一维，未列出的空间和微分均为零。两种 λ 给出相同的 (E₁,d₁)，且 E₂ 也相同；但 λ=0 时 d₂=0，λ=1 时 d₂ 是这两个一维项之间的同构。因此前一页的数据确实不足。','Each displayed space is one-dimensional; all unlisted spaces and differentials are zero. Both values of λ give the same (E₁,d₁), and the same E₂, but d₂ is zero for λ=0 and an isomorphism between the two one-dimensional terms for λ=1. The preceding-page data are therefore insufficient.']},

   {name:['分子映到分子','Map the numerator'],f:[R`n=p+q,\quad r\ge0,\quad a\in Z_r^{p,q}`,R`Da\in F^{p+r}C^{n+1},\qquad D(Da)=0`,R`Da\in Z_r^{p+r,q-r+1}`],note:['D²=0 保证像满足目标分子的条件。','D²=0 gives the target numerator condition.']},
   {name:['分母映到分母','Map the denominator'],f:[R`z\in Z_{r-1}^{p+1,q-1}\ \Longrightarrow\ z\in F^{p+1}C^n,\ Dz\in F^{p+r}C^{n+1}`,R`Dz\in F^{p+r}C^{n+1}\cap D(F^{p+1}C^n)=B_{r-1}^{p+r,q-r+1}`,R`b\in B_{r-1}^{p,q}\ \Longrightarrow\ Db=0`],note:['源分母的第一部分映入目标边界项，第二部分映为零。因此 D 诱导商上的映射。','The first part of the source denominator maps into the target boundary term; the second maps to zero. D therefore induces a quotient map.']},
   {name:['良定义与次数','Well-definedness and degree'],f:[R`a'=a+z+b\ \Longrightarrow\ [Da']_r=[Da]_r`,R`d_r^{p,q}:E_r^{p,q}\longrightarrow E_r^{p+r,q-r+1}`,R`d_r^{p,q}[a]_r:=[Da]_r`,R`(p+r)+(q-r+1)=p+q+1`],note:['z、b 属于上一步的两个源分母子空间。','Here z and b belong to the two source-denominator subspaces above.']},
   {name:['平方为零','Square zero'],f:[R`d_r^{p+r,q-r+1}d_r^{p,q}[a]_r=[D^2a]_r=0`,R`E_{r+1}^{p,q}\cong\frac{\ker(d_r^{p,q})}{\operatorname{im}(d_r^{p-r,q+r-1})}`],note:['平方为零来自 D²=0；下一页的滤过商与此微分的上同调自然同构。','Square zero follows from D²=0; the filtered quotient for the next page is naturally isomorphic to this cohomology.']}
  ]
 };
 function noteMath(text){if(/\$[^$]+\$/.test(text))return text.split(/(\$[^$]+\$)/g).map(part=>part.startsWith('$')?math(part.slice(1,-1)):noteMath(part)).join('');return text.replace(/K\^\{p,q\}|F\^pC\^\{p\+q\}|a∈K\^\{p,q\}|\[a\]₀/g,token=>math({'a∈K^{p,q}':R`a\in K^{p,q}`,'[a]₀':R`[a]_0`}[token]||token));}
 function paint(){
  const zero=context?.state.module==='learn'&&context.state.step===3;
  const firstTerm=context?.state.module==='learn'&&context.state.step===4&&context.state.notePage===0;
  const pageTopic=context?.state.module==='learn'?({3:['e0','d0'],4:['e1','d1'],5:['er','dr']}[context.state.step]?.[context.state.notePage]):null;
  if(pageTopic)topic=pageTopic;
  let html=['er','dr'].includes(topic)?`<p class="proof-emphasis"><strong>${t('关键区别','Key distinction')}</strong>${t(`对 ${math(R`r\ge1`)}，前一页 ${math(R`(E_{r-1},d_{r-1})`)} 通过取上同调确定 ${math(R`E_r`)} 的自然同构类，但不确定新的 ${math(R`d_r`)}。新微分需要原滤过复形 ${math(R`(C^\bullet,F,D)`)} 的信息。`,`For ${math(R`r\ge1`)}, the preceding page ${math(R`(E_{r-1},d_{r-1})`)} determines ${math(R`E_r`)} up to natural isomorphism by taking cohomology, but not the new ${math(R`d_r`)}. The new differential needs information from the original filtered complex ${math(R`(C^\bullet,F,D)`)}.`)}</p>`:'';
  if(topic==='cohom')html+=cohomologyExposition({r:context.construction?.r??Math.max(0,context.current-1),phase,point:context.point,math,t});
  else{
   const entries=explanations[topic],entry=entries[steps[topic]];
   html+=`<nav class="proof-steps" aria-label="${t('证明关键步骤','Key proof steps')}">${entries.map((e,i)=>`<button data-proof-step="${i}" aria-pressed="${steps[topic]===i}">${i+1}. ${t(...e.name)}</button>`).join('')}</nav><div class="proof-body"><div class="operation-content evolution-exposition">${entry.f.map(f=>`<div class="operation-equation">${math(f,true)}</div>`).join('')}</div><p class="operation-note">${noteMath(t(...entry.note))}</p></div>`;
  }
  if(['er','dr'].includes(topic))html+=`<p class="operation-note proof-reference"><a href="https://www.sas.rochester.edu/mth/sites/doug-ravenel/otherpapers/McCleary-UGSS.pdf#page=43" target="_blank" rel="noopener">McCleary, Definition 2.2, p. 29</a> · <a href="https://www.sas.rochester.edu/mth/sites/doug-ravenel/otherpapers/McCleary-UGSS.pdf#page=49" target="_blank" rel="noopener">Theorem 2.6, pp. 35–36</a></p>`;
  if(zero||firstTerm)html+=`<p class="operation-note proof-reference"><a href="https://www.sas.rochester.edu/mth/sites/doug-ravenel/otherpapers/McCleary-UGSS.pdf#page=49" target="_blank" rel="noopener">McCleary, Theorem 2.6, pp. 35–36</a> · <a href="https://www.sas.rochester.edu/mth/sites/doug-ravenel/otherpapers/McCleary-UGSS.pdf#page=62" target="_blank" rel="noopener">McCleary, Theorem 2.15, pp. 48–49</a></p>`;
  replaceMathContent(board,html);board.dataset.currentProofTopic=topic;board.dataset.currentProofStep=topic==='cohom'?phase:steps[topic];
 }
 board.addEventListener('click',e=>{
  const button=e.target.closest('[data-proof-topic],[data-proof-step],[data-co-phase]');if(!button||!context)return;
  e.stopPropagation();if(button.dataset.proofTopic){topic=button.dataset.proofTopic;}else if(button.dataset.proofStep!==undefined)steps[topic]=Number(button.dataset.proofStep);else phase=Number(button.dataset.coPhase);paint();
 });
 return {render(c){context=c;const nextKey=`${c.state.module}:${c.state.step}:${c.state.notePage}`;if(nextKey!==key){key=nextKey;topic=c.state.module==='learn'&&c.state.step===5?(c.state.notePage===0?'er':'dr'):c.state.module==='learn'&&c.state.step===4?(c.state.notePage===0?'e1':'d1'):c.construction?'cohom':'d0';}paint();},reset(){key='';context=null;steps={e0:0,e1:0,er:0,d0:0,d1:0,dr:0};phase=3;}};
}
