import {proofPanel,proofSections} from './proof-panel.js?v=99';
import {cycleDefinition,boundaryDefinition,pageQuotientTex,generalPageDefinition} from './filtered-notation.js?v=92';
import {replaceMathContent} from './math-transitions.js?v=97';
import {cohomologyExposition} from './cohomology-view.js?v=99';
// The current entry selects a concise exposition; details never change the diagram.
export function createDifferentialProof({board,math,language}){
 const R=String.raw,t=(zh,en)=>language()==='en'?en:zh;
 let context=null,key='',topic='d0';
 const explanations={
  e0:[
   {name:['页数与负指标','Pages and negative indices'],f:[R`n=p+q,\qquad r\le0`,R`Z_r^{p,q}=F^pC^n,\qquad Z_{r-1}^{p+1,q-1}=F^{p+1}C^n`,R`B_{r-1}^{p,q}=D(F^{p-r+1}C^{n-1})\subseteq F^{p+1}C^n`,R`\frac{Z_r^{p,q}}{Z_{r-1}^{p+1,q-1}+B_{r-1}^{p,q}}=\frac{F^pC^n}{F^{p+1}C^n}=\operatorname{Gr}_F^pC^n`],note:['本笔记的谱序列页按 $r\\ge0$ 编号。$r=0$ 的分母使用辅助子空间 $Z_{-1},B_{-1}$。若形式地把商公式代入 $r<0$，得到的仍是关联分次，并不自动为零；本笔记不另设负页。注意 $p-(r-1)=p-r+1$、$(p+1)+(r-1)=p+r$。','Pages in this notebook are indexed by $r\\ge0$. The denominator at $r=0$ uses the auxiliary subspaces $Z_{-1},B_{-1}$. Substituting $r<0$ formally into the quotient still gives the associated graded, not necessarily zero; no negative pages are introduced here. Note $p-(r-1)=p-r+1$ and $(p+1)+(r-1)=p+r$.']},
   {name:['性质：关联分次','Property: associated graded'],f:[R`n=p+q,\qquad Z_0^{p,q}=F^pC^n`,R`Z_{-1}^{p+1,q-1}=F^{p+1}C^n`,R`B_{-1}^{p,q}=D(F^{p+1}C^{n-1})\subseteq F^{p+1}C^n`,R`Z_{-1}^{p+1,q-1}+B_{-1}^{p,q}=F^{p+1}C^n`,R`E_0^{p,q}=\frac{F^pC^n}{F^{p+1}C^n}=\operatorname{Gr}_F^pC^n`],note:['证明：D 保持滤过，故 Z₀ 的像条件自动成立；Z₋₁ 的条件更弱，也自动成立。B₋₁ 已在下一层滤过中，故分母就是下一层。−1 只是 Z、B 的辅助指标，不表示存在 E₋₁ 页。','Proof: D preserves the filtration, so the condition for Z₀ is automatic, as is the weaker condition for Z₋₁. B₋₁ already lies in the next filtration layer, so the denominator is that layer. The index −1 is auxiliary for Z and B; it does not introduce an E₋₁ page.']},
   {name:['元素与记号','Elements and notation'],f:[R`[a]_0:=a+F^{p+1}C^{p+q}\in E_0^{p,q},\quad a\in F^pC^{p+q}`,R`\begin{array}{rcl}\Phi_0^{p,q}:K^{p,q}&\xrightarrow{\sim}&E_0^{p,q}\\a&\longmapsto&[a]_0\end{array}`],note:['当 a∈K^{p,q} 时，先通过直和因子的自然嵌入将 a 视为 F^pC^{p+q} 中的元素，再取陪集。此处 [a]₀ 是滤过商中的类，无须 a 满足闭性条件。','For a∈K^{p,q}, first regard a as an element of F^pC^{p+q} via the natural inclusion of the direct summand, then take its coset. Here [a]₀ is a class in a filtration quotient; no cocycle condition on a is required.']},
   {name:['同构与逆映射','The isomorphism and its inverse'],f:[R`n=p+q,\qquad F^pC^n=K^{p,q}\oplus F^{p+1}C^n`,R`a=\sum_{i\ge p}a_i,\qquad a_i\in K^{i,n-i}`,R`(\Phi_0^{p,q})^{-1}([a]_0):=a_p`],note:['每个陪集都有唯一一个属于 K^{p,q} 的代表元，因此该映射是典范同构。E₀ 的定义仍然是商空间；动画采用此同构在同一位置标示两者。','Every coset has exactly one representative in K^{p,q}, so the map is a canonical isomorphism. E₀ remains defined as a quotient; the animation uses this identification to label both at the same position.']},
   {name:['代表元无关','Independence of representative'],f:[R`a,a'\in F^pC^{p+q}`,R`[a']_0=[a]_0\iff a'-a\in F^{p+1}C^{p+q}`,R`a'-a\in F^{p+1}C^{p+q}\iff a'_p=a_p`],note:['更高列的分量不会改变第 p 列分量，故逆映射不依赖代表元。','Higher-column components do not change the column-p component, so the inverse is independent of the representative.']},
   {name:['统一的滤过构造','One filtered construction'],f:[generalPageDefinition,R`Z_{r-1}^{p+1,q-1}=Z_r^{p,q}\cap F^{p+1}C^{p+q}`,R`Z_{r-1}^{p+1,q-1}+B_{r-1}^{p,q}\subseteq Z_r^{p,q}`],note:['Z、B 的子空间公式对所有整数指标成立；所有 r≥0 的页都由同一个商定义。分母第一项满足同样的像条件，边界项因 D²=0 而闭，所以商有定义。Gr 是关联分次的记号，不含页数 r。','Defining Z and B for every integer index gives one quotient definition for all r≥0. The first denominator term satisfies the same image condition, and boundaries are closed by D²=0, so the quotient is defined. Gr denotes associated graded, not a page index.']}

  ],
  d0:[
   {name:['诱导到商','Descend to the quotient'],f:[R`d_0:=\operatorname{Gr}_F D,\qquad a,a'\in F^pC^n`,R`D(F^{p+1}C^n)\subseteq F^{p+1}C^{n+1}`,R`a'-a\in F^{p+1}C^n\ \Longrightarrow\ Da'-Da\in F^{p+1}C^{n+1}`,R`d_0^{p,q}[a]_0:=[Da]_0,\qquad n=p+q`],note:["D 保持下一层滤过，故 d₀ 不依赖代表元。左侧为每个陪集选取唯一的 $a\\in K^{p,q}$；一般代表元属于 $F^pC^{p+q}$。", "D preserves the next filtration layer, so d₀ is independent of the representative. On the left choose the unique $a\\in K^{p,q}$ in each coset; a general representative belongs to $F^pC^{p+q}$."]},
   {name:['只保留纵向分量','The vertical component survives'],f:[R`a\in K^{p,q},\qquad Da=\delta_1^{p,q}a+\delta_2^{p,q}a`,R`\delta_1^{p,q}a\in K^{p+1,q}\subseteq F^{p+1}C^{p+q+1}`,R`[Da]_0=[\delta_2^{p,q}a]_0`],note:['横向分量在商中为零；这并不是总复形上 D=δ₂。','The horizontal component vanishes in the quotient; this does not mean D=δ₂ on the total complex.']},
   {name:['与同构相容','Compatibility with the isomorphism'],f:[R`d_0^{p,q}\circ\Phi_0^{p,q}=\Phi_0^{p,q+1}\circ\delta_2^{p,q}`,R`d_0^{p,q}=\Phi_0^{p,q+1}\circ\delta_2^{p,q}\circ(\Phi_0^{p,q})^{-1}`,R`(K^{\bullet,\bullet},\delta_2)\cong(E_0^{\bullet,\bullet},d_0)`],note:['d₀ 对应 δ₂，而非总微分 D。一般只需滤过复形 (C,F,D) 即可构造 (E₀,d₀)，无须预先将 D 分解。','d₀ corresponds to δ₂, not the total differential D. In general the filtered complex (C,F,D) defines (E₀,d₀) without a prior decomposition of D.']},
   {name:['平方为零','Square zero'],f:[R`d_0^{p,q+1}d_0^{p,q}[a]_0=[D^2a]_0=0`],note:['D²=0 下降为商上的 d₀²=0。','D²=0 descends to d₀²=0 on the quotient.']}
  ],
  e1:[
   {name:["滤过商定义", "Filtered-quotient definition"],f:[R`Z_1^{p,q}:=F^pC^{p+q}\cap D^{-1}(F^{p+1}C^{p+q+1})`,R`B_0^{p,q}:=F^pC^{p+q}\cap D(F^pC^{p+q-1})`,pageQuotientTex(1),R`Z_0^{p+1,q-1}=F^{p+1}C^{p+q}`],note:["这直接用总复形的滤过与 D 定义。D 保持滤过，故分母包含于分子。", "This uses the filtration and D on the total complex directly. Preservation of the filtration puts the denominator inside the numerator."]},
   {name:["性质：前一页上同调", "Property: preceding-page cohomology"],f:[R`E_1^{p,q}\xrightarrow[\sim]{\Psi_1^{p,q}}H^q(E_0^{p,\bullet},d_0)=\frac{\ker(d_0^{p,q})}{\operatorname{im}(d_0^{p,q-1})}`,R`E_1^{p,q}\cong H^q(K^{p,\bullet},\delta_2)`],note:["$E_1$ 与前一页的上同调自然同构，这是滤过商定义的性质。第二个同构由 $\\Phi_0$ 与纵向微分的相容性得到。", "The natural identification with preceding-page cohomology is a property of the filtered quotient. The identification with vertical cohomology follows from compatibility of $\\Phi_0$ with the vertical differential."]},
   {name:["元素与代表元", "Elements and representatives"],f:[R`[a]_1:=a+(F^{p+1}C^{p+q}+B_0^{p,q}),\quad a\in Z_1^{p,q}`,R`\Psi_1^{p,q}([a]_1)=[a]_0+\operatorname{im}(d_0^{p,q-1})`,R`a,a'\in K^{p,q},\quad\delta_2a=\delta_2a'=0`,R`[a]_1=[a']_1\iff a'-a\in\operatorname{im}(\delta_2^{p,q-1})`],note:["一般代表元是总上链；也可以取第 p 列的纵向闭元为代表。最后一行的等价只针对这样的 K 中代表元。", "A general representative is a total cochain. One may also choose a vertical cocycle in column p; the last equivalence concerns these representatives in K."]}
  ],
  d1:[
   {name:['闭代表元','Closed representatives'],f:[R`a\in K^{p,q},\quad\delta_2a=0`,R`\delta_2\delta_1a=-\delta_1\delta_2a=0`],note:['反交换关系保证 δ₁a 仍为纵向闭元。','Anticommutation makes δ₁a a vertical cocycle.']},
   {name:['代表元无关','Independence of representative'],f:[R`a'=a+\delta_2b,\qquad b\in K^{p,q-1}`,R`\delta_1a'-\delta_1a=-\delta_2\delta_1b`,R`[\delta_1a']_1=[\delta_1a]_1`],note:['差值是一个纵向边界，所以 d₁ 不依赖闭代表元的选择。','The difference is a vertical boundary, so d₁ is independent of the closed representative.']},
   {name:['由 D 给出','Induced by D'],f:[R`Da=\delta_1a\in F^{p+1}C^{p+q+1}`,R`d_1^{p,q}[a]_1=[Da]_1=[\delta_1a]_1`,R`d_1^{p+1,q}d_1^{p,q}[a]_1=[\delta_1^2a]_1=0`],note:['这与 D 诱导的定义一致。','This agrees with the definition induced by D.']}
  ],
  er:[
   {name:['元素与代表元','Elements and representatives'],f:[R`r\ge0,\qquad a\in Z_r^{p,q}\subseteq F^pC^{p+q}`,R`[a]_r:=a+\bigl(Z_{r-1}^{p+1,q-1}+B_{r-1}^{p,q}\bigr)\in E_r^{p,q}`,R`a,a'\in Z_r^{p,q}`,R`[a]_r=[a']_r\iff a'-a\in Z_{r-1}^{p+1,q-1}+B_{r-1}^{p,q}`],note:["$[a]_r$ 是模掉分母子空间后的陪集。代表元 $a$ 是总上链，可以含多个 $K^{i,p+q-i}$ 分量；不能任取一个 $K^{p,q}$ 中的元素直接加上 $[\\,]_r$。图中先取首分量投影 $\\pi_p(Z_r^{p,q})\\subseteq K^{p,q}$，再取相应的商；$\\pi_p(a)=a_p$。","$[a]_r$ is a coset modulo the denominator. Its representative $a$ is a total cochain and may have several $K^{i,p+q-i}$ components; an arbitrary element of $K^{p,q}$ need not define $[a]_r$. The diagram first selects $\\pi_p(Z_r^{p,q})\\subseteq K^{p,q}$ and then takes the corresponding quotient, where $\\pi_p(a)=a_p$."]}
  ],
  dr:[
   {name:['箭头方向','Direction of the arrow'],f:[R`a\in Z_r^{p,q}\Longrightarrow Da\in F^{p+r}C^{p+q+1},\quad D(Da)=0`,R`D(Z_r^{p,q})=D(F^pC^{p+q})\cap F^{p+r}C^{p+q+1}`,R`D(Z_r^{p,q})=B_r^{p+r,q-r+1}\subseteq Z_r^{p+r,q-r+1}`,R`p'=p+r,\quad p'+q'=p+q+1\Longrightarrow q'=q-r+1`,R`d_r^{p,q}:E_r^{p,q}\longrightarrow E_r^{p+r,q-r+1}`],note:['设 $r\\ge0$。等式使用 $D(U\\cap D^{-1}V)=D(U)\\cap V$；边界包含于闭元由 $D^2=0$ 保证。微分的双次数是 $(r,1-r)$：$d_0$ 向上，$d_1$ 向右，$d_2$ 向右两格、向下一格。箭头留在第 $r$ 页内，不沿页数轴移动。','Let $r\\ge0$. The equality uses $D(U\\cap D^{-1}V)=D(U)\\cap V$; $D^2=0$ puts boundaries in cocycles. The bidegree is $(r,1-r)$: $d_0$ points up, $d_1$ right, and $d_2$ two columns right and one row down. The arrow stays on page $r$; it does not move along the page axis.']},
   {name:['新微分的来源','Source of the new differential'],f:[R`E_r^{p,q}\cong\frac{\ker(d_{r-1}^{p,q})}{\operatorname{im}(d_{r-1}^{p-r+1,q+r-2})}\quad(r\ge1)`,R`d_{r-1}|_{\ker d_{r-1}}=0`,R`d_r^{p,q}[a]_r:=[Da]_r,\qquad a\in Z_r^{p,q}`],note:['前一页的微分在闭元上已经为零，直接将它传到上同调只能得到零映射，不能据此得到新的 dᵣ。需返回原滤过复形，选取本页的总上链代表元 a，再施加 D。a 属于左侧标注的 Zᵣ，一般含有多个 K 分量，不能限定为单个 K 小块中的元素。','The preceding differential already vanishes on its cocycles, so descending that map to cohomology only gives zero, not the new dᵣ. Return to the original filtered complex, choose a total-cochain representative a for the current page, and apply D. As indicated on the left, a belongs to Zᵣ and may have several K-components; it need not lie in a single K-term.']},
   {name:['相同前页，不同微分','Same preceding page, different differential'],f:[R`\lambda\in\{0,1\},\quad K^{0,1}:=\langle x\rangle,\quad K^{1,0}:=\langle y\rangle`,R`K^{1,1}:=\langle u\rangle,\qquad K^{2,0}:=\langle z\rangle`,R`\delta_1x=u,\qquad\delta_2y=-u,\qquad\delta_1y=\lambda z`,R`E_1^{0,1}=\langle[x]_1\rangle,\quad E_1^{2,0}=\langle[z]_1\rangle,\quad d_1=0`,R`x+y\in Z_2^{0,1},\qquad D(x+y)=\lambda z`,R`d_2^{0,1}[x+y]_2=\lambda[z]_2`],note:['各空间均为一维，未列出的空间和微分均为零。两种 λ 给出相同的 (E₁,d₁)，且 E₂ 也相同；但 λ=0 时 d₂=0，λ=1 时 d₂ 是这两个一维项之间的同构。因此前一页的数据确实不足。','Each displayed space is one-dimensional; all unlisted spaces and differentials are zero. Both values of λ give the same (E₁,d₁), and the same E₂, but d₂ is zero for λ=0 and an isomorphism between the two one-dimensional terms for λ=1. The preceding-page data are therefore insufficient.']},

   {name:['分子映到分子','Map the numerator'],f:[R`n=p+q,\quad r\ge0,\quad a\in Z_r^{p,q}`,R`Da\in F^{p+r}C^{n+1},\qquad D(Da)=0`,R`Da\in Z_r^{p+r,q-r+1}`],note:['D²=0 保证像满足目标分子的条件。','D²=0 gives the target numerator condition.']},
   {name:['分母映到分母','Map the denominator'],f:[R`z\in Z_{r-1}^{p+1,q-1}\ \Longrightarrow\ z\in F^{p+1}C^n,\ Dz\in F^{p+r}C^{n+1}`,R`Dz\in F^{p+r}C^{n+1}\cap D(F^{p+1}C^n)=B_{r-1}^{p+r,q-r+1}`,R`b\in B_{r-1}^{p,q}\ \Longrightarrow\ Db=0`],note:['源分母的第一部分映入目标边界项，第二部分映为零。因此 D 诱导商上的映射。','The first part of the source denominator maps into the target boundary term; the second maps to zero. D therefore induces a quotient map.']},
   {name:['良定义与次数','Well-definedness and degree'],f:[R`a'=a+z+b\ \Longrightarrow\ [Da']_r=[Da]_r`,R`d_r^{p,q}:E_r^{p,q}\longrightarrow E_r^{p+r,q-r+1}`,R`d_r^{p,q}[a]_r:=[Da]_r`,R`(p+r)+(q-r+1)=p+q+1`],note:['z、b 属于上一步的两个源分母子空间。','Here z and b belong to the two source-denominator subspaces above.']},
   {name:['平方为零','Square zero'],f:[R`d_r^{p+r,q-r+1}d_r^{p,q}[a]_r=[D^2a]_r=0`,R`E_{r+1}^{p,q}\cong\frac{\ker(d_r^{p,q})}{\operatorname{im}(d_r^{p-r,q+r-1})}`],note:['平方为零来自 D²=0；下一页的滤过商与此微分的上同调自然同构。','Square zero follows from D²=0; the filtered quotient for the next page is naturally isomorphic to this cohomology.']}
  ]
 };
 function noteMath(text){if(/\$[^$]+\$/.test(text))return text.split(/(\$[^$]+\$)/g).map(part=>part.startsWith('$')?math(part.slice(1,-1)):noteMath(part)).join('');return text.replace(/K\^\{p,q\}|F\^pC\^\{p\+q\}|a∈K\^\{p,q\}|\[a\]₀/g,token=>math({'a∈K^{p,q}':R`a\in K^{p,q}`,'[a]₀':R`[a]_0`}[token]||token));}
 function paint(){
  const pageTopic=context?.state.module==='learn'?({3:['e0','d0'],4:['e1','d1'],5:['er','dr']}[context.state.step]?.[context.state.notePage]):null;
  if(pageTopic)topic=pageTopic;
  if(topic==='cohom'){
   replaceMathContent(board,cohomologyExposition({r:context.construction?.r??Math.max(0,context.current-1),point:context.point,math,t,language}));
  }else{
   const summaries={
    e0:{f:explanations.e0[2].f,note:t('先将 K 中的元素自然嵌入滤过项，再取陪集；这里无需闭性条件。','Include the K-summand in the filtration term, then take its coset; no cocycle condition is required.')},
    d0:{f:[R`[Da]_0=[\delta_2^{p,q}a]_0\quad(a\in K^{p,q})`,explanations.d0[2].f[0]],note:t('横向分量落入下一层滤过，在商中为零。因此 d₀ 对应纵向微分，而 D 本身仍有两个分量。','The horizontal component lies in the next filtration and vanishes in the quotient. Thus d₀ corresponds to the vertical differential, while D itself retains both components.')},
    e1:{f:[explanations.e1[1].f[0],explanations.e1[2].f[0]],note:t('E₁ 自然同构于逐列上同调；陪集的代表元属于 Z₁。','E₁ is naturally isomorphic to column cohomology; a coset representative lies in Z₁.')},
    d1:{f:[explanations.d1[2].f[1],R`\delta_2a=0,\quad a\in K^{p,q}`],note:t('反交换关系使 δ₁ 保持纵向闭元和边界，因此这个映射不依赖代表元。','Anticommutation makes δ₁ preserve vertical cocycles and boundaries, so this map is independent of the representative.')},
    er:{f:[explanations.er[0].f[1],R`a\in Z_r^{p,q}\subseteq F^pC^{p+q}`],note:t('此处是模掉分母后的陪集。代表元是总上链，可以包含多个 K 分量。','This is a coset modulo the denominator. Its representative is a total cochain and may have several K-components.')},
    dr:{f:[R`D(Z_r^{p,q})\subseteq Z_r^{p+r,q-r+1}`,R`d_r^{p,q}[a]_r=[Da]_r`],note:t(`双次数为 ${math('(r,1-r)')}。前一页上同调确定 ${math('E_r')} 的自然同构类，但新的 ${math('d_r')} 仍需要原滤过复形中的 ${math('D')}。`,`The bidegree is ${math('(r,1-r)')}. Preceding-page cohomology identifies ${math('E_r')}, but the new ${math('d_r')} still needs ${math('D')} in the original filtered complex.`)}
   },summary=summaries[topic];
   const details=proofSections(explanations[topic],{math,title:e=>t(...e.name),note:e=>noteMath(t(...e.note))});
   replaceMathContent(board,proofPanel({key:topic,title:t('页、代表元与诱导微分','Pages, representatives and induced differentials'),formulas:summary.f,note:summary.note,details:details+'<p><a href="https://www.sas.rochester.edu/mth/sites/doug-ravenel/otherpapers/McCleary-UGSS.pdf#page=49" target="_blank" rel="noopener">McCleary, Theorem 2.6</a></p>',math,language}));
  }
  board.dataset.currentProofTopic=topic;delete board.dataset.currentProofStep;
 }
 return {render(c){context=c;const nextKey=`${c.state.module}:${c.state.step}:${c.state.notePage}`;if(nextKey!==key){key=nextKey;topic=c.state.module==='learn'&&c.state.step===5?(c.state.notePage===0?'er':'dr'):c.state.module==='learn'&&c.state.step===4?(c.state.notePage===0?'e1':'d1'):c.construction?'cohom':'d0';}paint();},reset(){key='';context=null;}};
}
