import {proofPanel} from './proof-panel.js?v=155';
const R=String.raw;
export const hodgeTitles=[['复微分形式','Complex differential forms'],['Dolbeault 双复形','Dolbeault double complex'],['Hodge–de Rham 谱序列','Hodge–de Rham spectral sequence'],['Hodge 滤过','Hodge filtration'],['Kähler 情形的退化','Kähler degeneration'],['Hodge 分解','Hodge decomposition']];
export const hodgeContent={title:'Hodge decomposition',f:[
 R`\begin{gathered}\dim_{\mathbb C}X=m,\\\mathcal A^{p,q}(X),\quad 0\le p,q\le m,\\\mathcal A^n(X;\mathbb C)=\bigoplus_{p+q=n}\mathcal A^{p,q}(X)\end{gathered}`,
 R`\begin{gathered}K^{p,q}:=\mathcal A^{p,q}(X)\\\delta_1=\partial,\quad\delta_2=\bar\partial\\(C^\bullet,D)=(\mathcal A^\bullet(X;\mathbb C),d)\end{gathered}`,
 R`\begin{gathered}E_1^{p,q}\cong H^q(X,\Omega_X^p)\\E_1^{p,q}\Longrightarrow H_{\mathrm{dR}}^{p+q}(X;\mathbb C)\end{gathered}`,
 R`\begin{gathered}F^pC^n=\bigoplus_{a\ge p}\mathcal A^{a,n-a}(X)\\F^pH^n=\operatorname{im}\big(H^n(F^pC^\bullet)\to H^n\big)\\E_\infty^{p,q}\cong\operatorname{Gr}_F^pH^{p+q}\end{gathered}`,
 R`\begin{gathered}d_r^{p,q}=0\quad(r\ge1,\ \forall p,q)\\E_1^{p,q}\cong E_\infty^{p,q}\cong\operatorname{Gr}_F^pH^{p+q}\end{gathered}`,
 R`\begin{gathered}H^n=\bigoplus_{p+q=n}H^{p,q}(X)\\H^{p,q}(X)=F^pH^n\cap\overline{F^qH^n}\\H^{p,q}(X)\cong H^q(X,\Omega_X^p)\end{gathered}`
],text:'Hodge 分解与谱序列的关联分次。',note:'',proof:''};
export function hodgeSetup({page,math,t}){
 const text=page===0?t('设 X 是紧复流形。下列空间由光滑复值微分形式组成。','Let X be a compact complex manifold. The following spaces consist of smooth complex-valued differential forms.'):page>=4?t('进一步假设 X 为 Kähler 流形。','Assume in addition that X is Kähler.'):'';
 return text?`<div class="leray-setup"><p>${text}</p></div>`:'';
}
export function hodgeExposition({page,math,language}){
 const t=(z,e)=>language()==='en'?e:z,M=x=>math(x),eq=x=>`<div class="operation-equation">${math(x,true)}</div>`,p=x=>`<p>${x}</p>`;
 const ref='<a href="https://virtualmath1.stanford.edu/~conrad/shimsem/2013Notes/Littvhs.pdf#page=11" target="_blank" rel="noopener">Daniel Litt, Variations of Hodge Structure, Theorem 20 and Remark 21</a>';
 const base=t(`设 ${M('X')} 是复维数为 ${M('m')} 的紧复流形。`,`Let ${M('X')} be a compact complex manifold of complex dimension ${M('m')}.`);
 const kahler=t(`设 ${M('X')} 是紧 Kähler 流形，并记 ${M(R`H^n=H_{\mathrm{dR}}^n(X;\mathbb C)`)}；${M('F')} 为 3.4 的诱导滤过。`,`Let ${M('X')} be a compact Kähler manifold, write ${M(R`H^n=H_{\mathrm{dR}}^n(X;\mathbb C)`)}, and let ${M('F')} be the induced filtration of 3.4.`);
 const analytic=p(t('使用经典解析 Hodge 定理：在紧流形上每个 de Rham 类有唯一的 d-调和代表元；在紧 Hermitian 流形上每个 Dolbeault 类有唯一的 ∂̄-调和代表元。Kähler 恒等式进一步给出','We use the classical analytic Hodge theorems: each de Rham class on a compact manifold has a unique d-harmonic representative, and each Dolbeault class on a compact Hermitian manifold has a unique ∂̄-harmonic representative. The Kähler identities additionally give'))+eq(R`\Delta_d=2\Delta_{\bar\partial}=2\Delta_\partial,\qquad\Delta_T:=TT^*+T^*T`)+p(t('星号是所选 Kähler 度量的形式伴随。这些解析定理作为已知输入，并非仅由谱序列收敛得到。','Here the star denotes the formal adjoint for the chosen Kähler metric. These analytic theorems are inputs, not consequences of spectral-sequence convergence alone.'));
 const data=[
 {f:[R`\alpha=\sum_{|I|=p,\,|J|=q}\alpha_{I,J}\,dz_I\wedge d\bar z_J`],note:t(`${M(R`\mathcal A^{p,q}(X)`)} 是全局光滑 ${M('(p,q)')}-形式的向量空间；系数光滑，不要求全纯。${M(R`\Omega_X^p`)} 则表示全纯 p-形式层。`,`${M(R`\mathcal A^{p,q}(X)`)} is the vector space of global smooth ${M('(p,q)')}-forms; its coefficients need not be holomorphic. ${M(R`\Omega_X^p`)} denotes the sheaf of holomorphic p-forms.`),details:p('<strong>'+t('定义。','Definition.')+'</strong> '+base)+p(t('在局部全纯坐标中，按 dz 与其共轭微分的个数定义 (p,q)-型。全纯坐标变换保持型，因此这些局部定义相容。超出 0≤p,q≤m 的空间为零。','In local holomorphic coordinates, count dz and conjugate differentials to define type (p,q). Holomorphic coordinate changes preserve type, so the local definitions agree. Terms outside 0≤p,q≤m vanish.'))},
 {f:[R`\partial:K^{p,q}\to K^{p+1,q},\qquad\bar\partial:K^{p,q}\to K^{p,q+1}`,R`\partial^2=\bar\partial^2=0,\qquad\partial\bar\partial+\bar\partial\partial=0`],note:t('这正是第 1 节的第一象限双复形，且总复形是复值 de Rham 复形。','This is a first-quadrant double complex as in Section 1; its total complex is the complex-valued de Rham complex.'),details:p('<strong>'+t('命题。','Proposition.')+'</strong> '+base+t('则取上述 K、δ₁、δ₂ 得到双复形，其总微分为 d。','Then the displayed K, δ₁ and δ₂ form a double complex with total differential d.'))+p('<strong>'+t('证明。','Proof.')+'</strong> '+t('按型分解 d=∂+∂̄。将 d²=0 分别投影到双次数增加 (2,0)、(1,1)、(0,2) 的分量，得到三个双复形关系。','Decompose d=∂+∂̄ by type. Project d²=0 to its components of bidegrees (2,0), (1,1) and (0,2) to obtain the three double-complex identities.'))},
 {f:[R`E_1^{p,q}=H^q(\mathcal A^{p,\bullet}(X),\bar\partial)\cong H^q(X,\Omega_X^p)`],note:t('先沿纵向取 Dolbeault 上同调。第二个同构是 Dolbeault 定理；收敛则来自 2.9，尚不需要 Kähler 条件。','First take vertical Dolbeault cohomology. The second isomorphism is the Dolbeault theorem; convergence follows from 2.9 and does not yet require X to be Kähler.'),details:p('<strong>'+t('命题。','Proposition.')+'</strong> '+base+t('则列滤过给出下述谱序列。','Then the column filtration gives the following spectral sequence.'))+eq(hodgeContent.f[2])+p('<strong>'+t('证明。','Proof.')+'</strong> '+t('由第零页的纵向微分取上同调得到 E₁。Dolbeault 引理给出 Ω 的光滑 (p,•)-形式层的正合分解；这些层是细层，所以全局截面复形计算其层上同调。再用 2.9 的第一象限收敛定理。','Vertical cohomology of the zeroth page gives E₁. The Dolbeault lemma resolves Ω by the sheaves of smooth (p,•)-forms. These sheaves are fine, so their global sections compute sheaf cohomology. Apply the first-quadrant convergence theorem 2.9.'))+eq(R`0\to\Omega_X^p\to\mathcal A_X^{p,0}\xrightarrow{\bar\partial}\mathcal A_X^{p,1}\to\cdots`)+p(t('这里的 𝒜_X 是光滑形式层，其全局截面就是 3.1 的向量空间。','Here 𝒜_X is the sheaf of smooth forms; its global sections are the vector spaces from 3.1.'))},
 {f:[R`H^n:=H_{\mathrm{dR}}^n(X;\mathbb C),\qquad\operatorname{Gr}_F^pH^n=F^pH^n/F^{p+1}H^n`],note:t('这就是 Hodge 滤过。FᵖHⁿ 的类可以用首指标至少为 p 的 d-闭形式表示；E∞ 给出相邻层之商。','This is the Hodge filtration. A class in FᵖHⁿ has a d-closed representative whose first type index is at least p; E∞ identifies the adjacent filtration quotient.'),details:p('<strong>'+t('定义。','Definition.')+'</strong> '+base)+eq(hodgeContent.f[3])+p(t('在 1.12 的上同调诱导滤过中代入上述 Dolbeault 双复形，正好得到此定义。2.9 保证相对于这个指定的滤过收敛。无需先选择直和分裂。','Substituting the Dolbeault double complex into the induced cohomology filtration of 1.12 gives this definition. Theorem 2.9 establishes convergence for precisely this filtration. No splitting is chosen.'))},
 {f:[R`\Delta_d=2\Delta_{\bar\partial}`,R`E_1^{p,q}\cong E_\infty^{p,q}`],note:t('Kähler 条件使每个 E₁ 类具有 d-闭的纯型调和代表元，因此所有后续微分都为零。这比收敛多了一步。','The Kähler condition gives every E₁ class a d-closed harmonic representative of pure type. Hence every later differential vanishes. This is additional to convergence.'),details:p('<strong>'+t('定理。','Theorem.')+'</strong> '+kahler+t('则 Hodge–de Rham 谱序列在 E₁ 退化。','Then the Hodge–de Rham spectral sequence degenerates at E₁.'))+eq(hodgeContent.f[4])+p('<strong>'+t('证明。','Proof.')+'</strong>')+analytic+p(t('给定 E₁ 的类，取其 ∂̄-调和代表元 α。恒等式说明 α 也是 d-调和的，从而 dα=0。因此它代表所有后续页上的闭元，且 dᵣ[α]ᵣ=[dα]ᵣ=0。先得 d₁=0，再用逐页上同调同构归纳，得到所有 r≥1 的微分均为零。','Represent an E₁ class by a ∂̄-harmonic form α. The identity makes α d-harmonic, hence dα=0. It represents a cycle on each later page and dᵣ[α]ᵣ=[dα]ᵣ=0. Starting with d₁=0, induction using the page-cohomology isomorphisms makes every differential for r≥1 vanish.'))},
 {f:[R`H^{p,q}(X)\xrightarrow{\sim}\operatorname{Gr}_F^pH^n\quad(p+q=n)`],note:t('共轭滤过把关联分次片段识别为 Hⁿ 内部的典范子空间。一般谱序列没有这种互补结构，因而收敛或退化本身不等于 Hodge 分解。','The conjugate filtration identifies the graded pieces with canonical subspaces inside Hⁿ. A general spectral sequence has no such opposed structure, so convergence or degeneration alone is not Hodge decomposition.'),details:p('<strong>'+t('定理（Hodge 分解）。','Theorem (Hodge decomposition).')+'</strong> '+kahler+t('则有以下与 Kähler 度量选择无关的分解及自然同构。','Then the following decomposition and natural isomorphisms are independent of the choice of Kähler metric.'))+eq(hodgeContent.f[5])+p('<strong>'+t('证明。','Proof.')+'</strong>')+analytic+p(t('由于 Δ∂̄ 保持型，Δd 也保持型。故 d-调和 n-形式唯一分解为各 (p,q)-型的调和形式，且每个分量都 d-闭。de Rham 的调和代表元定理将这个直和分解送到 Hⁿ；Dolbeault 的调和代表元定理识别每个分量与 Hᑫ(X,Ωᵖ)。','Since Δ∂̄ preserves type, so does Δd. A d-harmonic n-form splits uniquely into harmonic (p,q)-components, each d-closed. The de Rham harmonic representative theorem transfers this direct sum to Hⁿ; the Dolbeault theorem identifies each summand with Hᑫ(X,Ωᵖ).'))+p(t('调和投影保持型，所以 Fᵖ 中的闭形式，其调和代表元仍只含第一指标至少为 p 的分量。反过来这些纯型调和形式本身就在 Fᵖ 中。因此','Harmonic projection preserves type. Thus the harmonic representative of a closed form in Fᵖ still has first index at least p. Conversely, these pure-type harmonic forms already lie in Fᵖ. Therefore'))+eq(R`F^pH^n=\bigoplus_{a\ge p}H^{a,n-a}(X),\quad\overline{F^qH^n}=\bigoplus_{b\ge q}H^{n-b,b}(X)`)+p(t('当 p+q=n 时，两式的交集中只保留 (p,q) 一项，得到定理中的交集公式。右侧由复结构、Hodge 滤过和复共轭决定，因而不依赖所选 Kähler 度量。最后投影到 Fᵖ/Fᵖ⁺¹ 即得关联分次同构。','For p+q=n the intersection retains exactly the (p,q)-summand. This intersection is determined by the complex structure, the Hodge filtration and conjugation, so it is independent of the chosen Kähler metric. Projection to Fᵖ/Fᵖ⁺¹ gives the graded-piece isomorphism.'))}
 ];
 const entry=data[page]||data[0];
 return proofPanel({key:'hodge-'+page,title:`3.${page+1} ${t(...hodgeTitles[page])}`,formulas:entry.f,note:entry.note,details:entry.details+p(ref),detailsAreComplete:true,math,language});
}
export function hodgeDiagram({page,label,t}){
 let svg='<svg viewBox="0 0 840 525" role="img" aria-label="Hodge decomposition"><defs><marker id="hodge-tip" viewBox="0 0 8 8" refX="6" refY="4" markerWidth="6" markerHeight="6" orient="auto"><path d="M1 1 L6 4 L1 7" fill="none" stroke="var(--gold)"/></marker></defs>',labels='';
 const box=(x,y,w=148)=>{svg+=`<rect x="${x-w/2}" y="${y-25}" width="${w}" height="50" rx="8" fill="var(--graph-region-fill)" stroke="var(--graph-border)"/>`;};
 if(page<=2){
  for(let p=0;p<3;p++)for(let q=0;q<3;q++){
   const x=205+210*p,y=375-125*q;box(x,y);
   labels+=label(x,y,page===2?R`H^{${q}}(X,\Omega_X^{${p}})`:R`\mathcal A^{${p},${q}}(X)`,145);
   if(page===1){if(p<2){svg+=`<path d="M${x+77},${y} H${x+132}" stroke="var(--gold)" marker-end="url(#hodge-tip)"/>`;labels+=label(x+105,y-23,R`\partial`,50,'gold');}if(q<2){svg+=`<path d="M${x},${y-29} V${y-95}" stroke="var(--gold)" marker-end="url(#hodge-tip)"/>`;labels+=label(x+25,y-62,R`\bar\partial`,50,'gold');}}
  }
  labels+=label(420,460,page===2?R`E_1^{p,q}\Longrightarrow H_{\mathrm{dR}}^{p+q}(X;\mathbb C)`:R`p,q\ge0\quad\text{${t("示意窗口","display window")}}`,760,'gold');
 }else if(page===4){
  for(const [i,r] of ['1','2','\\infty'].entries()){const x=180+i*240;box(x,235,185);labels+=label(x,235,R`E_{${r}}^{p,q}`,180,'gold');if(i<2)labels+=label(x+120,235,R`\cong`,50);}
  labels+=label(420,110,R`X\quad\text{${t("紧 Kähler 流形","compact Kähler")}}`,750,'title')+label(420,355,R`d_r^{p,q}=0\qquad(r\ge1)`,740,'gold');
 }else{
  const terms=page===3?[R`\operatorname{Gr}_F^0H^2`,R`\operatorname{Gr}_F^1H^2`,R`\operatorname{Gr}_F^2H^2`]:[R`H^{0,2}(X)`,R`H^{1,1}(X)`,R`H^{2,0}(X)`];
  terms.forEach((tex,i)=>{const x=185+235*i;box(x,255,190);labels+=label(x,255,tex,185,i?'gold':'');if(i<2)labels+=label(x+117,255,R`\oplus`,35);});
  labels+=label(420,115,page===3?R`\operatorname{Gr}_F H^2`:R`H^2_{\mathrm{dR}}(X;\mathbb C)`,730,'title');
  svg+='<path d="M318 212 H757 V298 H318 Z" fill="none" stroke="var(--gold)" stroke-dasharray="5 5" opacity=".6"/>';
  labels+=label(540,340,page===3?R`\operatorname{Gr}_F(F^1H^2)`:R`F^1H^2=H^{1,1}(X)\oplus H^{2,0}(X)`,570,'gold');
  if(page===5)labels+=label(420,432,R`H^{p,q}=F^pH^{p+q}\cap\overline{F^qH^{p+q}}`,760);
 }
 return svg+'</svg>'+labels;
}
