import {proofPanel} from './proof-panel.js?v=135';
const R=String.raw;
export const lerayTitles=[['几何设定','Geometric setup'],['内射分解','Injective resolution'],['直像复形','The pushforward complex'],['边界、闭元与上同调层','Boundaries, cycles and cohomology sheaves'],['辅助内射分解','Auxiliary injective resolutions'],['马蹄引理与逐项构造','Horseshoe construction'],['Cartan–Eilenberg 分解','Cartan–Eilenberg resolution'],['全局截面对象','The object of global sections'],['微分与符号约定','Differentials and signs'],['总复形与列滤过','Total complex and column filtration'],['Leray 谱序列的第二页','The second page of Leray'],['总上同调的识别','Identification of total cohomology'],['Leray 收敛','Leray convergence'],['应用：由总上同调消失推出直像消失','Application: vanishing of higher direct images'],['应用：有理奇点与解消','Application: rational singularities']];
export function leraySetup({math,t,page}){
 const notes=[t('设 f 是域 k 上概形之间的态射，𝓕 是 X 上的拟凝聚层。','Let f be a morphism of schemes over a field k, and let 𝓕 be a quasi-coherent sheaf on X.'),t(`在所有 ${math(R`\mathcal O_X`)}-模层的范畴中，取 ${math(R`\mathcal F`)} 的内射分解。`,`Choose an injective resolution of ${math(R`\mathcal F`)} in the category of all ${math(R`\mathcal O_X`)}-module sheaves.`),t('逐项取直像，得到 Y 上的层复形。','Apply the direct image term by term to obtain a complex of sheaves on Y.'),t('这里的 B、Z 是层的像与核。','Here B and Z are sheaf images and kernels.'),t(`对每个 ${math('q')}，选取边界层 ${math('B^q')} 的内射分解 ${math(R`U^{\bullet,q}`)}，以及上同调层 ${math('H^q=Z^q/B^q')} 的内射分解 ${math(R`V^{\bullet,q}`)}。${math('V^{p,q}')} 是后一个分解的第 ${math('p')} 项。`,`For each ${math('q')}, choose an injective resolution ${math(R`U^{\bullet,q}`)} of the boundary sheaf ${math('B^q')}, and an injective resolution ${math(R`V^{\bullet,q}`)} of the cohomology sheaf ${math('H^q=Z^q/B^q')}. The sheaf ${math('V^{p,q}')} is the degree-${math('p')} term of the latter resolution.`),t('对两条短正合列依次应用内射版马蹄引理。','Apply the injective horseshoe lemma to the two short exact sequences in order.'),t(`取 ${math(R`\mathcal A^\bullet`)} 的 Cartan–Eilenberg 内射分解 J。`,`Choose a Cartan–Eilenberg injective resolution J of ${math(R`\mathcal A^\bullet`)}.`)];
 if(page===13)return `<div class="leray-setup"><p>${t(`${math('f:X\\to Y')} 是双有理态射；${math('L')} 是 ${math('Y')} 上的线丛，${math('H')} 为很充足除子，${math(R`\omega_X`)} 为典范层。${math('L(mH):=L\\otimes\\mathcal O_Y(mH)')}。此处对 ${math(R`\mathcal F_m:=\omega_X\otimes f^*L(mH)`)} 使用 Leray 谱序列。`,`Here ${math('f:X\\to Y')} is birational; ${math('L')} is a line bundle on ${math('Y')}, ${math('H')} is a very ample divisor, and ${math(R`\omega_X`)} is the canonical sheaf. Write ${math('L(mH):=L\\otimes\\mathcal O_Y(mH)')}. Apply Leray to ${math(R`\mathcal F_m:=\omega_X\otimes f^*L(mH)`)}.`)}</p></div>`;
 return `<div class="leray-setup"><p>${notes[page]||''}</p></div>`;
}
export const lerayContent={title:'Leray spectral sequence',f:[
 R`f:X\to Y,\qquad\mathcal F\in\operatorname{QCoh}(X)`,
 R`0\to\mathcal F\to \mathcal{I}^0\xrightarrow{d_{\mathcal{I}}^0}\mathcal{I}^1\xrightarrow{d_{\mathcal{I}}^1}\cdots`,
 R`\begin{gathered}\mathcal{A}^\bullet:=f_*\mathcal{I}^\bullet\\A^q:=f_*\mathcal{I}^q,\qquad d_{\mathcal{A}}^q:=f_*(d_{\mathcal{I}}^q)\end{gathered}`,
 R`\begin{gathered}B^q:=\operatorname{im}(d_{\mathcal{A}}^{q-1}:\mathcal{A}^{q-1}\to \mathcal{A}^q)\\Z^q:=\ker(d_{\mathcal{A}}^q:\mathcal{A}^q\to \mathcal{A}^{q+1})\\H^q:=Z^q/B^q=\mathcal H^q(\mathcal{A}^\bullet)\end{gathered}`,
 R`\begin{gathered}0\to B^q\to U^{0,q}\to U^{1,q}\to\cdots\\0\to H^q\to V^{0,q}\to V^{1,q}\to\cdots\end{gathered}`,
 R`\begin{gathered}0\to B^q\to Z^q\to H^q\to0\\0\to Z^q\to \mathcal{A}^q\to B^{q+1}\to0\\W^{p,q}:=U^{p,q}\oplus V^{p,q}\\J^{p,q}:=W^{p,q}\oplus U^{p,q+1}\end{gathered}`,
 R`\begin{gathered}J:=\bigl(J^{\bullet,\bullet},h,v\bigr)\\0\to \mathcal{A}^q\to J^{0,q}\xrightarrow{h}J^{1,q}\xrightarrow{h}\cdots\\v:J^{p,q}\to J^{p,q+1}\end{gathered}`,
 R`\begin{gathered}K:=\{K^{p,q}\}_{p,q\in\mathbb Z}\\K^{p,q}:=\Gamma(Y,J^{p,q})\\K^{p,q}=0\quad(p<0\text{ or }q<0)\end{gathered}`,
 R`\begin{gathered}\bigl(K^{\bullet,\bullet},\delta_1,\delta_2\bigr)\\\delta_1^{p,q}:=\Gamma(Y,h^{p,q})\\\delta_2^{p,q}:=(-1)^p\Gamma(Y,v^{p,q})\\\delta_1^2=\delta_2^2=\delta_1\delta_2+\delta_2\delta_1=0\end{gathered}`,
 R`\begin{gathered}C^n:=\bigoplus_{p+q=n}K^{p,q},\quad D:=\delta_1+\delta_2\\F^aC^n:=\bigoplus_{p\ge a}K^{p,n-p}\end{gathered}`,
 R`\begin{gathered}E_1^{p,q}\cong\Gamma(Y,\mathcal H_v^q(J^{p,\bullet}))\\E_2^{p,q}\cong H^p(Y,R^qf_*\mathcal F)\end{gathered}`,
 R`H^n(C^\bullet,D)\cong H^n(X,\mathcal F)`,
 R`E_2^{p,q}\Longrightarrow H^{p+q}(X,\mathcal F)`,
 R`\begin{gathered}\mathcal G_m^q:=L(mH)\otimes R^qf_*\omega_X\\E_2^{p,q}(m)=H^p(Y,\mathcal G_m^q)\\m\gg0:\quad E_2^{p,q}(m)=0\ (p>0)\end{gathered}`,
 R`\begin{gathered}\pi:\widetilde X\to X,\quad\pi_*\mathcal O_{\widetilde X}=\mathcal O_X\\R^q\pi_*\mathcal O_{\widetilde X}=0\quad(q>0)\\H^n(X,\mathcal O_X)\xrightarrow{\sim}H^n(\widetilde X,\mathcal O_{\widetilde X})\end{gathered}`
],text:'',note:'',proof:''};
const km='https://studylib.net/doc/28454579/birational-geometry-of-algebraic-varieties--janos-kolla%CC%81r...';
export function lerayExposition({page,math,language}){
 const t=(zh,en)=>language()==='en'?en:zh,eq=x=>`<div class="operation-equation">${math(x,true)}</div>`,para=x=>`<p>${x}</p>`;
 const data=[
 {f:[R`\mathcal F\in\operatorname{Mod}(\mathcal O_X)`],note:t('后续内射分解在所有模层的范畴中选取。','Subsequent injective resolutions are chosen in the category of all module sheaves.'),detail:t(`拟凝聚层也可视为一个模层；使用整个模层范畴，可以选取足够多的内射对象。`,`${math(R`\mathcal A`)} quasi-coherent sheaf is also a module sheaf. The full category of module sheaves has enough injectives.`)},
 {f:[R`\mathcal H^0(\mathcal{I}^\bullet)\cong\mathcal F,\qquad\mathcal H^q(\mathcal{I}^\bullet)=0\ (q>0)`],note:t(`每个 ${math(R`\mathcal I^q`)} 都是内射模层，增广序列正合。`,`Each ${math(R`\mathcal I^q`)} is injective and the augmented sequence is exact.`),detail:t('取 𝓕 到内射对象的单射，对余核重复此构造，即得到内射分解。','Embed 𝓕 in an injective object and repeat on successive cokernels to obtain the resolution.')},
 {f:[R`\mathcal H^q(\mathcal{A}^\bullet)=R^qf_*\mathcal F`],note:t(`直像一般不正合，因此 ${math(R`\mathcal A^\bullet`)} 的高次上同调层未必为零。`,`Direct image is generally not exact, so the higher cohomology sheaves of ${math(R`\mathcal A^\bullet`)} need not vanish.`),detail:t(`右导出函子由内射分解计算：将 f_* 作用于 ${math(R`\mathcal I^\bullet`)}，再取第 q 个上同调层，便得到 R^qf_*𝓕。`,`Right derived functors are computed using an injective resolution: apply f_* to ${math(R`\mathcal I^\bullet`)} and take the q-th cohomology sheaf.`)},
 {f:[R`B^q\subseteq Z^q\subseteq \mathcal{A}^q,\qquad H^q\cong R^qf_*\mathcal F`],note:t(`${math(R`d_{\mathcal{A}}^2=0`)} 给出 ${math(R`B^q\subseteq Z^q`)}；${math(R`H^q`)} 是上同调层，不是全局截面的上同调群。`,`The relation ${math(R`d_{\mathcal{A}}^2=0`)} gives ${math(R`B^q\subseteq Z^q`)}. Here ${math(R`H^q`)} is a cohomology sheaf, not the cohomology of global sections.`),detail:t('像与核均在模层范畴中取。由复形的定义，相邻两个微分的复合为零，所以前一个微分的像包含在后一个的核中，因而商层有定义。','Images and kernels are taken in the category of module sheaves. Consecutive differentials compose to zero, so the quotient sheaf is defined.')},
 {f:[R`U^{p,q},V^{p,q}\text{ injective}\quad(p\ge0)`,R`U^{p,q}=V^{p,q}=0\quad(p<0)`],note:t('p 是内射分解次数，q 保留原复形次数。B⁰=0 时取 U•,0=0。','The index p is the resolution degree, while q retains the original degree. Take U•,0=0 since B⁰=0.'),detail:t('模层范畴有足够多内射对象，因此可分别选取这些分解。这里的选择不唯一，也不要求这些分解预先具有纵向微分。','There are enough injectives in the module-sheaf category. These choices are not unique, and no vertical differentials are required yet.')},
 {f:[R`0\to Z^q\to W^{0,q}\to W^{1,q}\to\cdots`,R`0\to \mathcal{A}^q\to J^{0,q}\to J^{1,q}\to\cdots`],note:t(`两次马蹄引理分别给出 W 对 Z 的分解、J 对 ${math(R`\mathcal A`)} 的分解。直和公式仅描述各项；横向微分还包含兼容扩张所需的非对角项。`,`The two horseshoe constructions resolve Z by W and ${math(R`\mathcal A`)} by J. The direct sums describe the terms; horizontal differentials also contain off-diagonal extension terms.`),detail:eq(R`\begin{gathered}0\to U^{\bullet,q}\to W^{\bullet,q}\to V^{\bullet,q}\to0,\\0\to W^{\bullet,q}\to J^{\bullet,q}\to U^{\bullet,q+1}\to0\end{gathered}`)+para(t('这些是与左侧原短正合列相容、逐项分裂的复形短正合列。有限直和保持内射性，所以 W、J 的各项仍为内射层。','These degreewise split exact sequences of complexes lift the original short exact sequences. Finite direct sums of injectives are injective.'))},
 {f:[R`v^{p,q}:J^{p,q}\twoheadrightarrow U^{p,q+1}\hookrightarrow W^{p,q+1}\hookrightarrow J^{p,q+1}`,R`h^2=v^2=0,\qquad hv=vh`],note:t('先为边界层 B^q、上同调层 H^q 取内射分解 U•,q、V•,q，再对两条短正合列使用内射版马蹄引理。这里 p 是分解次数，q 是原复形次数；具体映射见证明。','Resolve the boundary and cohomology sheaves by U and V, then apply the injective horseshoe lemma twice. Here p is the resolution degree and q the original degree; see the construction for the maps.'),detail:
 para(t('构造。取如下内射分解（B⁰=0 时取零分解）：','Construction. Choose injective resolutions (use the zero resolution for B⁰=0):'))+
 eq(R`B^q\longrightarrow U^{\bullet,q},\qquad H^q\longrightarrow V^{\bullet,q}.`)+
 para(t(`先对第一条短正合列应用马蹄引理，得到 Z^q 的内射分解 W•,q；再对第二条应用，得到 ${math(R`\mathcal A^q`)} 的内射分解 J•,q。所得复形短正合列逐项分裂：`,`Apply the horseshoe lemma first to obtain a resolution W of Z, then to obtain J resolving ${math(R`\mathcal A`)}. The resulting sequences split degreewise:`))+
 eq(R`\begin{gathered}0\to U^{\bullet,q}\to W^{\bullet,q}\to V^{\bullet,q}\to0,\\0\to W^{\bullet,q}\to J^{\bullet,q}\to U^{\bullet,q+1}\to0.\end{gathered}`)+
 para(t('取逐项直和模型，得到上面的 J^{p,q}。横向微分 h 是该内射分解的微分，包含马蹄引理给出的非对角分量，不能简单取三个微分的直和。定义纵向微分为复合：','Use the displayed direct-sum model for J. Its horizontal differential h includes the horseshoe off-diagonal terms. Define v by'))+
 eq(R`v^{p,q}:J^{p,q}\twoheadrightarrow U^{p,q+1}\hookrightarrow W^{p,q+1}\hookrightarrow J^{p,q+1}.`)+
 para(t('这些箭头均为横向复形的映射，故 hv=vh。v 的像落入下一次投影的核，故 v²=0。并且','These are horizontal chain maps, so hv=vh. The image of v lies in the next projection kernel, giving v²=0. Moreover,'))+
 eq(R`\ker v^{p,q}=W^{p,q},\quad\operatorname{im}v^{p,q-1}=U^{p,q},\quad\mathcal H_v^q(J^{p,\bullet})\cong V^{p,q}.`)+
 para(t('因此各项、闭元、边界和上同调层的横向复形均是对应层的内射分解，正是 Cartan–Eilenberg 条件。J 的选择不唯一。','Thus the terms, cycles, boundaries and cohomology are resolved compatibly, as required. The choice of J is not unique.'))},
 {f:[R`K^{p,q}=\Gamma(Y,J^{p,q})`],note:t('J 已在 3.7 定义。现在逐项取 Y 上的全局截面，得到双分次对象 K；下一条再定义两个微分。若 X、Y 是 k-概形，则这些项是 k-向量空间。','With J defined in 3.7, take global sections on Y term by term to obtain the bigraded object K. The next entry defines its two differentials. For k-schemes X and Y, these terms are k-vector spaces.'),detail:t('Γ(Y,−) 是加性左正合函子，可作用于 J 的各项与映射。此步仅定义对象，不将 Γ 与任意复形的上同调交换。','Γ(Y,−) is additive and left exact and can be applied to the terms and maps of J. This step only defines the object; it does not commute Γ with cohomology of arbitrary complexes.')},
 {f:[R`\delta_2^{p+1,q}\delta_1^{p,q}+\delta_1^{p,q+1}\delta_2^{p,q}=(-1)^{p+1}\Gamma(vh)+(-1)^p\Gamma(hv)=0`],note:t('现在 K 的每个小块都有明确含义：J 的全局截面。符号 (−1)^p 将交换的层映射转成第一节使用的反交换微分。','Each K block is now specified: the global sections of J. The sign (−1)^p converts commuting sheaf maps into the anticommuting differentials used in §1.'),detail:t('h²=v²=0 给出两个微分各自平方为零。上述计算给出反交换关系，因此 D²=0；不能在交换约定下直接令 δ₁=Γh、δ₂=Γv 而不处理符号。','The equations h²=v²=0 give the two square-zero identities. The displayed computation gives anticommutation and hence D²=0; the sign is essential when starting with commuting maps.')},
 {f:[R`E_0^{p,q}\cong K^{p,q},\quad d_0^{p,q}\leftrightarrow\delta_2^{p,q}`],note:t('使用第一节同一个列滤过。于是先沿 q 方向取上同调得到 E₁，再沿 p 方向取上同调得到 E₂。','Use exactly the column filtration of §1. Taking cohomology first in q gives E₁, and then in p gives E₂.'),detail:t('δ₁ 将第一指标提高一，δ₂ 保持第一指标，所以 D 保持 F。关联分次消去 δ₁ 的贡献，仅保留 δ₂。每条总次数对角线有限，所以总复形使用普通直和即可。','δ₁ raises the first index while δ₂ preserves it, so D preserves F. Passing to the associated graded removes δ₁ and retains δ₂. Each total-degree diagonal is finite, so ordinary direct sums suffice.')},
 {f:[R`E_2^{p,q}\cong H^p\!\left(\Gamma(Y,\mathcal H_v^q(J^{\bullet,\bullet})),h\right)\cong H^p(Y,R^qf_*\mathcal F)`],note:t('E₁ 仍是一个内射分解的截面项；到 E₂ 才得到熟悉的层上同调。因此定理选择明确写出第二页。','E₁ still consists of section terms of an injective resolution; E₂ is the familiar sheaf cohomology. This is why the theorem displays page two.'),detail:para(t('Proof. 固定 p。以下短正合列分裂，因为 B_v^{p,q} 与 Z_v^{p,q} 都是内射对象：','Proof. Fix p. The following short exact sequences split because B_v^{p,q} and Z_v^{p,q} are injective:'))+eq(R`0\to B_v^{p,q}\to Z_v^{p,q}\to\mathcal H_v^q(J^{p,\bullet})\to0`)+eq(R`0\to Z_v^{p,q}\to J^{p,q}\to B_v^{p,q+1}\to0`)+para(t('因此 Γ(Y,−) 保持这些列的正合性，得到 E₁ 的上述同构。由 CE 条件，𝓗_v^q(J^{•,•}) 是 R^qf_*𝓕 的内射分解，再取横向上同调便得到 E₂。这里并未假定 Γ 与任意复形的上同调交换。','Thus Γ(Y,−) preserves their exactness, giving the displayed identification of E₁. The CE condition makes 𝓗_v^q(J^{•,•}) an injective resolution of R^qf_*𝓕; horizontal cohomology gives E₂. No commutation of Γ with cohomology of arbitrary complexes is assumed.'))},
 {f:[R`H^n(C^\bullet,D)\cong H^n(X,\mathcal F)`],note:t('第一象限保证收敛到总复形上同调；还需识别总复形的上同调，才能得到 Leray 的目标。E₂ 并不表示已经稳定。','The first quadrant gives convergence to total cohomology. Identifying that cohomology gives the Leray target. E₂ does not assert stabilization.'),detail:para(t(`Proof. 内射层 ${math(R`\mathcal I^q`)} 是松弛层，${math(R`f_*\mathcal I^q`)} 仍松弛，因而对 Γ(Y,−) 无上同调。双复形若先沿 p 取上同调，只剩 p=0 的复形 ${math(R`\Gamma(Y,\mathcal A^\bullet)`)}。故`,`Proof. An injective sheaf ${math(R`\mathcal I^q`)} is flasque, and ${math(R`f_*\mathcal I^q`)} is flasque and hence Γ(Y,−)-acyclic. Taking p-cohomology first leaves only the p=0 complex ${math(R`\Gamma(Y,\mathcal A^\bullet)`)}. Therefore`))+eq(R`H^n(C,D)\cong H^n(\Gamma(Y,\mathcal{A}^\bullet))=H^n(\Gamma(X,\mathcal{I}^\bullet))\cong H^n(X,\mathcal F).`)},
 {f:[R`E_\infty^{p,q}\cong\operatorname{Gr}_F^pH^{p+q}(X,\mathcal F)`],note:t('由第一象限的收敛定理和上一节的总上同调同构，得到 Leray 收敛。这里的 E₂ 是 3.11 已识别的第二页。','First-quadrant convergence and the preceding total-cohomology isomorphism give Leray convergence. E₂ is the second page identified in 3.11.'),detail:para(t('证明。列滤过在每个总次数上有限，因此谱序列收敛到总复形的上同调。将该滤过沿 3.12 的同构输送到层上同调，即得结论。','Proof. The column filtration is finite in each total degree, so the spectral sequence converges to total cohomology. Transport this filtration through the isomorphism of 3.12 to obtain the assertion.'))},
 {f:[R`\mathcal G_m^q:=L(mH)\otimes R^qf_*\omega_X`,R`H^0(Y,L(mH)\otimes R^qf_*\omega_X)\cong H^q(X,\omega_X\otimes f^*L(mH))=0\quad(q>0)`,R`\Longrightarrow\quad R^qf_*\omega_X=0\quad(q>0)`],note:t('Kollár–Mori §2.5，证明 (2.64) 的 Step 4（pp. 71–72）。将书中的扭曲参数改记 m，避免与页数 r 混淆；完整假设与消失定理输入见证明。','Kollár–Mori §2.5, Step 4 of the proof of (2.64), pp. 71–72.  The twist m is distinct from the page r; the proof lists the hypotheses and vanishing input.'),detail:eq(R`\mathcal F_m:=\omega_X\otimes f^*L(mH),\qquad\mathcal G_m^q:=L(mH)\otimes R^qf_*\omega_X`)+eq(R`E_2^{p,q}(m)=H^p(Y,R^qf_*\mathcal F_m)\cong H^p(Y,\mathcal G_m^q)`)+para(t('Proof. 投影公式给出左侧的 E₂ 项。固定 m 充分大，Serre 消失使所有 p>0 的项为零，因此仅剩 p=0 一列，所有后续微分为零。总次数 q 的滤过只有一个可能非零的商，收敛于是给出所示同构。','Proof. The projection formula gives the displayed E₂ terms. For sufficiently large m, Serre vanishing kills every term with p>0. Only column p=0 remains, so later differentials vanish. The filtration in total degree q has only one possibly nonzero quotient; convergence gives the displayed isomorphism.'))+para(t('右端消失是外部消失定理的输入，不是由谱序列自动得到。对这样的 m，L(mH)⊗R^qf_*ω_X 还由全局截面生成。其全局截面为零，故该层为零；张量可逆层的逆便得到 R^qf_*ω_X=0。','Vanishing on the right is an input from a vanishing theorem, not a consequence of spectral sequences alone. For such m, L(mH)⊗R^qf_*ω_X is also globally generated. Zero global sections force this sheaf to be zero; tensoring by the inverse line bundle gives R^qf_*ω_X=0.'))},
 {f:[R`E_2^{p,q}=\begin{cases}H^p(X,\mathcal O_X),&q=0,\\0,&q>0,\end{cases}`,R`E_2^{n,0}\cong E_\infty^{n,0}\cong H^n(\widetilde X,\mathcal O_{\widetilde X})`],note:t('取复数域上具有有理奇点的正规簇 X 及一个解消 π。假设正是 KM Definition 5.8 中有理解消的条件；此处展开其 Leray 推论。','Let X be a normal complex variety with rational singularities and π a resolution. The hypotheses are the rational-resolution conditions of KM Definition 5.8; here we expand their Leray consequence.'),detail:para(t('Proof. 高阶直像消失使 E₂ 仅剩 q=0 一行，故 E₂=E∞。在总次数 n 上，F⁰=⋯=Fⁿ=Hⁿ，Fⁿ⁺¹=0，所以唯一的滤过商就是整个 Hⁿ。边缘映射由自然映射 𝒪_X→Rπ_*𝒪_Ẋ 诱导，给出左侧所写的典范同构。','Proof. Vanishing of higher direct images leaves only row q=0, so E₂=E∞. In degree n, F⁰=⋯=Fⁿ=Hⁿ and Fⁿ⁺¹=0. Thus the sole filtration quotient is all of Hⁿ. The edge map induced by 𝒪_X→Rπ_*𝒪_Ẋ is the canonical isomorphism displayed on the left.'))}
 ];
 const e=data[page]||data[0],title=`3.${page+1} ${t(...lerayTitles[page])}`;
 const refs=page>=13?`<a href="${km}" target="_blank" rel="noopener">Kollár–Mori (1998), ${page===13?'§2.5, pp. 71–72':'Definition 5.8'}</a>`:'<a href="https://stacks.math.columbia.edu/tag/015G" target="_blank" rel="noopener">Stacks, 13.21</a> · <a href="https://stacks.math.columbia.edu/tag/01EY" target="_blank" rel="noopener">Leray, 20.13.4</a>';
 return proofPanel({key:'leray-'+page,title,formulas:e.f,note:e.note,details:(e.detail.includes('<')?e.detail:para(e.detail)).replaceAll('Proof.',t('证明。','Proof.'))+`<p>${refs}</p>`,math,language});
}
export function lerayDiagram({page,label,t}){
 if(page<6){
  const lines=[
   [R`\mathcal F\quad\text{on }X`,R`X\xrightarrow{f}Y`],
   [R`\mathcal F\longrightarrow \mathcal{I}^\bullet`,R`0\to\mathcal F\to \mathcal{I}^0\to \mathcal{I}^1\to \mathcal{I}^2\to\cdots`],
   [R`\mathcal{I}^\bullet\xrightarrow{\ f_*\ }\mathcal{A}^\bullet`,R`f_*\mathcal{I}^0\to f_*\mathcal{I}^1\to f_*\mathcal{I}^2\to\cdots`],
   [R`B^q\subseteq Z^q\subseteq \mathcal{A}^q`,R`H^q=Z^q/B^q`],
   [R`B^q\longrightarrow U^{\bullet,q}`,R`H^q\longrightarrow V^{\bullet,q}`],
   [R`U^{p,q}\oplus V^{p,q}=W^{p,q}`,R`W^{p,q}\oplus U^{p,q+1}=J^{p,q}`]
  ][page];
  return `<svg viewBox="0 0 840 525" role="img" aria-label="${t('Leray 构造步骤','Leray construction')}"></svg>`+label(420,180,lines[0],780,'title')+label(420,300,lines[1],780,'gold');
 }
 if(page===12)return `<svg viewBox="0 0 840 525" role="img" aria-label="Leray convergence"></svg>`+label(420,200,R`E_2^{p,q}\Longrightarrow H^{p+q}(X,\mathcal F)`,800,'title')+label(420,320,R`E_\infty^{p,q}\cong\operatorname{Gr}_F^pH^{p+q}(X,\mathcal F)`,800,'gold');
 if(page>12)page--;
 page-=6;
 let svg='<defs><marker id="leray-tip" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="6" markerHeight="6" orient="auto"><path d="M1 1L8 5L1 9" fill="none" stroke="#77d8cc" stroke-width="1.3"/></marker></defs>',labels='';
 const arrow=(x,y,X,Y)=>{svg+=`<path d="M${x},${y} L${X},${Y}" fill="none" stroke="#77d8cc" stroke-width="1.4" marker-end="url(#leray-tip)"/>`;};
 {
  const example=page>=6,zero=(p,q)=>example&&(page===6?p>0:q>0);
  labels+=label(420,38,page===0?R`h:(p,q)\mapsto(p+1,q)\qquad v:(p,q)\mapsto(p,q+1)`:example?R`E_2=E_\infty`:page===4?R`E_0\ \rightsquigarrow\ E_1\ \rightsquigarrow\ E_2`:R`K^{p,q}:=\Gamma(Y,J^{p,q})`,800,'title');
  for(let p=0;p<3;p++)for(let q=0;q<3;q++){
   const x=170+230*p,y=350-95*q,z=zero(p,q),tex=example?(z?'0':`E_2^{${p},${q}}`):`${page===0?'J':'K'}^{${p},${q}}`;
   svg+=`<rect x="${x-43}" y="${y-23}" width="86" height="46" rx="9" fill="${z?'transparent':'#18343a'}" stroke="${z?'#47636833':'#7baba777'}"/>`;
   labels+=label(x,y,tex,180,z?'small':'');
   if(!example&&page!==1){if(p<2){arrow(x+49,y,x+181,y);labels+=label(x+115,y-17,page===0?`h^{${p},${q}}`:`\\delta_1^{${p},${q}}`,100,'small');}if(q<2){arrow(x,y-29,x,y-65);labels+=label(x+40,y-47,page===0?`v^{${p},${q}}`:`\\delta_2^{${p},${q}}`,90,'small');}}
  }
  labels+=label(400,104,R`\cdots`,70,'small')+label(755,255,R`\vdots`,60,'small');
  labels+=label(420,410,example?(page===6?R`E_2^{0,n}\cong H^n(X,\omega_X\otimes f^*L(mH))`:R`E_2^{n,0}\cong H^n(\widetilde X,\mathcal O_{\widetilde X})`):page===0?R`0\to \mathcal{A}^q\to J^{0,q}\to J^{1,q}\to\cdots`:page===1?R`K^{p,q}:=\Gamma(Y,J^{p,q})`:page===3?R`F^aC^n=\bigoplus_{p\ge a}K^{p,n-p}`:page===4?R`E_2^{p,q}\cong H^p(Y,R^qf_*\mathcal F)`:page===5?R`H^n(\operatorname{Tot}K)\cong H^n(X,\mathcal F)`:R`\delta_1=\Gamma(h),\qquad\delta_2|_{K^{p,q}}=(-1)^p\Gamma(v)`,800,'gold');
 }
 return `<svg viewBox="0 0 840 525" role="img" aria-label="${t('Leray 双复形与退化示意','Leray double complex and degeneration')}">${svg}</svg>${labels}`;
}
