import {proofPanel} from './proof-panel.js?v=109';
const R=String.raw;
export const lerayTitles=[['几何设定','Geometric setup'],['内射分解','Injective resolution'],['直像复形','The pushforward complex'],['Cartan–Eilenberg 分解','Cartan–Eilenberg resolution'],['全局截面对象','The object of global sections'],['微分与符号约定','Differentials and signs'],['总复形与列滤过','Total complex and column filtration'],['Leray 谱序列的第二页','The second page of Leray'],['Leray 收敛','Leray convergence'],['应用：由总上同调消失推出直像消失','Application: vanishing of higher direct images'],['应用：有理奇点与解消','Application: rational singularities']];
export function leraySetup({math,t,page}){
 const notes=[t('设 f 是域 k 上概形之间的态射，𝓕 是 X 上的拟凝聚层。','Let f be a morphism of schemes over a field k, and let 𝓕 be a quasi-coherent sheaf on X.'),t(`在所有 ${math(R`\mathcal O_X`)}-模层的范畴中，取 ${math(R`\mathcal F`)} 的内射分解。`,`Choose an injective resolution of ${math(R`\mathcal F`)} in the category of all ${math(R`\mathcal O_X`)}-module sheaves.`),t('逐项取直像，得到 Y 上的层复形。','Apply the direct image term by term to obtain a complex of sheaves on Y.'),t('取 A• 的 Cartan–Eilenberg 内射分解 J。','Choose a Cartan–Eilenberg injective resolution J of A•.')];
 return `<div class="leray-setup"><p>${notes[page]||''}</p></div>`;
}
export const lerayContent={title:'Leray spectral sequence',f:[
 R`f:X\to Y,\qquad\mathcal F\in\operatorname{QCoh}(X)`,
 R`0\to\mathcal F\to I^0\xrightarrow{d_I^0}I^1\xrightarrow{d_I^1}\cdots`,
 R`\begin{gathered}A^\bullet:=f_*I^\bullet\\A^q:=f_*I^q,\qquad d_A^q:=f_*(d_I^q)\end{gathered}`,
 R`\begin{gathered}J:=\bigl(J^{\bullet,\bullet},h,v\bigr)\\0\to A^q\to J^{0,q}\xrightarrow{h}J^{1,q}\xrightarrow{h}\cdots\\v:J^{p,q}\to J^{p,q+1}\end{gathered}`,
 R`\begin{gathered}K:=\{K^{p,q}\}_{p,q\in\mathbb Z}\\K^{p,q}:=\Gamma(Y,J^{p,q})\\K^{p,q}=0\quad(p<0\text{ or }q<0)\end{gathered}`,
 R`\begin{gathered}\bigl(K^{\bullet,\bullet},\delta_1,\delta_2\bigr)\\\delta_1^{p,q}:=\Gamma(Y,h^{p,q})\\\delta_2^{p,q}:=(-1)^p\Gamma(Y,v^{p,q})\\\delta_1^2=\delta_2^2=\delta_1\delta_2+\delta_2\delta_1=0\end{gathered}`,
 R`\begin{gathered}C^n:=\bigoplus_{p+q=n}K^{p,q},\quad D:=\delta_1+\delta_2\\F^aC^n:=\bigoplus_{p\ge a}K^{p,n-p}\end{gathered}`,
 R`\begin{gathered}E_1^{p,q}\cong\Gamma(Y,\mathcal H_v^q(J^{p,\bullet}))\\E_2^{p,q}\cong H^p(Y,R^qf_*\mathcal F)\end{gathered}`,
 R`\begin{gathered}E_2^{p,q}\cong H^p(Y,R^qf_*\mathcal F)\\\Longrightarrow H^{p+q}(X,\mathcal F)\end{gathered}`,
 R`\begin{gathered}E_2^{p,q}(m)=H^p(V,\mathcal G_m^q)\\m\gg0:\quad E_2^{p,q}(m)=0\ (p>0)\end{gathered}`,
 R`\begin{gathered}\pi:\widetilde X\to X,\quad\pi_*\mathcal O_{\widetilde X}=\mathcal O_X\\R^q\pi_*\mathcal O_{\widetilde X}=0\quad(q>0)\\H^n(X,\mathcal O_X)\xrightarrow{\sim}H^n(\widetilde X,\mathcal O_{\widetilde X})\end{gathered}`
],text:'',note:'',proof:''};
const km='https://studylib.net/doc/28454579/birational-geometry-of-algebraic-varieties--janos-kolla%CC%81r...';
export function lerayExposition({page,math,language}){
 const t=(zh,en)=>language()==='en'?en:zh,eq=x=>`<div class="operation-equation">${math(x,true)}</div>`,para=x=>`<p>${x}</p>`;
 const data=[
 {f:[R`\mathcal F\in\operatorname{Mod}(\mathcal O_X)`],note:t('后续内射分解在所有模层的范畴中选取。','Subsequent injective resolutions are chosen in the category of all module sheaves.'),detail:t('拟凝聚层也可视为一个模层；使用整个模层范畴，可以选取足够多的内射对象。','A quasi-coherent sheaf is also a module sheaf. The full category of module sheaves has enough injectives.')},
 {f:[R`\mathcal H^0(I^\bullet)\cong\mathcal F,\qquad\mathcal H^q(I^\bullet)=0\ (q>0)`],note:t('每个 I^q 都是内射模层，增广序列正合。','Each I^q is injective and the augmented sequence is exact.'),detail:t('取 𝓕 到内射对象的单射，对余核重复此构造，即得到内射分解。','Embed 𝓕 in an injective object and repeat on successive cokernels to obtain the resolution.')},
 {f:[R`\mathcal H^q(A^\bullet)=R^qf_*\mathcal F`],note:t('直像一般不正合，因此 A• 的高次上同调层未必为零。','Direct image is generally not exact, so the higher cohomology sheaves of A• need not vanish.'),detail:t('右导出函子由内射分解计算：将 f_* 作用于 I•，再取第 q 个上同调层，便得到 R^qf_*𝓕。','Right derived functors are computed using an injective resolution: apply f_* to I• and take the q-th cohomology sheaf.')},
 {f:[R`h^2=v^2=0,\qquad hv=vh`,R`f:X\to Y,\quad\mathcal F\in\operatorname{Mod}(\mathcal O_X)`,R`0\to\mathcal F\to I^\bullet`,R`Z_v^{p,q}:=\ker v^{p,q},\quad B_v^{p,q}:=\operatorname{im}v^{p,q-1}`,R`\mathcal H_v^q(J^{p,\bullet}):=Z_v^{p,q}/B_v^{p,q}`],note:t('先取 𝓕 的内射分解 I•，再为 A•=f_*I• 选取 J。p 是分解次数，q 是 A 的原次数。逐行分解 A 的同时，也分解其闭元、边界与上同调层；这正是 Cartan–Eilenberg 条件。取 J^{p,q}=0 当 p<0 或 q<0。','First resolve 𝓕 by I•, then choose J for A•=f_*I•. The indices p and q are the resolution degree and the original degree of A. Resolve its terms, cycles, boundaries and cohomology compatibly: this is the Cartan–Eilenberg condition. Set J^{p,q}=0 for p<0 or q<0.'),detail:t('我们采用 h、v 交换的约定。对每个 q，以下四个增广横向复形都是内射分解：','We use commuting h and v. For each q, all four augmented horizontal complexes below are injective resolutions:')+eq(R`\begin{aligned}A^q&\to J^{\bullet,q},&\ker d_A^q&\to Z_v^{\bullet,q},\\\operatorname{im}d_A^{q-1}&\to B_v^{\bullet,q},&\mathcal H^q(A)&\to\mathcal H_v^q(J^{\bullet,\bullet}).\end{aligned}`)+para(t('其存在性由足够多内射对象及马蹄引理给出。这里的 B_v、Z_v 是层的核与像，不是第一节的滤过子空间 B_r、Z_r。','Existence follows from enough injectives and the horseshoe lemma. Here B_v and Z_v are sheaf images and kernels, distinct from the filtered subspaces B_r and Z_r of §1.'))},
 {f:[R`K^{p,q}=\Gamma(Y,J^{p,q})`],note:t('J 已在 3.4 定义。现在逐项取 Y 上的全局截面，得到双分次对象 K；下一条再定义两个微分。若 X、Y 是 k-概形，则这些项是 k-向量空间。','With J defined in 3.4, take global sections on Y term by term to obtain the bigraded object K. The next entry defines its two differentials. For k-schemes X and Y, these terms are k-vector spaces.'),detail:t('Γ(Y,−) 是加性左正合函子，可作用于 J 的各项与映射。此步仅定义对象，不将 Γ 与任意复形的上同调交换。','Γ(Y,−) is additive and left exact and can be applied to the terms and maps of J. This step only defines the object; it does not commute Γ with cohomology of arbitrary complexes.')},
 {f:[R`\delta_2^{p+1,q}\delta_1^{p,q}+\delta_1^{p,q+1}\delta_2^{p,q}=(-1)^{p+1}\Gamma(vh)+(-1)^p\Gamma(hv)=0`],note:t('现在 K 的每个小块都有明确含义：J 的全局截面。符号 (−1)^p 将交换的层映射转成第一节使用的反交换微分。','Each K block is now specified: the global sections of J. The sign (−1)^p converts commuting sheaf maps into the anticommuting differentials used in §1.'),detail:t('h²=v²=0 给出两个微分各自平方为零。上述计算给出反交换关系，因此 D²=0；不能在交换约定下直接令 δ₁=Γh、δ₂=Γv 而不处理符号。','The equations h²=v²=0 give the two square-zero identities. The displayed computation gives anticommutation and hence D²=0; the sign is essential when starting with commuting maps.')},
 {f:[R`E_0^{p,q}\cong K^{p,q},\quad d_0^{p,q}\leftrightarrow\delta_2^{p,q}`],note:t('使用第一节同一个列滤过。于是先沿 q 方向取上同调得到 E₁，再沿 p 方向取上同调得到 E₂。','Use exactly the column filtration of §1. Taking cohomology first in q gives E₁, and then in p gives E₂.'),detail:t('δ₁ 将第一指标提高一，δ₂ 保持第一指标，所以 D 保持 F。关联分次消去 δ₁ 的贡献，仅保留 δ₂。每条总次数对角线有限，所以总复形使用普通直和即可。','δ₁ raises the first index while δ₂ preserves it, so D preserves F. Passing to the associated graded removes δ₁ and retains δ₂. Each total-degree diagonal is finite, so ordinary direct sums suffice.')},
 {f:[R`E_2^{p,q}\cong H^p\!\left(\Gamma(Y,\mathcal H_v^q(J^{\bullet,\bullet})),h\right)\cong H^p(Y,R^qf_*\mathcal F)`],note:t('E₁ 仍是一个内射分解的截面项；到 E₂ 才得到熟悉的层上同调。因此定理选择明确写出第二页。','E₁ still consists of section terms of an injective resolution; E₂ is the familiar sheaf cohomology. This is why the theorem displays page two.'),detail:para(t('Proof. 固定 p。以下短正合列分裂，因为 B_v^{p,q} 与 Z_v^{p,q} 都是内射对象：','Proof. Fix p. The following short exact sequences split because B_v^{p,q} and Z_v^{p,q} are injective:'))+eq(R`0\to B_v^{p,q}\to Z_v^{p,q}\to\mathcal H_v^q(J^{p,\bullet})\to0`)+eq(R`0\to Z_v^{p,q}\to J^{p,q}\to B_v^{p,q+1}\to0`)+para(t('因此 Γ(Y,−) 保持这些列的正合性，得到 E₁ 的上述同构。由 CE 条件，𝓗_v^q(J^{•,•}) 是 R^qf_*𝓕 的内射分解，再取横向上同调便得到 E₂。这里并未假定 Γ 与任意复形的上同调交换。','Thus Γ(Y,−) preserves their exactness, giving the displayed identification of E₁. The CE condition makes 𝓗_v^q(J^{•,•}) an injective resolution of R^qf_*𝓕; horizontal cohomology gives E₂. No commutation of Γ with cohomology of arbitrary complexes is assumed.'))},
 {f:[R`H^n(C^\bullet,D)\cong H^n(X,\mathcal F)`,R`E_\infty^{p,q}\cong\operatorname{Gr}_F^pH^{p+q}(X,\mathcal F)`],note:t('第一象限保证收敛到总复形上同调；还需识别总复形的上同调，才能得到 Leray 的目标。E₂ 并不表示已经稳定。','The first quadrant gives convergence to total cohomology. Identifying that cohomology gives the Leray target. E₂ does not assert stabilization.'),detail:para(t('Proof. 内射层 I^q 是松弛层，f_*I^q 仍松弛，因而对 Γ(Y,−) 无上同调。双复形若先沿 p 取上同调，只剩 p=0 的复形 Γ(Y,A•)。故','Proof. An injective sheaf I^q is flasque, and f_*I^q is flasque and hence Γ(Y,−)-acyclic. Taking p-cohomology first leaves only the p=0 complex Γ(Y,A•). Therefore'))+eq(R`H^n(C,D)\cong H^n(\Gamma(Y,A^\bullet))=H^n(\Gamma(X,I^\bullet))\cong H^n(X,\mathcal F).`)},
 {f:[R`\mathcal G_m^q:=L(mH)\otimes R^qg_*\omega_W`,R`H^0(V,L(mH)\otimes R^qg_*\omega_W)\cong H^q(W,\omega_W\otimes g^*L(mH))=0\quad(q>0)`,R`\Longrightarrow\quad R^qg_*\omega_W=0\quad(q>0)`],note:t('Kollár–Mori §2.5，证明 (2.64) 的 Step 4（pp. 71–72）。将书中的扭曲参数改记 m，避免与页数 r 混淆；完整假设与消失定理输入见证明。','Kollár–Mori §2.5, Step 4 of the proof of (2.64), pp. 71–72.  The twist m is distinct from the page r; the proof lists the hypotheses and vanishing input.'),detail:para(t('这里 V 光滑复射影，L 为 nef 且 big 线丛，g:W→V 是使 g*L≡A+E 的双有理态射，W 光滑射影、A ample、E 为系数小于 1 的有效 SNC 有理除子；H 为很充足除子。','Here V is smooth complex projective, L is nef and big, and g:W→V is birational with W smooth projective and g*L≡A+E, where A is ample and E is an effective SNC rational divisor with coefficients below 1; H is very ample.'))+para(t('Proof. 投影公式给出左侧的 E₂ 项。固定 m 充分大，Serre 消失使所有 p>0 的项为零，因此仅剩 p=0 一列，所有后续微分为零。总次数 q 的滤过只有一个可能非零的商，收敛于是给出所示同构。','Proof. The projection formula gives the displayed E₂ terms. For sufficiently large m, Serre vanishing kills every term with p>0. Only column p=0 remains, so later differentials vanish. The filtration in total degree q has only one possibly nonzero quotient; convergence gives the displayed isomorphism.'))+para(t('右端消失是外部消失定理的输入，不是由谱序列自动得到。对这样的 m，L(mH)⊗R^qg_*ω_W 还由全局截面生成。其全局截面为零，故该层为零；张量可逆层的逆便得到 R^qg_*ω_W=0。','Vanishing on the right is an input from a vanishing theorem, not a consequence of spectral sequences alone. For such m, L(mH)⊗R^qg_*ω_W is also globally generated. Zero global sections force this sheaf to be zero; tensoring by the inverse line bundle gives R^qg_*ω_W=0.'))},
 {f:[R`E_2^{p,q}=\begin{cases}H^p(X,\mathcal O_X),&q=0,\\0,&q>0,\end{cases}`,R`E_2^{n,0}\cong E_\infty^{n,0}\cong H^n(\widetilde X,\mathcal O_{\widetilde X})`],note:t('取复数域上具有有理奇点的正规簇 X 及一个解消 π。假设正是 KM Definition 5.8 中有理解消的条件；此处展开其 Leray 推论。','Let X be a normal complex variety with rational singularities and π a resolution. The hypotheses are the rational-resolution conditions of KM Definition 5.8; here we expand their Leray consequence.'),detail:para(t('Proof. 高阶直像消失使 E₂ 仅剩 q=0 一行，故 E₂=E∞。在总次数 n 上，F⁰=⋯=Fⁿ=Hⁿ，Fⁿ⁺¹=0，所以唯一的滤过商就是整个 Hⁿ。边缘映射由自然映射 𝒪_X→Rπ_*𝒪_Ẋ 诱导，给出左侧所写的典范同构。','Proof. Vanishing of higher direct images leaves only row q=0, so E₂=E∞. In degree n, F⁰=⋯=Fⁿ=Hⁿ and Fⁿ⁺¹=0. Thus the sole filtration quotient is all of Hⁿ. The edge map induced by 𝒪_X→Rπ_*𝒪_Ẋ is the canonical isomorphism displayed on the left.'))}
 ];
 const e=data[page]||data[0],title=`3.${page+1} ${t(...lerayTitles[page])}`;
 const refs=page>=9?`<a href="${km}" target="_blank" rel="noopener">Kollár–Mori (1998), ${page===9?'§2.5, pp. 71–72':'Definition 5.8'}</a>`:'<a href="https://stacks.math.columbia.edu/tag/015G" target="_blank" rel="noopener">Stacks, 13.21</a> · <a href="https://stacks.math.columbia.edu/tag/01EY" target="_blank" rel="noopener">Leray, 20.13.4</a>';
 return proofPanel({key:'leray-'+page,title,formulas:e.f,note:e.note,details:(e.detail.includes('<')?e.detail:para(e.detail)).replaceAll('Proof.',t('证明。','Proof.'))+`<p>${refs}</p>`,math,language});
}
export function lerayDiagram({page,label,t}){
 if(page<3){
  const lines=[
   [R`\mathcal F\quad\text{on }X`,R`X\xrightarrow{f}Y`],
   [R`\mathcal F\longrightarrow I^\bullet`,R`0\to\mathcal F\to I^0\to I^1\to I^2\to\cdots`],
   [R`I^\bullet\xrightarrow{\ f_*\ }A^\bullet`,R`f_*I^0\to f_*I^1\to f_*I^2\to\cdots`]
  ][page];
  return `<svg viewBox="0 0 840 525" role="img" aria-label="${t('Leray 构造步骤','Leray construction')}"></svg>`+label(420,180,lines[0],780,'title')+label(420,300,lines[1],780,'gold');
 }
 page-=3;
 let svg='<defs><marker id="leray-tip" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="6" markerHeight="6" orient="auto"><path d="M1 1L8 5L1 9" fill="none" stroke="#77d8cc" stroke-width="1.3"/></marker></defs>',labels='';
 const arrow=(x,y,X,Y)=>{svg+=`<path d="M${x},${y} L${X},${Y}" fill="none" stroke="#77d8cc" stroke-width="1.4" marker-end="url(#leray-tip)"/>`;};
 {
  const example=page>=6,zero=(p,q)=>example&&(page===6?p>0:q>0);
  labels+=label(420,38,page===0?R`h:(p,q)\mapsto(p+1,q)\qquad v:(p,q)\mapsto(p,q+1)`:example?R`E_2=E_\infty`:page===4?R`E_0\ \rightsquigarrow\ E_1\ \rightsquigarrow\ E_2`:R`K^{p,q}:=\Gamma(Y,J^{p,q})`,800,'title');
  for(let p=0;p<3;p++)for(let q=0;q<3;q++){
   const x=170+230*p,y=350-95*q,z=zero(p,q),tex=example?(z?'0':`E_2^{${p},${q}}`):`${page===0?'J':'K'}^{${p},${q}}`;
   svg+=`<rect x="${x-43}" y="${y-23}" width="86" height="46" rx="9" fill="${z?'transparent':'#18343a'}" stroke="${z?'#47636833':'#7baba777'}"/>`;
   labels+=label(x,y,tex,180,z?'small':'');
   if(!example&&page!==1){if(p<2){arrow(x+49,y,x+181,y);labels+=label(x+115,y-17,page===0?`h^{${p},${q}}`:`\\delta_1^{${p},${q}}`,100,'small');}if(q<2){arrow(x,y-29,x,y-65);labels+=label(x+40,y-47,page===0?`v^{${p},${q}}`:`\\delta_2^{${p},${q}}`,90,'small');}}
  }
  labels+=label(400,104,R`\cdots`,70,'small')+label(755,255,R`\vdots`,60,'small');
  labels+=label(420,410,example?(page===6?R`E_2^{0,n}\cong H^n(W,\omega_W\otimes g^*L(mH))`:R`E_2^{n,0}\cong H^n(\widetilde X,\mathcal O_{\widetilde X})`):page===0?R`0\to A^q\to J^{0,q}\to J^{1,q}\to\cdots`:page===1?R`K^{p,q}:=\Gamma(Y,J^{p,q})`:page===3?R`F^aC^n=\bigoplus_{p\ge a}K^{p,n-p}`:page===4?R`E_2^{p,q}\cong H^p(Y,R^qf_*\mathcal F)`:page===5?R`H^n(\operatorname{Tot}K)\cong H^n(X,\mathcal F)`:R`\delta_1=\Gamma(h),\qquad\delta_2|_{K^{p,q}}=(-1)^p\Gamma(v)`,800,'gold');
 }
 return `<svg viewBox="0 0 840 525" role="img" aria-label="${t('Leray 双复形与退化示意','Leray double complex and degeneration')}">${svg}</svg>${labels}`;
}
