import {replaceMathContent} from './math-transitions.js?v=64';

// First establish stabilization; only then name its common stable term.
export function createStabilityProof({board,math,language,onSelect=()=>{}}){
 const R=String.raw,t=(zh,en)=>language()==='en'?en:zh,steps=[0,0];let context=null;
 const entries=[[
  {name:['出射微分','Outgoing differential'],mode:'outgoing',f:[R`r>q+1\ \Longrightarrow\ q-r+1<0`,R`E_r^{p+r,q-r+1}=0,\qquad d_r^{p,q}=0`],note:()=>t('第一象限以外的项为零。中间项中的元素沿出射微分映到零；中间的空间本身并不消失。','Terms outside the first quadrant vanish. An element of the central term maps to zero under the outgoing differential; the central space itself remains.')},
  {name:['入射微分','Incoming differential'],mode:'incoming',f:[R`r>p\ \Longrightarrow\ p-r<0`,R`E_r^{p-r,q+r-1}=0,\qquad d_r^{p-r,q+r-1}=0`],note:()=>t('入射源是零空间，所以入射微分的像为零。动画沿箭头演示 0 映到 0，不从零空间发出非零元素，也不倒转微分。','The source is the zero space, so the incoming image is zero. The animation follows the arrow as 0 maps to 0; it creates no nonzero source element and does not reverse the differential.')},
  {name:['后续各页','All later pages'],mode:'stable',f:[R`s\ge r>\max\{p,q+1\}`,R`E_{s+1}^{p,q}:=\frac{\ker d_s^{p,q}}{\operatorname{im}d_s^{p-s,q+s-1}}=E_s^{p,q}/0`,R`\begin{aligned}\phi_s^{p,q}:E_s^{p,q}&\xrightarrow{\sim}E_{s+1}^{p,q}\\ \xi&\longmapsto\xi+0\end{aligned}`],note:()=>t('同一论证适用于每个后续页 s，因此这些自然同构可以依次复合。稳定的是选定的双次数位置，不是在某个统一页数后整张图都不变。','The same argument applies on every later page s, so these natural isomorphisms compose. Stabilization concerns the selected bidegree, not the entire page at one uniform stage.')}
 ],[
  {name:['稳定项','The stable term'],mode:'stable',f:[R`r_0>\max\{p,q+1\}`,R`E_\infty^{p,q}:=E_{r_0}^{p,q}`],note:()=>t('由前一命题，后续各页在此位置自然同构。选取任意满足条件的 r₀，并沿这些自然同构识别，所得共同稳定空间记作 E∞。','By the preceding proposition, all subsequent terms at this bidegree are naturally isomorphic. Choose any qualifying r₀ and identify them by these natural maps; their common stable space is denoted E∞.')},
  {name:['自然识别','Natural identifications'],mode:'stable',f:[R`s\ge r_0\ \Longrightarrow\ E_{r_0}^{p,q}\xrightarrow{\phi_{r_0}}\cdots\xrightarrow{\phi_{s-1}}E_s^{p,q}`,R`\iota_s:E_s^{p,q}\xrightarrow{\sim}E_\infty^{p,q}`,R`\iota_{r_0}:=\mathrm{id},\qquad\iota_{s+1}\circ\phi_s=\iota_s`],note:()=>t('ι 是上述复合自然同构的逆。换用另一个稳定页，得到典范同构的稳定项；这里没有任意挑选向量空间同构。','The maps ι are inverses of these composites. Choosing another stable page gives a canonically isomorphic stable term; no arbitrary vector-space isomorphism is chosen.')},
  {name:['逐位置稳定','Pointwise stabilization'],mode:'stable',f:[R`\forall p,q\ge0\ \exists r_0\ \forall s\ge r_0:\quad E_s^{p,q}\cong E_\infty^{p,q}`,R`r_0=\max\{p+1,q+2\}\ \text{is sufficient}`],note:()=>t('r₀ 可以依赖于 p、q；第一象限本身不保证所有位置有统一的稳定页。图上只标记选定位置的稳定项，其他节点仍属于当前页。','The bound r₀ may depend on p and q; the first-quadrant condition alone gives no uniform stable page. Only the selected stable term is identified in the diagram; other nodes still belong to the current page.')}
 ]];
 function paint(){
  if(!context)return;const {state,example:e}=context,section=state.step,index=steps[section],entry=entries[section][index];
  const example=section===1?R`E_\infty^{${e.p},${e.q}}:=E_{${e.r}}^{${e.p},${e.q}}`:index===0?R`d_{${e.r}}^{${e.p},${e.q}}:E_{${e.r}}^{${e.p},${e.q}}\longrightarrow E_{${e.r}}^{${e.p+e.r},${e.q-e.r+1}}=0`:index===1?R`d_{${e.r}}^{${e.p-e.r},${e.q+e.r-1}}:0=E_{${e.r}}^{${e.p-e.r},${e.q+e.r-1}}\longrightarrow E_{${e.r}}^{${e.p},${e.q}}`:R`E_{${e.r}}^{${e.p},${e.q}}\cong E_{${e.r+1}}^{${e.p},${e.q}}\cong E_{${e.r+2}}^{${e.p},${e.q}}\cong\cdots`;
  const note=entry.note().replace(/E∞|r₀|ι/g,k=>math({'E∞':'E_\\infty','r₀':'r_0','ι':'\\iota'}[k]));
  replaceMathContent(board,`<nav class="proof-steps" aria-label="${t('数学阐述步骤','Exposition steps')}">${entries[section].map((x,j)=>`<button data-stability-proof="${j}" aria-pressed="${j===index}">${j+1}. ${t(...x.name)}</button>`).join('')}</nav><div class="operation-content evolution-exposition">${entry.f.map(f=>`<div class="operation-equation">${math(f,true)}</div>`).join('')}</div><p class="operation-note">${note}</p><div class="operation-equation stability-example">${math(example,true)}</div><p class="operation-note proof-reference"><a href="https://www.sas.rochester.edu/mth/sites/doug-ravenel/otherpapers/McCleary-UGSS.pdf#page=19" target="_blank" rel="noopener">McCleary, §1.1, p. 5</a></p>`);
  board.dataset.currentProofTopic=section===0?'stabilization':'einfty';board.dataset.currentProofStep=String(index);
 }
 board.addEventListener('click',e=>{const button=e.target.closest('[data-stability-proof]');if(!button||!context)return;e.stopPropagation();steps[context.state.step]=Number(button.dataset.stabilityProof);paint();onSelect(entries[context.state.step][steps[context.state.step]].mode);});
 return {render(c){context=c;if(c)paint();},selectMode(mode){if(!context||context.state.step!==0)return;steps[0]=entries[0].findIndex(e=>e.mode===mode);paint();},mode(){return context?entries[context.state.step][steps[context.state.step]].mode:'outgoing';}};
}
