import {pageTransitionExposition,pageCohomologyExposition} from './page-transition.js?v=115';
import {replaceMathContent} from './math-transitions.js?v=97';
import {proofPanel,proofSections} from './proof-panel.js?v=109';

export function createStabilityProof({board,math,language}){
 const R=String.raw,t=(zh,en)=>language()==='en'?en:zh;let context=null,selectedMode='outgoing';
 const derivation=()=>[
  {name:['逐位置的界','A bound for each bidegree'],f:[R`p,q\ge0,\quad n:=p+q,\quad r_0:=\max\{p+1,q+2\}`,R`\forall s\ge r_0:\quad s>p,\quad s>q+1`,R`F^uC^m=C^m\ (u\le0),\qquad F^uC^m=0\ (u>m)`],note:t('固定 p、q 后选择这个充分界，实际可能更早稳定。第一象限只保证逐位置稳定，不保证整张谱序列有统一的稳定页。','Fix p and q before choosing this sufficient bound; stabilization may occur earlier. The first-quadrant condition gives pointwise stabilization, not a uniform stable page for the whole spectral sequence.')},
  {name:['入射与出射微分','Incoming and outgoing differentials'],f:[R`s>q+1\Longrightarrow E_s^{p+s,q-s+1}=0`,R`s>p\Longrightarrow E_s^{p-s,q+s-1}=0`,R`\ker d_s^{p,q}=E_s^{p,q},\qquad\operatorname{im}d_s^{p-s,q+s-1}=0`],note:t('第一象限以外的项在 E₀ 为零，由逐页取上同调，之后仍为零。上述两式说明此位置不再有非零的入射或出射微分。','Terms outside the first quadrant vanish on E₀ and remain zero on taking subsequent page cohomology. Thus both the incoming and outgoing differentials at this position vanish.')},
  {name:['分子固定','The numerator is fixed'],f:[R`Z_s^{p,q}:=F^pC^n\cap D^{-1}(F^{p+s}C^{n+1})`,R`p+s>p+q+1=n+1\Longrightarrow F^{p+s}C^{n+1}=0`,R`Z_s^{p,q}=F^pC^n\cap\ker(D:C^n\to C^{n+1})=:A`],note:t('此处 D⁻¹ 表示逆像。目标滤过层为零后，条件恰为 Da=0；分子不再依赖 s。','Here D⁻¹ denotes a preimage. Once the target filtration is zero, the condition is exactly Da=0; the numerator no longer depends on s.')},
  {name:['分母固定：高滤过项','The denominator: higher-filtration term'],f:[R`(p+1)+(q-1)=n,\qquad(p+1)+(s-1)=p+s`,R`\begin{aligned}Z_{s-1}^{p+1,q-1}&=F^{p+1}C^n\cap D^{-1}(F^{p+s}C^{n+1})\\&=F^{p+1}C^n\cap\ker D.\end{aligned}`],note:t('第一、第二个上标共同确定总次数；下标 s−1 与第一个上标 p+1 共同确定目标滤过指标。','The two superscripts determine the total degree; the subscript s−1 and first superscript p+1 determine the target filtration index.')},
  {name:['分母固定：边界项','The denominator: boundary term'],f:[R`p-(s-1)=p-s+1\le0`,R`\begin{aligned}B_{s-1}^{p,q}&=F^pC^n\cap D(F^{p-s+1}C^{n-1})\\&=F^pC^n\cap D(C^{n-1}).\end{aligned}`,R`N:=(F^{p+1}C^n\cap\ker D)+(F^pC^n\cap D(C^{n-1}))`],note:t('负滤过层不是零，而是整个相应次数的总对象。由 D²=0，边界都是闭元，故 N⊆A。','A nonpositive filtration level is the whole total object in that degree, not zero. Since D²=0, boundaries are cocycles, so N⊆A.')},
  {name:['自然映射与同构','The natural map and its inverse'],f:[R`\forall s\ge r_0:\qquad E_s^{p,q}=A/N=E_{s+1}^{p,q}`,R`\begin{aligned}\phi_s^{p,q}:E_s^{p,q}&\longrightarrow E_{s+1}^{p,q}\\[.3em][a]_s&\longmapsto[a]_{s+1}\end{aligned}`,R`[a]_s=[b]_s\iff a-b\in N\iff[a]_{s+1}=[b]_{s+1}`,R`(\phi_s^{p,q})^{-1}([a]_{s+1}):=[a]_s`],note:t('等价式同时给出良定义与单射。任意下一页的类都有代表元 a∈A，故满射；加法与数乘由同一商空间继承，所以映射线性。特别地 φᵣ₀ 是同构。这不是任意选择的向量空间同构，而是相同商模型上的恒等映射。','The equivalence proves well-definedness and injectivity. Every class on the next page has a representative a∈A, proving surjectivity. Addition and scalar multiplication are inherited from the same quotient, so the map is linear. In particular φᵣ₀ is an isomorphism: it is the identity in this common quotient model, not an arbitrary choice.')},
  {name:['与逐页上同调的相容性','Compatibility with page cohomology'],f:[R`\Psi_{s+1}^{p,q}:E_{s+1}^{p,q}\xrightarrow{\sim}\frac{\ker d_s^{p,q}}{\operatorname{im}d_s^{p-s,q+s-1}}`,R`\Psi_{s+1}^{p,q}([a]_{s+1})=[a]_s+0\qquad(s\ge r_0)`,R`\phi_s^{p,q}([a]_s)=(\Psi_{s+1}^{p,q})^{-1}([a]_s+0)=[a]_{s+1}`],note:t('因此，商模型中直接构造的映射与通过谱序列结构同构 Ψ 构造的映射相同。前面的同构证明不以这一步作为前提。','Thus the map constructed directly in the quotient model agrees with the one defined through the spectral-sequence structure isomorphism Ψ. The preceding proof of invertibility does not depend on this comparison.')},
  {name:['稳定项及其自然识别','The stable term and natural identifications'],f:[R`E_\infty^{p,q}:=E_{r_0}^{p,q}`,R`\iota_{r_0}:=\mathrm{id},\quad\iota_s:=(\phi_{s-1}\circ\cdots\circ\phi_{r_0})^{-1}\quad(s>r_0)`,R`\iota_{s+1}\circ\phi_s=\iota_s`,R`\forall p,q\ge0\ \exists r_0(p,q)\ \forall s\ge r_0(p,q):\ E_s^{p,q}\cong E_\infty^{p,q}`],note:t('换用另一满足稳定界的页，通过上述映射得到典范同构的稳定项。所依赖的是逐位置的自然识别，而非对整张图选一个共同的页数。','Another page satisfying the bound gives a canonically isomorphic stable term through these maps. The construction uses natural identifications at each bidegree, rather than one common page number for the entire grid.')}
 ];
 function paint(){
  if(!context)return;
  if(context.state.step===0&&context.state.notePage<2){const cohomology=context.state.notePage===0;replaceMathContent(board,(cohomology?pageCohomologyExposition:pageTransitionExposition)({math,language}));board.dataset.currentProofTopic=cohomology?'page-cohomology':'page-transition';delete board.dataset.currentProofStep;return;}
  const stable=context.state.step===1;
  const formulas=stable?[R`r_0:=\max\{p+1,q+2\},\qquad s\ge r_0`,R`\phi_s^{p,q}:E_s^{p,q}\xrightarrow{\sim}E_{s+1}^{p,q},\quad[a]_s\longmapsto[a]_{s+1}`]:[R`r>\max\{p,q+1\}\Longrightarrow d_r^{p,q}=d_r^{p-r,q+r-1}=0`,R`E_r^{p,q}\xrightarrow{\sim}E_{r+1}^{p,q}\xrightarrow{\sim}\cdots`];
  const note=stable?t(`对每个固定的 ${math('p,q')}，后续各页具有相同的分子与分母。稳定界可以依赖 ${math('p,q')}；沿上述自然同构识别后记作 ${math('E_\\infty^{p,q}')}。`,`For fixed ${math('p,q')}, all later pages have the same numerator and denominator. The bound may depend on ${math('p,q')}; their common term under these natural identifications is denoted ${math('E_\\infty^{p,q}')}.`):t('入射源与出射靶都落在第一象限外，因此像为零、核为整个当前项。','The incoming source and outgoing target lie outside the first quadrant, so the image is zero and the kernel is the entire current term.');
  const details=proofSections(derivation(),{math,title:e=>t(...e.name),note:e=>e.note})+'<p><a href="https://www.sas.rochester.edu/mth/sites/doug-ravenel/otherpapers/McCleary-UGSS.pdf#page=19" target="_blank" rel="noopener">McCleary, §1.1, p. 5; Theorem 2.6</a></p>';
  replaceMathContent(board,proofPanel({key:stable?'stable-term':'stabilization',title:t('逐位置稳定与自然同构的证明','Pointwise stabilization and the natural isomorphisms'),formulas,note,details,math,language}));
  board.dataset.currentProofTopic=stable?'einfty':'stabilization';delete board.dataset.currentProofStep;
 }
 return {render(c){context=c;if(c)paint();},selectMode(mode){selectedMode=mode;},mode:()=>context?.state.step===1?'stable':selectedMode};
}
