import Linear
set_option pp.universes false
set_option pp.proofs false
#check LinearStudy.powerSeriesQuotient_variable_nilpotent
#print axioms LinearStudy.powerSeriesQuotient_variable_nilpotent
#check LinearStudy.powerSeries_tensor_diagonal_eq_coordinate_ideal
#print axioms LinearStudy.powerSeries_tensor_diagonal_eq_coordinate_ideal
#check LinearStudy.powerSeriesQuotient_diagonal_jacobian
#print axioms LinearStudy.powerSeriesQuotient_diagonal_jacobian
#check LinearStudy.finiteFlat_centered_jacobian_annihilator
#print axioms LinearStudy.finiteFlat_centered_jacobian_annihilator
#check LinearStudy.equationChangeQuotientEquiv
#print axioms LinearStudy.equationChangeQuotientEquiv
#check LinearStudy.equationChangeQuotientEquiv_mk
#print axioms LinearStudy.equationChangeQuotientEquiv_mk
#check LinearStudy.regularSequence_change_equations
#print axioms LinearStudy.regularSequence_change_equations
#check LinearStudy.equationChangeQuotient_finite
#print axioms LinearStudy.equationChangeQuotient_finite
#check LinearStudy.equationChangeQuotient_flat
#print axioms LinearStudy.equationChangeQuotient_flat
#check LinearStudy.nilradical_kernel_transport
#print axioms LinearStudy.nilradical_kernel_transport
#check LinearStudy.iterate_degree_exceeds
#print axioms LinearStudy.iterate_degree_exceeds
#check LinearStudy.intersection_degree_lt
#print axioms LinearStudy.intersection_degree_lt
#check LinearStudy.degree_contradiction
#print axioms LinearStudy.degree_contradiction
#check LinearStudy.uniform_degree_estimate_impossible
#print axioms LinearStudy.uniform_degree_estimate_impossible
#check LinearStudy.determinant_mul_coordinate_of_relation
#print axioms LinearStudy.determinant_mul_coordinate_of_relation
#check LinearStudy.determinant_annihilates_coordinate_ideal
#print axioms LinearStudy.determinant_annihilates_coordinate_ideal
#check LinearStudy.coefficientDeterminant_annihilates_quotient
#print axioms LinearStudy.coefficientDeterminant_annihilates_quotient
#check LinearStudy.diagonal_annihilator_coefficient_isUnit
#print axioms LinearStudy.diagonal_annihilator_coefficient_isUnit
#check LinearStudy.diagonal_annihilator_multiplication_nonzero
#print axioms LinearStudy.diagonal_annihilator_multiplication_nonzero
#check LinearStudy.pairingTensorEndEquiv
#print axioms LinearStudy.pairingTensorEndEquiv
#check LinearStudy.pairingTensorEndEquiv_tmul
#print axioms LinearStudy.pairingTensorEndEquiv_tmul
#check LinearStudy.pairingTensorEndEquiv_left
#print axioms LinearStudy.pairingTensorEndEquiv_left
#check LinearStudy.pairingTensorEndEquiv_right
#print axioms LinearStudy.pairingTensorEndEquiv_right
#check LinearStudy.pairingDiagonal
#print axioms LinearStudy.pairingDiagonal
#check LinearStudy.pairingDiagonal_annihilates
#print axioms LinearStudy.pairingDiagonal_annihilates
#check LinearStudy.pairingTensorEndEquiv_trace
#print axioms LinearStudy.pairingTensorEndEquiv_trace
#check LinearStudy.pairingDiagonal_multiplication_eq_traceElement
#print axioms LinearStudy.pairingDiagonal_multiplication_eq_traceElement
#check LinearStudy.pairingTensorEndEquiv_of_diagonal_annihilator
#print axioms LinearStudy.pairingTensorEndEquiv_of_diagonal_annihilator
#check LinearStudy.pairingDiagonal_generates_annihilator
#print axioms LinearStudy.pairingDiagonal_generates_annihilator
#check LinearStudy.diagonal_annihilator_multiplication_eq_trace_multiple
#print axioms LinearStudy.diagonal_annihilator_multiplication_eq_trace_multiple
#check LinearStudy.pairingRightReduction
#print axioms LinearStudy.pairingRightReduction
#check LinearStudy.pairingRightReduction_tmul
#print axioms LinearStudy.pairingRightReduction_tmul
#check LinearStudy.pairingRightReduction_pairing
#print axioms LinearStudy.pairingRightReduction_pairing
#check LinearStudy.pairingRightReduction_diagonal
#print axioms LinearStudy.pairingRightReduction_diagonal
#check LinearStudy.epsilon
#print axioms LinearStudy.epsilon
#check LinearStudy.doublePoint_decomposition
#print axioms LinearStudy.doublePoint_decomposition
#check LinearStudy.doublePointPairingMap
#print axioms LinearStudy.doublePointPairingMap
#check LinearStudy.doublePointPerfectPairing
#print axioms LinearStudy.doublePointPerfectPairing
#check LinearStudy.doublePoint_nilradical
#print axioms LinearStudy.doublePoint_nilradical
#check LinearStudy.doublePoint_epsilon_is_dualGenerator
#print axioms LinearStudy.doublePoint_epsilon_is_dualGenerator
#check LinearStudy.doublePoint_annihilator_generated
#print axioms LinearStudy.doublePoint_annihilator_generated
#check LinearStudy.doublePoint_nilradical_annihilator
#print axioms LinearStudy.doublePoint_nilradical_annihilator
#check LinearStudy.doublePoint_quotient_generator_nonzero
#print axioms LinearStudy.doublePoint_quotient_generator_nonzero
#check LinearStudy.doublePoint_residue_to_evaluation
#print axioms LinearStudy.doublePoint_residue_to_evaluation
#check LinearStudy.dualGenerator
#print axioms LinearStudy.dualGenerator
#check LinearStudy.dualGenerator_pairing
#print axioms LinearStudy.dualGenerator_pairing
#check LinearStudy.dualGenerator_functional
#print axioms LinearStudy.dualGenerator_functional
#check LinearStudy.dualGenerator_annihilates
#print axioms LinearStudy.dualGenerator_annihilates
#check LinearStudy.annihilator_eq_scalar_generator
#print axioms LinearStudy.annihilator_eq_scalar_generator
#check LinearStudy.annihilator_iff_scalar_multiple
#print axioms LinearStudy.annihilator_iff_scalar_multiple
#check LinearStudy.dualGenerator_scalar_retraction
#print axioms LinearStudy.dualGenerator_scalar_retraction
#check LinearStudy.dualGenerator_quotient_nonzero
#print axioms LinearStudy.dualGenerator_quotient_nonzero
#check LinearStudy.weightedEvaluation
#print axioms LinearStudy.weightedEvaluation
#check LinearStudy.weightedEvaluation_apply
#print axioms LinearStudy.weightedEvaluation_apply
#check LinearStudy.weightedEvaluation_single
#print axioms LinearStudy.weightedEvaluation_single
#check LinearStudy.weightedEvaluation_nonzero
#print axioms LinearStudy.weightedEvaluation_nonzero
#check LinearStudy.extend_relation_by_zero
#print axioms LinearStudy.extend_relation_by_zero
#check LinearStudy.relation_factors_through_exact_sequence
#print axioms LinearStudy.relation_factors_through_exact_sequence
#check LinearStudy.factored_relation_nonzero
#print axioms LinearStudy.factored_relation_nonzero
#check LinearStudy.duality_zero_iff
#print axioms LinearStudy.duality_zero_iff
#check LinearStudy.homogeneousPointEvaluation
#print axioms LinearStudy.homogeneousPointEvaluation
#check LinearStudy.homogeneousPointEvaluation_apply
#print axioms LinearStudy.homogeneousPointEvaluation_apply
#check LinearStudy.rescaled_evaluation_relation
#print axioms LinearStudy.rescaled_evaluation_relation
#check LinearStudy.rescaled_evaluation_relation_zero
#print axioms LinearStudy.rescaled_evaluation_relation_zero
#check LinearStudy.quotientSpecialization_finite
#print axioms LinearStudy.quotientSpecialization_finite
#check LinearStudy.powerSeries_specialized_quotient_finite
#print axioms LinearStudy.powerSeries_specialized_quotient_finite
#check LinearStudy.powerSeries_specialized_quotient_artinian
#print axioms LinearStudy.powerSeries_specialized_quotient_artinian
#check LinearStudy.finiteFlat_closedFiber_traceElement
#print axioms LinearStudy.finiteFlat_closedFiber_traceElement
#check LinearStudy.firstJet
#print axioms LinearStudy.firstJet
#check LinearStudy.firstJet_fst
#print axioms LinearStudy.firstJet_fst
#check LinearStudy.firstJet_snd
#print axioms LinearStudy.firstJet_snd
#check LinearStudy.firstJet_surjective
#print axioms LinearStudy.firstJet_surjective
#check LinearStudy.firstJet_kernel
#print axioms LinearStudy.firstJet_kernel
#check LinearStudy.doublePointPowerSeriesEquiv
#print axioms LinearStudy.doublePointPowerSeriesEquiv
#check LinearStudy.doublePointPowerSeriesEquiv_mk
#print axioms LinearStudy.doublePointPowerSeriesEquiv_mk
#check LinearStudy.doublePoint_actual_jacobian
#print axioms LinearStudy.doublePoint_actual_jacobian
#check LinearStudy.doublePoint_actual_jacobian_generates
#print axioms LinearStudy.doublePoint_actual_jacobian_generates
#check LinearStudy.annihilates_nilradical_algEquiv
#print axioms LinearStudy.annihilates_nilradical_algEquiv
#check LinearStudy.quadratic_powerSeries_jacobian_annihilator
#print axioms LinearStudy.quadratic_powerSeries_jacobian_annihilator
#check LinearStudy.flat_genericFiber_injective
#print axioms LinearStudy.flat_genericFiber_injective
#check LinearStudy.flat_genericFiber_descend_annihilation
#print axioms LinearStudy.flat_genericFiber_descend_annihilation
#check LinearStudy.total_invariance_membership
#print axioms LinearStudy.total_invariance_membership
#check LinearStudy.total_invariance_iterate
#print axioms LinearStudy.total_invariance_iterate
#check LinearStudy.invariant_restriction
#print axioms LinearStudy.invariant_restriction
#check LinearStudy.restrictInvariant
#print axioms LinearStudy.restrictInvariant
#check LinearStudy.invariant_restriction_surjective
#print axioms LinearStudy.invariant_restriction_surjective
#check LinearStudy.powerSeriesQuotient_polynomial_diagonal
#print axioms LinearStudy.powerSeriesQuotient_polynomial_diagonal
#check LinearStudy.powerSeriesQuotient_jacobian_nonzero
#print axioms LinearStudy.powerSeriesQuotient_jacobian_nonzero
#check LinearStudy.powerSeriesQuotient_jacobian_scalar_socle
#print axioms LinearStudy.powerSeriesQuotient_jacobian_scalar_socle
#check LinearStudy.powerSeriesQuotient_jacobian_socle
#print axioms LinearStudy.powerSeriesQuotient_jacobian_socle
#check LinearStudy.finiteFlat_closedFiber_jacobian_nonzero
#print axioms LinearStudy.finiteFlat_closedFiber_jacobian_nonzero
#check LinearStudy.finiteFlat_residueTensor_jacobian_nonzero
#print axioms LinearStudy.finiteFlat_residueTensor_jacobian_nonzero
#check LinearStudy.finiteFlat_jacobian_primitive
#print axioms LinearStudy.finiteFlat_jacobian_primitive
#check LinearStudy.finiteFlat_residueTensor_jacobian_scalar_socle
#print axioms LinearStudy.finiteFlat_residueTensor_jacobian_scalar_socle
#check LinearStudy.powerSeriesJacobianClass
#print axioms LinearStudy.powerSeriesJacobianClass
#check LinearStudy.powerSeriesQuotient_jacobian_trace_multiple
#print axioms LinearStudy.powerSeriesQuotient_jacobian_trace_multiple
#check LinearStudy.powerSeriesQuotient_jacobian_annihilates_nilradical
#print axioms LinearStudy.powerSeriesQuotient_jacobian_annihilates_nilradical
#check LinearStudy.coefficientMatrix_koszul_compatibility
#print axioms LinearStudy.coefficientMatrix_koszul_compatibility
#check LinearStudy.coefficientKoszulComparison
#print axioms LinearStudy.coefficientKoszulComparison
#check LinearStudy.coefficientKoszulComparison_top
#print axioms LinearStudy.coefficientKoszulComparison_top
#check LinearStudy.ideal_ofFn
#print axioms LinearStudy.ideal_ofFn
#check LinearStudy.koszul_ofFn
#print axioms LinearStudy.koszul_ofFn
#check LinearStudy.functionKoszulAugmentation
#print axioms LinearStudy.functionKoszulAugmentation
#check LinearStudy.functionKoszulAugmentation_comp_d
#print axioms LinearStudy.functionKoszulAugmentation_comp_d
#check LinearStudy.functionKoszulAugmentationMap
#print axioms LinearStudy.functionKoszulAugmentationMap
#check LinearStudy.functionKoszulAugmentation_exact
#print axioms LinearStudy.functionKoszulAugmentation_exact
#check LinearStudy.functionKoszulResolution
#print axioms LinearStudy.functionKoszulResolution
#check LinearStudy.koszul_top_differential_functional_mem
#print axioms LinearStudy.koszul_top_differential_functional_mem
#check LinearStudy.homotopic_koszul_top_coordinates_congr
#print axioms LinearStudy.homotopic_koszul_top_coordinates_congr
#check LinearStudy.koszulAugmentation
#print axioms LinearStudy.koszulAugmentation
#check LinearStudy.koszulAugmentation_comp_d
#print axioms LinearStudy.koszulAugmentation_comp_d
#check LinearStudy.koszulAugmentationMap
#print axioms LinearStudy.koszulAugmentationMap
#check LinearStudy.koszulAugmentation_exact
#print axioms LinearStudy.koszulAugmentation_exact
#check LinearStudy.regularKoszulResolution
#print axioms LinearStudy.regularKoszulResolution
#check LinearStudy.equationIdeal_le_coordinateIdeal
#print axioms LinearStudy.equationIdeal_le_coordinateIdeal
#check LinearStudy.equationQuotientMap
#print axioms LinearStudy.equationQuotientMap
#check LinearStudy.coefficientComparison_augmentation
#print axioms LinearStudy.coefficientComparison_augmentation
#check LinearStudy.equationMap_socleMap_comp
#print axioms LinearStudy.equationMap_socleMap_comp
#check LinearStudy.socle_element_coefficientDeterminant_multiple
#print axioms LinearStudy.socle_element_coefficientDeterminant_multiple
#check LinearStudy.coordinate_annihilator_eq_coefficientDeterminant
#print axioms LinearStudy.coordinate_annihilator_eq_coefficientDeterminant
#check LinearStudy.coefficientDeterminant_ne_zero_of_local_artinian
#print axioms LinearStudy.coefficientDeterminant_ne_zero_of_local_artinian
#check LinearStudy.socleScalarMap_kernel
#print axioms LinearStudy.socleScalarMap_kernel
#check LinearStudy.socleQuotientMap
#print axioms LinearStudy.socleQuotientMap
#check LinearStudy.socleQuotientMap_apply_mk
#print axioms LinearStudy.socleQuotientMap_apply_mk
#check LinearStudy.topKoszulGenerator
#print axioms LinearStudy.topKoszulGenerator
#check LinearStudy.topExterior_alternating_map
#print axioms LinearStudy.topExterior_alternating_map
#check LinearStudy.topKoszulCoordinate
#print axioms LinearStudy.topKoszulCoordinate
#check LinearStudy.topKoszulCoordinate_generator
#print axioms LinearStudy.topKoszulCoordinate_generator
#check LinearStudy.topKoszulCoordinate_reconstruct
#print axioms LinearStudy.topKoszulCoordinate_reconstruct
#check LinearStudy.topKoszulEquiv
#print axioms LinearStudy.topKoszulEquiv
#check LinearStudy.topKoszulCoordinate_map_generator
#print axioms LinearStudy.topKoszulCoordinate_map_generator
#check LinearStudy.topKoszul_map
#print axioms LinearStudy.topKoszul_map
#check LinearStudy.linearEquationSubmodule
#print axioms LinearStudy.linearEquationSubmodule
#check LinearStudy.linearEquationSubspace
#print axioms LinearStudy.linearEquationSubspace
#check LinearStudy.mem_linearEquationSubmodule
#print axioms LinearStudy.mem_linearEquationSubmodule
#check LinearStudy.mem_linearEquationSubspace
#print axioms LinearStudy.mem_linearEquationSubspace
#check LinearStudy.powerSeries_hasEval_of_nilpotent
#print axioms LinearStudy.powerSeries_hasEval_of_nilpotent
#check LinearStudy.nilpotentPowerSeriesEval
#print axioms LinearStudy.nilpotentPowerSeriesEval
#check LinearStudy.nilpotentPowerSeriesEval_C
#print axioms LinearStudy.nilpotentPowerSeriesEval_C
#check LinearStudy.nilpotentPowerSeriesEval_X
#print axioms LinearStudy.nilpotentPowerSeriesEval_X
#check LinearStudy.nilpotentPowerSeriesEval_comp
#print axioms LinearStudy.nilpotentPowerSeriesEval_comp
#check LinearStudy.nilpotentPowerSeriesAlgEval
#print axioms LinearStudy.nilpotentPowerSeriesAlgEval
#check LinearStudy.powerSeries_boxZero_expansion
#print axioms LinearStudy.powerSeries_boxZero_expansion
#check LinearStudy.powerSeries_map_eq_trunc_of_nilpotent
#print axioms LinearStudy.powerSeries_map_eq_trunc_of_nilpotent
#check LinearStudy.powerSeries_map_pderiv_eq_trunc_of_nilpotent
#print axioms LinearStudy.powerSeries_map_pderiv_eq_trunc_of_nilpotent
#check LinearStudy.powerSeries_nilpotent_ringHom_ext
#print axioms LinearStudy.powerSeries_nilpotent_ringHom_ext
#check LinearStudy.oneVariable_unit_factorization
#print axioms LinearStudy.oneVariable_unit_factorization
#check LinearStudy.oneVariable_closedFiber_jacobian
#print axioms LinearStudy.oneVariable_closedFiber_jacobian
#check LinearStudy.multiplicationToDual
#print axioms LinearStudy.multiplicationToDual
#check LinearStudy.multiplicationGram
#print axioms LinearStudy.multiplicationGram
#check LinearStudy.multiplicationToDual_matrix
#print axioms LinearStudy.multiplicationToDual_matrix
#check LinearStudy.perfectPairingOfUnitDet
#print axioms LinearStudy.perfectPairingOfUnitDet
#check LinearStudy.exists_perfectPairing_of_residueDet_ne_zero
#print axioms LinearStudy.exists_perfectPairing_of_residueDet_ne_zero
#check LinearStudy.annihilator_scalar_action_baseChange
#print axioms LinearStudy.annihilator_scalar_action_baseChange
#check LinearStudy.annihilator_generator_coefficient_unit_after_baseChange
#print axioms LinearStudy.annihilator_generator_coefficient_unit_after_baseChange
#check LinearStudy.annihilator_generator_survives_new_parameterIdeal
#print axioms LinearStudy.annihilator_generator_survives_new_parameterIdeal
#check LinearStudy.liftedIdeal_sup_kernel
#print axioms LinearStudy.liftedIdeal_sup_kernel
#check LinearStudy.parameterQuotient_nilradical_image_isMaximal
#print axioms LinearStudy.parameterQuotient_nilradical_image_isMaximal
#check LinearStudy.parameterQuotient_nilradical_eq
#print axioms LinearStudy.parameterQuotient_nilradical_eq
#check LinearStudy.parameterQuotient_local_artinian
#print axioms LinearStudy.parameterQuotient_local_artinian
#check LinearStudy.arbitraryParameterLifts_artinian
#print axioms LinearStudy.arbitraryParameterLifts_artinian
#check LinearStudy.completeIntersection_parameterQuotient_artinian
#print axioms LinearStudy.completeIntersection_parameterQuotient_artinian
#check LinearStudy.powerSeries_polynomial_equations_unit_change
#print axioms LinearStudy.powerSeries_polynomial_equations_unit_change
#check LinearStudy.polynomial_diagonal_difference
#print axioms LinearStudy.polynomial_diagonal_difference
#check LinearStudy.powerSeries_unit_changed_coefficientDeterminant_ne_zero
#print axioms LinearStudy.powerSeries_unit_changed_coefficientDeterminant_ne_zero
#check LinearStudy.powerSeriesConstantCoeffAlgHom
#print axioms LinearStudy.powerSeriesConstantCoeffAlgHom
#check LinearStudy.equationIdeal_le_constantCoeff_kernel
#print axioms LinearStudy.equationIdeal_le_constantCoeff_kernel
#check LinearStudy.powerSeriesQuotientAugmentation
#print axioms LinearStudy.powerSeriesQuotientAugmentation
#check LinearStudy.powerSeriesQuotientAugmentation_mk
#print axioms LinearStudy.powerSeriesQuotientAugmentation_mk
#check LinearStudy.powerSeriesQuotientAugmentation_kernel
#print axioms LinearStudy.powerSeriesQuotientAugmentation_kernel
#check LinearStudy.powerSeriesQuotientAugmentation_surjective
#print axioms LinearStudy.powerSeriesQuotientAugmentation_surjective
#check LinearStudy.powerSeriesQuotientAugmentation_kernel_nilradical
#print axioms LinearStudy.powerSeriesQuotientAugmentation_kernel_nilradical
#check LinearStudy.powerSeries_socle_generator_dualGenerator
#print axioms LinearStudy.powerSeries_socle_generator_dualGenerator
#check LinearStudy.powerSeries_traceElement_eq_rank_socle
#print axioms LinearStudy.powerSeries_traceElement_eq_rank_socle
#check LinearStudy.powerSeries_completeIntersection_traceElement
#print axioms LinearStudy.powerSeries_completeIntersection_traceElement
#check LinearStudy.powerSeries_retraction_coordinate_constantCoeff_zero
#print axioms LinearStudy.powerSeries_retraction_coordinate_constantCoeff_zero
#check LinearStudy.powerSeriesCentering
#print axioms LinearStudy.powerSeriesCentering
#check LinearStudy.powerSeriesCentering_coordinate_reduction_zero
#print axioms LinearStudy.powerSeriesCentering_coordinate_reduction_zero
#check LinearStudy.powerSeriesCentering_pderiv
#print axioms LinearStudy.powerSeriesCentering_pderiv
#check LinearStudy.powerSeriesCentering_symm_pderiv
#print axioms LinearStudy.powerSeriesCentering_symm_pderiv
#check LinearStudy.powerSeriesCentering_symm_jacobian
#print axioms LinearStudy.powerSeriesCentering_symm_jacobian
#check LinearStudy.powerSeries_zeroConstant_variable_expansion
#print axioms LinearStudy.powerSeries_zeroConstant_variable_expansion
#check LinearStudy.powerSeries_equation_coefficient_matrix
#print axioms LinearStudy.powerSeries_equation_coefficient_matrix
#check LinearStudy.powerSeries_constantCoeff_kernel
#print axioms LinearStudy.powerSeries_constantCoeff_kernel
#check LinearStudy.powerSeries_coefficientDeterminant_annihilator
#print axioms LinearStudy.powerSeries_coefficientDeterminant_annihilator
#check LinearStudy.powerSeries_quotient_coordinateIdeal_isMaximal
#print axioms LinearStudy.powerSeries_quotient_coordinateIdeal_isMaximal
#check LinearStudy.powerSeries_coefficientDeterminant_maximal_annihilator
#print axioms LinearStudy.powerSeries_coefficientDeterminant_maximal_annihilator
#check LinearStudy.totalVariableSplit
#print axioms LinearStudy.totalVariableSplit
#check LinearStudy.totalVariableSplit_normal
#print axioms LinearStudy.totalVariableSplit_normal
#check LinearStudy.totalVariableSplit_parameter
#print axioms LinearStudy.totalVariableSplit_parameter
#check LinearStudy.powerSeriesCoordinateChart
#print axioms LinearStudy.powerSeriesCoordinateChart
#check LinearStudy.powerSeriesCoordinateChart_X
#print axioms LinearStudy.powerSeriesCoordinateChart_X
#check LinearStudy.powerSeriesCoordinateChart_C
#print axioms LinearStudy.powerSeriesCoordinateChart_C
#check LinearStudy.powerSeriesCoordinateChart_pderiv
#print axioms LinearStudy.powerSeriesCoordinateChart_pderiv
#check LinearStudy.nestedPowerSeriesTranslationRingEquiv
#print axioms LinearStudy.nestedPowerSeriesTranslationRingEquiv
#check LinearStudy.nestedPowerSeriesTranslationRingEquiv_C
#print axioms LinearStudy.nestedPowerSeriesTranslationRingEquiv_C
#check LinearStudy.nestedPowerSeriesTranslation
#print axioms LinearStudy.nestedPowerSeriesTranslation
#check LinearStudy.nestedPowerSeriesTranslation_X
#print axioms LinearStudy.nestedPowerSeriesTranslation_X
#check LinearStudy.coordinateChart_nestedPowerSeriesTranslation
#print axioms LinearStudy.coordinateChart_nestedPowerSeriesTranslation
#check LinearStudy.nestedPowerSeriesTranslation_pderiv
#print axioms LinearStudy.nestedPowerSeriesTranslation_pderiv
#check LinearStudy.nestedPowerSeriesTranslation_jacobian
#print axioms LinearStudy.nestedPowerSeriesTranslation_jacobian
#check LinearStudy.continuous_powerSeries_pderiv
#print axioms LinearStudy.continuous_powerSeries_pderiv
#check LinearStudy.powerSeries_pderiv_commutes_of_variables
#print axioms LinearStudy.powerSeries_pderiv_commutes_of_variables
#check LinearStudy.powerSeries_pderiv_rename_off_image
#print axioms LinearStudy.powerSeries_pderiv_rename_off_image
#check LinearStudy.powerSeries_pderiv_rename_equiv
#print axioms LinearStudy.powerSeries_pderiv_rename_equiv
#check LinearStudy.powerSeries_diagonal_difference
#print axioms LinearStudy.powerSeries_diagonal_difference
#check LinearStudy.powerSeries_diagonal_jacobian_matrix
#print axioms LinearStudy.powerSeries_diagonal_jacobian_matrix
#check LinearStudy.powerSeriesMapEquiv
#print axioms LinearStudy.powerSeriesMapEquiv
#check LinearStudy.powerSeriesMapEquiv_X
#print axioms LinearStudy.powerSeriesMapEquiv_X
#check LinearStudy.powerSeriesMapEquiv_C
#print axioms LinearStudy.powerSeriesMapEquiv_C
#check LinearStudy.powerSeriesMapEquiv_univariate_X
#print axioms LinearStudy.powerSeriesMapEquiv_univariate_X
#check LinearStudy.powerSeriesMapEquiv_univariate_C
#print axioms LinearStudy.powerSeriesMapEquiv_univariate_C
#check LinearStudy.nestedPowerSeriesEquiv
#print axioms LinearStudy.nestedPowerSeriesEquiv
#check LinearStudy.finSucc_constantCoeff
#print axioms LinearStudy.finSucc_constantCoeff
#check LinearStudy.nestedPowerSeriesEquiv_constantCoeff
#print axioms LinearStudy.nestedPowerSeriesEquiv_constantCoeff
#check LinearStudy.normalVariableIndex
#print axioms LinearStudy.normalVariableIndex
#check LinearStudy.nestedPowerSeriesEquiv_X
#print axioms LinearStudy.nestedPowerSeriesEquiv_X
#check LinearStudy.finSuccEquiv_rename_succ
#print axioms LinearStudy.finSuccEquiv_rename_succ
#check LinearStudy.nestedPowerSeriesEquiv_C
#print axioms LinearStudy.nestedPowerSeriesEquiv_C
#check LinearStudy.finSuccEquiv_pderiv_zero_coeff
#print axioms LinearStudy.finSuccEquiv_pderiv_zero_coeff
#check LinearStudy.finSuccEquiv_pderiv_succ_coeff
#print axioms LinearStudy.finSuccEquiv_pderiv_succ_coeff
#check LinearStudy.powerSeriesMapEquiv_univariate_coeff
#print axioms LinearStudy.powerSeriesMapEquiv_univariate_coeff
#check LinearStudy.nestedPowerSeriesEquiv_pderiv
#print axioms LinearStudy.nestedPowerSeriesEquiv_pderiv
#check LinearStudy.regular_transport_ringEquiv
#print axioms LinearStudy.regular_transport_ringEquiv
#check LinearStudy.powerSeries_cons_X_regular
#print axioms LinearStudy.powerSeries_cons_X_regular
#check LinearStudy.powerSeries_variables_regular
#print axioms LinearStudy.powerSeries_variables_regular
#check LinearStudy.powerSeries_socle_mul_constant
#print axioms LinearStudy.powerSeries_socle_mul_constant
#check LinearStudy.powerSeries_coefficientDeterminant_socle
#print axioms LinearStudy.powerSeries_coefficientDeterminant_socle
#check LinearStudy.powerSeries_coefficientDeterminant_scalar_socle
#print axioms LinearStudy.powerSeries_coefficientDeterminant_scalar_socle
#check LinearStudy.powerSeries_completeIntersection_perfectPairing
#print axioms LinearStudy.powerSeries_completeIntersection_perfectPairing
#check LinearStudy.parameterSpecialization
#print axioms LinearStudy.parameterSpecialization
#check LinearStudy.parameterSpecialization_surjective
#print axioms LinearStudy.parameterSpecialization_surjective
#check LinearStudy.parameterSpecialization_kernel
#print axioms LinearStudy.parameterSpecialization_kernel
#check LinearStudy.parameterSpecializationQuotientEquiv
#print axioms LinearStudy.parameterSpecializationQuotientEquiv
#check LinearStudy.quotientSpecialization
#print axioms LinearStudy.quotientSpecialization
#check LinearStudy.quotientSpecialization_kernel
#print axioms LinearStudy.quotientSpecialization_kernel
#check LinearStudy.quotientSpecialization_surjective
#print axioms LinearStudy.quotientSpecialization_surjective
#check LinearStudy.quotientSpecializationEquiv
#print axioms LinearStudy.quotientSpecializationEquiv
#check LinearStudy.powerSeriesClosedQuotientEquiv
#print axioms LinearStudy.powerSeriesClosedQuotientEquiv
#check LinearStudy.powerSeriesClosedQuotientEquiv_mk
#print axioms LinearStudy.powerSeriesClosedQuotientEquiv_mk
#check LinearStudy.powerSeries_map_pderiv
#print axioms LinearStudy.powerSeries_map_pderiv
#check LinearStudy.parameterSpecialization_jacobian
#print axioms LinearStudy.parameterSpecialization_jacobian
#check LinearStudy.powerSeriesClosedQuotientEquiv_jacobian
#print axioms LinearStudy.powerSeriesClosedQuotientEquiv_jacobian
#check LinearStudy.translationImages
#print axioms LinearStudy.translationImages
#check LinearStudy.translationImages_hasSubst
#print axioms LinearStudy.translationImages_hasSubst
#check LinearStudy.translation_fixes_parameters
#print axioms LinearStudy.translation_fixes_parameters
#check LinearStudy.translation_inverse
#print axioms LinearStudy.translation_inverse
#check LinearStudy.powerSeriesTranslationEquiv
#print axioms LinearStudy.powerSeriesTranslationEquiv
#check LinearStudy.powerSeriesTranslationEquiv_parameter
#print axioms LinearStudy.powerSeriesTranslationEquiv_parameter
#check LinearStudy.powerSeriesTranslationEquiv_normal
#print axioms LinearStudy.powerSeriesTranslationEquiv_normal
#check LinearStudy.powerSeriesTranslationEquiv_pderiv_normal
#print axioms LinearStudy.powerSeriesTranslationEquiv_pderiv_normal
#check LinearStudy.powerSeriesTranslationEquiv_jacobian
#print axioms LinearStudy.powerSeriesTranslationEquiv_jacobian
#check LinearStudy.annihilates_iff_mem_annihilator
#print axioms LinearStudy.annihilates_iff_mem_annihilator
#check LinearStudy.nilradical_annihilator_scalar_generation
#print axioms LinearStudy.nilradical_annihilator_scalar_generation
#check LinearStudy.unit_coefficient_generates_annihilator
#print axioms LinearStudy.unit_coefficient_generates_annihilator
#check LinearStudy.primitive_annihilator_coefficient_isUnit
#print axioms LinearStudy.primitive_annihilator_coefficient_isUnit
#check LinearStudy.primitive_annihilator_generates
#print axioms LinearStudy.primitive_annihilator_generates
#check LinearStudy.homogeneous_eval_smul
#print axioms LinearStudy.homogeneous_eval_smul
#check LinearStudy.HomogeneousEndomorphism.evalVector
#print axioms LinearStudy.HomogeneousEndomorphism.evalVector
#check LinearStudy.HomogeneousEndomorphism.evalVector_smul
#print axioms LinearStudy.HomogeneousEndomorphism.evalVector_smul
#check LinearStudy.HomogeneousEndomorphism.onPoints
#print axioms LinearStudy.HomogeneousEndomorphism.onPoints
#check LinearStudy.HomogeneousEndomorphism.onPoints_mk
#print axioms LinearStudy.HomogeneousEndomorphism.onPoints_mk
#check LinearStudy.HomogeneousEndomorphism.comp
#print axioms LinearStudy.HomogeneousEndomorphism.comp
#check LinearStudy.HomogeneousEndomorphism.comp_evalVector
#print axioms LinearStudy.HomogeneousEndomorphism.comp_evalVector
#check LinearStudy.HomogeneousEndomorphism.comp_onPoints
#print axioms LinearStudy.HomogeneousEndomorphism.comp_onPoints
#check LinearStudy.HomogeneousEndomorphism.identity
#print axioms LinearStudy.HomogeneousEndomorphism.identity
#check LinearStudy.HomogeneousEndomorphism.iterate
#print axioms LinearStudy.HomogeneousEndomorphism.iterate
#check LinearStudy.HomogeneousEndomorphism.iterate_degree
#print axioms LinearStudy.HomogeneousEndomorphism.iterate_degree
#check LinearStudy.HomogeneousEndomorphism.identity_onPoints
#print axioms LinearStudy.HomogeneousEndomorphism.identity_onPoints
#check LinearStudy.HomogeneousEndomorphism.iterate_onPoints
#print axioms LinearStudy.HomogeneousEndomorphism.iterate_onPoints
#check LinearStudy.HomogeneousEndomorphism.iterate_total_invariance
#print axioms LinearStudy.HomogeneousEndomorphism.iterate_total_invariance
#check LinearStudy.homogeneous_ideal_vanish_smul
#print axioms LinearStudy.homogeneous_ideal_vanish_smul
#check LinearStudy.homogeneous_ideal_vanish_unit_smul_iff
#print axioms LinearStudy.homogeneous_ideal_vanish_unit_smul_iff
#check LinearStudy.IntegralProjectiveEquations.zeroSet
#print axioms LinearStudy.IntegralProjectiveEquations.zeroSet
#check LinearStudy.IntegralProjectiveEquations.mem_zeroSet_mk
#print axioms LinearStudy.IntegralProjectiveEquations.mem_zeroSet_mk
#check LinearStudy.IntegralProjectiveEquations.zeroSet_nonempty
#print axioms LinearStudy.IntegralProjectiveEquations.zeroSet_nonempty
#check LinearStudy.LinearityTheoremGoal
#print axioms LinearStudy.LinearityTheoremGoal
#check LinearStudy.Annihilates
#print axioms LinearStudy.Annihilates
#check LinearStudy.multiplication_factors_through_reduction
#print axioms LinearStudy.multiplication_factors_through_reduction
#check LinearStudy.scalar_multiple_annihilates
#print axioms LinearStudy.scalar_multiple_annihilates
#check LinearStudy.annihilator_action_eq
#print axioms LinearStudy.annihilator_action_eq
#check LinearStudy.quotient_image_nonzero_iff
#print axioms LinearStudy.quotient_image_nonzero_iff
#check LinearStudy.ofList_smul_top
#print axioms LinearStudy.ofList_smul_top
#check LinearStudy.weaklyRegular_quotient_iff
#print axioms LinearStudy.weaklyRegular_quotient_iff
#check LinearStudy.weaklyRegular_exchange
#print axioms LinearStudy.weaklyRegular_exchange
#check LinearStudy.weaklyRegular_transport_ringEquiv
#print axioms LinearStudy.weaklyRegular_transport_ringEquiv
#check LinearStudy.powerSeries_specialized_equations_weaklyRegular
#print axioms LinearStudy.powerSeries_specialized_equations_weaklyRegular
#check LinearStudy.powerSeries_specialized_equations_zeroConstant
#print axioms LinearStudy.powerSeries_specialized_equations_zeroConstant
#check LinearStudy.powerSeries_specialized_equations_regular
#print axioms LinearStudy.powerSeries_specialized_equations_regular
#check LinearStudy.finiteFlat_jacobian_annihilator
#print axioms LinearStudy.finiteFlat_jacobian_annihilator
#check LinearStudy.lemma31_annihilator_conclusion
#print axioms LinearStudy.lemma31_annihilator_conclusion
#check LinearStudy.relativePowerSeriesQuotient_diagonal_jacobian
#print axioms LinearStudy.relativePowerSeriesQuotient_diagonal_jacobian
#check LinearStudy.relativePowerSeriesQuotient_jacobian_trace_multiple
#print axioms LinearStudy.relativePowerSeriesQuotient_jacobian_trace_multiple
#check LinearStudy.relativePowerSeriesQuotient_jacobian_annihilates_nilradical
#print axioms LinearStudy.relativePowerSeriesQuotient_jacobian_annihilates_nilradical
#check LinearStudy.exists_residue_functional_lift
#print axioms LinearStudy.exists_residue_functional_lift
#check LinearStudy.residue_multiplicationGram
#print axioms LinearStudy.residue_multiplicationGram
#check LinearStudy.exists_relative_perfectPairing_of_residue_socle
#print axioms LinearStudy.exists_relative_perfectPairing_of_residue_socle
#check LinearStudy.exists_finiteFlat_pairing_of_residue_socle
#print axioms LinearStudy.exists_finiteFlat_pairing_of_residue_socle
#check LinearStudy.primitive_of_residue_tensor_nonzero
#print axioms LinearStudy.primitive_of_residue_tensor_nonzero
#check LinearStudy.finiteFlat_annihilator_from_closed_socle
#print axioms LinearStudy.finiteFlat_annihilator_from_closed_socle
#check LinearStudy.nonzero_ideal_meets_nilpotent_annihilator
#print axioms LinearStudy.nonzero_ideal_meets_nilpotent_annihilator
#check LinearStudy.nonzero_ideal_meets_socle
#print axioms LinearStudy.nonzero_ideal_meets_socle
#check LinearStudy.socle_functional_detects_nonzero
#print axioms LinearStudy.socle_functional_detects_nonzero
#check LinearStudy.socle_multiplicationToDual_injective
#print axioms LinearStudy.socle_multiplicationToDual_injective
#check LinearStudy.perfectPairingOfSocle
#print axioms LinearStudy.perfectPairingOfSocle
#check LinearStudy.exists_perfectPairing_of_scalar_socle
#print axioms LinearStudy.exists_perfectPairing_of_scalar_socle
#check LinearStudy.ringEquiv_socle_forward
#print axioms LinearStudy.ringEquiv_socle_forward
#check LinearStudy.ringEquiv_socle_iff
#print axioms LinearStudy.ringEquiv_socle_iff
#check LinearStudy.scalar_socle_transport
#print axioms LinearStudy.scalar_socle_transport
#check LinearStudy.equationIdeal
#print axioms LinearStudy.equationIdeal
#check LinearStudy.relativeJacobian
#print axioms LinearStudy.relativeJacobian
#check LinearStudy.Lemma31Goal
#print axioms LinearStudy.Lemma31Goal
#check LinearStudy.polynomialDoubleTensor
#print axioms LinearStudy.polynomialDoubleTensor
#check LinearStudy.polynomialDoubleTensor_left
#print axioms LinearStudy.polynomialDoubleTensor_left
#check LinearStudy.polynomialDoubleTensor_right
#print axioms LinearStudy.polynomialDoubleTensor_right
#check LinearStudy.polynomialDoubleTensor_multiplication
#print axioms LinearStudy.polynomialDoubleTensor_multiplication
#check LinearStudy.polynomialDoubleTensor_rightReduction
#print axioms LinearStudy.polynomialDoubleTensor_rightReduction
#check LinearStudy.powerSeries_maximalIdeal_eq_coordinates
#print axioms LinearStudy.powerSeries_maximalIdeal_eq_coordinates
#check LinearStudy.parameterIdeal_map_eq_residueIdeal
#print axioms LinearStudy.parameterIdeal_map_eq_residueIdeal
#check LinearStudy.powerSeriesResidueTensorEquiv
#print axioms LinearStudy.powerSeriesResidueTensorEquiv
#check LinearStudy.powerSeriesResidueTensorEquiv_one_tmul
#print axioms LinearStudy.powerSeriesResidueTensorEquiv_one_tmul
#check LinearStudy.powerSeriesResidueFieldEquiv
#print axioms LinearStudy.powerSeriesResidueFieldEquiv
#check LinearStudy.powerSeriesResidueFieldEquiv_mk
#print axioms LinearStudy.powerSeriesResidueFieldEquiv_mk
#check LinearStudy.powerSeriesResidueTensorEquiv_algebraMap
#print axioms LinearStudy.powerSeriesResidueTensorEquiv_algebraMap
#check LinearStudy.powerSeriesResidueTensorEquiv_smul
#print axioms LinearStudy.powerSeriesResidueTensorEquiv_smul
#check LinearStudy.finiteFlat_powerSeries_relative_perfectPairing
#print axioms LinearStudy.finiteFlat_powerSeries_relative_perfectPairing
#check LinearStudy.thickeningIdeal
#print axioms LinearStudy.thickeningIdeal
#check LinearStudy.thickeningMk
#print axioms LinearStudy.thickeningMk
#check LinearStudy.thickeningX
#print axioms LinearStudy.thickeningX
#check LinearStudy.thickeningTop
#print axioms LinearStudy.thickeningTop
#check LinearStudy.thickeningMk_surjective
#print axioms LinearStudy.thickeningMk_surjective
#check LinearStudy.thickeningMk_eq_zero_iff
#print axioms LinearStudy.thickeningMk_eq_zero_iff
#check LinearStudy.thickeningX_pow
#print axioms LinearStudy.thickeningX_pow
#check LinearStudy.thickeningX_nilpotent
#print axioms LinearStudy.thickeningX_nilpotent
#check LinearStudy.thickening_X_annihilation_iff
#print axioms LinearStudy.thickening_X_annihilation_iff
#check LinearStudy.thickening_X_annihilator
#print axioms LinearStudy.thickening_X_annihilator
#check LinearStudy.thickeningTop_nonzero
#print axioms LinearStudy.thickeningTop_nonzero
#check LinearStudy.thickeningReduction
#print axioms LinearStudy.thickeningReduction
#check LinearStudy.thickeningReduction_mk
#print axioms LinearStudy.thickeningReduction_mk
#check LinearStudy.thickeningReduction_surjective
#print axioms LinearStudy.thickeningReduction_surjective
#check LinearStudy.thickeningReduction_kernel
#print axioms LinearStudy.thickeningReduction_kernel
#check LinearStudy.thickening_nilradical
#print axioms LinearStudy.thickening_nilradical
#check LinearStudy.thickening_nilradical_annihilator
#print axioms LinearStudy.thickening_nilradical_annihilator
#check LinearStudy.thickeningJacobian
#print axioms LinearStudy.thickeningJacobian
#check LinearStudy.thickeningJacobian_eq
#print axioms LinearStudy.thickeningJacobian_eq
#check LinearStudy.thickeningJacobian_unit_twist
#print axioms LinearStudy.thickeningJacobian_unit_twist
#check LinearStudy.thickeningJacobian_span
#print axioms LinearStudy.thickeningJacobian_span
#check LinearStudy.thickeningJacobian_annihilator
#print axioms LinearStudy.thickeningJacobian_annihilator
#check LinearStudy.thickeningJacobian_nonzero
#print axioms LinearStudy.thickeningJacobian_nonzero
#check LinearStudy.thickeningTop_mul_mk
#print axioms LinearStudy.thickeningTop_mul_mk
#check LinearStudy.thickening_nilradical_scalar_generation
#print axioms LinearStudy.thickening_nilradical_scalar_generation
#check LinearStudy.thickeningTop_scalar_eq_zero_iff
#print axioms LinearStudy.thickeningTop_scalar_eq_zero_iff
#check LinearStudy.thickeningTop_scalars_injective
#print axioms LinearStudy.thickeningTop_scalars_injective
#check LinearStudy.thickening_nilradical_maximal
#print axioms LinearStudy.thickening_nilradical_maximal
#check LinearStudy.thickening_closedFiber_artinian
#print axioms LinearStudy.thickening_closedFiber_artinian
#check LinearStudy.thickening_closedFiber_jacobian
#print axioms LinearStudy.thickening_closedFiber_jacobian
#check LinearStudy.traceElement
#print axioms LinearStudy.traceElement
#check LinearStudy.traceElement_pairing
#print axioms LinearStudy.traceElement_pairing
#check LinearStudy.trace_eq_rank_smul_reduction
#print axioms LinearStudy.trace_eq_rank_smul_reduction
#check LinearStudy.traceElement_eq_rank_dualGenerator
#print axioms LinearStudy.traceElement_eq_rank_dualGenerator
#check LinearStudy.traceElement_annihilates_kernel
#print axioms LinearStudy.traceElement_annihilates_kernel
#check LinearStudy.traceElement_functional
#print axioms LinearStudy.traceElement_functional
#check LinearStudy.traceElement_nonzero_over_field
#print axioms LinearStudy.traceElement_nonzero_over_field
#check LinearStudy.traceElement_generates_annihilator
#print axioms LinearStudy.traceElement_generates_annihilator
#check LinearStudy.eq_traceElement_of_residue_trace
#print axioms LinearStudy.eq_traceElement_of_residue_trace
#check LinearStudy.polynomialDoubleDiagonal
#print axioms LinearStudy.polynomialDoubleDiagonal
#check LinearStudy.polynomialDoubleRightZero
#print axioms LinearStudy.polynomialDoubleRightZero
#check LinearStudy.polynomialDoubleDiagonal_left
#print axioms LinearStudy.polynomialDoubleDiagonal_left
#check LinearStudy.polynomialDoubleRightZero_left
#print axioms LinearStudy.polynomialDoubleRightZero_left
#check LinearStudy.polynomialDoubleRightZero_right
#print axioms LinearStudy.polynomialDoubleRightZero_right
#check LinearStudy.polynomial_universal_difference_matrix
#print axioms LinearStudy.polynomial_universal_difference_matrix
#check ExteriorAlgebra.baseChangeι
#print axioms ExteriorAlgebra.baseChangeι
#check ExteriorAlgebra.baseChangeι_mul_add_swap
#print axioms ExteriorAlgebra.baseChangeι_mul_add_swap
#check ExteriorAlgebra.baseChangeι_sq_zero
#print axioms ExteriorAlgebra.baseChangeι_sq_zero
#check ExteriorAlgebra.baseChangeExteriorAlgebraToTensor
#print axioms ExteriorAlgebra.baseChangeExteriorAlgebraToTensor
#check exteriorPower.baseChangeGenerator_map_update_add
#print axioms exteriorPower.baseChangeGenerator_map_update_add
#check exteriorPower.baseChangeGenerator_map_update_smul
#print axioms exteriorPower.baseChangeGenerator_map_update_smul
#check exteriorPower.baseChangeGenerator
#print axioms exteriorPower.baseChangeGenerator
#check exteriorPower.baseChangeIsoForwardAux
#print axioms exteriorPower.baseChangeIsoForwardAux
#check exteriorPower.baseChangeIsoForward
#print axioms exteriorPower.baseChangeIsoForward
#check exteriorPower.baseChangeIsoForward_apply_one_tmul_ιMulti
#print axioms exteriorPower.baseChangeIsoForward_apply_one_tmul_ιMulti
#check exteriorPower.degreeProjection
#print axioms exteriorPower.degreeProjection
#check exteriorPower.degreeProjection_apply_ιMulti
#print axioms exteriorPower.degreeProjection_apply_ιMulti
#check exteriorPower.baseChangeInverseAlternating
#print axioms exteriorPower.baseChangeInverseAlternating
#check exteriorPower.baseChangeInverseAlternating_apply_tmul
#print axioms exteriorPower.baseChangeInverseAlternating_apply_tmul
#check exteriorPower.baseChangeIsoInverse
#print axioms exteriorPower.baseChangeIsoInverse
#check exteriorPower.baseChangeIsoInverse_apply_tmul
#print axioms exteriorPower.baseChangeIsoInverse_apply_tmul
#check exteriorPower.baseChange_left_inverse
#print axioms exteriorPower.baseChange_left_inverse
#check exteriorPower.baseChangeIsoForward_surjective
#print axioms exteriorPower.baseChangeIsoForward_surjective
#check exteriorPower.baseChange_right_inverse
#print axioms exteriorPower.baseChange_right_inverse
#check exteriorPower.baseChangeIso
#print axioms exteriorPower.baseChangeIso
#check exteriorPower.baseChangeIso_apply_tmul
#print axioms exteriorPower.baseChangeIso_apply_tmul
#check exteriorPower.baseChangeIso_symm_apply_tmul
#print axioms exteriorPower.baseChangeIso_symm_apply_tmul
#check ExteriorAlgebra.algebraMapInv_ι
#print axioms ExteriorAlgebra.algebraMapInv_ι
#check ExteriorAlgebra.algebraMapInv_algebraMap
#print axioms ExteriorAlgebra.algebraMapInv_algebraMap
#check ExteriorAlgebra.ιInv_ι
#print axioms ExteriorAlgebra.ιInv_ι
#check ExteriorAlgebra.ιInv_one
#print axioms ExteriorAlgebra.ιInv_one
#check ExteriorAlgebra.ιInv_algebraMap
#print axioms ExteriorAlgebra.ιInv_algebraMap
#check ExteriorAlgebra.ι_mul_ι_ring
#print axioms ExteriorAlgebra.ι_mul_ι_ring
#check ExteriorAlgebra.eq_algebraMap_add_ι
#print axioms ExteriorAlgebra.eq_algebraMap_add_ι
#check ExteriorAlgebra.prodRingEquiv
#print axioms ExteriorAlgebra.prodRingEquiv
#check ExteriorAlgebra.prodRingEquiv_apply
#print axioms ExteriorAlgebra.prodRingEquiv_apply
#check ExteriorAlgebra.prodEquivProd
#print axioms ExteriorAlgebra.prodEquivProd
#check ExteriorAlgebra.prodEquivProd_apply
#print axioms ExteriorAlgebra.prodEquivProd_apply
#check ExteriorAlgebra.prodEquivProd_comp_inl
#print axioms ExteriorAlgebra.prodEquivProd_comp_inl
#check ExteriorAlgebra.prodEquivProd_apply_snd
#print axioms ExteriorAlgebra.prodEquivProd_apply_snd
#check ExteriorAlgebra.map_mem_exteriorPower
#print axioms ExteriorAlgebra.map_mem_exteriorPower
#check ExteriorAlgebra.ι_mul_mem_exteriorPower_anticomm
#print axioms ExteriorAlgebra.ι_mul_mem_exteriorPower_anticomm
#check ExteriorAlgebra.exists_decomp
#print axioms ExteriorAlgebra.exists_decomp
#check ExteriorAlgebra.prodEquivProd_mem_exteriorPower
#print axioms ExteriorAlgebra.prodEquivProd_mem_exteriorPower
#check exteriorPowerProdEquivProd
#print axioms exteriorPowerProdEquivProd
#check exteriorPowerProdEquivProd_apply_coe
#print axioms exteriorPowerProdEquivProd_apply_coe
#check exteriorPowerProdEquivProd_apply_inl_ιMulti
#print axioms exteriorPowerProdEquivProd_apply_inl_ιMulti
#check exteriorPowerProdEquivProd_comp_inl
#print axioms exteriorPowerProdEquivProd_comp_inl
#check exteriorPowerProdEquivProd_apply_inr_ιMulti
#print axioms exteriorPowerProdEquivProd_apply_inr_ιMulti
#check koszulComplex.dAlternating
#print axioms koszulComplex.dAlternating
#check koszulComplex.dAlternating_apply
#print axioms koszulComplex.dAlternating_apply
#check koszulComplex.d
#print axioms koszulComplex.d
#check koszulComplex.d_comp_eq_zero
#print axioms koszulComplex.d_comp_eq_zero
#check koszulComplex
#print axioms koszulComplex
#check koszulComplex.X_eq_exteriorPower
#print axioms koszulComplex.X_eq_exteriorPower
#check koszulComplex.d_eq_d
#print axioms koszulComplex.d_eq_d
#check koszulComplex.ofList
#print axioms koszulComplex.ofList
#check koszulComplex.map_dAlternating_apply
#print axioms koszulComplex.map_dAlternating_apply
#check koszulComplex.map_d_comm
#print axioms koszulComplex.map_d_comm
#check koszulComplex.map
#print axioms koszulComplex.map
#check koszulComplex.map_comp
#print axioms koszulComplex.map_comp
#check koszulComplex.isoOfEquiv
#print axioms koszulComplex.isoOfEquiv
#check koszulComplex.isZero_X_of_card_generators_lt
#print axioms koszulComplex.isZero_X_of_card_generators_lt
#check koszulComplex.isZero_X_ofList_of_length_lt
#print axioms koszulComplex.isZero_X_ofList_of_length_lt
#check koszulComplex.exteriorPower.baseChangeIso_comm_aux
#print axioms koszulComplex.exteriorPower.baseChangeIso_comm_aux
#check koszulComplex.baseChangeIso
#print axioms koszulComplex.baseChangeIso
#check koszulComplex.ofListBaseChangeIso
#print axioms koszulComplex.ofListBaseChangeIso
#check koszulComplex.appendMap
#print axioms koszulComplex.appendMap
#check koszulComplex.XZeroEquiv
#print axioms koszulComplex.XZeroEquiv
#check koszulComplex.appendMap_d_eq_zero
#print axioms koszulComplex.appendMap_d_eq_zero
#check koszulComplex.exteriorPowerProdEquivProd_apply_inr_eq_snoc
#print axioms koszulComplex.exteriorPowerProdEquivProd_apply_inr_eq_snoc
#check koszulComplex.appendMap_d_eq_pos
#print axioms koszulComplex.appendMap_d_eq_pos
#check koszulComplex.fromOfListHomZero
#print axioms koszulComplex.fromOfListHomZero
#check koszulComplex.fromOfListHomSucc
#print axioms koszulComplex.fromOfListHomSucc
#check koszulComplex.from_ofList_hom_comm_zero
#print axioms koszulComplex.from_ofList_hom_comm_zero
#check koszulComplex.from_ofList_hom_comm_pos
#print axioms koszulComplex.from_ofList_hom_comm_pos
#check koszulComplex.toAppendMap
#print axioms koszulComplex.toAppendMap
#check koszulComplex.upOne
#print axioms koszulComplex.upOne
#check koszulComplex.upOneHomologyIso
#print axioms koszulComplex.upOneHomologyIso
#check koszulComplex.toUpOneHom
#print axioms koszulComplex.toUpOneHom
#check koszulComplex.to_self_hom_comm
#print axioms koszulComplex.to_self_hom_comm
#check koszulComplex.toUpOne
#print axioms koszulComplex.toUpOne
#check koszulComplex.toAppendMap_comp_toUpOne_eq_zero
#print axioms koszulComplex.toAppendMap_comp_toUpOne_eq_zero
#check koszulComplex.shortComplexProd
#print axioms koszulComplex.shortComplexProd
#check koszulComplex.shortComplexProd_shortExact
#print axioms koszulComplex.shortComplexProd_shortExact
#check koszulComplex.shortComplexProd_δ_eq
#print axioms koszulComplex.shortComplexProd_δ_eq
#check koszulComplex.zeroHomologyLinearEquivAux
#print axioms koszulComplex.zeroHomologyLinearEquivAux
#check koszulComplex.equiv_comp_koszulComplex.d_zero_eq
#print axioms koszulComplex.equiv_comp_koszulComplex.d_zero_eq
#check koszulComplex.d_zero_range_map
#print axioms koszulComplex.d_zero_range_map
#check koszulComplex.zeroHomologyOfListLinearEquiv
#print axioms koszulComplex.zeroHomologyOfListLinearEquiv
#check koszulComplex.snocLinearEquiv
#print axioms koszulComplex.snocLinearEquiv
#check koszulComplex.ofListIsoOfEqAux
#print axioms koszulComplex.ofListIsoOfEqAux
#check koszulComplex.ofListIsoOfEqAux_comp
#print axioms koszulComplex.ofListIsoOfEqAux_comp
#check koszulComplex.ofListIsoOfEq
#print axioms koszulComplex.ofListIsoOfEq
#check koszulComplex.exactAt_of_isRegular
#print axioms koszulComplex.exactAt_of_isRegular
#print LinearStudy.LinearityTheoremGoal
#print LinearStudy.HomogeneousEndomorphism
#print LinearStudy.IntegralProjectiveEquations
