module

public import Linear

#check LinearStudy.doublePoint_decomposition
#print axioms LinearStudy.doublePoint_decomposition
#check LinearStudy.doublePoint_nilradical
#print axioms LinearStudy.doublePoint_nilradical
#check LinearStudy.doublePoint_epsilon_is_dualGenerator
#print axioms LinearStudy.doublePoint_epsilon_is_dualGenerator
#check LinearStudy.doublePoint_annihilator_generated
#print axioms LinearStudy.doublePoint_annihilator_generated
#check LinearStudy.doublePoint_nilradical_annihilator
#print axioms LinearStudy.doublePoint_nilradical_annihilator
#check LinearStudy.doublePoint_quotient_generator_nonzero
#print axioms LinearStudy.doublePoint_quotient_generator_nonzero
#check LinearStudy.doublePoint_residue_to_evaluation
#print axioms LinearStudy.doublePoint_residue_to_evaluation
#check LinearStudy.dualGenerator_pairing
#print axioms LinearStudy.dualGenerator_pairing
#check LinearStudy.dualGenerator_functional
#print axioms LinearStudy.dualGenerator_functional
#check LinearStudy.dualGenerator_annihilates
#print axioms LinearStudy.dualGenerator_annihilates
#check LinearStudy.annihilator_eq_scalar_generator
#print axioms LinearStudy.annihilator_eq_scalar_generator
#check LinearStudy.annihilator_iff_scalar_multiple
#print axioms LinearStudy.annihilator_iff_scalar_multiple
#check LinearStudy.dualGenerator_scalar_retraction
#print axioms LinearStudy.dualGenerator_scalar_retraction
#check LinearStudy.dualGenerator_quotient_nonzero
#print axioms LinearStudy.dualGenerator_quotient_nonzero
#check LinearStudy.annihilates_iff_mem_annihilator
#print axioms LinearStudy.annihilates_iff_mem_annihilator
#check LinearStudy.nilradical_annihilator_scalar_generation
#print axioms LinearStudy.nilradical_annihilator_scalar_generation
#check LinearStudy.unit_coefficient_generates_annihilator
#print axioms LinearStudy.unit_coefficient_generates_annihilator
#check LinearStudy.primitive_annihilator_coefficient_isUnit
#print axioms LinearStudy.primitive_annihilator_coefficient_isUnit
#check LinearStudy.primitive_annihilator_generates
#print axioms LinearStudy.primitive_annihilator_generates
#check LinearStudy.multiplication_factors_through_reduction
#print axioms LinearStudy.multiplication_factors_through_reduction
#check LinearStudy.scalar_multiple_annihilates
#print axioms LinearStudy.scalar_multiple_annihilates
#check LinearStudy.annihilator_action_eq
#print axioms LinearStudy.annihilator_action_eq
#check LinearStudy.quotient_image_nonzero_iff
#print axioms LinearStudy.quotient_image_nonzero_iff

#check LinearStudy.Lemma31Goal
