module

public import Linear.Reduction
public import Linear.Duality
public import Linear.Target
public import Linear.Primitive
public import Linear.DoublePoint
public import Linear.FirstJet
public import Linear.GenericFiber
public import Linear.PairingMatrix
public import Linear.Degree
public import Linear.Iteration
public import Linear.Projective
public import Linear.Evaluation
public import Linear.LinearSubspace
public import Linear.OneVariable
public import Linear.SoclePairing
public import Linear.ResiduePairing
public import Linear.TraceElement
public import Linear.ParameterQuotient
public import Linear.DeterminantAnnihilator
public import Linear.PowerSeriesCoefficients
public import Linear.PowerSeriesRegular
public import Linear.KoszulResolution
public import Linear.KoszulTop
public import Linear.KoszulComparison
public import Linear.KoszulHomotopyTop
public import Linear.KoszulSocleMap
public import Linear.KoszulFunctionResolution
public import Linear.KoszulSocleDeterminant
public import Linear.PowerSeriesSocle
public import Linear.PowerSeriesAugmentation
public import Linear.PowerSeriesSpecialization
public import Linear.RegularSpecialization
public import Linear.FiniteSpecialization
public import Linear.SocleTransport
public import Linear.TensorSpecialization
public import Linear.NilpotentEvaluation
public import Linear.NilpotentEvaluationUnique
public import Linear.PolynomialDiagonal
public import Linear.PowerSeriesDiagonal
public import Linear.ArtinianDiagonal
public import Linear.DiagonalTrace
public import Linear.JacobianTrace

public import Linear.PolynomialApproximation
public import Linear.UniversalDifference
public import Linear.PolynomialSocle
public import Linear.DiagonalNonzero

public import Linear.TensorDifference

public import Linear.JacobianNonzero

public import Linear.JacobianSpecialization
public import Linear.RelativeJacobianTrace
public import Linear.CenteredRelativeJacobian
public import Linear.ParameterPairingChange

public import Linear.PowerSeriesFlatten
public import Linear.PowerSeriesTranslation
public import Linear.RelativeJacobian
public import Linear.ParameterLinearPart
public import Linear.ParameterSubstitution
public import Linear.NilpotentRegular
public import Linear.RegularGeneratorsFree
public import Linear.LiftedParametersRegular
public import Linear.LiftedParameterCoordinates
public import Linear.LiftedParameterMaps
public import Linear.LiftedParameterPresentation
public import Linear.ArbitraryParameterJacobian
public import Linear.ArbitraryParameterSocle
public import Linear.LocalResidueEvaluation
public import Linear.LocalFiberJacobian
public import Linear.ArtinianGlobalPairing
public import Linear.PolynomialFiberDiagonal
public import Linear.PolynomialRegular
public import Linear.DiagonalNormalization
public import Linear.PolynomialGlobalResidue
public import Linear.GlobalDiagonalNormalization
public import Linear.PolynomialDoubleFiber
public import Linear.PolynomialDifferenceDegree
public import Linear.PolynomialOriginFinite
public import Linear.HomogeneousQuotient
public import Linear.AffineFiltered
public import Linear.FirstSyzygy
public import Linear.FilteredIdeal
public import Linear.AffineFunctional
public import Linear.PolynomialContraction
public import Linear.TopDeterminant
public import Linear.ContractionPairing
public import Linear.AffineDiagonal
public import Linear.PointDecomposition
public import Linear.LocalizedAnnihilator
public import Linear.AffinePointRelation
public import Linear.ProjectiveChart
public import Linear.ArtinianCompletion
public import Linear.AffineOriginRelation
public import Linear.LocalFiber
public import Linear.PolynomialFormalCompletion
public import Linear.PolynomialPointCompletion
public import Linear.SmoothFormalQuotient
public import Linear.PolynomialFormalFiber
public import Linear.FormalFirstOrder
public import Linear.PowerSeriesThickeningFinite
public import Linear.PowerSeriesThickeningReduction
public import Linear.PowerSeriesCohenMacaulay
public import Linear.PowerSeriesThickeningFlat
public import Linear.ThickeningFromRadical
public import Linear.ProjectiveIdealInvariance
public import Linear.FormalInvariantThickening
public import Linear.PolynomialFormalDerivative
public import Linear.PolynomialSmoothCoordinates

public import Linear.LocalPullbackGenerators

public import Linear.ProjectiveCoordinateRelabel

public import Linear.SmoothInvariantLocal

public import Linear.ProjectiveSmoothLocal

public import Linear.UnramifiedParameters

public import Linear.PolynomialSmoothReduction

public import Linear.UnramifiedSmoothParameters

public import Linear.PolynomialDerivationChain

public import Linear.SmoothNormalJacobian

public import Linear.SmoothPolynomialFiber

public import Linear.FormalParameterFiber

public import Linear.LocalQuotientPullback

public import Linear.ActualUnramifiedPullback

public import Linear.SmoothPolynomialSocle

public import Linear.PolynomialFiberJacobian

public import Linear.FormalPullbackFiber

public import Linear.SmoothProjectiveFormalSocle

public import Linear.ConormalGenerators

public import Linear.SmoothConormal

public import Linear.SmoothPolynomialGenerators

public import Linear.LocalizedDifferentialBasis

public import Linear.RectangularMinor

public import Linear.SplitJacobianRank

public import Linear.PolynomialPointEvaluation

public import Linear.SmoothJacobianMinor

public import Linear.SmoothCoordinateSplit

public import Linear.SmoothReindexedFormalIdeal

public import Linear.SmoothCotangentDimension

public import Linear.CommonNormalCoordinates

public import Linear.PolynomialLinearChange

public import Linear.CommonPolynomialCoordinates

public import Linear.SmoothFixedConormalRank

public import Linear.SmoothCommonCoordinates

public import Linear.LocalGeneratorsEquiv

public import Linear.SmoothCommonFormalCoordinates

public import Linear.LocalizedDifferentialRank

public import Linear.SmoothLocusCoordinates

public import Linear.FirstJetNormalForm

public import Linear.TargetLinearNormal

public import Linear.PolynomialLinearGrading

public import Linear.OriginalIdealFirstOrder

public import Linear.SmoothTargetFirstOrder

public import Linear.FirstOrderLocalParameters

public import Linear.PolynomialFirstJet

public import Linear.PolynomialLocalParameters

public import Linear.PolynomialNormalEquations

public import Linear.SmoothCoordinateRank

public import Linear.OriginalPolynomialNormal

public import Linear.ConstructedTargetParameters

public import Linear.LocalQuotientMaximalIdeal

public import Linear.ActualTargetParameters

public import Linear.PointLocalCoordinateEquiv

public import Linear.SmoothTargetParameters

public import Linear.SmoothUnramifiedParameters

public import Linear.ProjectiveRationalChart

public import Linear.GeneralLocalQuotientPullback

public import Linear.RationalChartFormalComparison

public import Linear.HomogeneousRationalPullback

public import Linear.HomogeneousRationalIdeal

public import Linear.ProjectiveRationalInvariance

public import Linear.LocalizedPointQuotientEquiv

public import Linear.ProjectiveRationalFormalIdeal

public import Linear.AffineChartComparison

public import Linear.LocalizedSmoothPointReduction

public import Linear.GeneralUnramifiedPullback

public import Linear.RationalSmoothReduction

public import Linear.RationalUnramifiedParameters

public import Linear.RationalSmoothTargetParameters

public import Linear.RationalSmoothRadical

public import Linear.RationalSmoothJacobianSocle

public import Linear.ProjectiveAffinePrime

public import Linear.ProjectiveAffinePoint

public import Linear.ProjectiveAffineVariety

public import Linear.ProjectiveAffinePointData

public import Linear.LocalPullbackEssentialFiniteType

public import Linear.RationalLocalEssentialFiniteType

public import Linear.RationalFiniteTypeSocle

public import Linear.GenericSmoothOpen

public import Linear.FiniteTypeRationalPoint

public import Linear.SmoothRationalPoint

public import Linear.ProjectiveAffineSmoothLocus

public import Linear.ProjectiveAffineSmoothPoint

public import Linear.SmoothPointPrincipalOpen

public import Linear.ProjectiveSmoothOpenPoint

public import Linear.ProjectiveCommonChart

public import Linear.ProjectiveConeSurjectivity

public import Linear.ProjectiveCoordinateDomainMap

public import Linear.FiniteTypeFieldEndomorphism

public import Linear.FieldEndomorphismMap

public import Linear.ProjectiveCoordinateFractionMap

public import Linear.ProjectiveCoordinateGenericMap

public import Linear.ProjectiveGenericUnramified

public import Linear.GenericUnramifiedOpen

public import Linear.ProjectiveConeUnramifiedOpen

public import Linear.CoordinateRatioField

public import Linear.HomogeneousRatioFieldMap

public import Linear.ProjectiveCoordinateRatioMap

public import Linear.ProjectiveRatioChartKernel

public import Linear.ProjectiveChartFractionField

public import Linear.ProjectiveChartGenericMap

public import Linear.ProjectiveChartMapCoordinates

public import Linear.AwayFractionEmbedding

public import Linear.ProjectiveChartOpenMap

public import Linear.AwayFractionUnramified

public import Linear.ProjectiveChartUnramifiedOpen

public import Linear.GenericSmoothUnramifiedOpen

public import Linear.ProjectiveChartSmoothUnramified

public import Linear.UnramifiedLocalRingHom

public import Linear.GoodRationalPointForMap

public import Linear.ProjectiveChartGoodPoint

public import Linear.RationalPointLocalMap

public import Linear.ProjectiveChartLocalParameters

public import Linear.QuotientLocalPullbackComparison

public import Linear.AwayQuotientComparison

public import Linear.ProjectiveAmbientOpenComparison

public import Linear.LocalMapEquivComparison

public import Linear.RationalPointUnramifiedComposition

public import Linear.ProjectiveAmbientUnramifiedPoint

public import Linear.RationalPointLocalization

public import Linear.AffineRationalPointValues

public import Linear.ProjectiveGoodAffineCoordinates

public import Linear.ProjectiveAmbientAtPoint

public import Linear.ProjectiveCoordinateUnramified

public import Linear.ProjectiveSmoothPointParameters

public import Linear.ProjectiveLocalParametersConstructed

public import Linear.FractionModelAlgebraicOpen

public import Linear.ProjectiveTargetGoodOpen

public import Linear.TargetGoodLoci

public import Linear.ProjectiveTargetGoodLoci

public import Linear.HomogeneousMapFinite

public import Linear.ProjectiveConeFinite

public import Linear.FiniteRationalPoints

public import Linear.PolynomialMapFibersFinite

public import Linear.ProjectiveFibersFinite

public import Linear.ProjectiveFiberChartAvoidance

public import Linear.ProjectiveConeChartOpenIntersection

public import Linear.ProjectiveConeChartEvaluation

public import Linear.ProjectiveWholeFiberChart

public import Linear.ProjectiveConeGoodTargetPoint

public import Linear.ProjectiveChartPointEvaluation

public import Linear.ProjectiveWholeFiberGoodPoint

public import Linear.PolynomialFiniteZeroLocus

public import Linear.ProjectiveAffineFiberFinite

public import Linear.ProjectiveAffineFiberUnit

public import Linear.ProjectiveAffineFiberMap

public import Linear.UnramifiedEvaluationQuotient

public import Linear.ProjectiveAffineFiberReduced

public import Linear.ProjectiveNormalizedConePoint

public import Linear.ProjectiveWholeReducedFiber

public import Linear.FiniteReducedAlgebraPoints

public import Linear.PolynomialReducedPointCount

public import Linear.ProjectiveAffineFiberPointEquiv

public import Linear.ProjectiveWholeFiberPointCount

public import Linear.ProjectiveAffineFiberUniversal

public import Linear.ProjectiveAffineFiberTensor

public import Linear.ProjectiveWholeTensorFiber

public import Linear.HomogeneousPullbackComponents

public import Linear.ProjectiveHomogeneousChartAvoidance

public import Linear.ProjectiveGeneralReducedFibers

public import Linear.ProjectiveGeneralTensorFibers

public import Linear.AlgebraicFiniteTypeAway

public import Linear.GenericFreeAway

public import Linear.ProjectiveChartFiniteAway

public import Linear.ProjectiveChartFiniteFree

public import Linear.FreeAwayFiberRank

public import Linear.GenericFiberRankOpen

public import Linear.LocalizedAlgebraFiber

public import Linear.AlgebraicGenericFiberRank

public import Linear.ProjectiveGenericFiberRank

public import Linear.ProjectiveGeneralFiberRank

public import Linear.AwayPullbackFieldDegree

public import Linear.ProjectiveGenericFieldDegree

public import Linear.FieldEndomorphismDegree

public import Linear.ProjectivePullbackComposition

public import Linear.ProjectivePullbackIteration

public import Linear.ProjectiveIteratedWholeFiberDegree

public import Linear.HomogeneousCoordinatePieces

public import Linear.ProjectiveGradedPullback

public import Linear.HomogeneousCoordinateGrading

public import Linear.HilbertFiniteInstances

public import Linear.GradedModuleProjection

public import Linear.GradedModuleFiniteSupport

public import Linear.GradedSubmoduleDecomposition

public import Linear.GradedQuotientDecomposition

public import Linear.GradedSubalgebraDecomposition

public import Linear.GradedScalarExactSequence

public import Linear.GradedScalarInductionModules

public import Linear.GradedHilbertSeriesRecurrence

public import Linear.HomogeneousAdjoinGenerators

public import Linear.GradedHilbertSerre

public import Linear.HomogeneousCoordinateHilbertSeries

public import Linear.HomogeneousCoordinateHilbertPolynomial

public import Linear.HomogeneousCoordinateHilbertPositive

public import Linear.GradedHilbertDegree

public import Linear.HomogeneousCoordinateFiltration

public import Linear.HomogeneousCumulativeHilbert

public import Linear.ProjectiveCoordinateHilbertGrowth

public import Linear.ProjectiveFilteredPullback

public import Linear.ProjectiveFilteredReflection

public import Linear.GradedModuleHomogeneousGenerators

public import Linear.ProjectiveHomogeneousModuleGenerators

public import Linear.GradedGenericHomogeneousBasis

public import Linear.ProjectiveGenericHomogeneousBasis

public import Linear.GenericSpanDenominator

public import Linear.ProjectiveHomogeneousGenericControl

public import Linear.HomogeneousCoordinateComponentProduct

public import Linear.ProjectivePullbackAllComponents

public import Linear.ProjectiveHomogeneousCoefficientBound

public import Linear.ProjectiveFilteredCombination

public import Linear.ProjectiveFilteredUpperBound

public import Linear.ProjectiveGenericGrowthComparison

public import Linear.PolynomialGrowthLimits

public import Linear.PolynomialGrowthRank

public import Linear.ProjectiveGenericGrowthDegree

public import Linear.FractionPullbackFieldDegree

public import Linear.ProjectiveConeFieldGrowthDegree

public import Linear.ProjectiveScalingMap

public import Linear.ProjectiveScalingFixedRatios

public import Linear.ScalingOrbitTranscendental

public import Linear.ProjectiveConeCoordinateTranscendental

public import Linear.ProjectiveConeRatioRatFunc

public import Linear.RatFuncScaledPowerDegree

public import Linear.ProjectiveConePullbackScaling

public import Linear.TranscendentalAdjoinBaseDegree

public import Linear.FieldEndomorphismSimpleImage

public import Linear.ScaledPowerTranscendental

public import Linear.StableFieldImageDegree

public import Linear.FieldEndomorphismRationalDegree

public import Linear.ProjectiveConeDegreeFactor

public import Linear.ProjectiveRatioHilbertDegree

public import Linear.FieldEndomorphismConjugateDegree

public import Linear.ProjectiveChartHilbertDegree

public import Linear.ProjectiveWholeFiberHilbertPower

public import Linear.IntegralKrullDimension

public import Linear.NoetherNormalizationKrull

public import Linear.PolynomialFilteredImage

public import Linear.PolynomialRectangleDimension

public import Linear.BoundedPolynomialCombination

public import Linear.MatrixControlledPolynomialSpan

public import Linear.FiniteNormalizationFilteredBound

public import Linear.QuotientNormalizationFilteredLower

public import Linear.PolynomialGrowthDegreeComparison

public import Linear.QuotientNormalizationFilteredUpper

public import Linear.QuotientHilbertKrullDimension

public import Linear.ProjectiveConeHilbertKrullDimension

public import Linear.NoetherNormalizationTranscendence

public import Linear.FractionFieldTranscendence

public import Linear.ProjectiveChartHilbertKrullDimension

public import Linear.ProjectiveWholeFiberKrullPower

public import Linear.NormalizationDifferentialRank

public import Linear.ProjectiveDifferentialDimension

public import Linear.ProjectiveWholeFiberDimensionParameters

public import Linear.ProjectiveWholeFiberGoodDimension

public import Linear.ProjectiveWholeFiberPointLoci

public import Linear.ProjectiveSmoothCommonDimension

public import Linear.ProjectiveWholeFiberCommonCoordinates

public import Linear.ProjectiveAmbientFiber

public import Linear.ProjectiveFiberHighestRegular

public import Linear.ProjectiveAmbientFiberHighest

public import Linear.ProjectiveAmbientFiberCompleteIntersection

public import Linear.PointLocalPullbackCoordinateComparison

public import Linear.SmoothLinearTargetParameters

public import Linear.ProjectiveSmoothLinearParameters

public import Linear.PolynomialAwayCoordinateEquiv

public import Linear.RationalSourceCoordinateUnramified

public import Linear.ProjectiveTargetNormalCoordinates

public import Linear.RationalLinearTargetCoordinates

public import Linear.RationalLinearNormalSocle

public import Linear.RationalLinearNormalLocalSocle

public import Linear.CenteredTargetNormalCoordinates

public import Linear.ProjectiveCenteredNormalTarget

public import Linear.RationalCoordinateSandwich

public import Linear.RationalTargetCenterUnramified

public import Linear.RationalReindexedSourceCoordinates

public import Linear.PolynomialCoordinatePoints

public import Linear.ProjectiveReindexedRationalInvariance

public import Linear.ProjectiveWholeFiberLocalMaps

public import Linear.ProjectiveCenteredRationalInvariance

public import Linear.RationalReindexedCenteredLocalMap

public import Linear.CenteredCoordinatePointKernel

public import Linear.ProjectiveCenteredFiberLocalMaps

public import Linear.PolynomialEquationCoordinateAlgebra

public import Linear.ProjectiveCenteredFiberAlgebra

public import Linear.ActualCoordinateFiberPoints

public import Linear.ProjectiveOriginalFiberLocalSocle

public import Linear.ProjectiveWholeFiberCommonSocle

public import Linear.ProjectiveCenteredFiberIdeal

public import Linear.ActualEquationMaximalSocles

public import Linear.ProjectiveWholeFiberMaximalSocle

public import Linear.PolynomialLinearHighestComponents

public import Linear.PolynomialCoordinateOrigin

public import Linear.MatrixPolynomialHighest

public import Linear.PolynomialNormalJacobianDegree

public import Linear.ProjectiveCenteredFiberHighest

public import Linear.ProjectiveWholeFiberJacobianSystem

public import Linear.PolynomialReindexResiduePairing

public import Linear.PolynomialZeroLocusResidueRelation

public import Linear.PolynomialCoordinateZeroLocusEquiv

public import Linear.ProjectiveWholeFiberHomogeneousRelation

public import Linear.ProjectiveFiberRepresentativeRelation

public import Linear.HomogeneousLinearNormalization

public import Linear.ProjectiveLinearNormalization

public import Linear.ProjectiveLinearProjectionGoodOpen

public import Linear.ProjectiveLinearProjectionTensorFibers

public import Linear.ProjectiveLinearSectionPointEquiv

public import Linear.LinearProjectionFilteredGrowth

public import Linear.ProjectiveLinearSectionDegree

public import Linear.ProjectiveSimultaneousFiberRelations

public import Linear.ProjectiveSectionDefiningForms

public import Linear.ProjectiveSimultaneousWholePointFibers

public import Linear.ProjectiveActualFamilyRelation

public import Linear.ReducedPolynomialProjectionFibers

public import Linear.ProjectiveLinearSectionEquationFibers

public import Linear.NativeProjectiveChart

public import Linear.NativeProjectiveChartPullback

public import Linear.QuotientClosedBaseChange
public import Linear.NativeProjectiveChartClosedPullback
public import Linear.ProjectiveAffineLinearSection
public import Linear.ProjectiveAffineLinearSectionComparison
public import Linear.NativeProjectiveChartSectionReduced

public import Linear.ReducedClosedBaseChange
public import Linear.ProjectiveAffineFiberClosedPullback
public import Linear.ProjectiveLinearSectionClosedReduced
public import Linear.ProjectiveLinearSectionReducedPullbackOpen
public import Linear.FiniteReducedClosedBaseChange
public import Linear.ProjectiveLinearSectionFinitePullback

public import Linear.HomogeneousCutChartCoverage
public import Linear.ProjectivePulledSectionNativeCoverage
public import Linear.HomogeneousQuotientNativeChart
public import Linear.QuotientAwayAtUnit
public import Linear.ProjectivePulledSectionAffineComparison
public import Linear.ProjectivePulledSectionGlobalReduced

public import Linear.ProjectiveActualFamilyNativeCut

public import Linear.GradedSurjectiveNativeCharts
public import Linear.GradedSurjectiveProjClosed
public import Linear.ProjectivePulledSectionClosedEmbedding
